/**
 * Chapter F1's glossary (plan: docs/roles/proposals/P-F1-story.md §5), in both tracks: `gloss` is one Ground-up
 * sentence (≤ 25 words), `formal` one Formal sentence (≤ 40). Ids start `qc-` (709's namespace). A `bridge` offers the
 * Spin Lab unit that teaches the same idea (content/qc709/bridges.ts). Rides in the lazy course pack (pack.ts).
 *
 * Three of the plan's terms are 448's own glosses instead (qubit, global phase, relative phase): the gloss-at-first-use
 * lint (content/symbols.test.ts) keys those technical words to 448's entries, so F1's prose tags `[[qubit|…]]`,
 * `[[global-phase|…]]` and `[[relative-phase|…]]`, which a 709 page may do.
 */
import type { GlossEntry } from '../schema'

export const GLOSSARY: GlossEntry[] = [
  {
    id: 'qc-number-line',
    term: 'number line',
    gloss: 'The line of ordinary numbers: negatives to the left of zero, positives to the right.',
    formal: 'The real numbers ℝ with their order, drawn as a line.',
    first: 'f1-number-line:b1',
  },
  {
    id: 'qc-real-number',
    term: 'real number',
    gloss: 'Any point on the number line: whole numbers, fractions, and numbers such as √2 that no fraction equals.',
    formal: 'An element of ℝ, the complete ordered field that contains the rational numbers.',
    first: 'f1-number-line:b2',
    bridge: 'qc-l2-complex',
  },
  {
    id: 'qc-imaginary-unit',
    term: 'imaginary unit $i$',
    gloss: 'A number whose square is −1; multiplying by it turns a point a quarter turn about zero.',
    formal: 'The element $i$ of ℂ with $i^2 = -1$; multiplication by $i$ is the rotation of the plane by 90°.',
    first: 'f1-number-line:b4',
    symbols: ['i'],
    bridge: 'qc-l2-complex',
  },
  {
    id: 'qc-complex-plane',
    term: 'complex plane',
    gloss: 'The flat picture of complex numbers: the real part measured across, the imaginary part measured up.',
    formal: 'ℂ identified with ℝ² by sending $z$ to the pair of its real and imaginary parts (the Argand plane).',
    first: 'f1-number-line:b4',
    uses: ['qc-real-part', 'qc-imaginary-part'],
    bridge: 'qc-l2-complex',
  },
  {
    id: 'qc-complex-number',
    term: 'complex number',
    gloss: 'A number $a + bi$ built from two ordinary numbers; it can be drawn as a point in a plane.',
    formal: 'An element $a + bi$ of ℂ, with $a$ and $b$ real (Axler 1.1).',
    first: 'f1-plane:b1',
    bridge: 'qc-l2-complex',
  },
  {
    id: 'qc-real-part',
    term: 'real part',
    gloss: 'In $a + bi$, the ordinary number $a$: how far across the point sits.',
    formal: 'For $z = a + bi$, the real number $\\operatorname{Re} z = a$ (Axler 4.1).',
    first: 'f1-plane:b1',
  },
  {
    id: 'qc-imaginary-part',
    term: 'imaginary part',
    gloss: 'In $a + bi$, the ordinary number $b$ that multiplies $i$: how far up the point sits.',
    formal: 'For $z = a + bi$, the real number $\\operatorname{Im} z = b$; note that it is real, not $bi$ (Axler 4.1).',
    first: 'f1-plane:b1',
  },
  {
    id: 'qc-modulus',
    term: 'modulus (size) $|z|$',
    gloss: 'The size of a complex number: its distance from zero, found by Pythagoras.',
    formal: '$|z| = \\sqrt{zz^*} = \\sqrt{(\\operatorname{Re} z)^2 + (\\operatorname{Im} z)^2}$, which Axler calls the absolute value.',
    first: 'f1-plane:b3',
  },
  {
    id: 'qc-conjugate',
    term: 'complex conjugate $z^*$',
    gloss: 'The mirror image of a complex number in the across axis: $a + bi$ becomes $a - bi$.',
    formal: '$z^* = \\operatorname{Re} z - i\\operatorname{Im} z$, the reflection in the real axis; Axler writes $\\bar z$.',
    first: 'f1-plane:b4',
    bridge: 'qc-l2-complex',
  },
  {
    id: 'qc-triangle-inequality',
    term: 'triangle inequality',
    gloss: 'Two arrows placed tip to tail never reach farther than their two lengths added.',
    formal: '$|z + w| \\le |z| + |w|$, with equality exactly when one number is a nonnegative real multiple of the other.',
    first: 'f1-plane:b6',
  },
  {
    id: 'qc-field',
    term: 'field',
    gloss: 'A number system where adding, subtracting, multiplying and dividing, except by zero, follow the usual rules.',
    formal: 'A commutative ring with $1 \\ne 0$ in which every nonzero element has a multiplicative inverse.',
    first: 'f1-multiply:b1',
  },
  {
    id: 'qc-argument',
    term: 'argument (angle)',
    gloss: 'The angle of a complex number, measured counterclockwise from the positive across axis.',
    formal: 'The angle $\\arg z$ of $z \\ne 0$, defined up to multiples of 360°; the engine returns the principal value in (−180°, 180°].',
    first: 'f1-multiply:b4',
    bridge: 'qc-l2-complex',
  },
  {
    id: 'qc-polar-form',
    term: 'polar form',
    gloss: 'Naming a complex number by its size and its angle instead of by its two parts.',
    formal: '$z = r(\\cos\\varphi + i\\sin\\varphi) = re^{i\\varphi}$ with $r = |z|$ and $\\varphi = \\arg z$.',
    first: 'f1-multiply:b4',
    uses: ['qc-modulus', 'qc-argument'],
    bridge: 'qc-l2-complex',
  },
  {
    id: 'qc-de-moivre',
    term: 'de Moivre’s rule',
    gloss: 'Turning $n$ times by an angle is the same as turning once by $n$ times that angle.',
    formal: '$(\\cos\\varphi + i\\sin\\varphi)^n = \\cos n\\varphi + i\\sin n\\varphi$ for every integer $n$.',
    first: 'f1-multiply:b6',
  },
  {
    id: 'qc-algebraically-closed',
    term: 'algebraically closed',
    gloss: 'Every polynomial equation built from these numbers has a solution among them; the complex numbers are like that.',
    formal: 'Every nonconstant polynomial with coefficients in the field has a zero in it; for ℂ this is the fundamental theorem of algebra (Axler 4.12).',
    first: 'f1-number-line:b7',
  },
  {
    id: 'qc-radian',
    term: 'radian',
    gloss: 'An angle measured by the arc it cuts from a circle of radius 1; a full turn is $2\\pi$.',
    formal: 'The angle that cuts an arc of length 1 on the unit circle, so 360° is $2\\pi$ radians.',
    first: 'f1-euler:b1',
  },
  {
    id: 'qc-unit-circle',
    term: 'unit circle',
    gloss: 'All the complex numbers of size exactly 1.',
    formal: 'The set of $z$ with $|z| = 1$, the group U(1) under multiplication.',
    first: 'f1-euler:b2',
    bridge: 'qc-l2-complex',
  },
  {
    id: 'qc-e',
    term: 'Euler’s number $e$',
    gloss: 'The number, about 2.718, that growth split into ever more tiny steps settles on.',
    formal: '$e = \\lim_{n\\to\\infty}(1 + 1/n)^n$, which also equals the sum of $1/k!$ over all whole numbers $k$.',
    first: 'f1-euler:b3',
    symbols: ['e'],
  },
  {
    id: 'qc-euler-formula',
    term: 'Euler’s formula',
    gloss: '$e^{i\\varphi} = \\cos\\varphi + i\\sin\\varphi$: the point of the unit circle at angle $\\varphi$.',
    formal: 'The identity $e^{i\\varphi} = \\cos\\varphi + i\\sin\\varphi$ for real $\\varphi$, which gives every complex number the exponential form $re^{i\\varphi}$.',
    first: 'f1-euler:b5',
    bridge: 'qc-l2-complex',
  },
  {
    id: 'qc-phasor',
    term: 'phasor',
    gloss: 'A complex number drawn as an arrow, used to add waves by placing arrows tip to tail.',
    formal: 'A complex amplitude $A = |A|e^{i\\varphi}$ standing for an oscillation of size $|A|$ and phase $\\varphi$.',
    first: 'f1-phase:b1',
  },
  {
    id: 'qc-phase',
    term: 'phase',
    gloss: 'The angle of a complex number or of an amplitude.',
    formal: 'The argument of a phasor or amplitude, defined up to multiples of $2\\pi$.',
    first: 'f1-phase:b1',
    bridge: 'qc-l2-complex',
  },
  {
    id: 'qc-interference',
    term: 'interference',
    gloss: 'What happens when arrows add: lined-up arrows reinforce each other and opposite arrows cancel.',
    formal: 'The cross terms of $|\\sum_k A_k|^2 = \\sum_k |A_k|^2 + \\sum_{j \\ne k} A_j^*A_k$.',
    first: 'f1-phase:b2',
  },
  {
    id: 'qc-ray',
    term: 'ray (physical state)',
    gloss: 'All the vectors that differ only by an overall nonzero number; together they are one physical state.',
    formal: 'The set of all nonzero complex multiples of a state vector, one point of projective space.',
    first: 'f1-phase:b3',
    bridge: 'qc-l2-vector-space',
  },
  {
    id: 'qc-amplitude',
    term: 'amplitude',
    gloss: 'One of the complex numbers that describe a quantum state; its size squared is a chance.',
    formal: 'A coefficient of a state in a chosen orthonormal basis; its squared modulus is the probability of that outcome.',
    first: 'f1-phase:b4',
    bridge: 'qc-l1-vectors',
  },
]
