/**
 * Physics 709 chapter F1 "Numbers that turn": complex numbers, their plane, multiplication as stretch-and-turn, e^{iφ},
 * and the phases interference can and cannot see. The first Foundations chapter (no lecture notes: its own line is
 * phase 'core'); sources Axler, Bergou, Nielsen & Chuang and two pages of the 709 notes.
 *
 * Plan: docs/roles/proposals/P-F1-story.md; rulings docs/roles/decisions/qc709-pilots.md (ruling 1: Euler's series
 * proof is 448's homework, hints only here; ruling 5: phase 'core'; ruling 6: `sameAs` on the concept map) and
 * docs/roles/decisions/qc709-nc.md (the N&C addendum). Every number a learner sees is computed in F1.values.ts and
 * asserted in keyed claims (content.test.tsx runs `holds`; claims.test.ts compares each key with its numpy twin in
 * physics/__fixtures__/claims-qc709/f1.json).
 */
import type { Lecture } from '../schema'
import { axler, bergou, nc, notes, F1_STORY } from './F1.story'
import { F1_REVIEW } from './F1.review'
import { V, claim, close, d, pct } from './F1.values'

export const F1: Lecture = {
  id: 'F1',
  number: 1,
  title: 'Numbers that turn',
  outcomes: [
    'Explain why no number on the number line squares to −1, and how a quarter turn supplies one.',
    'Draw a complex number, add two of them, find a size, and mirror a number in the across axis.',
    'Multiply complex numbers, and say why sizes multiply and angles add.',
    'Say what Euler’s formula means, and why half a turn round the unit circle gives −1.',
    'Tell a global phase, which nothing can detect, from a relative phase, which interference shows.',
  ],
  prerequisites: [],
  // Where each symbol is first defined (unit, beat or site id), for the symbol-before-use lint of both tracks.
  // The Formal track meets some letters earlier (symbolsFormal): it names ℂ's parts at f1-number-line:b4, a second
  // number w and the bar z̄ in the conjugate beat, c and d in the addition rule, n in de Moivre's rule.
  symbols: {
    '\\alpha': 'f1-number-line:b6',
    '\\beta': 'f1-number-line:b6',
    '|\\cdot\\rangle': 'f1-number-line:b6',
    '|0\\rangle': 'f1-number-line:b6',
    '|1\\rangle': 'f1-number-line:b6',
    a: 'f1-number-line.play.f1-n-sqrt-i.hints[0]',
    b: 'f1-number-line.play.f1-n-sqrt-i.hints[0]',
    z: 'f1-plane:b1',
    w: 'f1-plane:b6',
    c: 'f1-multiply:b1',
    d: 'f1-multiply:b1',
    r: 'f1-multiply:b4',
    '\\varphi': 'f1-multiply:b4',
    '\\varphi_z': 'f1-multiply:b5',
    '\\varphi_w': 'f1-multiply:b5',
    u: 'f1-multiply:b5',
    v: 'f1-multiply:b5',
    q: 'f1-multiply:b5',
    e: 'f1-euler',
    '\\pi': 'f1-euler:b1',
    n: 'f1-euler:b3',
    '\\delta': 'f1-euler:b4',
    '\\gamma': 'f1-phase:b3',
    A: 'f1-phase:b3',
    B: 'f1-phase:b3',
    a_0: 'f1-phase:b4',
    a_1: 'f1-phase:b4',
    '\\varphi_0': 'f1-phase:b5',
    '\\varphi_1': 'f1-phase:b5',
    T: 'f1-phase.play.f1-ph-pi8.walkthrough[1]',
  },
  symbolsFormal: {
    a: 'f1-number-line:b4',
    b: 'f1-number-line:b4',
    '|+y\\rangle': 'f1-number-line:b6',
    Z: 'f1-number-line:b7',
    S: 'f1-number-line:b7',
    T: 'f1-number-line:b7',
    c: 'f1-plane:b2',
    d: 'f1-plane:b2',
    w: 'f1-plane:b4',
    '\\bar z': 'f1-plane:b4',
    R: 'f1-multiply:b5',
    n: 'f1-multiply:b6',
    f: 'f1-euler:b6',
    A: 'f1-phase:b1',
    A_k: 'f1-phase:b1',
    M: 'f1-phase:b3',
    '\\dagger': 'f1-phase:b3',
    '|\\psi\\rangle': 'f1-phase:b3',
    '\\langle\\cdot|': 'f1-phase:b3',
    '\\phi': 'f1-phase:b4',
    '|+n\\rangle': 'f1-phase:b4',
    P: 'f1-phase:b5',
    '|+z\\rangle': 'f1-phase:b6',
    '|-z\\rangle': 'f1-phase:b6',
    '|+x\\rangle': 'f1-phase:b6',
    '|-x\\rangle': 'f1-phase:b6',
    '\\delta_\\pm': 'f1-phase:b6',
    '\\delta_+': 'f1-phase:b6',
    '\\delta_-': 'f1-phase:b6',
    '\\langle\\cdot|\\cdot\\rangle': 'f1-phase:b6',
    '\\omega': 'f1-phase:b7',
    s: 'f1-phase:b7',
    N: 'f1-phase:b7',
  },
  units: [
    {
      id: 'f1-number-line',
      story: F1_STORY['f1-number-line'],
      review: F1_REVIEW['f1-number-line'],
      title: 'The gap that x² = −1 leaves',
      question: 'Which equations can ordinary numbers not solve, and what new number fills the last gap?',
      lecture: {
        pages: 'Axler pp. 2–3, 125; Bergou p. 1',
        summary: 'Negatives, fractions and roots each forced a new kind of number. The square root of −1 forces the last one, a quarter turn.',
      },
      books: [
        axler('§1A, 1.1–1.2, pp. 2–3', 'Complex numbers as a real part plus a real multiple of a new number whose square is −1, and the product rule that follows.'),
        axler('Ch. 4, 4.12, p. 125','The fundamental theorem of algebra: every nonconstant polynomial has a complex zero, so no further numbers are needed.'),
        bergou('§1.1, p. 1 (eq. 1.1)', 'Why physics cares: a qubit is described by two complex amplitudes.'),
      ],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'powers-of-i' },
        tryThis: [
          'Press “Multiply by i” twice: where does 1 land?',
          'Press it twice more: why are you back at 1?',
          'How many presses give $i^{2026}$? Only the remainder after dividing by 4 matters.',
        ],
      },
      clues: [],
      insight: 'No ordinary number squares to $-1$, so we add $i$, a quarter turn; with it, every square root exists.',
      insightFormal: 'Adjoining $i$ with $i^2 = -1$ gives ℂ, where multiplication by $i$ is the rotation by 90° and every nonconstant polynomial has a zero.',
      play: [
        {
          id: 'f1-n-power',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Powers of i repeat',
          prompt: 'What is $i^{2026}$? It is an ordinary number.',
          answer: V.f1IPow2026,
          tolerance: 0,
          hints: [
            { text: 'Powers of $i$ repeat.' },
            { text: 'Since $i^4 = 1$, only the remainder of 2026 divided by 4 matters.' },
            { text: '$2026 = 4 \\times 506 + 2$.' },
          ],
          walkthrough: [
            { text: '$i^{2026} = (i^4)^{506}\\,i^2 = 1 \\cdot (-1) = -1$.' },
            { text: 'In Formal terms: $i$ has order 4 among the numbers of size 1, and 2026 leaves remainder 2 on division by 4.' },
          ],
        },
        {
          id: 'f1-n-roots4',
          kind: 'choice',
          tier: 'core',
          title: 'Two square roots',
          prompt: 'Which pair of numbers both square to $-4$?',
          options: [
            { text: '2 and $-2$', correct: false, why: 'Real squares are never negative: $2^2$ and $(-2)^2$ are both $+4$.' },
            { text: '$4i$ and $-4i$', correct: false, why: `Too big: $(4i)^2 = -${d(V.f1Sq4iNeg, 0)}$.` },
            { text: '$2i$ and $-2i$', correct: true, why: 'Right: $(2i)^2 = 4i^2 = -4$, and $(-2i)^2$ is the same.' },
            { text: 'There is no such number.', correct: false, why: 'Not among ordinary numbers, but $2i$ and $-2i$ both work.' },
          ],
          hints: [{ text: 'Real squares are never negative.' }, { text: 'Split $-4$ as $4 \\times (-1)$.' }, { text: 'Take a square root of each factor.' }],
          walkthrough: [{ text: '$(2i)^2 = 4i^2 = -4$, and $(-2i)^2 = 4i^2 = -4$ as well.' }, { text: `By contrast $(4i)^2 = -${d(V.f1Sq4iNeg, 0)}$ and $2^2 = +4$.` }],
        },
        {
          id: 'f1-n-quadratic',
          kind: 'numeric',
          tier: 'core',
          title: 'A quadratic with no real root',
          prompt: '$x^2 + 9 = 0$ has two roots. What is the imaginary part of the one above the across axis?',
          answer: V.f1SqrtM9,
          tolerance: 0.001,
          hints: [{ text: 'Move 9 to the other side.' }, { text: '$x^2 = -9 = 9 \\times (-1)$.' }, { text: 'The roots are $\\pm 3i$.' }],
          walkthrough: [{ text: 'The roots are $x = \\pm 3i$. The one above the axis is $3i$, whose imaginary part is 3.' }],
        },
        {
          id: 'f1-n-sqrt-i',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A square root of i',
          prompt: 'Find a number whose square is $i$. What is its real part? Take the root whose parts are positive.',
          answer: V.f1SqrtIRe,
          tolerance: 0.005,
          hints: [
            { text: 'Write the unknown as $a + bi$, with $a$ and $b$ ordinary numbers.' },
            { text: 'Square it and match the parts: $a^2 - b^2 = 0$ and $2ab = 1$.' },
            { text: 'So $a = b$ and $2a^2 = 1$.' },
          ],
          walkthrough: [
            { text: `$a = b = 1/\\sqrt2 = ${d(V.f1SqrtIRe)}$.` },
            { text: 'In Formal terms: $x^2 = i$ has the roots $\\pm(1 + i)/\\sqrt2$, and ℂ is algebraically closed (Axler, p. 125).' },
          ],
        },
      ],
    },
    {
      id: 'f1-plane',
      story: F1_STORY['f1-plane'],
      review: F1_REVIEW['f1-plane'],
      title: 'Numbers as points and arrows',
      question: 'How do we draw, add, measure and mirror a complex number?',
      lecture: {
        pages: 'Axler pp. 2, 120–121',
        summary: 'A complex number is a point of the plane. Its parts are its coordinates, its size is a distance, and its conjugate is a mirror image.',
      },
      books: [
        axler('§1A, 1.1, p. 2', 'Addition part by part, and the rules it obeys.'),
        axler('Ch. 4, 4.1–4.4, pp. 120–121','Real and imaginary parts, the conjugate and the absolute value, with the rules they obey.'),
      ],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'conjugate', z: [1.2, 0.9] },
        tryThis: [
          'Drag $z$ around: its mirror $z^*$ follows on the other side of the across axis.',
          'Read $z^*z$ in the table: it is always a plain number that is never negative, the size squared.',
          'Drag $z$ onto the across axis, then onto the up axis. Where is $z^*$ each time?',
        ],
      },
      clues: [],
      insight: 'A complex number is a point and an arrow: add tip to tail, measure by Pythagoras, mirror in the across axis.',
      insightFormal: 'ℂ is the plane ℝ² with componentwise addition, the Euclidean modulus and conjugation as a reflection, tied together by $zz^* = |z|^2$.',
      play: [
        {
          id: 'f1-p-modulus',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A size by Pythagoras',
          prompt: 'What is $|-5 + 12i|$?',
          answer: V.f1Abs512,
          tolerance: 0,
          hints: [{ text: 'The size is the distance from zero.' }, { text: 'Use $\\sqrt{a^2 + b^2}$.' }, { text: '$25 + 144 = 169$.' }],
          walkthrough: [{ text: '$\\sqrt{169} = 13$. The minus sign does not matter, because it is squared.' }],
        },
        {
          id: 'f1-p-sum-size',
          kind: 'numeric',
          tier: 'core',
          title: 'Add, then measure',
          prompt: 'What is the size of $(3 + 4i) + (1 - 2i)$?',
          answer: V.f1AbsSum,
          tolerance: 0.005,
          hints: [{ text: 'Add first, then measure.' }, { text: 'The sum is $4 + 2i$.' }, { text: 'Its size is $\\sqrt{16 + 4}$.' }],
          walkthrough: [{ text: `$\\sqrt{20} = ${d(V.f1AbsSum)}$, which is less than $5 + ${d(V.f1Abs1m2)}$: the triangle inequality.` }],
        },
        {
          id: 'f1-p-zzstar',
          kind: 'numeric',
          tier: 'core',
          title: 'A number times its mirror',
          prompt: 'Compute $(2 - 3i)(2 + 3i)$.',
          answer: V.f1Prod23,
          tolerance: 0,
          hints: [{ text: 'These two numbers are mirrors of each other.' }, { text: 'A number times its mirror is its size squared.' }, { text: 'So the answer is $4 + 9$.' }],
          walkthrough: [{ text: '$4 + 6i - 6i - 9i^2 = 4 + 9 = 13$, a plain number with no $i$.' }],
        },
        {
          id: 'f1-p-triangle-equal',
          kind: 'choice',
          tier: 'stretch',
          title: 'When the sides add up',
          prompt: 'For which pair is $|z + w| = |z| + |w|$?',
          options: [
            { text: '1 and $i$', correct: false, why: `$|1 + i| = ${d(V.f1Abs11)}$, less than 2: the arrows point different ways.` },
            { text: '1 and $-1$', correct: false, why: 'Their sum is 0, far less than 2.' },
            { text: '$2 + 2i$ and $1 + i$', correct: true, why: 'Right: both point at 45°, so their lengths add.' },
            { text: '$i$ and $2$', correct: false, why: 'At right angles, so the sum is shorter than the two lengths added.' },
          ],
          hints: [{ text: 'When are two arrows, tip to tail, as long as their lengths added?' }, { text: 'They must point the same way.' }, { text: 'Compare the angles.' }],
          walkthrough: [
            { text: `Both $2 + 2i$ and $1 + i$ point at 45°, so $|3 + 3i| = ${d(V.f1Abs33)}$ equals $${d(V.f1Abs22)} + ${d(V.f1Abs11)}$.` },
            { text: 'In Formal terms: equality holds exactly when one number is a nonnegative real multiple of the other.' },
          ],
        },
      ],
    },
    {
      id: 'f1-multiply',
      story: F1_STORY['f1-multiply'],
      review: F1_REVIEW['f1-multiply'],
      title: 'Multiplying stretches and turns',
      question: 'What does multiplying two complex numbers do to their arrows?',
      lecture: {
        pages: 'Axler pp. 2–4, 121; N&C p. 85',
        summary: 'Multiplication follows from the bracket rules and one new fact about the square of the new number. Sizes multiply and angles add.',
      },
      books: [
        axler('§1A, 1.1–1.5, pp. 2–4', 'Multiplication, its rules, and the inverse of every nonzero number.'),
        axler('Ch. 4, 4.4, p. 121','The absolute value of a product is the product of the absolute values.'),
        nc('p. 85', 'Multipliers of size 1 are pure phases: the idea behind splitting a number into its size and a direction.'),
      ],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'multiply', z: [1, 0.5], w: [0, 1] },
        tryThis: [
          'With $w = i$, drag $z$: the product $zw$ is $z$ turned 90°, with its size kept.',
          'Drag $w$ to 2 on the across axis: now the product is a pure stretch.',
          'Put $w$ anywhere on the unit circle: $zw$ only turns. Read the angles in the table and check that they add.',
        ],
      },
      clues: [],
      insight: 'Multiplying multiplies sizes and adds angles, so a number of size 1 only turns.',
      insightFormal: 'In polar form $zw = |z||w|[\\cos(\\arg z + \\arg w) + i\\sin(\\arg z + \\arg w)]$: moduli multiply and arguments add, so the unit circle acts by rotations.',
      play: [
        {
          id: 'f1-m-product',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Multiply out',
          prompt: 'What is the imaginary part of $(2 + i)(1 + 3i)$?',
          answer: V.f1ProdIm,
          tolerance: 0,
          hints: [{ text: 'Multiply out all four pairs.' }, { text: 'Replace $i^2$ by $-1$.' }, { text: 'The terms with $i$ are $6i$ and $i$.' }],
          walkthrough: [{ text: '$2 + 6i + i + 3i^2 = -1 + 7i$, so the imaginary part is 7.' }],
        },
        {
          id: 'f1-m-angle',
          kind: 'numeric',
          tier: 'core',
          title: 'Angles add',
          prompt: 'What is the angle of $(1 + i)(1 + \\sqrt3\\,i)$, in degrees?',
          answer: V.f1Angle105Deg,
          tolerance: 0.5,
          unit: '°',
          hints: [{ text: 'Angles add when you multiply.' }, { text: '$1 + i$ is at 45°.' }, { text: '$1 + \\sqrt3\\,i$ is at 60°, because $\\tan 60^\\circ = \\sqrt3$.' }],
          walkthrough: [{ text: `45° + 60° = 105°. Bonus: the size is $\\sqrt2 \\times 2 = ${d(V.f1Abs105)}$.` }],
        },
        {
          id: 'f1-m-power4',
          kind: 'numeric',
          tier: 'core',
          title: 'A fourth power',
          prompt: 'What is $(1 + i)^4$? It is an ordinary number.',
          answer: V.f1OnePlusI4,
          tolerance: 0,
          hints: [{ text: 'Use size and angle.' }, { text: 'The size is $\\sqrt2$ and the angle 45°.' }, { text: 'Four copies: size 4, angle 180°.' }],
          walkthrough: [{ text: '$(\\sqrt2)^4 = 4$, at 180°, is $-4$.' }, { text: 'Check: $(1 + i)^2 = 2i$ and $(2i)^2 = -4$.' }],
        },
        {
          id: 'f1-m-inverse',
          kind: 'numeric',
          tier: 'stretch',
          title: 'One over a complex number',
          prompt: 'What is the real part of $1/(3 + 4i)$?',
          answer: V.f1Inv34Re,
          tolerance: 0.005,
          hints: [
            { text: 'Multiply top and bottom by the mirror of the bottom.' },
            { text: 'The bottom becomes $|3 + 4i|^2 = 25$.' },
            { text: 'The top becomes $3 - 4i$.' },
          ],
          walkthrough: [{ text: `$(3 - 4i)/25 = ${d(V.f1Inv34Re, 2)} - ${d(V.f1Inv34ImNeg, 2)}i$.` }, { text: 'In Formal terms: $z^{-1} = z^*/|z|^2$.' }],
        },
        {
          id: 'f1-m-proof-order',
          kind: 'order',
          tier: 'stretch',
          title: 'Why sizes multiply',
          prompt: 'Put the proof that sizes multiply in order.',
          steps: [
            'Write $zw = (ac - bd) + (ad + bc)i$.',
            'Square both parts and add them.',
            'The cross terms $-2abcd$ and $+2abcd$ cancel.',
            'Factor into $(a^2 + b^2)(c^2 + d^2)$.',
            'Take square roots: $|zw| = |z||w|$.',
          ],
          hints: [{ text: 'Start from the product rule.' }, { text: 'Use Pythagoras on the product.' }, { text: 'Look for two terms that cancel.' }],
          walkthrough: [{ text: 'This is the Ground-up derivation of the sizes beat: product rule, Pythagoras, cancel, factor, square root.' }],
        },
      ],
    },
    {
      id: 'f1-euler',
      story: F1_STORY['f1-euler'],
      review: F1_REVIEW['f1-euler'],
      title: 'eⁱᵠ: walking round the unit circle',
      question: 'Why does $e$, the number of compound growth, raised to an imaginary power walk round a circle?',
      lecture: {
        pages: 'Bergou p. 2; 709 notes p. 12; N&C pp. 15, 71, 207',
        summary: 'Growth split into many tiny steps defines the exponential. At an imaginary rate each tiny step is a turn, so the steps walk round the unit circle.',
      },
      books: [
        bergou('§1.1, p. 2 (eq. 1.2)', 'A qubit’s Bloch form carries $e^{i\\varphi}$ on its second amplitude.'),
        notes('709 notes p. 12 (eq. 1.4)', 'The state along a general direction uses the same $e^{i\\varphi}$.'),
        nc('Ex. 2.18, p. 71', 'The eigenvalues of a unitary matrix have size 1: they are numbers $e^{i\\varphi}$ on this unit circle.'),
        nc('Thm 4.3, p. 207', 'The Trotter formula: the same many-small-steps limit, for matrices (Chapter Q19).'),
      ],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'euler', phi: 180, n: 4 },
        tryThis: [
          'With φ at 180°, raise $n$ from 1 to 64 and watch the end point close in on −1.',
          'Set φ to 90°: where does the polygon close?',
          'Why does $n = 2$ overshoot so far? Compare with the clue above.',
        ],
      },
      clues: [],
      insight: 'Many tiny turns with almost no stretch add up to $e^{i\\varphi} = \\cos\\varphi + i\\sin\\varphi$, the point at angle $\\varphi$ on the unit circle.',
      insightFormal: '$e^{i\\varphi} = \\lim_{n\\to\\infty}(1 + i\\varphi/n)^n = \\cos\\varphi + i\\sin\\varphi$, the unit-speed solution of $f\' = if$ with $f(0) = 1$; so every nonzero number is $re^{i\\varphi}$.',
      play: [
        {
          id: 'f1-e-radians',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Degrees to radians',
          prompt: 'How many radians is 60°?',
          answer: V.f1Rad60,
          tolerance: 0.005,
          unit: 'rad',
          hints: [{ text: '180° is $\\pi$ radians.' }, { text: '60° is a third of 180°.' }, { text: 'So it is $\\pi/3$.' }],
          walkthrough: [{ text: `$\\pi/3 = ${d(V.f1Rad60)}$.` }],
        },
        {
          id: 'f1-e-euler-pi',
          kind: 'numeric',
          tier: 'core',
          title: 'Half a turn',
          prompt: 'What is $e^{i\\pi} + 1$?',
          answer: V.f1EulerPlusOne,
          tolerance: 1e-9,
          hints: [{ text: 'Where is the angle $\\pi$ on the unit circle?' }, { text: 'Halfway round.' }, { text: '$e^{i\\pi} = -1$.' }],
          walkthrough: [{ text: '$\\cos\\pi + i\\sin\\pi = -1$, so the sum is 0.' }],
        },
        {
          id: 'f1-e-cos75',
          kind: 'numeric',
          tier: 'core',
          title: 'A cosine from a product',
          prompt: 'Use $e^{i75^\\circ} = e^{i45^\\circ}\\,e^{i30^\\circ}$ to find $\\cos 75^\\circ$.',
          answer: V.f1Cos75,
          tolerance: 0.005,
          hints: [
            { text: 'Multiply out the two numbers of size 1.' },
            { text: 'The real part is $\\cos 45^\\circ\\cos 30^\\circ - \\sin 45^\\circ\\sin 30^\\circ$.' },
            { text: 'That is $\\tfrac{\\sqrt2}{2}\\cdot\\tfrac{\\sqrt3}{2} - \\tfrac{\\sqrt2}{2}\\cdot\\tfrac12$.' },
          ],
          walkthrough: [{ text: `$(\\sqrt6 - \\sqrt2)/4 = ${d(V.f1Cos75, 4)}$. This is the angle-addition rule read backwards.` }],
        },
        {
          id: 'f1-e-limit-size',
          kind: 'numeric',
          tier: 'stretch',
          title: 'How far off the circle?',
          prompt: 'What is the size of $(1 + i\\pi/100)^{100}$?',
          answer: V.f1Euler100Abs,
          tolerance: 0.005,
          hints: [{ text: 'Sizes multiply.' }, { text: 'One step has size $\\sqrt{1 + \\pi^2/10^4}$.' }, { text: 'Raise it to the 100th power.' }],
          walkthrough: [
            { text: `$(1 + \\pi^2/10^4)^{50} = ${d(V.f1Euler100Abs, 4)}$: still about ${pct(V.f1Euler100Abs - 1)} off the circle, which is why the definition needs $n \\to \\infty$.` },
          ],
        },
        {
          // ruling 1 (qc709-pilots.md): the series proof of Euler's formula is 448's assigned homework (L2 p. 7), so it
          // ships hints only here too; F1 proves the formula by the limit and by the velocity instead
          id: 'f1-e-series',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Euler’s formula from a series',
          prompt: 'Show that $e^{i\\varphi} = \\cos\\varphi + i\\sin\\varphi$ from the power series of $e^x$. Then check: what ordinary number is $e^{i\\pi}$?',
          answer: V.f1ExpiPiRe,
          tolerance: 0.001,
          assigned: '448 L2 p.7',
          hints: [
            { text: 'Which infinite sum defines $e^x$?' },
            { text: 'Put $x = i\\varphi$ and simplify each power of $i$.' },
            { text: 'Group the terms with no $i$ and those with one $i$, and compare them with sums you know.' },
          ],
          walkthrough: [],
        },
      ],
    },
    {
      id: 'f1-phase',
      story: F1_STORY['f1-phase'],
      review: F1_REVIEW['f1-phase'],
      title: 'Phases you can and cannot see',
      question: 'When arrows add, why does only the difference of their angles matter?',
      lecture: {
        pages: 'Bergou pp. 7–8; 709 notes pp. 7, 12; N&C pp. 93, 174',
        summary: 'Arrows added tip to tail interfere. A common turn of every arrow changes nothing measurable, while a turn of one arrow changes the sum.',
      },
      books: [
        bergou('§1.5, pp. 7–8 (eq. 1.18)', 'An interferometer whose output chances depend only on the difference of two path phases.'),
        notes('709 notes p. 7', 'The states along $\\pm x$ differ only in the phase of their second amplitude.'),
        nc('§2.2.7, p. 93', 'Global and relative phase side by side; a relative phase depends on the basis, a global one never shows.'),
        nc('§4.2, p. 174 (eq. 4.3)', 'The T gate (N&C: π/8 gate) is a global phase times a symmetric phase matrix, which is where π/8 in its name comes from.'),
      ],
      visual: {
        kind: 'phase-dial',
        props: { theta: 0, rotations: false },
        tryThis: [
          'Turn both amplitudes together: the point on the circle stays put.',
          'Now turn only the second amplitude: the point moves.',
          'Stop the relative phase at 180°. Up to a global phase, which state is that?',
        ],
      },
      clues: [],
      insight: 'Only the angle between arrows changes their sum: a common turn is invisible, a relative turn is physics.',
      insightFormal: 'Observables depend on phase differences only: a global phase $e^{i\\gamma}$ is unobservable, so states are rays, while a relative phase sets interference and the Bloch longitude.',
      claims: [
        claim('f1Pi8', 'turning 0° and 45° back by 22.5° makes them ±22.5°', () => close(V.f1Pi8, 22.5)),
        claim('f1TGlobal', 'T = e^{iπ/8} R_z(π/4) (qc/gates.ts)', () => V.f1TGlobal === 1),
        claim('f1GlobalI', 'i|+x⟩ is the same physical state as |+x⟩', () => V.f1GlobalI === 1),
        claim('f1SizeOne', 'two unit arrows 120° apart add to size 1', () => close(V.f1SizeOne, 1) && close(V.f1SizeOneDeg, 120)),
      ],
      play: [
        {
          id: 'f1-ph-cancel',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Opposite arrows',
          prompt: 'What is $|1 + e^{i\\pi}|$?',
          answer: V.f1Cancel,
          tolerance: 1e-9,
          hints: [{ text: 'Where does $e^{i\\pi}$ point?' }, { text: 'Opposite to 1.' }, { text: 'Opposite arrows of equal size cancel.' }],
          walkthrough: [{ text: '$1 + (-1) = 0$.' }],
        },
        {
          id: 'f1-ph-quarter',
          kind: 'numeric',
          tier: 'core',
          title: 'Arrows at right angles',
          prompt: 'What is $|1 + e^{i\\pi/2}|^2$?',
          answer: V.f1Interf90,
          tolerance: 0.005,
          hints: [{ text: 'Use $2 + 2\\cos\\varphi$.' }, { text: '$\\cos 90^\\circ = 0$.' }, { text: 'Or compute $|1 + i|^2$.' }],
          walkthrough: [{ text: '$2 + 0 = 2$. The arrows are at right angles, so Pythagoras gives $1 + 1$.' }],
        },
        {
          id: 'f1-ph-size-one',
          kind: 'numeric',
          tier: 'core',
          title: 'A sum of size 1',
          prompt: 'Two arrows of size 1 add up to an arrow of size 1. What is the angle between them, in degrees from 0 to 180?',
          answer: V.f1SizeOneDeg,
          tolerance: 0.5,
          unit: '°',
          hints: [{ text: 'The size squared is $2 + 2\\cos\\varphi$.' }, { text: 'Set it equal to 1.' }, { text: 'Then $\\cos\\varphi = -\\tfrac12$.' }],
          walkthrough: [{ text: 'The angle is 120°: then the two arrows and their sum form an equal-sided triangle.' }],
        },
        {
          id: 'f1-ph-detect',
          kind: 'choice',
          tier: 'core',
          title: 'Which change shows?',
          prompt: 'A qubit’s amplitudes are $1/\\sqrt2$ and $1/\\sqrt2$. Which change could a measurement ever detect?',
          options: [
            { text: 'Multiply both by $i$', correct: false, why: 'Both arrows turn together: a global phase, which nothing detects.' },
            { text: 'Multiply both by $-1$', correct: false, why: 'Also a common turn, by half a turn: nothing changes.' },
            { text: 'Multiply only the second by $-1$', correct: true, why: 'Right: that is a relative phase of $\\pi$, which makes a different state, the one along $-x$.' },
            { text: 'Multiply both by $e^{0.3i}$', correct: false, why: 'A common turn by 0.3 radians: still a global phase.' },
          ],
          hints: [{ text: 'Which changes turn every arrow together?' }, { text: 'A common turn is a global phase.' }, { text: 'Only a relative phase changes interference.' }],
          walkthrough: [
            { text: 'The first, second and fourth changes turn both arrows together: global phases.' },
            { text: 'The third turns only one amplitude, a relative phase of $\\pi$: it makes a different state, the notes’ second state with $\\delta = \\pi$.' },
            { text: 'In Formal terms: only the ray matters.' },
          ],
        },
        {
          id: 'f1-ph-mz',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Bergou’s interferometer',
          prompt:
            'In Bergou’s interferometer the phases are $\\varphi_0 = 0$ and $\\varphi_1 = 90^\\circ$. What is the probability at the exit that collects $(e^{i\\varphi_0} + e^{i\\varphi_1})/2$?',
          answer: V.f1Mz90,
          tolerance: 0.005,
          unit: 'probability',
          hints: [{ text: 'Add the two arrows of size ½.' }, { text: 'Their angle difference is 90°.' }, { text: 'Use $[1 + \\cos(\\varphi_1 - \\varphi_0)]/2$.' }],
          walkthrough: [
            { text: `$[1 + \\cos 90^\\circ]/2 = ${d(V.f1Mz90, 1)}$.` },
            { text: 'In Formal terms: Bergou’s eq. 1.18 depends only on $\\varphi_1 - \\varphi_0$ (p. 8).' },
          ],
        },
        {
          // N&C addendum §3.3 (qc709-nc.md): N&C Ex. 4.3 is assigned on no sheet, so its walkthrough ships (marked ⚑)
          id: 'f1-ph-pi8',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Equal and opposite',
          prompt: 'Two arrows of size 1 point at 0° and 45°. Turn both back by the same angle until they point at equal and opposite angles. By how many degrees?',
          answer: V.f1Pi8,
          tolerance: 0.05,
          unit: '°',
          hints: [{ text: 'A common turn changes nothing measurable.' }, { text: 'The two angles must average to zero.' }, { text: 'Halve 45°.' }],
          walkthrough: [
            { text: `They end at $+${d(V.f1Pi8, 1)}^\\circ$ and $-${d(V.f1Pi8, 1)}^\\circ$: halve 45° and turn both back by that much.` },
            {
              text: 'In Formal terms (N&C ⚑ Ex. 4.3, p. 175): the phase gate $T$ (N&C: π/8 gate) multiplies the $|1\\rangle$ amplitude by $e^{i\\pi/4}$. It equals $e^{i\\pi/8}$ times $\\mathrm{diag}(e^{-i\\pi/8}, e^{i\\pi/8})$, a global phase times this symmetric pair, hence π/8 in its name.',
            },
          ],
        },
      ],
    },
  ],
}
