/**
 * Physics 709 chapter F2 "Vectors and inner products": the complex vector space ℂⁿ, the inner product ⟨α|β⟩, norm,
 * orthogonality, orthonormal bases and components, and Gram–Schmidt. The second Foundations chapter (no lecture
 * notes: its own line is phase 'core'); sources Axler, Nielsen & Chuang and the 709 notes. Bridges to F1 for complex
 * numbers; does not re-teach it. The canonical owner of ℂⁿ, ⟨·|·⟩, norm, orthonormality and Gram–Schmidt — the
 * already-built Q1–Q3 keep their own inline teaching of these ideas (ownership rule: a later wiring pass adds
 * Q→F bridges; this build does not touch the Q chapters).
 *
 * Plan: docs/roles/proposals/P-F2-story.md; rulings docs/roles/decisions/qc709-foundations.md,
 * qc709-foundations-rulings.md (every §12 recommendation accepted, including: 709 HW1 is submitted
 * (docs/roles/decisions/homework-status.md), so `f2-gs-spin1` ships a full walkthrough, not hints-only).
 * Every number a learner sees is computed in F2.values.ts and asserted in keyed claims (content.test.tsx runs
 * `holds`; claims.test.ts compares each key with its numpy twin in physics/__fixtures__/claims-qc709/f2.json).
 */
import type { Lecture } from '../schema'
import { F2_STORY } from './F2.story'
import { F2_REVIEW } from './F2.review'
import { V, claim, close } from './F2.values'

export const F2: Lecture = {
  id: 'F2',
  number: 2,
  title: 'Vectors and inner products',
  outcomes: [
    'Say what ℂⁿ is: lists of complex numbers you can add and scale, and write a spin as a ket built from two complex numbers.',
    'Form the inner product of two kets, and explain why the bra’s numbers are conjugated.',
    'Find a state’s length, tell when two states are orthogonal, and compute the angle between two real states.',
    'Read a state’s coordinates off an orthonormal frame as inner products, and check them with Parseval’s sum.',
    'Turn any independent set into an orthonormal frame by Gram–Schmidt, subtracting shadows and normalizing.',
  ],
  prerequisites: ['qc-imaginary-unit', 'qc-complex-plane', 'qc-complex-multiply'],
  // Every entry here is the EXACT string content/walk.ts `texSymbols`/`requiredSymbols` extracts (not the author's own
  // notation): a letter already used with a different meaning earlier in the SAME unit (e.g. e, c, c_1) is registered
  // once, at its own first appearance; a later unit's different use of the same bare letter piggybacks on it, as the
  // symbol-before-use lint is a mechanical, per-string check, not a per-meaning one.
  symbols: {
    '|\\cdot\\rangle': 'f2-vectors',
    '|\\psi\\rangle': 'f2-vectors',
    '|0\\rangle': 'f2-vectors',
    '|1\\rangle': 'f2-vectors',
    '\\alpha': 'f2-vectors',
    '\\beta': 'f2-vectors',
    '|\\alpha\\rangle': 'f2-vectors',
    '|\\beta\\rangle': 'f2-vectors',
    '|+z\\rangle': 'f2-vectors',
    '|-z\\rangle': 'f2-vectors',
    '|+x\\rangle': 'f2-vectors',
    '|-x\\rangle': 'f2-vectors',
    '\\mathbb': 'f2-vectors',
    C: 'f2-vectors',
    R: 'f2-vectors',
    n: 'f2-vectors',
    i: 'f2-vectors',
    '\\mathsf': 'f2-vectors',
    T: 'f2-vectors',
    '|\\psi_1\\rangle': 'f2-vectors',
    '|\\psi_2\\rangle': 'f2-vectors',
    c_1: 'f2-vectors',
    c_2: 'f2-vectors',
    V: 'f2-vectors',
    a_1: 'f2-vectors',
    a_2: 'f2-vectors',
    '\\dim': 'f2-vectors',
    b_1: 'f2-inner-product',
    z: 'f2-inner-product',
    b_2: 'f2-inner-product',
    a_i: 'f2-inner-product',
    b_i: 'f2-inner-product',
    '|+y\\rangle': 'f2-inner-product',
    '\\textstyle': 'f2-inner-product',
    M: 'f2-inner-product',
    '\\dagger': 'f2-inner-product',
    c_i: 'f2-inner-product',
    I: 'f2-inner-product',
    '\\langle\\cdot|\\cdot\\rangle': 'f2-inner-product',
    '\\langle\\cdot|': 'f2-inner-product',
    '\\langle\\cdot\\rangle': 'f2-inner-product',
    '|\\,c_1\\beta+c_2\\gamma\\rangle': 'f2-inner-product',
    '|c_1\\beta+c_2\\gamma\\rangle': 'f2-inner-product',
    '|\\gamma\\rangle': 'f2-inner-product',
    u: 'f2-inner-product',
    v: 'f2-inner-product',
    '|v\\rangle': 'f2-inner-product',
    '|u\\rangle': 'f2-inner-product',
    '\\theta': 'f2-norm-angle',
    '\\psi': 'f2-norm-angle',
    a: 'f2-norm-angle',
    b: 'f2-norm-angle',
    '\\lambda': 'f2-norm-angle',
    '\\perp': 'f2-norm-angle',
    e: 'f2-norm-angle',
    '|e\\rangle': 'f2-norm-angle',
    '\\arccos': 'f2-norm-angle',
    '\\pi': 'f2-norm-angle',
    w: 'f2-norm-angle',
    '|w\\rangle': 'f2-norm-angle',
    c: 'f2-norm-angle',
    '\\iff': 'f2-norm-angle',
    '|e_i\\rangle': 'f2-orthonormal',
    '|e_j\\rangle': 'f2-orthonormal',
    '\\delta_ij': 'f2-orthonormal',
    j: 'f2-orthonormal',
    c_0: 'f2-orthonormal',
    '|e_0\\rangle': 'f2-orthonormal',
    '|e_1\\rangle': 'f2-orthonormal',
    '|\\alpha_i\\rangle': 'f2-orthonormal',
    "|e'_i\\rangle": 'f2-orthonormal',
    'd_+': 'f2-orthonormal',
    'd_-': 'f2-orthonormal',
    '|e_2\\rangle': 'f2-orthonormal',
    '|\\alpha_k\\rangle': 'f2-orthonormal',
    e_1: 'f2-gram-schmidt',
    e_2: 'f2-gram-schmidt',
    f_k: 'f2-gram-schmidt',
    f_j: 'f2-gram-schmidt',
    v_k: 'f2-gram-schmidt',
    '|f_j\\rangle': 'f2-gram-schmidt',
    '|v_k\\rangle': 'f2-gram-schmidt',
    v_1: 'f2-gram-schmidt',
    v_2: 'f2-gram-schmidt',
    '|v_2\\rangle': 'f2-gram-schmidt',
    f_2: 'f2-gram-schmidt',
    e_k: 'f2-gram-schmidt',
    '\\xrightarrow': 'f2-gram-schmidt',
    '|+1z\\rangle': 'f2-gram-schmidt',
    '|+1x\\rangle': 'f2-gram-schmidt',
    '|-1x\\rangle': 'f2-gram-schmidt',
    '|\\chi\\rangle': 'f2-gram-schmidt',
    S_x: 'f2-gram-schmidt',
    '\\hbar': 'f2-gram-schmidt',
  },
  units: [
    {
      id: 'f2-vectors',
      story: F2_STORY['f2-vectors'],
      review: F2_REVIEW['f2-vectors'],
      title: 'Lists you can add: ℂⁿ and kets',
      question: 'What is a state you can add and scale, and why complex entries?',
      lecture: {
        pages: 'Axler §1A pp. 4–7, §1B pp. 12–13; notes n1 pp. 3–4; N&C §2.1.1 p. 62',
        summary: 'A quantum state is a ket, a short list of complex numbers. The lists add and scale by the usual vector-space rules, and a spin needs exactly two of them.',
      },
      books: [
        { source: 'axler', where: '§1A, pp. 4–7', adds: '$\\mathbb R^n$ and $\\mathbb C^n$ as lists, componentwise addition and scalar multiplication.' },
        { source: 'axler', where: '§1B, 1.20, pp. 12–13', adds: 'the vector-space axioms the lists obey.' },
        { source: 'nc', where: '§2.1.1 p. 63', adds: 'two spanning sets for $\\mathbb C^2$ (the z pair and the x pair).' },
      ],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'powers-of-i' },
        tryThis: [
          'Press “Multiply by i” and read the readout: the number in front of $|{-}z\\rangle$ runs through $1, i, -1, -i$, four different kets built from the same two-number list.',
          'After four presses the list returns to its start: multiplying by $i$ four times is multiplying by $1$.',
        ],
      },
      clues: [],
      insight: 'A quantum state is a ket: a list of complex numbers that add and scale like vectors. A spin needs exactly two.',
      insightFormal: '$\\mathbb C^n$ is a vector space under componentwise $+$ and scalar $\\cdot$ (Axler §1.20); a qubit’s state lives in $\\mathbb C^2$, of dimension 2.',
      play: [
        {
          id: 'f2-v-amp',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The second number of |−x⟩',
          prompt: 'Write $|{-}x\\rangle$ in the z frame. What is its second number?',
          answer: V.f2VAmp,
          tolerance: 0.005,
          hints: [
            { text: '$|{-}x\\rangle = (|{+}z\\rangle - |{-}z\\rangle)/\\sqrt2$.' },
            { text: 'The second number multiplies $|{-}z\\rangle$.' },
            { text: '$-1/\\sqrt2$.' },
          ],
          walkthrough: [{ text: '$|{-}x\\rangle = (1/\\sqrt2,\\ -1/\\sqrt2)$, so the second number is $-0.7071$.' }],
        },
        {
          id: 'f2-v-dependent',
          kind: 'choice',
          tier: 'core',
          title: 'Which set is dependent',
          prompt: 'Which set is linearly dependent in $\\mathbb C^2$?',
          options: [
            { text: '$(1,0), (0,1)$', correct: false, why: 'Independent: neither is a multiple of the other.' },
            { text: '$(1,0), (1,1)$', correct: false, why: 'Independent: they point in different directions.' },
            { text: '$(1,0), (0,1), (1,1)$', correct: true, why: '$(1,1) = (1,0) + (0,1)$: three vectors in a 2-D space are always dependent.' },
            { text: '$(1,i), (1,0)$', correct: false, why: 'Independent: neither is a complex multiple of the other.' },
          ],
          hints: [{ text: 'How many directions does $\\mathbb C^2$ have?' }, { text: 'Two.' }, { text: 'A third vector must be spare.' }],
          walkthrough: [{ text: '$(1,1) = (1,0) + (0,1)$; three vectors in a 2-D space are always dependent.' }],
        },
        {
          id: 'f2-v-super',
          kind: 'numeric',
          tier: 'core',
          title: 'Reading off a coefficient',
          prompt: 'In $0.6|0\\rangle + 0.8|1\\rangle$, what is the coefficient of $|1\\rangle$?',
          answer: V.f2VSuper,
          tolerance: 0.005,
          hints: [{ text: 'It is the second entry.' }, { text: 'Read it off.' }, { text: '$0.8$.' }],
          walkthrough: [{ text: '$0.8$; its square, $0.64$, is the chance of reading $1$ (Chapter Q1).' }],
        },
      ],
    },
    {
      id: 'f2-inner-product',
      story: F2_STORY['f2-inner-product'],
      review: F2_REVIEW['f2-inner-product'],
      title: 'Bra meets ket: ⟨α|β⟩',
      question: 'How do we multiply two states to get one number, and why conjugate the bra?',
      claims: [claim('f2PlusYAmpSq', 'each entry of |+y⟩ has squared size one half (the ½ in this unit’s bilinear example)', () => close(V.f2PlusYAmpSq, 0.5, 5e-5))],
      lecture: {
        pages: 'Axler §6A pp. 182–185; notes n1 pp. 4–5; N&C §2.1.4 pp. 65–66',
        summary: 'A bra against a ket gives one number, the inner product. Mirroring the bra’s numbers before multiplying is what makes a state’s length honest.',
      },
      books: [
        { source: 'axler', where: '6.2 p. 183', adds: 'the inner-product axioms and the first-slot-linear convention.' },
        { source: 'axler', where: '6.3 p. 184', adds: 'a weighted inner product with positive weights.' },
        { source: 'nc', where: '§2.1.4 pp. 65–66', adds: 'the $\\mathbb C^n$ inner product (eq. 2.14) and its properties.' },
      ],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'conjugate', z: [0.7071, 0.7071] },
        tryThis: [
          'Drag $z$ anywhere: $z^*z$ is never negative. That mirror is why $\\langle\\psi|\\psi\\rangle \\ge 0$.',
        ],
      },
      clues: [],
      insight: 'The inner product mirrors the bra, multiplies matching numbers and adds: that mirror is what keeps every state’s length honest.',
      insightFormal: '$\\langle\\alpha|\\beta\\rangle = \\sum_i a_i^* b_i$: conjugate-linear in the bra, linear in the ket (Axler §6.2; N&C Eq. 2.14), so $\\langle\\psi|\\psi\\rangle \\ge 0$.',
      play: [
        {
          id: 'f2-i-zx',
          kind: 'numeric',
          tier: 'warm-up',
          title: '⟨+z|+x⟩',
          prompt: 'What is $\\langle{+}z|{+}x\\rangle$?',
          answer: V.f2InnerZX,
          tolerance: 0.005,
          hints: [{ text: 'Mirror the bra, multiply, add.' }, { text: '$1\\cdot\\tfrac1{\\sqrt2} + 0\\cdot\\tfrac1{\\sqrt2}$.' }, { text: '$1/\\sqrt2$.' }],
          walkthrough: [{ text: '$0.7071$.' }],
        },
        {
          id: 'f2-i-yy',
          kind: 'numeric',
          tier: 'core',
          title: '⟨+y|+y⟩',
          prompt: 'What is $\\langle{+}y|{+}y\\rangle$?',
          answer: V.f2InnerYY,
          tolerance: 1e-6,
          hints: [{ text: 'Mirror the bra: $i$ becomes $-i$.' }, { text: '$\\tfrac12 + (-i)(i)/2$.' }, { text: '$(-i)(i) = 1$.' }],
          walkthrough: [{ text: '$\\tfrac12 + \\tfrac12 = 1$; without the mirror you get $0$, a false length.' }],
        },
        {
          id: 'f2-i-overlap',
          kind: 'numeric',
          tier: 'core',
          title: 'An overlap chance',
          prompt: 'What is $|\\langle{+}x|{+}y\\rangle|^2$?',
          answer: V.f2InnerXYabs2,
          tolerance: 0.005,
          hints: [{ text: '$\\langle{+}x|{+}y\\rangle = \\tfrac12 + \\tfrac{i}2$.' }, { text: 'Its size squared.' }, { text: '$\\tfrac14 + \\tfrac14$.' }],
          walkthrough: [{ text: '$0.5$; equal sizes along up and down, but the phase makes the overlap less than 1.' }],
        },
        {
          id: 'f2-i-weighted',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A weighted inner product',
          prompt: 'With weights $(2, 1)$, what is $\\langle{+}x|{+}z\\rangle_M$?',
          answer: V.f2WeightedXZ,
          tolerance: 0.005,
          hints: [{ text: '$\\alpha^\\dagger M\\beta$.' }, { text: '$M = \\operatorname{diag}(2, 1)$.' }, { text: '$\\tfrac1{\\sqrt2}\\cdot 2\\cdot 1$.' }],
          walkthrough: [{ text: '$2/\\sqrt2 = \\sqrt2 = 1.4142$.' }],
        },
      ],
    },
    {
      id: 'f2-norm-angle',
      story: F2_STORY['f2-norm-angle'],
      review: F2_REVIEW['f2-norm-angle'],
      title: 'Length, right angles, and the law of cosines',
      question: 'How long is a state, when are two orthogonal, and what is the angle between them?',
      lecture: {
        pages: 'Axler §6A pp. 186–190; notes n1 p. 5 Fig. 3',
        summary: 'A state’s length is the root of its inner product with itself. Orthogonal states have a zero inner product, and for real states the inner product also gives the angle between them.',
      },
      books: [
        { source: 'axler', where: '6.7, 6.9–6.17 pp. 186–190', adds: 'the norm, orthogonality, Pythagoras, the angle formula, Cauchy–Schwarz and the triangle inequality.' },
      ],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'multiply', z: [1, 0], w: [0.7071, 0.7071] },
        tryThis: [
          'Read $w$’s angle off the table: $45°$.',
          'Drag $w$ to $90°$: $zw$’s angle is $z$’s angle plus $w$’s, always.',
          'Drag $z$ to $90°$ too: $zw$’s angle reaches $180°$.',
        ],
      },
      clues: [],
      insight: 'Length is the root of the self inner product. A zero inner product means orthogonal, and for real states it also gives the angle between them.',
      insightFormal: '$\\|\\psi\\| = \\sqrt{\\langle\\psi|\\psi\\rangle}$; $\\alpha \\perp \\beta \\iff \\langle\\alpha|\\beta\\rangle = 0$; for real vectors $\\operatorname{Re}\\langle\\alpha|\\beta\\rangle = \\|\\alpha\\|\\|\\beta\\|\\cos\\theta$ (Axler §6A Ex. 15).',
      play: [
        {
          id: 'f2-n-len',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A sum’s length',
          prompt: 'What is the length of $|{+}z\\rangle + |{+}x\\rangle$?',
          answer: V.f2NormZplusX,
          tolerance: 0.005,
          hints: [{ text: 'Add the lists.' }, { text: '$(1.7071,\\ 0.7071)$.' }, { text: '$\\sqrt{1.7071^2 + 0.7071^2}$.' }],
          walkthrough: [{ text: '$\\sqrt{3.4142} = 1.8478$, less than $1 + 1$ (triangle inequality).' }],
        },
        {
          id: 'f2-n-angle',
          kind: 'numeric',
          tier: 'core',
          title: 'An angle in state space',
          prompt: 'What is the angle between $|{+}z\\rangle$ and $|{+}x\\rangle$, in degrees?',
          answer: V.f2AngleZX,
          tolerance: 0.5,
          unit: '°',
          hints: [{ text: '$\\cos\\theta = \\langle{+}z|{+}x\\rangle$.' }, { text: '$1/\\sqrt2$.' }, { text: '$\\arccos(1/\\sqrt2)$.' }],
          walkthrough: [{ text: '$45°$; the x frame is the z frame tilted $45°$ in state space.' }],
        },
        {
          id: 'f2-n-orth',
          kind: 'numeric',
          tier: 'core',
          title: 'A right angle',
          prompt: 'The states $|{+}x\\rangle$ and $|{-}x\\rangle$ are orthogonal. What is the angle between them, in degrees?',
          answer: V.f2AngleXmX,
          tolerance: 0.5,
          unit: '°',
          hints: [{ text: '$\\langle{+}x|{-}x\\rangle = 0$.' }, { text: '$\\cos\\theta = 0$.' }, { text: '$\\arccos 0$.' }],
          walkthrough: [{ text: '$90°$: orthogonal states sit at a right angle in the real slice, though they are opposite spins.' }],
        },
        {
          id: 'f2-n-triangle',
          kind: 'choice',
          tier: 'stretch',
          title: 'When the triangle rule is tight',
          prompt: 'For which pair is $\\|\\alpha + \\beta\\| = \\|\\alpha\\| + \\|\\beta\\|$?',
          options: [
            { text: '$(1,0), (0,1)$', correct: false, why: '$\\sqrt2 < 2$: they turn a corner.' },
            { text: '$(1,0), (2,0)$', correct: true, why: 'Parallel: $3 = 1 + 2$.' },
            { text: '$(1,0), (-1,0)$', correct: false, why: 'Opposite: the sum is $0$, far short of $2$.' },
            { text: '$(1,1), (1,-1)$', correct: false, why: 'Orthogonal: the sum is shorter than the two lengths added.' },
          ],
          hints: [{ text: 'Equality needs the same direction.' }, { text: 'A nonnegative multiple.' }, { text: '$(2,0) = 2(1,0)$.' }],
          walkthrough: [{ text: '$(1,0), (2,0)$ are parallel, so $3 = 1 + 2$. For $(1,0),(0,1)$: $\\sqrt2 < 2$.' }],
        },
      ],
    },
    {
      id: 'f2-orthonormal',
      story: F2_STORY['f2-orthonormal'],
      review: F2_REVIEW['f2-orthonormal'],
      title: 'A frame at right angles: components by inner products',
      question: 'What makes a basis the nicest kind, and how do we read a state’s coordinates off it?',
      claims: [
        claim('f2CompZ', 'the z-frame first coordinate of this unit’s example ψ (unit-wide)', () => close(V.f2CompZ, 0.6)),
        claim('f2CompZ2', 'the z-frame second coordinate of this unit’s example ψ (unit-wide)', () => close(V.f2CompZ2, 0.8)),
      ],
      lecture: {
        pages: 'Axler §6B pp. 197–200; notes n2 p. 6; N&C §2.1.1 p. 63',
        summary: 'An orthonormal basis is a right-angled frame of unit vectors. A state’s coordinates in such a frame are just inner products, and the length is the same however the frame is chosen.',
      },
      books: [
        { source: 'axler', where: '6.22, 6.24–6.25, 6.27–6.28, 6.30 pp. 197–200', adds: 'orthonormal lists, their independence, bases, and the component/Parseval formulas.' },
        { source: 'nc', where: '§2.1.1 p. 63', adds: '$\\dim \\mathbb C^n = n$.' },
      ],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'conjugate', z: [0.6, 0] },
        tryThis: [
          'Drag $z$ to $0.6$, then to $0.8$: $z^*z$ reads $0.36$ and $0.64$, which sum to $1$, like the squared coordinates of a unit state.',
        ],
      },
      clues: [],
      insight: 'An orthonormal frame is a right-angled, unit-length basis; coordinates in it are inner products, and the length survives any change of frame.',
      insightFormal: '$\\langle e_i|e_j\\rangle = \\delta_{ij}$; $c_i = \\langle e_i|\\psi\\rangle$; Parseval $\\|\\psi\\|^2 = \\sum_i|c_i|^2$ and completeness $\\sum_i|e_i\\rangle\\langle e_i| = I$ (Axler §6.27, §6.30).',
      play: [
        {
          id: 'f2-o-comp',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A z-frame coordinate',
          prompt: 'For $0.6|0\\rangle + 0.8|1\\rangle$, what is $\\langle 0|\\psi\\rangle$?',
          answer: V.f2CompZ,
          tolerance: 0.005,
          hints: [{ text: 'The coordinate is an inner product.' }, { text: '$\\langle 0|\\psi\\rangle = c_0$.' }, { text: '$0.6$.' }],
          walkthrough: [{ text: '$0.6$.' }],
        },
        {
          id: 'f2-o-xframe',
          kind: 'numeric',
          tier: 'core',
          title: 'The same state in the x frame',
          prompt: 'The same state in the x frame: what is $\\langle{+}x|\\psi\\rangle$?',
          answer: V.f2CompX,
          tolerance: 0.005,
          hints: [{ text: '$\\langle{+}x|\\psi\\rangle = (c_0 + c_1)/\\sqrt2$.' }, { text: '$(0.6 + 0.8)/\\sqrt2$.' }, { text: '$1.4/\\sqrt2$.' }],
          walkthrough: [{ text: '$0.9899$; check Parseval: $0.9899^2 + 0.1414^2 = 1$.' }],
        },
        {
          id: 'f2-o-dependent',
          kind: 'choice',
          tier: 'core',
          title: 'A dependent triple (N&C Ex. 2.1)',
          prompt: 'The triple $(1,-1), (1,2), (2,1)$ in $\\mathbb C^2$ is linearly dependent. Which coefficients show it?',
          options: [
            { text: '$2(1,-1) - (1,2) = (2,1)$', correct: false, why: 'That combination gives $(1,-4)$, not $(2,1)$.' },
            { text: '$(1,-1) + (1,2) = (2,1)$', correct: true, why: 'Exactly the dependence: one combination of the first two gives the third (N&C Exercise 2.1, not a homework item).' },
            { text: '$(1,-1) - (1,2) = (2,1)$', correct: false, why: 'That combination gives $(0,-3)$, not $(2,1)$.' },
            { text: 'None: the triple is independent', correct: false, why: 'Three vectors in a 2-D space are always dependent.' },
          ],
          hints: [{ text: 'Three vectors in a 2-D space.' }, { text: 'One is a combination of the other two.' }, { text: 'Try adding the first two.' }],
          walkthrough: [{ text: '$(1,-1) + (1,2) = (2,1)$, so the triple is dependent.' }],
        },
        {
          id: 'f2-o-parseval',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Parseval in the x frame',
          prompt: 'For $\\langle{+}x|\\psi\\rangle = 0.9899$ and $\\langle{-}x|\\psi\\rangle = -0.1414$, what is $\\sum |c\'|^2$?',
          answer: V.f2ParsevalX,
          tolerance: 1e-4,
          hints: [{ text: 'Parseval.' }, { text: 'Add the squares.' }, { text: '$0.98 + 0.02$.' }],
          walkthrough: [{ text: '$1$: the length is the same in every orthonormal frame.' }],
        },
      ],
    },
    {
      id: 'f2-gram-schmidt',
      story: F2_STORY['f2-gram-schmidt'],
      review: F2_REVIEW['f2-gram-schmidt'],
      title: 'Straightening a skew frame: Gram–Schmidt',
      question: 'Given any independent set, how do we build a right-angled frame with the same span?',
      claims: [
        claim('f2GsSpin1E0', 'the spin-1 leftover’s first z-component (unit-wide, the challenge answer)', () => close(V.f2GsSpin1E0, 0.7071, 5e-5)),
        claim('f2GsSpin1SxNorm', 'S_x applied to the spin-1 leftover gives the zero vector', () => close(V.f2GsSpin1SxNorm, 0, 1e-9)),
        claim('f2GsSpin1', 'the middle eigenvalue of the spin-1 S_x matrix is 0', () => close(V.f2GsSpin1, 0, 1e-9)),
      ],
      lecture: {
        pages: 'Axler §6B pp. 200–201; notes n2 pp. 6–7 Fig. 4; N&C eq. 2.17',
        summary: 'Gram–Schmidt turns any independent set into an orthonormal frame with the same span: subtract each vector’s shadow on the frame so far, then normalize.',
      },
      books: [
        { source: 'axler', where: '6.32 pp. 200–201', adds: 'the Gram–Schmidt procedure and its proof.' },
        { source: 'nc', where: 'eq. 2.17 p. 66', adds: 'the complex Gram–Schmidt formula.' },
      ],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'conjugate', z: [0.7071, 0.7071] },
        tryThis: [
          'Scroll the derivation: watch the shadow subtracted from $|{+}z\\rangle$, then the leftover divided by its length.',
          'In the widget, drag $z$ off the real axis: its mirror $z^*$ is the conjugation that Gram–Schmidt applies in $\\langle e_1|v\\rangle$ for complex entries.',
        ],
      },
      clues: [],
      insight: 'Keep the first vector, subtract each later one’s shadow on the frame so far, and normalize the leftover. The result spans the same space, now at right angles.',
      insightFormal: '$f_k = v_k - \\sum_{j<k}\\langle f_j|v_k\\rangle f_j/\\|f_j\\|^2$, $e_k = f_k/\\|f_k\\|$ (Axler §6.32; N&C Eq. 2.17), orthonormal with the same span.',
      play: [
        {
          id: 'f2-gs-shadow',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The shadow coefficient',
          prompt: 'Gram–Schmidt on $|{+}x\\rangle$ then $|{+}z\\rangle$: what is the shadow coefficient $\\langle{+}x|{+}z\\rangle$?',
          answer: V.f2GsUnitShadow,
          tolerance: 0.005,
          hints: [{ text: 'Keep $e_1 = |{+}x\\rangle$.' }, { text: 'The shadow of $|{+}z\\rangle$ on it.' }, { text: '$\\langle{+}x|{+}z\\rangle$.' }],
          walkthrough: [{ text: '$0.7071$; subtracting $0.7071\\,e_1$ from $|{+}z\\rangle$ leaves $(0.5, -0.5)$.' }],
        },
        {
          id: 'f2-gs-second',
          kind: 'numeric',
          tier: 'core',
          title: 'The second frame vector',
          prompt: 'After Gram–Schmidt on $|{+}x\\rangle, |{+}z\\rangle$, what is the first entry of $e_2$?',
          answer: V.f2GsUnitE2,
          tolerance: 0.005,
          hints: [{ text: 'The leftover is $(0.5, -0.5)$.' }, { text: 'Normalize it.' }, { text: 'Divide by $\\sqrt{0.5}$.' }],
          walkthrough: [{ text: '$e_2 = (0.7071, -0.7071) = |{-}x\\rangle$.' }],
        },
        {
          id: 'f2-gs-complex',
          kind: 'numeric',
          tier: 'core',
          title: 'A complex Gram–Schmidt',
          prompt: 'Gram–Schmidt on $(1, i)$ then $(0, 1)$: the second entry of $e_1$ has what size?',
          answer: V.f2GsComplexSize,
          tolerance: 0.005,
          hints: [{ text: 'Normalize $(1, i)$.' }, { text: 'Its length is $\\sqrt2$.' }, { text: '$|i|/\\sqrt2$.' }],
          walkthrough: [{ text: '$e_1 = (1/\\sqrt2,\\ i/\\sqrt2)$, so the second entry has size $0.7071$.' }],
        },
        {
          id: 'f2-gs-spin1',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A spin-1 eigenstate by Gram–Schmidt',
          prompt:
            'A spin-1 particle: adjoin $|{+1}z\\rangle$ to the orthonormal pair $\\{|{+1}x\\rangle, |{-1}x\\rangle\\}$, Gram–Schmidt it and normalize. Call the leftover $|\\chi\\rangle$. What is its first z-component, the amplitude on $|{+1}z\\rangle$?',
          answer: V.f2GsSpin1E0,
          tolerance: 0.005,
          hints: [
            { text: 'Which vectors are you orthogonalizing against?' },
            { text: 'Subtract both shadows from $|{+1}z\\rangle$.' },
            { text: 'The leftover points along $(1, 0, -1)$; divide it by its length.' },
          ],
          walkthrough: [
            {
              text: 'Subtracting the shadows on $|{+1}x\\rangle$ and $|{-1}x\\rangle$ from $|{+1}z\\rangle$ leaves a vector along $(1, 0, -1)$, orthogonal to both. Divided by its length, $|\\chi\\rangle = (1/\\sqrt2,\\ 0,\\ -1/\\sqrt2)$: its first z-component is $0.7071$.',
            },
            {
              text: 'Since $S_x$ is Hermitian, its three eigenspaces (for $\\hbar, 0, -\\hbar$) are mutually orthogonal and span the space; a state orthogonal to the $\\pm\\hbar$ eigenstates must be the $0$ eigenstate.',
            },
            { text: 'Diagonalizing the explicit $S_x$ matrix gives eigenvalues $\\hbar, 0, -\\hbar$, so this agrees: $S_x|\\chi\\rangle$ is the zero vector.' },
          ],
        },
      ],
    },
  ],
}
