/**
 * Physics 709 chapter F3 "Matrices and linear maps": a linear map becomes a matrix, matrix products, the adjoint,
 * and change of basis. The third Foundations chapter (no lecture notes: its own line is phase 'core'); it builds on
 * F2 (kets, inner products, orthonormal bases; merged, and bridged from here) and is the bridge target every later
 * chapter reaches for when it writes an operator as a matrix.
 *
 * Plan: docs/roles/proposals/P-F3-story.md; rulings docs/roles/decisions/qc709-foundations.md,
 * qc709-foundations-rulings.md, qc709-nc.md (ruling 1: "Hermitian ⇒ real eigenvalues" was 448 L3 homework, now
 * submitted; F3 still only states and cites it at `f3-adjoint:b3`, and F4 owns the proof). Every number a learner
 * sees is computed in F3.values.ts and asserted in keyed claims (content.test.tsx runs `holds`; claims.test.ts
 * compares each key with its numpy twin in physics/__fixtures__/claims-qc709/f3.json).
 */
import type { Lecture } from '../schema'
import { axler, F3_STORY, nc } from './F3.story'
import { F3_REVIEW } from './F3.review'
import { V, d } from './F3.values'

export const F3: Lecture = {
  id: 'F3',
  number: 3,
  title: 'Matrices and linear maps',
  outcomes: [
    'Say what makes a map linear, and show a gate, a projection and a rotation are linear.',
    'Write a linear map as a matrix with entries $A_{ij} = \\langle i|A|j\\rangle$, and act on a state by matrix times column.',
    'Chain two maps by multiplying their matrices, and explain why $XZ$ and $ZX$ differ.',
    'Form the adjoint $A^\\dagger$ by conjugate-transposing, and say when a matrix is Hermitian or unitary.',
    'Rewrite a map’s matrix in a new orthonormal frame as $UAU^\\dagger$, and see that $Z$ in the x frame is $X$.',
  ],
  // F2's own stations (kets, the inner product, orthonormal frames) are this chapter's prerequisites (P-F3 review 18).
  prerequisites: ['qc-ket', 'qc-inner-product-station', 'qc-orthonormal-basis'],
  // Every symbol the lints require is registered at its real first site in reading order (P-F3 review 10): a beat, or a
  // unit-level site such as a title, summary, tryThis line or challenge. A symbol with no use is not listed.
  symbols: {
    A: 'F3.outcomes[1]',
    A_ij: 'F3.outcomes[1]',
    '\\langle\\cdot|': 'F3.outcomes[1]',
    '|\\cdot\\rangle': 'F3.outcomes[1]',
    '|i\\rangle': 'F3.outcomes[1]',
    '|j\\rangle': 'F3.outcomes[1]',
    X: 'F3.outcomes[2]',
    Z: 'F3.outcomes[2]',
    '\\dagger': 'F3.outcomes[3]',
    U: 'F3.outcomes[4]',
    '\\psi_1': 'f3-linear-maps',
    '\\psi_2': 'f3-linear-maps',
    V: 'f3-linear-maps:b1',
    W: 'f3-linear-maps:b1',
    a: 'f3-linear-maps:b1',
    b: 'f3-linear-maps:b1',
    '|0\\rangle': 'f3-linear-maps:b1',
    '|1\\rangle': 'f3-linear-maps:b1',
    '|\\psi\\rangle': 'f3-linear-maps:b1',
    '|\\psi_1\\rangle': 'f3-linear-maps:b1',
    '|\\psi_2\\rangle': 'f3-linear-maps:b1',
    c_j: 'f3-linear-maps:b2',
    '|e_j\\rangle': 'f3-linear-maps:b2',
    P_0: 'f3-linear-maps:b3',
    'R_\\theta': 'f3-linear-maps:b3',
    B: 'f3-linear-maps:b4',
    I: 'f3-linear-maps:b4',
    '|+x\\rangle': 'f3-linear-maps:b4',
    c_i: 'f3-linear-maps:b5',
    L: 'f3-linear-maps.books[0]',
    v: 'f3-linear-maps.visual.tryThis[0]',
    '\\psi': 'f3-linear-maps.review',
    '|+z\\rangle': 'f3-linear-maps.play.f3-l-act',
    '|-z\\rangle': 'f3-linear-maps.play.f3-l-act.walkthrough[0]',
    f: 'f3-linear-maps.play.f3-l-linear.options[3]',
    '\\phi': 'f3-linear-maps.play.f3-l-linear.hints[0]',
    j: 'f3-matrix-of-map',
    M: 'f3-matrix-of-map:b1',
    i: 'f3-matrix-of-map:b1',
    '|e_i\\rangle': 'f3-matrix-of-map:b1',
    '\\bar c': 'f3-matrix-of-map:b2',
    '\\bar f': 'f3-matrix-of-map:b2',
    '\\langle\\cdot|\\cdot\\rangle': 'f3-matrix-of-map:b2',
    c_0: 'f3-matrix-of-map:b2',
    c_1: 'f3-matrix-of-map:b2',
    f_i: 'f3-matrix-of-map:b2',
    '|A\\psi\\rangle': 'f3-matrix-of-map:b2',
    H: 'f3-matrix-of-map:b3',
    '\\pi': 'f3-matrix-of-map:b3',
    '|-x\\rangle': 'f3-matrix-of-map:b3',
    '\\hat A': 'f3-matrix-of-map:b4',
    T: 'f3-matrix-of-map.books[0]',
    '\\hbar': 'f3-matrix-of-map.visual.tryThis[0]',
    k: 'f3-matrix-of-map.review',
    '|e_k\\rangle': 'f3-matrix-of-map.review',
    A_jr: 'f3-products:b1',
    B_rk: 'f3-products:b1',
    '|e_r\\rangle': 'f3-products:b1',
    C: 'f3-products:b4',
    A_ji: 'f3-adjoint:b1',
    '\\varphi': 'f3-adjoint:b1',
    '|A^\\dagger\\varphi\\rangle': 'f3-adjoint:b1',
    '|Ae_i\\rangle': 'f3-adjoint:b1',
    '|\\varphi\\rangle': 'f3-adjoint:b1',
    A_i: 'f3-adjoint:b2',
    a_i: 'f3-adjoint:b2',
    '|v\\rangle': 'f3-adjoint:b2',
    '|w\\rangle': 'f3-adjoint:b2',
    Y: 'f3-adjoint:b3',
    S: 'f3-adjoint:b5',
    S_y: 'f3-adjoint.visual.tryThis[0]',
    U_ij: 'f3-change-of-basis:b1',
    U_ki: 'f3-change-of-basis:b1',
    '\\alpha': 'f3-change-of-basis:b1',
    '\\alpha_j': 'f3-change-of-basis:b1',
    c: 'f3-change-of-basis:b1',
    d: 'f3-change-of-basis:b1',
    d_i: 'f3-change-of-basis:b1',
    l: 'f3-change-of-basis:b1',
    '|\\alpha\'_i\\rangle': 'f3-change-of-basis:b1',
    '|\\alpha\'_k\\rangle': 'f3-change-of-basis:b1',
    '|\\alpha\'_l\\rangle': 'f3-change-of-basis:b1',
    '|\\alpha_i\\rangle': 'f3-change-of-basis:b1',
    '|\\alpha_j\\rangle': 'f3-change-of-basis:b1',
    '\\hat U': 'f3-change-of-basis:b2',
    '|k\'\\rangle': 'f3-change-of-basis:b2',
    '|l\'\\rangle': 'f3-change-of-basis:b2',
    '\\delta_ij': 'f3-change-of-basis:b4',
    '|\\alpha\'_j\\rangle': 'f3-change-of-basis:b4',
    '|\\alpha_k\\rangle': 'f3-change-of-basis:b4',
    'B_x\\leftarrowz': 'f3-change-of-basis.visual.tryThis[0]',
    'B_z\\leftarrowx': 'f3-change-of-basis.visual.tryThis[0]',
    S_z: 'f3-change-of-basis.visual.tryThis[0]',
    S_x: 'f3-change-of-basis.visual.tryThis[1]',
    'B_y\\leftarrowz': 'f3-change-of-basis.visual.tryThis[2]',
    'B_z\\leftarrowy': 'f3-change-of-basis.visual.tryThis[2]',
  },
  units: [
    {
      id: 'f3-linear-maps',
      story: F3_STORY['f3-linear-maps'],
      review: F3_REVIEW['f3-linear-maps'],
      title: 'Machines that respect addition',
      question: 'What is a linear map, and why does it turn sums into sums?',
      lecture: {
        pages: 'Axler §3A pp. 52–55; notes n2 p. 10; N&C §2.1.2 p. 63',
        summary: 'A linear map respects addition and scaling. Gates, projections and rotations are all linear; squaring the amplitudes is not.',
      },
      books: [
        axler('§3A, 3.1–3.9, pp. 52–55', 'Linear maps $\\mathcal L(V, W)$ and their defining property.'),
        nc('§2.1.2, p. 63', 'Linear operators, the identity and zero operators, and composition.'),
      ],
      visual: {
        kind: 'operator-action',
        props: { preset: 'σx' },
        tryThis: [
          'Drag $v$ to the right-hand end of the horizontal axis, that is $|0\\rangle$: $Av$ points straight up, because $X$ swaps the two entries.',
          'Press σz and drag $v$ straight down: $Av$ points straight up, the opposite arrow. $Z$ flips the sign of the down part.',
          'Press P+z: the projector keeps the up part of every arrow and drops the rest, so $Av$ always lies on the horizontal axis. It is still a matrix, so it is linear.',
        ],
      },
      clues: [],
      insight: 'A linear map respects every sum and scaling, so gates, projections and rotations all have one; squaring does not.',
      insightFormal: 'A linear operator satisfies $A(a\\psi_1 + b\\psi_2) = aA\\psi_1 + bA\\psi_2$; it is fixed by its action on a basis, and composition of linear maps is linear too.',
      play: [
        {
          id: 'f3-l-act',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A swap of the two entries',
          prompt: 'What is the second entry of $X|{+}z\\rangle$?',
          answer: V.f3Xplusz,
          tolerance: 0,
          hints: [{ text: '$X$ swaps the two numbers.' }, { text: '$(1, 0) \\mapsto (0, 1)$.' }, { text: 'The second entry is 1.' }],
          walkthrough: [{ text: '$X|{+}z\\rangle = |{-}z\\rangle = (0, 1)$: the second entry is 1.' }],
        },
        {
          id: 'f3-l-linear',
          kind: 'choice',
          tier: 'core',
          title: 'Which rule is linear?',
          prompt: 'Which rule is a linear map on ℂ²?',
          options: [
            { text: '$(a, b) \\mapsto (a^2, b^2)$', correct: false, why: 'Doubling the input quadruples the output: not linear.' },
            { text: '$(a, b) \\mapsto (a + 1, b)$', correct: false, why: 'This moves the origin; it does not send sums to sums.' },
            { text: '$(a, b) \\mapsto (b, a)$', correct: true, why: 'This is $X$: a swap respects both sums and scaling.' },
            { text: '$(a, b) \\mapsto (|a|, |b|)$', correct: false, why: 'Taking sizes is not linear: $f(-v) = f(v) \\ne -f(v)$.' },
          ],
          hints: [
            { text: 'Linear means $A(2\\psi) = 2A\\psi$ and $A(\\psi + \\phi) = A\\psi + A\\phi$.' },
            { text: 'Squaring and shifting by 1 both fail one of these.' },
            { text: 'Swapping the two entries passes both checks.' },
          ],
          walkthrough: [{ text: '$(a, b) \\mapsto (b, a)$ is $X$, linear. Squaring quadruples on doubling; shifting by 1 moves the origin.' }],
        },
        {
          id: 'f3-l-proj',
          kind: 'numeric',
          tier: 'core',
          title: 'What the projector drops',
          prompt: 'The projector $|0\\rangle\\langle 0|$ acts on $(0.6, 0.8)$. What is the second entry of the result?',
          answer: V.f3ProjZ,
          tolerance: 0.005,
          hints: [{ text: '$|0\\rangle\\langle 0|$ keeps the $|0\\rangle$ part.' }, { text: 'It is $\\operatorname{diag}(1, 0)$.' }, { text: 'The second entry is dropped.' }],
          walkthrough: [{ text: `The result is $(0.6, ${d(V.f3ProjZ, 0)})$: the projector keeps only the up part.` }],
        },
      ],
    },
    {
      id: 'f3-matrix-of-map',
      story: F3_STORY['f3-matrix-of-map'],
      review: F3_REVIEW['f3-matrix-of-map'],
      title: 'A map becomes a table of numbers',
      question: 'How does a linear map become a grid of numbers, and what does each entry mean?',
      lecture: {
        pages: 'Axler §3C pp. 69–72 (3.31–3.32); notes n2 p. 10',
        summary: 'Send each frame vector through the map and stack the results as columns: that grid is the map’s matrix. Acting on a state is then matrix times column.',
      },
      books: [axler('§3C, 3.31–3.32, pp. 69–72', 'The matrix of a linear map $\\mathcal M(T)$, with a worked example.')],
      visual: {
        kind: 'operator-builder',
        props: { axis: 'x' },
        tryThis: [
          'Step to the end: the table is $\\tfrac\\hbar2$ times $X$. Read column 0 of the grid, $(0, 1)$: that is $X|0\\rangle = |1\\rangle$.',
          'Pick tilt, set $45^\\circ$ and step to the end: the table is $\\tfrac\\hbar2$ times $H$, with entries $\\pm1/\\sqrt2$.',
          'Pick $x$ again and step to the end: the top-right entry is $\\langle 0|X|1\\rangle = 1$, times $\\tfrac\\hbar2$.',
        ],
      },
      clues: [],
      insight: 'Any linear map becomes a table of numbers, $A_{ij} = \\langle i|A|j\\rangle$, and acting on a state is matrix times column.',
      insightFormal: 'In an orthonormal basis $A_{ij} = \\langle e_i|A|e_j\\rangle$, column $j$ is $A|e_j\\rangle$, and $A = \\sum_{ij}A_{ij}|e_i\\rangle\\langle e_j|$.',
      play: [
        {
          id: 'f3-m-entry',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Read an entry off the table',
          prompt: 'What is $\\langle 0|X|1\\rangle$?',
          answer: V.f3XelemZmz,
          tolerance: 0,
          hints: [{ text: '$X|1\\rangle = |0\\rangle$.' }, { text: 'Overlap that with $\\langle 0|$: $\\langle 0|0\\rangle$.' }, { text: 'That overlap is 1.' }],
          walkthrough: [{ text: '$\\langle 0|X|1\\rangle = 1$, the off-diagonal entry of $X$.' }],
        },
        {
          id: 'f3-m-hadamard',
          kind: 'numeric',
          tier: 'core',
          title: 'Hadamard’s one negative entry',
          prompt: 'What is $\\langle 1|H|1\\rangle$?',
          answer: V.f3MatH,
          tolerance: 0.005,
          hints: [{ text: '$H|1\\rangle = |{-}x\\rangle = (1/\\sqrt2, -1/\\sqrt2)$.' }, { text: 'Overlap that with $\\langle 1|$.' }, { text: 'It is $-1/\\sqrt2$.' }],
          walkthrough: [{ text: `$\\langle 1|H|1\\rangle = ${d(V.f3MatH)}$, the one negative entry of $H$.` }],
        },
        {
          id: 'f3-m-act',
          kind: 'numeric',
          tier: 'core',
          title: 'Acting with the table',
          prompt: '$H$ acts on $(0.6, 0.8)$. What is the first entry of the result?',
          answer: V.f3ActionHc,
          tolerance: 0.005,
          hints: [{ text: '$\\bar f = H\\bar c$.' }, { text: 'The first row of $H$ is $(1/\\sqrt2, 1/\\sqrt2)$.' }, { text: 'Compute $(0.6 + 0.8)/\\sqrt2$.' }],
          walkthrough: [{ text: `The first entry is $${d(V.f3ActionHc)}$. It equals the x-frame coordinate $\\langle{+}x|\\psi\\rangle$ of the same vector, because the z→x change matrix $U$ happens to equal $H$. Applying a gate moves the state; changing frame only renames it.` }],
        },
      ],
    },
    {
      id: 'f3-products',
      story: F3_STORY['f3-products'],
      review: F3_REVIEW['f3-products'],
      title: 'One map then another: matrix products',
      question: 'Why is matrix multiplication defined the way it is, and why is order everything?',
      lecture: {
        pages: 'Axler §3C pp. 72–74 (3.41–3.42); §3D pp. 90–91 (3.79–3.81)',
        summary: 'The matrix product is defined to match doing one map after another. Order matters: multiplying matrices is not commutative.',
      },
      books: [axler('§3C–3D, 3.41, 3.79–3.81, pp. 72–74, 90–91', 'Matrix multiplication, the identity matrix and invertibility.')],
      visual: {
        kind: 'operator-action',
        props: { preset: 'σx' },
        tryThis: [
          'Scroll the story: the first beat multiplies $H$ by $X$, and the grid shows the product table $HX$.',
          'The next beats sandwich $HXH$, which lands on $Z$, and then put $XZ$ beside $ZX$: they differ by a sign.',
          'In the widget, drag $v$ to the right-hand end of the horizontal axis and press σx, then σz: σx sends it straight up, σz leaves it where it is. The widget shows one table at a time; the story’s grids show their product.',
        ],
      },
      clues: [],
      insight: 'Chaining two maps multiplies their tables, $(AB)_{jk} = \\sum_r A_{jr}B_{rk}$, and order matters: $XZ = -ZX$.',
      insightFormal: 'Matrix multiplication is defined so $\\mathcal M(AB) = \\mathcal M(A)\\mathcal M(B)$; it is associative but not commutative, and an invertible map has $AA^{-1} = I$.',
      play: [
        {
          id: 'f3-p-hxh',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The sandwiched entry',
          prompt: 'What is the entry $\\langle 1|HXH|1\\rangle$?',
          answer: V.f3HXH,
          tolerance: 0,
          hints: [{ text: '$HXH = Z$.' }, { text: '$Z = \\operatorname{diag}(1, -1)$.' }, { text: 'The lower entry is $-1$.' }],
          walkthrough: [{ text: '$HXH = Z$, so $\\langle 1|HXH|1\\rangle = -1$.' }],
        },
        {
          id: 'f3-p-order',
          kind: 'choice',
          tier: 'core',
          title: 'Order and sign',
          prompt: 'Which is true for $X$ and $Z$?',
          options: [
            { text: '$XZ = ZX$', correct: false, why: 'Compute both: they differ.' },
            { text: '$XZ = -ZX$', correct: true, why: '$XZ = \\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$, $ZX = \\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}$: the sign flips.' },
            { text: '$XZ = I$', correct: false, why: 'Neither product is the identity.' },
            { text: '$XZ = Z$', correct: false, why: '$XZ$ has zero diagonal; $Z$ does not.' },
          ],
          hints: [
            { text: 'Compute both products.' },
            { text: '$XZ = \\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$, $ZX = \\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}$.' },
            { text: 'Compare the signs of their entries.' },
          ],
          walkthrough: [{ text: '$XZ = -ZX$: the two gates anticommute, so order flips every sign.' }],
        },
        {
          id: 'f3-p-inverse',
          kind: 'numeric',
          tier: 'core',
          title: 'A gate that undoes itself',
          prompt: 'What is $X^2$? Give the $\\langle 0|X^2|0\\rangle$ entry.',
          answer: V.f3Xsq,
          tolerance: 0,
          hints: [{ text: '$X$ undoes itself.' }, { text: '$X^2 = I$.' }, { text: 'The $(0, 0)$ entry of $I$ is 1.' }],
          walkthrough: [{ text: '$X^2 = I$, so $\\langle 0|X^2|0\\rangle = 1$: $X$ is its own inverse.' }],
        },
      ],
    },
    {
      id: 'f3-adjoint',
      story: F3_STORY['f3-adjoint'],
      review: F3_REVIEW['f3-adjoint'],
      title: 'The mirror of a map',
      question: 'What is the adjoint, when does a matrix equal its own mirror, and why does the frame matter?',
      lecture: {
        pages: 'Axler §7A pp. 231–232 (7.7, 7.9); notes n2 p. 9; N&C §2.1.6 pp. 69–70',
        summary: 'Every map has an adjoint, found in an orthonormal frame by conjugate-transposing. Hermitian maps equal their own mirror; unitary maps keep every length.',
      },
      books: [
        axler('§7A, 7.7, 7.9, pp. 231–232', 'The conjugate transpose $A^*$, and a caution for non-orthonormal bases.'),
        nc('§2.1.6, pp. 69–70', 'The adjoint $A^\\dagger$ (eq. 2.32), $(AB)^\\dagger = B^\\dagger A^\\dagger$, Hermitian and unitary operators.'),
      ],
      visual: {
        kind: 'operator-builder',
        props: { axis: 'y' },
        tryThis: [
          'Step through $S_y$: the corners are $-i$ and $+i$, each the conjugate of the other, and the ✓ for $S_y^\\dagger = S_y$ holds.',
          'Read the note under the last step: the bra uses the conjugate $(1, -i)/\\sqrt2$. That conjugation is the mirror at work.',
          'This builder only makes Hermitian tables. For a unitary that is not Hermitian, see the clue at the end of the story: $S^\\dagger S = I$ but $S^\\dagger \\ne S$.',
        ],
      },
      clues: [],
      insight: 'Every map has a mirror $A^\\dagger$; Hermitian means $A^\\dagger = A$, unitary means $U^\\dagger = U^{-1}$ and keeps every length.',
      insightFormal: '$A^\\dagger$ is fixed by $\\langle\\varphi|A\\psi\\rangle = \\langle A^\\dagger\\varphi|\\psi\\rangle$; in an orthonormal frame it is the conjugate transpose, and every gate is unitary.',
      play: [
        {
          id: 'f3-a-sdag',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Conjugating the diagonal',
          prompt: 'For $S = \\operatorname{diag}(1, i)$, what is the imaginary part of the $(1,1)$ entry of $S^\\dagger$?',
          answer: V.f3Sdag,
          tolerance: 0,
          hints: [{ text: 'Conjugate the diagonal.' }, { text: '$i$ becomes $-i$.' }, { text: 'The imaginary part is $-1$.' }],
          walkthrough: [{ text: '$S^\\dagger = \\operatorname{diag}(1, -i)$: the $(1,1)$ entry is $-i$.' }],
        },
        {
          id: 'f3-a-hermitian',
          kind: 'choice',
          tier: 'core',
          title: 'Which equals its own mirror?',
          prompt: 'Which of these is Hermitian ($A^\\dagger = A$)?',
          options: [
            { text: '$S = \\operatorname{diag}(1, i)$', correct: false, why: '$S^\\dagger = \\operatorname{diag}(1, -i) \\ne S$.' },
            { text: '$Y = \\begin{pmatrix}0&-i\\\\i&0\\end{pmatrix}$', correct: true, why: '$Y^\\dagger = Y$: conjugating and transposing returns the same table.' },
            { text: '$|0\\rangle\\langle 1|$', correct: false, why: 'Its mirror is $|1\\rangle\\langle 0|$, a different table.' },
            { text: '$\\operatorname{diag}(1, 2i)$', correct: false, why: 'A non-real diagonal entry is never its own conjugate.' },
          ],
          hints: [{ text: 'Conjugate-transpose each table.' }, { text: '$Y^\\dagger = Y$.' }, { text: 'The others change under the mirror.' }],
          walkthrough: [{ text: '$Y$ is Hermitian; $S$ and $\\operatorname{diag}(1, 2i)$ have a non-real diagonal entry, and $|0\\rangle\\langle 1|$ is not symmetric.' }],
        },
        {
          id: 'f3-a-unitary',
          kind: 'numeric',
          tier: 'core',
          title: 'Unitary without being Hermitian',
          prompt: 'Is $S$ unitary? Give the $(0,0)$ entry of $S^\\dagger S$.',
          answer: V.f3SdagS,
          tolerance: 0,
          hints: [{ text: 'Compute $S^\\dagger S$.' }, { text: '$\\operatorname{diag}(1, -i)\\operatorname{diag}(1, i)$.' }, { text: 'That is $\\operatorname{diag}(1, 1) = I$.' }],
          walkthrough: [{ text: '$S^\\dagger S = I$, so $S$ is unitary even though it is not Hermitian.' }],
        },
        {
          id: 'f3-a-product',
          kind: 'choice',
          tier: 'stretch',
          title: 'Mirroring a product',
          prompt: 'What is $(XZ)^\\dagger$?',
          options: [
            { text: '$XZ$', correct: false, why: 'A product’s mirror reverses the order.' },
            { text: '$X^\\dagger Z^\\dagger$', correct: false, why: 'Close, but the order must reverse too.' },
            { text: '$ZX$', correct: true, why: '$(XZ)^\\dagger = Z^\\dagger X^\\dagger = ZX$, since $X$ and $Z$ are each Hermitian.' },
            { text: '$-XZ$', correct: false, why: 'The entries do not simply flip sign.' },
          ],
          hints: [{ text: '$(AB)^\\dagger = B^\\dagger A^\\dagger$.' }, { text: '$X^\\dagger = X$ and $Z^\\dagger = Z$.' }, { text: 'Reverse the order.' }],
          walkthrough: [{ text: '$(XZ)^\\dagger = Z^\\dagger X^\\dagger = ZX$.' }],
        },
      ],
    },
    {
      id: 'f3-change-of-basis',
      story: F3_STORY['f3-change-of-basis'],
      review: F3_REVIEW['f3-change-of-basis'],
      title: 'The same map in a new frame',
      question: 'How does a map’s table change when you choose a different frame, and what stays fixed?',
      lecture: {
        pages: 'Axler §3D pp. 91–92 (3.82–3.83); notes n2 pp. 8–9',
        summary: 'A new orthonormal frame changes a state’s coordinates by $U$ and a map’s table by $UAU^\\dagger$. The map itself, its lengths, trace and determinant are unchanged.',
      },
      books: [axler('§3D, 3.82–3.83, pp. 91–92', 'The two change-of-basis matrices between a pair of bases are inverses.')],
      visual: {
        kind: 'basis-translator',
        props: { target: 'x', mode: 'operator', operator: 'Sz' },
        tryThis: [
          '$S_z$ in the x basis is $\\tfrac\\hbar2$ times $X$: the readout writes it as $B_{x\\leftarrow z}S_zB_{z\\leftarrow x}$.',
          'Switch the operator to $S_x$: its table turns diagonal, $\\tfrac\\hbar2$ times $Z$, and the widget says the x basis is its own eigenbasis.',
          'Switch the new basis to y: $B_{z\\leftarrow y}$ and $B_{y\\leftarrow z}$ now have different entries, though each is the other’s inverse.',
        ],
      },
      clues: [],
      insight: 'A new frame changes a state’s coordinates by $d = Uc$ and a map’s table by $UAU^\\dagger$; $Z$ in the x frame is $X$.',
      insightFormal: '$U_{ij} = \\langle\\alpha\'_i|\\alpha_j\\rangle$ is always unitary; $A\' = UAU^\\dagger$ rewrites an operator without changing the map, its trace or its determinant.',
      play: [
        {
          id: 'f3-cb-coord',
          kind: 'numeric',
          tier: 'warm-up',
          title: '$|0\\rangle$ in the x frame',
          prompt: '$|0\\rangle$ in the x frame: what is its first new coordinate $\\langle{+}x|0\\rangle$?',
          answer: V.f3InnerPlusXZ,
          tolerance: 0.005,
          hints: [{ text: '$U = H$ for z→x.' }, { text: 'The first row of $H$ dotted with $(1, 0)$.' }, { text: 'That is $1/\\sqrt2$.' }],
          walkthrough: [{ text: `$|0\\rangle = (|{+}x\\rangle + |{-}x\\rangle)/\\sqrt2$, so the first coordinate is $${d(V.f3InnerPlusXZ)}$.` }],
        },
        {
          id: 'f3-cb-zinx',
          kind: 'numeric',
          tier: 'core',
          title: '$Z$ seen from the x frame',
          prompt: 'What is the $(0,1)$ entry of $Z$ written in the x frame, $UZU^\\dagger$?',
          answer: V.f3ZinX,
          tolerance: 0,
          hints: [{ text: '$UZU^\\dagger = HZH$.' }, { text: '$HZH = X$.' }, { text: 'The off-diagonal entry of $X$ is 1.' }],
          walkthrough: [{ text: '$Z$ in the x frame is $X$, whose $(0, 1)$ entry is 1.' }],
        },
        {
          id: 'f3-cb-unitary',
          kind: 'numeric',
          tier: 'core',
          title: 'A change of frame keeps lengths',
          prompt: 'For the z→x change $U = H$, what is the $(0,0)$ entry of $U^\\dagger U$?',
          answer: V.f3Uunitary,
          tolerance: 0,
          hints: [{ text: 'A change-of-basis matrix is unitary.' }, { text: '$H^\\dagger H = I$.' }, { text: 'The $(0,0)$ entry of $I$ is 1.' }],
          walkthrough: [{ text: '$U^\\dagger U = I$: changing frames never stretches a state.' }],
        },
        {
          id: 'f3-cb-xinx',
          kind: 'numeric',
          tier: 'stretch',
          title: '$X$ in its own eigenframe',
          prompt: 'What does $X$ become in the x frame? Give the $(0,0)$ entry of $UXU^\\dagger$.',
          answer: V.f3XinX,
          tolerance: 0,
          hints: [{ text: '$UXU^\\dagger = HXH$.' }, { text: '$HXH = Z$.' }, { text: 'The $(0,0)$ entry of $Z$ is 1.' }],
          walkthrough: [{ text: '$X$ in its own frame is $Z = \\operatorname{diag}(1, -1)$; the $(0, 0)$ entry is 1.' }],
        },
      ],
    },
  ],
}
