/**
 * Physics 709 chapter F4 "Eigenvalues, Hermitian and unitary operators, the spectral theorem": the canonical owner
 * of eigenvalues/eigenvectors, the characteristic equation, Hermitian and unitary operators and the spectral
 * theorem. The fourth Foundations chapter (no lecture notes: its own line is phase 'core'); it builds on F1
 * (complex numbers), F2 (vectors, inner products) and F3 (matrices, the adjoint, change of basis), all merged, and
 * is the bridge target every later chapter reaches for when it diagonalizes an observable or exponentiates a
 * Hamiltonian.
 *
 * Plan: docs/roles/proposals/P-F4-story.md; rulings docs/roles/decisions/qc709-foundations.md,
 * qc709-foundations-rulings.md, qc709-nc.md (ruling 1: "Hermitian ⇒ real eigenvalues" was 448 L3 homework, since
 * submitted: `f4-hermitian:b2` proves it for 2×2 only, `f4-hermitian:b3` states it in any size and cites the revised
 * notes (n4 p. 17), and the orthogonality half is derived in `f4-hermitian:b4`). Every number a learner sees is computed in F4.values.ts and asserted in keyed claims
 * (content.test.tsx runs `holds`; claims.test.ts compares each key with its numpy twin in
 * physics/__fixtures__/claims-qc709/f4.json).
 */
import type { Lecture } from '../schema'
import { F4_REVIEW } from './F4.review'
import { axler, C, F4_STORY } from './F4.story'
import { V, d } from './F4.values'

export const F4: Lecture = {
  id: 'F4',
  number: 4,
  title: 'Eigenvalues, Hermitian and unitary operators',
  outcomes: [
    'Find the arrows a matrix only stretches, and the stretch factors, from the characteristic equation.',
    'Say why a table equal to its own mirror has real stretches and right-angle directions.',
    'Rebuild a Hermitian table from its directions, read it in its own frame, and apply a function to it.',
    'Recognise a table that keeps every length, and say why its stretches sit on the unit circle.',
    'Decide when two tables can be diagonalized together, and name their shared directions.',
    'Tell a table with no backward stretch, and take its square root.',
  ],
  prerequisites: ['qc-orthonormal-basis', 'qc-matrix-of-map', 'qc-adjoint', 'qc-change-of-basis-station', 'qc-euler'],
  // Every symbol the lints require is registered at its real first site in reading order (P-F3/F4 review: symbols
  // before use): a beat, or a unit-level site such as a title, summary, tryThis line or challenge. K is the Hermitian
  // generator of a time evolution; H is the Hadamard only.
  symbols: {
    A: 'f4-eigen:b1',
    X: 'f4-eigen:b1',
    Z: 'f4-eigen:b1',
    '\\lambda': 'f4-eigen:b1',
    '\\theta': 'f4-eigen:b1',
    '|+n\\rangle': 'f4-eigen:b1',
    '|\\cdot\\rangle': 'f4-eigen:b1',
    '|a\\rangle': 'f4-eigen:b1',
    I: 'f4-eigen:b2',
    a: 'f4-eigen:b2',
    b: 'f4-eigen:b2',
    c: 'f4-eigen:b2',
    d: 'f4-eigen:b2',
    '\\boldsymbol': 'f4-eigen:b3',
    '\\sigma': 'f4-eigen:b3',
    '\\varphi': 'f4-eigen:b3',
    n: 'f4-eigen:b3',
    '|-n\\rangle': 'f4-eigen:b3',
    '\\otimes': 'f4-eigen:b4',
    R: 'f4-eigen:b5',
    i: 'f4-eigen:b5',
    v: 'f4-eigen.visual.tryThis[0]',
    A_00: 'f4-eigen.play.f4-e-trace.hints[2]',
    A_11: 'f4-eigen.play.f4-e-trace.hints[2]',
    '\\lambda_1': 'f4-eigen.play.f4-e-trace.walkthrough[0]',
    '\\lambda_2': 'f4-eigen.play.f4-e-trace.walkthrough[0]',
    '\\sigma_x': 'f4-eigen.play.f4-e-complex.options[0]',
    '\\sigma_z': 'f4-eigen.play.f4-e-complex.options[1]',
    A_ij: 'f4-hermitian:b1',
    A_ji: 'f4-hermitian:b1',
    T: 'f4-hermitian:b1',
    '\\dagger': 'f4-hermitian:b1',
    u: 'f4-hermitian:b1',
    '\\langle\\cdot|': 'f4-hermitian:b3',
    '\\langle\\cdot|\\cdot\\rangle': 'f4-hermitian:b4',
    '|Aa_2\\rangle': 'f4-hermitian:b4',
    '|a_1\\rangle': 'f4-hermitian:b4',
    '|a_2\\rangle': 'f4-hermitian:b4',
    S_y: 'f4-hermitian.visual.tryThis[0]',
    '\\hbar': 'f4-hermitian.visual.tryThis[0]',
    A_01: 'f4-hermitian.play.f4-h-ishermitian.options[0]',
    A_10: 'f4-hermitian.play.f4-h-ishermitian.options[0]',
    '|+x\\rangle': 'f4-hermitian.play.f4-h-orthogonal',
    '|-x\\rangle': 'f4-hermitian.play.f4-h-orthogonal',
    S_x: 'f4-hermitian.play.f4-h-gs',
    '|+1x\\rangle': 'f4-hermitian.play.f4-h-gs',
    '|+1z\\rangle': 'f4-hermitian.play.f4-h-gs',
    '|-1x\\rangle': 'f4-hermitian.play.f4-h-gs',
    'P_+x': 'f4-spectral:b1',
    'P_-x': 'f4-spectral:b1',
    '\\lambda_i': 'f4-spectral:b1',
    '|a_i\\rangle': 'f4-spectral:b1',
    B: 'f4-spectral:b2',
    D: 'f4-spectral:b2',
    U: 'f4-spectral:b2',
    '\\delta_ij': 'f4-spectral:b2',
    '\\lambda_j': 'f4-spectral:b2',
    j: 'f4-spectral:b2',
    '|a_j\\rangle': 'f4-spectral:b2',
    P: 'f4-spectral:b3',
    f: 'f4-spectral:b3',
    t: 'f4-spectral:b3',
    'P_+': 'f4-spectral:b4',
    'P_-': 'f4-spectral:b4',
    'P_\\lambda': 'f4-spectral:b4',
    'P_\\mu': 'f4-spectral:b4',
    'P_\\pm': 'f4-spectral:b4',
    '\\delta_\\lambda\\mu': 'f4-spectral:b4',
    '\\sigma_n': 'f4-spectral.visual.tryThis[1]',
    K: 'f4-spectral.play.f4-s-exp',
    '\\pi': 'f4-spectral.play.f4-s-exp',
    e: 'f4-spectral.play.f4-s-exp',
    H: 'f4-unitary:b1',
    w: 'f4-unitary:b1',
    '|Uv\\rangle': 'f4-unitary:b1',
    '|Uw\\rangle': 'f4-unitary:b1',
    '|v\\rangle': 'f4-unitary:b1',
    '|w\\rangle': 'f4-unitary:b1',
    '|0\\rangle': 'f4-unitary:b2',
    '|1\\rangle': 'f4-unitary:b2',
    S: 'f4-unitary:b3',
    R_z: 'f4-unitary.visual.tryThis[0]',
    'P_+z': 'f4-commuting:b1',
    '\\sigma_y': 'f4-commuting:b2',
    '\\not': 'f4-positive:b1',
    V: 'f4-positive:b3',
    '\\Sigma': 'f4-positive:b3',
  },
  units: [
    {
      id: 'f4-eigen',
      story: F4_STORY['f4-eigen'],
      review: F4_REVIEW['f4-eigen'],
      title: 'The arrows a machine only stretches',
      question: 'Which directions does a matrix leave in place, only scaling them, and how do we find the scales?',
      lecture: {
        pages: 'Axler 5A pp. 134\u2013135, 5B p. 151; notes n3 p. 14, n4 p. 17',
        summary: 'An eigenvector is an arrow a matrix only stretches, by its eigenvalue. The scales solve the characteristic equation, and can be complex, repeated, or (for a defective table) short of a full set.',
      },
      books: [
        axler('5A, 5.5\u20135.8, pp. 134\u2013135', 'Eigenvalues, eigenvectors, the characteristic idea.'),
        axler('5B, Ex. 5B.11, p. 151', 'The characteristic quadratic of a 2×2 operator.'),
      ],
      visual: {
        kind: 'operator-action',
        props: { a: 0.5, b: 0.5, d: -0.5 },
        tryThis: [
          'Tick show eigen-directions: the readout lists the eigenvalues $-0.707$ and $0.707$. Drag $v$ onto a line, and the widget says it is an eigenvector.',
          'Set $b = 0$: the two lines snap onto the axes, because a diagonal table only stretches the axis arrows.',
          'Press [[2,1],[1,2]]: the eigenvalues are $1$ and $3$, and the lines sit at $\\pm45^\\circ$.',
        ],
      },
      clues: [],
      insight: 'An eigenvector is an arrow a matrix only stretches; the stretch, its eigenvalue, solves the characteristic equation.',
      insightFormal: '$A|a\\rangle = \\lambda|a\\rangle$ ($|a\\rangle \\ne 0$) defines an eigenpair; $\\det(A - \\lambda I) = 0$ finds every $\\lambda$, real or complex.',
      claims: [C.xzHalfEntry],
      play: [
        {
          id: 'f4-e-trace',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Trace from eigenvalues',
          prompt: 'A 2×2 table has eigenvalues $3$ and $-1$. What is its trace?',
          answer: V.f4ETrace,
          tolerance: 0,
          hints: [{ text: 'The trace is the sum of the eigenvalues.' }, { text: '$3 + (-1)$.' }, { text: 'It is also $A_{00} + A_{11}$.' }],
          walkthrough: [{ text: '$\\operatorname{tr} = \\lambda_1 + \\lambda_2 = 2$; the determinant would be $-3$.' }],
        },
        {
          id: 'f4-e-eigenvalue',
          kind: 'numeric',
          tier: 'core',
          title: 'The larger eigenvalue',
          prompt: 'What is the larger eigenvalue of $\\tfrac12(X + Z)$?',
          answer: V.f4XZvalHigh,
          tolerance: 0.005,
          hints: [{ text: '$\\operatorname{tr} = 0$, so the eigenvalues are $\\pm\\lambda$.' }, { text: '$\\det = -0.5$.' }, { text: '$\\lambda^2 = 0.5$.' }],
          walkthrough: [{ text: `$\\lambda = \\sqrt{0.5} = ${d(V.f4XZvalHigh, 4)}$; the smaller is $-${d(V.f4XZvalHigh, 4)}$.` }],
        },
        {
          id: 'f4-e-complex',
          kind: 'choice',
          tier: 'core',
          title: 'Which has non-real eigenvalues?',
          prompt: 'Which matrix has non-real eigenvalues?',
          options: [
            { text: '$\\sigma_x$', correct: false, why: 'Hermitian: eigenvalues $\\pm1$.' },
            { text: '$\\sigma_z$', correct: false, why: 'Hermitian: eigenvalues $\\pm1$.' },
            { text: 'the quarter-turn $\\begin{pmatrix}0 & -1\\\\ 1 & 0\\end{pmatrix}$', correct: true, why: 'Its characteristic equation is $\\lambda^2 + 1 = 0$, roots $\\pm i$.' },
            { text: '$\\tfrac12(X + Z)$', correct: false, why: 'Hermitian: eigenvalues real.' },
          ],
          hints: [{ text: 'Real eigenvalues come from Hermitian tables.' }, { text: 'Which one is not its own mirror?' }, { text: 'A rotation fixes no real arrow.' }],
          walkthrough: [{ text: 'The quarter-turn\u2019s characteristic equation is $\\lambda^2 + 1 = 0$, roots $\\pm i$; the others are Hermitian.' }],
        },
        {
          id: 'f4-e-defective',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A defective eigenspace',
          prompt: 'The shear $\\begin{pmatrix}2 & 1\\\\ 0 & 2\\end{pmatrix}$ has one eigenvalue. How many independent eigenvectors?',
          answer: V.f4ShearVecCount,
          tolerance: 0,
          hints: [{ text: 'Solve $(A - 2I)v = 0$.' }, { text: '$\\begin{pmatrix}0 & 1\\\\ 0 & 0\\end{pmatrix}v = 0$.' }, { text: 'Only $v = (1, 0)$ works.' }],
          walkthrough: [{ text: 'The eigenvalue $2$ is defective; its eigenspace is a single line, so the shear is not diagonalizable.' }],
        },
      ],
    },
    {
      id: 'f4-hermitian',
      story: F4_STORY['f4-hermitian'],
      review: F4_REVIEW['f4-hermitian'],
      title: 'Tables equal to their own mirror',
      question: 'Why does a Hermitian table have real eigenvalues and eigenvectors at right angles?',
      lecture: {
        pages: 'Axler 7A pp. 228\u2013238; notes n4 p. 17',
        summary: 'A Hermitian table equals its own mirror. Its eigenvalues are always real (the notes prove this directly), and eigenvectors with different eigenvalues are orthogonal.',
      },
      books: [
        axler('7A, 7.1, 7.5, 7.10\u20137.14, pp. 228\u2013235', 'Adjoints; self-adjoint operators and real eigenvalues.'),
        axler('7A, p. 238', 'Self-adjoint implies real eigenvalues; [[qc-orthogonal|orthogonality]] of eigenvectors.'),
      ],
      visual: {
        kind: 'operator-builder',
        props: { axis: 'y' },
        tryThis: [
          'Step through $S_y$: the corners are $-i$ and $+i$, yet the ✓ for Hermitian holds and the two outcomes $\\pm\\hbar/2$ are real.',
          'Pick tilt and drag the slider: every angle keeps the ✓, whatever the table looks like.',
          'The builder cannot break Hermiticity. For a table that fails it, scroll back to the quarter-turn in the previous unit: its eigenvalues are $\\pm i$.',
        ],
      },
      clues: [],
      insight: 'A Hermitian table equals its own mirror, has real eigenvalues, and eigenvectors with different eigenvalues at right angles.',
      insightFormal: '$A = A^\\dagger \\Rightarrow \\lambda$ real (notes n4 p. 17) and $\\lambda_1 \\ne \\lambda_2 \\Rightarrow \\langle a_2|a_1\\rangle = 0$ (Axler 7A, p. 238); an orthonormal eigenbasis always exists.',
      claims: [C.xzHalfEntry],
      play: [
        {
          id: 'f4-h-ishermitian',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which table is Hermitian?',
          prompt: 'Which table is Hermitian?',
          options: [
            { text: '$\\begin{pmatrix}1 & i\\\\ i & 1\\end{pmatrix}$', correct: false, why: '$A_{10} = i \\ne -i = A_{01}^*$.' },
            { text: '$\\begin{pmatrix}1 & i\\\\ -i & 1\\end{pmatrix}$', correct: true, why: 'Its own mirror: $A_{10} = -i = A_{01}^*$, real diagonal.' },
            { text: '$\\begin{pmatrix}0 & 1\\\\ 0 & 0\\end{pmatrix}$', correct: false, why: 'Not symmetric even without conjugating.' },
            { text: '$\\begin{pmatrix}i & 0\\\\ 0 & 1\\end{pmatrix}$', correct: false, why: 'A non-real diagonal entry is never its own conjugate.' },
          ],
          hints: [{ text: 'Flip across the diagonal and conjugate.' }, { text: 'The corners must be mirrors.' }, { text: 'The diagonal must be real.' }],
          walkthrough: [{ text: '$\\begin{pmatrix}1 & i\\\\ -i & 1\\end{pmatrix}^\\dagger$ equals itself; the first option has $A_{10} = i \\ne -i = A_{01}^*$.' }],
        },
        {
          id: 'f4-h-realeig',
          kind: 'numeric',
          tier: 'core',
          title: 'A real eigenvalue from a complex entry',
          prompt: 'The Hermitian $\\begin{pmatrix}2 & i\\\\ -i & 2\\end{pmatrix}$ has eigenvalues $2 \\pm ?$. Give the larger eigenvalue.',
          answer: V.f4HermEx1Max,
          tolerance: 0,
          hints: [{ text: 'Use $\\tfrac{a+d}2 \\pm \\tfrac12\\sqrt{(a-d)^2 + 4|b|^2}$.' }, { text: '$a = d = 2$, $|b| = 1$.' }, { text: '$2 \\pm 1$.' }],
          walkthrough: [{ text: 'Discriminant $0 + 4 = 4$, so $\\lambda = 2 \\pm 1 = 3, 1$; both real.' }],
        },
        {
          id: 'f4-h-orthogonal',
          kind: 'numeric',
          tier: 'core',
          title: 'Overlap of two eigenvectors',
          prompt: 'The eigenvectors of $\\sigma_x$ for $+1$ and $-1$ are $|{\\pm}x\\rangle$. What is their overlap $|\\langle{+}x|{-}x\\rangle|$?',
          answer: V.f4PlusMinusXOverlap,
          tolerance: 0.005,
          hints: [{ text: 'Different eigenvalues force orthogonality.' }, { text: '$|{\\pm}x\\rangle = (1, \\pm1)/\\sqrt2$.' }, { text: '$\\tfrac12(1 - 1)$.' }],
          walkthrough: [{ text: '$\\langle{+}x|{-}x\\rangle = \\tfrac12(1\\cdot1 + 1\\cdot(-1)) = 0$: perpendicular directions.' }],
        },
        {
          id: 'f4-h-gs',
          kind: 'choice',
          tier: 'stretch',
          title: 'Why Gram\u2013Schmidt lands on an eigenvector',
          prompt:
            'Spin 1 has three $S_x$ eigenstates. Take $|{+1}z\\rangle$, subtract its shadows on $|{+1}x\\rangle$ and $|{-1}x\\rangle$, and normalize the leftover. Why must the leftover be an $S_x$ eigenvector?',
          options: [
            { text: 'Gram\u2013Schmidt always returns an eigenvector of whatever operator you are studying.', correct: false, why: 'It only returns a vector orthogonal to the ones kept so far; the operator plays no part in the recipe.' },
            { text: '$|{+1}z\\rangle$ is already an $S_x$ eigenvector, and subtracting shadows keeps it one.', correct: false, why: '$|{+1}z\\rangle$ is not an $S_x$ eigenvector, and subtracting shadows moves it off whatever line it was on.' },
            {
              text: '$S_x$ is Hermitian, so its eigenvectors form an orthonormal basis; the only direction orthogonal to $|{\\pm1}x\\rangle$ is the third eigenvector.',
              correct: true,
              why: 'A Hermitian operator has a full orthonormal set of eigenvectors, so the leftover orthogonal to two of them can only be the third.',
            },
            { text: 'The subtracted shadows are the $S_x$ eigenvalues, so what is left carries eigenvalue $0$.', correct: false, why: 'The shadows are parts of a vector, not eigenvalues; the eigenvalue $0$ is a consequence, not the reason.' },
          ],
          hints: [
            { text: 'What does Gram\u2013Schmidt guarantee about the leftover, in terms of the vectors already kept?' },
            { text: 'The leftover is orthogonal to $|{+1}x\\rangle$ and $|{-1}x\\rangle$. What is special about the eigenvectors of a Hermitian operator?' },
            { text: 'Three orthonormal vectors fill a 3-dimensional space: only one direction is left once two are fixed.' },
          ],
          walkthrough: [
            { text: 'Gram\u2013Schmidt guarantees one thing only: the leftover is orthogonal to the vectors already kept, here $|{+1}x\\rangle$ and $|{-1}x\\rangle$.' },
            { text: '$S_x$ is Hermitian, so its three eigenvectors are orthonormal and fill the space. The only direction orthogonal to two of them is the third.' },
            { text: 'So the leftover is the $S_x$ eigenvector with eigenvalue $0$. Chapter F2 works the numbers: the leftover points along $(1, 0, -1)$.' },
          ],
        },
      ],
    },
    {
      id: 'f4-spectral',
      story: F4_STORY['f4-spectral'],
      review: F4_REVIEW['f4-spectral'],
      title: 'Building and reading a matrix by its directions',
      question: 'How does a Hermitian table split into its directions, and how do functions act on it?',
      lecture: {
        pages: 'Axler 7B pp. 245\u2013246; N&C §2.1.6 Box 2.2 p. 72, §2.1.8 p. 75; notes n4 p. 17',
        summary: 'A Hermitian table is a sum of its eigenvalues times their projectors. In its own basis it is diagonal, and a function of the table acts on the eigenvalues alone.',
      },
      books: [
        axler('7B, 7.29, 7.31, pp. 245\u2013246', 'The real and the complex spectral theorems.'),
        { source: 'nc', where: '§2.1.6 Box 2.2, p. 72; §2.1.8, p. 75', adds: 'The spectral decomposition, and the functional calculus.' },
      ],
      visual: {
        kind: 'operator-builder',
        props: { axis: 'x' },
        tryThis: [
          'Step to the end: the last line is the spectral sum $\\tfrac\\hbar2P_+ - \\tfrac\\hbar2P_-$, the two outcomes as weights on the two projectors.',
          'Pick tilt, set $45^\\circ$ and step to the end: the same sum rebuilds $\\tfrac\\hbar2\\sigma_n$ for that axis.',
          'The weights here stay $\\pm\\tfrac\\hbar2$. To see a function act on them, scroll the story to the function beat: squaring turns $\\pm1$ into $1$.',
        ],
      },
      clues: [],
      insight: 'A Hermitian table is $\\sum_i \\lambda_i|a_i\\rangle\\langle a_i|$, diagonal in its own basis, and a function of it acts on the eigenvalues alone.',
      insightFormal: 'The spectral theorem $A = \\sum_i \\lambda_i|a_i\\rangle\\langle a_i|$ (Axler Eq. 7.31) gives $B^\\dagger A B = \\operatorname{diag}(\\lambda_i)$ and the functional calculus $f(A) = \\sum_i f(\\lambda_i)|a_i\\rangle\\langle a_i|$ (N&C §2.1.8).',
      claims: [C.xzHalfEntry, C.halfIXentry],
      play: [
        {
          id: 'f4-s-square',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Squaring the eigenvalues',
          prompt: '$\\sigma_x$ has eigenvalues $\\pm1$. What is the (repeated) eigenvalue of $\\sigma_x^2$?',
          answer: V.f4XsqEigVal,
          tolerance: 0,
          hints: [{ text: 'A function acts on the eigenvalues.' }, { text: 'Square each of $\\pm1$.' }, { text: '$(\\pm1)^2 = 1$.' }],
          walkthrough: [{ text: '$\\sigma_x^2 = I$, eigenvalues $1$ and $1$.' }],
        },
        {
          id: 'f4-s-rebuild',
          kind: 'numeric',
          tier: 'core',
          title: 'Rebuilding a table from its spectrum',
          prompt: 'Add the projectors with weights $+1$ and $-1$: $(+1)|{+}x\\rangle\\langle{+}x| + (-1)|{-}x\\rangle\\langle{-}x|$. What is the top-right entry?',
          answer: V.f4SpectralRebuildTR,
          tolerance: 0,
          hints: [{ text: 'This is a spectral decomposition.' }, { text: 'It rebuilds a Pauli matrix.' }, { text: 'Which one has eigenvectors $|{\\pm}x\\rangle$?' }],
          walkthrough: [{ text: 'The sum is $\\sigma_x = \\begin{pmatrix}0 & 1\\\\ 1 & 0\\end{pmatrix}$; the top-right is $1$.' }],
        },
        {
          id: 'f4-s-diagonal',
          kind: 'numeric',
          tier: 'core',
          title: 'Diagonalizing in its own basis',
          prompt: 'Diagonalize $\\tfrac12(X + Z)$ in its own basis, with $|{+}n\\rangle$ first. What is its top-left diagonal entry?',
          answer: V.f4XZvalHigh,
          tolerance: 0.005,
          hints: [{ text: 'In its own basis a Hermitian table is diagonal.' }, { text: 'The diagonal holds the eigenvalues.' }, { text: 'The larger is $+1/\\sqrt2$.' }],
          walkthrough: [{ text: `$B^\\dagger A B = \\operatorname{diag}(${d(V.f4XZvalHigh, 4)}, -${d(V.f4XZvalHigh, 4)})$.` }],
        },
        {
          id: 'f4-s-exp',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A function of a Hermitian table',
          prompt: 'For $K = \\tfrac12\\sigma_z$, the unitary $e^{-iK\\cdot\\pi}$ has which diagonal entries? Give the real part of the top-left one.',
          answer: V.f4ExpHalfZPiRe,
          tolerance: 0.005,
          hints: [{ text: '$f(A)$ acts on the eigenvalues $\\pm\\tfrac12$.' }, { text: '$e^{-i(\\pm1/2)\\pi} = e^{\\mp i\\pi/2}$.' }, { text: '$e^{-i\\pi/2} = -i$.' }],
          walkthrough: [{ text: 'Diagonal $e^{-i\\pi/2} = -i$ and $e^{i\\pi/2} = i$; the real part of each is $0$.' }],
        },
      ],
    },
    {
      id: 'f4-unitary',
      story: F4_STORY['f4-unitary'],
      review: F4_REVIEW['f4-unitary'],
      title: 'Machines that keep every length',
      question: 'What does a table that keeps all lengths look like, and why are its eigenvalues on the unit circle?',
      lecture: {
        pages: 'Axler 7D pp. 260\u2013261; notes n2 p. 9',
        summary: 'A unitary table keeps every length, $U^\\dagger U = I$. Its eigenvalues have size 1, on the unit circle, and $e^{-iKt}$ turns the [[qc-bloch-sphere|Bloch sphere]] about a Hermitian $K$\u2019s own axis.',
      },
      books: [axler('7D, 7.53, pp. 260\u2013261', 'Isometries and unitary operators.')],
      visual: {
        kind: 'bloch',
        props: { theta: 90, phi: 0, rotations: true },
        tryThis: [
          'Press $R_z(180^\\circ)$: where does $|{+}x\\rangle$ go? It lands on $|{-}x\\rangle$, the opposite point of the equator.',
          'Press $R_z(360^\\circ)$: the arrow comes home, but both phasors now read $-1/\\sqrt2$. The whole state picked up a factor $-1$, the eigenvalue $e^{-i\\pi}$ of this turn.',
          'Set $\\theta = 0$ and press any $R_z$: $|0\\rangle$ never moves, because it is an eigenvector of every $R_z$.',
        ],
      },
      clues: [],
      insight: 'A unitary keeps every length, $U^\\dagger U = I$; its eigenvalues have size 1, on the unit circle.',
      insightFormal: '$U^\\dagger U = UU^\\dagger = I \\Leftrightarrow \\|Uv\\| = \\|v\\|$ for all $v$; every eigenvalue is $e^{i\\theta}$, and $e^{-iKt}$ is a unitary sharing $K$\u2019s eigenvectors.',
      claims: [C.halfZentry],
      play: [
        {
          id: 'f4-u-isunitary',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which table keeps every length?',
          prompt: 'Which table keeps every length?',
          options: [
            { text: '$\\tfrac12(X + Z)$', correct: false, why: 'A Hermitian table whose stretches are $\\pm1/\\sqrt2$: it shrinks every arrow along its eigen-directions, so it is not length-preserving.' },
            { text: 'the Hadamard $\\tfrac1{\\sqrt2}\\begin{pmatrix}1 & 1\\\\ 1 & -1\\end{pmatrix}$', correct: true, why: '$H^\\dagger H = I$.' },
            { text: '$\\begin{pmatrix}2 & 0\\\\ 0 & 1\\end{pmatrix}$', correct: false, why: 'A stretch by $2$ changes a length.' },
            { text: '$|{+}x\\rangle\\langle{+}x|$', correct: false, why: 'A projector shortens arrows outside its own direction.' },
          ],
          hints: [{ text: 'Columns must be perpendicular unit arrows.' }, { text: 'A projector shortens arrows.' }, { text: 'A stretch by $2$ changes a length.' }],
          walkthrough: [{ text: '$H^\\dagger H = I$; the others stretch or shorten some arrow.' }],
        },
        {
          id: 'f4-u-unitcircle',
          kind: 'numeric',
          tier: 'core',
          title: 'Size of a unitary\u2019s eigenvalue',
          prompt: 'The phase gate $S = \\operatorname{diag}(1, i)$ is unitary. What is the size of each eigenvalue?',
          answer: V.f4SAbsEig,
          tolerance: 0.005,
          hints: [{ text: 'A unitary keeps lengths.' }, { text: 'So $|\\lambda| = 1$.' }, { text: '$|1| = |i| = 1$.' }],
          walkthrough: [{ text: 'Eigenvalues $1$ and $i$, both on the unit circle.' }],
        },
        {
          id: 'f4-u-rotation',
          kind: 'numeric',
          tier: 'core',
          title: 'A unitary as a turn',
          prompt: '$e^{-i\\sigma_z t}$ turns the Bloch sphere about $z$. By what angle, in degrees, at $t = \\pi/2$?',
          answer: V.f4RzHalfPiAngleDeg,
          tolerance: 0.5,
          hints: [{ text: '$e^{-i\\theta\\,\\mathbf n\\cdot\\boldsymbol\\sigma/2}$ turns by $\\theta$.' }, { text: 'Here $K = \\sigma_z = 2\\cdot\\tfrac12\\sigma_z$.' }, { text: '$\\theta = 2t = \\pi$.' }],
          walkthrough: [{ text: '$\\sigma_z = \\mathbf n\\cdot\\boldsymbol\\sigma$ with $|\\mathbf n| = 1$, so the turn is $2t = \\pi = 180^\\circ$.' }],
        },
        {
          id: 'f4-u-hermunit',
          kind: 'choice',
          tier: 'stretch',
          title: 'Hermitian and unitary together',
          prompt: 'A table is both Hermitian and unitary. Its eigenvalues are:',
          options: [
            { text: 'any real numbers', correct: false, why: 'Unitary also forces size 1.' },
            { text: 'any numbers of size 1', correct: false, why: 'Hermitian also forces them real.' },
            { text: 'only $+1$ and $-1$', correct: true, why: 'Real (Hermitian) $\\cap$ size-1 (unitary) $= \\{+1, -1\\}$.' },
            { text: 'only $+1$', correct: false, why: '$-1$ is also real and of size 1.' },
          ],
          hints: [{ text: 'Hermitian makes them real.' }, { text: 'Unitary makes them size 1.' }, { text: 'Which reals have size 1?' }],
          walkthrough: [{ text: '$\\lambda$ real and $|\\lambda| = 1$ gives $\\lambda = \\pm1$, so $A^2 = I$.' }],
        },
      ],
    },
    {
      id: 'f4-commuting',
      story: F4_STORY['f4-commuting'],
      review: F4_REVIEW['f4-commuting'],
      title: 'When two machines share directions',
      question: 'When can two tables be diagonalized at once, and what does that mean?',
      lecture: {
        pages: 'Axler 5E p. 175; notes n4 pp. 18\u201319',
        summary: 'Two Hermitian tables share a full eigenbasis exactly when they commute, $[A, B] = 0$. Otherwise, as with $\\sigma_x$ and $\\sigma_z$, no shared basis exists.',
      },
      books: [axler('5E, p. 175', 'Simultaneous diagonalizability.')],
      visual: {
        kind: 'operator-action',
        props: { a: 1, b: 0, d: -1 },
        tryThis: [
          'Tick show eigen-directions: the two lines are the axes, the $z$ directions of $\\sigma_z$.',
          'Press P+z: the lines stay on the axes. The two tables share a basis, and $\\sigma_z$ and $P_{+z}$ commute.',
          'Press σx: the lines turn to $\\pm45^\\circ$. They are no longer the axes, so $\\sigma_x$ shares no basis with $\\sigma_z$.',
        ],
      },
      clues: [],
      insight: 'Two Hermitian tables share a full eigenbasis exactly when they commute, $[A, B] = 0$.',
      insightFormal: '$[A, B] = 0 \\Leftrightarrow$ a common orthonormal eigenbasis exists (Axler 5E); distinct eigenvalues of $A$ force $B$ diagonal in $A$\u2019s basis.',
      claims: [C.pzCoef],
      play: [
        {
          id: 'f4-c-commute',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which pair commutes?',
          prompt: 'Which pair commutes?',
          options: [
            { text: '$\\sigma_x, \\sigma_z$', correct: false, why: '$[\\sigma_x, \\sigma_z] = -2i\\sigma_y \\ne 0$.' },
            { text: '$\\sigma_z, \\operatorname{diag}(1, 0)$', correct: true, why: 'Both diagonal in the same ($z$) basis.' },
            { text: '$\\sigma_x, \\sigma_y$', correct: false, why: 'The Paulis $x, y, z$ do not commute.' },
            { text: '$\\sigma_y, \\sigma_z$', correct: false, why: 'The Paulis $x, y, z$ do not commute.' },
          ],
          hints: [{ text: 'Diagonal tables commute.' }, { text: 'Which pair is diagonal in the same basis?' }, { text: 'The Paulis $x, y, z$ do not commute.' }],
          walkthrough: [{ text: '$\\sigma_z$ and $\\operatorname{diag}(1, 0)$ are both $z$-diagonal, so $[A, B] = 0$.' }],
        },
        {
          id: 'f4-c-commutator',
          kind: 'numeric',
          tier: 'core',
          title: 'The size of a commutator',
          prompt: 'What is the largest entry size of $[\\sigma_x, \\sigma_z] = \\sigma_x\\sigma_z - \\sigma_z\\sigma_x$?',
          answer: V.f4XZcomm,
          tolerance: 0,
          hints: [{ text: '$[\\sigma_x, \\sigma_z] = -2i\\sigma_y$.' }, { text: '$\\sigma_y$ has entries of size 1.' }, { text: '$|{-2i}| = 2$.' }],
          walkthrough: [{ text: '$[\\sigma_x, \\sigma_z] = \\begin{pmatrix}0 & -2\\\\ 2 & 0\\end{pmatrix}$ (that is $-2i\\sigma_y$); the largest entry is $2$.' }],
        },
        {
          id: 'f4-c-simul',
          kind: 'choice',
          tier: 'stretch',
          title: 'When a shared eigenbasis exists',
          prompt: 'Two Hermitian tables share a full eigenbasis exactly when:',
          options: [
            { text: 'they have the same trace', correct: false, why: 'Equal traces say nothing about shared directions.' },
            { text: 'they commute', correct: true, why: '$[A, B] = 0 \\Leftrightarrow$ a shared eigenbasis.' },
            { text: 'one is a multiple of the other', correct: false, why: 'Too strong a condition — commuting is enough.' },
            { text: 'both are unitary', correct: false, why: 'Unitarity says nothing about sharing a basis with another table.' },
          ],
          hints: [{ text: 'Think about diagonal tables.' }, { text: 'Diagonal tables commute, and conversely.' }, { text: 'The test is $AB = BA$.' }],
          walkthrough: [{ text: 'A shared eigenbasis $\\Leftrightarrow [A, B] = 0$ (both diagonal there).' }],
        },
      ],
    },
    {
      id: 'f4-positive',
      story: F4_STORY['f4-positive'],
      review: F4_REVIEW['f4-positive'],
      title: 'Tables with no negative stretch; square roots',
      question: 'Which tables never flip an arrow backwards, and how do we take a square root of a matrix?',
      lecture: {
        pages: 'Axler 7C pp. 251\u2013253, 7E p. 273, 7F p. 286',
        summary: 'A positive table never stretches an arrow backwards: no negative eigenvalue. It has a unique positive square root, and any table at all splits into a turn times a positive stretch (the polar decomposition).',
      },
      books: [
        axler('7C, 7.34, 7.38, pp. 251\u2013252', 'Positive operators.'),
        axler('7C, 7.36, 7.39, pp. 251\u2013253', 'The positive square root.'),
        axler('7E\u20137F, 7.70, 7.93, pp. 273, 286', 'The singular-value decomposition and the polar decomposition.'),
      ],
      visual: {
        kind: 'operator-action',
        props: { preset: 'P+x' },
        tryThis: [
          'Tick show eigen-directions: the eigenvalues of $P_{+x}$ are $0$ and $1$, none negative.',
          'Press σz: a $-1$ appears among the eigenvalues, so σz is not positive.',
          'Press [[2,1],[1,2]]: the eigenvalues are $1$ and $3$, positive but not a projector.',
        ],
      },
      clues: [],
      insight: 'A positive table never stretches an arrow backwards. It has a unique positive square root, and any table splits into a turn times a positive stretch.',
      insightFormal: '$A \\ge 0 \\Leftrightarrow A = A^\\dagger$ and spectrum $\\ge 0$ (Axler Eq. 7.34 and 7.38); $\\sqrt A$ is the unique positive operator with $(\\sqrt A)^2 = A$ (Axler Eq. 7.36); every $A = U|A|$ (Axler Eq. 7.93).',
      claims: [C.xzHalfEntry, C.halfIXentry],
      play: [
        {
          id: 'f4-p-positive',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which table is positive?',
          prompt: 'Which table is positive ($A \\ge 0$)?',
          options: [
            { text: '$\\sigma_z$', correct: false, why: 'Has eigenvalue $-1$.' },
            { text: '$|{+}x\\rangle\\langle{+}x|$', correct: true, why: 'Eigenvalues $1, 0$: none negative.' },
            { text: '$\\sigma_y$', correct: false, why: 'Has eigenvalue $-1$.' },
            { text: '$\\begin{pmatrix}1 & 2\\\\ 2 & 1\\end{pmatrix}$', correct: false, why: 'Eigenvalues $3$ and $-1$: one is negative.' },
          ],
          hints: [{ text: 'Positive means no negative eigenvalue.' }, { text: 'A projector\u2019s eigenvalues are $0$ and $1$.' }, { text: '$\\sigma_z$ has a $-1$.' }],
          walkthrough: [{ text: 'The projector is $\\ge 0$; the others have a negative eigenvalue.' }],
        },
        {
          id: 'f4-p-sqrt',
          kind: 'numeric',
          tier: 'core',
          title: 'Square root of a diagonal table',
          prompt: 'The positive table $\\operatorname{diag}(4, 9)$ has a positive square root. What is its larger diagonal entry?',
          answer: V.f4SqrtDiag49Val,
          tolerance: 0,
          hints: [{ text: 'The square root acts on the eigenvalues.' }, { text: '$\\sqrt4 = 2$, $\\sqrt9 = 3$.' }, { text: 'Same directions, rooted stretches.' }],
          walkthrough: [{ text: '$\\sqrt{\\operatorname{diag}(4, 9)} = \\operatorname{diag}(2, 3)$.' }],
        },
        {
          id: 'f4-p-svd',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Singular values of a non-Hermitian table',
          prompt: 'The shear $\\begin{pmatrix}2 & 1\\\\ 0 & 2\\end{pmatrix}$ is not Hermitian. What is its largest singular value?',
          answer: V.f4ShearSV0,
          tolerance: 0.005,
          hints: [{ text: 'Singular values are $\\sqrt{\\text{eigenvalues of } A^\\dagger A}$.' }, { text: '$A^\\dagger A = \\begin{pmatrix}4 & 2\\\\ 2 & 5\\end{pmatrix}$.' }, { text: `Its larger eigenvalue is $${d(V.f4ShearSV0 ** 2, 2)}$.` }],
          walkthrough: [{ text: `Singular values $${d(V.f4ShearSV0, 4)}, ${d(V.f4ShearSV1, 4)}$ — the eigenvalues of $|A|$, unlike the repeated eigenvalue $2$ of the table itself.` }],
        },
      ],
    },
  ],
}
