/**
 * Physics 709 chapter F4 "Eigenvalues, Hermitian and unitary operators, the spectral theorem": the canonical owner
 * of eigenvalues/eigenvectors, the characteristic equation, Hermitian and unitary operators and the spectral
 * theorem. The fourth Foundations chapter (no lecture notes: its own line is phase 'core'); it builds on F1
 * (complex numbers), F2 (vectors, inner products) and F3 (matrices, the adjoint, change of basis), all merged, and
 * is the bridge target every later chapter reaches for when it diagonalizes an observable or exponentiates a
 * Hamiltonian.
 *
 * Plan: docs/roles/proposals/P-F4-story.md; rulings docs/roles/decisions/qc709-foundations.md,
 * qc709-foundations-rulings.md, qc709-nc.md (ruling 1: "Hermitian ⇒ real eigenvalues" is 448 L3 homework, so F4
 * states and cites it at `f4-hermitian:b3` without deriving it — only the orthogonality half is derived, at
 * `f4-hermitian:b4`). Every number a learner sees is computed in F4.values.ts and asserted in keyed claims
 * (content.test.tsx runs `holds`; claims.test.ts compares each key with its numpy twin in
 * physics/__fixtures__/claims-qc709/f4.json).
 */
import type { Lecture } from '../schema'
import { F4_REVIEW } from './F4.review'
import { axler, F4_STORY } from './F4.story'
import { V, d } from './F4.values'

export const F4: Lecture = {
  id: 'F4',
  number: 4,
  title: 'Eigenvalues, Hermitian and unitary operators',
  outcomes: [
    'Find the arrows a matrix only stretches, and the stretch factors, from the characteristic equation.',
    'Say why a table equal to its own mirror has real stretches and right-angle directions.',
    'Rebuild a Hermitian table from its directions, read it in its own frame, and apply a function to it.',
    'Recognise a table that keeps every length, and say why its stretches sit on the unit circle.',
    'Decide when two tables can be diagonalized together, and name their shared directions.',
    'Tell a table with no backward stretch, and take its square root.',
  ],
  prerequisites: ['qc-orthonormal-basis', 'qc-matrix-of-map', 'qc-adjoint', 'qc-change-of-basis-station', 'qc-euler'],
  symbols: {
    A: 'F4.outcomes[0]',
    B: 'F4.outcomes[0]',
    D: 'F4.outcomes[0]',
    U: 'F4.outcomes[0]',
    I: 'F4.outcomes[0]',
    P: 'F4.outcomes[0]',
    R: 'F4.outcomes[0]',
    S: 'F4.outcomes[0]',
    H: 'F4.outcomes[0]',
    X: 'F4.outcomes[0]',
    Z: 'F4.outcomes[0]',
    a: 'F4.outcomes[0]',
    b: 'F4.outcomes[0]',
    c: 'F4.outcomes[0]',
    d: 'F4.outcomes[0]',
    e: 'F4.outcomes[0]',
    f: 'F4.outcomes[0]',
    i: 'F4.outcomes[0]',
    j: 'F4.outcomes[0]',
    n: 'F4.outcomes[0]',
    t: 'F4.outcomes[0]',
    v: 'F4.outcomes[0]',
    w: 'F4.outcomes[0]',
    '\\lambda': 'F4.outcomes[0]',
    '\\lambda_1': 'F4.outcomes[0]',
    '\\lambda_2': 'F4.outcomes[0]',
    '\\lambda_i': 'F4.outcomes[0]',
    '\\lambda_j': 'F4.outcomes[0]',
    '\\theta': 'F4.outcomes[0]',
    '\\pi': 'F4.outcomes[0]',
    '\\delta_ij': 'F4.outcomes[0]',
    '\\delta_\\lambda\\mu': 'F4.outcomes[0]',
    '\\dagger': 'F4.outcomes[0]',
    '\\sigma': 'F4.outcomes[0]',
    '\\sigma_x': 'F4.outcomes[0]',
    '\\sigma_y': 'F4.outcomes[0]',
    '\\sigma_z': 'F4.outcomes[0]',
    '\\sigma_n': 'F4.outcomes[0]',
    '\\boldsymbol': 'F4.outcomes[0]',
    '\\otimes': 'F4.outcomes[0]',
    '\\not': 'F4.outcomes[0]',
    '|\\cdot\\rangle': 'F4.outcomes[0]',
    '\\langle\\cdot|': 'F4.outcomes[0]',
    '\\langle\\cdot|\\cdot\\rangle': 'F4.outcomes[0]',
    '|a\\rangle': 'F4.outcomes[0]',
    '|a_1\\rangle': 'F4.outcomes[0]',
    '|a_2\\rangle': 'F4.outcomes[0]',
    '|a_i\\rangle': 'F4.outcomes[0]',
    '|a_j\\rangle': 'F4.outcomes[0]',
    '|Aa_2\\rangle': 'F4.outcomes[0]',
    '|+n\\rangle': 'F4.outcomes[0]',
    '|-n\\rangle': 'F4.outcomes[0]',
    '|+x\\rangle': 'F4.outcomes[0]',
    '|-x\\rangle': 'F4.outcomes[0]',
    '|v\\rangle': 'F4.outcomes[0]',
    '|w\\rangle': 'F4.outcomes[0]',
    '|Uv\\rangle': 'F4.outcomes[0]',
    '|Uw\\rangle': 'F4.outcomes[0]',
    '|0\\rangle': 'F4.outcomes[0]',
    '|1\\rangle': 'F4.outcomes[0]',
    'A_00': 'F4.outcomes[0]',
    'A_11': 'F4.outcomes[0]',
    'A_ij': 'F4.outcomes[0]',
    'A_ji': 'F4.outcomes[0]',
    'A_10': 'F4.outcomes[0]',
    'A_01': 'F4.outcomes[0]',
    'b_10': 'F4.outcomes[0]',
    'b_01': 'F4.outcomes[0]',
    'S_x': 'F4.outcomes[0]',
    'P_\\lambda': 'F4.outcomes[0]',
    'P_\\mu': 'F4.outcomes[0]',
    'P_\\pm': 'F4.outcomes[0]',
    'P_+x': 'F4.outcomes[0]',
    'P_-x': 'F4.outcomes[0]',
    'P_+z': 'F4.outcomes[0]',
    'P_+': 'F4.outcomes[0]',
    'P_-': 'F4.outcomes[0]',
    '\\Sigma': 'F4.outcomes[0]',
    'V': 'F4.outcomes[0]',
  },
  units: [
    {
      id: 'f4-eigen',
      story: F4_STORY['f4-eigen'],
      review: F4_REVIEW['f4-eigen'],
      title: 'The arrows a machine only stretches',
      question: 'Which directions does a matrix leave in place, only scaling them, and how do we find the scales?',
      lecture: {
        pages: 'Axler 5A p. 133, 5D p. 163; notes p. 14',
        summary: 'An eigenvector is an arrow a matrix only stretches, by its eigenvalue. The scales solve the characteristic equation, and can be complex, repeated, or (for a defective table) short of a full set.',
      },
      books: [
        axler('5A, 5.5\u20135.8, p. 133', 'Eigenvalues, eigenvectors, the characteristic idea.'),
        axler('5D, 5.27, p. 163', 'The characteristic polynomial of a 2×2 operator.'),
      ],
      visual: {
        kind: 'operator-action',
        props: { op: { matrix: [['1/2', '1/2'], ['1/2', '-1/2']] }, mode: 'eigen' },
        tryThis: [
          'Make the operator arrow point along $z$: what are the two eigenvalues?',
          'Shrink it to zero: when is the matrix $\\lambda I$?',
          'Point it at $45^\\circ$: read the $\\pm0.707$ bars.',
        ],
      },
      clues: [],
      insight: 'An eigenvector is an arrow a matrix only stretches; the stretch, its eigenvalue, solves the characteristic equation.',
      insightFormal: '$A|a\\rangle = \\lambda|a\\rangle$ ($|a\\rangle \\ne 0$) defines an eigenpair; $\\det(A - \\lambda I) = 0$ finds every $\\lambda$, real or complex.',
      play: [
        {
          id: 'f4-e-trace',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Trace from eigenvalues',
          prompt: 'A 2×2 table has eigenvalues $3$ and $-1$. What is its trace?',
          answer: V.f4ETrace,
          tolerance: 0,
          hints: [{ text: 'The trace is the sum of the eigenvalues.' }, { text: '$3 + (-1)$.' }, { text: 'It is also $A_{00} + A_{11}$.' }],
          walkthrough: [{ text: '$\\operatorname{tr} = \\lambda_1 + \\lambda_2 = 2$; the determinant would be $-3$.' }],
        },
        {
          id: 'f4-e-eigenvalue',
          kind: 'numeric',
          tier: 'core',
          title: 'The larger eigenvalue',
          prompt: 'What is the larger eigenvalue of $\\tfrac12(X + Z)$?',
          answer: V.f4XZvalHigh,
          tolerance: 0.005,
          hints: [{ text: '$\\operatorname{tr} = 0$, so the eigenvalues are $\\pm\\lambda$.' }, { text: '$\\det = -0.5$.' }, { text: '$\\lambda^2 = 0.5$.' }],
          walkthrough: [{ text: `$\\lambda = \\sqrt{0.5} = ${d(V.f4XZvalHigh, 4)}$; the smaller is $-${d(V.f4XZvalHigh, 4)}$.` }],
        },
        {
          id: 'f4-e-complex',
          kind: 'choice',
          tier: 'core',
          title: 'Which has non-real eigenvalues?',
          prompt: 'Which matrix has non-real eigenvalues?',
          options: [
            { text: '$\\sigma_x$', correct: false, why: 'Hermitian: eigenvalues $\\pm1$.' },
            { text: '$\\sigma_z$', correct: false, why: 'Hermitian: eigenvalues $\\pm1$.' },
            { text: 'the quarter-turn $\\begin{pmatrix}0 & -1\\\\ 1 & 0\\end{pmatrix}$', correct: true, why: 'Its characteristic equation is $\\lambda^2 + 1 = 0$, roots $\\pm i$.' },
            { text: '$\\tfrac12(X + Z)$', correct: false, why: 'Hermitian: eigenvalues real.' },
          ],
          hints: [{ text: 'Real eigenvalues come from Hermitian tables.' }, { text: 'Which one is not its own mirror?' }, { text: 'A rotation fixes no real arrow.' }],
          walkthrough: [{ text: 'The quarter-turn\u2019s characteristic equation is $\\lambda^2 + 1 = 0$, roots $\\pm i$; the others are Hermitian.' }],
        },
        {
          id: 'f4-e-defective',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A defective eigenspace',
          prompt: 'The shear $\\begin{pmatrix}2 & 1\\\\ 0 & 2\\end{pmatrix}$ has one eigenvalue. How many independent eigenvectors?',
          answer: V.f4ShearVecCount,
          tolerance: 0,
          hints: [{ text: 'Solve $(A - 2I)v = 0$.' }, { text: '$\\begin{pmatrix}0 & 1\\\\ 0 & 0\\end{pmatrix}v = 0$.' }, { text: 'Only $v = (1, 0)$ works.' }],
          walkthrough: [{ text: 'The eigenvalue $2$ is defective; its eigenspace is a single line, so the shear is not diagonalizable.' }],
        },
      ],
    },
    {
      id: 'f4-hermitian',
      story: F4_STORY['f4-hermitian'],
      review: F4_REVIEW['f4-hermitian'],
      title: 'Tables equal to their own mirror',
      question: 'Why does a Hermitian table have real eigenvalues and eigenvectors at right angles?',
      lecture: {
        pages: 'Axler 7A pp. 228\u2013235, 7B p. 243; notes p. 15',
        summary: 'A Hermitian table equals its own mirror. Its eigenvalues are always real (the notes prove this directly), and eigenvectors with different eigenvalues are at right angles.',
      },
      books: [
        axler('7A, 7.1, 7.5, 7.10\u20137.14, pp. 228\u2013235', 'Adjoints; self-adjoint operators and real eigenvalues.'),
        axler('7B, 7.22, p. 243', 'Self-adjoint implies real eigenvalues; [[qc-orthogonal|orthogonality]] of eigenvectors.'),
      ],
      visual: {
        kind: 'operator-builder',
        props: { mode: 'edit-hermitian' },
        tryThis: [
          'Set a complex corner $b = i$: are the bars still real?',
          'Make the two diagonal entries equal: find the degenerate case.',
          'Break Hermiticity ($b_{10} \\ne b_{01}^*$) and watch a bar leave the real line.',
        ],
      },
      clues: [],
      insight: 'A Hermitian table equals its own mirror, has real eigenvalues, and eigenvectors with different eigenvalues at right angles.',
      insightFormal: '$A = A^\\dagger \\Rightarrow \\lambda$ real (notes p. 15) and $\\lambda_1 \\ne \\lambda_2 \\Rightarrow \\langle a_2|a_1\\rangle = 0$ (Axler 7.22); an orthonormal eigenbasis always exists.',
      play: [
        {
          id: 'f4-h-ishermitian',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which table is Hermitian?',
          prompt: 'Which table is Hermitian?',
          options: [
            { text: '$\\begin{pmatrix}1 & i\\\\ i & 1\\end{pmatrix}$', correct: false, why: '$A_{10} = i \\ne -i = A_{01}^*$.' },
            { text: '$\\begin{pmatrix}1 & i\\\\ -i & 1\\end{pmatrix}$', correct: true, why: 'Its own mirror: $A_{10} = -i = A_{01}^*$, real diagonal.' },
            { text: '$\\begin{pmatrix}0 & 1\\\\ 0 & 0\\end{pmatrix}$', correct: false, why: 'Not symmetric even without conjugating.' },
            { text: '$\\begin{pmatrix}i & 0\\\\ 0 & 1\\end{pmatrix}$', correct: false, why: 'A complex diagonal entry is never its own conjugate.' },
          ],
          hints: [{ text: 'Flip across the diagonal and conjugate.' }, { text: 'The corners must be mirrors.' }, { text: 'The diagonal must be real.' }],
          walkthrough: [{ text: '$\\begin{pmatrix}1 & i\\\\ -i & 1\\end{pmatrix}^\\dagger$ equals itself; the first option has $A_{10} = i \\ne -i = A_{01}^*$.' }],
        },
        {
          id: 'f4-h-realeig',
          kind: 'numeric',
          tier: 'core',
          title: 'A real eigenvalue from a complex entry',
          prompt: 'The Hermitian $\\begin{pmatrix}2 & i\\\\ -i & 2\\end{pmatrix}$ has eigenvalues $2 \\pm ?$. Give the larger eigenvalue.',
          answer: V.f4HermEx1Max,
          tolerance: 0,
          hints: [{ text: 'Use $\\tfrac{a+d}2 \\pm \\tfrac12\\sqrt{(a-d)^2 + 4|b|^2}$.' }, { text: '$a = d = 2$, $|b| = 1$.' }, { text: '$2 \\pm 1$.' }],
          walkthrough: [{ text: 'Discriminant $0 + 4 = 4$, so $\\lambda = 2 \\pm 1 = 3, 1$; both real.' }],
        },
        {
          id: 'f4-h-orthogonal',
          kind: 'numeric',
          tier: 'core',
          title: 'Overlap of two eigenvectors',
          prompt: 'The eigenvectors of $\\sigma_x$ for $+1$ and $-1$ are $|{\\pm}x\\rangle$. What is their overlap $|\\langle{+}x|{-}x\\rangle|$?',
          answer: V.f4PlusMinusXOverlap,
          tolerance: 0.005,
          hints: [{ text: 'Different eigenvalues force orthogonality.' }, { text: '$|{\\pm}x\\rangle = (1, \\pm1)/\\sqrt2$.' }, { text: '$\\tfrac12(1 - 1)$.' }],
          walkthrough: [{ text: '$\\langle{+}x|{-}x\\rangle = \\tfrac12(1\\cdot1 + 1\\cdot(-1)) = 0$: perpendicular directions.' }],
        },
        {
          id: 'f4-h-gs',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Gram\u2013Schmidt onto an eigenvector',
          prompt: 'Gram\u2013Schmidt applied to a vector not along an $S_x$ eigenvector lands on which eigenvector? (Give its $\\theta$ in degrees on the equator.)',
          answer: V.f4GsAngleDeg,
          tolerance: 0.01,
          assigned: 'HW1 P5(c)',
          hints: [{ text: 'Which operator\u2019s eigenbasis is the target?' }, { text: 'The $x$ eigenvectors sit on the equator.' }, { text: 'Project and renormalize (Chapter F2).' }],
          walkthrough: [],
        },
      ],
    },
    {
      id: 'f4-spectral',
      story: F4_STORY['f4-spectral'],
      review: F4_REVIEW['f4-spectral'],
      title: 'Building and reading a matrix by its directions',
      question: 'How does a Hermitian table split into its directions, and how do functions act on it?',
      lecture: {
        pages: 'Axler 7B pp. 246\u2013247; N&C §2.2 Box 2.2 p. 72; notes p. 15',
        summary: 'A Hermitian table is a sum of its eigenvalues times their projectors. In its own basis it is diagonal, and a function of the table acts on the eigenvalues alone.',
      },
      books: [
        axler('7B, 7.29, 7.31, pp. 246\u2013247', 'The complex and real spectral theorems.'),
        { source: 'nc', where: '§2.2, Box 2.2, p. 72', adds: 'The spectral decomposition and the functional calculus.' },
      ],
      visual: {
        kind: 'operator-builder',
        props: { mode: 'spectral-build', eigenAngleDeg: 45 },
        tryThis: [
          'Set both eigenvalues to $1$: the grid becomes $I$.',
          'Set them $+1, -1$ at $45^\\circ$: rebuild $\\sigma_n$.',
          'Square the eigenvalues: read off $f(A)$ for $f = (\\cdot)^2$.',
        ],
      },
      clues: [],
      insight: 'A Hermitian table is $\\sum_i \\lambda_i|a_i\\rangle\\langle a_i|$, diagonal in its own basis, and a function of it acts on the eigenvalues alone.',
      insightFormal: 'The spectral theorem $A = \\sum_i \\lambda_i|a_i\\rangle\\langle a_i|$ (Axler 7.29) gives $B^\\dagger A B = \\operatorname{diag}(\\lambda_i)$ and the functional calculus $f(A) = \\sum_i f(\\lambda_i)|a_i\\rangle\\langle a_i|$ (N&C Box 2.2).',
      play: [
        {
          id: 'f4-s-square',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Squaring the eigenvalues',
          prompt: '$\\sigma_x$ has eigenvalues $\\pm1$. What is the (repeated) eigenvalue of $\\sigma_x^2$?',
          answer: V.f4XsqEigVal,
          tolerance: 0,
          hints: [{ text: 'A function acts on the eigenvalues.' }, { text: 'Square each of $\\pm1$.' }, { text: '$(\\pm1)^2 = 1$.' }],
          walkthrough: [{ text: '$\\sigma_x^2 = I$, eigenvalues $1$ and $1$.' }],
        },
        {
          id: 'f4-s-rebuild',
          kind: 'numeric',
          tier: 'core',
          title: 'Rebuilding a table from its spectrum',
          prompt: 'Add the projectors with weights $+1$ and $-1$: $(+1)|{+}x\\rangle\\langle{+}x| + (-1)|{-}x\\rangle\\langle{-}x|$. What is the top-right entry?',
          answer: V.f4SpectralRebuildTR,
          tolerance: 0,
          hints: [{ text: 'This is a spectral decomposition.' }, { text: 'It rebuilds a Pauli matrix.' }, { text: 'Which one has eigenvectors $|{\\pm}x\\rangle$?' }],
          walkthrough: [{ text: 'The sum is $\\sigma_x = \\begin{pmatrix}0 & 1\\\\ 1 & 0\\end{pmatrix}$; the top-right is $1$.' }],
        },
        {
          id: 'f4-s-diagonal',
          kind: 'numeric',
          tier: 'core',
          title: 'Diagonalizing in its own basis',
          prompt: 'Diagonalize $\\tfrac12(X + Z)$ in its own basis. What is its top-left diagonal entry?',
          answer: V.f4XZvalHigh,
          tolerance: 0.005,
          hints: [{ text: 'In its own basis a Hermitian table is diagonal.' }, { text: 'The diagonal holds the eigenvalues.' }, { text: 'The larger is $+1/\\sqrt2$.' }],
          walkthrough: [{ text: `$B^\\dagger A B = \\operatorname{diag}(${d(V.f4XZvalHigh, 4)}, -${d(V.f4XZvalHigh, 4)})$.` }],
        },
        {
          id: 'f4-s-exp',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A function of a Hermitian table',
          prompt: 'For $H = \\tfrac12\\sigma_z$, the unitary $e^{-iH\\cdot\\pi}$ has which diagonal entries? Give the real part of the top-left one.',
          answer: V.f4ExpHalfZPiRe,
          tolerance: 0.005,
          hints: [{ text: '$f(A)$ acts on the eigenvalues $\\pm\\tfrac12$.' }, { text: '$e^{-i(\\pm1/2)\\pi} = e^{\\mp i\\pi/2}$.' }, { text: '$e^{-i\\pi/2} = -i$.' }],
          walkthrough: [{ text: 'Diagonal $e^{-i\\pi/2} = -i$ and $e^{i\\pi/2} = i$; the real part of each is $0$.' }],
        },
      ],
    },
    {
      id: 'f4-unitary',
      story: F4_STORY['f4-unitary'],
      review: F4_REVIEW['f4-unitary'],
      title: 'Machines that keep every length',
      question: 'What does a table that keeps all lengths look like, and why are its eigenvalues on the unit circle?',
      lecture: {
        pages: 'Axler 7E p. 270; notes p. 16',
        summary: 'A unitary table keeps every length, $U^\\dagger U = I$. Its eigenvalues have size 1, on the unit circle, and $e^{-iHt}$ turns the [[qc-bloch-sphere|Bloch sphere]] about a Hermitian $H$\u2019s own axis.',
      },
      books: [axler('7E, 7.51, p. 270', 'Isometries and unitary operators.')],
      visual: {
        kind: 'bloch',
        props: { mode: 'rotate', axis: 'z', angleDeg: 0 },
        tryThis: [
          'Rotate by $180^\\circ$ about $z$: where does $|{+}x\\rangle$ go?',
          'Watch the eigenvalues meet at $-1$.',
          'Rotate about $x$ instead: which axis fixes $|0\\rangle$?',
        ],
      },
      clues: [],
      insight: 'A unitary keeps every length, $U^\\dagger U = I$; its eigenvalues have size 1, on the unit circle.',
      insightFormal: '$U^\\dagger U = UU^\\dagger = I \\Leftrightarrow \\|Uv\\| = \\|v\\|$ for all $v$; every eigenvalue is $e^{i\\theta}$, and $e^{-iHt}$ is a unitary sharing $H$\u2019s eigenvectors.',
      play: [
        {
          id: 'f4-u-isunitary',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which table keeps every length?',
          prompt: 'Which table keeps every length?',
          options: [
            { text: '$\\tfrac12(X + Z)$', correct: false, why: 'A projector-like Hermitian table that stretches by $\\pm1/\\sqrt2$, not length-preserving on every arrow.' },
            { text: 'the Hadamard $\\tfrac1{\\sqrt2}\\begin{pmatrix}1 & 1\\\\ 1 & -1\\end{pmatrix}$', correct: true, why: '$H^\\dagger H = I$.' },
            { text: '$\\begin{pmatrix}2 & 0\\\\ 0 & 1\\end{pmatrix}$', correct: false, why: 'A stretch by $2$ changes a length.' },
            { text: '$|{+}x\\rangle\\langle{+}x|$', correct: false, why: 'A projector shortens arrows outside its own direction.' },
          ],
          hints: [{ text: 'Columns must be perpendicular unit arrows.' }, { text: 'A projector shortens arrows.' }, { text: 'A stretch by $2$ changes a length.' }],
          walkthrough: [{ text: '$H^\\dagger H = I$; the others stretch or shorten some arrow.' }],
        },
        {
          id: 'f4-u-unitcircle',
          kind: 'numeric',
          tier: 'core',
          title: 'Size of a unitary\u2019s eigenvalue',
          prompt: 'The phase gate $S = \\operatorname{diag}(1, i)$ is unitary. What is the size of each eigenvalue?',
          answer: V.f4SAbsEig,
          tolerance: 0.005,
          hints: [{ text: 'A unitary keeps lengths.' }, { text: 'So $|\\lambda| = 1$.' }, { text: '$|1| = |i| = 1$.' }],
          walkthrough: [{ text: 'Eigenvalues $1$ and $i$, both on the unit circle.' }],
        },
        {
          id: 'f4-u-rotation',
          kind: 'numeric',
          tier: 'core',
          title: 'A unitary as a turn',
          prompt: '$e^{-i\\sigma_z t}$ turns the Bloch sphere about $z$. By what angle, in degrees, at $t = \\pi/2$?',
          answer: V.f4RzHalfPiAngleDeg,
          tolerance: 0.5,
          hints: [{ text: '$e^{-i\\theta\\,\\mathbf n\\cdot\\boldsymbol\\sigma/2}$ turns by $\\theta$.' }, { text: 'Here $H = \\sigma_z = 2\\cdot\\tfrac12\\sigma_z$.' }, { text: '$\\theta = 2t = \\pi$.' }],
          walkthrough: [{ text: '$\\sigma_z = \\mathbf n\\cdot\\boldsymbol\\sigma$ with $|\\mathbf n| = 1$, so the turn is $2t = \\pi = 180^\\circ$.' }],
        },
        {
          id: 'f4-u-hermunit',
          kind: 'choice',
          tier: 'stretch',
          title: 'Hermitian and unitary together',
          prompt: 'A table is both Hermitian and unitary. Its eigenvalues are:',
          options: [
            { text: 'any real numbers', correct: false, why: 'Unitary also forces size 1.' },
            { text: 'any numbers of size 1', correct: false, why: 'Hermitian also forces them real.' },
            { text: 'only $+1$ and $-1$', correct: true, why: 'Real (Hermitian) $\\cap$ size-1 (unitary) $= \\{+1, -1\\}$.' },
            { text: 'only $+1$', correct: false, why: '$-1$ is also real and of size 1.' },
          ],
          hints: [{ text: 'Hermitian makes them real.' }, { text: 'Unitary makes them size 1.' }, { text: 'Which reals have size 1?' }],
          walkthrough: [{ text: '$\\lambda$ real and $|\\lambda| = 1$ gives $\\lambda = \\pm1$, so $A^2 = I$.' }],
        },
      ],
    },
    {
      id: 'f4-commuting',
      story: F4_STORY['f4-commuting'],
      review: F4_REVIEW['f4-commuting'],
      title: 'When two machines share directions',
      question: 'When can two tables be diagonalized at once, and what does that mean?',
      lecture: {
        pages: 'Axler 5E p. 175; notes p. 16',
        summary: 'Two Hermitian tables share a full eigenbasis exactly when they commute, $[A, B] = 0$. Otherwise, as with $\\sigma_x$ and $\\sigma_z$, no shared basis exists.',
      },
      books: [axler('5E, p. 175', 'Simultaneous diagonalizability.')],
      visual: {
        kind: 'operator-action',
        props: { mode: 'commutator', a: 'Z', b: 'X' },
        tryThis: [
          'Pick $Z$ and $Z$: do they share a basis?',
          'Pick $X$ and $Z$: read $[X, Z] \\ne 0$.',
          'Pick $Z$ and $I$: why does $I$ always commute?',
        ],
      },
      clues: [],
      insight: 'Two Hermitian tables share a full eigenbasis exactly when they commute, $[A, B] = 0$.',
      insightFormal: '$[A, B] = 0 \\Leftrightarrow$ a common orthonormal eigenbasis exists (Axler 5E); distinct eigenvalues of $A$ force $B$ diagonal in $A$\u2019s basis.',
      play: [
        {
          id: 'f4-c-commute',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which pair commutes?',
          prompt: 'Which pair commutes?',
          options: [
            { text: '$\\sigma_x, \\sigma_z$', correct: false, why: '$[\\sigma_x, \\sigma_z] = -2i\\sigma_y \\ne 0$.' },
            { text: '$\\sigma_z, \\operatorname{diag}(1, 0)$', correct: true, why: 'Both diagonal in the same ($z$) basis.' },
            { text: '$\\sigma_x, \\sigma_y$', correct: false, why: 'The Paulis $x, y, z$ do not commute.' },
            { text: '$\\sigma_y, \\sigma_z$', correct: false, why: 'The Paulis $x, y, z$ do not commute.' },
          ],
          hints: [{ text: 'Diagonal tables commute.' }, { text: 'Which pair is diagonal in the same basis?' }, { text: 'The Paulis $x, y, z$ do not commute.' }],
          walkthrough: [{ text: '$\\sigma_z$ and $\\operatorname{diag}(1, 0)$ are both $z$-diagonal, so $[A, B] = 0$.' }],
        },
        {
          id: 'f4-c-commutator',
          kind: 'numeric',
          tier: 'core',
          title: 'The size of a commutator',
          prompt: 'What is the largest entry size of $[\\sigma_x, \\sigma_z] = \\sigma_x\\sigma_z - \\sigma_z\\sigma_x$?',
          answer: V.f4XZcomm,
          tolerance: 0,
          hints: [{ text: '$[\\sigma_x, \\sigma_z] = -2i\\sigma_y$.' }, { text: '$\\sigma_y$ has entries of size 1.' }, { text: '$|{-2i}| = 2$.' }],
          walkthrough: [{ text: '$[\\sigma_x, \\sigma_z] = \\begin{pmatrix}0 & -2\\\\ 2 & 0\\end{pmatrix}$ (that is $-2i\\sigma_y$); the largest entry is $2$.' }],
        },
        {
          id: 'f4-c-simul',
          kind: 'choice',
          tier: 'stretch',
          title: 'When a shared eigenbasis exists',
          prompt: 'Two Hermitian tables share a full eigenbasis exactly when:',
          options: [
            { text: 'they have the same trace', correct: false, why: 'Equal traces say nothing about shared directions.' },
            { text: 'they commute', correct: true, why: '$[A, B] = 0 \\Leftrightarrow$ a shared eigenbasis.' },
            { text: 'one is a multiple of the other', correct: false, why: 'Too strong a condition — commuting is enough.' },
            { text: 'both are unitary', correct: false, why: 'Unitarity says nothing about sharing a basis with another table.' },
          ],
          hints: [{ text: 'Think about diagonal tables.' }, { text: 'Diagonal tables commute, and conversely.' }, { text: 'The test is $AB = BA$.' }],
          walkthrough: [{ text: 'A shared eigenbasis $\\Leftrightarrow [A, B] = 0$ (both diagonal there).' }],
        },
      ],
    },
    {
      id: 'f4-positive',
      story: F4_STORY['f4-positive'],
      review: F4_REVIEW['f4-positive'],
      title: 'Tables with no negative stretch; square roots',
      question: 'Which tables never flip an arrow backwards, and how do we take a square root of a matrix?',
      lecture: {
        pages: 'Axler 7C p. 251, 7D pp. 258\u2013260, 7F p. 285',
        summary: 'A positive table never stretches an arrow backwards: no negative eigenvalue. It has a unique positive square root, and any table at all splits into a turn times a positive stretch (the polar form).',
      },
      books: [
        axler('7C, 7.43, p. 251', 'Positive operators.'),
        axler('7D, 7.44\u20137.52, pp. 258\u2013260', 'The positive square root.'),
        axler('7F, 7.58, p. 285', 'The polar decomposition and the singular-value decomposition.'),
      ],
      visual: {
        kind: 'operator-builder',
        props: { mode: 'sqrt', spectrum: 'bars' },
        tryThis: [
          'Edit $\\tfrac12(I + X)$: both bars $\\ge 0$.',
          'Add $-Z$ until a bar dips below zero.',
          'Take the square root of $I$: how many square roots does $I$ have?',
        ],
      },
      clues: [],
      insight: 'A positive table never stretches an arrow backwards. It has a unique positive square root, and any table splits into a turn times a positive stretch.',
      insightFormal: '$A \\ge 0 \\Leftrightarrow A = A^\\dagger$ and spectrum $\\ge 0$ (Axler 7.43); $\\sqrt A$ is the unique positive operator with $(\\sqrt A)^2 = A$; every $A = U|A|$ (Axler 7.58).',
      play: [
        {
          id: 'f4-p-positive',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which table is positive?',
          prompt: 'Which table is positive ($A \\ge 0$)?',
          options: [
            { text: '$\\sigma_z$', correct: false, why: 'Has eigenvalue $-1$.' },
            { text: '$|{+}x\\rangle\\langle{+}x|$', correct: true, why: 'Eigenvalues $1, 0$: none negative.' },
            { text: '$\\sigma_y$', correct: false, why: 'Has eigenvalue $-1$.' },
            { text: '$\\begin{pmatrix}1 & 0\\\\ 0 & -1\\end{pmatrix}$', correct: false, why: 'Has eigenvalue $-1$.' },
          ],
          hints: [{ text: 'Positive means no negative eigenvalue.' }, { text: 'A projector\u2019s eigenvalues are $0$ and $1$.' }, { text: '$\\sigma_z$ has a $-1$.' }],
          walkthrough: [{ text: 'The projector is $\\ge 0$; the others have a negative eigenvalue.' }],
        },
        {
          id: 'f4-p-sqrt',
          kind: 'numeric',
          tier: 'core',
          title: 'Square root of a diagonal table',
          prompt: 'The positive table $\\operatorname{diag}(4, 9)$ has a positive square root. What is its larger diagonal entry?',
          answer: V.f4SqrtDiag49Val,
          tolerance: 0,
          hints: [{ text: 'The square root acts on the eigenvalues.' }, { text: '$\\sqrt4 = 2$, $\\sqrt9 = 3$.' }, { text: 'Same directions, rooted stretches.' }],
          walkthrough: [{ text: '$\\sqrt{\\operatorname{diag}(4, 9)} = \\operatorname{diag}(2, 3)$.' }],
        },
        {
          id: 'f4-p-svd',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Singular values of a non-Hermitian table',
          prompt: 'The shear $\\begin{pmatrix}2 & 1\\\\ 0 & 2\\end{pmatrix}$ is not Hermitian. What is its largest singular value?',
          answer: V.f4ShearSV0,
          tolerance: 0.005,
          hints: [{ text: 'Singular values are $\\sqrt{\\text{eigenvalues of } A^\\dagger A}$.' }, { text: '$A^\\dagger A = \\begin{pmatrix}4 & 2\\\\ 2 & 5\\end{pmatrix}$.' }, { text: 'Its larger eigenvalue is $6.56$.' }],
          walkthrough: [{ text: `Singular values $${d(V.f4ShearSV0, 4)}, ${d(V.f4ShearSV1, 4)}$ — the true stretch factors, unlike the repeated eigenvalue $2$.` }],
        },
      ],
    },
  ],
}
