/**
 * Physics 709 chapter F5 "Chance with numbers": probability, expectation and variance — the trimmed probability
 * chapter that grounds the Born rule, $\langle M\rangle$ and $\Delta M$ for the Q chapters. The fifth Foundations
 * chapter (no lecture notes of its own beyond the brief usage it grounds: its own line is phase 'core'); it bridges
 * to F2 (the inner product, for the Born-rule link) and to Spin Lab's L1/L4/L3/L7 rather than re-teaching them.
 *
 * Plan: docs/roles/proposals/P-F5-story.md; rulings docs/roles/decisions/qc709-foundations.md,
 * qc709-foundations-rulings.md. The map's full F5 (five units, ending in joint distributions) is TRIMMED here to
 * four units (probability, expectation, spread, surprise); the joint/correlator unit is deferred (plan §12 Q1) —
 * `info.marginals`/`info.correlatorC` exist unused; Q10 teaches CHSH inline. Every number is computed in
 * F5.values.ts and asserted in keyed claims (content.test.tsx runs `holds`; claims.test.ts compares each key with
 * its numpy twin in physics/__fixtures__/claims-qc709/f5.json, pipeline/claims_qc709/f5.py).
 */
import type { Lecture } from '../schema'
import { F5_REVIEW } from './F5.review'
import { bergou, F5_STORY } from './F5.story'
import { V } from './F5.values'

export const F5: Lecture = {
  id: 'F5',
  number: 5,
  title: 'Chance with numbers',
  outcomes: [
    'Say what a probability is, check that a list of chances adds to 1, and multiply chances for independent events.',
    'Compute the expectation $\\langle X\\rangle$ of a random reading, and read it as a long-run average.',
    'Measure scatter with the variance and standard deviation, and explain why the average of $N$ readings sharpens by $\\sqrt N$.',
    'Count the information in a reading in bits, with the Shannon entropy.',
  ],
  // F2 (the inner product, for the Born-rule link P = |⟨a|ψ⟩|²) is the one Foundations prerequisite; the Ground
  // ramp otherwise assumes only percentages, fractions, coin flips and a class average (plan §0 "Prerequisites").
  prerequisites: ['qc-inner-product-station'],
  symbols: {
    // every symbol here is "defined" at one of the chapter's own outcome sentences, which read first in the
    // chapter (readingOrder: outcomes → watch → corrections → units) — the same blanket-definition convention F6
    // used (F6.story.ts / F6.ts), since F5 is a math-foundations chapter introducing many symbols at once.
    '\\Omega': 'F5.outcomes[0]',
    P: 'f5-probability:b1',
    A: 'F5.outcomes[0]',
    B: 'F5.outcomes[0]',
    N: 'F5.outcomes[2]',
    n: 'F5.outcomes[0]',
    X: 'F5.outcomes[1]',
    Y: 'F5.outcomes[1]',
    a: 'F5.outcomes[1]',
    b: 'F5.outcomes[1]',
    p: 'F5.outcomes[0]',
    'p_+': 'F5.outcomes[0]',
    'p_-': 'F5.outcomes[0]',
    H: 'F5.outcomes[3]',
    h: 'F5.outcomes[3]',
    M: 'F5.outcomes[1]',
    'M_\\alpha': 'F5.outcomes[1]',
    'P_\\alpha': 'F5.outcomes[1]',
    S_z: 'F5.outcomes[1]',
    T: 'F5.outcomes[0]',
    E: 'F5.outcomes[1]',
    I: 'F5.outcomes[2]',
    f_n: 'F5.outcomes[0]',
    x_k: 'F5.outcomes[1]',
    X_k: 'F5.outcomes[2]',
    '\\mu': 'F5.outcomes[1]',
    '\\sigma': 'f5-spread:b2',
    '\\theta': 'f5-probability:b4',
    '\\hbar': 'F5.outcomes[1]',
    '\\Delta': 'F5.outcomes[2]',
    '\\bar X': 'F5.outcomes[2]',
    '\\bar X_n': 'F5.outcomes[1]',
    '\\langle\\cdot\\rangle': 'F5.outcomes[1]',
    '\\langle\\cdot|\\cdot\\rangle': 'F5.outcomes[0]',
    '|\\cdot\\rangle': 'F5.outcomes[0]',
    '|a\\rangle': 'F5.outcomes[0]',
    '|\\psi\\rangle': 'F5.outcomes[0]',
    '|+n\\rangle': 'F5.outcomes[0]',
    // the stand-in labels of the classical pictures (a ket label names a heads/tails outcome), defined where first drawn
    '|0\\rangle': 'f5-probability:b3',
    '|00\\rangle': 'f5-probability:b3',
    '|11\\rangle': 'f5-spread:b4',
  },
  // the density matrix $\rho$ appears only in the Formal track's links of $\langle M\rangle$ to $\mathrm{Tr}(\rho M)$
  symbolsFormal: { '\\rho': 'f5-average:b3', '\\langle\\cdot|': 'f5-average:b3' },
  units: [
    {
      id: 'f5-probability',
      story: F5_STORY['f5-probability'],
      review: F5_REVIEW['f5-probability'],
      title: 'Chances over a list of outcomes',
      question: 'What is a probability, why do a list’s chances add to 1, and when do chances multiply?',
      lecture: {
        pages: 'notes p. 15',
        summary: 'A probability assigns each outcome a chance from 0 to 1; a sample space’s chances add to 1, and independent events multiply.',
      },
      // no course source states the probability axioms or independence (no Bergou/Reif cite, per the judge's ruling): only
      // the notes' use of a chance as an overlap, which this chapter grounds
      books: [
        { source: 'lecture', where: 'notes p. 15', adds: 'The chance of a reading as an overlap, $P(a) = |\\langle a|\\psi\\rangle|^2$, and the average $\\langle M\\rangle = \\sum_\\alpha M_\\alpha P_\\alpha$, the usage this chapter grounds.' },
      ],
      visual: {
        kind: 'deposit-stats',
        props: { state: '+x', axis: 'z', seed: 709 },
        tryThis: [
          'Read the chance above the buttons: $P(+z) = 0.5000$, so $P(-z) = 0.5$ too, and the two chances add to 1.',
          'Fire $+1000$ atoms: every atom lands in one of the two piles, so the two counts add to 1000, and the up share settles near $50\\%$.',
          'Press Clear and fire $+10$: with so few atoms the share can sit far from $50\\%$. Fire $+10$ again and watch it move.',
        ],
      },
      clues: [],
      insight: 'A probability is a chance from 0 to 1; a sample space’s chances add to 1, and independent events multiply.',
      insightFormal: '$P: \\Omega \\to [0,1]$ with $\\sum_x P(x) = 1$; independence means $P(A\\cap B) = P(A)P(B)$.',
      play: [
        {
          id: 'f5-p-die',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'An even face',
          prompt: 'A fair die. What is the probability of rolling an even number?',
          answer: V.f5DieEven,
          tolerance: 0.005,
          hints: [{ text: 'Add the chances of the outcomes in the event.' }, { text: 'Three of the six faces are even.' }, { text: '$3 \\times \\tfrac16$.' }],
          walkthrough: [{ text: '$P(\\text{even}) = \\tfrac16 + \\tfrac16 + \\tfrac16 = 0.5$.' }],
        },
        {
          id: 'f5-p-two-heads',
          kind: 'numeric',
          tier: 'core',
          title: 'Two heads',
          prompt: 'Two fair coins. What is the chance of two heads?',
          answer: V.f5TwoCoin,
          tolerance: 0.005,
          hints: [{ text: 'The two flips are independent.' }, { text: 'Independent chances multiply.' }, { text: '$\\tfrac12 \\times \\tfrac12$.' }],
          walkthrough: [{ text: '$P(\\text{HH}) = 0.25$; the four outcomes each have $0.25$.' }],
        },
        {
          id: 'f5-p-born',
          kind: 'numeric',
          tier: 'core',
          title: 'A Born chance',
          prompt: 'A spin at $\\theta = 60°$ is read along $z$. What is $P(+)$?',
          answer: V.f5BornP,
          tolerance: 0.005,
          hints: [{ text: '$P(+) = \\cos^2(\\theta/2)$.' }, { text: '$\\theta/2 = 30°$.' }, { text: '$\\cos 30° = 0.866$, squared.' }],
          walkthrough: [{ text: '$\\cos^2 30° = 0.75$, so $P(-) = 0.25$.' }],
        },
        {
          id: 'f5-p-at-least-one',
          kind: 'numeric',
          tier: 'stretch',
          title: 'At least one head',
          prompt: 'Three fair coins. What is the chance of at least one head?',
          answer: V.f5AtLeastOne,
          tolerance: 0.005,
          hints: [{ text: 'Use the complement.' }, { text: '"At least one head" is the opposite of "all tails".' }, { text: '$P(\\text{all tails}) = (1/2)^3$.' }],
          walkthrough: [{ text: '$1 - \\tfrac18 = 0.875$.' }],
        },
      ],
    },
    {
      id: 'f5-average',
      story: F5_STORY['f5-average'],
      review: F5_REVIEW['f5-average'],
      title: 'The number you expect on average',
      question: 'What single number summarises a random reading, and how do we compute it?',
      lecture: {
        pages: 'notes p. 15; Bergou §5.2, p. 81, Eq. 5.9',
        summary: 'The expectation $\\langle X\\rangle = \\sum_x x\\,P(x)$ is the chance-weighted average, the long-run mean of many readings.',
      },
      books: [
        bergou('§5.2, p. 81, Eq. 5.9', 'The expectation of a reading as a chance-weighted sum of its values; it also equals a trace with the density matrix.'),
        { source: 'lecture', where: 'notes p. 15', adds: 'The average $\\langle M\\rangle = \\sum_\\alpha M_\\alpha P_\\alpha$.' },
      ],
      visual: {
        kind: 'amplitude-bars',
        props: { state: [60, 0], basis: 'z' },
        tryThis: [
          'At $\\theta = 60°$ the bars read $75.0\\%$ for $+z$ and $25.0\\%$ for $-z$. Weight the readings $\\pm\\tfrac12$ by those chances: $\\langle S_z\\rangle = \\tfrac12(0.75 - 0.25) = 0.25\\hbar$.',
          'Slide $\\theta$ to $90°$: the chances are $50\\%$ each, so $\\langle S_z\\rangle = 0$, an average that neither reading ($\\pm\\tfrac12$) takes.',
          'Slide $\\theta$ to $0°$: $+z$ has $100\\%$, so the average is that one value, $+\\tfrac12\\hbar$.',
        ],
      },
      clues: [],
      insight: 'The expectation weighs each value by its chance and adds; it is the long-run average, not a promised outcome.',
      insightFormal: '$\\langle X\\rangle = \\sum_x x\\,P(x)$, linear: $\\langle aX+b\\rangle = a\\langle X\\rangle + b$ (Bergou §5.2, Eq. 5.9).',
      play: [
        {
          id: 'f5-a-die',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A fair die’s expectation',
          prompt: 'What is the expectation of a fair die?',
          answer: V.f5DieMean,
          tolerance: 0.005,
          hints: [{ text: 'Weight each face by $1/6$.' }, { text: 'Add $1 + 2 + \\cdots + 6 = 21$.' }, { text: 'Divide by 6.' }],
          walkthrough: [{ text: '$21/6 = 3.5$.' }],
        },
        {
          id: 'f5-a-biased',
          kind: 'numeric',
          tier: 'core',
          title: 'A biased payoff',
          prompt: 'A coin pays one dollar for heads ($p = 0.6$), nothing for tails. What is the expected pay, in dollars?',
          answer: V.f5BiasedMean,
          tolerance: 0.005,
          hints: [{ text: '$\\langle X\\rangle = \\sum x\\,P(x)$.' }, { text: '$1\\cdot0.6 + 0\\cdot0.4$.' }, { text: 'Only heads pays.' }],
          walkthrough: [{ text: '$\\langle X\\rangle = 0.6$.' }],
        },
        {
          id: 'f5-a-linear',
          kind: 'numeric',
          tier: 'core',
          title: 'A linear rescaling',
          prompt: 'A fair die’s face is doubled and 1 added. What is the new expectation?',
          answer: V.f5LinMean,
          tolerance: 0,
          hints: [{ text: 'Expectation is linear.' }, { text: '$\\langle 2X + 1\\rangle = 2\\langle X\\rangle + 1$.' }, { text: '$\\langle X\\rangle = 3.5$.' }],
          walkthrough: [{ text: '$2\\cdot3.5 + 1 = 8$.' }],
        },
        {
          id: 'f5-a-spin',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A spin average',
          prompt: 'A spin with $P(+) = 0.75$. What is $\\langle S_z\\rangle$, in units of $\\hbar$?',
          answer: V.f5SpinAvg,
          tolerance: 0.005,
          hints: [{ text: 'Values $\\pm\\tfrac12$ (in $\\hbar$).' }, { text: '$\\langle S_z\\rangle = \\tfrac12(2p - 1)$.' }, { text: '$2\\cdot0.75 - 1 = 0.5$.' }],
          walkthrough: [{ text: '$\\tfrac12\\cdot0.5 = 0.25\\hbar$; the same as Chapter Q3’s operator average.' }],
        },
      ],
    },
    {
      id: 'f5-spread',
      story: F5_STORY['f5-spread'],
      review: F5_REVIEW['f5-spread'],
      title: 'How widely the readings scatter',
      question: 'How do we measure scatter, and why does the average of many readings sharpen?',
      // Film opener (plan §10.2, "qc-f5-galton") deferred: media generation is out of scope for this build.
      lecture: {
        pages: 'notes pp. 18–19; Bergou §5.2, p. 81, Eq. 5.10',
        summary: 'The variance $(\\Delta X)^2 = \\langle X^2\\rangle - \\langle X\\rangle^2$ measures scatter; the average of $N$ readings has spread $\\sigma/\\sqrt N$.',
      },
      // no course source states the binomial moments or the $\\sigma/\\sqrt N$ law (no Bergou/Reif cite, per the judge's ruling)
      books: [
        bergou('§5.2, p. 81, Eq. 5.10', 'The variance $\\sigma^2 = \\langle X^2\\rangle - \\langle X\\rangle^2$ of a reading.'),
        { source: 'lecture', where: 'notes pp. 18–19', adds: 'The dispersion $\\langle A^2\\rangle - \\langle A\\rangle^2$.' },
      ],
      visual: {
        kind: 'deposit-stats',
        props: { state: '+x', axis: 'z', seed: 709 },
        tryThis: [
          'Press Clear, then $+10$ twice ($N = 20$): the readout says expected $10.0 \\pm 2.2$, which is $\\sqrt{20\\cdot0.5\\cdot0.5}$.',
          'Press Clear, then $+100$ ($N = 100$): expected $50.0 \\pm 5.0$, and the 95% band is $40$ to $60$, a smaller share of $N$.',
          'Press Clear, then $+10000$: expected $5000.0 \\pm 50.0$, so the fraction’s spread is $0.5\\%$, against $5\\%$ at $N = 100$. Ten times tighter for $100$ times the atoms.',
        ],
      },
      clues: [],
      insight: 'The variance measures scatter about the mean; averaging $N$ readings shrinks the spread of the mean by $\\sqrt N$.',
      insightFormal: '$(\\Delta X)^2 = \\langle X^2\\rangle - \\langle X\\rangle^2 \\ge 0$ (Bergou §5.2, Eq. 5.10); $\\Delta\\bar X = \\sigma/\\sqrt N$ for $N$ independent readings.',
      play: [
        {
          id: 'f5-s-coin-var',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A coin’s variance',
          prompt: 'A fair coin ($0/1$). What is its variance?',
          answer: V.f5VarHalf,
          tolerance: 0.005,
          hints: [{ text: '$\\mu = 0.5$.' }, { text: 'Variance is $p(1-p)$.' }, { text: '$0.5 \\times 0.5$.' }],
          walkthrough: [{ text: '$\\mathrm{Var} = 0.25$, $\\sigma = 0.5$.' }],
        },
        {
          id: 'f5-s-die-sd',
          kind: 'numeric',
          tier: 'core',
          title: 'A die’s standard deviation',
          prompt: 'What is the standard deviation of a fair die (to 3 d.p.)?',
          answer: V.f5DieSD,
          tolerance: 0.0005,
          hints: [{ text: 'Variance first.' }, { text: '$\\langle X^2\\rangle - \\langle X\\rangle^2 = 15.167 - 12.25$.' }, { text: '$\\sqrt{2.917}$.' }],
          walkthrough: [{ text: '$\\sqrt{2.917} = 1.708$.' }],
        },
        {
          id: 'f5-s-binomial',
          kind: 'numeric',
          tier: 'core',
          title: '100 coin flips',
          prompt: '100 fair coin flips. What is the standard deviation of the head count?',
          answer: V.f5BinSD,
          tolerance: 0,
          hints: [{ text: 'Variance is $Np(1-p)$.' }, { text: '$100 \\times 0.5 \\times 0.5 = 25$.' }, { text: '$\\sqrt{25}$.' }],
          walkthrough: [{ text: '$\\sigma = 5$; counts fall within about 5 of $50$, roughly two times in three.' }],
        },
        {
          id: 'f5-s-sqrtN',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Averaging readings',
          prompt: 'A reading has $\\sigma = 2$. Average 64 independent readings. What is the spread of the average?',
          answer: V.f5SqrtN64,
          tolerance: 0.005,
          hints: [{ text: 'The sample mean’s spread is $\\sigma/\\sqrt N$.' }, { text: '$\\sqrt{64} = 8$.' }, { text: '$2/8$.' }],
          walkthrough: [{ text: '$\\sigma/\\sqrt N = 0.25$: averaging sharpens the estimate.' }],
        },
      ],
    },
    {
      id: 'f5-surprise',
      story: F5_STORY['f5-surprise'],
      review: F5_REVIEW['f5-surprise'],
      title: 'Counting information in bits',
      question: 'How much does one reading tell us, measured in yes/no questions?',
      lecture: {
        pages: 'Bergou §11.1, pp. 190–191; §3.8, p. 55, Eq. 3.71',
        summary: 'The Shannon entropy $H = -\\sum_x P(x)\\log_2 P(x)$ counts a reading’s information in bits; the binary entropy $h(p)$ is its two-outcome case.',
      },
      books: [bergou('§11.1, pp. 190–191', 'The Shannon entropy.'), bergou('§3.8, p. 55, Eq. 3.71', 'The binary entropy function $h(p)$.')],
      visual: {
        kind: 'amplitude-bars',
        props: { state: [90, 0], basis: 'z' },
        tryThis: [
          'At $\\theta = 90°$ the bars read $50.0\\%$ each: a fair coin, $H = 1$ bit.',
          'Slide $\\theta$ to $60°$: the bars read $75.0\\%$ and $25.0\\%$, so $h(0.75) = 0.811$ bits, less than a full bit.',
          'Slide $\\theta$ to $0°$: the bars read $100.0\\%$ and $0.0\\%$, a sure reading, so $H = 0$.',
        ],
      },
      clues: [],
      insight: 'Information is counted in bits; a sure outcome carries none, and the uniform distribution carries the most.',
      insightFormal: '$H = -\\sum_x P(x)\\log_2 P(x)$ bits; $h(p)$ peaks at 1 bit at $p=\\tfrac12$ (Bergou §11.1, pp. 190–191; §3.8, Eq. 3.71).',
      play: [
        {
          id: 'f5-u-coin',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'One coin flip',
          prompt: 'How many bits does one fair coin flip carry?',
          answer: V.f5HCoin,
          tolerance: 0,
          hints: [{ text: 'One yes/no question.' }, { text: '$H = \\log_2 2$.' }, { text: '$\\log_2 2 = 1$.' }],
          walkthrough: [{ text: '$H = 1$ bit.' }],
        },
        {
          id: 'f5-u-die',
          kind: 'numeric',
          tier: 'core',
          title: 'One die roll',
          prompt: 'How many bits does a fair die roll carry (to 3 d.p.)?',
          answer: V.f5HDie,
          tolerance: 0.0005,
          hints: [{ text: 'Six equally likely outcomes.' }, { text: '$H = \\log_2 6$.' }, { text: '$\\log_2 6 = 2.585$.' }],
          walkthrough: [{ text: '$H = 2.585$ bits.' }],
        },
        {
          id: 'f5-u-binary',
          kind: 'numeric',
          tier: 'core',
          title: 'A biased coin',
          prompt: 'A $75/25$ coin. How many bits does one flip carry (to 3 d.p.)?',
          answer: V.f5hThreeQuarter,
          tolerance: 0.0005,
          hints: [{ text: 'Use $h(p)$.' }, { text: '$-0.75\\log_2 0.75 - 0.25\\log_2 0.25$.' }, { text: 'Between 0 and 1.' }],
          walkthrough: [{ text: '$h(0.75) = 0.811$ bits, less than a full bit.' }],
        },
        {
          id: 'f5-u-max',
          kind: 'choice',
          tier: 'stretch',
          title: 'The most informative bias',
          prompt: 'For which coin bias is the information per flip largest?',
          options: [
            { text: '$p = 0.1$', correct: false, why: 'A very predictable coin carries little information.' },
            { text: '$p = 0.25$', correct: false, why: 'Still fairly predictable; $h(0.25) < 1$.' },
            { text: '$p = 0.5$', correct: true, why: '$h(p)$ is maximal (1 bit) exactly at $p=0.5$: the symmetric, hardest-to-predict case.' },
            { text: '$p = 0.9$', correct: false, why: 'A heavily biased coin carries little information.' },
          ],
          hints: [{ text: 'Most uncertain means most informative.' }, { text: 'When is the coin hardest to predict?' }, { text: 'The symmetric case.' }],
          walkthrough: [{ text: '$h(p)$ peaks at $p = 0.5$ ($H=1$); the biased coins carry less.' }],
        },
      ],
    },
  ],
}
