/**
 * Physics 709 chapter F6 "Tensor products": the joint space of two systems, ⊗ on vectors and on operators, and the
 * product-versus-entangled test. The sixth and last Foundations chapter (no lecture notes: its own line is phase
 * 'core'); it builds on F2 (vectors, inner products, bases) and F3 (matrices), both merged, and is the bridge target
 * every later chapter reaches for when it joins two systems.
 *
 * Plan: docs/roles/proposals/P-F6-story.md; rulings docs/roles/decisions/qc709-foundations.md,
 * qc709-foundations-rulings.md. F6 does NOT re-teach Q4's gate tensor products or Q6's Bell states and correlation
 * grid — it builds the algebra of ⊗ abstractly and reuses their glossary entries (see F6.story.ts's header comment).
 * Every number a learner sees is computed in F6.values.ts and asserted in keyed claims (content.test.tsx runs
 * `holds`; claims.test.ts compares each key with its numpy twin in physics/__fixtures__/claims-qc709/f6.json).
 */
import type { Lecture } from '../schema'
import { F6_REVIEW } from './F6.review'
import { axler, bergou, F6_STORY, nc } from './F6.story'
import { V, d, pct } from './F6.values'

export const F6: Lecture = {
  id: 'F6',
  number: 6,
  title: 'Many at once',
  outcomes: [
    'Say how big the joint space of two systems is, and name its basis states $|ab\\rangle$.',
    'Combine two state lists with $\\otimes$: every amplitude of the first times every amplitude of the second, in big-endian order.',
    'Build $A \\otimes B$ as a block table, and act with a machine on just one part, like $X \\otimes I$.',
    'Tell a product (independent) state from an entangled one with the factoring test $\\det C = 0$.',
    'Explain why dimensions multiply, and why $n$ qubits need $2^n$ numbers to store.',
  ],
  // F2 (vectors, inner products, orthonormal bases) and F3 (matrices, linear maps) are both merged prerequisites.
  prerequisites: ['qc-ket', 'qc-inner-product-station', 'qc-orthonormal-basis', 'qc-linear-operator', 'qc-matrix-of-map'],
  symbols: {
    A: 'F6.outcomes[0]',
    B: 'F6.outcomes[0]',
    C: 'F6.outcomes[0]',
    I: 'F6.outcomes[0]',
    X: 'F6.outcomes[0]',
    Z: 'F6.outcomes[0]',
    V: 'F6.outcomes[0]',
    W: 'F6.outcomes[0]',
    U: 'F6.outcomes[0]',
    r: 'F6.outcomes[0]',
    m: 'F6.outcomes[0]',
    n: 'F6.outcomes[0]',
    u: 'F6.outcomes[0]',
    v: 'F6.outcomes[0]',
    a: 'F6.outcomes[0]',
    b: 'F6.outcomes[0]',
    c: 'F6.outcomes[0]',
    d: 'F6.outcomes[0]',
    k: 'F6.outcomes[0]',
    '\\theta': 'F6.outcomes[0]',
    '\\Phi': 'F6.outcomes[0]',
    '\\Psi': 'F6.outcomes[0]',
    '\\top': 'F6.outcomes[0]',
    '\\dim': 'F6.outcomes[0]',
    'a_0': 'F6.outcomes[0]',
    'a_1': 'F6.outcomes[0]',
    'a_j': 'F6.outcomes[0]',
    'b_0': 'F6.outcomes[0]',
    'b_1': 'F6.outcomes[0]',
    'b_k': 'F6.outcomes[0]',
    'c_ab': 'F6.outcomes[0]',
    'c_j': 'F6.outcomes[0]',
    'c_00': 'F6.outcomes[0]',
    'c_01': 'F6.outcomes[0]',
    'c_10': 'F6.outcomes[0]',
    'c_11': 'F6.outcomes[0]',
    'd_k': 'F6.outcomes[0]',
    'e_j': 'F6.outcomes[0]',
    'f_k': 'F6.outcomes[0]',
    'A_ab': 'F6.outcomes[0]',
    'A_aa\'': 'F6.outcomes[0]',
    'B_a\'b\'': 'F6.outcomes[0]',
    'X_A': 'F6.outcomes[0]',
    'I_B': 'F6.outcomes[0]',
    'V_1': 'F6.outcomes[0]',
    'V_n': 'F6.outcomes[0]',
    'V_i': 'F6.outcomes[0]',
    'r_A': 'F6.outcomes[0]',
    'r_B': 'F6.outcomes[0]',
    '\\otimes': 'F6.outcomes[1]',
    '\\psi': 'F6.outcomes[1]',
    '\\varphi': 'F6.outcomes[1]',
    '\\psi_a': 'F6.outcomes[1]',
    '\\varphi_b': 'F6.outcomes[1]',
    '\\psi_0': 'F6.outcomes[1]',
    '\\psi_1': 'F6.outcomes[1]',
    '\\varphi_0': 'F6.outcomes[1]',
    '\\varphi_1': 'F6.outcomes[1]',
    '\\delta_bb\'': 'F6.outcomes[2]',
    // generic notations: the ket bracket itself, and the bra-ket / bra forms, each needed once before any named ket
    '|\\cdot\\rangle': 'F6.outcomes[0]',
    '\\langle\\cdot|\\cdot\\rangle': 'F6.outcomes[4]',
    '\\langle\\cdot|': 'F6.outcomes[2]',
    '|0\\rangle': 'F6.outcomes[0]',
    '|1\\rangle': 'F6.outcomes[0]',
    '|00\\rangle': 'F6.outcomes[0]',
    '|01\\rangle': 'F6.outcomes[0]',
    '|10\\rangle': 'F6.outcomes[0]',
    '|11\\rangle': 'F6.outcomes[0]',
    '|000\\rangle': 'F6.outcomes[0]',
    '|111\\rangle': 'F6.outcomes[0]',
    '|110\\rangle': 'F6.outcomes[0]',
    '|a\\rangle': 'F6.outcomes[0]',
    '|b\\rangle': 'F6.outcomes[0]',
    '|ab\\rangle': 'F6.outcomes[0]',
    "|a'b'\\rangle": 'F6.outcomes[0]',
    '|c\\rangle': 'F6.outcomes[4]',
    '|d\\rangle': 'F6.outcomes[4]',
    '|+\\rangle': 'F6.outcomes[1]',
    '|-\\rangle': 'F6.outcomes[1]',
    '|+0\\rangle': 'F6.outcomes[1]',
    '|+-\\rangle': 'F6.outcomes[1]',
    '|++\\rangle': 'F6.outcomes[3]',
    '|\\psi\\rangle': 'F6.outcomes[0]',
    '|\\varphi\\rangle': 'F6.outcomes[0]',
    '|e_k\\otimese_l\\rangle': 'F6.outcomes[2]',
    '|a\\otimesb\\rangle': 'F6.outcomes[4]',
    '|c\\otimesd\\rangle': 'F6.outcomes[4]',
    '|u\\rangle': 'F6.outcomes[2]',
    '|v\\rangle': 'F6.outcomes[2]',
    "|b_0\\ldotsb_n-1\\rangle": 'F6.outcomes[0]',
  },
  units: [
    {
      id: 'f6-pairs',
      story: F6_STORY['f6-pairs'],
      review: F6_REVIEW['f6-pairs'],
      title: 'Two systems, one joint space',
      question: 'How big is the space of two systems together, and what are its basis states?',
      lecture: {
        pages: 'Axler 9.73 p. 374; N&C §2.1.7 p. 71; Bergou §3.1 p. 31',
        summary: 'Two systems combine into one joint space of dimension $mn$, with basis states $|ab\\rangle$ — every first state paired with every second.',
      },
      books: [
        axler('9.73, p. 374', 'The tensor product $V \\otimes W$ of two [[qc-vector-space|vector spaces]], its basis $e_j \\otimes f_k$ and dimension $mn$.'),
        nc('§2.1.7, p. 71', 'The tensor product of state spaces and the big-endian basis order.'),
      ],
      visual: {
        kind: 'amplitude-bars',
        props: { mode: 'register', qubits: 2 },
        tryThis: ['Two qubits: count 4 bars.', 'Add a third qubit: now 8 bars.', 'Label the index-2 bar ($|10\\rangle$, big-endian).'],
      },
      clues: [],
      insight: 'Two systems with $m$ and $n$ states join into $mn$ joint states, living in $\\text{\u2102}^m \\otimes \\text{\u2102}^n$.',
      insightFormal: 'The joint space of systems with spaces $V$ ($\\dim m$) and $W$ ($\\dim n$) is $V \\otimes W$, of dimension $mn$; $n$ qubits give $\\text{\u2102}^{2^n}$.',
      play: [
        {
          id: 'f6-pa-dim',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Three qubits, how many states?',
          prompt: 'How many basis states does a three-qubit register have?',
          answer: V.f6Strings,
          tolerance: 0,
          hints: [{ text: 'Each qubit doubles the count.' }, { text: '$2 \\times 2 \\times 2$.' }, { text: '$2^3$.' }],
          walkthrough: [{ text: '$2^3 = 8$ basis states, $|000\\rangle$ to $|111\\rangle$.' }],
        },
        {
          id: 'f6-pa-index',
          kind: 'numeric',
          tier: 'core',
          title: 'Reading a big-endian index',
          prompt: 'In the big-endian order, what index is $|110\\rangle$?',
          answer: V.f6Idx110,
          tolerance: 0,
          hints: [{ text: 'Read the bits as a binary number, first qubit most significant.' }, { text: '$1 \\cdot 4 + 1 \\cdot 2 + 0 \\cdot 1$.' }, { text: '$4 + 2$.' }],
          walkthrough: [{ text: '$|110\\rangle \\mapsto 6$.' }],
        },
        {
          id: 'f6-pa-ten',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Ten qubits',
          prompt: 'How many amplitudes describe a ten-qubit register?',
          answer: V.f6TenDim,
          tolerance: 0,
          hints: [{ text: 'Dimensions multiply.' }, { text: '$2^{10}$.' }, { text: 'Not $2 \\times 10 = 20$.' }],
          walkthrough: [{ text: `$2^{10} = ${d(V.f6TenDim, 0)}$, far more than the $20$ that adding would give.` }],
        },
      ],
    },
    {
      id: 'f6-kron',
      story: F6_STORY['f6-kron'],
      review: F6_REVIEW['f6-kron'],
      title: 'Every amplitude times every amplitude',
      question: 'How do we combine two state lists into one, and in what order?',
      lecture: {
        pages: 'Axler 9.72 p. 372; N&C §2.1.7 pp. 71–72; Bergou Eq. 1.3 p. 2',
        summary: 'The tensor product $\\otimes$ builds the joint state: multiply every amplitude of the first factor by every amplitude of the second.',
      },
      books: [
        axler('9.72, p. 372', 'The coordinates of a tensor product $\\psi \\otimes \\varphi$ as products of coordinates.'),
        bergou('Eq. 1.3, p. 2', 'A two-qubit state written as the tensor product of two single-qubit states.'),
      ],
      visual: {
        kind: 'amplitude-bars',
        props: { mode: 'kron', a: '+', b: '0' },
        tryThis: ['$|{+}\\rangle \\otimes |0\\rangle$: read $(0.707, 0, 0.707, 0)$.', 'Swap to $|0\\rangle \\otimes |{+}\\rangle$.', '$|{+}\\rangle \\otimes |{-}\\rangle$: find the signs (each $\\pm0.5$).'],
      },
      clues: [],
      insight: 'The tensor product multiplies every amplitude of the first factor by every amplitude of the second.',
      insightFormal: 'The tensor product $|\\psi\\rangle \\otimes |\\varphi\\rangle$ has amplitudes $(\\psi \\otimes \\varphi)_{ab} = \\psi_a \\varphi_b$, extended bilinearly from a basis.',
      play: [
        {
          id: 'f6-k-first',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The first amplitude of a product',
          prompt: 'What is the first amplitude of $|{+}\\rangle \\otimes |0\\rangle$ (to 3 d.p.)?',
          answer: V.f6PlusZeroRe,
          tolerance: 0.0005,
          hints: [{ text: 'Multiply the two first amplitudes.' }, { text: '$0.707 \\times 1$.' }, { text: '$1/\\sqrt2$.' }],
          walkthrough: [{ text: `$c_{00} = 0.707 \\times 1 = ${d(V.f6PlusZeroRe)}$.` }],
        },
        {
          id: 'f6-k-which',
          kind: 'choice',
          tier: 'core',
          title: 'Which state is $|{+}\\rangle \\otimes |{-}\\rangle$?',
          prompt: 'Which state is $|{+}\\rangle \\otimes |{-}\\rangle$?',
          options: [
            { text: '$(0.5, 0.5, 0.5, 0.5)$', correct: false, why: 'This has no negative entries, but $|{-}\\rangle$ carries a minus.' },
            { text: '$(0.5, -0.5, 0.5, -0.5)$', correct: true, why: 'Every amplitude is a product; the $b=1$ slots carry $|{-}\\rangle$’s minus.' },
            { text: '$(0.707, 0, 0, 0.707)$', correct: false, why: 'This is an entangled pattern, not a product of two single-qubit lists.' },
            { text: '$(0.5, 0.5, -0.5, -0.5)$', correct: false, why: 'The sign pattern is on the wrong slots: it is the $a=1$ rows that would flip, not the $b=1$ columns.' },
          ],
          hints: [{ text: 'Every amplitude is a product.' }, { text: '$|{-}\\rangle = (0.707, -0.707)$.' }, { text: 'The minus rides on the second factor.' }],
          walkthrough: [{ text: '$(0.707)(\\pm0.707) = \\pm0.5$; the $b=1$ slots get the minus.' }],
        },
        {
          id: 'f6-k-order',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Which index does the order give?',
          prompt: 'What index does $|0\\rangle \\otimes |1\\rangle$ occupy?',
          answer: V.f6Idx01,
          tolerance: 0,
          hints: [{ text: '$|0\\rangle \\otimes |1\\rangle = |01\\rangle$.' }, { text: 'First qubit 0, second 1.' }, { text: '$0 \\cdot 2 + 1$.' }],
          walkthrough: [{ text: '$|01\\rangle \\mapsto 1$ (not $|10\\rangle \\mapsto 2$: order matters).' }],
        },
      ],
    },
    {
      id: 'f6-operator',
      story: F6_STORY['f6-operator'],
      review: F6_REVIEW['f6-operator'],
      title: 'Machines acting on one part',
      question: 'How does a matrix on one system act on the pair, and what is $A \\otimes B$ as a table?',
      lecture: {
        pages: 'Axler 9D p. 378; N&C §2.1.7 p. 73; Bergou §2.1 p. 16',
        summary: 'The Kronecker product $A \\otimes B$ is the block table of a combined machine, acting factor by factor: $(A \\otimes B)(u \\otimes v) = Au \\otimes Bv$.',
      },
      books: [
        nc('§2.1.7, p. 73', 'The tensor product of operators as a block matrix, $(A \\otimes B)_{(aa\'),(bb\')} = A_{ab}B_{a\'b\'}$.'),
        bergou('§2.1, p. 16', 'A local operator $X_A \\otimes I_B$ acting on one system of a pair.'),
      ],
      visual: {
        kind: 'operator-action',
        props: { opA: 'X', opB: 'I' },
        tryThis: ['$X \\otimes I$ on $|01\\rangle$: lands on $|11\\rangle$.', 'Swap to $I \\otimes X$ instead.', 'Try $Z \\otimes Z$: a diagonal block table.'],
      },
      clues: [],
      insight: 'A combined machine acts factor by factor: $(A \\otimes B)(u \\otimes v) = Au \\otimes Bv$, and its table is the Kronecker product $A \\otimes B$.',
      insightFormal: '$(A \\otimes B)_{(aa\'),(bb\')} = A_{ab}B_{a\'b\'}$ (N&C §2.1.7); $(A \\otimes B)(u \\otimes v) = Au \\otimes Bv$ extended bilinearly (Axler 9D).',
      play: [
        {
          id: 'f6-o-dim',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The size of a combined table',
          prompt: '$A$ and $B$ are both $2 \\times 2$. How big is $A \\otimes B$?',
          answer: V.f6XIdim,
          tolerance: 0,
          hints: [{ text: 'Sizes multiply.' }, { text: '$2 \\times 2$.' }, { text: 'A $4 \\times 4$ table.' }],
          walkthrough: [{ text: '$A \\otimes B$ is $4 \\times 4$.' }],
        },
        {
          id: 'f6-o-act',
          kind: 'numeric',
          tier: 'core',
          title: 'Where a local gate lands',
          prompt: '$(X \\otimes I)|01\\rangle$ lands on which index?',
          answer: V.f6Idx11,
          tolerance: 0,
          hints: [{ text: '$X$ flips the first qubit, $I$ leaves the second.' }, { text: '$|01\\rangle \\to |11\\rangle$.' }, { text: '$|11\\rangle$ is index 3.' }],
          walkthrough: [{ text: '$X|0\\rangle \\otimes I|1\\rangle = |1\\rangle \\otimes |1\\rangle = |11\\rangle$, index 3.' }],
        },
        {
          id: 'f6-o-local',
          kind: 'choice',
          tier: 'core',
          title: 'Which operator touches only qubit 2?',
          prompt: 'Which operator changes only the second qubit?',
          options: [
            { text: '$X \\otimes I$', correct: false, why: 'This changes qubit 1, not qubit 2.' },
            { text: '$I \\otimes X$', correct: true, why: 'The $I$ factor leaves qubit 1 and flips qubit 2.' },
            { text: '$X \\otimes X$', correct: false, why: 'This changes both qubits.' },
            { text: '$Z \\otimes I$', correct: false, why: 'This changes qubit 1 only, and by a sign flip, not a bit flip.' },
          ],
          hints: [{ text: 'The $I$ factor does nothing.' }, { text: 'Which factor sits in the second slot?' }, { text: '$I \\otimes (\\cdot)$ touches qubit 2.' }],
          walkthrough: [{ text: '$I \\otimes X$ leaves qubit 1 and flips qubit 2.' }],
        },
      ],
    },
    {
      id: 'f6-product-or-not',
      story: F6_STORY['f6-product-or-not'],
      review: F6_REVIEW['f6-product-or-not'],
      title: 'When a joint state splits, and when it does not',
      question: 'How can we tell if two systems are independent, or tangled together?',
      lecture: {
        pages: 'N&C §2.1.7 p. 73; Axler 9D',
        summary: 'A joint state is a product when it splits back into two single states; the test is a determinant of its 2×2 coefficient table.',
      },
      books: [nc('§2.1.7, p. 73', 'The coefficient-matrix (Schmidt rank) test for a product versus an entangled two-qubit state.')],
      visual: {
        kind: 'operator-builder',
        props: { mode: 'coef-test' },
        tryThis: ['$\\theta = 0°$: a product, full reduced arrows.', '$\\theta = 45°$: the Bell state, arrows gone.', 'Find $\\det C$ at each ($0$ then $\\tfrac12$).'],
      },
      clues: [],
      insight: 'A product state $|\\psi\\rangle \\otimes |\\varphi\\rangle$ splits into two single states; an entangled one does not. The test: $\\det C = 0$.',
      insightFormal: 'A two-qubit state is a product iff its coefficient matrix $C = [c_{ab}]$ has rank 1, i.e. $\\det C = c_{00}c_{11} - c_{01}c_{10} = 0$; otherwise it is entangled.',
      play: [
        {
          id: 'f6-pr-det-prod',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A product’s determinant',
          prompt: 'For $|{+}{+}\\rangle$, what is $\\det C$ of its coefficient matrix?',
          answer: V.f6ProdDet,
          tolerance: 0.005,
          hints: [{ text: 'All four amplitudes are 0.5.' }, { text: '$0.25 - 0.25$.' }, { text: 'Zero means a product.' }],
          walkthrough: [{ text: '$\\det C = 0$, so $|{+}{+}\\rangle$ is a product.' }],
        },
        {
          id: 'f6-pr-det-bell',
          kind: 'numeric',
          tier: 'core',
          title: 'The Bell state’s determinant',
          prompt: 'For the Bell state $(|00\\rangle + |11\\rangle)/\\sqrt2$, what is $\\det C$?',
          answer: V.f6BellDet,
          tolerance: 0.005,
          hints: [{ text: '$C = \\tfrac1{\\sqrt2}\\begin{pmatrix}1 & 0\\\\ 0 & 1\\end{pmatrix}$.' }, { text: '$\\det = \\tfrac1{\\sqrt2} \\cdot \\tfrac1{\\sqrt2} - 0$.' }, { text: '$\\tfrac12 - 0$.' }],
          walkthrough: [{ text: `$\\det C = ${d(V.f6BellDet)} \\ne 0$: entangled.` }],
        },
        {
          id: 'f6-pr-which',
          kind: 'choice',
          tier: 'core',
          title: 'Spot the entangled state',
          prompt: 'Which two-qubit state is entangled?',
          options: [
            { text: '$|00\\rangle$', correct: false, why: 'This is already a single basis state: a product.' },
            { text: '$|{+}{+}\\rangle$', correct: false, why: '$\\det C = 0$: a product of two $|{+}\\rangle$ states.' },
            { text: '$(|01\\rangle + |10\\rangle)/\\sqrt2$', correct: true, why: '$\\det C = -\\tfrac12 \\ne 0$: entangled (the $\\Psi^+$ Bell state).' },
            { text: '$|0\\rangle \\otimes |{-}\\rangle$', correct: false, why: 'Written as an explicit $\\otimes$, this is already a product.' },
          ],
          hints: [{ text: 'Can it be written as one $\\otimes$ one?' }, { text: 'Compute $\\det C$.' }, { text: 'For $(|01\\rangle + |10\\rangle)/\\sqrt2$, $C = \\tfrac1{\\sqrt2}\\begin{pmatrix}0 & 1\\\\ 1 & 0\\end{pmatrix}$.' }],
          walkthrough: [{ text: '$\\det C = -\\tfrac12 \\ne 0$: entangled (the $\\Psi^+$ Bell state).' }],
        },
      ],
    },
    {
      id: 'f6-growth',
      story: F6_STORY['f6-growth'],
      review: F6_REVIEW['f6-growth'],
      title: 'Inner products factor; the memory wall',
      question: 'Why do dimensions multiply, and why does that make big quantum systems hard to store?',
      lecture: {
        pages: 'Axler 9D p. 376; N&C §2.1.7',
        summary: 'Inner products factor over $\\otimes$; dimensions multiply, so storing $n$ qubits costs $2^n$ amplitudes — a memory wall.',
      },
      books: [axler('9D, p. 376', 'The inner product on a tensor-product space, and the dimension of a multi-factor tensor product.')],
      visual: {
        kind: 'amplitude-bars',
        props: { mode: 'growth', qubits: 1 },
        tryThis: ['$n = 2$: 4 numbers.', '$n = 10$: 1024.', '$n = 30$: 16 GiB — the wall.'],
      },
      clues: [],
      insight: 'Overlaps of product states factor: $\\langle a{\\otimes}b|c{\\otimes}d\\rangle = \\langle a|c\\rangle\\langle b|d\\rangle$. Dimensions multiply, so storing $n$ qubits costs $2^n$ amplitudes.',
      insightFormal: 'The inner product on $V \\otimes W$ factors bilinearly; $\\dim(V \\otimes W) = \\dim V \\cdot \\dim W$, so an $n$-qubit register needs $2^n \\times 16$ bytes — exponential, not linear.',
      play: [
        {
          id: 'f6-g-norm',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The length of a product',
          prompt: 'What is the length of $|{+}\\rangle \\otimes |{-}\\rangle$?',
          answer: V.f6ProdNorm,
          tolerance: 0,
          hints: [{ text: 'Lengths multiply.' }, { text: '$1 \\times 1$.' }, { text: 'A product of unit states is unit length.' }],
          walkthrough: [{ text: '$\\|a \\otimes b\\| = \\|a\\|\\,\\|b\\| = 1$.' }],
        },
        {
          id: 'f6-g-mem',
          kind: 'numeric',
          tier: 'core',
          title: 'Storing 30 qubits',
          prompt: 'How many gigabytes to store a 30-qubit register (16 bytes per amplitude)?',
          answer: V.f6Mem30,
          tolerance: 0,
          hints: [{ text: '$2^{30}$ amplitudes.' }, { text: '$\\times 16$ bytes.' }, { text: '$2^{30}$ bytes is a GiB.' }],
          walkthrough: [{ text: `$2^{30} \\times 16 = ${d(V.f6Mem30, 0)}$ GiB.` }],
        },
        {
          id: 'f6-g-params',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Counting a product’s parameters',
          prompt: 'A ten-qubit product state uses how many real parameters?',
          answer: V.f6Params10Product,
          tolerance: 0,
          hints: [{ text: 'Each qubit is a point on a [[qc-bloch-sphere|Bloch sphere]].' }, { text: '2 parameters each.' }, { text: '$2 \\times 10$.' }],
          walkthrough: [{ text: `$2n = ${d(V.f6Params10Product, 0)}$, against $2\\cdot2^{10}-2 = ${d(V.f6Params10General, 0)}$ for a general state (${pct(V.f6ProdFrac)}).` }],
        },
      ],
    },
  ],
}
