/** GENERATED by content/meta.test.ts (UPDATE_META=1): do not edit by hand. */
import type { LectureMeta } from '../meta'

export const QC_META: LectureMeta[] = [
  {
    "id": "F1",
    "number": 1,
    "title": "Numbers that turn",
    "units": [
      {
        "id": "f1-number-line",
        "title": "The gap that $x^2 = -1$ leaves",
        "question": "Which equations can ordinary numbers not solve, and what new number fills the last gap?",
        "challenges": [
          "f1-n-power",
          "f1-n-roots4",
          "f1-n-quadratic",
          "f1-n-sqrt-i"
        ],
        "equations": []
      },
      {
        "id": "f1-plane",
        "title": "Numbers as points and arrows",
        "question": "How do we draw, add, measure and mirror a complex number?",
        "challenges": [
          "f1-p-modulus",
          "f1-p-sum-size",
          "f1-p-zzstar",
          "f1-p-triangle-equal"
        ],
        "equations": []
      },
      {
        "id": "f1-multiply",
        "title": "Multiplying stretches and turns",
        "question": "What does multiplying two complex numbers do to their arrows?",
        "challenges": [
          "f1-m-product",
          "f1-m-angle",
          "f1-m-power4",
          "f1-m-inverse",
          "f1-m-proof-order"
        ],
        "equations": []
      },
      {
        "id": "f1-euler",
        "title": "$e^{i\\varphi}$: walking round the unit circle",
        "question": "Why does $e$, the number of compound growth, raised to an imaginary power walk round a circle?",
        "challenges": [
          "f1-e-radians",
          "f1-e-euler-pi",
          "f1-e-cos75",
          "f1-e-limit-size",
          "f1-e-series"
        ],
        "equations": []
      },
      {
        "id": "f1-phase",
        "title": "Phases you can and cannot see",
        "question": "When arrows add, why does only the difference of their angles matter?",
        "challenges": [
          "f1-ph-cancel",
          "f1-ph-quarter",
          "f1-ph-size-one",
          "f1-ph-detect",
          "f1-ph-mz",
          "f1-ph-pi8"
        ],
        "equations": []
      }
    ]
  },
  {
    "id": "Q1",
    "number": 1,
    "title": "Stern–Gerlach and the rules of the game",
    "units": [
      {
        "id": "q1-two-spots",
        "title": "Two spots from a lopsided magnet",
        "question": "Why does a lopsided field push atoms at all, and why into exactly two spots?",
        "challenges": [
          "q1-t-spots",
          "q1-t-force",
          "q1-t-deflection",
          "q1-t-gradient",
          "q1-t-sign"
        ],
        "equations": []
      },
      {
        "id": "q1-sequences",
        "title": "A second magnet can erase the first",
        "question": "What happens when atoms sorted along z meet a magnet turned 90°, then a z magnet again?",
        "challenges": [
          "q1-s-repeat",
          "q1-s-zxz",
          "q1-s-middle-z",
          "q1-s-four",
          "q1-s-refute"
        ],
        "equations": []
      },
      {
        "id": "q1-superposition",
        "title": "Adding states: the superposition principle",
        "question": "If an atom can be in |+z⟩ or |−z⟩, what does it mean to be in both?",
        "challenges": [
          "q1-p-half",
          "q1-p-34i",
          "q1-p-normalize",
          "q1-p-mixture",
          "q1-p-difference",
          "q1-p-not-unit"
        ],
        "equations": []
      },
      {
        "id": "q1-vector-space",
        "title": "The rules for adding and scaling kets",
        "question": "Which rules must kets obey so that adding and scaling always make sense?",
        "challenges": [
          "q1-v-zero",
          "q1-v-poly",
          "q1-v-degree",
          "q1-v-real-scalars",
          "q1-v-lazy"
        ],
        "equations": []
      },
      {
        "id": "q1-inner-product",
        "title": "Lengths and angles for complex vectors",
        "question": "How do we measure a ket’s length, and the overlap of two kets, when the numbers are complex?",
        "challenges": [
          "q1-i-dot",
          "q1-i-norm",
          "q1-i-orth",
          "q1-i-conj-lin",
          "q1-i-weighted"
        ],
        "equations": []
      }
    ]
  }
]
