/** GENERATED by content/meta.test.ts (UPDATE_META=1): do not edit by hand. */
import type { LectureMeta } from '../meta'

export const QC_META: LectureMeta[] = [
  {
    "id": "F1",
    "number": 1,
    "title": "Numbers that turn",
    "units": [
      {
        "id": "f1-number-line",
        "title": "The gap that x² = −1 leaves",
        "question": "Which equations can ordinary numbers not solve, and what new number fills the last gap?",
        "challenges": [
          "f1-n-power",
          "f1-n-roots4",
          "f1-n-quadratic",
          "f1-n-sqrt-i"
        ],
        "equations": []
      },
      {
        "id": "f1-plane",
        "title": "Numbers as points and arrows",
        "question": "How do we draw, add, measure and mirror a complex number?",
        "challenges": [
          "f1-p-modulus",
          "f1-p-sum-size",
          "f1-p-zzstar",
          "f1-p-triangle-equal"
        ],
        "equations": []
      },
      {
        "id": "f1-multiply",
        "title": "Multiplying stretches and turns",
        "question": "What does multiplying two complex numbers do to their arrows?",
        "challenges": [
          "f1-m-product",
          "f1-m-angle",
          "f1-m-power4",
          "f1-m-inverse",
          "f1-m-proof-order"
        ],
        "equations": []
      },
      {
        "id": "f1-euler",
        "title": "eⁱᵠ: walking round the unit circle",
        "question": "Why does $e$, the number of compound growth, raised to an imaginary power walk round a circle?",
        "challenges": [
          "f1-e-radians",
          "f1-e-euler-pi",
          "f1-e-cos75",
          "f1-e-limit-size",
          "f1-e-series"
        ],
        "equations": []
      },
      {
        "id": "f1-phase",
        "title": "Phases you can and cannot see",
        "question": "When arrows add, why does only the difference of their angles matter?",
        "challenges": [
          "f1-ph-cancel",
          "f1-ph-quarter",
          "f1-ph-size-one",
          "f1-ph-detect",
          "f1-ph-mz",
          "f1-ph-pi8"
        ],
        "equations": []
      }
    ]
  },
  {
    "id": "Q1",
    "number": 1,
    "title": "Stern–Gerlach and the rules of the game",
    "units": [
      {
        "id": "q1-two-spots",
        "title": "Two spots from a lopsided magnet",
        "question": "Why does a lopsided field push atoms at all, and why into exactly two spots?",
        "challenges": [
          "q1-t-spots",
          "q1-t-force",
          "q1-t-deflection",
          "q1-t-gradient",
          "q1-t-sign"
        ],
        "equations": []
      },
      {
        "id": "q1-sequences",
        "title": "A second magnet can erase the first",
        "question": "What happens when atoms sorted along z meet a magnet turned 90°, then a z magnet again?",
        "challenges": [
          "q1-s-repeat",
          "q1-s-zxz",
          "q1-s-middle-z",
          "q1-s-four",
          "q1-s-refute"
        ],
        "equations": []
      },
      {
        "id": "q1-superposition",
        "title": "Adding states: the superposition principle",
        "question": "If an atom can be in |+z⟩ or |−z⟩, what does it mean to be in both?",
        "challenges": [
          "q1-p-half",
          "q1-p-34i",
          "q1-p-normalize",
          "q1-p-mixture",
          "q1-p-difference",
          "q1-p-not-unit"
        ],
        "equations": []
      },
      {
        "id": "q1-vector-space",
        "title": "The rules for adding and scaling kets",
        "question": "Which rules must kets obey so that adding and scaling always make sense?",
        "challenges": [
          "q1-v-zero",
          "q1-v-poly",
          "q1-v-degree",
          "q1-v-real-scalars",
          "q1-v-lazy"
        ],
        "equations": []
      },
      {
        "id": "q1-inner-product",
        "title": "Lengths and angles for complex vectors",
        "question": "How do we measure a ket’s length, and the overlap of two kets, when the numbers are complex?",
        "challenges": [
          "q1-i-dot",
          "q1-i-norm",
          "q1-i-orth",
          "q1-i-conj-lin",
          "q1-i-weighted"
        ],
        "equations": []
      }
    ]
  },
  {
    "id": "Q2",
    "number": 2,
    "title": "Coordinates, bases and turning frames",
    "units": [
      {
        "id": "q2-basis",
        "title": "Independent arrows and a basis",
        "question": "When does a set of arrows give every vector one, and only one, address?",
        "challenges": [
          "q2-b-dim",
          "q2-b-comp",
          "q2-b-independent",
          "q2-b-slanted"
        ],
        "equations": []
      },
      {
        "id": "q2-gram-schmidt",
        "title": "Straightening a basis with Gram–Schmidt",
        "question": "How do we turn independent arrows into an orthonormal basis?",
        "challenges": [
          "q2-g-left",
          "q2-g-3d",
          "q2-g-third",
          "q2-g-order"
        ],
        "equations": []
      },
      {
        "id": "q2-spin-space",
        "title": "Spin states in the z and x frames",
        "question": "How do the notes pin down the numbers in |±x⟩, and how do we go back?",
        "challenges": [
          "q2-s-amp",
          "q2-s-delta",
          "q2-s-inverse",
          "q2-s-angle"
        ],
        "equations": []
      },
      {
        "id": "q2-operators",
        "title": "Operators, outer products and their tables",
        "question": "What does an operator do to arrows, and how does a basis turn it into a table?",
        "challenges": [
          "q2-o-len",
          "q2-o-outer",
          "q2-o-element",
          "q2-o-linear"
        ],
        "equations": []
      },
      {
        "id": "q2-change",
        "title": "Changing coordinates with one matrix",
        "question": "How do the numbers of a state, and of an operator, change with the basis?",
        "challenges": [
          "q2-c-u22",
          "q2-c-d2",
          "q2-c-sz",
          "q2-c-dagger"
        ],
        "equations": []
      },
      {
        "id": "q2-photon",
        "title": "Turning the frame of a photon",
        "question": "Why does turning the polarizer frame only put a phase on circular light?",
        "challenges": [
          "q2-p-malus",
          "q2-p-spin",
          "q2-p-phase",
          "q2-p-jz"
        ],
        "equations": []
      }
    ]
  },
  {
    "id": "Q3",
    "number": 3,
    "title": "Measurement, the Bloch sphere and uncertainty",
    "units": [
      {
        "id": "q3-born",
        "title": "Chances from overlaps and projectors",
        "question": "How does an overlap become a chance, and how does an operator hold it?",
        "challenges": [
          "q3-b-overlap",
          "q3-b-sandwich",
          "q3-b-phase",
          "q3-b-missing"
        ],
        "equations": []
      },
      {
        "id": "q3-bloch",
        "title": "Every spin state is a point on a sphere",
        "question": "Which two angles fix any spin state, and where is its opposite?",
        "challenges": [
          "q3-s-theta",
          "q3-s-nx",
          "q3-s-minus",
          "q3-s-120"
        ],
        "equations": []
      },
      {
        "id": "q3-spin-operators",
        "title": "Spin operators built from projectors",
        "question": "How do Stern–Gerlach filters build S_z, S_x, S_y and S_n?",
        "challenges": [
          "q3-o-pz",
          "q3-o-sigman",
          "q3-o-sy",
          "q3-o-px"
        ],
        "equations": []
      },
      {
        "id": "q3-observables",
        "title": "Measurement rules and why observables are Hermitian",
        "question": "What does a measurement do to a state, what is its average, and why is its operator Hermitian?",
        "challenges": [
          "q3-m-avg",
          "q3-m-sx",
          "q3-m-adjoint",
          "q3-m-hermitian"
        ],
        "equations": []
      },
      {
        "id": "q3-spectral",
        "title": "Real eigenvalues, spectral form and spread",
        "question": "Why are an observable’s values real, and how do its eigenvectors give powers and spreads?",
        "challenges": [
          "q3-e-eig",
          "q3-e-disp",
          "q3-e-f",
          "q3-e-spread-x"
        ],
        "equations": []
      },
      {
        "id": "q3-uncertainty",
        "title": "Commutators and the floor under two spreads",
        "question": "When can two quantities both be sharp, and how small can two spreads be together?",
        "challenges": [
          "q3-u-comm",
          "q3-u-floor",
          "q3-u-which",
          "q3-u-schwarz",
          "q3-u-steps"
        ],
        "equations": []
      }
    ]
  },
  {
    "id": "Q5",
    "number": 5,
    "title": "Deutsch's trick and interference",
    "units": [
      {
        "id": "q5-problem",
        "title": "Constant or balanced: Deutsch's question",
        "question": "What does Deutsch's problem ask, and why does a classical computer look twice?",
        "challenges": [
          "q5-p-count",
          "q5-p-which",
          "q5-p-xor",
          "q5-p-queries"
        ],
        "equations": []
      },
      {
        "id": "q5-oracle",
        "title": "The f-CNOT and the phase kickback",
        "question": "How does a quantum computer ask about f, and where does the answer land?",
        "challenges": [
          "q5-o-cnot",
          "q5-o-out",
          "q5-o-kick",
          "q5-o-phase"
        ],
        "equations": [
          "U_f|x\\rangle|y\\rangle = |x\\rangle|y \\oplus f(x)\\rangle"
        ]
      },
      {
        "id": "q5-one-value",
        "title": "Both values in, only one out",
        "question": "If one query computes f(0) and f(1) together, what can a reading return?",
        "challenges": [
          "q5-v-prob",
          "q5-v-wh",
          "q5-v-values",
          "q5-v-state"
        ],
        "equations": []
      },
      {
        "id": "q5-deutsch",
        "title": "Deutsch's circuit: one query, a global answer",
        "question": "How does one use of U_f decide constant or balanced?",
        "challenges": [
          "q5-d-read",
          "q5-d-psi2",
          "q5-d-steps",
          "q5-d-sign"
        ],
        "equations": [
          "|\\psi_3\\rangle = \\pm|f(0) \\oplus f(1)\\rangle|-\\rangle"
        ]
      },
      {
        "id": "q5-interferometer",
        "title": "Two paths, one photon: Deutsch in glass",
        "question": "Why does one photon through two splitters tell equal phases from unequal ones?",
        "challenges": [
          "q5-i-bs",
          "q5-i-p90",
          "q5-i-p45",
          "q5-i-which"
        ],
        "equations": [
          "P(\\text{output 1}) = \\cos^2\\tfrac{\\varphi_1 - \\varphi_0}2"
        ]
      },
      {
        "id": "q5-other-models",
        "title": "Two other ways to compute",
        "question": "Can a computation run on slowly changed energies, or on measurements alone?",
        "challenges": [
          "q5-m-gap0",
          "q5-m-gapmin",
          "q5-m-w",
          "q5-m-byproduct"
        ],
        "equations": [
          "\\mathcal H(s) = (1-s)\\mathcal H_0 + s\\mathcal H_1"
        ]
      }
    ]
  }
]
