/**
 * Chapter Q1 glossary (Physics 709; P-Q1-story §5), merged into the lazy course pack by file name (pack.ts). Every entry
 * has a Ground-up sentence (`gloss`, ≤ 25 words) and a Formal one (`formal`, ≤ 40), paraphrased; `bridge` names a
 * Spin Lab unit (content/qc709/bridges.ts) that teaches the same idea, offered in the popover. Ids start `qc-`; an
 * entry named `qc-<448 id>` also satisfies the "gloss at first use" lint for that technical term (content/symbols.test.ts).
 */
import type { GlossEntry } from '../schema'

export const GLOSSARY: GlossEntry[] = [
  /* q1-two-spots */
  {
    id: 'qc-stern-gerlach',
    term: 'Stern–Gerlach experiment',
    gloss: 'Silver atoms fly through a lopsided magnet and land on a plate in two spots, showing that spin comes in two values.',
    formal: 'The deflection of an Ag beam by an inhomogeneous magnetic field, which resolves the spectrum of the moment’s $z$ component (1921–22).',
    first: 'q1-two-spots:b1',
    bridge: 'qc-l1-quantized',
  },
  {
    id: 'qc-magnetic-moment',
    term: 'magnetic moment $\\vec\\mu$',
    gloss: 'How strong a tiny magnet is, and which way it points.',
    formal: 'The vector $\\vec\\mu$ whose energy in a field $\\vec B$ is $E = -\\vec\\mu\\cdot\\vec B$.',
    first: 'q1-two-spots:b2',
    symbols: ['\\vec\\mu'],
    bridge: 'qc-l1-quantized',
  },
  {
    id: 'qc-field-gradient',
    term: 'field gradient',
    gloss: 'How fast a magnetic field’s strength changes from one place to the next.',
    formal: 'A derivative such as $\\partial B_z/\\partial z$, part of the gradient of $\\vec B$; a nonzero gradient exerts a force on a moment.',
    first: 'q1-two-spots:b3',
    bridge: 'qc-l1-quantized',
  },
  {
    id: 'qc-quantized',
    term: 'quantized',
    gloss: 'Coming only in separate values, like the steps of a stair, never anything in between.',
    formal: 'Having a discrete spectrum; here the moment’s $z$ component takes two values, and $S_z$ takes $\\pm\\hbar/2$.',
    first: 'q1-two-spots:b5',
    bridge: 'qc-l1-quantized',
  },
  {
    id: 'qc-hbar',
    term: 'reduced Planck constant $\\hbar$',
    gloss: 'A tiny fixed number of nature, about $1.05 \\times 10^{-34}$ joule-seconds, that sets the size of spin.',
    formal: 'The constant $\\hbar = h/2\\pi$; the engine works in units with $\\hbar = 1$, and the page appends ħ to spin values.',
    first: 'q1-two-spots:b5',
    symbols: ['\\hbar'],
    bridge: 'qc-l1-quantized',
  },
  {
    id: 'qc-spin',
    term: 'spin',
    gloss: 'A built-in turning property of particles such as the electron; its up–down part is always $+\\hbar/2$ or $-\\hbar/2$.',
    formal: 'Intrinsic angular momentum $\\vec S$; for spin ½ each component has eigenvalues $\\pm\\hbar/2$, and $\\vec S = \\hbar\\vec\\sigma/2$.',
    first: 'q1-two-spots:b5',
    bridge: 'qc-l1-quantized',
  },
  {
    id: 'qc-bohr-magneton',
    term: 'Bohr magneton $\\mu_B$',
    gloss: 'The natural unit of an electron’s magnetic strength, about $9.27 \\times 10^{-24}$ joules per tesla.',
    formal: 'The unit $\\mu_B = e\\hbar/2m_e$ in SI units; the Gaussian form carries an extra factor of the speed of light.',
    first: 'q1-two-spots:b6',
    symbols: ['\\mu_B'],
  },
  {
    id: 'qc-g-factor',
    term: 'g-factor',
    gloss: 'The number, close to 2 for an electron, that turns a spin into a magnetic strength.',
    formal: 'The factor $g$ in $\\vec\\mu = -g\\mu_B\\vec S/\\hbar$; for the electron $g$ is slightly above 2.',
    first: 'q1-two-spots:b6',
  },
  {
    id: 'qc-precession',
    term: 'precession',
    gloss: 'The circling of a spinning magnet’s axis around a field, like the wobble of a tilted top.',
    formal: 'The rotation of $\\vec\\mu$ about $\\vec B$ at the Larmor rate $g\\mu_B B/\\hbar$, which averages the transverse parts of the moment to zero.',
    first: 'q1-two-spots:b7',
    bridge: 'qc-l1-quantized',
  },
  /* q1-sequences */
  {
    id: 'qc-sequential-measurement',
    term: 'sequential measurement',
    gloss: 'Sending the atoms that one magnet kept into another magnet, and so on down a row.',
    formal: 'A chain of filters: each leaves the eigenstate of its outcome, and probabilities multiply along a path.',
    first: 'q1-sequences:b1',
    bridge: 'qc-l1-sequential',
  },
  {
    id: 'qc-hidden-label',
    term: 'hidden label',
    gloss: 'The guess that each atom secretly carries fixed answers that magnets only read off.',
    formal: 'A hidden-variable model with joint definite values, such as $|{+z}; {+x}\\rangle$ in the notes (p. 3).',
    first: 'q1-sequences:b4',
    bridge: 'qc-l1-quantized',
  },
  /* q1-superposition */
  {
    id: 'qc-ket',
    term: 'ket $|\\psi\\rangle$',
    gloss: 'The symbol for a quantum state; it holds everything that can be predicted about the system.',
    formal: 'A vector of the state space, written in Dirac notation.',
    first: 'q1-superposition:b1',
    symbols: ['|\\cdot\\rangle'],
    bridge: 'qc-l1-vectors',
  },
  {
    id: 'qc-dirac-notation',
    term: 'Dirac notation',
    gloss: 'Writing states as kets, like $|\\psi\\rangle$, and their partners as bras, like $\\langle\\psi|$.',
    formal: 'Bra–ket notation for vectors, dual vectors and their inner products.',
    first: 'q1-superposition:b1',
    bridge: 'qc-l2-vector-space',
  },
  {
    id: 'qc-hilbert-space',
    term: 'Hilbert space',
    gloss: 'The space where kets live: they can be added, scaled, and measured for length and angle.',
    formal: 'A complete inner-product space; a finite-dimensional inner-product space is complete automatically.',
    first: 'q1-superposition:b1',
    bridge: 'qc-l2-vector-space',
  },
  {
    id: 'qc-superposition',
    term: 'superposition principle',
    gloss: 'If a system can be in each of two states, it can also be in any mix of them.',
    formal: 'For states $|\\psi_1\\rangle, |\\psi_2\\rangle$ and complex $c_1, c_2$ with a nonzero sum, $c_1|\\psi_1\\rangle + c_2|\\psi_2\\rangle$, once normalized, is a state.',
    first: 'q1-sequences:b6',
    bridge: 'qc-l1-vectors',
  },
  {
    id: 'qc-born-rule',
    term: 'Born rule',
    gloss: 'An outcome’s chance is the size of its number in the state, squared.',
    formal: 'For a normalized $|\\psi\\rangle$, the probability of outcome $k$ is $|\\langle k|\\psi\\rangle|^2$.',
    first: 'q1-superposition:b3',
    bridge: 'qc-l3-postulates',
  },
  {
    id: 'qc-mixture',
    term: 'mixture',
    gloss: 'A beam made of different states in fixed shares, with no definite phase between them.',
    formal: 'An ensemble of states with weights and no phase relation; its density matrix is the weighted sum of their projectors (Chapter Q6).',
    first: 'q1-superposition:b6',
    bridge: 'qc-l6-mixture',
  },
  {
    id: 'qc-normalized',
    term: 'normalized',
    gloss: 'Divided by its own length, so that its new length is 1.',
    formal: 'Of unit norm; any nonzero vector becomes one after division by its norm.',
    first: 'q1-superposition:b2',
    bridge: 'qc-l1-vectors',
  },
  /* q1-vector-space */
  {
    id: 'qc-vector-space',
    term: 'vector space',
    gloss: 'A set of objects that can be added and scaled by numbers, following a fixed list of rules.',
    formal: 'A set with addition and scalar multiplication over a field that satisfies Axler’s axioms (Def. 1.20).',
    first: 'q1-vector-space:b1',
    bridge: 'qc-l2-vector-space',
  },
  {
    id: 'qc-scalar',
    term: 'scalar',
    gloss: 'A plain number, real or complex, used to scale a vector.',
    formal: 'An element of the field of the vector space.',
    first: 'q1-vector-space:b1',
    bridge: 'qc-l2-vector-space',
  },
  {
    id: 'qc-closure',
    term: 'closure',
    gloss: 'A set is closed when combining its members always gives another member.',
    formal: 'A set is closed under an operation when the result of the operation stays in the set.',
    first: 'q1-vector-space:b2',
    bridge: 'qc-l2-vector-space',
  },
  {
    id: 'qc-zero-vector',
    term: 'zero vector 0',
    gloss: 'The vector that changes nothing when added; its length is 0, so it is never a state.',
    formal: 'The additive identity of the space, written $|0\\rangle$ in the notes and 0 here, because $|0\\rangle$ is a qubit state.',
    first: 'q1-vector-space:b3',
    bridge: 'qc-l2-vector-space',
  },
  {
    id: 'qc-additive-inverse',
    term: 'opposite vector',
    gloss: 'The vector that cancels a given vector when the two are added, leaving the zero vector.',
    formal: 'The unique vector that adds to a given one to give 0 (Axler 1.27).',
    first: 'q1-vector-space:b3',
    bridge: 'qc-l2-vector-space',
  },
  {
    id: 'qc-polynomial-space',
    term: 'polynomial space',
    gloss: 'All polynomials up to a chosen degree; they add and scale like the lists of their coefficients.',
    formal: 'The space of real polynomials of degree at most $n$, identified with the lists of their coefficients (Axler 2.12).',
    first: 'q1-vector-space:b5',
  },
  /* q1-inner-product */
  {
    id: 'qc-bra',
    term: 'bra $\\langle\\psi|$',
    gloss: 'The partner of a ket: a row of the ket’s numbers, each one conjugated.',
    formal: 'The dual vector of a ket, its conjugate transpose in components.',
    first: 'q1-inner-product:b1',
    symbols: ['\\langle\\cdot|'],
    bridge: 'qc-l2-inner-product',
  },
  {
    id: 'qc-dual-space',
    term: 'dual space',
    gloss: 'The set of all bras, one partner for every ket.',
    formal: 'The space of linear functionals on the state space; the map from a ket to its bra is antilinear.',
    first: 'q1-inner-product:b1',
    bridge: 'qc-l2-vector-space',
  },
  {
    id: 'qc-inner-product',
    term: 'inner product',
    gloss: 'A way to combine a bra and a ket into one number that measures overlap, length and angle.',
    formal: 'A positive-definite, conjugate-symmetric map from pairs of vectors to scalars, linear in the second slot.',
    first: 'q1-inner-product:b2',
    symbols: ['\\langle\\cdot|\\cdot\\rangle'],
    bridge: 'qc-l2-inner-product',
  },
  {
    id: 'qc-conjugate-symmetry',
    term: 'conjugate symmetry',
    gloss: 'Swapping the two sides of an inner product gives its complex conjugate.',
    formal: 'The rule that the inner product with its two slots exchanged is the complex conjugate of the original.',
    first: 'q1-inner-product:b2',
    bridge: 'qc-l2-inner-product',
  },
  {
    id: 'qc-sesquilinear',
    term: 'sesquilinear',
    gloss: 'Linear on the ket side, with numbers conjugated on the bra side.',
    formal: 'Linear in one slot and conjugate-linear in the other; in physics the conjugate-linear slot is the first.',
    first: 'q1-inner-product:b2',
  },
  {
    id: 'qc-norm',
    term: 'norm',
    gloss: 'The length of a vector: the square root of its inner product with itself.',
    formal: 'The length of a vector, the square root of its inner product with itself, written with single bars in the notes.',
    first: 'q1-inner-product:b4',
    bridge: 'qc-l2-inner-product',
  },
  {
    id: 'qc-hermitian-matrix',
    term: 'Hermitian matrix',
    gloss: 'A square table equal to its own mirror image across the diagonal, with every entry conjugated.',
    formal: 'A square matrix equal to its conjugate transpose, so each entry is the conjugate of its mirror entry.',
    first: 'q1-inner-product:b5',
    bridge: 'qc-l3-eigen',
  },
  {
    id: 'qc-weighted-inner-product',
    term: 'weighted inner product',
    gloss: 'An inner product with a square table of numbers placed between the bra and the ket.',
    formal: 'The form $\\beta^\\dagger M\\alpha$, an inner product exactly when $M$ is Hermitian with positive eigenvalues.',
    first: 'q1-inner-product:b5',
  },
  {
    id: 'qc-projection',
    term: 'projection (shadow)',
    gloss: 'The shadow one arrow casts on another arrow’s line when light falls straight onto that line.',
    formal: 'The orthogonal projection of one vector onto the line spanned by another, along which the first splits into parallel and perpendicular parts.',
    first: 'q1-inner-product:b6',
    bridge: 'qc-l3-projectors',
  },
]
