import { I } from '../../physics/complex'
import { inner, vec } from '../../physics/linalg'
import { eigh } from '../../physics/qc/cmat'
import { SZ } from '../../physics/spin'
import { URL } from '../refs'
import type { Lecture } from '../schema'
import { Q1_REVIEW } from './Q1.review'
import { Q1_STORY } from './Q1.story'
import { V, close, d, tf, uf } from './Q1.values'

// Physics 709, chapter Q1: the notes' Lecture 1 (9/2, printed pp. 2–5), in both tracks. Every number a learner sees is
// computed in Q1.values.ts, then asserted in keyed claims (content.test.tsx runs `holds`; claims.test.ts compares each
// key with numpy, pipeline/claims_qc709/q1.py). Plan: docs/roles/proposals/P-Q1-story.md; rulings
// docs/roles/decisions/qc709-pilots.md and qc709-nc.md. No Q1 challenge is assigned homework in either course, and none
// works HW1 P2 (the tilted middle magnet): the Try-it bench stays editable, with no preset tilt (ruling 3).

export const Q1: Lecture = {
  id: 'Q1',
  number: 1,
  title: 'Stern–Gerlach and the rules of the game',
  date: 'Sep 2, 2026',
  outcomes: [
    'Explain how a lopsided field pushes a small magnet, and why the plate shows two spots, not a smear.',
    'Predict what z, then x, then z magnets do, and say what “a measurement can erase an earlier one” means.',
    'Write a superposition of two states, rescale it, and find each outcome’s chance.',
    'List the rules of a vector space, and test whether a set of objects obeys them.',
    'Compute an inner product and a length for complex vectors, and say why the bra’s numbers are conjugated.',
  ],
  // F1's stations (written in parallel); the map draws Q1's own concepts from content/qc709/concepts.ts
  prerequisites: ['qc-complex-plane', 'qc-complex-multiply', 'qc-phase'],
  // Symbols defined in the text itself (symbol → the beat or site whose sentence defines it), Ground-up track. The
  // plan's flags (P-Q1-story §7) stand: a is an acceleration in 1.4 and a scalar in 4.4; the notes' α, β are amplitudes
  // in 3.5 and vectors |α⟩, |β⟩ from Unit 1.4 on (said in q1-vector-space:b1).
  symbols: {
    '\\mu_z': 'q1-two-spots:b2',
    B_z: 'q1-two-spots:b2',
    E: 'q1-two-spots:b2',
    G: 'q1-two-spots:b3',
    F_z: 'q1-two-spots:b3',
    B_0: 'q1-two-spots:b3',
    '\\mu': 'q1-two-spots:b4',
    '\\Delta': 'q1-two-spots:b4',
    m: 'q1-two-spots:b4',
    a: 'q1-two-spots:b4',
    t: 'q1-two-spots:b4',
    L: 'q1-two-spots:b4',
    v: 'q1-two-spots:b4',
    e: 'q1-two-spots:b6',
    m_e: 'q1-two-spots:b6',
    S_z: 'q1-two-spots.review',
    '|\\cdot\\rangle': 'q1-sequences:b1',
    '|+z\\rangle': 'q1-sequences:b1',
    '|-z\\rangle': 'q1-sequences:b1',
    '\\widehat': 'q1-sequences:b1',
    '|+x\\rangle': 'q1-sequences:b3',
    '|-x\\rangle': 'q1-sequences:b3',
    '|+z;\\pmx\\rangle': 'q1-sequences:b4',
    '|\\psi\\rangle': 'q1-superposition:b1',
    '\\psi': 'q1-superposition:b1',
    '|\\psi_1\\rangle': 'q1-superposition:b2',
    '|\\psi_2\\rangle': 'q1-superposition:b2',
    c_1: 'q1-superposition:b2',
    c_2: 'q1-superposition:b2',
    '|+y\\rangle': 'q1-superposition:b3',
    P: 'q1-superposition:b4',
    '|0\\rangle': 'q1-superposition:b5',
    '|1\\rangle': 'q1-superposition:b5',
    '\\alpha': 'q1-superposition:b5',
    '\\beta': 'q1-superposition:b5',
    '|\\alpha\\rangle': 'q1-vector-space:b2',
    '|\\beta\\rangle': 'q1-vector-space:b2',
    '|\\gamma\\rangle': 'q1-vector-space:b2',
    b: 'q1-vector-space:b4',
    n: 'q1-vector-space:b5',
    V: 'q1-vector-space:b5',
    c: 'q1-vector-space.play.q1-v-lazy',
    '\\langle\\cdot|\\cdot\\rangle': 'q1-inner-product:b1',
    '|\\chi\\rangle': 'q1-inner-product:b1',
    '|c\\beta\\rangle': 'q1-inner-product:b3',
    '|c_1\\beta+c_2\\gamma\\rangle': 'q1-inner-product:b3',
    w: 'q1-inner-product:b3',
    a_1: 'q1-inner-product:b4',
    a_2: 'q1-inner-product:b4',
    b_1: 'q1-inner-product:b4',
    b_2: 'q1-inner-product:b4',
    M: 'q1-inner-product:b5',
    '\\dagger': 'q1-inner-product:b5',
    '\\theta': 'q1-inner-product:b6',
    '\\langle\\cdot\\rangle': 'q1-inner-product:b7',
    '|i+z\\rangle': 'q1-inner-product:b7',
  },
  // The Formal track defines more, and some symbols earlier (merged over `symbols` for that track only)
  symbolsFormal: {
    '\\vec r': 'q1-two-spots:b1',
    '\\partial': 'q1-two-spots:b1',
    B_z: 'q1-two-spots:b1',
    '\\vec F': 'q1-two-spots:b3',
    '\\nabla': 'q1-two-spots:b3',
    '\\theta_\\mu': 'q1-two-spots:b4',
    D: 'q1-two-spots:b4',
    S_z: 'q1-two-spots:b5',
    g: 'q1-two-spots:b6',
    B_x: 'q1-two-spots:b7',
    B_y: 'q1-two-spots:b7',
    '\\omega_L': 'q1-two-spots:b7',
    B: 'q1-two-spots:b7',
    '\\langle\\cdot\\rangle': 'q1-two-spots:b7',
    '\\mu_x': 'q1-two-spots:b7',
    '\\mu_y': 'q1-two-spots:b7',
    '|\\cdot\\rangle': 'q1-two-spots:b8',
    '|+Z\\rangle': 'q1-two-spots:b8',
    a: 'q1-two-spots.play.q1-t-deflection.hints[0]',
    t: 'q1-two-spots.play.q1-t-deflection.hints[1]',
    '|0\\rangle': 'q1-sequences:b1',
    '\\langle\\cdot|': 'q1-sequences:b2',
    S_x: 'q1-sequences:b3',
    '|+z;+x\\rangle': 'q1-sequences:b4',
    S_y: 'q1-sequences:b6',
    '|\\Psi\\rangle': 'q1-superposition:b2',
    '|\\psi_3\\rangle': 'q1-superposition:b2',
    d_1: 'q1-superposition:b2',
    d_2: 'q1-superposition:b2',
    '|\\psi(\\vartheta)\\rangle': 'q1-superposition:b2',
    '\\vartheta': 'q1-superposition:b2',
    '|-Z\\rangle': 'q1-superposition:b5',
    V: 'q1-vector-space:b1',
    F: 'q1-vector-space:b1',
    '|\\alpha\\rangle': 'q1-vector-space:b1',
    '|\\beta\\rangle': 'q1-vector-space:b1',
    '|\\gamma\\rangle': 'q1-vector-space:b1',
    c: 'q1-vector-space:b4',
    P_n: 'q1-vector-space:b5',
    '\\dagger': 'q1-inner-product:b1',
    '|c_1\\beta+c_2\\gamma\\rangle': 'q1-inner-product:b2',
    T: 'q1-inner-product:b4',
    a_i: 'q1-inner-product:b4',
    b_i: 'q1-inner-product:b4',
    M_ij: 'q1-inner-product:b5',
    M_ji: 'q1-inner-product:b5',
    I: 'q1-inner-product:b5',
    '\\sigma_y': 'q1-inner-product:b5',
    '\\sigma_z': 'q1-inner-product:b8',
  },
  corrections: [
    {
      where: 'notes p. 2',
      says: 'The notes say the moment is g μ_B L_z/ħ, with μ_B = eħ/2m_e c and an angular momentum L_z = ±ħ/2.',
      shouldSay: `The values ±ħ/2 belong to the spin S_z, and for an electron μ_z = −g μ_B S_z/ħ with g close to 2, so the moment points against the spin. In SI units μ_B = eħ/2m_e = ${d(V.q1MuB)} × 10⁻²⁴ J/T; the extra speed of light belongs to Gaussian units.`,
      check: () => close(V.q1MuB, 9.2740100783, 1e-9) && V.q1SignDown > 0,
    },
    {
      where: 'notes p. 2',
      says: 'The notes say the atoms land on a screen.',
      shouldSay: 'The 1922 deposit formed on a glass plate, which is what the bench draws. This chapter says plate, as Spin Lab does.',
      check: () => V.q1Defl > 0,
    },
    {
      where: 'notes p. 2',
      says: 'The notes say the electron’s angular momentum is quantized in units of ħ/2.',
      shouldSay: 'Its z component takes the two values +ħ/2 and −ħ/2, which are one ħ apart. The plate shows those two values, not a ladder of steps of ħ/2.',
      check: () => close(eigh(SZ).values[1] - eigh(SZ).values[0], 1) && close(eigh(SZ).values[1], 0.5),
    },
    {
      where: 'notes p. 2',
      says: 'The notes call ħ the Planck constant.',
      shouldSay: 'ħ is the reduced Planck constant, h/2π; the Planck constant h is 2π times larger. The engine counts spin in units of ħ, so S_z reads ±½.',
      check: () => close(eigh(SZ).values[1], 0.5),
    },
    {
      where: 'notes p. 2',
      says: 'The notes give F_z = μ_z ∂B_z/∂z for a field along z.',
      shouldSay: 'That is an idealization. A field with no sources that changes along z must also change sideways; the moment’s fast precession averages the sideways pushes away (Unit 1.1, beyond the notes).',
      check: () => close(V.q1Defl, 0.5 * V.q1Accel * 1e4 * (V.q1Flight * 1e-6) ** 2 * 1000, 1e-12),
    },
    {
      where: 'notes p. 3',
      says: 'The notes say only a single measurement can be performed on a quantum system.',
      shouldSay: 'Successive measurements are possible and repeatable: z then z agrees every time. What fails is keeping an earlier answer, because a measurement along a new axis replaces the state the first one prepared. Only a destructive measurement allows just one.',
      check: () => close(V.q1Repeat, 1) && close(V.q1Zxz, 1 / 8),
    },
    {
      where: 'notes p. 3',
      says: 'The notes say any linear combination of two states is again a state.',
      shouldSay: 'Any combination with a nonzero sum is, once divided by its length. |+z⟩ − |+z⟩ is the zero vector, which no rescaling turns into a state, and |+z⟩ + |−z⟩ must be divided by √2.',
      check: () => close(V.q1ZeroSum, 0) && close(V.q1LenSqrt2, Math.SQRT2),
    },
    {
      where: 'notes p. 4',
      says: 'The notes say seven properties define a vector space.',
      shouldSay: 'They leave out 1|α⟩ = |α⟩ (Axler 1.20, p. 12). Without it, the scaling c|α⟩ = 0 for every c obeys every listed property (Unit 1.4).',
      check: () => V.q1Lazy === 1,
    },
    {
      where: 'notes p. 4',
      says: 'The notes write the zero vector as |0⟩.',
      shouldSay: 'In this course |0⟩ is the qubit state |+z⟩, of length 1, so the zero vector is written 0, of length 0. N&C make the same exception (p. 62).',
      check: () => close(V.q1KetZeroNotZero, 1) && close(V.q1ZeroVec, 0),
    },
    {
      where: 'notes p. 4',
      says: 'The notes list a unique zero vector and a unique inverse among the rules.',
      shouldSay: 'Uniqueness is not an extra rule: it follows from the others (Axler 1.26–1.27, p. 14). Harmless, but not an axiom.',
      check: () => close(V.q1Inverse, 0),
    },
    {
      where: 'notes p. 4',
      says: 'The notes say the nth-order real polynomials form a vector space.',
      shouldSay: 'The polynomials of degree at most n do (Axler 2.12, p. 31). Degree exactly n is not closed: (x² + x) + (−x² + 1) = x + 1.',
      check: () => close(V.q1Degree, 0),
    },
    {
      where: 'notes p. 4',
      says: 'The notes call the inner product a bilinear map of a vector and a dual vector.',
      shouldSay: `Over the complex numbers it is sesquilinear: conjugate-linear in the bra, as the notes’ own fifth rule shows. A bilinear form would give (3, 4i) a “length squared” of ${d(V.q1Bilinear34i, 0)} instead of ${d(V.q1Norm34i, 0)}.`,
      check: () => close(V.q1Bilinear34i, -7) && close(V.q1Norm34i, 25),
    },
    {
      where: 'notes p. 5, Fig. 3',
      says: 'The notes give ⟨α|β⟩/|α| = |β| cos θ as a general statement.',
      shouldSay: 'That holds for real vectors. For complex ones ⟨α|β⟩ can be complex, so the shadow uses its real part: α = (1, 0) and β = (i, 0) would give the “length” i.',
      check: () => close(inner(vec(1, 0), vec(I, 0)).im, 1),
    },
  ],
  watch: [
    {
      source: 'mit805',
      where: 'Lecture 3 (second half)',
      adds: 'Zwiebach walks through the real Stern–Gerlach apparatus: why a field gradient deflects a magnetic moment, and what the two spots mean.',
      url: URL.mit805(3),
    },
  ],
  units: [
    {
      id: 'q1-two-spots',
      story: Q1_STORY['q1-two-spots'],
      review: Q1_REVIEW['q1-two-spots'],
      title: 'Two spots from a lopsided magnet',
      question: 'Why does a lopsided field push atoms at all, and why into exactly two spots?',
      lecture: {
        pages: 'notes p. 2, Fig. 1',
        summary:
          'Silver atoms cross a magnet whose field changes with height. The push follows the slope of the energy, and the plate shows two spots, so the moment takes two values.',
      },
      books: [
        { source: 'nc', where: '§1.5.1, pp. 43–44', adds: 'The hydrogen version of 1927: an atom with no orbital magnetism still makes two spots, which pins the two values on the electron’s spin.' },
        { source: 'mit805', where: 'Lecture 3; notes “Spin one-half, bras, kets, and operators”, §1', adds: 'Why only the up–down force survives, although the sideways field gradients are real.', url: URL.mit805(3) },
      ],
      visual: {
        kind: 'sg-lab',
        props: { source: 'oven', axes: ['z'], editable: false, predict: true, seed: 709 },
        tryThis: ['Predict first: a smear or two spots?', 'Fire 200 atoms and compare the two halves of the plate.'],
      },
      clues: [],
      insight: 'A lopsided field pushes each atom by an amount set by its up–down moment. The plate is a picture of that moment: two spots, two values.',
      insightFormal:
        'The deflection maps $\\mu_z$ linearly onto the plate, so the number of lines counts the eigenvalues of $\\mu_z$: the spin’s $z$ component is quantized, $S_z = \\pm\\hbar/2$.',
      pitfalls: ['Thinking a stronger magnet could make more spots. It only pushes the same two values further apart.'],
      play: [
        {
          id: 'q1-t-spots',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'How many spots?',
          prompt: 'An oven beam passes one $z$ magnet. How many spots form on the plate?',
          answer: V.q1Spots,
          tolerance: 0.1,
          unit: 'spots',
          hints: [{ text: 'Classically you would expect a smear.' }, { text: 'What did Stern and Gerlach see on their plate?' }, { text: '$\\mu_z$ takes only two values.' }],
          walkthrough: [{ text: `${d(V.q1Spots, 0)} spots, one for each value of $\\mu_z$.` }],
        },
        {
          id: 'q1-t-force',
          kind: 'numeric',
          tier: 'core',
          title: 'The push on one atom',
          prompt: `A silver atom with $\\mu_z = ${d(V.q1MuB)} \\times 10^{-24}$ J/T sits in a gradient of 1000 T/m. What is the force on it, in units of $10^{-21}$ N?`,
          answer: V.q1Force,
          tolerance: 0.005,
          unit: '× 10⁻²¹ N',
          hints: [{ text: 'A force is the downhill slope of energy.' }, { text: 'Here $F_z = \\mu_z G$.' }, { text: 'Multiply, then shift the power of ten.' }],
          walkthrough: [{ text: `$${d(V.q1MuB)} \\times 10^{-24} \\times 10^{3} = ${d(V.q1Force)} \\times 10^{-21}$ newtons.` }],
        },
        {
          id: 'q1-t-deflection',
          kind: 'numeric',
          tier: 'core',
          title: 'How far sideways?',
          prompt: 'The same atom crosses a magnet 35 mm long at 550 m/s. How far has it moved sideways at the magnet’s end, in mm?',
          answer: V.q1Defl,
          tolerance: 0.002,
          unit: 'mm',
          hints: [
            { text: `Find the acceleration $a = F_z/m$, with the silver atom’s mass $m = ${d(V.q1Mass, 3)} \\times 10^{-25}$ kg.` },
            { text: 'The time inside the magnet is $t = L/v$.' },
            { text: 'Then use $\\Delta z = \\tfrac12 a t^2$.' },
          ],
          walkthrough: [
            { text: `$a = ${d(V.q1Accel, 4)} \\times 10^{4}$ m/s² and $t = ${d(V.q1Flight, 2)}$ µs.` },
            { text: `$\\Delta z = \\tfrac12 a t^2 \\approx ${d(V.q1Defl, 4)}$ mm, about a tenth of a millimetre.` },
          ],
        },
        {
          id: 'q1-t-gradient',
          kind: 'choice',
          tier: 'core',
          title: 'A steeper field',
          prompt: 'Double the field gradient. What happens on the plate?',
          options: [
            { text: 'The spots move twice as far apart', correct: true, why: 'Right. The push $F_z = \\mu_z G$ doubles, so the deflection doubles; the atom still has two values.' },
            { text: 'Four spots appear', correct: false, why: 'The number of spots counts the values of $\\mu_z$, and the magnet does not change them.' },
            { text: 'The spots merge into a band', correct: false, why: 'A band needs a continuous range of $\\mu_z$; the atom still has two values.' },
            { text: 'Nothing changes', correct: false, why: 'The push is proportional to the gradient, so the spots move.' },
          ],
          hints: [{ text: 'Which quantity sets the push?' }, { text: 'The push is $F_z = \\mu_z G$.' }, { text: 'Does $G$ change the values $\\mu_z$ can take?' }],
          walkthrough: [{ text: `The deflection grows from ${d(V.q1Defl)} mm to ${d(V.q1DeflG2)} mm. The number of spots is set by the atom, not by the magnet.` }],
        },
        {
          id: 'q1-t-sign',
          kind: 'choice',
          tier: 'stretch',
          title: 'Which spot is spin up?',
          prompt: 'The field grows upward. Which spot do atoms with $S_z = +\\hbar/2$ reach?',
          options: [
            { text: 'The upper spot', correct: false, why: 'That would be true if the moment pointed along the spin. For an electron it points the other way.' },
            { text: 'The lower spot, because silver’s moment points opposite to its spin', correct: true, why: 'Right. $S_z > 0$ gives $\\mu_z < 0$, so the push points toward the weaker field, downward.' },
            { text: 'Both spots', correct: false, why: 'Every atom with $S_z = +\\hbar/2$ has the same $\\mu_z$, so they all go one way.' },
            { text: 'Neither spot', correct: false, why: 'The atoms do land: $\\mu_z$ is not zero.' },
          ],
          hints: [
            { text: 'The push depends on $\\mu_z$, not on $S_z$ directly.' },
            { text: 'For an electron, $\\mu_z$ has the opposite sign to $S_z$.' },
            { text: 'So $S_z > 0$ gives $\\mu_z < 0$.' },
          ],
          walkthrough: [
            { text: `$\\mu_z$ is close to $-\\mu_B$, so $F_z < 0$ and the atom lands ${d(V.q1SignDown)} mm below the middle: the lower spot.` },
            { text: 'Which spot a picture calls “+” is a labelling choice; the bench’s fidelity notes say which one it means.' },
          ],
        },
      ],
    },
    {
      id: 'q1-sequences',
      story: Q1_STORY['q1-sequences'],
      review: Q1_REVIEW['q1-sequences'],
      title: 'A second magnet can erase the first',
      question: 'What happens when atoms sorted along z meet a magnet turned 90°, then a z magnet again?',
      lecture: {
        pages: 'notes pp. 2–3',
        summary:
          'A kept beam is in a definite state. Repeating a measurement repeats its answer; a magnet turned 90° splits the beam and erases the earlier answer.',
      },
      books: [
        { source: 'nc', where: '§1.5.1, pp. 44–45', adds: 'The same cascade of magnets, with the classical expectation of one central spot and the two-label guess spelled out.' },
        { source: 'nc', where: 'Box 2.5, p. 91', adds: 'Why a repeated projective measurement gives the same answer, while a destructive one can be made only once.' },
      ],
      visual: {
        kind: 'sg-lab',
        props: { source: 'oven', axes: ['z', 'x', 'z'], keep: ['+', '+'], editable: true, maxDevices: 3, predict: true, seed: 709 },
        tryThis: ['Run z, x, z: what reaches the plate?', 'Make the middle magnet a $z$ magnet.', 'Keep the − beam at the $x$ magnet instead.'],
      },
      clues: [],
      insight: 'A measurement leaves the atom in its outcome’s state. A magnet along a new axis replaces the old answer instead of reading it.',
      insightFormal:
        'Each filter projects onto the eigenstate of its outcome; $S_z$ and $S_x$ do not commute, so there are no joint labels, and an SG$_x$ between two SG$_z$ restores the 50/50 split.',
      pitfalls: ['Thinking the atoms keep a memory of their first answer. After the $x$ magnet, the plate shows both $z$ spots.'],
      play: [
        {
          id: 'q1-s-repeat',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Ask again',
          prompt: '$|{+z}\\rangle$ atoms meet a second $z$ magnet. What fraction lands in the + spot?',
          answer: V.q1Repeat,
          tolerance: 0.001,
          unit: 'fraction',
          hints: [{ text: 'The atoms were just sorted along $z$.' }, { text: 'Measuring the same thing again repeats the answer.' }, { text: 'None of them can go down.' }],
          walkthrough: [{ text: 'All of them: a repeated measurement along the same axis gives the same answer every time.' }],
        },
        {
          id: 'q1-s-zxz',
          kind: 'numeric',
          tier: 'core',
          title: 'z, x, z from the furnace',
          prompt: 'Furnace → $z$ magnet (keep +) → $x$ magnet (keep +) → $z$ magnet. What fraction of the furnace’s atoms lands in the + spot?',
          answer: V.q1Zxz,
          tolerance: 0.001,
          unit: 'fraction',
          hints: [{ text: 'Each magnet along a new axis passes half of what reaches it.' }, { text: 'There are three halvings in a row.' }, { text: 'Multiply ½ × ½ × ½.' }],
          walkthrough: [{ text: `${uf(V.q1Zxz)}. The other spot also gets ${uf(V.q1Zxz)}, and ${uf(V.q1ZxzBlocked1)} and ${uf(V.q1ZxzBlocked2)} of the atoms are blocked on the way.` }],
        },
        {
          id: 'q1-s-middle-z',
          kind: 'choice',
          tier: 'core',
          title: 'A middle magnet along z',
          prompt: 'Replace the middle $x$ magnet by a $z$ magnet that keeps the + beam. What does the last magnet show?',
          options: [
            { text: 'Every atom in the + spot', correct: true, why: 'Right. No axis changes, so every magnet repeats the first answer.' },
            { text: 'Half in each spot', correct: false, why: 'That needs a magnet along a new axis in between.' },
            { text: 'Every atom in the − spot', correct: false, why: 'The kept atoms are all $|{+z}\\rangle$, and a $z$ magnet never sends them down.' },
            { text: 'No atom arrives', correct: false, why: 'The + beam passes both kept filters.' },
          ],
          hints: [{ text: 'Does any magnet change the axis?' }, { text: 'Repeated measurements along one axis agree.' }, { text: 'Compare with the second magnet of this unit.' }],
          walkthrough: [{ text: `Every plate atom lands in the + spot, and ${uf(V.q1Zzz)} of the furnace’s atoms reach the plate.` }],
        },
        {
          id: 'q1-s-four',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Four magnets',
          prompt: 'Furnace → $z$ (keep +) → $x$ (keep +) → $z$ (keep +) → $x$. What fraction of the furnace’s atoms lands in the + spot?',
          answer: V.q1Zxzx,
          tolerance: 0.001,
          unit: 'fraction',
          hints: [{ text: 'Count the changes of axis.' }, { text: 'Every magnet halves what reaches it.' }, { text: 'There are four halvings.' }],
          walkthrough: [{ text: `$\\left(\\tfrac12\\right)^4 = ${tf(V.q1Zxzx)}$. Each new axis erases the previous answer, so every magnet is a fresh coin toss.` }],
        },
        {
          id: 'q1-s-refute',
          kind: 'order',
          tier: 'stretch',
          title: 'Refute the hidden labels',
          prompt: 'Put the argument against hidden labels in order.',
          steps: [
            'Keep the + beam of a $z$ magnet.',
            'Keep the + beam of an $x$ magnet.',
            'If the $z$ label survived, a last $z$ magnet would send every atom to the + spot.',
            'The plate shows both spots, half each.',
            'So the $x$ magnet erased the $z$ label.',
          ],
          hints: [{ text: 'Start with the preparation.' }, { text: 'State the prediction before the result.' }, { text: 'The conclusion comes last.' }],
          walkthrough: [{ text: 'This is the notes’ argument on p. 3: prepare, predict from the hidden label, observe, conclude.' }],
        },
      ],
    },
    {
      id: 'q1-superposition',
      story: Q1_STORY['q1-superposition'],
      review: Q1_REVIEW['q1-superposition'],
      title: 'Adding states: the superposition principle',
      question: 'If an atom can be in |+z⟩ or |−z⟩, what does it mean to be in both?',
      lecture: {
        pages: 'notes p. 3; p. 7 (preview)',
        summary: 'States are kets in a [[qc-vector-space|vector space]] with an [[qc-inner-product|inner product]]. Any combination of two states, rescaled, is again a state.',
      },
      books: [
        { source: 'bergou', where: '§1.1, eq. (1.1), p. 1', adds: 'The qubit: any two-level system, in a complex combination of its two basis states.' },
        { source: 'nc', where: 'pp. 45, xxix', adds: 'The cascade explained with a qubit, and the same labels as this course: the up beam of a $z$ magnet is the qubit’s first basis state.' },
        { source: 'nc', where: 'Ex. 2.57, p. 86', adds: 'Two measurements in a row act as one combined measurement, so their probabilities multiply.' },
      ],
      visual: {
        kind: 'amplitude-bars',
        props: { state: '+x', basis: 'z', editable: true },
        tryThis: [
          'Read the two $z$ bars of $|{+x}\\rangle$.',
          'Switch the basis to $x$: the bars jump to all and nothing.',
          'Set the phase to 90° to reach $|{+y}\\rangle$: why are its $z$ bars and its $x$ bars both equal?',
        ],
      },
      clues: [],
      insight: 'Any mix of states is a state once rescaled. Its numbers may be complex, and each chance is a number’s size, squared.',
      insightFormal:
        'States are normalized vectors of a complex Hilbert space; the Born rule reads probabilities, and a definite relative phase separates a superposition from a mixture.',
      pitfalls: ['Reading a superposition as a beam that is half one state and half the other. An $x$ magnet tells the two apart.'],
      play: [
        {
          id: 'q1-p-half',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'An equal mix',
          prompt: 'What is $P(+z)$ for $(|{+z}\\rangle + |{-z}\\rangle)/\\sqrt2$?',
          answer: V.q1PX,
          tolerance: 0.005,
          unit: 'probability',
          hints: [{ text: 'Find the number in front of $|{+z}\\rangle$.' }, { text: 'It is $1/\\sqrt2$.' }, { text: 'Square its size.' }],
          walkthrough: [{ text: `$(1/\\sqrt2)^2 = ${tf(V.q1PX)}$.` }],
        },
        {
          id: 'q1-p-34i',
          kind: 'numeric',
          tier: 'core',
          title: 'A complex amplitude',
          prompt: '$|\\psi\\rangle = \\tfrac35|{+z}\\rangle + \\tfrac45 i|{-z}\\rangle$. What is $P(-z)$?',
          answer: V.q1P34i,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'The number in front of $|{-z}\\rangle$ is $\\tfrac45 i$.' },
            { text: 'Its size squared is the number times its complex conjugate.' },
            { text: 'Work out $(-\\tfrac45 i)(\\tfrac45 i)$.' },
          ],
          walkthrough: [
            { text: `$(-\\tfrac45 i)(\\tfrac45 i) = \\tfrac{16}{25} = ${d(V.q1P34i, 2)}$. With $P(+z) = \\tfrac{9}{25} = ${d(V.q1P34iUp, 2)}$, the two add to 1.` },
            { text: `Trap: $(\\tfrac45 i)^2 = -${d(V.q1Sq34i, 2)}$ is not a probability; the size squared uses the conjugate.` },
          ],
        },
        {
          id: 'q1-p-normalize',
          kind: 'numeric',
          tier: 'core',
          title: 'Rescale first',
          prompt: 'Rescale $|{+z}\\rangle + 2|{-z}\\rangle$ to length 1. What is $P(+z)$?',
          answer: V.q1PNorm,
          tolerance: 0.005,
          unit: 'probability',
          hints: [{ text: 'The length is $\\sqrt{1 + 4}$.' }, { text: 'Divide both numbers by $\\sqrt5$.' }, { text: 'Square the first one.' }],
          walkthrough: [{ text: `$(1/\\sqrt5)^2 = ${tf(V.q1PNorm)} = ${d(V.q1PNorm, 1)}$.` }],
        },
        {
          id: 'q1-p-mixture',
          kind: 'choice',
          tier: 'core',
          title: 'Superposition or mixture?',
          prompt: 'A beam of $|{+x}\\rangle$ atoms and a 50/50 mixture of $|{+z}\\rangle$ and $|{-z}\\rangle$ atoms both meet an $x$ magnet. What happens?',
          options: [
            { text: 'Both split 50/50', correct: false, why: 'Along $z$ they look the same, but not along $x$.' },
            { text: 'The $|{+x}\\rangle$ beam goes all up; the mixture splits 50/50', correct: true, why: 'Right. An $x$ magnet reads $|{+x}\\rangle$ as up every time, while each atom of the mixture is a $z$ state.' },
            { text: 'Both go all up', correct: false, why: 'Each atom of the mixture is $|{+z}\\rangle$ or $|{-z}\\rangle$, and each of those splits 50/50 along $x$.' },
            { text: 'The mixture goes all up', correct: false, why: 'The mixture has no definite phase between its parts, so nothing favours $+x$.' },
          ],
          hints: [{ text: 'Along $z$ the two beams look the same.' }, { text: 'What does an $x$ magnet do to $|{+x}\\rangle$?' }, { text: 'Each atom of the mixture is a $z$ state.' }],
          walkthrough: [{ text: `The superposition gives $P(+x) = ${d(V.q1SupX, 0)}$, the mixture ${d(V.q1MixX, 1)}. The superposition has a definite [[relative-phase|relative phase]]; the mixture has none.` }],
        },
        {
          id: 'q1-p-difference',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A difference of states',
          prompt: 'Rescale $|{+z}\\rangle - |{+x}\\rangle$ to length 1. What is $P(+z)$?',
          answer: V.q1PDiff,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Write both states as columns.' },
            { text: `The difference is $(1 - ${d(V.q1AmpX)}, -${d(V.q1AmpX)})$.` },
            { text: `Its squared length is ${d(V.q1DiffLen2)}.` },
          ],
          walkthrough: [{ text: `$${d(V.q1DiffTop2, 4)}/${d(V.q1DiffLen2, 4)} = ${d(V.q1PDiff, 3)}$, which is $\\sin^2 22.5^\\circ$.` }],
        },
        {
          id: 'q1-p-not-unit',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Squares that add to 1',
          prompt: 'In $(|{+z}\\rangle + |{+x}\\rangle)/\\sqrt2$ the two coefficients have squared sizes ½ and ½, adding to 1. What is the vector’s length?',
          answer: V.q1PNotUnit,
          tolerance: 0.005,
          unit: 'length',
          hints: [
            { text: 'Squared sizes add up to the squared length only for perpendicular arrows.' },
            { text: 'These two arrows are 45° apart.' },
            { text: 'Add the columns, then use Pythagoras.' },
          ],
          walkthrough: [
            { text: `The vector is $(${d(V.q1PNotUnitTop)}, ${d(V.q1PNotUnitBottom, 1)})$, with squared length ${d(V.q1PNotUnitLen2)}. Its length is ${d(V.q1PNotUnit, 4)}, not 1.` },
            { text: `The extra ${d(V.q1AmpX)} is a cross term between the two states. It vanishes only for [[orthogonal|orthogonal]] states, so squares adding to 1 are not enough.` },
          ],
        },
      ],
    },
    {
      id: 'q1-vector-space',
      story: Q1_STORY['q1-vector-space'],
      review: Q1_REVIEW['q1-vector-space'],
      title: 'The rules for adding and scaling kets',
      question: 'Which rules must kets obey so that adding and scaling always make sense?',
      lecture: {
        pages: 'notes pp. 3–4, Fig. 2',
        summary: 'The notes list the rules for adding and scaling vectors, with lists of numbers and polynomials as examples.',
      },
      books: [
        { source: 'axler', where: '§1B, 1.19–1.20, p. 12; 1.26–1.27, p. 14; 2.12, p. 31', adds: 'The full list of rules, including scaling by 1; why the zero vector and the opposites are unique; and the polynomials of degree at most a given number.' },
        { source: 'nc', where: '§2.1, pp. 61–62', adds: 'The same rules in physics notation, and the same reason to write the zero vector without a ket.' },
      ],
      visual: {
        kind: 'phase-dial',
        props: { theta: 0, rotations: false },
        tryThis: ['Multiply both amplitudes by the same number of size 1: the point stays.', 'Change one amplitude only: the point moves.'],
      },
      clues: [],
      insight: 'Kets obey a short list of rules for adding and scaling. The states are the length-1 members of that space.',
      insightFormal:
        'The kets form a complex vector space satisfying Axler’s axioms, including $1|\\alpha\\rangle = |\\alpha\\rangle$; the states are its unit vectors, which do not form a subspace.',
      pitfalls: ['Writing the zero vector as $|0\\rangle$. In this course $|0\\rangle$ is the qubit state $|{+z}\\rangle$, of length 1.'],
      play: [
        {
          id: 'q1-v-zero',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which one is zero?',
          prompt: 'In $V^2(\\text{ℂ})$, which of these is the zero vector?',
          options: [
            { text: '$|0\\rangle$, the qubit state', correct: false, why: 'In this course $|0\\rangle$ is $|{+z}\\rangle$, of length 1.' },
            { text: 'The column $(0, 0)$', correct: true, why: 'Right. Adding it changes nothing, and its length is 0.' },
            { text: '$(1, 1)$', correct: false, why: 'Adding it changes every vector.' },
            { text: '$(0, 1)$', correct: false, why: 'That is $|{-z}\\rangle$, a state of length 1.' },
          ],
          hints: [{ text: 'The zero vector changes nothing when added.' }, { text: 'Its length is 0.' }, { text: 'A state has length 1.' }],
          walkthrough: [{ text: 'The column $(0, 0)$. The notes write it $|0\\rangle$, which in this course means $|{+z}\\rangle$ instead.' }],
        },
        {
          id: 'q1-v-poly',
          kind: 'numeric',
          tier: 'core',
          title: 'Polynomials as vectors',
          prompt: 'In $(1 + 2x) + 3(x - x^2)$, what is the coefficient of $x$?',
          answer: V.q1VPoly,
          tolerance: 0.001,
          hints: [{ text: 'Scale first, then add.' }, { text: '$3(x - x^2) = 3x - 3x^2$.' }, { text: 'Add the $x$ terms.' }],
          walkthrough: [{ text: `$2 + 3 = ${d(V.q1VPoly, 0)}$, so the sum is $1 + ${d(V.q1VPoly, 0)}x - 3x^2$.` }],
        },
        {
          id: 'q1-v-degree',
          kind: 'choice',
          tier: 'core',
          title: 'Degree exactly 2',
          prompt: 'Why are the polynomials of degree exactly 2 not a vector space?',
          options: [
            { text: '$x^2 + x$ plus $-x^2 + 1$ gives $x + 1$, of degree 1', correct: true, why: 'Right. A sum can leave the set, so it is not closed; the zero polynomial is missing too.' },
            { text: 'They cannot be scaled', correct: false, why: 'Scaling by a nonzero number keeps the degree.' },
            { text: 'They have no opposites', correct: false, why: 'The opposite of $x^2 + 1$ is $-x^2 - 1$, still of degree 2.' },
            { text: 'Their sums have degree 4', correct: false, why: 'Adding never raises the degree; multiplying would.' },
          ],
          hints: [{ text: 'Test closure under addition.' }, { text: 'Can a sum lose its $x^2$ term?' }, { text: 'Try two leading terms that cancel.' }],
          walkthrough: [{ text: `The coefficients add to $(1, 1, ${d(V.q1Degree, 0)})$: the $x^2$ term cancels. The zero polynomial is missing as well.` }],
        },
        {
          id: 'q1-v-real-scalars',
          kind: 'choice',
          tier: 'core',
          title: 'Real pairs, complex numbers',
          prompt: 'Take pairs of real numbers, and allow complex scalars. Is that a vector space?',
          options: [
            { text: 'Yes', correct: false, why: 'Scaling must stay inside the set for every allowed scalar.' },
            { text: 'No: $i \\cdot (1, 0) = (i, 0)$ is not a pair of real numbers', correct: true, why: 'Right. One complex scaling already leaves the set.' },
            { text: 'No: sums can be complex', correct: false, why: 'A sum of real pairs is a real pair.' },
            { text: 'Yes, if the pairs have length 1', correct: false, why: 'Length is not one of the rules, and unit pairs are not closed under addition anyway.' },
          ],
          hints: [{ text: 'Closure must hold for every allowed scalar.' }, { text: 'Try the scalar $i$.' }, { text: 'Is the result still a pair of real numbers?' }],
          walkthrough: [{ text: 'The scalars are part of the definition: $V(\\text{ℝ})$ and $V(\\text{ℂ})$ are different spaces, even for the same objects.' }],
        },
        {
          id: 'q1-v-lazy',
          kind: 'choice',
          tier: 'stretch',
          title: 'A lazy scaling',
          prompt: 'Define scaling as $c|\\alpha\\rangle = 0$ for every number $c$. Which rule fails?',
          options: [
            { text: '$(c_1 + c_2)(|\\alpha\\rangle + |\\beta\\rangle) = c_1|\\alpha\\rangle + c_1|\\beta\\rangle + c_2|\\alpha\\rangle + c_2|\\beta\\rangle$', correct: false, why: 'Both sides are 0, so it holds.' },
            { text: '$a(b|\\gamma\\rangle) = (ab)|\\gamma\\rangle$', correct: false, why: 'Both sides are 0, so it holds.' },
            { text: '$1|\\alpha\\rangle = |\\alpha\\rangle$', correct: true, why: 'Right. Scaling by 1 gives 0, not the vector itself.' },
            { text: 'None; it is a vector space', correct: false, why: 'Scaling by 1 must give the vector back.' },
          ],
          hints: [{ text: 'Both sides of the distributive rule are 0.' }, { text: 'So is each side of the grouping rule for scaling.' }, { text: 'What should scaling by 1 do?' }],
          walkthrough: [{ text: '$1|\\alpha\\rangle = 0$, which differs from $|\\alpha\\rangle$ for any nonzero vector. This is why Axler lists scaling by 1 as a rule.' }],
        },
      ],
    },
    {
      id: 'q1-inner-product',
      story: Q1_STORY['q1-inner-product'],
      review: Q1_REVIEW['q1-inner-product'],
      title: 'Lengths and angles for complex vectors',
      question: 'How do we measure a ket’s length, and the overlap of two kets, when the numbers are complex?',
      lecture: {
        pages: 'notes pp. 4–5, Fig. 3',
        summary: 'Each ket has a bra. The inner product obeys four rules, conjugates the bra, and gives lengths; a weighted version needs a positive Hermitian table.',
      },
      books: [
        { source: 'axler', where: '§6A, 6.2, p. 183; 6.3, p. 184', adds: 'The mathematician’s inner product, linear in the first slot, and weighted examples.' },
        { source: 'nc', where: 'Fig. 2.1, p. 62; §2.1.4, pp. 65–67', adds: 'A table of Dirac notation, and the physicists’ convention for the inner product.' },
        { source: 'nc', where: 'Ex. 2.6, p. 66', adds: 'N&C ⚑: the bra side is conjugate-linear, the derivation of Unit 1.5 in this chapter. No course sheet assigns it.' },
      ],
      visual: {
        kind: 'projector',
        props: { state: 45, basis: 0, editableBasis: true },
        tryThis: ['State at 45°, basis at 0°: read the two shadows.', 'Turn the basis until one shadow vanishes.', 'Why do the squared shadows add to 1?'],
      },
      clues: [],
      insight: 'An inner product measures overlap and length. For complex vectors the bra is conjugated, or lengths could come out negative.',
      insightFormal:
        'The inner product is positive definite, conjugate-symmetric and linear in the ket, hence conjugate-linear in the bra; $\\beta^\\dagger M\\alpha$ qualifies exactly for Hermitian $M$ with positive eigenvalues.',
      pitfalls: ['Forgetting to conjugate the bra. Then $(3, 4i)$ would have a negative “length squared”.'],
      play: [
        {
          id: 'q1-i-dot',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A real inner product',
          prompt: '$\\beta = (1, 2)$ and $\\alpha = (3, -1)$. What is $\\langle\\beta|\\alpha\\rangle$?',
          answer: V.q1Dot,
          tolerance: 0.001,
          hints: [{ text: 'Multiply matching entries.' }, { text: 'Real entries need no conjugating.' }, { text: 'Add $1 \\cdot 3$ and $2 \\cdot (-1)$.' }],
          walkthrough: [{ text: `$1 \\cdot 3 + 2 \\cdot (-1) = ${d(V.q1Dot, 0)}$.` }],
        },
        {
          id: 'q1-i-norm',
          kind: 'numeric',
          tier: 'core',
          title: 'The length of (3, 4i)',
          prompt: 'What is the length of $(3, 4i)$?',
          answer: V.q1Len34i,
          tolerance: 0.005,
          unit: 'length',
          hints: [{ text: 'Conjugate the bra’s entries.' }, { text: 'Work out $3 \\cdot 3 + (-4i)(4i)$.' }, { text: 'That is $9 + 16$.' }],
          walkthrough: [{ text: `$\\sqrt{${d(V.q1Norm34i, 0)}} = ${d(V.q1Len34i, 0)}$. Without the conjugate you would get $9 - 16 = ${d(V.q1Bilinear34i, 0)}$.` }],
        },
        {
          id: 'q1-i-orth',
          kind: 'numeric',
          tier: 'core',
          title: 'A hidden right angle',
          prompt: '$\\beta = (1, i)$ and $\\alpha = (i, 1)$. What is $|\\langle\\beta|\\alpha\\rangle|$?',
          answer: V.q1Orth,
          tolerance: 0.001,
          hints: [{ text: 'The bra is $(1, -i)$.' }, { text: 'Work out $1 \\cdot i + (-i) \\cdot 1$.' }, { text: 'Simplify.' }],
          walkthrough: [{ text: `$i - i = ${d(V.q1Orth, 0)}$: the two vectors are orthogonal. The first is $\\sqrt2|{+y}\\rangle$; the second is a multiple of the state along $-y$.` }],
        },
        {
          id: 'q1-i-conj-lin',
          kind: 'numeric',
          tier: 'core',
          title: 'A number on the bra side',
          prompt: '$c = 2 + i$, $\\beta = (1, 0)$ and $\\alpha = (0.6, 0.8)$. What is the imaginary part of $\\langle c\\beta|\\alpha\\rangle$?',
          answer: V.q1ConjLinCh,
          tolerance: 0.005,
          hints: [
            { text: 'A number on the bra side comes out conjugated.' },
            { text: 'So $\\langle c\\beta|\\alpha\\rangle = c^*\\langle\\beta|\\alpha\\rangle$.' },
            { text: 'Here $\\langle\\beta|\\alpha\\rangle = 0.6$.' },
          ],
          walkthrough: [{ text: `$(2 - i)(0.6) = ${d(V.q1ConjLinChRe, 1)} - ${d(-V.q1ConjLinCh, 1)}i$, so the imaginary part is $-${d(-V.q1ConjLinCh, 1)}$.` }],
        },
        {
          id: 'q1-i-weighted',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A weighted length',
          prompt: '$M = \\begin{pmatrix}2 & i\\\\ -i & 2\\end{pmatrix}$ and $\\alpha = (1, -i)$. What is $\\langle\\alpha|\\alpha\\rangle_M$?',
          answer: V.q1MNorm1mi,
          tolerance: 0.005,
          hints: [{ text: 'First compute $M\\alpha$.' }, { text: '$M\\alpha = (3, -3i)$.' }, { text: 'Then take the bra $(1, i)$ times it.' }],
          walkthrough: [
            { text: `$1 \\cdot 3 + i \\cdot (-3i) = ${d(V.q1MNorm1mi, 0)}$.` },
            { text: `This $\\alpha$ is an eigenvector of $M$ with eigenvalue ${d(V.q1MEigHigh, 0)}, and its plain length squared is 2, so the weight triples it.` },
          ],
        },
      ],
    },
  ],
}
