import type { Lecture } from '../schema'
import { Q10_REVIEW } from './Q10.review'
import { Q10_STORY } from './Q10.story'
import { BOB_NO_MEAS, BOX_XX, COND_X, LHV, PHI_PT_EIGS, PHI_ZZ, PROD_S, V, X_WARMUP, d } from './Q10.values'

// Physics 709, chapter Q10: "Entanglement, no signalling and Bell's inequality" (Bergou §3.1-3.3, pp. 31-37; N&C
// §2.6, pp. 111-117), in both tracks. Every number a learner sees is computed in Q10.values.ts, then asserted in
// keyed claims (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy,
// pipeline/claims_qc709/q10.py). Plan: docs/roles/proposals/P-Q10-story.md; rulings
// docs/roles/decisions/qc709-Q10Q13.md, qc709-remap.md. Q10 owns separable mixtures, no-signalling, local
// hidden-variable statistics, the correlator as used here, the CHSH value S, the Tsirelson bound and the PR box.
// No sheet assigns anything in Q10 (Bergou's ⚑ P3.1/P3.2 are cited asides only, per ruling 12); every challenge
// below carries a full walkthrough.

export const Q10: Lecture = {
  id: 'Q10',
  number: 10,
  title: 'Entanglement, no signalling and Bell’s inequality',
  outcomes: [
    'Say what a separable state is and why its correlations are only classical.',
    "Show that one half of an entangled pair cannot carry a message: the partner's state is the same whatever Alice does.",
    'Write an instruction set, and show that the CHSH score of any instruction set is at most 2.',
    'Define the correlator and the CHSH value S, and state the Bell inequality $|S| \\le 2$ for any classical story.',
    'Compute $S = 2\\sqrt2$ for an entangled pair, show a product state never beats 2, and state the Tsirelson bound.',
  ],
  prerequisites: [
    'qc-density-matrix',
    'qc-mixed-states',
    'qc-ensemble',
    'qc-maximally-mixed',
    'qc-local-realism',
    'qc-hidden-values',
    'qc-mermin-argument',
    'qc-bell-basis',
    'qc-correlation-grid',
    'qc-product-state',
    'qc-entangled',
    'qc-factoring-test',
    'qc-pauli-matrices',
    'qc-commutator',
    'qc-expectation',
  ],
  symbols: {
    // q10-separable
    '\\rho': 'q10-separable:b1',
    '|00\\rangle': 'q10-separable:b1',
    '|11\\rangle': 'q10-separable:b1',
    '\\rho_A^k': 'q10-separable:b1',
    '\\rho_B^k': 'q10-separable:b1',
    'p_k': 'q10-separable:b1',
    '\\Phi^+': 'q10-separable:b2',
    'X_1': 'q10-separable:b2',
    'X_2': 'q10-separable:b2',
    '\\langle\\cdot\\rangle': 'q10-separable:b2',
    'Z_1': 'q10-separable:b2',
    'Z_2': 'q10-separable:b2',
    '\\rho^{T_B}': 'q10-separable:b3',
    'Y_1': 'q10-no-signal:b3',
    'Y_2': 'q10-no-signal:b3',
    // q10-no-signal
    '\\mathrm{Tr}_A': 'q10-no-signal:b2',
    '\\rho_B': 'q10-no-signal:b2',
    'I': 'q10-no-signal:b2',
    // q10-hidden
    'a_1': 'q10-hidden:b1',
    'a_2': 'q10-hidden:b1',
    'b_1': 'q10-hidden:b1',
    'b_2': 'q10-hidden:b1',
    'P(a_1, a_2, b_1, b_2)': 'q10-hidden:b1',
    'X': 'q10-hidden:b2',
    // q10-chsh
    '\\langle ab\\rangle': 'q10-chsh:b1',
    'S': 'q10-chsh:b2',
    // q10-violation
    '\\chi': 'q10-violation:b1',
    '\\delta': 'q10-violation:b2',
    'C': 'q10-violation:b4',
    '[A, B]': 'q10-violation:b4',
    '\\Psi^-': 'q10-violation:b5',
  },
  units: [
    {
      id: 'q10-separable',
      story: Q10_STORY['q10-separable'],
      review: Q10_REVIEW['q10-separable'],
      title: 'Mixtures of products: separable states',
      question: "When is a mixed pair's correlation only classical?",
      lecture: { pages: 'Bergou §3.1 pp. 31–32, Eqs. 3.1–3.4', summary: 'A separable state is a chance-weighted sum of products; the partial transpose tells it from an entangled one.' },
      books: [{ source: 'bergou', where: '§3.1 pp. 31–32, Eqs. 3.1–3.4', adds: 'separable mixtures, the example Eq. 3.3 and the standard Bell states.' }],
      visual: { kind: 'bloch', props: { theta: 90, phi: 0, editable: true, landmarks: true }, tryThis: ['Drag the point to the surface: every product member is pure.', 'The mixture of two sits inside.'] },
      clues: [],
      insight: 'A separable state is a coin mixture of products: its correlations are classical, however they are read.',
      insightFormal: 'Separable $\\Rightarrow$ PPT; for two qubits the partial transpose is also sufficient, so a negative eigenvalue certifies entanglement.',
      pitfalls: ['Reading the same $z$ correlation as the same state: the box and $\\Phi^+$ agree in $z$ but differ in $x$ and $y$.'],
      play: [
        {
          id: 'q10-s-xx',
          kind: 'numeric',
          tier: 'warm-up',
          title: "The box's x average",
          prompt: 'What is $\\langle X_1X_2\\rangle$ for the coin box $\\tfrac12(|00\\rangle\\langle00| + |11\\rangle\\langle11|)$?',
          answer: BOX_XX,
          tolerance: 0.005,
          hints: [{ text: 'Average over the two members.' }, { text: 'Each member is a product with $\\langle X\\rangle = 0$.' }, { text: '$\\tfrac12\\cdot0 + \\tfrac12\\cdot0$.' }],
          walkthrough: [{ text: 'Both $|00\\rangle$ and $|11\\rangle$ give $\\langle X_1X_2\\rangle = 0$, so the box does too.' }],
        },
        {
          id: 'q10-s-neg',
          kind: 'numeric',
          tier: 'core',
          title: 'A negative eigenvalue',
          prompt: "The partial transpose of $\\Phi^+$ has four eigenvalues. What is the smallest?",
          answer: PHI_PT_EIGS[0],
          tolerance: 0.005,
          hints: [{ text: "Transpose Bob's index." }, { text: 'A corner of the matrix moves in.' }, { text: 'Eigenvalues $(\\tfrac12, \\tfrac12, \\tfrac12, -\\tfrac12)$.' }],
          walkthrough: [{ text: '$-0.5$: $\\rho_{\\Phi^+}^{T_B}$ has a negative eigenvalue, so $\\Phi^+$ is entangled; the box’s are all $\\ge 0$.' }],
        },
        {
          id: 'q10-s-which',
          kind: 'choice',
          tier: 'core',
          title: 'Which is entangled?',
          prompt: 'Which of these is entangled?',
          options: [
            { text: '$\\Phi^+$', correct: true, why: 'Right: its partial transpose has a negative eigenvalue.' },
            { text: '$\\tfrac12(|00\\rangle\\langle00| + |11\\rangle\\langle11|)$', correct: false, why: 'The coin box is a mixture of products: separable.' },
            { text: '$\\tfrac13|00\\rangle\\langle00| + \\tfrac23|11\\rangle\\langle11|$', correct: false, why: 'Also a mixture of products: separable.' },
            { text: '$|0\\rangle\\langle0|\\otimes\\tfrac12I$', correct: false, why: 'A product of a pure state and a mixed one: separable.' },
          ],
          hints: [{ text: 'Try the partial transpose.' }, { text: 'A mixture of products is separable.' }, { text: 'Only $\\Phi^+$ has a negative eigenvalue.' }],
          walkthrough: [{ text: 'The three mixtures are separable (PPT); only $\\Phi^+$ fails the Peres test.' }],
        },
      ],
    },
    {
      id: 'q10-no-signal',
      story: Q10_STORY['q10-no-signal'],
      review: Q10_REVIEW['q10-no-signal'],
      title: "No signalling: the partner learns nothing",
      question: "Can Alice's choice of measurement change what Bob sees?",
      lecture: { pages: 'Bergou §3.2 pp. 32–33, Eqs. 3.5–3.7; N&C §2.4.3 pp. 105–107', summary: "Bob's reduced state is $\\tfrac12I$ whether or not Alice measures: entanglement sends no message." },
      books: [{ source: 'bergou', where: '§3.2 pp. 32–33, Eqs. 3.5–3.7', adds: "a phase-gate-and-Hadamard scheme that still fails to signal." }],
      visual: { kind: 'bloch', props: { theta: 60, phi: 45, editable: true, measure: 'z' }, tryThis: ['Measure z at θ = 60°: 0 and 1 come up, but the long-run split is fixed by the arrow, not by you.'] },
      clues: [],
      insight: "Averaged over Alice's outcomes, Bob's state is $\\tfrac12I$, the same as with no measurement: no signal.",
      insightFormal: '$\\rho_B = \\mathrm{Tr}_A\\rho = \\tfrac12I$ for any basis Alice chooses; a local operation cannot change the partner’s reduced state.',
      pitfalls: ['Treating the collapse as a message: the jump is real but invisible until a classical call arrives.'],
      play: [
        {
          id: 'q10-n-rb',
          kind: 'numeric',
          tier: 'warm-up',
          title: "Bob's z average",
          prompt: 'Alice and Bob share $\\Phi^+$. What is $\\langle Z\\rangle$ for Bob\'s qubit, with no message from Alice?',
          answer: BOB_NO_MEAS[2],
          tolerance: 0.005,
          hints: [{ text: "Bob's state is $\\mathrm{Tr}_A\\rho$." }, { text: 'For $\\Phi^+$ it is $\\tfrac12I$.' }, { text: 'The centre has $\\langle Z\\rangle = 0$.' }],
          walkthrough: [{ text: '$\\rho_B = \\tfrac12I$, so every $\\langle\\sigma\\rangle = 0$.' }],
        },
        {
          id: 'q10-n-after',
          kind: 'numeric',
          tier: 'core',
          title: 'Averaged after a reading',
          prompt: 'Alice measures $x$ and tells no one. Averaged over her outcomes, what is Bob\'s $\\langle X\\rangle$?',
          answer: COND_X.avg[0],
          tolerance: 0.005,
          hints: [{ text: 'Average the two conditioned states.' }, { text: '$+x$ and $-x$ with equal weight.' }, { text: 'They cancel.' }],
          walkthrough: [{ text: '$\\tfrac12(+\\hat x) + \\tfrac12(-\\hat x) = 0$: Bob stays at the centre, so no signal.' }],
        },
        {
          id: 'q10-n-signal',
          kind: 'choice',
          tier: 'core',
          title: 'A faster-than-light bit?',
          prompt: 'Can Alice send Bob a bit faster than light by choosing her measurement axis?',
          options: [
            { text: "No — Bob's reduced state is $\\tfrac12I$ for every choice", correct: true, why: "Right: no local choice of Alice's changes $\\rho_B$." },
            { text: 'Yes, by measuring $x$ instead of $z$', correct: false, why: 'Both give $\\rho_B = \\tfrac12I$: no difference reaches Bob.' },
            { text: 'Yes, if they share $\\Phi^+$', correct: false, why: 'Sharing $\\Phi^+$ is exactly the no-signalling case.' },
            { text: 'Only with a third qubit', correct: false, why: 'No number of extra qubits lets a local choice signal.' },
          ],
          hints: [{ text: 'What can Bob measure?' }, { text: 'His statistics come from $\\rho_B$.' }, { text: '$\\rho_B = \\tfrac12I$ always.' }],
          walkthrough: [{ text: "No local choice of Alice's changes $\\rho_B$, so Bob's statistics never depend on it." }],
        },
      ],
    },
    {
      id: 'q10-hidden',
      story: Q10_STORY['q10-hidden'],
      review: Q10_REVIEW['q10-hidden'],
      title: "Instruction sets: a classical story",
      question: 'Could each particle carry answers fixed in advance?',
      lecture: { pages: 'Bergou §3.3 pp. 33–34, Eqs. 3.8–3.9; N&C §2.6 pp. 115–116', summary: 'A local hidden-variable model assigns each particle fixed $\\pm1$ answers; the combination $X$ is always $\\pm2$.' },
      books: [{ source: 'bergou', where: '§3.3 pp. 33–34, Eqs. 3.8–3.9', adds: 'the instruction-set picture and the $X = \\pm2$ identity.' }],
      visual: { kind: 'sg-lab', props: { source: 'oven', axes: ['x', 'z'], editable: true, predict: true, seed: 710 }, tryThis: ['Fire 100 along $x$, then $z$: each axis has fixed statistics, like a card’s answers.'] },
      clues: [],
      insight: 'A card fixes four $\\pm1$ answers in advance; the combination $X = a_1(b_1+b_2) + a_2(b_1-b_2)$ is always $\\pm2$.',
      insightFormal: "Every one of the 16 cards gives $|X| = 2$; unlike Mermin's single-run argument, the CHSH clash is statistical.",
      pitfalls: ['Thinking one run refutes a card: every single run is possible; only the averaged score betrays it.'],
      play: [
        {
          id: 'q10-h-x',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'One card’s score',
          prompt: 'A card reads $a_1 = 1, a_2 = 1, b_1 = 1, b_2 = -1$. What is $X = a_1(b_1 + b_2) + a_2(b_1 - b_2)$?',
          answer: X_WARMUP,
          tolerance: 0.005,
          hints: [{ text: '$b_1 + b_2 = 0$.' }, { text: '$b_1 - b_2 = 2$.' }, { text: '$a_2\\cdot2$.' }],
          walkthrough: [{ text: '$1\\cdot0 + 1\\cdot2 = 2$.' }],
        },
        {
          id: 'q10-h-max',
          kind: 'numeric',
          tier: 'core',
          title: 'The largest |X|',
          prompt: 'Over all 16 cards, what is the largest value of $|X|$?',
          answer: LHV.maxS,
          tolerance: 0.005,
          hints: [{ text: 'One bracket is always 0.' }, { text: 'The other is $\\pm2$.' }, { text: 'So $|X|$ is fixed.' }],
          walkthrough: [{ text: 'Every card gives $|X| = 2$; the maximum is 2.' }],
        },
      ],
    },
    {
      id: 'q10-chsh',
      story: Q10_STORY['q10-chsh'],
      review: Q10_REVIEW['q10-chsh'],
      title: "The CHSH inequality: a classical ceiling",
      question: 'How high can a classical correlation score climb?',
      lecture: { pages: 'Bergou §3.3 p. 34, Eq. 3.10; N&C §2.6 pp. 113–114', summary: 'The CHSH value $S$ averages four correlators; a classical story caps it at 2, the Bell inequality.' },
      books: [{ source: 'nc', where: '§2.6 pp. 113–114', adds: 'the CHSH derivation with $Q, R, S, T$ settings.' }],
      visual: { kind: 'phase-dial', props: { theta: 90, rotations: true }, tryThis: ['Turn the dial a full lap: a relative phase, the knob the CHSH experiment turns.'] },
      clues: [],
      insight: 'The CHSH value $S$ adds four correlators in a set pattern; no classical story can push it past 2.',
      insightFormal: '$|S| = |\\sum P(\\cdots)X| \\le 2$ for every local hidden-variable model: the CHSH Bell inequality.',
      pitfalls: ["Confusing the CHSH value $S$ with Chapter Q9's entropy $S(\\rho)$: different quantity, same letter."],
      play: [
        {
          id: 'q10-c-ceil',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The classical ceiling',
          prompt: 'What is the largest CHSH value $S$ any instruction-set model can reach?',
          answer: LHV.maxS,
          tolerance: 0.005,
          hints: [{ text: '$S$ averages $X = \\pm2$.' }, { text: 'A weighted average of $\\pm2$.' }, { text: 'Cannot leave $[-2, 2]$.' }],
          walkthrough: [{ text: '$|S| = |\\sum P\\,X| \\le 2$, the CHSH inequality.' }],
        },
        {
          id: 'q10-c-corr',
          kind: 'numeric',
          tier: 'core',
          title: 'Always agreeing',
          prompt: 'Two readings always agree. What is their correlator $\\langle ab\\rangle$?',
          answer: PHI_ZZ,
          tolerance: 0.005,
          hints: [{ text: '$\\langle ab\\rangle = \\sum ab\\,P$.' }, { text: 'Always agree means $ab = +1$.' }, { text: 'Average of $+1$.' }],
          walkthrough: [{ text: 'If $a = b$ every run, $\\langle ab\\rangle = +1$; always disagree gives $-1$.' }],
        },
      ],
    },
    {
      id: 'q10-violation',
      story: Q10_STORY['q10-violation'],
      review: Q10_REVIEW['q10-violation'],
      title: 'Breaking the ceiling: $2\\sqrt2$',
      question: 'By how much can an entangled pair beat the classical score?',
      lecture: { pages: 'Bergou §3.3 pp. 34–36, Eqs. 3.11–3.19; N&C §2.6 pp. 116–117', summary: 'An entangled pair scores $2\\sqrt2$; a product state never beats 2; quantum mechanics itself stops at $2\\sqrt2$.' },
      books: [{ source: 'bergou', where: '§3.3 pp. 34–36, Eqs. 3.11–3.19', adds: 'the violating state $\\chi$, the product-state bound and the Tsirelson identity.' }],
      visual: { kind: 'phase-dial', props: { theta: 90, rotations: true }, tryThis: ['Set the dial to 45°: the phase that gives $\\chi$ its maximal violation.'] },
      clues: [],
      insight: `An entangled pair scores ${d(V.q10ChiS, 3)}, above the classical 2; quantum mechanics itself stops at that value.`,
      insightFormal: `$S_\\chi = ${d(V.q10ChiS, 3)}$; product (and separable) states obey $S \\le 2$; the Tsirelson bound $\\|C\\| \\le ${d(V.q10Tsirelson, 3)}$ caps every quantum state.`,
      pitfalls: ['Thinking quantum mechanics can reach $S = 4$: only the unphysical PR box does.'],
      play: [
        {
          id: 'q10-v-s',
          kind: 'numeric',
          tier: 'core',
          title: 'The violating score',
          prompt: 'For $|\\chi\\rangle = (|00\\rangle + e^{i45°}|11\\rangle)/\\sqrt2$ with $x, y$ settings, what is the CHSH value $S$?',
          answer: V.q10ChiS,
          tolerance: 0.01,
          hints: [{ text: 'Three correlators $+\\tfrac{\\sqrt2}2$, one $-\\tfrac{\\sqrt2}2$.' }, { text: '$S = 3\\cdot\\tfrac{\\sqrt2}2 + \\tfrac{\\sqrt2}2$.' }, { text: '$2\\sqrt2$.' }],
          walkthrough: [{ text: `$\\langle XX\\rangle = \\langle XY\\rangle = \\langle YX\\rangle = \\tfrac{\\sqrt2}2$, $\\langle YY\\rangle = -\\tfrac{\\sqrt2}2$, so $S = 2\\sqrt2 = ${d(V.q10ChiS, 3)}$.` }],
        },
        {
          id: 'q10-v-prod',
          kind: 'numeric',
          tier: 'core',
          title: 'A product state’s score',
          prompt: 'What is the CHSH value of the product state $|+x\\rangle|+x\\rangle$ with the same $x, y$ settings?',
          answer: PROD_S,
          tolerance: 0.005,
          hints: [{ text: 'Correlators factor.' }, { text: '$\\langle\\sigma_x\\rangle = 1$, $\\langle\\sigma_y\\rangle = 0$ for $|+x\\rangle$.' }, { text: 'Only $\\langle XX\\rangle = 1$ survives.' }],
          walkthrough: [{ text: '$S = x_1(y_1 + y_2) + x_2(y_1 - y_2) = 1\\cdot(1 + 0) + 0 = 1 \\le 2$.' }],
        },
        {
          id: 'q10-v-tsirelson',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The Tsirelson bound',
          prompt: 'The CHSH operator $C$ satisfies $C^2 \\le 8I$. What is the largest $|S|$ quantum mechanics allows?',
          answer: V.q10Tsirelson,
          tolerance: 0.01,
          hints: [{ text: '$|S| = |\\langle C\\rangle| \\le \\|C\\|$.' }, { text: '$\\|C\\| = \\sqrt{\\|C^2\\|}$.' }, { text: '$\\sqrt8$.' }],
          walkthrough: [{ text: `$C^2$ has top eigenvalue 8, so $\\|C\\| = 2\\sqrt2$; the Tsirelson bound is $2\\sqrt2 \\approx ${d(V.q10Tsirelson, 3)}$.` }],
        },
        {
          id: 'q10-v-pr',
          kind: 'choice',
          tier: 'stretch',
          title: 'A stronger-than-quantum link?',
          prompt: 'A correlation scores $S = 4$ and sends no signal. Is it allowed by quantum mechanics?',
          options: [
            { text: 'No — quantum mechanics stops at $2\\sqrt2$', correct: true, why: 'Right: the Tsirelson bound.' },
            { text: 'Yes, it is the PR box', correct: false, why: 'The PR box is a mathematical object, not a quantum state.' },
            { text: 'Yes, if the state is entangled enough', correct: false, why: 'No state, however entangled, beats $2\\sqrt2$.' },
            { text: 'Only for three qubits', correct: false, why: 'The bound holds regardless of the number of qubits.' },
          ],
          hints: [{ text: "What is Tsirelson's bound?" }, { text: '$2\\sqrt2 < 4$.' }, { text: 'The PR box is only a mathematical object.' }],
          walkthrough: [{ text: 'The Popescu–Rohrlich box scores 4 with no signalling, but exceeds $2\\sqrt2$, so quantum mechanics does not allow it.' }],
        },
      ],
    },
  ],
}
