import type { Lecture } from '../schema'
import { Q11_REVIEW } from './Q11.review'
import { Q11_STORY, Q11_UNIT_CLAIMS_BY_ID } from './Q11.story'
import { claim, close, V } from './Q11.values'

// Physics 709, chapter Q11: "Using entanglement: dense coding, teleportation, swapping" (Bergou §3.4, pp. 37-40;
// N&C §1.3.7, §2.3; no lecture-notes source — a 'books'-phase chapter). Every number a learner sees is computed in
// Q11.values.ts, then asserted in keyed claims (content.test.tsx runs `holds`; claims.test.ts compares each key
// with numpy, pipeline/claims_qc709/q11.py). Plan: docs/roles/proposals/P-Q11-story.md; rulings
// docs/roles/decisions/qc709-Q10Q13.md. Q11 owns dense coding, teleportation and entanglement swapping as
// protocols, the Pauli correction operators, the ebit as a resource, and the Weyl–Bell qudit basis (Formal). No
// sheet assigns anything in Q11: every challenge here carries a full walkthrough, except the qudit stretch item
// (Bergou's ⚑ P3.3 is cited only, state only, no derivation to walk through).

export const Q11: Lecture = {
  id: 'Q11',
  number: 11,
  title: 'Using entanglement: dense coding, teleportation, swapping',
  outcomes: [
    'Show that a local Pauli on one half of a Bell pair cycles it through all four Bell states.',
    'Explain dense coding: one shared pair lets Alice send two classical bits with one qubit.',
    "Regroup an unknown qubit state and a shared pair in Alice's own Bell basis, and read off Bob's four possible states.",
    'Run the teleportation circuit, apply the right correction, and say why no cloning or faster-than-light signal occurs.',
    'Explain entanglement swapping: a Bell measurement links two particles that never met, and how repeaters use it.',
    'State the qudit generalisation of the Bell basis (Formal).',
  ],
  prerequisites: ['qc-bell-basis-station', 'qc-bell-measurement-station', 'qc-cnot', 'qc-circuits', 'qc-readout', 'qc-spin-operators', 'qc-mixed-states'],
  symbols: {
    // Generic bra-ket notation markers (as Q8's own map defines them), all needed from q11-bell-tools on.
    '\\langle\\cdot\\rangle': 'q11-bell-tools:b1',
    '\\langle\\cdot|\\cdot\\rangle': 'q11-bell-tools:b1',
    '\\langle\\cdot|': 'q11-bell-tools:b1',
    '|\\cdot\\rangle': 'q11-bell-tools:b1',

    // q11-bell-tools
    '\\Phi': 'q11-bell-tools:b1',
    '\\Psi': 'q11-bell-tools:b2',
    '\\Psi_+': 'q11-bell-tools:b1',
    '\\beta_00': 'q11-bell-tools:b1',
    '\\otimes': 'q11-bell-tools:b1',
    Z: 'q11-bell-tools:b1',
    '|00\\rangle': 'q11-bell-tools:b1',
    '|11\\rangle': 'q11-bell-tools:b1',
    '|\\Phi^+\\rangle': 'q11-bell-tools:b1',
    I: 'q11-bell-tools:b1',
    P_A: 'q11-bell-tools:b1',
    X: 'q11-bell-tools:b2',
    Y: 'q11-bell-tools:b2',
    '|10\\rangle': 'q11-bell-tools:b2',
    '|01\\rangle': 'q11-bell-tools:b2',
    i: 'q11-bell-tools:b2',
    P: 'q11-bell-tools:b2',
    H: 'q11-bell-tools:b2',
    '|1\\rangle': 'q11-bell-tools:b2',

    // q11-dense-coding
    '\\xrightarrow': 'q11-dense-coding:b2',

    // q11-teleport-algebra
    '|\\psi\\rangle': 'q11-teleport-algebra:b1',
    '\\alpha': 'q11-teleport-algebra:b1',
    '|0\\rangle': 'q11-teleport-algebra:b1',
    '\\beta': 'q11-teleport-algebra:b1',
    A_1: 'q11-teleport-algebra:b1',
    A_2: 'q11-teleport-algebra:b1',
    B: 'q11-teleport-algebra:b1',
    '|xy\\rangle': 'q11-teleport-algebra:b2',
    '\\beta_xy': 'q11-teleport-algebra:b2',
    '|\\beta_xy\\rangle': 'q11-teleport-algebra:b2',
    '\\sigma': 'q11-teleport-algebra:b2',
    '\\sigma_xy': 'q11-teleport-algebra:b2',
    '\\sigma_00': 'q11-teleport-algebra:b2',
    '\\sigma_01': 'q11-teleport-algebra:b2',
    '\\sigma_10': 'q11-teleport-algebra:b2',
    '\\sigma_11': 'q11-teleport-algebra:b2',
    M_1: 'q11-teleport-algebra:b3',
    M_2: 'q11-teleport-algebra:b3',

    // q11-teleport-circuit
    c: 'q11-teleport-circuit:b2',
    '\\rho_B': 'q11-teleport-circuit:b3',
    '\\rho': 'q11-teleport-circuit:b3',
    A: 'q11-teleport-circuit:b3',

    // q11-swapping
    C: 'q11-swapping:b1',
    B_1: 'q11-swapping:b1',
    B_2: 'q11-swapping:b1',

    // q11-qudit
    d: 'q11-qudit',
    '\\mathbb': 'q11-qudit:b1',
    N: 'q11-qudit:b1',
    e: 'q11-qudit:b1',
    n: 'q11-qudit:b1',
    m: 'q11-qudit:b1',
    j: 'q11-qudit:b1',
    '|\\chi_n,m\\rangle': 'q11-qudit:b1',
    "|\\chi_n',m'\\rangle": 'q11-qudit:b1',
    "\\delta_nn'": 'q11-qudit:b1',
    "\\delta_mm'": 'q11-qudit:b1',
    '|j\\rangle': 'q11-qudit:b1',
    '|j\\oplusm\\rangle': 'q11-qudit:b1',
    '\\pi': 'q11-qudit:b1',
  },
  units: [
    {
      id: 'q11-bell-tools',
      story: Q11_STORY['q11-bell-tools'],
      review: Q11_REVIEW['q11-bell-tools'],
      claims: Q11_UNIT_CLAIMS_BY_ID['q11-bell-tools'],
      title: 'The Bell basis as a toolkit',
      question: 'How does a local gate move one pair through the Bell basis?',
      lecture: { pages: 'Bergou §3.4, p. 37 (no lecture-notes source)', summary: 'A local Pauli on one half of a shared Bell pair cycles it through all four Bell states.' },
      books: [
        { source: 'nc', where: '§2.3, p. 97', adds: 'the Bell-cycle gates, $I, Z, X, Y$, and their images under a Bell measurement.' },
        { source: 'nc', where: '§1.3.6, p. 25', adds: 'the Bell-creating circuit (Fig. 1.12), reused here for the Bell cycle.' },
        { source: 'bergou', where: '§3.4, p. 37', adds: 'the singlet-resource version of the same cycle (Bergou B6: his Bell names are swapped).' },
      ],
      visual: { kind: 'bloch', props: { theta: 0, phi: 0, editable: true, rotations: true, rotationAngles: [90, 180] }, tryThis: ["Turn the dial: a half turn is like the $Z$ cycle, a quarter like $X$ or $Y$."] },
      clues: [],
      insight: 'A local Pauli on one half of a Bell pair cycles the shared pair through all four Bell states.',
      insightFormal: '$(P\\otimes I)|\\Phi^+\\rangle$ for $P \\in \\{I, Z, X, Y\\}$ gives the four orthonormal Bell states, distinguished by one Bell measurement.',
      pitfalls: ["Thinking the gate on Alice's qubit also changes Bob's own reduced state: it stays $\\tfrac12I$ throughout."],
      play: [
        {
          id: 'q11-bt-which',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which gate?',
          prompt: "Which gate on Alice's qubit turns $\\Phi^+$ into $\\Phi^-$?",
          options: [
            { text: '$Z$', correct: true, why: '$Z$ flips the sign of the $|11\\rangle$ term, giving $\\Phi^-$.' },
            { text: '$X$', correct: false, why: '$X$ gives $\\Psi^+$ instead.' },
            { text: '$Y$', correct: false, why: '$Y$ gives $\\Psi^-$ instead.' },
            { text: '$H$', correct: false, why: 'A Hadamard is not one of the four Bell-cycle gates.' },
          ],
          hints: [{ text: '$\\Phi^-$ differs from $\\Phi^+$ by a sign on the $|11\\rangle$ term.' }, { text: 'Which Pauli signs $|1\\rangle$?' }, { text: '$Z|1\\rangle = -|1\\rangle$.' }],
          walkthrough: [{ text: '$Z\\otimes I$ flips the sign of the $|11\\rangle$ term, giving $\\Phi^-$.' }],
        },
        {
          id: 'q11-bt-psi-minus',
          kind: 'choice',
          tier: 'core',
          title: 'The singlet',
          prompt: 'Which gate turns $\\Phi^+$ into the singlet $\\Psi^-$?',
          options: [
            { text: '$Y$', correct: true, why: '$Y$ both flips and signs the terms, giving $\\Psi^-$ up to a [[global-phase|global phase]].' },
            { text: '$X$', correct: false, why: '$X$ flips but does not sign: it gives $\\Psi^+$.' },
            { text: '$Z$', correct: false, why: '$Z$ signs but does not flip: it gives $\\Phi^-$.' },
            { text: '$I$', correct: false, why: '$I$ leaves the pair at $\\Phi^+$.' },
          ],
          hints: [{ text: '$\\Psi^-$ both flips and signs the terms.' }, { text: '$X$ flips, $Z$ signs.' }, { text: '$Y$ does both, up to a phase.' }],
          walkthrough: [{ text: "$Y\\otimes I$ gives the pair $\\Psi^-$; the overall phase it carries is global, invisible to a Bell reading." }],
        },
      ],
    },
    {
      id: 'q11-dense-coding',
      story: Q11_STORY['q11-dense-coding'],
      review: Q11_REVIEW['q11-dense-coding'],
      claims: Q11_UNIT_CLAIMS_BY_ID['q11-dense-coding'],
      title: 'Dense coding: two bits, one qubit',
      question: 'How can one qubit carry two classical bits?',
      lecture: { pages: 'Bergou §3.4.1, pp. 37–38 (no lecture-notes source)', summary: 'A pre-shared Bell pair lets one transmitted qubit carry two classical bits.' },
      books: [
        { source: 'nc', where: '§2.3, pp. 97–98', adds: 'the dense-coding circuit (Eqs. 2.133–2.137): encode, send, Bell-measure.' },
        { source: 'bergou', where: '§3.4.1, pp. 37–38, Table 3.1', adds: 'the same protocol tabulated by gate and resulting Bell state.' },
      ],
      visual: { kind: 'amplitude-bars', props: { state: [0, 0], basis: 'z', editable: true }, tryThis: ['Try each gate on the shared pair: which one lands on which Bell state?'] },
      clues: [],
      insight: 'One shared Bell pair lets Alice send two classical bits by sending just one qubit.',
      insightFormal: "Four orthogonal Pauli encodings of $\\Phi^+$ are resolved by one Bell measurement, so one transmitted qubit carries $\\log_2 4 = 2$ classical bits.",
      pitfalls: ['Thinking the sent qubit alone holds the bits: its own reduced state is $\\tfrac12I$ no matter which gate was used.'],
      play: [
        {
          id: 'q11-dc-bits',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'How many bits?',
          prompt: 'With one shared Bell pair and one sent qubit, how many classical bits can Alice send Bob?',
          answer: V.q11DCbits,
          tolerance: 0.001,
          hints: [{ text: 'Four gates, four Bell states.' }, { text: 'A Bell measurement reads all four apart.' }, { text: '$\\log_2 4$.' }],
          walkthrough: [{ text: 'Four distinguishable encodings carry $\\log_2 4 = 2$ bits.' }],
        },
        {
          id: 'q11-dc-eve',
          kind: 'choice',
          tier: 'core',
          title: 'Eavesdropping',
          prompt: 'Eve steals the one qubit Alice sends. What can she learn from it alone?',
          options: [
            { text: 'Nothing — it is $\\tfrac12I$', correct: true, why: "Right: Alice's sent qubit alone is maximally mixed, whichever gate she used." },
            { text: 'One of the two bits', correct: false, why: 'A single qubit carries no part of either bit on its own.' },
            { text: 'Both bits', correct: false, why: 'She would need both qubits for a Bell measurement.' },
            { text: 'The Bell state', correct: false, why: 'The Bell state needs both qubits together to identify.' },
          ],
          hints: [{ text: 'What is one half of a Bell pair, on its own?' }, { text: 'Its reduced state.' }, { text: '$\\tfrac12I$ in every basis.' }],
          walkthrough: [{ text: "Each encoded qubit's own reduced state is $\\tfrac12I$, independent of the bits; the message lives in the correlation, which needs both halves." }],
        },
      ],
    },
    {
      id: 'q11-teleport-algebra',
      story: Q11_STORY['q11-teleport-algebra'],
      review: Q11_REVIEW['q11-teleport-algebra'],
      claims: Q11_UNIT_CLAIMS_BY_ID['q11-teleport-algebra'],
      title: 'Teleportation: the regrouping',
      question: 'How can a state move with only two bits sent?',
      lecture: { pages: 'N&C §1.3.7, pp. 26–27 (no lecture-notes source)', summary: "Regrouping $|\\psi\\rangle|\\Phi^+\\rangle$ in Alice's own Bell basis gives four equally likely, correctably twisted copies of $|\\psi\\rangle$ on Bob's qubit." },
      books: [
        { source: 'nc', where: '§1.3.7, pp. 26–27, Eqs. 1.31–1.36', adds: 'the full algebraic regrouping, step by step, ending in the correction rule.' },
        { source: 'bergou', where: '§3.4.2, pp. 38–39, Eq. 3.20', adds: 'the same regrouping with the singlet resource (Bergou B6: swapped names).' },
      ],
      visual: { kind: 'bloch', props: { theta: 73.7, phi: 0, editable: true }, tryThis: ['Drag the state anywhere: the right correction always restores it on Bob\'s side.'] },
      clues: [],
      insight: 'Regrouping the three-qubit state in Alice\'s Bell basis leaves Bob with $|\\psi\\rangle$, twisted by one of four Paulis.',
      insightFormal: '$|\\psi\\rangle_{A_1}|\\Phi^+\\rangle_{A_2B} = \\tfrac12\\sum_{xy}|\\beta_{xy}\\rangle(\\sigma_{xy}|\\psi\\rangle)$, each term with probability $\\tfrac14$.',
      pitfalls: ['Thinking Alice must learn $|\\psi\\rangle$ to send it: the protocol never measures the unknown state itself.'],
      play: [
        {
          id: 'q11-ta-prob',
          kind: 'numeric',
          tier: 'warm-up',
          title: "Alice's outcome",
          prompt: "In teleportation, what is the probability of Alice's outcome 01?",
          answer: V.q11TeleP,
          tolerance: 0.005,
          hints: [{ text: 'Four equal Bell parts.' }, { text: 'Each has weight $\\tfrac14$.' }, { text: '$\\tfrac14$.' }],
          walkthrough: [{ text: 'The regrouped state has four parts of equal weight, so every outcome has probability $\\tfrac14$.' }],
        },
        {
          id: 'q11-ta-corr',
          kind: 'choice',
          tier: 'core',
          title: 'Which correction?',
          prompt: "Alice's two qubits read 10. Which correction restores $|\\psi\\rangle$ on Bob's qubit?",
          options: [
            { text: '$Z$', correct: true, why: '$Z^1X^0 = Z$: a single $Z$ undoes the twist.' },
            { text: '$X$', correct: false, why: 'That is the correction for outcome 01.' },
            { text: '$ZX$', correct: false, why: 'That is the correction for outcome 11.' },
            { text: 'nothing', correct: false, why: 'That is the correction only for outcome 00.' },
          ],
          hints: [{ text: 'The correction is $Z^{M_1}X^{M_2}$.' }, { text: '$M_1 = 1$, $M_2 = 0$.' }, { text: '$Z^1X^0 = Z$.' }],
          walkthrough: [{ text: "Bob's pre-correction state is $Z|\\psi\\rangle$; applying $Z$ again (since $Z^2 = I$) gives $|\\psi\\rangle$." }],
        },
        {
          id: 'q11-ta-fid',
          kind: 'numeric',
          tier: 'core',
          title: 'The final fidelity',
          prompt: "After the right correction, what is the fidelity between Bob's qubit and $|\\psi\\rangle$?",
          answer: V.q11TeleFid,
          tolerance: 0.005,
          hints: [{ text: 'Teleportation is exact, not approximate.' }, { text: 'The correction exactly undoes the Pauli twist.' }, { text: 'The state is fully recovered.' }],
          walkthrough: [{ text: 'Each branch, corrected, gives $|\\psi\\rangle$ back with fidelity 1.' }],
        },
      ],
    },
    {
      id: 'q11-teleport-circuit',
      story: Q11_STORY['q11-teleport-circuit'],
      review: Q11_REVIEW['q11-teleport-circuit'],
      claims: Q11_UNIT_CLAIMS_BY_ID['q11-teleport-circuit'],
      title: 'Teleportation: the circuit and the call',
      question: 'Why is no state cloned, and no signal sent faster than light?',
      lecture: { pages: 'N&C §1.3.7, pp. 27–28 (no lecture-notes source)', summary: "Before Bob's classical call his qubit is $\\tfrac12I$, and Alice's own qubit ends as a plain bit, not a second copy of $|\\psi\\rangle$." },
      books: [{ source: 'nc', where: '§1.3.7, pp. 27–28, Fig. 1.13', adds: 'the circuit form of teleportation, with the classically controlled correction.' }],
      visual: { kind: 'bloch', props: { theta: 73.7, phi: 0, editable: false, measure: 'z' }, tryThis: ["Before the call Bob's qubit is the centre; only the correction moves it."] },
      clues: [],
      insight: "Before the classical call Bob's qubit is $\\tfrac12I$; only the correction, after the call, makes it $|\\psi\\rangle$.",
      insightFormal: "$\\rho_B^{\\mathrm{pre}} = \\tfrac12I$ independent of $|\\psi\\rangle$; exactly one copy of $|\\psi\\rangle$ exists after the protocol, on Bob's qubit.",
      pitfalls: ['Thinking the twist itself carries the state faster than light: it is the classical bits, bounded by $c$, that complete the transfer.'],
      play: [
        {
          id: 'q11-tc-pre',
          kind: 'numeric',
          tier: 'warm-up',
          title: "Before the call",
          prompt: "Before Alice's classical call, what is $\\langle Z\\rangle$ for Bob's qubit?",
          answer: V.q11BobPre,
          tolerance: 0.005,
          hints: [{ text: "Bob's pre-call state is the average over Alice's four outcomes." }, { text: 'It is $\\tfrac12I$.' }, { text: 'Every average vanishes at the centre.' }],
          walkthrough: [{ text: "$\\rho_B^{\\mathrm{pre}} = \\tfrac12I$, so $\\langle Z\\rangle = 0$: no information has arrived before the call." }],
        },
        {
          id: 'q11-tc-clone',
          kind: 'choice',
          tier: 'core',
          title: 'A copy?',
          prompt: 'After teleportation, how many qubits hold $|\\psi\\rangle$?',
          options: [
            { text: "One (Bob's)", correct: true, why: "Right: Alice's qubit has collapsed to a plain bit." },
            { text: "Two (Alice's and Bob's)", correct: false, why: "That would clone an unknown state, which no circuit can do." },
            { text: 'None', correct: false, why: 'After the correction Bob does hold $|\\psi\\rangle$.' },
            { text: 'Four', correct: false, why: 'Only one data qubit and one shared pair are involved.' },
          ],
          hints: [{ text: "What happens to Alice's qubit?" }, { text: 'Her measurement collapses it.' }, { text: 'It ends as a plain 0 or 1.' }],
          walkthrough: [{ text: "Alice's data qubit is a computational basis state after her measurement, so only Bob holds $|\\psi\\rangle$: no cloning." }],
        },
      ],
    },
    {
      id: 'q11-swapping',
      story: Q11_STORY['q11-swapping'],
      review: Q11_REVIEW['q11-swapping'],
      claims: Q11_UNIT_CLAIMS_BY_ID['q11-swapping'],
      title: 'Entanglement swapping and repeaters',
      question: 'Can two strangers end up entangled without ever meeting?',
      lecture: { pages: 'Bergou §3.4.3, pp. 39–40 (no lecture-notes source)', summary: "A middle party's own Bell measurement on two unrelated pairs leaves the outer two particles entangled." },
      books: [
        { source: 'bergou', where: '§3.4.3, pp. 39–40, Eq. 3.21', adds: 'the swapping identity, with the singlet resource (Bergou B6: swapped names).' },
        { source: 'bergou', where: '§14.3, pp. 260–262', adds: 'quantum repeaters: chained swaps over a lossy fibre link.' },
      ],
      visual: { kind: 'amplitude-bars', props: { state: [0, 0], basis: 'z', editable: true }, tryThis: ["Picture Bob's own Bell measurement: it always leaves A, C sharing his own outcome."] },
      clues: [],
      insight: "A middle party's own Bell measurement links two particles that have never interacted.",
      insightFormal: '$|\\Phi^+\\rangle_{AB_1}|\\Phi^+\\rangle_{B_2C} = \\tfrac12\\sum_{xy}|\\beta_{xy}\\rangle_{B_1B_2}|\\beta_{xy}\\rangle_{AC}$: each outcome swaps the entanglement onto A, C.',
      pitfalls: ['Thinking A and C can use the pair before the call: their marginal states are $\\tfrac12I$ until Bob announces his outcome.'],
      play: [
        {
          id: 'q11-sw-prob',
          kind: 'numeric',
          tier: 'warm-up',
          title: "Bob's outcome",
          prompt: 'In entanglement swapping, what is the probability Bob reads $\\Phi^+$ on his own two qubits?',
          answer: V.q11SwapP,
          tolerance: 0.005,
          hints: [{ text: 'Four equal Bell parts.' }, { text: 'Each carries weight $\\tfrac14$.' }, { text: '$\\tfrac14$.' }],
          walkthrough: [{ text: 'The regrouped four-qubit state has four equal Bell parts, so each of Bob\'s outcomes has probability $\\tfrac14$.' }],
        },
        {
          id: 'q11-sw-ac',
          kind: 'choice',
          tier: 'core',
          title: 'Which pair?',
          prompt: 'Bob reads $\\Psi^+$ on his own two qubits. What state do Alice and Charlie share?',
          options: [
            { text: '$\\Psi^+$', correct: true, why: "A and C land in exactly the Bell state Bob read." },
            { text: '$\\Phi^+$', correct: false, why: 'That is only the outcome when Bob reads $\\Phi^+$.' },
            { text: 'a product state', correct: false, why: 'Swapping always leaves A, C entangled, never a product state.' },
            { text: '$\\tfrac12I$', correct: false, why: 'That is each of their OWN marginal states, not the joint state they share.' },
          ],
          hints: [{ text: 'Recall the swapping identity.' }, { text: 'A and C always land in the Bell state Bob reads.' }, { text: 'The same $\\beta_{xy}$.' }],
          walkthrough: [{ text: '$|\\Phi^+\\rangle|\\Phi^+\\rangle = \\tfrac12\\sum_{xy}|\\beta_{xy}\\rangle_{B_1B_2}|\\beta_{xy}\\rangle_{AC}$, so Bob\'s $\\Psi^+$ leaves A, C in $\\Psi^+$.' }],
        },
      ],
    },
    {
      id: 'q11-qudit',
      story: Q11_STORY['q11-qudit'],
      review: Q11_REVIEW['q11-qudit'],
      claims: Q11_UNIT_CLAIMS_BY_ID['q11-qudit'],
      title: 'Larger alphabets (Formal)',
      question: 'Do these tricks work for $d$-level systems, not just qubits?',
      lecture: { pages: 'Bergou §3.4, Problem 3.3, p. 40 (⚑, state only; no lecture-notes source)', summary: 'The Bell basis generalizes to a full orthonormal set of maximally entangled states on two $d$-level qudits.' },
      books: [{ source: 'bergou', where: 'Problem 3.3, p. 40', adds: 'the Weyl–Bell basis $|\\chi_{n, m}\\rangle$ for $d$-level systems (⚑: stated, no worked solution).' }],
      visual: { kind: 'bloch', props: { theta: 90, phi: 0, editable: true }, tryThis: ['A reminder that one qubit ($N = 2$) is the smallest alphabet the formula allows.'] },
      clues: [],
      insight: 'A $d$-level qudit still has its own full basis of maximally entangled states.',
      insightFormal: '$|\\chi_{n, m}\\rangle = \\tfrac1{\\sqrt N}\\sum_je^{2\\pi ijn/N}|j\\rangle|j \\oplus m\\rangle$, $N^2$ orthonormal states; $N = 2$ recovers the Bell basis exactly.',
      play: [
        {
          id: 'q11-qd-count',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Counting the basis',
          prompt: 'For $d$-level systems, how many generalized Bell states $|\\chi_{n, m}\\rangle$ are there, at $N = 3$?',
          answer: V.q11WeylCount3,
          tolerance: 0.001,
          hints: [{ text: 'Two indices, $n$ and $m$.' }, { text: 'Each runs $0$ to $N - 1$.' }, { text: '$N \\times N$.' }],
          walkthrough: [],
        },
      ],
    },
  ],
}

export { claim, close }
