import type { Lecture } from '../schema'
import { Q12_REVIEW } from './Q12.review'
import { Q12_STORY, Q12_UNIT_CLAIMS_BY_ID } from './Q12.story'
import { V, claim, close } from './Q12.values'

// Physics 709, chapter Q12: "Detecting and measuring entanglement" (Bergou §3.5-3.9, pp. 40-59; N&C §12.5,
// pp. 571-582), in both tracks. A `'books'`-phase chapter (the notes stop at Lecture 7): every ramp beat is [B],
// every clue is [C], no [L] beat. Plan: docs/roles/proposals/P-Q12-story.md; rulings
// docs/roles/decisions/qc709-Q10Q13.md, qc709-remap.md. Every number a learner sees is computed in Q12.values.ts,
// then asserted in keyed claims (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy,
// pipeline/claims_qc709/q12.py). No sheet assigns any Q12 item (Bergou's ⚑ P3.4-P3.8 are cited derivations only,
// per `qc709-Q10Q13.md`), so every challenge below carries a full walkthrough.

export const Q12: Lecture = {
  id: 'Q12',
  number: 12,
  title: 'Detecting and measuring entanglement',
  outcomes: [
    'Take the transpose of one half of a density matrix and read whether the result has a negative eigenvalue; say why a negative one proves entanglement.',
    'Build one observable, a witness, whose average is negative only for some entangled states.',
    'List what local operations and a classical phone call can and cannot do to a shared pair, and read the Procrustean success chance off the algebra.',
    'Quote the entanglement of a pure pair as $E = S(\\rho_A)$, and say why local unitaries and a lost phone call leave it unchanged.',
    'Compute the concurrence of a two-qubit state and turn it into the entanglement.',
    'Contrast GHZ and W, and show why one qubit cannot be fully entangled with two others at once (monogamy).',
  ],
  prerequisites: [
    'qc-partial-trace-station',
    'qc-entropy-station',
    'qc-schmidt-station',
    'qc-state-distance',
    'qc-density-matrix-station',
    'qc-bloch-ball-station',
    'qc-ghz',
    'qc-bell-basis-station',
    'qc-operator-tensor-station',
  ],
  symbols: {
    // available from the chapter's very first site (Q12.outcomes / Q12.corrections, read before any unit)
    E: 'Q12',
    S: 'Q12',
    '\\rho_A': 'Q12',
    '|\\cdot\\rangle': 'Q12',
    '|10\\rangle': 'Q12',
    A: 'Q12',
    B: 'Q12',
    '|1\\rangle': 'Q12',
    '|00\\rangle': 'Q12',
    '|0\\rangle': 'Q12',
    '|\\psi^(k)\\rangle': 'Q12',
    E_F: 'Q12',
    '\\rho': 'Q12',
    '\\inf': 'Q12',
    p_k: 'Q12',
    '|v_0\\rangle': 'Q12',
    '|v_1\\rangle': 'Q12',
    'C_A:BC': 'Q12',
    p: 'Q12',
    // q12-ppt
    '\\rho_A,k': 'q12-ppt:b1',
    '\\otimes': 'q12-ppt:b1',
    '\\rho_B,k': 'q12-ppt:b1',
    '|\\Psi^-\\rangle': 'q12-ppt:b1',
    '|n\\nu\\rangle': 'q12-ppt:b2',
    '\\langle\\cdot|': 'q12-ppt:b2',
    '|m\\mu\\rangle': 'q12-ppt:b2',
    '\\rho_m\\mu,n\\nu': 'q12-ppt:b2',
    '\\rho_m\\nu,n\\mu': 'q12-ppt:b2',
    T_B: 'q12-ppt:b2',
    m: 'q12-ppt:b2',
    '\\mu': 'q12-ppt:b2',
    n: 'q12-ppt:b2',
    '\\nu': 'q12-ppt:b2',
    T: 'q12-ppt:b3',
    '\\lambda_\\min': 'q12-ppt:b3',
    '\\lambda': 'q12-ppt:b3',
    '\\iff': 'q12-ppt:b4',
    I: 'q12-ppt:b5',
    '\\sigma_x': 'q12-ppt.visual',
    w: 'q12-ppt:b5',
    // q12-witness
    W: 'q12-witness:b1',
    '\\rho_s': 'q12-witness:b1',
    '\\rho_e': 'q12-witness:b1',
    '\\langle\\cdot\\rangle': 'q12-witness:b1',
    '|\\eta\\rangle': 'q12-witness:b2',
    '\\lambda_-': 'q12-witness:b2',
    X: 'q12-witness:b2',
    Y: 'q12-witness:b2',
    '\\sigma_z': 'q12-witness.visual',
    // q12-locc
    '|\\psi\\rangle': 'q12-locc:b2',
    '|11\\rangle': 'q12-locc:b3',
    '|01\\rangle': 'q12-locc:b3',
    '\\pi': 'q12-locc:b3',
    '\\Phi': 'q12-locc:b3',
    '\\theta': 'q12-locc:b3',
    U_A: 'q12-locc:b3',
    p_s: 'q12-locc:b3',
    // q12-entropy
    '\\rho_B': 'q12-entropy:b1',
    '|\\psi(\\theta)\\rangle': 'q12-entropy:b1',
    h: 'q12-entropy:b1',
    "|\\psi'\\rangle": 'q12-entropy:b2',
    U_B: 'q12-entropy:b2',
    '\\dagger': 'q12-entropy:b2',
    '|\\varphi\\rangle': 'q12-entropy:b3',
    '\\lambda_\\psi': 'q12-entropy:b3',
    '\\lambda_\\varphi': 'q12-entropy:b3',
    '\\overline E': 'q12-entropy:b3',
    '\\rho_AB': 'q12-entropy:b4',
    d: 'q12-entropy:b5',
    U: 'q12-entropy.play.q12-en-local',
    // q12-concurrence
    '\\tilde\\psi': 'q12-concurrence:b1',
    '|\\tilde\\psi\\rangle': 'q12-concurrence:b1',
    '|\\psi^*\\rangle': 'q12-concurrence:b1',
    '\\sigma_y': 'q12-concurrence:b1',
    '\\langle\\cdot|\\cdot\\rangle': 'q12-concurrence:b1',
    C: 'q12-concurrence:b1',
    A_jk: 'q12-concurrence:b2',
    '\\lambda_1': 'q12-concurrence:b2',
    '\\lambda_2': 'q12-concurrence:b2',
    '\\lambda_3': 'q12-concurrence:b4',
    '\\lambda_4': 'q12-concurrence:b4',
    '\\lambda_j': 'q12-concurrence:b4',
    N: 'q12-concurrence:b4',
    '\\lambda_i': 'q12-concurrence.pitfalls',
    '\\tilde\\rho': 'q12-concurrence:b4',
    // q12-multipartite
    '|W\\rangle': 'q12-multipartite:b1',
    '|000\\rangle': 'q12-multipartite:b1',
    '|111\\rangle': 'q12-multipartite:b1',
    '|100\\rangle': 'q12-multipartite:b1',
    '|010\\rangle': 'q12-multipartite:b1',
    '|001\\rangle': 'q12-multipartite:b1',
    C_AB: 'q12-multipartite:b2',
    'C_A:B': 'q12-multipartite:b3',
    'C_A:C': 'q12-multipartite:b3',
    C_AC: 'q12-multipartite:b3',
  },
  symbolsFormal: {
    '\\prec': 'q12-entropy:b3',
  },
  units: [
    {
      id: 'q12-ppt',
      story: Q12_STORY['q12-ppt'],
      review: Q12_REVIEW['q12-ppt'],
      claims: Q12_UNIT_CLAIMS_BY_ID['q12-ppt'],
      title: 'The partial transpose test',
      question: 'If a state is separable, what survives a one-sided transpose?',
      lecture: { pages: 'books only (the notes stop at Lecture 7)', summary: 'This chapter draws no lecture notes; every beat is sourced to Bergou.' },
      books: [{ source: 'bergou', where: '§3.5 pp. 40–42, Eqs. 3.22–3.26', adds: 'the partial transpose, the Peres criterion, and the running separable-vs-entangled family.' }],
      visual: { kind: 'operator-builder', props: { axis: 'z' }, tryThis: ['Build $\\tfrac12I + \\tfrac1{\\sqrt2}\\sigma_x$: one eigenvalue is negative — not a state.'] },
      clues: [],
      insight: 'A negative eigenvalue of $\\rho^{T_B}$ proves entanglement; for two qubits the test is exact and sharper than CHSH.',
      insightFormal: 'The Peres criterion $\\rho^{T_B}\\ge 0$ is necessary for every separable state and, in $2\\otimes2$ and $2\\otimes3$, sufficient too (Horodecki).',
      pitfalls: ['Reading "no Bell violation" as "separable": CHSH is only sufficient, and PPT catches entangled states CHSH misses.'],
      play: [
        {
          id: 'q12-pp-min',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The running state’s smallest eigenvalue',
          prompt: 'For the running state at $p = 0.5$, what is the smallest eigenvalue of $\\rho^{T_B}$?',
          answer: V.q12BergLamMinAt05,
          tolerance: 0.005,
          hints: [{ text: 'Flip Bob’s index, then take eigenvalues.' }, { text: 'Three are positive.' }, { text: '$\\tfrac12[(1-p) - \\sqrt{(1-p)^2 + p^2}]$.' }],
          walkthrough: [{ text: 'At $p = 0.5$, $\\tfrac12[0.5 - \\sqrt{0.5}] = -0.1036 < 0$, so the state is entangled.' }],
        },
        {
          id: 'q12-pp-werner',
          kind: 'choice',
          tier: 'core',
          title: 'When is the Werner state entangled?',
          prompt: 'For which $w$ is the Werner state $w|\\Psi^-\\rangle\\langle\\Psi^-| + (1-w)\\tfrac14I$ entangled?',
          options: [
            { text: '$w > \\tfrac13$', correct: true, why: 'Right: $\\lambda_{\\min}(\\rho^{T_B}) = (1-3w)/4$ is $0$ at $w = \\tfrac13$, negative above.' },
            { text: '$w > \\tfrac12$', correct: false, why: 'That is too high: the state is already entangled below it.' },
            { text: '$w > 1/\\sqrt2$', correct: false, why: 'That is the CHSH threshold of Unit 12.1, not the Werner entanglement threshold.' },
            { text: 'all $w > 0$', correct: false, why: 'Too low: the Werner state is separable for small $w$.' },
          ],
          hints: [{ text: 'Find $\\lambda_{\\min}(\\rho^{T_B})$.' }, { text: 'It is $(1 - 3w)/4$.' }, { text: 'Negative when $w > \\tfrac13$.' }],
          walkthrough: [{ text: '$(1-3w)/4 < 0 \\iff w > \\tfrac13$; PPT is exact for two qubits, so that is the entanglement threshold.' }],
        },
        {
          id: 'q12-pp-vs-chsh',
          kind: 'choice',
          tier: 'core',
          title: 'Entangled without breaking CHSH?',
          prompt: 'At $p = 0.5$ the running state breaks no CHSH bound. Is it entangled?',
          options: [
            { text: 'Yes — its partial transpose is negative', correct: true, why: 'Right: $\\lambda_{\\min}(\\rho^{T_B}) < 0$ already at $p = 0.5$.' },
            { text: 'No — CHSH is the final word', correct: false, why: 'CHSH is only sufficient for entanglement, not necessary.' },
            { text: 'Only if $p > 1/\\sqrt2$', correct: false, why: 'That is backwards: the state is entangled well below the CHSH threshold.' },
            { text: 'Cannot tell', correct: false, why: 'PPT settles it exactly for two qubits.' },
          ],
          hints: [{ text: 'CHSH is only sufficient.' }, { text: 'PPT is sharper.' }, { text: '$\\lambda_{\\min} < 0$ already at $p = 0.5$.' }],
          walkthrough: [{ text: 'PPT detects entanglement for all $p > 0$, well below the CHSH threshold $0.707$.' }],
        },
        {
          id: 'q12-pp-sum',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The eigenvalues sum to the trace',
          prompt: 'The eigenvalues of $\\rho^{T_B}$ at $p = 0.5$ are $-0.1036, 0.25, 0.25, 0.6036$. What do they sum to?',
          answer: V.q12BergPptSpec05Sum,
          tolerance: 0.01,
          hints: [{ text: 'The partial transpose does not change the trace.' }, { text: '$\\mathrm{Tr}\\,\\rho = 1$.' }, { text: 'Add the four.' }],
          walkthrough: [{ text: '$-0.1036 + 0.25 + 0.25 + 0.6036 = 1$; the flip moves eigenvalues around but keeps the trace.' }],
        },
      ],
    },
    {
      id: 'q12-witness',
      story: Q12_STORY['q12-witness'],
      review: Q12_REVIEW['q12-witness'],
      claims: Q12_UNIT_CLAIMS_BY_ID['q12-witness'],
      title: 'One observable that spots entanglement',
      question: 'Can a single measured quantity flag an entangled state?',
      lecture: { pages: 'books only', summary: 'This chapter draws no lecture notes; every beat is sourced to Bergou.' },
      books: [{ source: 'bergou', where: '§3.5 pp. 42–44, Eqs. 3.27–3.28', adds: 'the entanglement witness, built from the Peres test’s own negative eigenvector.' }],
      visual: { kind: 'operator-builder', props: { axis: 'x' }, tryThis: ['Build $\\sigma_z$; its average on $|0\\rangle$ is $+1$, on $|1\\rangle$ is $-1$: a sign reads a property.'] },
      clues: [],
      insight: 'A witness $W$ has $\\langle W\\rangle \\ge 0$ on every separable state and $< 0$ on some entangled one; it needs no tomography.',
      insightFormal: '$W = (|\\eta\\rangle\\langle\\eta|)^{T_B}$, built from $\\rho^{T_B}$’s negative eigenvector, certifies entanglement from a single expectation value.',
      pitfalls: ['Thinking $W$ itself is positive: only $\\rho_s^{T_B}$ is; $W$ has a negative eigenvalue by construction.'],
      play: [
        {
          id: 'q12-wi-val',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The witness’s value',
          prompt: 'For the witness built from $\\rho^{T_B}$’s negative eigenvector, what is $\\mathrm{Tr}(\\rho W)$ at $p = 0.5$?',
          answer: V.q12WitnessVal,
          tolerance: 0.005,
          hints: [{ text: 'It equals the negative eigenvalue.' }, { text: '$\\mathrm{Tr}(\\rho W) = \\mathrm{Tr}(\\rho^{T_B}|\\eta\\rangle\\langle\\eta|)$.' }, { text: '$= \\lambda_-$.' }],
          walkthrough: [{ text: 'By the transpose-swap identity $\\mathrm{Tr}(\\rho W) = \\lambda_- = -0.1036$.' }],
        },
        {
          id: 'q12-wi-why',
          kind: 'choice',
          tier: 'core',
          title: 'Why non-negative on separable states?',
          prompt: 'Why is $\\mathrm{Tr}(\\rho_sW) \\ge 0$ for every separable $\\rho_s$?',
          options: [
            { text: 'Because $\\rho_s^{T_B} \\ge 0$', correct: true, why: 'Right: separable states are PPT, so the sandwich is non-negative.' },
            { text: 'Because $W \\ge 0$', correct: false, why: 'False: $W$ itself has a negative eigenvalue.' },
            { text: 'Because $\\rho_s$ is pure', correct: false, why: 'Separable states need not be pure; this is not why.' },
            { text: 'Because $\\mathrm{Tr}\\,\\rho_s = 1$', correct: false, why: 'Every state has trace 1; that alone says nothing about sign.' },
          ],
          hints: [{ text: 'Move the flip onto $\\rho_s$.' }, { text: 'Separable states are PPT.' }, { text: '$\\langle\\eta|\\rho_s^{T_B}|\\eta\\rangle \\ge 0$.' }],
          walkthrough: [{ text: '$\\mathrm{Tr}(\\rho_sW) = \\langle\\eta|\\rho_s^{T_B}|\\eta\\rangle \\ge 0$ because $\\rho_s^{T_B} \\ge 0$; $W$ itself is not positive.' }],
        },
      ],
    },
    {
      id: 'q12-locc',
      story: Q12_STORY['q12-locc'],
      review: Q12_REVIEW['q12-locc'],
      claims: Q12_UNIT_CLAIMS_BY_ID['q12-locc'],
      title: 'Local moves and a shared coin',
      question: 'What can two distant labs do to a shared pair, and at what cost?',
      lecture: { pages: 'books only', summary: 'This chapter draws no lecture notes; every beat is sourced to Bergou and N&C.' },
      books: [
        { source: 'bergou', where: '§3.6 pp. 45–46', adds: 'LOCC, ebits, and the Procrustean distillation protocol (erratum B9 on its failure branch).' },
        { source: 'nc', where: '§12.5.2 pp. 578–582', adds: 'distillation and dilution as the limiting rate $E(|\\psi\\rangle) = S(\\rho_A)$.' },
      ],
      visual: { kind: 'phase-dial', props: { theta: 30, rotations: false }, tryThis: ['Set $\\theta = 45°$: the pair is already maximal, nothing to distil.'] },
      clues: [],
      insight: 'LOCC is local gates, measurements and a classical call; it can distil or dilute entanglement but never create it.',
      insightFormal: 'Procrustean distillation succeeds with probability $p_s = 2\\sin^2\\theta$, leaving $\\Phi^+$ on success and $|1\\rangle_{A\'}|00\\rangle$ on failure (erratum B9).',
      pitfalls: ['"Local operations can boost entanglement": LOCC can only redistribute or spend it, never manufacture it from a product state.'],
      play: [
        {
          id: 'q12-lo-ps',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Procrustean success chance at 30°',
          prompt: 'Procrustean distillation on $\\cos30°|00\\rangle + \\sin30°|11\\rangle$: what is the success chance?',
          answer: V.q12ProcPs30,
          tolerance: 0.005,
          hints: [{ text: '$p_s = 2\\sin^2\\theta$.' }, { text: '$\\sin30° = \\tfrac12$.' }, { text: '$2 \\times \\tfrac14$.' }],
          walkthrough: [{ text: '$2\\sin^230° = 0.5$; a $0$ on the ancilla leaves a Bell pair.' }],
        },
        {
          id: 'q12-lo-max',
          kind: 'numeric',
          tier: 'core',
          title: 'Procrustean success chance at 45°',
          prompt: 'Run the same step on an already-maximal pair, $\\theta = 45°$. What is the success chance?',
          answer: V.q12ProcPs45,
          tolerance: 0.005,
          hints: [{ text: '$p_s = 2\\sin^2\\theta$.' }, { text: '$\\sin45° = 1/\\sqrt2$.' }, { text: '$2 \\times \\tfrac12$.' }],
          walkthrough: [{ text: '$2\\sin^245° = 1$; a maximal pair is already distilled, so nothing is discarded.' }],
        },
        {
          id: 'q12-lo-moves',
          kind: 'choice',
          tier: 'core',
          title: 'Which move is not LOCC?',
          prompt: 'Which of these is **not** an LOCC move?',
          options: [
            { text: 'Mailing qubit $A$ to Bob', correct: true, why: 'Right: LOCC excludes exchanging any quantum system.' },
            { text: 'Appending a fresh qubit', correct: false, why: 'Allowed: each lab may add its own ancilla.' },
            { text: 'Measuring locally', correct: false, why: 'Allowed: each lab may measure its own qubits.' },
            { text: 'Phoning the result', correct: false, why: 'Allowed: classical communication is exactly what the "CC" means.' },
          ],
          hints: [{ text: '"Local" means each lab alone.' }, { text: 'The phone carries classical bits only.' }, { text: 'No qubits travel.' }],
          walkthrough: [{ text: 'LOCC allows local gates, measurements, ancillas and classical messages, but never sending a qubit.' }],
        },
      ],
    },
    {
      id: 'q12-entropy',
      story: Q12_STORY['q12-entropy'],
      review: Q12_REVIEW['q12-entropy'],
      claims: Q12_UNIT_CLAIMS_BY_ID['q12-entropy'],
      title: 'Entanglement as a number',
      question: 'How much entanglement does a pure pair hold, and does it ever grow?',
      lecture: { pages: 'books only', summary: 'This chapter draws no lecture notes; every beat is sourced to Bergou and N&C.' },
      books: [
        { source: 'bergou', where: '§3.7 pp. 47–53, Eqs. 3.41, 3.58–3.60', adds: '$E = S(\\rho_A)$, local-unitary invariance, additivity, LOCC monotonicity, and the entanglement of formation (erratum B11).' },
        { source: 'nc', where: '§12.5.1 p. 573, Theorem 12.15', adds: 'majorization as the exact LOCC-convertibility condition (stated, not proved).' },
      ],
      visual: { kind: 'operator-builder', props: { axis: 'z' }, tryThis: ['Build $\\mathrm{diag}(0.75, 0.25)$ and read its eigenvalues: they feed $S = h(0.75) = 0.811$ bit.'] },
      clues: [],
      insight: 'A pure pair’s entanglement is $E = S(\\rho_A)$: local-unitary invariant, additive, and never increased by LOCC.',
      insightFormal: '$E(|\\psi\\rangle) = S(\\rho_A) = S(\\rho_B)$; for mixed $\\rho$ the entanglement of formation $E_F(\\rho) = \\inf\\sum_kp_kE(|\\psi^{(k)}\\rangle)$ takes its place.',
      pitfalls: ['Using $S(\\rho_A)$ for a mixed pair: the Werner state has $S(\\rho_A) = 1$ bit yet is only weakly entangled.'],
      play: [
        {
          id: 'q12-en-pure',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Entanglement of the tilted pair',
          prompt: 'What is the entanglement $E = S(\\rho_A)$ of $\\cos30°|00\\rangle + \\sin30°|11\\rangle$, in bits?',
          answer: V.q12E30,
          tolerance: 0.005,
          unit: 'bit',
          hints: [{ text: '$\\rho_A = \\mathrm{diag}(\\cos^230°, \\sin^230°)$.' }, { text: '$= \\mathrm{diag}(0.75, 0.25)$.' }, { text: '$h(0.75)$.' }],
          walkthrough: [{ text: '$-0.75\\log_20.75 - 0.25\\log_20.25 = 0.811$ bit.' }],
        },
        {
          id: 'q12-en-bell',
          kind: 'numeric',
          tier: 'core',
          title: 'Entanglement of a Bell state',
          prompt: 'What is $E$ for a Bell state?',
          answer: V.q12Ebell,
          tolerance: 0.005,
          unit: 'bit',
          hints: [{ text: 'Its half is $\\tfrac12I$.' }, { text: '$S(\\tfrac12I)$.' }, { text: '$\\log_22$.' }],
          walkthrough: [{ text: 'The reduced state is maximally mixed, $E = 1$ bit, the maximum for two qubits.' }],
        },
        {
          id: 'q12-en-local',
          kind: 'choice',
          tier: 'core',
          title: 'Does a local gate change E?',
          prompt: 'Does a Hadamard on Alice’s qubit change the entanglement?',
          options: [
            { text: 'No', correct: true, why: 'Right: a local unitary conjugates $\\rho_A$ without moving its eigenvalues.' },
            { text: 'Yes, it doubles it', correct: false, why: 'Local gates cannot change entanglement at all.' },
            { text: 'Yes, it zeroes it', correct: false, why: 'Local gates cannot change entanglement at all.' },
            { text: 'Only if Bob also acts', correct: false, why: 'Even a local gate on both sides leaves $E$ unchanged.' },
          ],
          hints: [{ text: 'It conjugates $\\rho_A$.' }, { text: 'Eigenvalues are unchanged.' }, { text: '$S$ depends only on them.' }],
          walkthrough: [{ text: '$S(U\\rho_AU^\\dagger) = S(\\rho_A)$; local unitaries leave $E$ alone.' }],
        },
        {
          id: 'q12-en-mixed',
          kind: 'choice',
          tier: 'stretch',
          title: 'Is S(ρ_A) the Werner state’s entanglement?',
          prompt: 'The Werner state at $w = 0.5$ has $S(\\rho_A) = 1$ bit. Is that its entanglement?',
          options: [
            { text: 'No — it is weakly entangled, not maximally', correct: true, why: 'Right: its concurrence is only $0.25$, far below maximal.' },
            { text: 'Yes, it is maximally entangled', correct: false, why: 'A fully mixed marginal does not mean maximal entanglement for a mixed pair.' },
            { text: 'No, it is separable', correct: false, why: 'It is entangled: $w = 0.5 > \\tfrac13$.' },
            { text: 'Cannot tell', correct: false, why: 'The concurrence settles it: $0.25$.' },
          ],
          hints: [{ text: '$S(\\rho_A)$ measures entanglement only for pure states.' }, { text: 'The Werner state is mixed.' }, { text: 'Use the entanglement of formation instead.' }],
          walkthrough: [{ text: 'A mixed state’s marginal can be fully mixed with little entanglement; its concurrence is only $0.25$.' }],
        },
      ],
    },
    {
      id: 'q12-concurrence',
      story: Q12_STORY['q12-concurrence'],
      review: Q12_REVIEW['q12-concurrence'],
      claims: Q12_UNIT_CLAIMS_BY_ID['q12-concurrence'],
      title: 'Concurrence: one formula for two qubits',
      question: 'Is there a closed formula for a two-qubit pair’s entanglement?',
      lecture: { pages: 'books only', summary: 'This chapter draws no lecture notes; every beat is sourced to Bergou.' },
      books: [{ source: 'bergou', where: '§3.8 pp. 54–56, Eqs. 3.65–3.79', adds: 'the concurrence, its pure-state formula, Wootters’ mixed-state formula, and the negativity.' }],
      visual: { kind: 'phase-dial', props: { theta: 30, rotations: false }, tryThis: ['Dial $\\theta$ from $0°$ to $45°$: $C$ climbs from $0$ to $1$.'] },
      clues: [],
      insight: 'For a pure pair $C = 2\\sqrt{\\lambda_1\\lambda_2} = \\sin2\\theta$; Wootters extends it to any mixed two-qubit state.',
      insightFormal: '$C(|\\psi\\rangle) = |\\langle\\psi|\\tilde\\psi\\rangle|$; $E(C) = h\\big(\\tfrac{1+\\sqrt{1-C^2}}2\\big)$; $C(\\rho) = \\max(0,\\lambda_1-\\lambda_2-\\lambda_3-\\lambda_4)$ for the Wootters square roots of $\\rho\\tilde\\rho$.',
      pitfalls: ['Reading the Wootters $\\lambda_i$ as Schmidt weights: they are square-root eigenvalues of $\\rho\\tilde\\rho$, a different list.'],
      play: [
        {
          id: 'q12-co-pure',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Concurrence of the tilted pair',
          prompt: 'What is the concurrence of $\\cos30°|00\\rangle + \\sin30°|11\\rangle$?',
          answer: V.q12ConcPure30,
          tolerance: 0.005,
          hints: [{ text: '$C = \\sin2\\theta$.' }, { text: '$2\\theta = 60°$.' }, { text: '$\\sin60°$.' }],
          walkthrough: [{ text: '$C = 2\\sqrt{\\lambda_1\\lambda_2} = 2\\sqrt{0.75 \\times 0.25} = \\sin60° = 0.866$.' }],
        },
        {
          id: 'q12-co-werner',
          kind: 'numeric',
          tier: 'core',
          title: 'Concurrence of the Werner state',
          prompt: 'What is the concurrence of the Werner state at $w = 0.5$?',
          answer: V.q12WerConcAtHalf,
          tolerance: 0.005,
          hints: [{ text: 'Wootters: $\\max(0, \\lambda_1 - \\lambda_2 - \\lambda_3 - \\lambda_4)$.' }, { text: 'For Werner it reduces to $(3w - 1)/2$.' }, { text: '$(1.5 - 1)/2$.' }],
          walkthrough: [{ text: '$(3 \\times 0.5 - 1)/2 = 0.25$, matching the PPT verdict that the state is weakly entangled.' }],
        },
        {
          id: 'q12-co-eofc',
          kind: 'numeric',
          tier: 'core',
          title: 'Entanglement from concurrence',
          prompt: 'For $C = 0.866$, what is the entanglement $E(C)$, in bits?',
          answer: V.q12EofC30,
          tolerance: 0.005,
          unit: 'bit',
          hints: [{ text: '$E(C) = h\\!\\big((1 + \\sqrt{1 - C^2})/2\\big)$.' }, { text: '$\\sqrt{1 - 0.75} = 0.5$.' }, { text: '$h(0.75)$.' }],
          walkthrough: [{ text: '$(1 + 0.5)/2 = 0.75$, $h(0.75) = 0.811$ — the same number as the entropy.' }],
        },
        {
          id: 'q12-co-product',
          kind: 'choice',
          tier: 'stretch',
          title: 'Concurrence of a product',
          prompt: 'What is the concurrence of the product state $|01\\rangle$?',
          options: [
            { text: '0', correct: true, why: '$\\det A = 0$ for a product state, so $C = 2|\\det A| = 0$.' },
            { text: '0.5', correct: false, why: 'Too high: a product state carries no entanglement.' },
            { text: '1', correct: false, why: 'That is the maximum, reserved for a Bell state.' },
            { text: '$1/\\sqrt2$', correct: false, why: 'Concurrence never exceeds 1, and a product gives exactly 0.' },
          ],
          hints: [{ text: '$C = 2\\sqrt{\\lambda_1\\lambda_2}$.' }, { text: 'One weight is $0$.' }, { text: 'The product is $0$.' }],
          walkthrough: [{ text: '$\\lambda_2 = 0$, so $C = 0$: no entanglement.' }],
        },
      ],
    },
    {
      id: 'q12-multipartite',
      story: Q12_STORY['q12-multipartite'],
      review: Q12_REVIEW['q12-multipartite'],
      claims: Q12_UNIT_CLAIMS_BY_ID['q12-multipartite'],
      title: 'Three qubits: GHZ, W and monogamy',
      question: 'With three qubits, can every pair be strongly entangled at once?',
      lecture: { pages: 'books only', summary: 'This chapter draws no lecture notes; every beat is sourced to Bergou.' },
      books: [{ source: 'bergou', where: '§3.9 pp. 57–58, Eq. 3.84', adds: 'GHZ vs W, SLOCC classes, and the Coffman–Kundu–Wootters monogamy inequality (erratum B12).' }],
      visual: { kind: 'deposit-stats', props: { state: '+x', axis: 'z', seed: 709 }, tryThis: ['Fire many atoms from one qubit of the W state along any axis: about half each way, whichever axis you choose.'] },
      clues: [],
      insight: 'GHZ and W are both genuinely three-way entangled, but GHZ’s is all three-way while W keeps pairwise entanglement; monogamy caps how much can be shared.',
      insightFormal: 'GHZ-class and W-class are the two inequivalent SLOCC classes of genuinely tripartite states; the CKW inequality $C_{A:B}^2+C_{A:C}^2\\le C_{A:BC}^2$ is saturated by $|W\\rangle$.',
      pitfalls: ['"More parties, more sharing": monogamy limits it; GHZ holds no pairwise entanglement at all once one qubit is traced out.'],
      play: [
        {
          id: 'q12-mu-wab',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'W’s reduced pair',
          prompt: 'Trace qubit $C$ out of the W state. What is the concurrence of the remaining pair?',
          answer: V.q12WpairConc,
          tolerance: 0.005,
          hints: [{ text: '$\\rho_{AB} = \\tfrac13[(|01\\rangle + |10\\rangle)(\\langle01| + \\langle10|) + |00\\rangle\\langle00|]$.' }, { text: 'Wootters gives $\\tfrac23$.' }, { text: '$0.667$.' }],
          walkthrough: [{ text: 'The W state keeps pairwise entanglement, $C_{AB} = \\tfrac23$.' }],
        },
        {
          id: 'q12-mu-ghz',
          kind: 'numeric',
          tier: 'core',
          title: 'GHZ’s reduced pair',
          prompt: 'Do the same for the GHZ state. What is the reduced pair’s concurrence?',
          answer: V.q12GhzPairConc,
          tolerance: 0.005,
          hints: [{ text: 'The reduced pair is $\\tfrac12(|00\\rangle\\langle00| + |11\\rangle\\langle11|)$.' }, { text: 'That is a classical coin mixture.' }, { text: 'It is separable.' }],
          walkthrough: [{ text: 'GHZ entanglement is purely three-way; its reduced pair has $C = 0$.' }],
        },
        {
          id: 'q12-mu-ckw',
          kind: 'numeric',
          tier: 'core',
          title: 'The CKW left side',
          prompt: 'For the W state, evaluate $C_{A:B}^2 + C_{A:C}^2$.',
          answer: V.q12CkwLeft,
          tolerance: 0.005,
          hints: [{ text: 'Both concurrences are $\\tfrac23$.' }, { text: '$2 \\times (\\tfrac23)^2$.' }, { text: '$2 \\times \\tfrac49$.' }],
          walkthrough: [{ text: '$\\tfrac49 + \\tfrac49 = \\tfrac89 = 0.889$, equal to $C_{A:BC}^2 = (\\tfrac{2\\sqrt2}3)^2$: the monogamy bound is saturated.' }],
        },
        {
          id: 'q12-mu-sloc',
          kind: 'choice',
          tier: 'stretch',
          title: 'W into GHZ by SLOCC?',
          prompt: 'Can stochastic LOCC turn a W state into a GHZ state?',
          options: [
            { text: 'No — they are different SLOCC classes', correct: true, why: 'Right: GHZ-class and W-class are inequivalent.' },
            { text: 'Yes, always', correct: false, why: 'No local map connects the two classes.' },
            { text: 'Yes, with probability $\\tfrac89$', correct: false, why: 'The CKW value $\\tfrac89$ is a monogamy bound, not a conversion probability.' },
            { text: 'Only for three qubits', correct: false, why: 'The classes are inequivalent precisely at three qubits; the question is settled there.' },
          ],
          hints: [{ text: 'SLOCC needs invertible local operators.' }, { text: 'There are exactly two tripartite classes.' }, { text: 'No local map connects them.' }],
          walkthrough: [{ text: 'GHZ and W are the two inequivalent genuinely-tripartite SLOCC classes; neither can be turned into the other.' }],
        },
      ],
    },
  ],
  corrections: [
    {
      where: 'Bergou p. 46 (§3.6.2)',
      says: 'The Procrustean failure branch is $|10\\rangle_{AB}$.',
      shouldSay: 'The failure branch is $|1\\rangle_{A\'}|00\\rangle_{AB}$: qubit $A$ stays $|0\\rangle$, not $|1\\rangle$.',
      check: () => close(V.q12ProcFailFidToKet00, 1, 1e-6),
      source: 'book',
    },
    {
      where: 'Bergou p. 52, Eqs. 3.59–3.60',
      says: 'The entanglement of formation is $E_F(\\rho) = \\inf\\sum_kE(|\\psi^{(k)}\\rangle)$.',
      shouldSay: 'The weight $p_k$ is missing: $E_F(\\rho) = \\inf\\sum_kp_kE(|\\psi^{(k)}\\rangle)$.',
      check: () => true,
      source: 'book',
    },
    {
      where: 'Bergou p. 59, Eq. 3.86',
      says: 'The W state’s second Schmidt partner is printed $|v_0\\rangle$.',
      shouldSay: 'It should read $|v_1\\rangle$ (the CKW computation for $C_{A:BC}$ needs two distinct partners).',
      check: () => close(V.q12CkwLeft, V.q12CkwRight, 1e-6),
      source: 'book',
    },
    {
      where: 'Bergou p. 41',
      says: 'All Bell inequalities hold for $p \\le 1/\\sqrt2$.',
      shouldSay: 'That bound is proved only for CHSH (the Horodecki bound); say "CHSH", not "every Bell inequality".',
      check: () => close(V.q12ChshThresh, Math.SQRT1_2, 1e-9),
      source: 'book',
    },
  ],
}

export { claim, close }
