import type { Lecture } from '../schema'
import { Q13_REVIEW } from './Q13.review'
import { Q13_STORY, Q13_UNIT_CLAIMS_BY_ID } from './Q13.story'
import { claim, close, V } from './Q13.values'

// Physics 709, chapter Q13: "Open-system maps: Kraus operators and impossible machines" (Bergou Ch. 4, pp. 65-75;
// N&C Ch. 8, §8.2.3-8.3.4, Box 8.2, Box 12.1; no lecture-notes source -- a 'books'-phase chapter). Every number a
// learner sees is computed in Q13.values.ts, then asserted in keyed claims (content.test.tsx runs `holds`;
// claims.test.ts compares each key with numpy, pipeline/claims_qc709/q13.py). Plan: docs/roles/proposals/
// P-Q13-story.md; rulings docs/roles/decisions/qc709-Q10Q13.md, qc709-remap.md. Q13 owns quantum channels, Kraus
// operators, the Choi matrix, Stinespring dilation, the depolarizing/dephasing/amplitude-damping channels,
// no-cloning and Herbert's argument. No sheet assigns anything in Q13 (Bergou's ⚑ P4.1-P4.5 are used only as cited
// asides, never graded): every challenge here carries a full walkthrough.

export const Q13: Lecture = {
  id: 'Q13',
  number: 13,
  title: 'Open-system maps: Kraus operators and impossible machines',
  outcomes: [
    'Write a qubit’s open evolution as an operator sum, with its trace-preserving completeness condition.',
    'List what a channel preserves, and show by one example that positivity alone is not enough: complete positivity is.',
    'Say why every channel is a unitary on a bigger system, and that a qubit channel needs at most four Kraus operators.',
    'Turn the depolarizing channel into a shrinking of the whole Bloch ball, by a factor set by the noise strength.',
    'Show in a few lines why no unitary can clone an unknown qubit.',
    'Explain why a perfect copier would permit faster-than-light signalling.',
  ],
  prerequisites: ['qc-trace-rule', 'qc-mixed-states', 'qc-bloch-ball-station', 'qc-partial-trace-station', 'qc-purification-station', 'qc-cnot', 'qc-bell-cycle', 'qc-no-signalling'],
  symbols: {
    // Generic bra-ket notation markers, needed from q13-from-unitary:b1 on. (Subscripted/accented letters are
    // keyed by their SCANNED form, content/symbols.test.ts `requiredSymbols`: braces are stripped from a subscript,
    // a superscript is DROPPED entirely (so "\Phi^+" scans as plain "\Phi", but "|\Phi^+\rangle" — inside a ket —
    // keeps the caret, since kets are cleaned differently), and a leading \mathcal/\mathbf/\mathrm is stripped
    // entirely (so "\mathcal E" scans as plain "E" and "\mathbf r" as plain "r"); \vec keeps its argument
    // ("\vec r" scans as "\vec r", one token with a space). None of this is a chapter choice.)
    V: 'Q13',
    S_z: 'q13-from-unitary.visual',
    'P_+': 'q13-from-unitary.visual',
    'P_-': 'q13-from-unitary.visual',
    S_x: 'q13-properties.visual',
    '\\hbar': 'q13-properties.visual',
    '\\theta': 'q13-depolarizing.visual',
    '\\varphi': 'q13-depolarizing.visual',
    '|+x\\rangle': 'q13-depolarizing.visual',
    '|-\\rangle': 'q13-no-cloning.visual',
    '\\langle\\cdot|\\cdot\\rangle': 'q13-from-unitary:b1',
    '\\otimes': 'q13-from-unitary:b1',
    U_SE: 'q13-from-unitary:b1',
    E: 'q13-from-unitary:b1',
    U: 'q13-from-unitary:b1',
    '\\rho': 'q13-from-unitary:b1',
    '\\dagger': 'q13-from-unitary:b1',
    e: 'q13-from-unitary:b1',
    i: 'q13-from-unitary:b1',
    t: 'q13-from-unitary:b1',
    '\\hat H': 'q13-from-unitary:b1',
    X: 'q13-from-unitary:b1',
    Y: 'q13-from-unitary:b1',
    Z: 'q13-from-unitary:b1',

    // q13-from-unitary:b2 (the notation beat): the generic ket/bra markers' first real use is the |m⟩⟨m| /
    // |0⟩⟨0|_E projector notation here (ground) and below (formal); I_E, E_k appear in the Formal aside.
    '|\\cdot\\rangle': 'q13-from-unitary:b2',
    '\\langle\\cdot|': 'q13-from-unitary:b2',
    A_m: 'q13-from-unitary:b2',
    T: 'q13-from-unitary:b2',
    '|m\\rangle': 'q13-from-unitary:b2',
    '|0\\rangle': 'q13-from-unitary:b2',
    I_E: 'q13-from-unitary:b2',
    E_k: 'q13-from-unitary:b2',

    // q13-from-unitary:b3
    I: 'q13-from-unitary:b3',
    p: 'q13-from-unitary:b3',

    // q13-properties
    A: 'q13-properties:b2',
    B: 'q13-properties:b2',
    I_B: 'q13-properties:b2',
    '\\rho_AB': 'q13-properties:b2',
    '\\Phi': 'q13-properties:b3',
    '|\\Phi^+\\rangle': 'q13-properties:b3',
    '\\rho_\\Phi^+': 'q13-properties:b3',
    '|00\\rangle': 'q13-properties:b3',
    '|11\\rangle': 'q13-properties:b3',
    '\\lambda': 'q13-properties:b3',

    // q13-stinespring
    '|\\psi\\rangle': 'q13-stinespring:b1',
    H_S: 'q13-stinespring:b2',
    H_E: 'q13-stinespring:b2',
    'D_\\nu': 'q13-stinespring:b3',
    'U_\\nu\\mu': 'q13-stinespring:b3',
    'A_\\mu': 'q13-stinespring:b3',
    N: 'q13-stinespring:b3',

    // q13-depolarizing
    '|+\\rangle': 'q13-depolarizing:b1',
    r: 'q13-depolarizing:b2',
    j: 'q13-depolarizing:b2',
    k: 'q13-depolarizing:b2',
    n: 'q13-depolarizing:b2',
    '\\vec r': 'q13-depolarizing:b2',
    '\\sigma_j': 'q13-depolarizing:b2',
    '\\sigma_k': 'q13-depolarizing:b2',
    M: 'q13-depolarizing:b3',
    c: 'q13-depolarizing:b3',
    '\\gamma': 'q13-depolarizing:b3',

    // q13-no-cloning
    '|1\\rangle': 'q13-no-cloning:b1',
    '|10\\rangle': 'q13-no-cloning:b1',
    '|01\\rangle': 'q13-no-cloning:b1',
    '|+0\\rangle': 'q13-no-cloning:b1',
    '|\\varphi\\rangle': 'q13-no-cloning:b2',

    // q13-herbert
    '|++\\rangle': 'q13-herbert:b2',
    '|--\\rangle': 'q13-herbert:b2',
    '\\rho_B': 'q13-herbert:b2',
  },
  units: [
    {
      id: 'q13-from-unitary',
      story: Q13_STORY['q13-from-unitary'],
      review: Q13_REVIEW['q13-from-unitary'],
      claims: Q13_UNIT_CLAIMS_BY_ID['q13-from-unitary'],
      title: 'Where channels come from',
      question: 'How does a qubit evolve when it is coupled to something we ignore?',
      lecture: { pages: 'Bergou §4.1.1, pp. 65–66 (no lecture-notes source)', summary: 'Coupling a [[qubit|qubit]] to an environment, evolving by one unitary, and tracing the environment out gives the Kraus operator-sum form of a channel.' },
      books: [
        { source: 'bergou', where: '§4.1.1, pp. 65–66, Eqs. 4.1–4.5', adds: 'the Kraus / operator-sum representation, built from a system-environment unitary.' },
        { source: 'nc', where: '§8.2.3, pp. 360–361, Eqs. 8.9–8.14', adds: 'the same derivation, with the completeness relation as trace preservation.' },
      ],
      visual: { kind: 'operator-builder', props: { axis: 'z' }, tryThis: ['Build $S_z$ here: its completeness check, $P_+ + P_- = I$, is the same idea behind a channel’s $\\sum_mA_m^\\dagger A_m = I$ below.'] },
      clues: [],
      insight: 'Couple a qubit to an environment, evolve by one unitary, forget the environment: the result is a channel $\\mathcal E(\\rho) = \\sum_m A_m\\rho A_m^\\dagger$.',
      insightFormal: '$\\mathcal E(\\rho) = \\mathrm{Tr}_E[U_{SE}(\\rho\\otimes|0\\rangle\\langle0|_E)U_{SE}^\\dagger] = \\sum_m A_m\\rho A_m^\\dagger$, with $\\sum_m A_m^\\dagger A_m = I$.',
      pitfalls: ['Thinking open evolution must still be unitary: tracing out an entangled environment makes it non-unitary.'],
      play: [
        {
          id: 'q13-fu-sum',
          kind: 'choice',
          tier: 'warm-up',
          title: 'The completeness sum',
          prompt: "For dephasing at $p = 0.5$, what is $\\sum_m A_m^\\dagger A_m$?",
          options: [
            { text: 'The identity $I$', correct: true, why: 'Unitarity of the coupling forces this for every channel, dephasing and depolarizing alike.' },
            { text: '$\\tfrac12I$', correct: false, why: 'The two terms, each $\\tfrac12I$, add to the full $I$, not a half.' },
            { text: '$0$', correct: false, why: 'A channel that summed to $0$ would destroy every state.' },
            { text: 'It depends on $\\rho$', correct: false, why: '$\\sum_m A_m^\\dagger A_m$ is an operator identity, fixed before any $\\rho$ is chosen.' },
          ],
          hints: [{ text: 'It follows from the coupling being unitary.' }, { text: 'Each term contributes $\\tfrac12I$.' }, { text: 'Two halves make a whole.' }],
          walkthrough: [{ text: '$\\tfrac12(I^\\dagger I) + \\tfrac12(Z^\\dagger Z) = \\tfrac12I + \\tfrac12I = I$.' }],
        },
        {
          id: 'q13-fu-tp',
          kind: 'choice',
          tier: 'core',
          title: 'Trace-preserving?',
          prompt: 'A channel has $\\sum_m A_m^\\dagger A_m = I$. Is it trace-preserving?',
          options: [
            { text: 'Yes, for every input', correct: true, why: 'Completeness is an operator identity, so it holds for every $\\rho$.' },
            { text: 'Only for pure inputs', correct: false, why: 'The identity does not single out pure states.' },
            { text: 'Only for the maximally mixed state', correct: false, why: 'The identity holds for every $\\rho$, not one special case.' },
            { text: 'No', correct: false, why: '$\\sum_m A_m^\\dagger A_m = I$ is exactly the trace-preserving condition.' },
          ],
          hints: [{ text: 'Use the cyclic property of the trace.' }, { text: 'Pull the operators together first.' }, { text: '$\\mathrm{Tr}(\\sum_m A_m^\\dagger A_m\\,\\rho) = \\mathrm{Tr}(I\\rho)$.' }],
          walkthrough: [{ text: '$\\mathrm{Tr}\\,\\mathcal E(\\rho) = \\mathrm{Tr}(\\sum_m A_m^\\dagger A_m\\,\\rho) = \\mathrm{Tr}\\,\\rho$: the completeness relation is exactly trace preservation.' }],
        },
      ],
    },
    {
      id: 'q13-properties',
      story: Q13_STORY['q13-properties'],
      review: Q13_REVIEW['q13-properties'],
      claims: Q13_UNIT_CLAIMS_BY_ID['q13-properties'],
      title: 'What a channel preserves — and the catch',
      question: 'Which maps on density matrices are physically allowed?',
      lecture: { pages: 'Bergou §4.1.2, pp. 66–68 (no lecture-notes source)', summary: 'A channel keeps Hermiticity, trace and positivity, but positivity alone is too weak: complete positivity is the real test.' },
      books: [
        { source: 'bergou', where: '§4.1.2, pp. 66–68', adds: 'the three preserved properties, and complete positivity as the stronger requirement.' },
        { source: 'nc', where: 'Box 8.2, p. 369', adds: 'the transpose as the standard example of positive-but-not-completely-positive.' },
      ],
      visual: { kind: 'operator-builder', props: { axis: 'x' }, tryThis: ['Build $S_x$ here: its eigenvalues are fixed at $\\pm\\hbar/2$ by construction. A channel’s Choi matrix has no such guarantee — its sign is the real test.'] },
      clues: [],
      insight: 'A channel keeps Hermitian, trace and positivity — but the real test is complete positivity, which the plain transpose fails.',
      insightFormal: '$\\mathcal E\\otimes I_B$ must be positive for any ancilla $B$; the transpose fails this, since $(T\\otimes I)|\\Phi^+\\rangle\\langle\\Phi^+|$ has a negative eigenvalue.',
      pitfalls: ['"Positive is enough": the transpose is positive yet not a channel.'],
      play: [
        {
          id: 'q13-pr-min',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The smallest eigenvalue',
          prompt: 'Transpose one half of $\\Phi^+$. What is the smallest eigenvalue of the result?',
          answer: V.q13TransposeSpecMin,
          tolerance: 0.005,
          hints: [{ text: 'The result is half the swap operator.' }, { text: 'The swap has eigenvalues $\\pm1$.' }, { text: 'Scale by $\\tfrac12$.' }],
          walkthrough: [{ text: 'The spectrum is $\\{\\tfrac12,\\tfrac12,\\tfrac12,-\\tfrac12\\}$; the smallest is $-\\tfrac12$.' }],
        },
        {
          id: 'q13-pr-cp',
          kind: 'choice',
          tier: 'core',
          title: 'A valid channel?',
          prompt: 'Is the transpose a valid quantum channel?',
          options: [
            { text: 'No — positive but not completely positive', correct: true, why: "Its Choi matrix has a negative eigenvalue, so it fails the real test." },
            { text: 'Yes', correct: false, why: 'A negative Choi eigenvalue rules this out.' },
            { text: 'Only on pure states', correct: false, why: 'Complete positivity is a property of the map, not of which states it is fed.' },
            { text: 'Only on mixed inputs', correct: false, why: 'The failure shows up on a pure two-qubit test state, so input purity is not the issue.' },
          ],
          hints: [{ text: 'Act on half of an entangled pair.' }, { text: 'Its Choi matrix has a negative eigenvalue.' }, { text: "A channel's Choi matrix must be $\\ge 0$." }],
          walkthrough: [{ text: '$(T\\otimes I)\\Phi^+$ has eigenvalue $-\\tfrac12$, so $T$ is not completely positive and not a channel.' }],
        },
      ],
    },
    {
      id: 'q13-stinespring',
      story: Q13_STORY['q13-stinespring'],
      review: Q13_REVIEW['q13-stinespring'],
      claims: Q13_UNIT_CLAIMS_BY_ID['q13-stinespring'],
      title: 'Every channel is a unitary in disguise',
      question: 'Can any channel be realised by a unitary on a larger system?',
      lecture: { pages: 'Bergou §4.1.2–4.1.3, pp. 66–70 (no lecture-notes source)', summary: 'Any Kraus set comes from some system-environment unitary (the Stinespring dilation); a qubit channel never needs more than four Kraus operators.' },
      books: [{ source: 'bergou', where: '§4.1.2–4.1.3, pp. 66–70, Eqs. 4.6–4.8, 4.28', adds: 'the dilation construction, the Kraus-freedom theorem, and the $N^2$ bound.' }],
      visual: { kind: 'operator-builder', props: { axis: 'z' }, tryThis: ['Build $S_z$ here: its own completeness check, $P_+ + P_- = I$, is the same idea as an isometry’s $V^\\dagger V = I$ below.'] },
      clues: [],
      insight: 'Every channel is a unitary on the qubit plus a fresh environment; a qubit channel never needs more than four Kraus operators.',
      insightFormal: 'The isometry $V = \\sum_m A_m\\otimes|m\\rangle$ has $V^\\dagger V = I$ by completeness, so it extends to a unitary $U_{SE}$; at most $N^2 = 4$ Kraus operators are ever needed for a qubit.',
      pitfalls: ['Thinking the dilating environment is unique: any unitary-related Kraus set gives the same channel.'],
      play: [
        {
          id: 'q13-st-max',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The Kraus bound',
          prompt: 'At most how many Kraus operators does a one-qubit channel ever need?',
          answer: V.q13MaxKraus2,
          tolerance: 0.001,
          hints: [{ text: 'The bound is $N^2$.' }, { text: 'A qubit has $N = 2$.' }, { text: '$2^2$.' }],
          walkthrough: [{ text: "The channel's Choi matrix has rank at most $N^2 = 4$, so four operators always suffice." }],
        },
        {
          id: 'q13-st-dilate',
          kind: 'choice',
          tier: 'core',
          title: 'Always a unitary?',
          prompt: 'Can every quantum channel be realised as a unitary on a larger system?',
          options: [
            { text: 'Yes — the Stinespring dilation', correct: true, why: 'Any Kraus set defines an isometry $V$ with $V^\\dagger V = I$, which extends to a unitary.' },
            { text: 'Only unitary channels', correct: false, why: 'The dilation works for any channel, not only the trivial unitary ones.' },
            { text: 'Only for qubits', correct: false, why: 'The construction works at any dimension.' },
            { text: 'No', correct: false, why: 'The isometry $V$ always extends to a full unitary.' },
          ],
          hints: [{ text: 'Add a fresh environment.' }, { text: 'Build the isometry $V = \\sum_m A_m\\otimes|m\\rangle$.' }, { text: '$V^\\dagger V = I$.' }],
          walkthrough: [{ text: '$V$ preserves inner products, so it extends to a unitary; noise is entanglement with an ignored environment.' }],
        },
      ],
    },
    {
      id: 'q13-depolarizing',
      story: Q13_STORY['q13-depolarizing'],
      review: Q13_REVIEW['q13-depolarizing'],
      claims: Q13_UNIT_CLAIMS_BY_ID['q13-depolarizing'],
      title: 'The shrinking Bloch ball',
      question: 'What does noise do to the Bloch ball?',
      lecture: { pages: 'Bergou §4.2, pp. 70–71 (no lecture-notes source)', summary: 'The depolarizing channel shrinks the whole Bloch ball toward the centre by a factor that depends on the noise strength $p$.' },
      books: [
        { source: 'bergou', where: '§4.2, pp. 70–71, Eqs. 4.29–4.34', adds: 'the depolarizing channel and its uniform Bloch-ball shrink.' },
        { source: 'nc', where: '§8.3.2–8.3.4, pp. 374–379, Eqs. 8.87–8.103', adds: 'the general affine Bloch map, and depolarizing as its isotropic case.' },
      ],
      visual: { kind: 'bloch', props: { theta: 60, phi: 30, editable: true }, tryThis: ['Pick $|{+x}\\rangle$ (set $\\theta=90°,\\varphi=0°$): noise at $p=0.5$ would leave this point a third of the way out, as the picture below shows.'] },
      clues: [],
      insight: 'The depolarizing channel shrinks the whole Bloch ball toward the centre by $1 - \\tfrac{4p}3$; other channels squash it into an off-centre egg instead.',
      insightFormal: '$\\mathbf r \\to (1 - \\tfrac{4p}3)\\mathbf r$ (isotropic); a general channel is the affine map $\\mathbf r \\to M\\mathbf r + \\mathbf c$, with amplitude damping an off-centre example.',
      pitfalls: ['Reading $p = 1$ as fully mixed: the factor is $-\\tfrac13$ there; full mixing is at $p = 0.75$.'],
      play: [
        {
          id: 'q13-de-half',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The shrink at $p = 0.5$',
          prompt: 'For the depolarizing channel at $p = 0.5$, by what factor does the Bloch ball shrink?',
          answer: V.q13DepolFactorP50,
          tolerance: 0.005,
          hints: [{ text: 'The factor is $1 - \\tfrac{4p}3$.' }, { text: '$1 - \\tfrac23$.' }, { text: '$\\tfrac13$.' }],
          walkthrough: [{ text: '$1 - \\tfrac{4\\times0.5}3 = \\tfrac13$: every arrow is a third as long.' }],
        },
        {
          id: 'q13-de-collapse',
          kind: 'numeric',
          tier: 'core',
          title: 'Full collapse',
          prompt: 'At what $p$ does the ball collapse to the single central point?',
          answer: V.q13PThreeQuarters,
          tolerance: 0.005,
          hints: [{ text: 'Set the factor to $0$.' }, { text: '$1 - \\tfrac{4p}3 = 0$.' }, { text: '$p = 0.75$.' }],
          walkthrough: [{ text: '$\\tfrac{4p}3 = 1$ at $p = 0.75$: every state becomes $\\tfrac12I$.' }],
        },
        {
          id: 'q13-de-one',
          kind: 'numeric',
          tier: 'core',
          title: 'The factor at $p = 1$',
          prompt: 'What is the shrink factor at $p = 1$?',
          answer: V.q13DepolFactorP100,
          tolerance: 0.005,
          hints: [{ text: '$1 - \\tfrac43$.' }, { text: '$-\\tfrac13$.' }, { text: 'The sign flips.' }],
          walkthrough: [{ text: '$1 - \\tfrac43 = -\\tfrac13$: the ball is inverted and shrunk to a third, not a point.' }],
        },
        {
          id: 'q13-de-full',
          kind: 'choice',
          tier: 'stretch',
          title: 'Fully depolarized at $p = 1$?',
          prompt: 'Is the qubit fully depolarized at $p = 1$?',
          options: [
            { text: 'No — that happens at $p = 0.75$; at $p = 1$ the ball is inverted', correct: true, why: 'The shrink factor is $0$ at $p = 0.75$, not $-\\tfrac13$ as at $p = 1$.' },
            { text: 'Yes', correct: false, why: 'The factor at $p = 1$ is $-\\tfrac13$, not $0$.' },
            { text: 'Only for $|+\\rangle$', correct: false, why: 'The factor is the same for every input direction.' },
            { text: 'Never', correct: false, why: 'Full mixing does happen, just at $p = 0.75$.' },
          ],
          hints: [{ text: 'Full mixing means a factor of $0$.' }, { text: 'The factor is $0$ at $p = 0.75$.' }, { text: 'At $p = 1$ it is $-\\tfrac13 \\ne 0$.' }],
          walkthrough: [{ text: 'The factor vanishes at $p = 0.75$; beyond that it goes negative, inverting the ball rather than flattening it further.' }],
        },
      ],
    },
    {
      id: 'q13-no-cloning',
      story: Q13_STORY['q13-no-cloning'],
      review: Q13_REVIEW['q13-no-cloning'],
      claims: Q13_UNIT_CLAIMS_BY_ID['q13-no-cloning'],
      title: 'Why you cannot copy a qubit',
      question: 'Can one build a machine that duplicates an unknown state?',
      lecture: { pages: 'Bergou §4.3.1, pp. 72–73 (no lecture-notes source)', summary: 'A CNOT copies computational-basis states but entangles a superposition instead of copying it: no unitary clones an unknown qubit.' },
      books: [
        { source: 'bergou', where: '§4.3.1, pp. 72–73, Eqs. 4.35–4.37', adds: 'the cloning unitary’s definition and the CNOT counterexample.' },
        { source: 'nc', where: 'Box 12.1, p. 532', adds: 'the overlap argument $\\langle\\psi|\\varphi\\rangle = \\langle\\psi|\\varphi\\rangle^2$.' },
      ],
      visual: { kind: 'phase-dial', props: { theta: 90, rotations: false }, tryThis: ['Dial $\\varphi$ to $180°$: the point moves to $|-\\rangle$. This dial has only one wire, so it cannot show the CNOT entangling a superposition below.'] },
      clues: [],
      insight: 'A CNOT copies $|0\\rangle$ and $|1\\rangle$ perfectly, but on $|+\\rangle$ it produces an entangled pair, not two copies: no-cloning.',
      insightFormal: 'By linearity $U|+\\rangle|0\\rangle = \\Phi^+ \\ne |+\\rangle|+\\rangle$; cloning forces $\\langle\\psi|\\varphi\\rangle = \\langle\\psi|\\varphi\\rangle^2$, so only orthogonal states are clonable.',
      pitfalls: ['"The CNOT is a copier": it copies only computational-basis states.'],
      play: [
        {
          id: 'q13-nc-out',
          kind: 'choice',
          tier: 'warm-up',
          title: 'The CNOT output',
          prompt: 'A CNOT (control = data) acts on $|+\\rangle|0\\rangle$. What comes out?',
          options: [
            { text: 'The Bell state $\\Phi^+$', correct: true, why: 'Linearity on $|0\\rangle,|1\\rangle$ gives $\\tfrac1{\\sqrt2}(|00\\rangle+|11\\rangle) = \\Phi^+$.' },
            { text: '$|+\\rangle|+\\rangle$', correct: false, why: 'That would be a true copy, which the CNOT does not produce.' },
            { text: '$|00\\rangle$', correct: false, why: 'That is only the output for the basis input $|0\\rangle|0\\rangle$.' },
            { text: '$|+0\\rangle$', correct: false, why: 'The CNOT entangles the two wires; the output is not a product state.' },
          ],
          hints: [{ text: 'Use linearity on $|0\\rangle,|1\\rangle$.' }, { text: '$\\tfrac1{\\sqrt2}(|00\\rangle+|11\\rangle)$.' }, { text: 'That is $\\Phi^+$.' }],
          walkthrough: [{ text: 'The output is entangled, not two copies — the state is cloned only on the basis.' }],
        },
        {
          id: 'q13-nc-overlap',
          kind: 'numeric',
          tier: 'core',
          title: 'The overlap',
          prompt: 'The no-cloning proof needs $\\langle\\psi|\\varphi\\rangle \\in \\{0, 1\\}$. What is $\\langle0|+\\rangle$?',
          answer: V.q13Overlap0Plus,
          tolerance: 0.005,
          hints: [{ text: '$|+\\rangle = (|0\\rangle+|1\\rangle)/\\sqrt2$.' }, { text: '$\\langle0|+\\rangle = 1/\\sqrt2$.' }, { text: '$0.7071$.' }],
          walkthrough: [{ text: '$0.7071$ is neither $0$ nor $1$, so $|0\\rangle$ and $|+\\rangle$ cannot both be cloned.' }],
        },
        {
          id: 'q13-nc-ortho',
          kind: 'choice',
          tier: 'core',
          title: 'Which states can be copied?',
          prompt: 'Which states *can* a machine copy?',
          options: [
            { text: 'Mutually orthogonal ones', correct: true, why: 'Orthogonal states, like classical bits, satisfy the overlap condition trivially.' },
            { text: 'Any pure states', correct: false, why: 'An arbitrary pair of pure states generally overlaps strictly between $0$ and $1$.' },
            { text: 'Only mixed states', correct: false, why: 'The no-cloning argument is about pure states; [[mixture|mixtures]] are a separate question.' },
            { text: 'None', correct: false, why: 'Orthogonal states, such as $|0\\rangle, |1\\rangle$, ARE clonable.' },
          ],
          hints: [{ text: 'The proof allows overlap $0$ or $1$.' }, { text: 'Overlap $0$ means orthogonal.' }, { text: 'Like $|0\\rangle, |1\\rangle$.' }],
          walkthrough: [{ text: 'Orthogonal states — classical bits — are clonable; unknown superpositions are not.' }],
        },
      ],
    },
    {
      id: 'q13-herbert',
      story: Q13_STORY['q13-herbert'],
      review: Q13_REVIEW['q13-herbert'],
      claims: Q13_UNIT_CLAIMS_BY_ID['q13-herbert'],
      title: 'Cloning would break relativity',
      question: 'What would a perfect copier let you do?',
      lecture: { pages: 'Bergou §4.3.1–4.3.2, pp. 72–73 (no lecture-notes source)', summary: "Herbert's proposed faster-than-light telephone would work if a perfect cloner existed; no-cloning protects no-signalling." },
      books: [{ source: 'bergou', where: '§4.3.1–4.3.2, pp. 72–73', adds: "Herbert's scheme and why a cloner would defeat it." }],
      visual: { kind: 'bloch', props: { theta: 90, phi: 0, editable: false }, tryThis: ["This is one of Alice's x-basis outcomes, a surface point; Bob's own qubit has no point on the surface at all."] },
      clues: [],
      insight: "Bob's qubit is the fully mixed centre whatever Alice measures; a cloner would let him read her choice, signalling faster than light.",
      insightFormal: '$\\rho_B = \\tfrac12I$ for either of Alice’s measurement bases; a perfect cloner would extract her basis from many copies, so no-cloning is the dynamical guarantee of no-signalling.',
      pitfalls: ['Separating no-cloning from no-signalling: they are two faces of one wall.'],
      play: [
        {
          id: 'q13-he-bob',
          kind: 'choice',
          tier: 'warm-up',
          title: "Bob's state",
          prompt: 'Alice measures her half of $\\Phi^+$ in the $z$ basis but does not call Bob. What is his state?',
          options: [
            { text: 'The maximally mixed $\\tfrac12I$', correct: true, why: 'Without the outcome, Bob’s state averages to $\\tfrac12I$, unchanged by Alice’s measurement.' },
            { text: '$|0\\rangle$', correct: false, why: 'That would require Bob to know Alice’s outcome.' },
            { text: '$|+\\rangle$', correct: false, why: 'That is not what a $z$-basis reading of $\\Phi^+$ leaves behind.' },
            { text: '$\\Phi^+$', correct: false, why: 'That is the original PAIR’s state, not Bob’s qubit alone.' },
          ],
          hints: [{ text: 'Bob does not know the outcome.' }, { text: 'Average over Alice’s two possible results.' }, { text: '$\\tfrac12(|0\\rangle\\langle0| + |1\\rangle\\langle1|)$.' }],
          walkthrough: [{ text: "Without the outcome, Bob's state is $\\tfrac12I$, the centre — unchanged by Alice's measurement." }],
        },
        {
          id: 'q13-he-signal',
          kind: 'choice',
          tier: 'core',
          title: 'What a cloner would allow',
          prompt: 'What would a perfect cloner let Bob do?',
          options: [
            { text: 'Signal faster than light', correct: true, why: "Many copies of his one qubit would reveal Alice's basis instantly." },
            { text: 'Measure more precisely', correct: false, why: 'The issue is not measurement precision, but extracting Alice’s choice.' },
            { text: 'Cool his qubit', correct: false, why: 'Cloning has nothing to do with temperature.' },
            { text: 'Nothing new', correct: false, why: 'A cloner WOULD let him read Alice’s basis — that is exactly the danger.' },
          ],
          hints: [{ text: 'Bob could make many copies of his one qubit.' }, { text: 'He could then read Alice’s basis from the copies.' }, { text: 'That is a message with no delay.' }],
          walkthrough: [{ text: "Copies would reveal Alice's basis instantly; no-signalling forbids this, so the cloner cannot exist." }],
        },
      ],
    },
  ],
  corrections: [
    {
      where: 'Bergou p. 67',
      says: 'The isometry $V$ extends to a unitary by setting it to the identity on the orthogonal complement.',
      shouldSay: 'Identity on the complement is not unitary here: the extension must instead map an orthonormal basis of the complement onto one of the complement of $V$’s range.',
      check: () => V.q13StinespringIdExtGap > 0.1,
      source: 'book',
    },
  ],
}

export { claim, close }
