import type { Lecture } from '../schema'
import { Q14_REVIEW } from './Q14.review'
import { Q14_STORY, Q14_UNIT_CLAIMS_BY_ID } from './Q14.story'
import { claim, close, V } from './Q14.values'

// Physics 709, chapter Q14: "Generalized measurements and telling states apart" (Bergou Ch. 5, pp. 77-104; N&C
// §2.2.4-2.2.8; no lecture-notes source -- a 'books'-phase chapter). Every number a learner sees is computed in
// Q14.values.ts, then asserted in keyed claims (content.test.tsx runs `holds`; claims.test.ts compares each key with
// numpy, pipeline/claims_qc709/q14.py). Plan: docs/roles/proposals/P-Q14-story.md; rulings
// docs/roles/decisions/qc709-Q14.md, qc709-remap.md. Q14 owns generalized measurement, the POVM and its elements,
// detection operators, Neumark's theorem, the trine, unambiguous (USD) and minimum-error (Helstrom) discrimination,
// the inconclusive outcome, the prior. No sheet assigns anything in Q14 (Bergou's ⚑ P5.1-P5.6 are not ingested):
// every challenge here carries a full walkthrough. §5.6 (sequential measurements) is out of scope (ruling 1 of
// qc709-Q14.md); the pointer unit's von Neumann pointer-shift is cited physics only, no engine number depends on it.

export const Q14: Lecture = {
  id: 'Q14',
  number: 14,
  title: 'Generalized measurements and telling states apart',
  outcomes: [
    'Describe a measurement as coupling the system to a meter, then read the chance of each outcome off the meter.',
    'Say what a POVM is — positive elements adding to the identity — and build one with more outcomes than the qubit has dimensions.',
    "State Neumark's theorem: every POVM is an ordinary projective measurement on the system plus an ancilla.",
    'Explain why no measurement identifies two non-orthogonal states with certainty, and build the unambiguous scheme with its inconclusive outcome.',
    'Compute the minimum-error (Helstrom) bound for telling two states apart when every trial must get an answer.',
    'Compare the two strategies and state the trade-off: never-wrong costs you answered trials.',
  ],
  prerequisites: [
    'qc-selective-measurement',
    'qc-observable',
    'qc-spectral-representation',
    'qc-density-matrix',
    'qc-trace',
    'qc-bloch-ball',
    'qc-positive-operator',
    'qc-partial-trace',
    'qc-purification',
    'qc-trace-distance',
    'qc-quantum-channel',
    'qc-kraus-operator',
    'qc-stinespring',
    'qc-unitary-freedom',
    'qc-operator-matrix',
  ],
  symbols: {
    // q14-pointer: recapped ρ, X, P, a generic unitary U, the pointer-shift letters (cited physics only; Formal's
    // von Neumann model H ⊃ ħgXP, U = e^{-igtXP}).
    '\\rho': 'q14-pointer:b1',
    X: 'q14-pointer:b1',
    P: 'q14-pointer:b1',
    g: 'q14-pointer:b1',
    t: 'q14-pointer:b1',
    U: 'q14-pointer:b1',
    '\\lambda_j': 'q14-pointer:b1',
    x_j: 'q14-pointer:b1',
    H: 'q14-pointer:b1',
    '\\supset': 'q14-pointer:b1',
    '\\hbar': 'q14-pointer:b1',
    e: 'q14-pointer:b1',
    i: 'q14-pointer:b1',
    M_m: 'q14-pointer',
    '\\langle\\cdot\\rangle': 'q14-pointer',
    '\\eta': 'q14-pointer:b2',
    Z: 'q14-pointer:b2',
    I: 'q14-pointer:b2',
    '|0\\rangle': 'q14-pointer:b2',
    '|\\cdot\\rangle': 'q14-pointer:b2',
    '|1\\rangle': 'q14-pointer:b2',
    'E_+': 'q14-pointer:b2',
    'E_-': 'q14-pointer:b2',
    'p_\\pm': 'q14-pointer:b2',
    'E_\\pm': 'q14-pointer:b2',
    'p_+': 'q14-pointer:b2',
    '\\langle\\cdot|': 'q14-pointer:b2',
    '|+\\rangle': 'q14-pointer:b3',
    p_i: 'q14-pointer:b4',
    E_i: 'q14-pointer:b4',

    // q14-povm
    '\\Pi_j': 'q14-povm:b2',
    '|\\psi_j\\rangle': 'q14-povm:b2',
    '|\\psi_0\\rangle': 'q14-povm:b2',
    '|\\psi_1\\rangle': 'q14-povm:b2',
    '|\\psi_2\\rangle': 'q14-povm:b2',
    E_j: 'q14-povm:b2',
    p_0: 'q14-povm:b2',
    E_0: 'q14-povm:b2',
    '\\langle\\cdot|\\cdot\\rangle': 'q14-povm:b2',
    p_1: 'q14-povm:b2',
    p_error: 'q14-povm:b2',
    p_correct: 'q14-povm',
    P_i: 'q14-povm:b1',
    P_j: 'q14-povm:b1',
    '\\delta_ij': 'q14-povm:b1',
    '\\dagger': 'q14-povm:b3',
    A_i: 'q14-povm:b3',
    A_j: 'q14-povm:b3',
    E_1: 'q14-povm:b3',
    U_i: 'q14-povm:b3',
    E_m: 'q14-povm',

    // q14-neumark
    A: 'q14-neumark:b1',
    B: 'q14-neumark:b1',
    H_A: 'q14-neumark:b1',
    H_B: 'q14-neumark:b1',
    U_AB: 'q14-neumark:b1',
    I_A: 'q14-neumark:b1',
    m: 'q14-neumark:b1',
    '\\otimes': 'q14-neumark:b1',
    '|\\psi_A\\rangle': 'q14-neumark:b1',
    '|\\psi_B\\rangle': 'q14-neumark:b1',
    '|m_B\\rangle': 'q14-neumark:b1',
    A_m: 'q14-neumark:b2',
    '|m\\rangle': 'q14-neumark:b2',
    '|\\psi\\rangle': 'q14-neumark:b2',
    p_m: 'q14-neumark:b2',
    V: 'q14-neumark:b3',
    E_2: 'q14-neumark:b3',

    // q14-usd
    '\\eta_1': 'q14-usd:b1',
    '\\eta_2': 'q14-usd:b1',
    c: 'q14-usd:b3',
    'P_': 'q14-usd:b1',
    q_1: 'q14-usd:b2',
    p_2: 'q14-usd:b2',
    q_2: 'q14-usd:b2',
    Q: 'q14-usd:b3',
    '\\Theta': 'q14-usd:b3',
    '\\eta_i': 'q14-usd:b3',

    // q14-min-error
    '\\Gamma': 'q14-min-error:b2',
    '\\rho_1': 'q14-min-error:b1',
    '\\rho_2': 'q14-min-error:b1',
    P_E: 'q14-min-error:b2',
    '\\lambda': 'q14-min-error:b2',
    '\\eta_\\min': 'q14-min-error:b4',

    // Try-it lines define the symbols they use in the line itself (the widgets label them the same way)
    'P_+': 'q14-pointer',
    'P_-': 'q14-pointer',
    '\\alpha': 'q14-povm',
    '|-\\rangle': 'q14-compare',

    // q14-compare
    'Q_': 'q14-compare:b1',
  },
  units: [
    {
      id: 'q14-pointer',
      story: Q14_STORY['q14-pointer'],
      review: Q14_REVIEW['q14-pointer'],
      claims: Q14_UNIT_CLAIMS_BY_ID['q14-pointer'],
      title: 'Reading a qubit through a meter',
      question: 'How do you actually measure a quantum system?',
      lecture: { pages: 'Bergou §5.2, pp. 78–80 (no lecture-notes source)', summary: 'Coupling a qubit to a meter and reading it; a soft meter gives a positive, non-projective outcome.' },
      books: [
        { source: 'bergou', where: '§5.2, pp. 78–80, Eqs. 5.1–5.8', adds: 'the von Neumann pointer model, the pointer shift and the standard-quantum-limit resolution.' },
        { source: 'nc', where: '§2.2.3, p. 85, Eq. 2.92', adds: 'measurement operators $\\{M_m\\}$ and the general probability rule.' },
      ],
      visual: { kind: 'operator-builder', props: { axis: 'z' }, tryThis: ['Pick z: $P_+ = |0\\rangle\\langle0|$ and $P_- = |1\\rangle\\langle1|$ are the sharp meter. The soft meter at $\\eta=\\tfrac12$ blends them, $E_+ = \\tfrac34P_+ + \\tfrac14P_-$.'] },
      clues: [],
      insight: 'A measurement couples the system to a meter, then reads the meter: a sharp meter projects, a blurry one gives a soft, positive outcome.',
      insightFormal: '$p_\\pm = \\mathrm{Tr}(E_\\pm\\rho)$, $E_\\pm = \\tfrac12(I \\pm \\eta Z)$: the projective rule made general, sharp at $\\eta=1$, unsharp below.',
      pitfalls: ['Thinking every measurement must be sharp — a meter can be blurred, giving positive outcomes that are not projectors.'],
      play: [
        {
          id: 'q14-po-soft',
          kind: 'choice',
          tier: 'warm-up',
          title: 'The soft meter on $|0\\rangle$',
          prompt: 'Feed $|0\\rangle$ into the soft $Z$ meter at sharpness $\\eta = \\tfrac12$. What is the chance of reading "up"?',
          options: [
            { text: '$0.75$', correct: true, why: 'The projective rule with $E_+$ for the projector: $\\tfrac12(1+\\tfrac12)$.' },
            { text: '$0.5$', correct: false, why: 'That is the chance on $|+\\rangle$, which leans neither way.' },
            { text: '$1$', correct: false, why: 'Only a sharp meter ($\\eta=1$) ever reaches certainty.' },
            { text: '$0.25$', correct: false, why: 'That is the chance of the OTHER outcome, down.' },
          ],
          hints: [{ text: 'Use the projective rule with $E_+$ for the projector.' }, { text: '$E_+ = \\mathrm{diag}(0.75, 0.25)$.' }, { text: 'Its top-left entry.' }],
          walkthrough: [{ text: '$p_+ = \\mathrm{Tr}(E_+|0\\rangle\\langle0|) = \\tfrac12(1 + \\tfrac12) = 0.75$.' }],
        },
        {
          id: 'q14-po-plus',
          kind: 'choice',
          tier: 'core',
          title: 'The soft meter on $|+\\rangle$',
          prompt: 'Feed $|+\\rangle$ into the same soft meter. What is the chance of "up"?',
          options: [
            { text: '$0.5$', correct: true, why: '$\\langle Z\\rangle = 0$ on $|+\\rangle$, so the $Z$ term drops out and the meter is a fair coin.' },
            { text: '$0.75$', correct: false, why: 'That is the chance on $|0\\rangle$, which leans up.' },
            { text: '$1$', correct: false, why: 'A soft meter never reaches certainty.' },
            { text: '$0$', correct: false, why: '$|+\\rangle$ leans neither up nor down, not all the way down.' },
          ],
          hints: [{ text: '$\\langle Z\\rangle = 0$ on $|+\\rangle$.' }, { text: '$p_+ = \\tfrac12(1 + \\eta\\langle Z\\rangle)$.' }, { text: 'The $Z$ term drops out.' }],
          walkthrough: [{ text: '$|+\\rangle$ leans neither way, so the soft meter is a fair coin: $0.5$.' }],
        },
      ],
    },
    {
      id: 'q14-povm',
      story: Q14_STORY['q14-povm'],
      review: Q14_REVIEW['q14-povm'],
      claims: Q14_UNIT_CLAIMS_BY_ID['q14-povm'],
      title: 'More answers than dimensions',
      question: 'Can a measurement have more outcomes than the space has dimensions?',
      lecture: { pages: 'Bergou §5.3, pp. 81–84 (no lecture-notes source)', summary: 'Drop orthogonality: a POVM is any set of positive operators adding to the identity, built from detection operators.' },
      books: [
        { source: 'bergou', where: '§5.3, pp. 81–84, Eq. 5.11; §5.4, pp. 86–87, Eqs. 5.24–5.25', adds: 'the POVM, detection operators and the trine ensemble.' },
        { source: 'nc', where: '§2.2.6, pp. 90–92, Eq. 2.117', adds: 'the POVM element $E_m \\equiv M_m^\\dagger M_m$.' },
      ],
      visual: { kind: 'bloch', props: { theta: 90, phi: 0, editable: true }, tryThis: ['Set θ = 120°, φ = 0°: that is $|\\psi_0\\rangle$. Read $\\alpha = \\langle0|\\psi_0\\rangle$, so $|\\alpha|^2 = 0.25 = |\\langle\\psi_2|\\psi_0\\rangle|^2$, the trine overlap that gives the $\\tfrac16$ error.'] },
      clues: [],
      insight: 'A POVM drops orthogonality: positive elements $E_i$ adding to $I$, with any number of outcomes — the trine gives three on a qubit.',
      insightFormal: '$\\sum_i E_i = I$, $E_i = A_i^\\dagger A_i \\ge 0$; the trine $E_j = \\tfrac23|\\psi_j\\rangle\\langle\\psi_j|$ gives three outcomes, $p_{\\text{correct}} = \\tfrac23$.',
      pitfalls: ['Thinking a qubit allows at most two outcomes — that is projective; a POVM can have any number.'],
      play: [
        {
          id: 'q14-pv-correct',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The trine’s correct outcome',
          prompt: "Feed the trine's $|\\psi_0\\rangle$ into the trine POVM. What is the chance of the correct outcome $0$?",
          answer: V.q14TrineCorrect,
          tolerance: 0.005,
          hints: [{ text: '$p_0 = \\langle\\psi_0|E_0|\\psi_0\\rangle$.' }, { text: '$E_0 = \\tfrac23|\\psi_0\\rangle\\langle\\psi_0|$.' }, { text: '$\\tfrac23 \\times 1$.' }],
          walkthrough: [{ text: '$p_0 = \\tfrac23|\\langle\\psi_0|\\psi_0\\rangle|^2 = \\tfrac23 = 0.667$.' }],
        },
        {
          id: 'q14-pv-error',
          kind: 'numeric',
          tier: 'core',
          title: 'The trine’s error chance',
          prompt: 'For that same input, what is the chance of a wrong outcome (say outcome $1$)?',
          answer: V.q14TrineError,
          tolerance: 0.005,
          hints: [{ text: '$p_1 = \\tfrac23|\\langle\\psi_1|\\psi_0\\rangle|^2$.' }, { text: 'The trine overlaps square to $\\tfrac14$.' }, { text: '$\\tfrac23 \\times \\tfrac14$.' }],
          walkthrough: [{ text: '$|\\langle\\psi_1|\\psi_0\\rangle|^2 = \\tfrac14$, so $p_{\\text{error}} = \\tfrac16 = 0.167$.' }],
        },
        {
          id: 'q14-pv-count',
          kind: 'choice',
          tier: 'core',
          title: 'Three outcomes on one qubit?',
          prompt: 'Can a single-qubit measurement have three distinct outcomes?',
          options: [
            { text: 'Yes — a POVM can, like the trine', correct: true, why: 'Three positive operators summing to $I$: a legitimate POVM.' },
            { text: 'No, never', correct: false, why: 'That holds only for a projective (sharp) measurement.' },
            { text: 'Only for mixed states', correct: false, why: "The outcome count is a property of the POVM, not of the input state." },
            { text: 'Only on two qubits', correct: false, why: 'The trine is a genuine one-qubit POVM.' },
          ],
          hints: [{ text: 'Drop orthogonality.' }, { text: 'Three positive operators summing to $I$.' }, { text: 'The trine.' }],
          walkthrough: [{ text: 'Projective caps outcomes at $2$, but the trine is a legitimate three-outcome POVM.' }],
        },
      ],
    },
    {
      id: 'q14-neumark',
      story: Q14_STORY['q14-neumark'],
      review: Q14_REVIEW['q14-neumark'],
      claims: Q14_UNIT_CLAIMS_BY_ID['q14-neumark'],
      title: 'Every POVM is projective upstairs',
      question: 'Is a POVM a real measurement, or just bookkeeping?',
      lecture: { pages: 'Bergou §5.4, pp. 84–89 (no lecture-notes source)', summary: "Neumark's theorem: a POVM is an ordinary sharp measurement on the system plus an ancilla." },
      books: [{ source: 'bergou', where: '§5.4, pp. 84–89, Eqs. 5.15–5.23, 5.26–5.31', adds: 'the ancilla construction and the trine’s qutrit dilation.' }],
      visual: { kind: 'operator-builder', props: { axis: 'z' }, tryThis: ['Check the readout $P_+ + P_- = I$: completeness is what makes $V^\\dagger V = I$.'] },
      clues: [],
      insight: "A POVM is real: add an ancilla, couple, measure the ancilla sharply. Every POVM is a sharp measurement upstairs.",
      insightFormal: '$V^\\dagger V = \\sum_m A_m^\\dagger A_m = I \\Rightarrow V$ extends to a unitary $U_{AB}$; the dilated measurement reproduces $\\mathrm{Tr}(E_j\\rho)$ exactly.',
      pitfalls: ['Thinking the POVM and its dilation give different chances — they agree by construction (that is the theorem).'],
      play: [
        {
          id: 'q14-nm-real',
          kind: 'choice',
          tier: 'warm-up',
          title: 'A real measurement?',
          prompt: 'Is a POVM a physically real measurement, or just bookkeeping?',
          options: [
            { text: 'Real — a sharp measurement on an ancilla (Neumark)', correct: true, why: '$V^\\dagger V = I$ extends to a unitary; reading the ancilla realises the POVM.' },
            { text: 'Just bookkeeping', correct: false, why: "Neumark's theorem gives it a genuine physical realisation." },
            { text: 'Only projective POVMs', correct: false, why: 'Every POVM, not only the projective special case, dilates.' },
            { text: 'Only for qubits', correct: false, why: 'The construction works at any dimension.' },
          ],
          hints: [{ text: 'Add an ancilla.' }, { text: 'Couple with one unitary.' }, { text: 'Measure the ancilla sharply.' }],
          walkthrough: [{ text: '$V^\\dagger V = I$ extends to a unitary; reading the ancilla realises the POVM.' }],
        },
        {
          id: 'q14-nm-dim',
          kind: 'numeric',
          tier: 'core',
          title: 'The trine’s ancilla dimension',
          prompt: 'The trine POVM has three outcomes on a qubit. What ancilla dimension realises it as a sharp measurement?',
          answer: V.q14NeumarkAncillaDim,
          tolerance: 0.001,
          hints: [{ text: 'One ancilla level per outcome.' }, { text: 'The trine has three outcomes.' }, { text: 'A qutrit.' }],
          walkthrough: [{ text: 'The ancilla dimension equals the number of POVM elements, here $3$.' }],
        },
        {
          id: 'q14-nm-match',
          kind: 'numeric',
          tier: 'core',
          title: 'The dilated chance',
          prompt: 'The dilated sharp measurement acts on $|0\\rangle$. What is the chance of the third outcome?',
          answer: V.q14NeumarkMatch2,
          tolerance: 0.005,
          hints: [{ text: 'It must match $\\mathrm{Tr}(E_2|0\\rangle\\langle0|)$.' }, { text: '$E_2 = \\tfrac23|0\\rangle\\langle0|$.' }, { text: '$\\tfrac23$.' }],
          walkthrough: [{ text: 'The lift reproduces the POVM chances, so the third outcome has chance $0.667$.' }],
        },
      ],
    },
    {
      id: 'q14-usd',
      story: Q14_STORY['q14-usd'],
      review: Q14_REVIEW['q14-usd'],
      claims: Q14_UNIT_CLAIMS_BY_ID['q14-usd'],
      title: 'Never wrong, sometimes unsure',
      question: 'Can you identify a state and never be mistaken?',
      lecture: { pages: 'Bergou §5.5.1, pp. 89–93 (no lecture-notes source)', summary: 'Unambiguous discrimination: never wrong, but with an inconclusive outcome when the states are not orthogonal.' },
      books: [
        { source: 'bergou', where: '§5.5.1, pp. 89–93, Eqs. 5.32–5.46, Fig. 5.1', adds: 'the never-err detectors, the inconclusive outcome and the success formula.' },
        { source: 'nc', where: '§2.2.6, pp. 91–92, Eqs. 2.118–2.120', adds: "the explicit never-err POVM for $|0\\rangle, |+\\rangle$." },
      ],
      visual: { kind: 'bloch', props: { theta: 45, phi: 0, editable: true }, tryThis: ['Lower θ from 90° toward 0°: the state’s overlap with $|0\\rangle$, $|\\alpha|$, grows. That overlap is the inconclusive rate.'] },
      clues: [],
      insight: "Non-orthogonal states cannot be unambiguously sorted with no failures; a third, 'don't know', outcome lets you never be wrong.",
      insightFormal: '$E_1+E_2+E_0=I$, $E_1|\\psi_2\\rangle=E_2|\\psi_1\\rangle=0$; equal-prior success $1-|\\langle\\psi_1|\\psi_2\\rangle|$.',
      pitfalls: ["Thinking the inconclusive outcome is an error — it is a refusal to answer, never a wrong answer."],
      play: [
        {
          id: 'q14-usd-succ',
          kind: 'numeric',
          tier: 'warm-up',
          title: "Bob's success rate",
          prompt: 'Bob must unambiguously tell $|0\\rangle$ from $|+\\rangle$ at even odds. How often can he succeed?',
          answer: V.q14UsdSucc,
          tolerance: 0.005,
          hints: [{ text: 'Success $= 1 - |\\langle\\psi_1|\\psi_2\\rangle|$.' }, { text: '$\\langle0|+\\rangle = 1/\\sqrt2$.' }, { text: '$1 - 0.707$.' }],
          walkthrough: [{ text: '$1 - 1/\\sqrt2 = 0.293$.' }],
        },
        {
          id: 'q14-usd-inc',
          kind: 'numeric',
          tier: 'core',
          title: "Bob's inconclusive rate",
          prompt: "For that same task, how often must Bob answer 'don't know'?",
          answer: V.q14UsdInconcl,
          tolerance: 0.005,
          hints: [{ text: 'Success + inconclusive $= 1$.' }, { text: '$1 - 0.293$.' }, { text: '$1/\\sqrt2$.' }],
          walkthrough: [{ text: 'Inconclusive $= 1 - 0.293 = 0.707$.' }],
        },
        {
          id: 'q14-usd-perfect',
          kind: 'choice',
          tier: 'core',
          title: 'A failure-free scheme?',
          prompt: 'Can any measurement unambiguously sort two non-orthogonal states with no failures at all?',
          options: [
            { text: 'No — that would force $\\langle\\psi_1|\\psi_2\\rangle = 0$', correct: true, why: 'Sandwiching $I$ between the states forces orthogonality.' },
            { text: 'Yes', correct: false, why: 'Perfect USD is possible only for orthogonal states.' },
            { text: 'Only pure states', correct: false, why: 'Purity is not what blocks a failure-free scheme; orthogonality is.' },
            { text: 'Only at equal priors', correct: false, why: 'The prior changes the success rate, not whether a failure-free scheme exists.' },
          ],
          hints: [{ text: 'Assume two never-err detectors adding to $I$.' }, { text: 'Sandwich $I$ between the states.' }, { text: 'You get $\\langle\\psi_1|\\psi_2\\rangle = 0$.' }],
          walkthrough: [{ text: 'Perfect USD forces orthogonality, which $|0\\rangle, |+\\rangle$ (overlap $0.707$) do not have.' }],
        },
      ],
    },
    {
      id: 'q14-min-error',
      story: Q14_STORY['q14-min-error'],
      review: Q14_REVIEW['q14-min-error'],
      claims: Q14_UNIT_CLAIMS_BY_ID['q14-min-error'],
      title: 'The fewest mistakes: Helstrom',
      question: 'If you must always guess, how often must you be wrong?',
      lecture: { pages: 'Bergou §5.5.2, pp. 94–98 (no lecture-notes source)', summary: 'Minimum-error discrimination: always conclusive, with the Helstrom bound as the least possible error rate.' },
      books: [{ source: 'bergou', where: '§5.5.2, pp. 94–98, Eqs. 5.49–5.61', adds: 'the Helstrom operator, the trace-norm bound and the pure-state formula.' }],
      visual: { kind: 'bloch', props: { theta: 45, phi: 0, editable: true }, tryThis: ['Set θ = 180°: $|1\\rangle$ is opposite $|0\\rangle$, overlap $0$, and the Helstrom error drops to $0$.'] },
      clues: [],
      insight: 'Minimum-error discrimination always answers; the fewest possible mistakes is the Helstrom bound, set by $\\Gamma = \\eta_2\\rho_2 - \\eta_1\\rho_1$.',
      insightFormal: '$P_E = \\tfrac12(1 - \\lVert\\eta_2\\rho_2 - \\eta_1\\rho_1\\rVert_1)$; pure, equal-prior form $\\tfrac12(1 - \\sqrt{1-|\\langle\\psi_1|\\psi_2\\rangle|^2})$.',
      pitfalls: ["Thinking a measurement always helps — if $\\Gamma$ has no negative eigenvalue, always guessing the likelier state is optimal."],
      play: [
        {
          id: 'q14-me-succ',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The best success rate',
          prompt: 'Guessing every time between $|0\\rangle$ and $|+\\rangle$ at even odds, what is the best chance of being right?',
          answer: V.q14HelstromSucc,
          tolerance: 0.005,
          hints: [{ text: 'Helstrom: $\\tfrac12(1 + \\sqrt{1 - c^2})$.' }, { text: '$c = 1/\\sqrt2$, so $c^2 = \\tfrac12$.' }, { text: '$\\tfrac12(1 + 0.707)$.' }],
          walkthrough: [{ text: '$\\tfrac12(1 + \\sqrt{1/2}) = 0.854$.' }],
        },
        {
          id: 'q14-me-err',
          kind: 'numeric',
          tier: 'core',
          title: 'The smallest error rate',
          prompt: 'What is the smallest error rate you can achieve?',
          answer: V.q14HelstromErr,
          tolerance: 0.005,
          hints: [{ text: 'Error $= 1 - $ success.' }, { text: '$\\tfrac12(1 - \\sqrt{1 - c^2})$.' }, { text: '$\\tfrac12(1 - 0.707)$.' }],
          walkthrough: [{ text: '$P_E = 0.146$.' }],
        },
        {
          id: 'q14-me-nomeas',
          kind: 'choice',
          tier: 'core',
          title: 'A skewed prior',
          prompt: 'If one of the two states is very likely, the best minimum-error strategy can be…',
          options: [
            { text: 'To always guess that state, with no measurement', correct: true, why: 'If $\\Gamma$ has no negative eigenvalue, $E_1=0$, $E_2=I$: no measurement helps.' },
            { text: 'To always measure', correct: false, why: 'A measurement adds nothing once $\\Gamma$ has only one sign.' },
            { text: 'To use the trine', correct: false, why: 'The trine is a different, three-outcome POVM for a different task.' },
            { text: 'To decline to answer', correct: false, why: 'Minimum-error discrimination never declines; that is unambiguous discrimination.' },
          ],
          hints: [{ text: 'Look at $\\Gamma = \\eta_2\\rho_2 - \\eta_1\\rho_1$.' }, { text: 'If it has no negative eigenvalue.' }, { text: '$E_1 = 0$.' }],
          walkthrough: [{ text: 'No negative eigenvalue $\\Rightarrow E_2 = I$, always guess $\\rho_2$, error $\\eta_{\\min}$.' }],
        },
      ],
    },
    {
      id: 'q14-compare',
      story: Q14_STORY['q14-compare'],
      review: Q14_REVIEW['q14-compare'],
      claims: Q14_UNIT_CLAIMS_BY_ID['q14-compare'],
      title: 'The price of certainty',
      question: 'Which is better — never wrong, or fewest wrong?',
      lecture: { pages: 'Bergou §5.5.1–5.5.2, pp. 92–98 (no lecture-notes source)', summary: 'The two discrimination strategies trade certainty for answered trials, with an exact bound linking them.' },
      books: [{ source: 'bergou', where: '§5.5.1–5.5.2, pp. 92–98, Eq. 5.61, Fig. 5.1', adds: 'the comparison of the two strategies and the exact trade-off bound.' }],
      visual: { kind: 'phase-dial', props: { theta: 90, rotations: false }, tryThis: ['Set the dial to $0°$ ($|+\\rangle$), then $180°$ ($|-\\rangle = (|0\\rangle - |1\\rangle)/\\sqrt2$): the two states are orthogonal, so both strategies succeed with certainty.'] },
      clues: [],
      insight: 'Unambiguous never errs but often fails; minimum-error always answers but sometimes errs — the error is at most half the inconclusive rate.',
      insightFormal: '$\\tfrac12(1+\\sqrt{1-c^2}) \\ge 1-c$ on $[0,1)$; $P_E \\le \\tfrac12 Q_{\\mathrm{opt}}$ (Eq. 5.61).',
      pitfalls: ['Thinking one strategy is simply "better" — they optimise different things (never-wrong vs fewest-wrong).'],
      play: [
        {
          id: 'q14-cp-which',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which wins per trial?',
          prompt: 'You may never be wrong, OR you must always answer. Which gives the higher chance of a correct answer per trial for $|0\\rangle, |+\\rangle$?',
          options: [
            { text: 'Minimum-error (always answer)', correct: true, why: '$0.854 > 0.293$: minimum-error spends mistakes to answer every time.' },
            { text: 'Unambiguous (never wrong)', correct: false, why: 'Its success rate, $0.293$, is lower per trial.' },
            { text: 'They are equal', correct: false, why: 'The two success rates differ substantially, $0.854$ vs $0.293$.' },
            { text: 'Depends only on the prior', correct: false, why: 'At these EQUAL priors minimum-error already wins; the comparison does not need a skewed prior.' },
          ],
          hints: [{ text: 'Compare $0.854$ and $0.293$.' }, { text: 'Minimum-error spends mistakes to answer every time.' }, { text: 'It dominates in $(0, 1)$.' }],
          walkthrough: [{ text: '$0.854 > 0.293$, so minimum-error gives more correct answers per trial.' }],
        },
        {
          id: 'q14-cp-tradeoff',
          kind: 'choice',
          tier: 'core',
          title: 'Checking the bound',
          prompt: 'Here the minimum error is $0.146$ and the inconclusive rate is $0.707$. Does $P_E \\le \\tfrac12 Q_{\\mathrm{opt}}$ hold?',
          options: [
            { text: 'Yes — $0.146 \\le 0.354$', correct: true, why: 'Half the inconclusive rate is $0.354$, which the error does not exceed.' },
            { text: 'No', correct: false, why: '$0.146$ is well under half of $0.707$.' },
            { text: 'Only at orthogonality', correct: false, why: 'The bound holds generally, not only at one special overlap.' },
            { text: 'Only for mixed states', correct: false, why: 'Both strategies here act on pure states; the bound is general.' },
          ],
          hints: [{ text: '$\\tfrac12 Q = \\tfrac12(0.707)$.' }, { text: '$= 0.354$.' }, { text: '$0.146 \\le 0.354$.' }],
          walkthrough: [{ text: "The Helstrom error is at most half the optimal USD failure (Bergou Eq. 5.61)." }],
        },
      ],
    },
  ],
  corrections: [
    {
      where: 'Bergou p. 86',
      says: 'An isometry extends to a unitary "e.g. by setting it to be the identity on the orthogonal complement".',
      shouldSay: "That particular extension is not unitary here: completing V's orthonormal columns to a full orthonormal basis (Gram–Schmidt) always works, but the identity on the complement does not, since V's own range already meets that complement.",
      check: () => V.q14NeumarkExtendGap > 0.5,
      source: 'book',
    },
  ],
}

export { claim, close }
