import type { Lecture } from '../schema'
import { Q17_REVIEW } from './Q17.review'
import { Q17_STORY, Q17_UNIT_CLAIMS_BY_ID } from './Q17.story'
import { ALPHA_DEG, V, claim, close, d } from './Q17.values'

// Physics 709, chapter Q17: "Searching an unsorted list: Grover" (Bergou §7.3, pp. 120-125; N&C §6.1-6.2, pp. 248-254, and §6.6,
// pp. 269-271), in both tracks. A `'books'`-phase chapter (the 709 notes do not reach it yet): every ramp beat is [B], every clue is
// [C], no [L] beat. Plan: docs/roles/proposals/P-Q17-story.md; rulings docs/roles/decisions/qc709-Q15Q17.md. Every number a learner
// sees is computed in Q17.values.ts, then asserted in keyed claims (content.test.tsx runs `holds`; claims.test.ts compares each key
// with numpy, pipeline/claims_qc709/q17.py). No sheet assigns any Q17 item (Bergou's end-of-chapter problems for Chapter 7 do not
// concern Grover's search), so every challenge below carries a full walkthrough. The four Corrections are each backed by an engine
// computation of the discrepancy (Q17.values.ts) and worded "our calculation finds ...".

export const Q17: Lecture = {
  id: 'Q17',
  number: 17,
  title: 'Searching an unsorted list: Grover',
  outcomes: [
    'Write the oracle as a sign flip, I − 2|x₀⟩⟨x₀|, and one Grover step as a circuit.',
    'Show that the search state stays in a real plane and find sin α = 1/√N.',
    'Prove that two reflections make a rotation by twice the angle between their lines.',
    'Predict the chance sin²((2k+1)α), pick the best number of steps and recognise overshoot.',
    'Explain why no algorithm can search with fewer than about √N questions.',
  ],
  prerequisites: ['qc-oracle-kickback', 'qc-quantum-parallelism', 'qc-registers', 'qc-f4-unitary'],
  // One definition site per symbol: the first beat that uses it in EITHER track (each track also defines it in its own words there).
  symbols: {
    // q17-oracle
    x_0: 'q17-oracle:b1',
    n: 'q17-oracle:b1',
    N: 'q17-oracle:b1',
    f: 'q17-oracle:b1',
    '|\\cdot\\rangle': 'q17-oracle:b2',
    '|x\\rangle': 'q17-oracle:b2',
    '|x_0\\rangle': 'q17-oracle:b2',
    '\\langle\\cdot|': 'q17-oracle:b2',
    U_f: 'q17-oracle:b2',
    I: 'q17-oracle:b2',
    '|0\\rangle': 'q17-oracle:b3',
    U_0: 'q17-oracle:b3',
    U_H: 'q17-oracle:b3',
    H: 'q17-oracle:b3',
    '\\otimes': 'q17-oracle:b3',
    '|w_0\\rangle': 'q17-oracle:b3',
    Q: 'q17-oracle:b3',
    // q17-plane
    '\\langle\\cdot|\\cdot\\rangle': 'q17-plane:b1',
    '|x_0^\\perp\\rangle': 'q17-plane:b1',
    '\\alpha': 'q17-plane:b1',
    '\\theta': 'q17-plane:b1',
    U_w_0: 'q17-plane:b2',
    S: 'q17-plane:b2',
    c_1: 'q17-plane:b2',
    c_2: 'q17-plane:b2',
    k: 'q17-plane:b4',
    // q17-two-reflections
    'R_x_0^\\perp': 'q17-two-reflections:b1',
    '|w_0^\\perp\\rangle': 'q17-two-reflections:b2',
    D: 'q17-two-reflections:b2',
    R_w_0: 'q17-two-reflections:b2',
    Z: 'q17-two-reflections:b2',
    X: 'q17-two-reflections:b2',
    M_1: 'q17-two-reflections:b3',
    M_2: 'q17-two-reflections:b3',
    R: 'q17-two-reflections:b3',
    v_1: 'q17-two-reflections:b3',
    v_2: 'q17-two-reflections:b3',
    'R_\\theta': 'q17-two-reflections:b3',
    // q17-iterate
    P_k: 'q17-iterate:b1',
    a_x: 'q17-iterate:b2',
    '\\bar a': 'q17-iterate:b2',
    '\\pi': 'q17-iterate:b3',
    '\\bar n': 'q17-iterate:b3',
    P_fail: 'q17-iterate:b3',
    M: 'q17-iterate:b4',
    '|11\\rangle': 'q17-iterate:b4',
    // q17-optimal
    '|\\psi_k^x\\rangle': 'q17-optimal:b1',
    '|\\psi_0\\rangle': 'q17-optimal:b1',
    '|\\psi_k\\rangle': 'q17-optimal:b1',
    '\\psi_k': 'q17-optimal:b1',
    U_k: 'q17-optimal:b1',
    U_x: 'q17-optimal:b1',
    U_1: 'q17-optimal:b1',
    D_k: 'q17-optimal:b1',
    '|\\psi_2\\rangle': 'q17-optimal:b1',
    'D_k+1': 'q17-optimal:b2',
    D_1: 'q17-optimal:b2',
    D_2: 'q17-optimal:b2',
    D_3: 'q17-optimal:b2',
    '|\\psi_2^x\\rangle': 'q17-optimal:b2',
  },
  symbolsFormal: {},
  units: [
    {
      id: 'q17-oracle',
      story: Q17_STORY['q17-oracle'],
      review: Q17_REVIEW['q17-oracle'],
      claims: Q17_UNIT_CLAIMS_BY_ID['q17-oracle'],
      title: 'A black box that marks one item',
      question: 'How does a quantum computer ask “is this the one?” without opening the box?',
      lecture: {
        pages: 'Bergou §7.3, pp. 120–121; N&C §6.1.1–6.1.2, pp. 248–251 (no lecture-notes source)',
        summary: 'The search problem, the marking oracle as a sign flip, and one Grover step drawn as a circuit.',
      },
      books: [
        { source: 'bergou', where: '§7.3, pp. 120–121, Eqs. 7.13–7.14, Fig. 7.2', adds: 'the search problem, the marking oracle, and the operators that make up one Grover step.' },
        { source: 'nc', where: '§6.1.1–6.1.2, pp. 248–251, Eqs. 6.1–6.6', adds: 'the oracle as a sign flip, and the four-part Grover iteration with its phase-shift step.' },
      ],
      visual: {
        kind: 'bloch',
        props: { theta: 90, phi: 0, editable: false, measure: 'z', rotations: true, rotationAngles: [180] },
        tryThis: [
          'One wire is the smallest search: two strings, and |+⟩ is their even mix. Press the Rz(180°) button. The ⟨Sx⟩ line goes from 0.5 ħ to −0.5 ħ, so |+⟩ has become |−⟩ up to an overall phase: exactly what the mark does when the marked string is 1.',
          'The z bars read +z 50.0% and −z 50.0% before and after. Marking alone changes no chance.',
        ],
      },
      clues: [],
      insight: 'The oracle marks the item with a sign, and a sign changes no chance. One Grover step is the mark followed by three moves that turn that sign into amplitude.',
      insightFormal: '$U_f = I - 2|x_0\\rangle\\langle x_0|$ is invisible to one reading ($|\\langle x|U_f|w_0\\rangle|^2 = 1/N$); $Q = -U_HU_0U_HU_f$ converts the sign into amplitude.',
      pitfalls: ['Expecting the mark alone to make the marked string more likely: it changes a sign, not a chance.'],
      play: [
        {
          id: 'q17-or-blind',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Chance after the mark alone',
          prompt: 'Eight strings, marked string $101$. Start from the even mix $|w_0\\rangle$ and apply the oracle once. What is the chance of reading $101$?',
          answer: V.q17Blind,
          tolerance: 0.005,
          hints: [{ text: 'A sign flip changes the amplitude’s sign, not its size.' }, { text: 'Before the mark all eight strings had the same chance.' }, { text: 'Eight equal chances add to 1.' }],
          walkthrough: [{ text: 'The oracle flips the sign of the amplitude of $101$, and a chance is the amplitude squared, so every string keeps its chance, $1/8 = 0.125$.' }],
        },
        {
          id: 'q17-or-mean',
          kind: 'numeric',
          tier: 'core',
          title: 'The average after the mark',
          prompt: 'After the first mark, what is the average of the eight amplitudes?',
          answer: V.q17MeanAfterOracle,
          tolerance: 0.005,
          hints: [{ text: 'Seven amplitudes are $+0.3536$ and one is $-0.3536$.' }, { text: 'Add them: seven positives minus one leaves six.' }, { text: 'Divide by eight.' }],
          walkthrough: [{ text: `$(7 - 1) \\times ${d(V.q17Bar, 4)} / 8 = ${d(V.q17MeanAfterOracle, 4)}$.` }],
        },
        {
          id: 'q17-or-sign',
          kind: 'choice',
          tier: 'core',
          title: 'Does the mark help yet?',
          prompt: 'After the oracle alone acts on $|w_0\\rangle$, what is the chance of reading the marked string?',
          options: [
            { text: `$${d(V.q17Blind, 3)}$, unchanged`, correct: true, why: 'The oracle changes a sign, and a sign changes no chance.' },
            { text: `$${d(V.q17P1, 3)}$, as after a full step`, correct: false, why: 'That needs the other three moves of the step, which turn the sign into amplitude.' },
            { text: '$1$', correct: false, why: 'One mark cannot make the answer certain.' },
            { text: '$0$', correct: false, why: 'The marked string keeps its full chance; the sign of its amplitude is all that changed.' },
          ],
          hints: [{ text: 'What does the oracle change about the marked amplitude?' }, { text: 'A chance is the amplitude squared.' }, { text: 'Squaring removes a sign.' }],
          walkthrough: [{ text: `The marked amplitude goes from $+${d(V.q17Bar, 4)}$ to $-${d(V.q17Bar, 4)}$; squared, both give $${d(V.q17Blind, 3)}$.` }],
        },
      ],
    },
    {
      id: 'q17-plane',
      story: Q17_STORY['q17-plane'],
      review: Q17_REVIEW['q17-plane'],
      claims: Q17_UNIT_CLAIMS_BY_ID['q17-plane'],
      title: 'The whole search in one flat plane',
      question: 'Why can eight dimensions be drawn on one page?',
      lecture: {
        pages: 'Bergou §7.3, pp. 121–123 (no lecture-notes source)',
        summary: 'The search stays in a real plane spanned by the marked string and the even mix of the rest. The start sits at angle α, where sin α = 1/√N.',
      },
      books: [
        { source: 'bergou', where: '§7.3, pp. 121–123, Eqs. 7.15 and 7.17', adds: 'the invariant plane, its two axes, and the start state written in them.' },
        { source: 'nc', where: '§6.1.3, pp. 252–253, Eqs. 6.8–6.10', adds: 'the same two axes under the names |α⟩ and |β⟩, with the angle written θ/2.' },
      ],
      visual: {
        kind: 'projector',
        props: { state: ALPHA_DEG, basis: 0, editableBasis: false },
        tryThis: [
          'This real plane is the Projector’s own: read its right axis, |+z⟩, as the across axis |x₀⊥⟩ and its up axis, |−z⟩, as the marked axis |x₀⟩. The arrow starts at 20.7°, the start |w₀⟩ for eight strings: the ⟨−z|ψ⟩ row reads 0.354 and P = 12.5%.',
          'The note under the picture says angles in this plane are half the sphere’s. Grover’s plane has no sphere behind it: its angles are exactly these state angles.',
        ],
      },
      clues: [],
      insight: 'The whole eight-dimensional search lives in one flat real plane, with the start at angle α where sin α = 1/√N. Angles in it are true state angles.',
      insightFormal: '$Q$ maps $S = \\mathrm{span}\\{|w_0\\rangle, |x_0\\rangle\\}$ into itself with real coefficients; $|w_0\\rangle = \\sin\\alpha|x_0\\rangle + \\cos\\alpha|x_0^\\perp\\rangle$ with $\\sin\\alpha = 1/\\sqrt N$.',
      pitfalls: ['Drawing this plane as a Bloch sphere: there states at right angles sit opposite each other, here they sit 90° apart.'],
      play: [
        {
          id: 'q17-pl-sin',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The start’s shadow for sixteen strings',
          prompt: 'For $N = 16$, what is $\\sin\\alpha$?',
          answer: V.q17SinN16,
          tolerance: 0.005,
          hints: [{ text: 'The rule is $\\sin\\alpha = 1/\\sqrt N$.' }, { text: 'The square root of $16$ is a whole number.' }, { text: 'One over four.' }],
          walkthrough: [{ text: '$\\sin\\alpha = 1/\\sqrt{16} = 1/4 = 0.25$.' }],
        },
        {
          id: 'q17-pl-alpha',
          kind: 'numeric',
          tier: 'core',
          title: 'The start’s angle for eight strings',
          prompt: 'For $N = 8$, how large is $\\alpha$, in degrees?',
          answer: V.q17AlphaDeg,
          tolerance: 0.05,
          unit: '°',
          hints: [{ text: '$\\sin\\alpha = 1/\\sqrt8$.' }, { text: 'Use the inverse sine on a calculator.' }, { text: 'The value is $0.3536$; its inverse sine is a little over $20$.' }],
          walkthrough: [{ text: `$\\sin\\alpha = ${d(V.q17SinA, 4)}$, so $\\alpha = ${d(V.q17AlphaDeg, 2)}°$.` }],
        },
        {
          id: 'q17-pl-perp',
          kind: 'choice',
          tier: 'core',
          title: 'Is the printed vector at right angles?',
          prompt:
            'Bergou writes the across axis as $(|w_0\\rangle + \\langle x_0|w_0\\rangle|x_0\\rangle)/\\sqrt{1 - 1/N}$. Is this [[orthogonal|orthogonal]] to $|x_0\\rangle$ for $N = 8$?',
          options: [
            { text: `No: its overlap with $|x_0\\rangle$ is $${d(V.q17BookPerpOverlap, 3)}$, and the sign must be a minus`, correct: true, why: 'With a plus the overlap is $2/\\sqrt7$; with a minus it is exactly $0$.' },
            { text: 'Yes, it is at right angles', correct: false, why: 'The plus sign adds the $|x_0\\rangle$ part instead of removing it.' },
            { text: 'Yes, but only for $N = 8$', correct: false, why: 'The overlap is nonzero for every $N$.' },
            { text: 'No, because $|w_0\\rangle$ has the wrong length', correct: false, why: '$|w_0\\rangle$ has length 1; the slip is the sign.' },
          ],
          hints: [{ text: 'Take the overlap with $|x_0\\rangle$ and use $\\langle x_0|w_0\\rangle = 1/\\sqrt N$.' }, { text: 'With a plus, the two terms $1/\\sqrt N$ add.' }, { text: 'The result is $2/\\sqrt N$ over $\\sqrt{1 - 1/N}$, not zero.' }],
          walkthrough: [{ text: `The overlap is $(1/\\sqrt8 + 1/\\sqrt8)/\\sqrt{7/8} = ${d(V.q17BookPerpOverlap, 3)}$. A minus sign makes it $0$.` }],
        },
      ],
    },
    {
      id: 'q17-two-reflections',
      story: Q17_STORY['q17-two-reflections'],
      review: Q17_REVIEW['q17-two-reflections'],
      claims: Q17_UNIT_CLAIMS_BY_ID['q17-two-reflections'],
      title: 'Two mirrors make a turn',
      question: 'What does one Grover step do to the arrow?',
      lecture: {
        pages: 'Bergou §7.3, pp. 121–123 (no lecture-notes source)',
        summary: 'The mark is a mirror along the across axis; the rest of the step is a mirror through |w₀⟩. Two mirrors make a rotation by twice the angle between them.',
      },
      books: [
        { source: 'bergou', where: '§7.3, pp. 121–123, Eq. 7.16, Theorem 1, Figs. 7.3–7.5', adds: 'the step as two reflections and the proof that two reflections make a rotation.' },
        { source: 'nc', where: '§6.1.3, pp. 252–253, Eqs. 6.11–6.13, Fig. 6.3', adds: 'the same picture drawn with the oracle as a reflection and the inversion about the mean as the second one.' },
      ],
      visual: {
        kind: 'operator-action',
        props: { a: V.q17Cos2a, b: V.q17Sin2a, d: -V.q17Cos2a },
        tryThis: [
          'This matrix is the mirror along |w₀⟩’s line for eight strings: a = 0.75, b = 0.66 and d = −0.75 (to two places). Tick “show eigen-directions”: the eigenvalues read 1 and −1, one line the mirror keeps and one it flips, at right angles.',
          'Press σz: the matrix becomes diag(1, −1), the mirror along the across axis that the mark makes.',
        ],
      },
      clues: [],
      insight: 'The mark and the rest of the step are two mirrors. Two mirrors that meet at angle α turn everything by 2α, so one Grover step is a turn by 2α.',
      insightFormal: '$Q = D\\,U_f = R_{w_0}R_{x_0^\\perp} = R(2\\alpha)$ on $S$ (Theorem 1); the reversed order is $R(-2\\alpha)$.',
      pitfalls: ['Thinking one step turns the arrow by α, the angle between the mirrors, instead of 2α.'],
      play: [
        {
          id: 'q17-tr-step',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The turn of one step',
          prompt: 'For $N = 8$, by how many degrees does one Grover step turn the arrow?',
          answer: V.q17TwoAlphaDeg,
          tolerance: 0.05,
          unit: '°',
          hints: [{ text: 'One step turns by twice the angle $\\alpha$.' }, { text: 'For $N = 8$, $\\alpha = 20.70°$.' }, { text: 'Double it.' }],
          walkthrough: [{ text: `$2\\alpha = 2 \\times ${d(V.q17AlphaDeg, 2)}° = ${d(V.q17TwoAlphaDeg, 2)}°$.` }],
        },
        {
          id: 'q17-tr-thirty',
          kind: 'numeric',
          tier: 'core',
          title: 'Two mirrors thirty degrees apart',
          prompt: 'Two mirror lines meet at $30°$. Used one after the other, by how many degrees do they turn every vector?',
          answer: V.q17TrThirty,
          tolerance: 0.01,
          unit: '°',
          hints: [{ text: 'Two mirrors that meet at angle $\\alpha$ turn everything by $2\\alpha$.' }, { text: 'Here $\\alpha = 30°$.' }, { text: 'Double it.' }],
          walkthrough: [{ text: 'By Theorem 1 the turn is twice the angle between the mirrors: $2 \\times 30° = 60°$.' }],
        },
        {
          id: 'q17-tr-order',
          kind: 'choice',
          tier: 'core',
          title: 'The mirrors in the other order',
          prompt: 'Use the line through $|w_0\\rangle$ first, then the across axis. What happens to the arrow?',
          options: [
            { text: 'It turns by $-2\\alpha$, the other way', correct: true, why: 'The reversed product is the inverse turn: mirrors do not commute.' },
            { text: 'It turns by $2\\alpha$, as before', correct: false, why: 'Swapping the order swaps the direction of the turn.' },
            { text: 'It does not turn at all', correct: false, why: 'Two mirrors always make a turn by twice their angle, in one direction or the other.' },
            { text: 'It turns by $\\alpha$', correct: false, why: 'Two mirrors turn by $2\\alpha$, never by $\\alpha$.' },
          ],
          hints: [{ text: 'Write the product of the two tables in the reverse order.' }, { text: 'The first order gave a turn by $+2\\alpha$.' }, { text: 'The reverse is the inverse of that turn.' }],
          walkthrough: [{ text: `The reversed product has entries $${d(V.q17Cos2a, 2)}$, $${d(V.q17Sin2a, 2)}$ over $-${d(V.q17Sin2a, 2)}$, $${d(V.q17Cos2a, 2)}$: a turn by $-2\\alpha$.` }],
        },
      ],
    },
    {
      id: 'q17-iterate',
      story: Q17_STORY['q17-iterate'],
      review: Q17_REVIEW['q17-iterate'],
      claims: Q17_UNIT_CLAIMS_BY_ID['q17-iterate'],
      title: 'Turn until you reach the target',
      question: 'How many steps, and what if you overshoot?',
      lecture: {
        pages: 'Bergou §7.3, p. 123; N&C §6.1.3–6.1.4, pp. 252–254 (no lecture-notes source)',
        summary: 'After k steps the arrow is at (2k+1)α and the chance is its sine squared. Stop at the closest whole number of steps; more steps overshoot.',
      },
      books: [
        { source: 'bergou', where: '§7.3, p. 123, Eqs. 7.17–7.18', adds: 'the state after n steps, the best number of steps and the chance of a miss.' },
        { source: 'nc', where: '§6.1.3–6.1.4, pp. 252–254, Eqs. 6.7, 6.12–6.17', adds: 'the inversion about the mean, the closest-integer rule for the number of steps, and the case of several marked items.' },
      ],
      visual: {
        kind: 'projector',
        props: { state: 3 * ALPHA_DEG, basis: 0, editableBasis: false },
        tryThis: [
          'One step for eight strings puts the arrow at 3α = 62.1°: the ⟨−z|ψ⟩ row reads 0.884 and P = 78.1%.',
          'Drag the arrow up until that row reads about 94.5%: that is two steps, at about 103.5°. Drag on to about 145° (three steps): the row falls to about 33%.',
        ],
      },
      clues: [],
      insight: 'After k steps the chance of the marked string is sin²((2k+1)α). Stop at the whole number of steps that leaves the arrow nearest vertical; one step too many overshoots.',
      insightFormal: '$P_k = \\sin^2((2k+1)\\alpha)$; $k^* = \\mathrm{CI}((\\pi - 2\\alpha)/(4\\alpha))$ with miss chance at most $1/N$; past $k^*$ the chance falls.',
      pitfalls: ['Thinking more steps always mean a better chance: the arrow keeps turning past vertical.'],
      play: [
        {
          id: 'q17-it-one',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'After one step',
          prompt: 'For $N = 8$, what is the chance of reading $x_0$ after one Grover step?',
          answer: V.q17P1,
          tolerance: 0.005,
          hints: [{ text: 'After $k$ steps the chance is $\\sin^2((2k+1)\\alpha)$.' }, { text: 'For $k = 1$ the angle is $3\\alpha = 62.11°$.' }, { text: 'Square its sine, $0.8839$.' }],
          walkthrough: [{ text: `$\\sin^2(3\\alpha) = ${d(V.q17InvMarked, 4)}^2 = ${d(V.q17P1, 4)}$.` }],
        },
        {
          id: 'q17-it-kopt',
          kind: 'numeric',
          tier: 'core',
          title: 'The best number of steps for 1024 strings',
          prompt: 'For $N = 1024$, how many steps $k^*$ leave the arrow nearest to vertical?',
          answer: V.q17Kopt1024,
          tolerance: 0,
          hints: [{ text: 'The steps wanted are $(\\pi - 2\\alpha)/(4\\alpha)$, with $\\sin\\alpha = 1/32$.' }, { text: 'For large $N$ this is about $\\tfrac\\pi4\\sqrt N$ minus a little.' }, { text: 'Round to the closest whole number.' }],
          walkthrough: [{ text: `$\\alpha = 1/32$ radians (about $1.79°$), so the steps wanted come to about $24.6$; the closest whole number is $${V.q17Kopt1024}$.` }],
        },
        {
          id: 'q17-it-over',
          kind: 'numeric',
          tier: 'stretch',
          title: 'One step too many',
          prompt: 'For $N = 8$, what is the chance of reading $x_0$ after three steps?',
          answer: V.q17P3,
          tolerance: 0.005,
          hints: [{ text: 'After $k$ steps the angle is $(2k+1)\\alpha$.' }, { text: 'For $k = 3$ the angle is $7\\alpha = 144.93°$, past vertical.' }, { text: 'Square the sine of that angle.' }],
          walkthrough: [{ text: `$\\sin^2(7\\alpha) = ${d(V.q17P3, 4)}$, lower than after two steps: the arrow overshot.` }],
        },
      ],
    },
    {
      id: 'q17-optimal',
      story: Q17_STORY['q17-optimal'],
      review: Q17_REVIEW['q17-optimal'],
      claims: Q17_UNIT_CLAIMS_BY_ID['q17-optimal'],
      title: 'No algorithm can do better',
      question: 'Could a cleverer algorithm beat √N questions?',
      lecture: {
        pages: 'Bergou §7.3, pp. 124–125; N&C §6.6, pp. 269–271 (no lecture-notes source)',
        summary: 'Compare any search algorithm with the same steps and no oracle. Each query adds a little to the difference and success needs a lot, so √N queries are needed.',
      },
      books: [
        { source: 'bergou', where: '§7.3, pp. 124–125, Eqs. 7.19–7.29', adds: 'the argument that no algorithm needs fewer than order √N queries.' },
        { source: 'nc', where: '§6.6, pp. 269–271', adds: 'the same optimality result, proved with the same comparison of runs with and without the oracle.' },
      ],
      visual: {
        kind: 'projector',
        props: { state: 5 * ALPHA_DEG, basis: 0, editableBasis: false },
        tryThis: [
          'Two steps for eight strings leave the arrow at 5α = 103.5°: the ⟨−z|ψ⟩ row reads P = 94.5%.',
          'Drag it to straight up, 90°: the row reads P = 100.0%. Grover’s whole job is this quarter turn, made in steps of 2α = 41.4°.',
        ],
      },
      clues: [],
      insight: 'Each query moves the state only a little, but success needs a big difference. So any search needs about √N queries, and Grover’s method is optimal.',
      insightFormal: '$D_k \\le 4k^2$ and success above one half forces $D_k \\ge N(2-\\sqrt2) - 2\\sqrt N$, so $k$ is at least of order $\\sqrt N$ (Eq. 7.29).',
      pitfalls: ['Reading the bound’s smaller number as Grover being far from optimal: the bound is for success above one half, and both grow like √N.'],
      play: [
        {
          id: 'q17-op-bound',
          kind: 'numeric',
          tier: 'core',
          title: 'The lower bound for 1024 strings',
          prompt: 'Evaluate Bergou’s Eq. 7.29 for $N = 1024$: the fewest queries any algorithm can use, as a real number.',
          answer: V.q17Bbbv1024,
          tolerance: 0.01,
          hints: [{ text: 'Put $4k^2$ above $N(2-\\sqrt2) - 2\\sqrt N$ and solve for $k$.' }, { text: 'For $N = 1024$: $1024 \\times 0.5858 - 64 = 535.8$.' }, { text: 'Divide by $4$ and take the square root.' }],
          walkthrough: [{ text: `$4k^2 \\ge 535.8$, so $k \\ge \\sqrt{133.96} = ${d(V.q17Bbbv1024, 2)}$.` }],
        },
        {
          id: 'q17-op-tight',
          kind: 'choice',
          tier: 'core',
          title: 'Is Grover optimal?',
          prompt: `For $N = 1024$ the bound asks for $${d(V.q17Bbbv1024, 2)}$ queries and Grover uses $${V.q17Kopt1024}$. Is Grover’s method optimal?`,
          options: [
            { text: 'Yes, in how the cost grows: both are of order $\\sqrt N$', correct: true, why: 'The bound is for success above one half, and Grover after $12$ steps is just below that.' },
            { text: 'No, it uses twice as many queries as needed', correct: false, why: 'A constant factor is not what the bound controls, and the bound targets a lower success than Grover’s $0.9995$.' },
            { text: 'No, a better algorithm exists that needs only about $\\log N$ queries', correct: false, why: 'The bound rules that out: every algorithm needs about $\\sqrt N$.' },
            { text: 'It cannot be said', correct: false, why: 'The two bounds have the same growth, which settles it.' },
          ],
          hints: [{ text: 'Compare how both numbers grow with $N$, not their values at one $N$.' }, { text: 'The bound asks for success above one half; Grover aims near $1$.' }, { text: 'Both scale like $\\sqrt N$.' }],
          walkthrough: [{ text: `Both are of order $\\sqrt N$. At $N = 1024$ Grover reaches only $${d(V.q17P12of1024, 4)}$ after $12$ steps, so the bound is nearly tight at its own target.` }],
        },
      ],
    },
  ],
  corrections: [
    {
      where: 'Bergou p. 121, Eq. 7.15',
      says: 'Second line: c₁|w₀⟩ + (2/√N + c₂)(|x₀⟩ − (2/√N)|x₀⟩). The factor lacks c₁, and the last ket is |x₀⟩.',
      shouldSay: `Our calculation finds that the last ket must be |w₀⟩ and the factor 2c₁/√N + c₂: for eight strings and the start |w₀⟩ the printed right side misses Q|ψ⟩ by ${d(V.q17E1Printed, 3)} in length, while c₁|w₀⟩ + (2c₁/√N + c₂)(|x₀⟩ − (2/√N)|w₀⟩) matches it to rounding.`,
      check: () => V.q17E1Printed > 0.5 && V.q17E1Corrected < 1e-9,
      source: 'book',
    },
    {
      where: 'Bergou pp. 121–122',
      says: 'The vectors |x₀⊥⟩ and |w₀⊥⟩ are written with a plus sign, and −U_f is set equal to −(I − 2|w₀⟩⟨w₀|).',
      shouldSay: `Our calculation finds that both vectors need a minus sign: as printed, |x₀⊥⟩ overlaps |x₀⟩ by ${d(V.q17BookPerpOverlap, 3)} for eight strings instead of 0, and by symmetry so does |w₀⊥⟩ with |w₀⟩. And −(I − 2|w₀⟩⟨w₀|) is −U_w₀, not −U_f: the two matrices differ by ${d(V.q17E2UfGap, 2)} in their largest entry.`,
      check: () => V.q17BookPerpOverlap > 0.5 && V.q17PerpTrueOverlap < 1e-9 && V.q17E2UfGap > 1,
      source: 'book',
    },
    {
      where: 'Bergou p. 123',
      says: 'cos α = (1 − 1/√N)^½, and the chance of measuring x ≠ x₀ is cos²α at n̄, which is O(1/N²).',
      shouldSay: `Our calculation finds cos α = (1 − 1/N)^½: for eight strings the engine’s own overlap gives ${d(V.q17CosA, 4)}, not the printed form’s ${d(V.q17CosPrinted, 4)}. And cos²α at n̄ is the chance of ANY wrong string, of order 1/N (${d(V.q17Fail8, 4)} for eight strings, below 1/N = ${d(V.q17FailBound8, 3)}); it is each single wrong string’s share that is of order 1/N² (${d(V.q17MissPerItem, 4)} = 1/128).`,
      check: () =>
        close(V.q17CosA, Math.sqrt(7 / 8), 1e-9) && Math.abs(V.q17CosPrinted - V.q17CosA) > 0.1 && V.q17Fail8 > 5 * V.q17MissPerItem && V.q17Fail8 <= V.q17FailBound8,
      source: 'book',
    },
    {
      where: 'Bergou p. 124, Eq. 7.22',
      says: 'The middle line ends with + |⟨x|ψₖ⟩|²: the last term carries no factor 4.',
      shouldSay: `Our calculation finds the weight must be 4, because ‖(Uₓ − I)ψₖ‖² = 4|⟨x|ψₖ⟩|². With the printed weight 1 the line fails at k = 0 for eight strings: its right side is ${d(V.q17StepBoundPrinted, 0)} while D₁ = ${d(V.q17D1, 0)}; with weight 4 it is ${d(V.q17StepBoundTrue, 0)}, tight. The next line (+ 4) and the conclusion Dₖ ≤ 4k² are unaffected.`,
      check: () => close(V.q17StepBoundPrinted, 1, 1e-9) && close(V.q17StepBoundTrue, 4, 1e-9) && V.q17D1 > V.q17StepBoundPrinted + 1,
      source: 'book',
    },
  ],
}

export { claim, close }
