/**
 * Chapter Q2 glossary (Physics 709; P-Q2-story §5), merged into the lazy course pack by file name (pack.ts). Every
 * entry has a Ground-up sentence (`gloss`, ≤ 25 words) and a Formal one (`formal`, ≤ 40), paraphrased; `bridge`
 * names a Spin Lab unit (content/qc709/bridges.ts) that teaches the same idea. Ids start `qc-`.
 * Reused, not redefined here: `qc-amplitude` (F1), `qc-born-rule`, `qc-inner-product`, `qc-bra`, `qc-zero-vector` (Q1).
 */
import type { GlossEntry } from '../schema'

export const GLOSSARY: GlossEntry[] = [
  /* q2-basis */
  {
    id: 'qc-linearly-independent',
    term: 'linearly independent',
    gloss: 'Arrows none of which can be built from the others by scaling and adding.',
    formal: 'A list is LI when $\\sum_i c_i|\\alpha_i\\rangle = 0$ forces every $c_i = 0$; otherwise it is LD.',
    first: 'q2-basis:b1',
    bridge: 'qc-l4-basis',
  },
  {
    id: 'qc-vector-space-fn',
    term: 'vector space $V^n(F)$',
    gloss: 'A set of arrows, with numbers from a field F, that can be scaled and added.',
    formal: '$V^n(F)$: $n$-dimensional over the field $F$; a qubit’s $V^2(\\mathbb{C})$ has a real 2D slice, this plane.',
    first: 'q2-basis:b2',
    introduces: 'space',
  },
  {
    id: 'qc-dimension',
    term: 'dimension',
    gloss: 'The largest number of independent arrows a space holds; 2 for a qubit.',
    formal: 'A vector space $V(F)$ is $n$-dimensional when its largest LI set has $n$ members.',
    first: 'q2-basis:b2',
    bridge: 'qc-l2-three-bases',
  },
  {
    id: 'qc-basis',
    term: 'basis',
    gloss: 'Independent arrows from which every vector is built in exactly one way.',
    formal: 'An LI spanning list of $V^n$; the expansion of any $|\\alpha\\rangle \\in V^n$ in it is unique (Axler 2.28).',
    first: 'q2-basis:b3',
    bridge: 'qc-l4-basis',
  },
  {
    id: 'qc-component',
    term: 'component',
    gloss: 'How much of one basis arrow a vector contains.',
    formal: 'The number $c_i$ in $|\\alpha\\rangle = \\sum_i c_i|e_i\\rangle$; in an ON basis $c_i = \\langle e_i|\\alpha\\rangle$.',
    first: 'q2-basis:b3',
    bridge: 'qc-l2-inner-product',
  },
  {
    id: 'qc-component-column',
    term: 'components as a column $(c_1, c_2)$',
    gloss: 'A vector’s components, written one under the other instead of in a sum.',
    formal: 'The column $c = (c_1, \\ldots, c_n)^T$ that lists $|\\alpha\\rangle = \\sum_i c_i|e_i\\rangle$’s coefficients in order.',
    first: 'q2-basis:b3',
    introduces: 'notation',
  },
  {
    id: 'qc-orthonormal-basis',
    term: 'orthonormal',
    gloss: 'Arrows at right angles to each other, each of length 1.',
    formal: 'A list $\\{|\\alpha_i\\rangle\\}$ with $\\langle\\alpha_i|\\alpha_j\\rangle = \\delta_{ij}$.',
    first: 'q2-basis:b4',
    bridge: 'qc-l4-basis',
  },
  {
    id: 'qc-kronecker-delta',
    term: 'Kronecker delta $\\delta_{ij}$',
    gloss: 'A shorthand that is 1 when its two labels match and 0 when they differ.',
    formal: '$\\delta_{ij} = 1$ for $i = j$ and $0$ for $i \\ne j$.',
    first: 'q2-basis:b4',
    symbols: ['\\delta_{ij}'],
    introduces: 'notation',
  },
  /* q2-gram-schmidt */
  {
    id: 'qc-gram-schmidt',
    term: 'Gram–Schmidt procedure',
    gloss: 'A recipe that makes independent arrows orthonormal: remove the shadows on earlier arrows, then rescale.',
    formal: '$|\\alpha_j\\rangle = |\\alpha\'_j\\rangle/\\sqrt{\\langle\\alpha\'_j|\\alpha\'_j\\rangle}$, with $|\\alpha\'_j\\rangle = |\\beta_j\\rangle - \\sum_{i<j}|\\alpha\'_i\\rangle\\langle\\alpha\'_i|\\beta_j\\rangle/\\langle\\alpha\'_i|\\alpha\'_i\\rangle$.',
    first: 'q2-gram-schmidt:b1',
    bridge: 'qc-l4-basis',
  },
  {
    id: 'qc-r3-example',
    term: '$\\mathbb{R}^3$',
    gloss: 'Ordinary 3D space, used here only as a bigger example of Gram–Schmidt.',
    formal: 'The real 3-dimensional space of triples $(x, y, z)$, with the usual dot product as its inner product.',
    first: 'q2-gram-schmidt:b4',
    introduces: 'space',
  },
  /* q2-operators */
  {
    id: 'qc-linear-operator',
    term: 'linear operator',
    gloss: 'A rule that turns vectors into vectors and respects adding and scaling.',
    formal: 'A linear map $A: V \\to V$, $A(a|\\psi_1\\rangle + b|\\psi_2\\rangle) = aA|\\psi_1\\rangle + bA|\\psi_2\\rangle$.',
    first: 'q2-operators:b1',
    bridge: 'qc-l3-operators',
    introduces: 'notation',
  },
  {
    id: 'qc-outer-product',
    term: 'outer product $|\\alpha\\rangle\\langle\\beta|$',
    gloss: 'A ket followed by a bra: it makes a copy of the ket, scaled by an overlap.',
    formal: '$|\\alpha\\rangle\\langle\\beta|: |\\psi\\rangle \\mapsto \\langle\\beta|\\psi\\rangle|\\alpha\\rangle$; its matrix is $\\alpha\\beta^\\dagger$.',
    first: 'q2-operators:b4',
    bridge: 'qc-l3-projectors',
    introduces: 'notation',
  },
  {
    id: 'qc-matrix-element',
    term: 'matrix element $A_{ij}$',
    gloss: 'One entry of an operator’s table: how much of arrow $i$ it makes from arrow $j$.',
    formal: '$A_{ij} = \\langle e_i|A|e_j\\rangle$ in an ON basis $\\{|e_i\\rangle\\}$.',
    first: 'q2-operators:b5',
    bridge: 'qc-l3-operators',
    introduces: 'notation',
  },
  /* q2-change */
  {
    id: 'qc-change-of-basis-matrix',
    term: 'change-of-basis matrix $U$',
    gloss: 'The table that turns a vector’s old components into its new ones.',
    formal: '$U_{ij} = \\langle\\alpha\'_i|\\alpha_j\\rangle$, so $c\' = Uc$; Spin Lab’s B is $U^\\dagger$.',
    first: 'q2-change:b1',
    bridge: 'qc-l5-coordinates',
  },
  {
    id: 'qc-u-entries',
    term: 'entries $U_{ij}$',
    gloss: 'The numbers inside the change-of-basis table U, one overlap per row and column.',
    formal: '$U_{ij} = \\langle\\alpha\'_i|\\alpha_j\\rangle$, written out as a table rather than named only as a whole.',
    first: 'q2-change:b2',
    introduces: 'notation',
  },
  {
    id: 'qc-dagger-matrix',
    term: 'dagger $\\dagger$ (on a table)',
    gloss: 'Mirror a table across its diagonal and conjugate every entry.',
    formal: '$(A^\\dagger)_{ij} = A^*_{ji}$, applied here to the change-of-basis table $U$.',
    first: 'q2-change:b4',
    introduces: 'notation',
  },
  {
    id: 'qc-hadamard',
    term: 'Hadamard matrix $H$',
    gloss: 'The table that turns z components into x components; used twice, it undoes itself.',
    formal: '$H = \\tfrac{1}{\\sqrt2}\\begin{pmatrix}1&1\\\\1&-1\\end{pmatrix} = H^\\dagger = H^{-1}$ (Bergou p. 4).',
    first: 'q2-change:b6',
  },
  {
    id: 'qc-completeness',
    term: 'completeness relation',
    gloss: 'Adding every basis arrow times its own bra gives the operator that changes nothing.',
    formal: '$\\sum_k|\\alpha_k\\rangle\\langle\\alpha_k| = I$ for an orthonormal basis.',
    first: 'q2-change:b4',
    bridge: 'qc-l4-basis',
    introduces: 'notation',
  },
  {
    id: 'qc-unitary',
    term: 'unitary',
    gloss: 'A table undone by its conjugated mirror image; it keeps all lengths and angles.',
    formal: 'A matrix $U$ with $UU^\\dagger = U^\\dagger U = I$.',
    first: 'q2-change:b4',
    bridge: 'qc-l5-coordinates',
  },
  {
    id: 'qc-similarity-transform',
    term: 'similarity transform',
    gloss: 'Rewriting an operator’s table for a new basis: U times the old table times U†.',
    formal: '$A\' = UAU^\\dagger$.',
    first: 'q2-change:b5',
    bridge: 'qc-l5-operators',
  },
  /* q2-photon */
  {
    id: 'qc-polarization',
    term: 'polarization',
    gloss: 'The direction in which a light wave’s electric field swings.',
    formal: 'A photon’s polarization state lies in $\\mathrm{span}\\{|x\\rangle, |y\\rangle\\}$, with $\\langle x|y\\rangle = 0$.',
    first: 'q2-photon:b1',
    bridge: 'qc-l1-average',
  },
  {
    id: 'qc-photon-space',
    term: 'photon space $\\mathrm{span}\\{|x\\rangle, |y\\rangle\\}$',
    gloss: 'The two-dimensional space of one photon’s polarization states.',
    formal: '$\\mathrm{span}\\{|x\\rangle, |y\\rangle\\} \\cong V^2(\\mathbb{C})$: the same qubit space, a new physical system.',
    first: 'q2-photon:b1',
    introduces: 'space',
  },
  {
    id: 'qc-circular-polarization',
    term: 'circular polarization',
    gloss: 'Light whose field turns round in a circle; its states are $|R\\rangle$ and $|L\\rangle$.',
    formal: '$|R\\rangle, |L\\rangle = (|x\\rangle \\pm i|y\\rangle)/\\sqrt2$, the eigenstates of a frame turn.',
    first: 'q2-photon:b3',
    introduces: 'notation',
  },
  {
    id: 'qc-generator',
    term: 'generator',
    gloss: 'The operator in the exponent of a turn; it sets how fast each state’s phase turns.',
    formal: "The Hermitian $J_z$: $e^{-iJ_z\\chi/\\hbar}$ turns the frame ($|x\\rangle \\to |x'\\rangle$); the coordinate table $U(\\chi)$ is its inverse.",
    first: 'q2-photon:b5',
    bridge: 'qc-l6-generator',
    introduces: 'notation',
  },
  {
    id: 'qc-helicity',
    term: 'helicity',
    gloss: 'A photon’s spin about its line of flight: +ħ or −ħ.',
    formal: 'The $J_z$ eigenvalue on $|R\\rangle$ or $|L\\rangle$: $\\pm\\hbar$ (the notes’ $R$ = positive helicity).',
    first: 'q2-photon:b5',
    introduces: 'notation',
  },
]
