import type { Lecture } from '../schema'
import { Q2_REVIEW } from './Q2.review'
import { Q2_STORY } from './Q2.story'
import { V, close, d } from './Q2.values'

// Physics 709, chapter Q2: the notes' Lecture 2 (9/9, printed pp. 6–10), in both tracks. Every number a learner sees
// is computed in Q2.values.ts, then asserted in keyed claims (content.test.tsx runs `holds`; claims.test.ts compares
// each key with numpy, pipeline/claims_qc709/q2.py). Plan: docs/roles/proposals/P-Q2-story.md; rulings
// docs/roles/decisions/qc709-Q2Q3.md. Unit order swaps the notes' own (operators before change of basis, ruling
// Q2-1): A' = UAU† needs A_ij, outer products and the identity as a sum, which `q2-operators` builds first.

export const Q2: Lecture = {
  id: 'Q2',
  number: 2,
  title: 'Coordinates, bases and turning frames',
  date: 'Sep 9, 2026',
  outcomes: [
    'Test whether arrows are independent, and find a vector’s components in a basis.',
    'Turn independent arrows into an orthonormal basis with Gram–Schmidt.',
    'Derive |±x⟩ from the Stern–Gerlach facts, and write |±z⟩ back in the x basis.',
    'Read an operator as a table, and build one from outer products.',
    'Change a state’s coordinates with U, and an operator’s table with UAU†.',
    'Show that turning a polarizer frame changes |x⟩ but only puts a phase on |R⟩, and read J_z = ±ħ from it.',
  ],
  prerequisites: ['qc-inner-product', 'qc-vector-space', 'qc-superposition', 'qc-phase', 'qc-euler'],
  symbols: {
    // q2-basis
    'c_i': 'q2-basis:b1',
    '|\\alpha_i\\rangle': 'q2-basis:b1',
    'n': 'q2-basis:b1',
    '|\\cdot\\rangle': 'q2-basis:b1',
    '|+x\\rangle': 'q2-basis:b1',
    '|+z\\rangle': 'q2-basis:b1',
    '|-z\\rangle': 'q2-basis:b1',
    '|\\alpha_1\\rangle': 'q2-basis:b1',
    '|\\alpha_n\\rangle': 'q2-basis:b1',
    'V': 'q2-basis:b1',
    '\\mathbb': 'q2-basis:b1',
    'C': 'q2-basis:b1',
    'F': 'q2-basis:b2',
    '|e_i\\rangle': 'q2-basis:b3',
    '\\psi': 'q2-basis:b3',
    'c': 'q2-basis:b3',
    'i': 'q2-basis:b3',
    'N': 'q2-basis:b3',
    '|e_1\\rangle': 'q2-basis:b3',
    '|e_n\\rangle': 'q2-basis:b3',
    '|\\alpha\\rangle': 'q2-basis:b3',
    '\\delta_ij': 'q2-basis:b4',
    '\\langle\\cdot|\\cdot\\rangle': 'q2-basis:b4',
    '|e_j\\rangle': 'q2-basis:b4',
    'j': 'q2-basis:b4',
    '|\\alpha_j\\rangle': 'q2-basis:b4',
    '|\\psi\\rangle': 'q2-basis:b5',
    '\\langle\\cdot|': 'q2-basis:b5',
    'c_j': 'q2-basis:b5',
    '|-x\\rangle': 'q2-basis:b5',
    'a': 'q2-basis:b5',
    'd': 'q2-basis:b5',
    '\\delta_ji': 'q2-basis:b5',
    '\\langle\\cdot\\rangle': 'q2-basis:b5',
    'v': 'q2-basis:b5',
    'e_k': 'q2-basis:b5',
    '|e_k\\rangle': 'q2-basis:b5',
    '|v\\rangle': 'q2-basis:b5',
    'c_x': 'q2-basis:b5',
    'c_1': 'q2-basis:b6',
    'c_2': 'q2-basis:b6',
    // q2-gram-schmidt
    '|\\beta_j\\rangle': 'q2-gram-schmidt:b1',
    "|\\alpha'_j\\rangle": 'q2-gram-schmidt:b1',
    '|\\beta_1\\rangle': 'q2-gram-schmidt:b1',
    '|\\beta_2\\rangle': 'q2-gram-schmidt:b1',
    '|\\beta_n\\rangle': 'q2-gram-schmidt:b1',
    "|\\alpha'_1\\rangle": 'q2-gram-schmidt:b2',
    "|\\alpha'_2\\rangle": 'q2-gram-schmidt:b2',
    '|\\alpha_2\\rangle': 'q2-gram-schmidt:b3',
    "|\\alpha'_i\\rangle": 'q2-gram-schmidt:b3',
    "|\\alpha'_3\\rangle": 'q2-gram-schmidt:b4',
    '|+y\\rangle': 'q2-gram-schmidt:b5',
    '|-y\\rangle': 'q2-gram-schmidt:b5',
    '\\dim': 'q2-gram-schmidt:b6',
    '|\\beta_3\\rangle': 'q2-gram-schmidt.play.q2-g-third',
    '\\alpha': 'q2-gram-schmidt.play.q2-g-third.hints[0]',
    // q2-spin-space
    '\\beta': 'q2-spin-space:b1',
    '|0\\rangle': 'q2-spin-space:b1',
    '|1\\rangle': 'q2-spin-space:b1',
    'P': 'q2-spin-space:b1',
    '|\\to\\rangle': 'q2-spin-space:b1',
    '|\\leftarrow\\rangle': 'q2-spin-space:b1',
    '|+\\rangle': 'q2-spin-space:b1',
    '|-\\rangle': 'q2-spin-space:b1',
    '|s_x=\\pm\\rangle': 'q2-spin-space:b2',
    'e': 'q2-spin-space:b2',
    '\\delta_\\pm': 'q2-spin-space:b2',
    '\\delta_+': 'q2-spin-space:b3',
    '\\delta_-': 'q2-spin-space:b3',
    '\\pi': 'q2-spin-space:b3',
    '|\\psi_\\delta\\rangle': 'q2-spin-space:b3',
    '\\delta': 'q2-spin-space:b3',
    '\\gamma_1': 'q2-spin-space:b4',
    '\\gamma_2': 'q2-spin-space:b4',
    '|\\psi_\\pi/2\\rangle': 'q2-spin-space:b6',
    '\\psi_\\pi/2': 'q2-spin-space:b6',
    // q2-operators
    '|\\psi_1\\rangle': 'q2-operators:b1',
    '|\\psi_2\\rangle': 'q2-operators:b1',
    'A': 'q2-operators:b1',
    'b': 'q2-operators:b1',
    'R': 'q2-operators:b2',
    '|A(+z)\\rangle': 'q2-operators:b2',
    '|A(-z)\\rangle': 'q2-operators:b2',
    'K': 'q2-operators:b3',
    '|K(+z)\\rangle': 'q2-operators:b3',
    '|K(-z)\\rangle': 'q2-operators:b3',
    '|\\beta\\rangle': 'q2-operators:b4',
    '\\dagger': 'q2-operators:b4',
    'A_ij': 'q2-operators:b5',
    'f_i': 'q2-operators:b5',
    'f_1': 'q2-operators:b5',
    'f_2': 'q2-operators:b5',
    'f': 'q2-operators:b5',
    'A_12': 'q2-operators:b5',
    'T': 'q2-operators:b6',
    // q2-change
    'U': 'q2-change:b1',
    'U_ij': 'q2-change:b1',
    'B': 'q2-change:b1',
    'c_\\rmnew': 'q2-change:b1',
    'c_\\rmold': 'q2-change:b1',
    'd_1': 'q2-change:b2',
    'd_2': 'q2-change:b2',
    'U_z\\tox': 'q2-change:b2',
    'I': 'q2-change:b4',
    '|\\alpha_k\\rangle': 'q2-change:b4',
    'S_z': 'q2-change:b5',
    '\\hbar': 'q2-change:b5',
    '|j\\rangle': 'q2-change:b5',
    "|l'\\rangle": 'q2-change:b5',
    '|i\\rangle': 'q2-change:b5',
    "|k'\\rangle": 'q2-change:b5',
    'k': 'q2-change:b5',
    'l': 'q2-change:b5',
    'U_ki': 'q2-change:b5',
    'S_x': 'q2-change:b5',
    'H': 'q2-change:b6',
    'U_22': 'q2-change.play.q2-c-u22',
    '\\sigma_z': 'q2-change.play.q2-c-sz.hints[2]',
    '\\sigma_x': 'q2-change.play.q2-c-sz.hints[2]',
    'U_12': 'q2-change.play.q2-c-dagger.hints[1]',
    // q2-photon
    '|x\\rangle': 'q2-photon:b1',
    '|y\\rangle': 'q2-photon:b1',
    'E': 'q2-photon:b1',
    '\\varphi': 'q2-photon:b1',
    '\\chi': 'q2-photon:b1',
    '|H\\rangle': 'q2-photon:b1',
    "|x'\\rangle": 'q2-photon:b2',
    "|y'\\rangle": 'q2-photon:b2',
    "|i'\\rangle": 'q2-photon:b2',
    '|R\\rangle': 'q2-photon:b3',
    '|L\\rangle': 'q2-photon:b3',
    "|R'\\rangle": 'q2-photon:b4',
    "|L'\\rangle": 'q2-photon:b4',
    'J_z': 'q2-photon:b5',
    "|R(L)'\\rangle": 'q2-photon:b5',
    '|R(L)\\rangle': 'q2-photon:b5',
    '|V\\rangle': 'q2-photon:b6',
    'R_y': 'q2-photon:b6',
    '\\theta': 'q2-photon:b6',
    '|\\theta=45°\\rangle': 'q2-photon:b6',
  },
  symbolsFormal: {
    '\\hat A': 'q2-operators:b5',
  },
  corrections: [
    {
      where: 'p. 9, Eq. 1.3',
      says: 'The |−x⟩ coefficient is (c₂ − c₁)/√2.',
      shouldSay: `(c₁ − c₂)/√2, as the matrix just below it gives. The printed sign turns the state at 30° into the one at 60°: it would read P(+z) = ${d(V.q2WrongPzPlus, 2)} instead of ${d(V.q2WrongPzMinus, 2)}.`,
      check: () => close(V.q2D30Re1, (V.q2Comp30Re0 - V.q2Comp30Re1) / Math.SQRT2) && V.q2Printed < 0 && V.q2WrongSame === 1,
    },
    {
      where: 'p. 9',
      says: "[Û†]_ij = U*_ji equals ⟨α_j|α'_i⟩.",
      shouldSay: "U*_ji = ⟨α_i|α'_j⟩; the printed bracket is U*_ij. The boxed proof uses the right form. The two differ once U is not symmetric, e.g. z → y.",
      check: () => close(V.q2UyDag01Re, Math.SQRT1_2) && close(V.q2UyNotes01Im, Math.SQRT1_2),
    },
    {
      where: 'p. 10',
      says: 'A linear operator maps V onto itself.',
      shouldSay: 'Into itself: its outputs need not fill V. The projector |+z⟩⟨+z| is linear, yet every output lies on one line.',
      check: () => V.q2ProjRank === 1,
    },
  ],
  units: [
    {
      id: 'q2-basis',
      story: Q2_STORY['q2-basis'],
      review: Q2_REVIEW['q2-basis'],
      title: 'Independent arrows and a basis',
      question: 'When does a set of arrows give every vector one, and only one, address?',
      lecture: {
        pages: 'notes p. 6',
        summary: 'A set of arrows is linearly independent when only the all-zero mix gives the zero vector. Independent arrows spanning the whole space form a basis, and every vector has unique components in it.',
      },
      books: [
        { source: 'axler', where: '2.15, p. 32; 2.28, p. 39; 2.35, p. 44; 6.27–6.30, p. 199–200', adds: 'Linear independence, the uniqueness of a basis expansion, dimension, and reading components as overlaps in an orthonormal list.' },
      ],
      visual: { kind: 'basis-translator', props: { target: 'x', mode: 'state', theta: 60, phi: 0 }, tryThis: ['Read the x column of ψ.', 'Set θ = 90°: which column is (1, 0)?'] },
      clues: [],
      insight: 'Independent arrows spanning a space form a basis; every vector has unique components in it, and in an orthonormal basis a component is an overlap.',
      insightFormal:
        'An LI spanning list of $V^n$ is a basis; the expansion of any $|\\alpha\\rangle$ is unique (Axler 2.28), and $c_i = \\langle e_i|\\alpha\\rangle$ exactly when the basis is orthonormal.',
      pitfalls: ['Reading components as overlaps in a basis that is not orthonormal.'],
      play: [
        {
          id: 'q2-b-dim',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The dimension of a qubit',
          prompt: 'What is the dimension of $V^2(\\mathbb{C})$, the space of a qubit’s kets?',
          answer: V.q2Dim,
          tolerance: 0.1,
          hints: [{ text: 'Count independent arrows.' }, { text: '|+z⟩, |−z⟩ already give every vector.' }, { text: 'A third is always a mix.' }],
          walkthrough: [{ text: `Two, so every basis has ${d(V.q2Dim, 0)} arrows.` }],
        },
        {
          id: 'q2-b-comp',
          kind: 'numeric',
          tier: 'core',
          title: 'A component along |+x⟩',
          prompt: '$\\psi = (0.6, 0.8)$. What is its component along $|{+x}\\rangle$?',
          answer: V.q2BComp,
          tolerance: 0.005,
          hints: [{ text: 'The basis is orthonormal.' }, { text: '$c = \\langle{+x}|\\psi\\rangle$.' }, { text: '$(0.6 + 0.8)/\\sqrt2$.' }],
          walkthrough: [{ text: `$1.4/1.414 = ${d(V.q2BComp, 3)}$.` }],
        },
        {
          id: 'q2-b-independent',
          kind: 'choice',
          tier: 'core',
          title: 'Which set is independent?',
          prompt: 'Which set is linearly independent?',
          options: [
            { text: '$|{+z}\\rangle$, $|{-z}\\rangle$, $|{+x}\\rangle$', correct: false, why: '$|{+x}\\rangle$ is a mix of the other two: dependent.' },
            { text: '$|{+z}\\rangle$, $|{+x}\\rangle$', correct: true, why: 'Right. They point different ways in the plane, and neither is a multiple of the other.' },
            { text: '$|{+x}\\rangle$, $-|{+x}\\rangle$', correct: false, why: 'These are multiples of one arrow: dependent.' },
            { text: '$|{+z}\\rangle$ and the zero vector', correct: false, why: 'Any set holding the zero vector is dependent.' },
          ],
          hints: [{ text: 'Look for a mix that gives 0.' }, { text: 'Three arrows in a plane are always dependent.' }, { text: 'Any set holding 0 is dependent.' }],
          walkthrough: [{ text: 'Only $|{+z}\\rangle$, $|{+x}\\rangle$: they point different ways.' }],
        },
        {
          id: 'q2-b-slanted',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A slanted basis',
          prompt: 'In the basis $|{+z}\\rangle$, $|{+x}\\rangle$, what is the component of $|{-z}\\rangle$ along $|{+x}\\rangle$?',
          answer: V.q2NonOrthRe1,
          tolerance: 0.005,
          hints: [{ text: 'Not an overlap: the basis is slanted.' }, { text: 'Solve $c_1|{+z}\\rangle + c_2|{+x}\\rangle = |{-z}\\rangle$.' }, { text: 'The $|{+x}\\rangle$ part needs $c_2/\\sqrt2 = 1$.' }],
          walkthrough: [{ text: `$c_2 = \\sqrt2$, $c_1 = ${d(V.q2NonOrthRe0, 0)}$ (clue b6).` }],
        },
      ],
    },
    {
      id: 'q2-gram-schmidt',
      story: Q2_STORY['q2-gram-schmidt'],
      review: Q2_REVIEW['q2-gram-schmidt'],
      title: 'Straightening a basis with Gram–Schmidt',
      question: 'How do we turn independent arrows into an orthonormal basis?',
      lecture: { pages: 'notes pp. 6–7, Fig. 4', summary: 'Gram–Schmidt keeps the first arrow, removes each new arrow’s shadows on the earlier ones, and rescales what is left into an orthonormal basis.' },
      books: [
        { source: 'axler', where: '6.32, p. 201', adds: 'The Gram–Schmidt procedure, projecting each step at a time.' },
        { source: 'nc', where: 'p. 66, Ex. 2.8', adds: 'The same recipe, with the general proof that the leftover stays at right angles left as an exercise (N&C ⚑), assigned in no course sheet.' },
      ],
      visual: { kind: 'projector', props: { state: 60, basis: 0, editableBasis: true }, tryThis: ['Read the shadow on |+z⟩ at 60°.', 'Turn the basis until one shadow is zero: now the arrows are already at right angles.'] },
      clues: [],
      insight: 'Keep the first arrow, remove each new arrow’s shadows on the earlier ones, and rescale each leftover to length 1. A zero leftover means the input was dependent.',
      insightFormal: "$|\\alpha'_j\\rangle = |\\beta_j\\rangle - \\sum_{i<j}|\\alpha'_i\\rangle\\langle\\alpha'_i|\\beta_j\\rangle/\\langle\\alpha'_i|\\alpha'_i\\rangle$, then $|\\alpha_j\\rangle = |\\alpha'_j\\rangle/\\sqrt{\\langle\\alpha'_j|\\alpha'_j\\rangle}$.",
      pitfalls: ['Forgetting to rescale the leftover to length 1.'],
      play: [
        {
          id: 'q2-g-left',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'How long is the leftover?',
          prompt: '$|\\beta_1\\rangle = |{+z}\\rangle$, $|\\beta_2\\rangle = (0.6, 0.8)$. How long is the leftover $|\\alpha\'_2\\rangle$?',
          answer: V.q2GLeft,
          tolerance: 0.005,
          hints: [{ text: 'Remove the shadow on |+z⟩.' }, { text: 'It is $0.6|{+z}\\rangle$.' }, { text: 'What is left is $(0, 0.8)$.' }],
          walkthrough: [{ text: `${d(V.q2GLeft, 1)}; rescaled, $|{-z}\\rangle$.` }],
        },
        {
          id: 'q2-g-3d',
          kind: 'numeric',
          tier: 'core',
          title: 'A squared length in 3D',
          prompt: '$|\\beta_1\\rangle = (1, 1, 0)$, $|\\beta_2\\rangle = (1, 0, 1)$. What is $\\langle\\alpha\'_2|\\alpha\'_2\\rangle$?',
          answer: V.q2G3DRes2Norm2,
          tolerance: 0.005,
          hints: [{ text: '⟨β1|β2⟩ = 1, ⟨β1|β1⟩ = 2.' }, { text: 'Remove ½ of β1.' }, { text: '(0.5, −0.5, 1).' }],
          walkthrough: [{ text: `$0.25 + 0.25 + 1 = ${d(V.q2G3DRes2Norm2, 1)}$.` }],
        },
        {
          id: 'q2-g-third',
          kind: 'numeric',
          tier: 'core',
          title: 'Continuing to a third arrow',
          prompt: 'Continue with $|\\beta_3\\rangle = (0, 1, 1)$. What is the first entry of $|\\alpha\'_3\\rangle$?',
          answer: V.q2Gs3DRes2Re0,
          tolerance: 0.005,
          hints: [{ text: "Remove the shadows on $\\alpha'_1$ and $\\alpha'_2$." }, { text: 'Their sizes are ½ and 1/3 of those arrows.' }, { text: '(0, 1, 1) − (0.5, 0.5, 0) − (1/6, −1/6, 1/3).' }],
          walkthrough: [{ text: `$(${d(V.q2Gs3DRes2Re0)}, ${d(V.q2Gs3DRes2Re1)}, ${d(V.q2Gs3DRes2Re2)})$.` }],
        },
        {
          id: 'q2-g-order',
          kind: 'choice',
          tier: 'stretch',
          title: 'Order matters',
          prompt: 'Run the recipe on the 60° arrow first, then $|{+z}\\rangle$. What comes out?',
          options: [
            { text: '$|{+z}\\rangle$, $|{-z}\\rangle$', correct: false, why: 'That is the order used in the beats, not this one.' },
            { text: `(${d(V.q2Gs60, 1)}, ${d(V.q2GsResRe1)}) and (${d(V.q2GOrderE1Re0)}, ${d(V.q2GOrderE1Re1, 1)})`, correct: true, why: 'Right. Keeping the 60° arrow first changes which orthonormal pair comes out.' },
            { text: `(${d(V.q2Gs60, 1)}, ${d(V.q2GsResRe1)}) and $|{-z}\\rangle$`, correct: false, why: 'The second arrow is not simply |−z⟩ when the order is reversed.' },
            { text: 'the same basis in the other order', correct: false, why: 'Gram–Schmidt is not order-independent: only the SPAN after each step is fixed, not the individual output arrows.' },
          ],
          hints: [{ text: 'The first arrow is kept exactly.' }, { text: 'Remove from |+z⟩ its shadow on the 60° arrow.' }, { text: 'Rescale.' }],
          walkthrough: [{ text: 'Order matters: the first arrow always survives unchanged.' }],
        },
      ],
    },
    {
      id: 'q2-spin-space',
      story: Q2_STORY['q2-spin-space'],
      review: Q2_REVIEW['q2-spin-space'],
      title: 'Spin states in the z and x frames',
      question: 'How do the notes pin down the numbers in |±x⟩, and how do we go back?',
      lecture: { pages: 'notes pp. 7–8, Eqs. 1.1–1.2, Fig. 5', summary: 'The z-magnet statistics of |±x⟩ pin down their amplitudes; requiring |−x⟩ at right angles to |+x⟩ forces the sign, giving the inverse relation too.' },
      books: [{ source: 'axler', where: '6.30, p. 200', adds: 'Reading amplitudes as overlaps in an orthonormal basis, applied to the spin states.' }],
      visual: { kind: 'amplitude-bars', props: { state: [90, 0], basis: 'z', editable: true }, tryThis: ['φ = 180°: |−x⟩.', 'φ = 90°: the z bars stay ½, ½; which basis tells it from |±x⟩?'] },
      clues: [],
      insight: 'The z-magnet statistics of |±x⟩ give equal amplitude sizes; being at right angles forces the sign, giving |±x⟩ = (|+z⟩ ± |−z⟩)/√2 and its inverse.',
      insightFormal: '$|s_x = \\pm\\rangle = \\alpha|{+z}\\rangle + e^{i\\delta_\\pm}\\beta|{-z}\\rangle$ with $\\alpha = \\beta = 1/\\sqrt2$; $\\delta_+ = 0$ is the free choice, $\\delta_- = \\pi$ is forced by orthogonality.',
      pitfalls: ['Thinking any phase will do for |−x⟩: δ₋ = 90° gives |+y⟩, unbiased with respect to the x magnet.'],
      play: [
        {
          id: 'q2-s-amp',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'An amplitude, squared',
          prompt: '$|\\psi\\rangle = 0.866|{+z}\\rangle + 0.5i|{-z}\\rangle$. What is $P(-z)$?',
          answer: V.q2AmpExP1,
          tolerance: 0.005,
          hints: [{ text: 'Size squared.' }, { text: '$|0.5i|^2 = 0.5^2$.' }, { text: 'Not $(0.5i)^2$.' }],
          walkthrough: [{ text: `${d(V.q2AmpExP1, 2)}.` }],
        },
        {
          id: 'q2-s-delta',
          kind: 'numeric',
          tier: 'core',
          title: 'A phase off from 180°',
          prompt: 'For $(|{+z}\\rangle + e^{i\\delta}|{-z}\\rangle)/\\sqrt2$ with $\\delta = 90°$, what is $|\\langle{+x}|\\psi\\rangle|$?',
          answer: V.q2DeltaAt90,
          tolerance: 0.005,
          hints: [{ text: '$\\langle{+x}| = (1, 1)/\\sqrt2$.' }, { text: 'The overlap is $(1 + e^{i\\delta})/2$.' }, { text: '$|1 + i| = \\sqrt2$.' }],
          walkthrough: [{ text: `$\\sqrt2/2 = ${d(V.q2DeltaAt90, 4)}$.` }],
        },
        {
          id: 'q2-s-inverse',
          kind: 'choice',
          tier: 'core',
          title: '|−z⟩ in the x basis',
          prompt: 'Which is $|{-z}\\rangle$ in the x basis?',
          options: [
            { text: '$(|{+x}\\rangle - |{-x}\\rangle)/\\sqrt2$', correct: true, why: 'Right. Subtracting Eq. 1.2 from Eq. 1.1 cancels the |+z⟩ parts.' },
            { text: '$(|{+x}\\rangle + |{-x}\\rangle)/\\sqrt2$', correct: false, why: 'That is $|{+z}\\rangle$, the sum, not the difference.' },
            { text: '$|{-x}\\rangle$', correct: false, why: '|−z⟩ is not a single x-basis arrow; it is a mix of both.' },
            { text: '$(|{+x}\\rangle + i|{-x}\\rangle)/\\sqrt2$', correct: false, why: 'No phase i appears in the real inverse relation.' },
          ],
          hints: [{ text: 'Subtract Eq. 1.2 from Eq. 1.1.' }, { text: 'The |+z⟩ parts cancel.' }, { text: 'Divide by √2.' }],
          walkthrough: [{ text: 'Beat 2.3 b4 derives exactly this.' }],
        },
        {
          id: 'q2-s-angle',
          kind: 'numeric',
          tier: 'stretch',
          title: 'An angle in the plane',
          prompt: 'In the real plane, what angle (degrees) separates $|{+z}\\rangle$ and $|{-x}\\rangle$?',
          answer: V.q2SAngle,
          tolerance: 0.5,
          hints: [{ text: '$|{-x}\\rangle = (1, -1)/\\sqrt2$.' }, { text: 'It points 45° below $|{+z}\\rangle$.' }, { text: '$\\cos = 0.707$.' }],
          walkthrough: [{ text: `${d(V.q2SAngle, 0)}° here, 90° on the sphere.` }],
        },
      ],
    },
    {
      id: 'q2-operators',
      story: Q2_STORY['q2-operators'],
      review: Q2_REVIEW['q2-operators'],
      title: 'Operators, outer products and their tables',
      question: 'What does an operator do to arrows, and how does a basis turn it into a table?',
      lecture: { pages: 'notes p. 10, Fig. 6', summary: 'A linear operator turns vectors into vectors while respecting mixing. In a basis it is a table of matrix elements, and Σ Aij|ei⟩⟨ej| rebuilds the operator from outer products.' },
      books: [
        { source: 'axler', where: '3.31, p. 69; 5.1, p. 133', adds: 'The definition of a linear map, and building an operator from its matrix elements.' },
        { source: 'nc', where: 'Eqs. 2.12, 2.25, pp. 64, 68', adds: 'Operators as sums of outer products, by inserting the identity twice.' },
      ],
      visual: { kind: 'operator-action', props: { preset: '[[2,1],[1,2]]' }, tryThis: ['Drag the arrow: where does it only stretch?', 'Are the images of |+z⟩ and |−z⟩ at right angles?'] },
      clues: [],
      insight: 'A linear operator turns vectors into vectors and respects mixing; in a basis it is a table, and outer products rebuild it exactly.',
      insightFormal: '$A: V \\to V$ linear (into, not necessarily onto); $f = \\hat Ac$ in a basis, and $A = \\sum_{ij}A_{ij}|e_i\\rangle\\langle e_j|$.',
      pitfalls: ['A shift such as "add |+z⟩" is not linear: it moves the zero vector.'],
      play: [
        {
          id: 'q2-o-len',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The length of an image',
          prompt: '$A = [[1, -1], [1, 1]]$. How long is $A|{+z}\\rangle$?',
          answer: V.q2FigANorm,
          tolerance: 0.005,
          hints: [{ text: '$A|{+z}\\rangle$ is the first column.' }, { text: '$(1, 1)$.' }, { text: 'Pythagoras.' }],
          walkthrough: [{ text: `$\\sqrt2 = ${d(V.q2FigANorm)}$.` }],
        },
        {
          id: 'q2-o-outer',
          kind: 'numeric',
          tier: 'core',
          title: 'An outer product applied',
          prompt: 'Apply $|{+z}\\rangle\\langle{+x}|$ to $|{-z}\\rangle$. What is the first component?',
          answer: V.q2OOuterZ,
          tolerance: 0.005,
          hints: [{ text: 'The result is $\\langle{+x}|{-z}\\rangle|{+z}\\rangle$.' }, { text: '$\\langle{+x}|{-z}\\rangle = 1/\\sqrt2$.' }, { text: 'The second component is 0.' }],
          walkthrough: [{ text: `$(${d(V.q2OOuterZ)}, 0)$.` }],
        },
        {
          id: 'q2-o-element',
          kind: 'numeric',
          tier: 'core',
          title: 'A matrix element',
          prompt: 'For $A = [[1, -1], [1, 1]]$, what is $A_{12} = \\langle{+z}|A|{-z}\\rangle$?',
          answer: V.q2Aij01,
          tolerance: 0.1,
          hints: [{ text: '$A|{-z}\\rangle$ is column 2.' }, { text: '$(-1, 1)$.' }, { text: 'Take its |+z⟩ part.' }],
          walkthrough: [{ text: `${d(V.q2Aij01, 0)}.` }],
        },
        {
          id: 'q2-o-linear',
          kind: 'choice',
          tier: 'stretch',
          title: 'Which rule is linear?',
          prompt: 'Which rule is a linear operator?',
          options: [
            { text: 'add $|{+z}\\rangle$ to every vector', correct: false, why: 'It fails 0 ↦ 0 (Unit 2.4 b6).' },
            { text: 'multiply every vector by 3', correct: true, why: 'Right. Scaling by a fixed number respects both sums and scaling.' },
            { text: 'square each component', correct: false, why: 'Squaring does not respect scaling: doubling a vector quadruples its image.' },
            { text: 'replace each component by its size', correct: false, why: 'Taking a size is not linear: it does not respect negative scalars.' },
          ],
          hints: [{ text: 'Test $0 \\mapsto 0$.' }, { text: 'Test doubling.' }, { text: 'Squaring doubles to four times.' }],
          walkthrough: [{ text: 'Only scaling by 3 respects sums and scaling.' }],
        },
      ],
    },
    {
      id: 'q2-change',
      story: Q2_STORY['q2-change'],
      review: Q2_REVIEW['q2-change'],
      title: 'Changing coordinates with one matrix',
      question: 'How do the numbers of a state, and of an operator, change with the basis?',
      lecture: { pages: 'notes pp. 8–9, Eq. 1.3', summary: 'A vector’s new components are overlaps with the new basis, c\' = Uc; U is unitary by completeness, and an operator’s table changes as A\' = UAU†. From z to x, U is the Hadamard matrix.' },
      books: [
        { source: 'bergou', where: 'Eq. 1.8, p. 4', adds: 'The z-to-x change-of-basis matrix, named H, the Hadamard gate.' },
        { source: 'axler', where: '3.82–3.84, p. 92–93', adds: 'The matrix of a linear map under a change of basis.' },
        { source: 'nc', where: 'Eq. 1.19, p. 22; Ex. 2.20, p. 71', adds: 'The same |−⟩ combination with the correct sign, and (N&C ⚑, unassigned) the general similarity-transform proof.' },
      ],
      visual: { kind: 'basis-translator', props: { target: 'x', mode: 'operator', operator: 'Sz' }, tryThis: ['S_z in the x basis: diagonal?', 'Switch to S_x: now?'] },
      clues: [],
      insight: "New components are overlaps with the new basis, c' = Uc; U keeps lengths (UU† = I), and an operator's table changes as A' = UAU†. From z to x, U is the Hadamard matrix H.",
      insightFormal: "$U_{ij} = \\langle\\alpha'_i|\\alpha_j\\rangle$, Spin Lab's $B^\\dagger$; completeness proves $UU^\\dagger = I$; $A' = UAU^\\dagger$.",
      pitfalls: ["Trusting Eq. 1.3's printed sign: it turns ψ at 30° into the state at 60°."],
      play: [
        {
          id: 'q2-c-u22',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'An entry of U',
          prompt: 'For z → x, what is $U_{22} = \\langle{-x}|{-z}\\rangle$?',
          answer: V.q2CU22,
          tolerance: 0.005,
          hints: [{ text: '$\\langle{-x}| = (1, -1)/\\sqrt2$.' }, { text: 'Pick its second entry.' }, { text: '$-1/\\sqrt2$.' }],
          walkthrough: [{ text: `${d(V.q2CU22)}.` }],
        },
        {
          id: 'q2-c-d2',
          kind: 'numeric',
          tier: 'core',
          title: 'A new x component',
          prompt: '$c = (0.6, 0.8)$. What is $d_2$, the $|{-x}\\rangle$ component?',
          answer: V.q2CD2,
          tolerance: 0.005,
          hints: [{ text: '$d_2 = (c_1 - c_2)/\\sqrt2$.' }, { text: "Not Eq. 1.3's sign." }, { text: '$-0.2/1.414$.' }],
          walkthrough: [{ text: `${d(V.q2CD2, 3)} (see the errata box).` }],
        },
        {
          id: 'q2-c-sz',
          kind: 'numeric',
          tier: 'core',
          title: 'S_z, turned to the x basis',
          prompt: 'In the x basis, what is the top-right entry of $S_z$, in units of $\\hbar$?',
          answer: V.q2SzXTopRight,
          tolerance: 0.005,
          hints: [{ text: "$A' = UAU^\\dagger$." }, { text: '$U = H$.' }, { text: '$H\\sigma_zH = \\sigma_x$.' }],
          walkthrough: [{ text: '$S_z$ reads $(\\hbar/2)(0\\ 1; 1\\ 0)$ in x.' }],
        },
        {
          id: 'q2-c-dagger',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A dagger entry',
          prompt: 'For z → y, what is the imaginary part of $[U^\\dagger]_{21} = \\langle\\alpha_2|\\alpha\'_1\\rangle = \\langle{-z}|{+y}\\rangle$?',
          answer: V.q2UyDag10Im,
          tolerance: 0.005,
          hints: [{ text: '$[U^\\dagger]_{21} = U^*_{12}$.' }, { text: '$U_{12} = \\langle{+y}|{-z}\\rangle = -i/\\sqrt2$.' }, { text: 'Conjugate it.' }],
          walkthrough: [{ text: `$i/\\sqrt2 = ${d(V.q2UyDag10Im)}i$ (see the errata box).` }],
        },
      ],
    },
    {
      id: 'q2-photon',
      story: Q2_STORY['q2-photon'],
      review: Q2_REVIEW['q2-photon'],
      title: 'Turning the frame of a photon',
      question: 'Why does turning the polarizer frame only put a phase on circular light?',
      lecture: { pages: 'notes p. 9', summary: 'A photon polarization frame turns as a real rotation; linear states rotate with it, but circular states only pick up a phase.' },
      books: [{ source: 'bergou', where: '§14.2, p. 257', adds: 'Photon polarization as a qubit, |0⟩ = |H⟩ = |x⟩, |1⟩ = |V⟩, with the sphere’s angle-doubling rule.' }],
      visual: { kind: 'projector', props: { state: 45, basis: 0, editableBasis: true }, tryThis: ['Basis at 45°: half passes.', 'Basis at 90°: nothing passes.', 'Why does spin need 180° for that?'] },
      clues: [],
      insight: 'A photon has two linear polarization states; a frame turn moves them, but only rephases the circular states, giving $J_z = \\pm\\hbar$.',
      insightFormal: "$U(\\chi)$ is a real rotation (det +1); $|R'\\rangle = e^{-i\\chi}|R\\rangle$, $|L'\\rangle = e^{i\\chi}|L\\rangle$; $\\chi$ in the lab is $2\\chi$ on the qubit sphere.",
      pitfalls: ["A new phase does not mean a new state: |R'⟩ = −i|R⟩ at 90° is the same state as |R⟩."],
      play: [
        {
          id: 'q2-p-malus',
          kind: 'numeric',
          tier: 'warm-up',
          title: "Malus's law",
          prompt: 'x-polarized light meets a polarizer turned by 60°. What fraction passes?',
          answer: V.q2PMalus60,
          tolerance: 0.005,
          hints: [{ text: 'Squared shadow.' }, { text: '$\\cos 60° = 0.5$.' }, { text: 'Square it.' }],
          walkthrough: [{ text: `${d(V.q2PMalus60, 2)}.` }],
        },
        {
          id: 'q2-p-spin',
          kind: 'numeric',
          tier: 'core',
          title: 'Spin at the matching angle',
          prompt: '$|{+z}\\rangle$ atoms meet a magnet tilted by 60°. What fraction lands +?',
          answer: V.q2PSpin60,
          tolerance: 0.005,
          hints: [{ text: 'Spin uses half the angle.' }, { text: '$\\cos^2 30°$.' }, { text: '$0.866^2$.' }],
          walkthrough: [{ text: `${d(V.q2PSpin60, 2)}, against light's ${d(V.q2PMalus60, 2)}.` }],
        },
        {
          id: 'q2-p-phase',
          kind: 'numeric',
          tier: 'core',
          title: 'A phase factor',
          prompt: 'Turn the frame by $\\chi = 30°$. What is the real part of the factor $e^{-i\\chi}$ on $|R\\rangle$?',
          answer: V.q2PhaseCos30,
          tolerance: 0.005,
          hints: [{ text: "$|R'\\rangle = e^{-i\\chi}|R\\rangle$." }, { text: 'Euler: $\\cos\\chi - i\\sin\\chi$.' }, { text: '$\\cos 30°$.' }],
          walkthrough: [{ text: `${d(V.q2PhaseCos30)}; the imaginary part is $${d(V.q2PhaseSin30, 1)}$.` }],
        },
        {
          id: 'q2-p-jz',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A J_z expectation',
          prompt: 'In $\\{|x\\rangle, |y\\rangle\\}$, $J_z/\\hbar = [[0, -i], [i, 0]]$. What is $\\langle R|J_z|R\\rangle/\\hbar$?',
          answer: V.q2SandwichR,
          tolerance: 0.005,
          hints: [{ text: 'Apply the table to $(1, i)/\\sqrt2$.' }, { text: 'You get $(1, i)/\\sqrt2$ back.' }, { text: '$\\langle R|R\\rangle = 1$.' }],
          walkthrough: [{ text: `+${d(V.q2SandwichR, 0)}: $|R\\rangle$ is the eigenstate with $J_z = +\\hbar$.` }],
        },
      ],
    },
  ],
}
