import type { Lecture } from '../schema'
import { Q3_REVIEW } from './Q3.review'
import { Q3_STORY } from './Q3.story'
import { V, d, uf } from './Q3.values'

// Physics 709, chapter Q3: the notes' Lectures 3-4 (9/14 & 9/16, printed pp. 11-20), in both tracks. Every number a learner
// sees is computed in Q3.values.ts, then asserted in keyed claims (content.test.tsx runs `holds`; claims.test.ts
// compares each key with numpy, pipeline/claims_qc709/q3.py). Plan: docs/roles/proposals/P-Q3-story.md; rulings
// docs/roles/decisions/qc709-Q2Q3.md, qc709-map.md, qc709-pilots.md, qc709-nc.md. Ruling Q3-1: every formerly
// assigned problem (⟨+n|−n⟩, ⟨S⟩ and ΔS for |+n⟩, the real-eigenvalue proof) is now worked in full — no Q3 challenge
// is assigned homework in either course.

export const Q3: Lecture = {
  id: 'Q3',
  number: 3,
  title: 'Measurement, the Bloch sphere and uncertainty',
  date: 'Sep 14 & 16, 2026',
  outcomes: [
    'Write a chance as a projector sandwich, ⟨ψ|P|ψ⟩, and check that a basis’s chances add to 1.',
    'Place any spin state on the sphere with two angles, and find its opposite state.',
    'Build S_z, S_x, S_y and S_n from projectors, and name the Pauli matrices.',
    'Say what a measurement does to the state, find an average, and explain why observables are Hermitian.',
    'Prove that a Hermitian operator’s eigenvalues are real, and compute ⟨S⟩ and ΔS for any |+n⟩.',
    'State and prove the uncertainty relation, and test it on |+x⟩, |+z⟩ and |+n⟩.',
  ],
  // Q2's stations (qc-basis, qc-operator-matrix, qc-change-of-basis, qc-x-states), Q1's superposition and F1's Euler
  // formula, named by the plan; the map draws Q3's own concepts from content/qc709/concepts.ts.
  prerequisites: ['qc-basis', 'qc-operator-matrix', 'qc-change-of-basis', 'qc-x-states', 'qc-superposition', 'qc-euler'],
  symbols: {
    '|\\alpha\\rangle': 'q3-born:b1',
    '|M\\rangle': 'q3-born:b1',
    p_M: 'q3-born:b1',
    P_M: 'q3-born:b2',
    '|\\cdot\\rangle': 'q3-born:b2.derivation',
    '|\\psi\\rangle': 'q3-born:b2.derivation',
    '\\langle\\cdot|': 'q3-born:b2.derivation',
    '\\langle\\cdot|\\cdot\\rangle': 'q3-born:b2.derivation.ground[0]',
    '|e_i\\rangle': 'q3-born.review',
    I: 'q3-born:b3',
    P_i: 'q3-born:b3',
    P_j: 'q3-born:b4',
    p_j: 'q3-born:b4',
    '|+x\\rangle': 'q3-born.play.q3-b-overlap',
    '|+z\\rangle': 'q3-born.play.q3-b-overlap',
    '\\psi': 'q3-born.play.q3-b-sandwich',
    'P_+x': 'q3-born.play.q3-b-sandwich',
    i: 'q3-born.play.q3-b-phase',
    'P_-x': 'q3-born.play.q3-b-phase',
    '|-x\\rangle': 'q3-born.play.q3-b-phase.hints[0]',
    '\\theta': 'q3-bloch:b1',
    '\\varphi': 'q3-bloch:b1',
    '|+n\\rangle': 'q3-bloch:b1',
    '|\\theta,\\varphi\\rangle': 'q3-bloch:b1',
    '\\leftrightarrow': 'q3-bloch:b1',
    S: 'q3-bloch:b1',
    '|-z\\rangle': 'q3-bloch:b1',
    e: 'q3-bloch:b1',
    '\\alpha': 'q3-bloch:b1.derivation.ground[0]',
    '\\beta': 'q3-bloch:b1.derivation.ground[0]',
    '\\hat n': 'q3-bloch:b2',
    n_x: 'q3-bloch:b2',
    n_y: 'q3-bloch:b2',
    '|-n\\rangle': 'q3-bloch:b3',
    P: 'q3-bloch.play.q3-s-theta',
    'P_+z': 'q3-spin-operators:b1',
    'P_-z': 'q3-spin-operators:b1',
    S_z: 'q3-spin-operators:b3',
    S_x: 'q3-spin-operators:b4',
    S_y: 'q3-spin-operators:b4',
    '\\sigma_x': 'q3-spin-operators:b5',
    '\\sigma_y': 'q3-spin-operators:b5',
    '\\sigma_z': 'q3-spin-operators:b5',
    '\\sigma_n': 'q3-spin-operators:b5',
    '\\vec\\sigma': 'q3-spin-operators:b5',
    '\\hbar': 'q3-spin-operators:b3',
    S_i: 'q3-spin-operators:b3',
    '\\sigma_i': 'q3-spin-operators:b5',
    S_n: 'q3-spin-operators:b5',
    'P_+n': 'q3-spin-operators:b5',
    'P_-n': 'q3-spin-operators:b5',
    c: 'q3-spin-operators:b6',
    s: 'q3-spin-operators:b6',
    '|+y\\rangle': 'q3-spin-operators.play.q3-o-sy.options[0]',
    '|-y\\rangle': 'q3-spin-operators.play.q3-o-sy.hints[1]',
    'M_\\alpha': 'q3-observables:b2',
    'P_\\alpha': 'q3-observables:b2',
    '\\langle\\cdot\\rangle': 'q3-spin-operators:b6.derivation',
    '\\vec S': 'q3-spin-operators:b6.derivation',
    M: 'q3-observables:b2',
    A: 'q3-observables.review',
    B: 'q3-observables.review',
    '\\dagger': 'q3-observables:b4',
    a: 'q3-spectral:b1',
    '|a\\rangle': 'q3-spectral:b1',
    f: 'q3-spectral:b4',
    a_i: 'q3-spectral:b1',
    '|a_i\\rangle': 'q3-spectral:b1',
    a_1: 'q3-spectral:b2.derivation',
    '|a_1\\rangle': 'q3-spectral:b2.derivation.ground[0]',
    '|Aa_1\\rangle': 'q3-spectral:b2.derivation.ground[3]',
    '\\Delta': 'q3-spectral:b5.derivation',
    n_i: 'q3-spectral:b5.derivation',
    '|b\\rangle': 'q3-uncertainty:b3',
    '|\\langle[A,B]\\rangle': 'q3-uncertainty:b4.derivation',
    '|\\langle\\DeltaA\\,\\DeltaB\\rangle': 'q3-uncertainty:b4.derivation.ground[2]',
    '|^2+\\tfrac14\\langle\\DeltaA\\,\\DeltaB+\\DeltaB\\,\\DeltaA\\rangle': 'q3-uncertainty:b4',
    S_j: 'q3-uncertainty.review',
    '\\epsilon_ijk': 'q3-uncertainty.review',
    S_k: 'q3-uncertainty.review',
    '|\\langle[S_x,S_y]\\rangle': 'q3-uncertainty.play.q3-u-floor',
    '|\\langleS_z\\rangle': 'q3-uncertainty.play.q3-u-which',
    b: 'q3-uncertainty.play.q3-u-schwarz',
  },
  symbolsFormal: {
    'P_α|β': 'q3-born:b1',
    '\\langle\\cdot|\\cdot\\rangle': 'q3-born:b2.derivation.formal[0]',
    P_i: 'q3-born:b3',
    I: 'q3-born:b3',
    P_j: 'q3-born:b4',
    p_j: 'q3-born:b4',
    '|\\theta,\\varphi\\rangle': 'q3-bloch:b1',
    '\\leftrightarrow': 'q3-bloch:b1',
    S: 'q3-bloch:b1',
    '\\alpha': 'q3-bloch:b1.derivation.formal[0]',
    '\\beta': 'q3-bloch:b1.derivation.formal[0]',
    S_i: 'q3-spin-operators:b3',
    '\\hbar': 'q3-spin-operators:b3',
    '\\sigma_i': 'q3-spin-operators:b5',
    S_n: 'q3-spin-operators:b5',
    'P_+n': 'q3-spin-operators:b5',
    'P_-n': 'q3-spin-operators:b5',
    M: 'q3-observables:b2',
    '\\dagger': 'q3-observables:b4',
    '\\mathbb': 'q3-observables:b5',
    R: 'q3-observables:b5',
    C: 'q3-observables:b5',
    '\\forall': 'q3-observables:b5',
    a_i: 'q3-spectral:b1',
    '|a_i\\rangle': 'q3-spectral:b1',
    '|a_1\\rangle': 'q3-spectral:b2.derivation.formal[0]',
    '|Aa_1\\rangle': 'q3-spectral:b2.derivation.formal[0]',
    '|\\langle\\DeltaA\\,\\DeltaB\\rangle': 'q3-uncertainty:b4.derivation.formal[0]',
  },
  corrections: [
    {
      where: 'notes p. 17',
      says: 'The notes reuse p. 9’s symbol Û with the opposite order, saying Û†ÂÛ is the diagonal table in the new (eigenvector) basis.',
      shouldSay: 'With p. 9’s Û (Û_ij = ⟨α′_i|α_j⟩, the change of basis to the eigenbasis), the diagonal table is ÛÂÛ†, exactly as p. 9’s own rule Â′ = ÛÂÛ† says. Û†ÂÛ is diagonal only when Û’s COLUMNS are the eigenvectors — the transpose of p. 9’s convention.',
      check: () => V.q3DiagUAUdIsDiag === 1 && V.q3DiagUdAUIsDiag === 0,
    },
  ],
  units: [
    {
      id: 'q3-born',
      story: Q3_STORY['q3-born'],
      review: Q3_REVIEW['q3-born'],
      title: 'Chances from overlaps and projectors',
      question: 'How does an overlap become a chance, and how does an operator hold it?',
      lecture: {
        pages: 'notes p. 11',
        summary: 'The Born rule for any two states, written as a projector sandwich; a basis’s projectors add to the identity.',
      },
      books: [
        { source: 'bergou', where: '§5.2, p. 80', adds: 'The same rule as a postulate: P²=P, and the state after a result is the rescaled projection.' },
        { source: 'nc', where: 'Eqs. 2.103–2.104, p. 88; Eq. 2.22, p. 67', adds: 'The probability and post-measurement state for a projective measurement, and completeness for an ON basis.' },
      ],
      visual: {
        kind: 'projector',
        props: { state: 30, basis: 45, editableBasis: true },
        tryThis: [`Read ${d(V.q3BornPlus, 3)} and ${d(V.q3BornMinus, 3)}.`, 'Turn the basis to 30°: one shadow is the whole arrow.'],
      },
      clues: [],
      insight: 'A chance is a projector sandwich, ⟨ψ|P|ψ⟩. A basis’s projectors add to I, so its chances add to 1, and the state after a result is the projection, rescaled.',
      insightFormal:
        '$P_M = |M\\rangle\\langle M|$ gives $p_M = \\langle\\psi|P_M|\\psi\\rangle$, an idempotent, self-adjoint operator; $\\sum_i P_i = I$ for a complete basis, and $P_j|\\psi\\rangle/\\sqrt{p_j}$ is the post-measurement state.',
      pitfalls: ['Thinking a phase on |M⟩ changes the chance: a projector, like a probability, depends only on the ray.'],
      play: [
        {
          id: 'q3-b-overlap',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The notes’ own example',
          prompt: 'What is $|\\langle{+x}|{+z}\\rangle|^2$?',
          answer: V.q3Pzx,
          tolerance: 0.005,
          hints: [{ text: '$\\langle{+x}| = (1, 1)/\\sqrt2$.' }, { text: '$\\langle{+x}|{+z}\\rangle = 1/\\sqrt2$.' }, { text: 'Square it.' }],
          walkthrough: [{ text: `${d(V.q3Pzx, 1)}, the notes’ example.` }],
        },
        {
          id: 'q3-b-sandwich',
          kind: 'numeric',
          tier: 'core',
          title: 'The sandwich',
          prompt: '$\\psi = (0.6, 0.8)$. What is $\\langle\\psi|P_{+x}|\\psi\\rangle$?',
          answer: V.q3BSandwich,
          tolerance: 0.005,
          hints: [{ text: 'It equals $|\\langle{+x}|\\psi\\rangle|^2$.' }, { text: '$\\langle{+x}|\\psi\\rangle = 1.4/\\sqrt2$.' }, { text: '$1.96/2$.' }],
          walkthrough: [{ text: `${d(V.q3BSandwich, 2)}.` }],
        },
        {
          id: 'q3-b-phase',
          kind: 'numeric',
          tier: 'core',
          title: 'A phase inside ψ',
          prompt: '$\\psi = (0.6, 0.8i)$. What is $\\langle\\psi|P_{-x}|\\psi\\rangle$?',
          answer: V.q3BPhase,
          tolerance: 0.005,
          hints: [{ text: '$\\langle{-x}|\\psi\\rangle = (0.6 - 0.8i)/\\sqrt2$.' }, { text: 'Size squared, not square.' }, { text: '$(0.36 + 0.64)/2$.' }],
          walkthrough: [{ text: `${uf(V.q3BPhase)}: a quarter-turn phase gives 50/50 along x.` }],
        },
        {
          id: 'q3-b-missing',
          kind: 'numeric',
          tier: 'stretch',
          title: 'One projector alone',
          prompt: 'Keep only $P_{+x}$ of the x basis. What is $\\langle\\psi|P_{+x}|\\psi\\rangle$ for $\\psi = (0.866, 0.5)$?',
          answer: V.q3BornPlus,
          tolerance: 0.005,
          hints: [{ text: 'One projector alone.' }, { text: 'It is below 1.' }, { text: 'The rest belongs to $P_{-x}$.' }],
          walkthrough: [{ text: `${d(V.q3BornPlus, 3)}; with $P_{-x}$ (${d(V.q3BornMinus, 3)}) the total is 1: completeness.` }],
        },
      ],
    },
    {
      id: 'q3-bloch',
      story: Q3_STORY['q3-bloch'],
      review: Q3_REVIEW['q3-bloch'],
      title: 'Every spin state is a point on a sphere',
      question: 'Which two angles fix any spin state, and where is its opposite?',
      lecture: {
        pages: 'notes p. 12, Eqs. 1.4–1.5',
        summary: 'Every spin state, up to a global phase, is |+n⟩ = |θ, φ⟩: a point n̂ on a sphere of radius 1. The opposite point is an [[orthogonal|orthogonal]] state.',
      },
      books: [
        { source: 'bergou', where: 'Eq. 1.2, p. 2', adds: 'The same two-angle form of a qubit state.' },
        { source: 'nc', where: 'Eq. 1.4, p. 15', adds: 'The identical parametrization, up to a global phase.' },
      ],
      visual: {
        kind: 'bloch',
        props: { theta: 60, phi: 45, editable: true, landmarks: true, measure: 'z' },
        tryThis: ['θ = 90°: which φ gives |+y⟩?', 'Opposite points: compare the z bars.'],
      },
      clues: [],
      insight: 'Two angles place any spin state on a sphere of radius 1. The opposite point is a state at right angles, not the state with a flipped sign.',
      insightFormal: '$|{+n}\\rangle = |\\theta,\\varphi\\rangle \\leftrightarrow \\hat n \\in S^2$ is one-to-one on rays; the antipode $|{-n}\\rangle$ satisfies $\\langle{+n}|{-n}\\rangle = 0$.',
      pitfalls: ['Taking −|+z⟩ for the south pole: it is |+z⟩ again, the same point.'],
      play: [
        {
          id: 'q3-s-theta',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Which angle?',
          prompt: 'Which polar angle θ, in degrees, gives $P({+z}) = 0.75$?',
          answer: V.q3STheta,
          tolerance: 1,
          unit: '°',
          hints: [{ text: '$P({+z}) = \\cos^2(\\theta/2)$.' }, { text: '$\\cos(\\theta/2) = 0.866$.' }, { text: '$\\theta/2 = 30°$.' }],
          walkthrough: [{ text: `${d(V.q3STheta, 0)}°.` }],
        },
        {
          id: 'q3-s-nx',
          kind: 'numeric',
          tier: 'core',
          title: 'One component of n̂',
          prompt: 'For $\\theta = 90°$, $\\varphi = 60°$, what is $n_x$?',
          answer: V.q3SNx,
          tolerance: 0.005,
          hints: [{ text: '$n_x = \\sin\\theta\\cos\\varphi$.' }, { text: '$\\sin 90° = 1$.' }, { text: '$\\cos 60°$.' }],
          walkthrough: [{ text: `${d(V.q3SNx, 1)}.` }],
        },
        {
          id: 'q3-s-minus',
          kind: 'numeric',
          tier: 'core',
          title: 'The opposite state',
          prompt: 'For $\\theta = 60°$, $\\varphi = 0$, what is the $|{+z}\\rangle$ amplitude of $|{-n}\\rangle$?',
          answer: V.q3SMinus,
          tolerance: 0.005,
          hints: [{ text: 'Eq. 1.5.' }, { text: 'It is $\\sin(\\theta/2)$.' }, { text: '$\\sin 30°$.' }],
          walkthrough: [{ text: `${d(V.q3SMinus, 1)}: $|{-n}\\rangle = (${d(V.q3SMinus, 1)}, -${d(V.q3SMinusBetaAbs, 3)})$.` }],
        },
        {
          id: 'q3-s-120',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Below the equator',
          prompt: 'For $\\theta = 120°$, $\\varphi = 0$, what is $|\\langle{+z}|{+n}\\rangle|^2$?',
          answer: V.q3S120,
          tolerance: 0.005,
          hints: [{ text: '$\\cos^2(\\theta/2)$.' }, { text: '$\\theta/2 = 60°$.' }, { text: '$0.5^2$.' }],
          walkthrough: [{ text: `${uf(V.q3S120)}: below the equator, down is more likely.` }],
        },
      ],
    },
    {
      id: 'q3-spin-operators',
      story: Q3_STORY['q3-spin-operators'],
      review: Q3_REVIEW['q3-spin-operators'],
      title: 'Spin operators built from projectors',
      question: 'How do Stern–Gerlach filters build S_z, S_x, S_y and S_n?',
      lecture: {
        pages: 'notes pp. 12–14, Eqs. 1.6–1.8',
        summary: 'A filter is a projector; weighting each outcome’s projector by its reading builds the spin operator. Out comes the Pauli matrices and S_n = (ħ/2)n̂·σ⃗.',
      },
      books: [{ source: 'nc', where: 'Fig. 2.2; Ex. 2.60, p. 90', adds: 'The general σ_n = n̂·σ⃗ and its ±1 eigenvalues, matched to N&C’s ±ħ/2 convention.' }],
      visual: {
        kind: 'operator-builder',
        props: { axis: 'z' },
        tryThis: ['Do the projectors add to I?', 'Tilt: the matrices fill in, the checks stay ✓.'],
      },
      clues: [],
      insight: 'A filter is a projector; weighting its outcomes by ±ħ/2 and adding gives the spin operator. S_n = (ħ/2)n̂·σ⃗ for any axis n̂.',
      insightFormal: '$S_i = \\tfrac\\hbar2\\sigma_i$ and $S_n = \\tfrac\\hbar2(P_{+n} - P_{-n}) = \\tfrac\\hbar2\\hat n\\cdot\\vec\\sigma$, basis-free although P̂’s table is basis-dependent.',
      pitfalls: ['Reading equal tables as the same operator: P_{+z} in x and P_{+x} in z share four entries, yet P_{+z}|+z⟩ = |+z⟩ while P_{+x}|+z⟩ does not.'],
      play: [
        {
          id: 'q3-o-pz',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Apply the filter',
          prompt: 'Apply $P_{+z}$ to $(0.6, 0.8)$. How long is the result?',
          answer: V.q3OPz,
          tolerance: 0.005,
          hints: [{ text: '$P_{+z}$ keeps the first entry.' }, { text: '$(0.6, 0)$.' }, { text: 'Its length.' }],
          walkthrough: [{ text: `${d(V.q3OPz, 1)}; squared, the chance ${d(V.q3OPz * V.q3OPz, 2)}.` }],
        },
        {
          id: 'q3-o-sigman',
          kind: 'numeric',
          tier: 'core',
          title: 'One entry of σ_n',
          prompt: 'For $\\theta = 60°$, what is the top-left entry of $\\sigma_n$?',
          answer: V.q3OSigmaN,
          tolerance: 0.005,
          hints: [{ text: 'Eq. 1.7.' }, { text: 'It is $\\cos\\theta$.' }, { text: '$\\cos 60°$.' }],
          walkthrough: [{ text: `${d(V.q3OSigmaN, 1)}.` }],
        },
        {
          id: 'q3-o-sy',
          kind: 'choice',
          tier: 'core',
          title: 'Which table is σ_y?',
          prompt: 'Which table is $\\sigma_y$?',
          options: [
            { text: '$[[0, -i], [i, 0]]$', correct: true, why: 'Right: it sends $(1, i)$ to $(1, i)$, so $|{+y}\\rangle$ is its eigenvector.' },
            { text: '$[[0, i], [i, 0]]$', correct: false, why: 'Not Hermitian: the corners are not conjugates (it is $i\\sigma_x$).' },
            { text: '$[[0, 1], [-1, 0]]$', correct: false, why: 'A real quarter turn (−J), not Hermitian.' },
            { text: '$[[0, i], [-i, 0]]$', correct: false, why: 'This is $-\\sigma_y$.' },
          ],
          hints: [{ text: 'It must be Hermitian.' }, { text: 'Its eigenvectors are $|\\pm y\\rangle$.' }, { text: 'Apply it to $(1, i)$.' }],
          walkthrough: [{ text: '$[[0, -i], [i, 0]]$ sends $(1, i)$ to $(1, i)$.' }],
        },
        {
          id: 'q3-o-px',
          kind: 'numeric',
          tier: 'stretch',
          title: 'One entry of P_{+x}',
          prompt: 'What is the top-right entry of $P_{+x}$ in the z basis?',
          answer: V.q3OPx,
          tolerance: 0.005,
          hints: [{ text: '$P_{+x} = |{+x}\\rangle\\langle{+x}|$.' }, { text: '$(1/\\sqrt2)(1/\\sqrt2)$.' }, { text: 'Every entry is ½.' }],
          walkthrough: [{ text: `${uf(V.q3OPx)}; P_{+z} in the x basis has the same entries (this unit’s clue).` }],
        },
      ],
    },
    {
      id: 'q3-observables',
      story: Q3_STORY['q3-observables'],
      review: Q3_REVIEW['q3-observables'],
      title: 'Measurement rules and why observables are Hermitian',
      question: 'What does a measurement do to a state, what is its average, and why is its operator Hermitian?',
      lecture: {
        pages: 'notes pp. 14–15',
        summary: 'A measurement jumps the state to the outcome’s state. An observable’s operator has its readings times their projectors, and real averages force it to be Hermitian.',
      },
      books: [
        { source: 'bergou', where: 'Eq. 2.20, p. 19', adds: 'The Bloch vector as three averages, n_j = Tr(ρσ_j).' },
        { source: 'axler', where: '7.1, p. 228; 7.5, p. 230; 7.13–7.14, p. 234', adds: 'The adjoint’s definition and rules, and the theorem that real averages force Hermiticity over ℂ.' },
      ],
      visual: {
        kind: 'deposit-stats',
        props: { state: '+x', axis: 'z', seed: 709 },
        tryThis: ['Fire 10, then 100 atoms: the average’s scatter shrinks.', 'Every single reading is still ±ħ/2.'],
      },
      clues: [],
      insight: 'A measurement jumps the state to the result’s state. The average is Σ value × chance, and real averages in every state force an observable’s operator to be Hermitian.',
      insightFormal:
        '$\\langle M\\rangle = \\langle\\psi|M|\\psi\\rangle = \\sum_\\alpha M_\\alpha P_\\alpha$; $\\langle\\psi|M|\\psi\\rangle \\in \\mathbb{R}\\ \\forall\\psi \\Rightarrow M = M^\\dagger$ over $\\mathbb{C}$ (Axler 7.13–7.14).',
      pitfalls: ['Checking Hermiticity on real arrows only: the quarter turn J passes there, yet ⟨+y|J|+y⟩ = −i.'],
      play: [
        {
          id: 'q3-m-avg',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A weighted average',
          prompt: 'Readings $+\\hbar/2$ with chance 0.9 and $-\\hbar/2$ with 0.1. What is $\\langle S_z\\rangle$, in units of ħ?',
          answer: V.q3MAvg,
          tolerance: 0.005,
          unit: 'ħ',
          hints: [{ text: 'Value times chance, added.' }, { text: '$0.5 \\times 0.9 - 0.5 \\times 0.1$.' }, { text: '$0.45 - 0.05$.' }],
          walkthrough: [{ text: `${d(V.q3MAvg, 1)}ħ.` }],
        },
        {
          id: 'q3-m-sx',
          kind: 'numeric',
          tier: 'core',
          title: 'One average for |+n⟩',
          prompt: 'For $|{+n}\\rangle$ ($\\theta = 60°$, $\\varphi = 45°$), what is $\\langle S_x\\rangle$ in units of ħ?',
          answer: V.q3AvgSx,
          tolerance: 0.005,
          unit: 'ħ',
          hints: [{ text: '$\\langle S_x\\rangle = \\tfrac\\hbar2 n_x$.' }, { text: '$n_x = \\sin 60°\\cos 45°$.' }, { text: '$0.5 \\times 0.612$.' }],
          walkthrough: [{ text: `${d(V.q3AvgSx, 3)}ħ (D3).` }],
        },
        {
          id: 'q3-m-adjoint',
          kind: 'choice',
          tier: 'core',
          title: 'The adjoint of a product',
          prompt: 'What is $(AB)^\\dagger$?',
          options: [
            { text: '$A^\\dagger B^\\dagger$', correct: false, why: 'The order must reverse.' },
            { text: '$B^\\dagger A^\\dagger$', correct: true, why: 'Right: take the adjoint of $A(B|\\alpha\\rangle)$.' },
            { text: '$(BA)^*$', correct: false, why: 'The adjoint conjugates AND transposes, not just conjugates.' },
            { text: '$A^*B^*$', correct: false, why: 'The order and the transpose are both missing.' },
          ],
          hints: [{ text: 'Take the adjoint of $A(B|\\alpha\\rangle)$.' }, { text: 'The bra of $B|\\alpha\\rangle$ is $\\langle\\alpha|B^\\dagger$.' }, { text: 'Then A acts inside.' }],
          walkthrough: [{ text: '$\\langle\\alpha|(AB)^\\dagger = \\langle\\alpha|B^\\dagger A^\\dagger$.' }],
        },
        {
          id: 'q3-m-hermitian',
          kind: 'choice',
          tier: 'stretch',
          title: 'Which table is an observable?',
          prompt: 'Which table can be an observable?',
          options: [
            { text: '$[[1, 2-i], [2+i, -3]]$', correct: true, why: 'Right: it equals its own adjoint.' },
            { text: '$[[0, 1], [0, 0]]$', correct: false, why: 'Its adjoint is $[[0,0],[1,0]]$, a different table.' },
            { text: '$[[0, -1], [1, 0]]$', correct: false, why: 'The real quarter turn J: its adjoint is its negative.' },
            { text: '$[[1, i], [i, 1]]$', correct: false, why: 'The corners must be conjugates: $i \\ne -i$.' },
          ],
          hints: [{ text: 'Mirror and conjugate.' }, { text: 'The corners must be conjugates.' }, { text: '$i$ and $i$ are not.' }],
          walkthrough: [{ text: 'Only $[[1, 2-i], [2+i, -3]]$ equals its own adjoint.' }],
        },
      ],
    },
    {
      id: 'q3-spectral',
      story: Q3_STORY['q3-spectral'],
      review: Q3_REVIEW['q3-spectral'],
      title: 'Real eigenvalues, spectral form and spread',
      question: 'Why are an observable’s values real, and how do its eigenvectors give powers and spreads?',
      lecture: {
        pages: 'notes pp. 17–18',
        summary: 'A Hermitian operator has real eigenvalues and an orthonormal eigenbasis, in which its table is diagonal; powers and the dispersion follow from the same spectrum.',
      },
      books: [
        { source: 'axler', where: '5.5, p. 134; 7.12, p. 233; 7.22, p. 238; 7.31, p. 246', adds: 'The eigenvalue equation, real eigenvalues of a self-adjoint operator, orthogonality of eigenvectors of distinct eigenvalues, and the resulting ON eigenbasis.' },
        { source: 'nc', where: 'Box 2.2, p. 72', adds: 'The spectral theorem and functions of a Hermitian operator, boxed the same way.' },
      ],
      visual: {
        kind: 'bloch',
        props: { theta: 60, phi: 45, editable: true, measure: 'x' },
        tryThis: ['θ = 0: which spread is zero?', 'θ = 90°: what is (ΔS_z)²?'],
      },
      clues: [],
      insight: 'A Hermitian operator’s eigenvalues are real, and its eigenvectors form an orthonormal basis in which its table is diagonal. The dispersion (ΔA)² measures how widely readings scatter.',
      insightFormal:
        '$A = A^\\dagger \\Rightarrow a_i \\in \\mathbb{R}$; $A = \\sum_i a_i|a_i\\rangle\\langle a_i|$, $f(A) = \\sum_i f(a_i)|a_i\\rangle\\langle a_i|$; $(\\Delta S_i)^2 = \\tfrac{\\hbar^2}4(1 - n_i^2)$ for $|{+n}\\rangle$.',
      pitfalls: ['Diagonalizing with the wrong side of U: the diagonal table is UAU†, not Û†ÂÛ with p. 9’s Û (see the errata box).'],
      play: [
        {
          id: 'q3-e-eig',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The larger eigenvalue',
          prompt: 'What is the larger eigenvalue of $[[1, 2-i], [2+i, -3]]$?',
          answer: V.q3EEig,
          tolerance: 0.005,
          hints: [{ text: '$\\det(M - aI) = 0$.' }, { text: '$a^2 + 2a - 8 = 0$.' }, { text: 'Factor.' }],
          walkthrough: [{ text: `$(a - ${d(V.q3EEig, 0)})(a + 4) = 0$.` }],
        },
        {
          id: 'q3-e-disp',
          kind: 'numeric',
          tier: 'core',
          title: 'One dispersion',
          prompt: 'For $|{+n}\\rangle$ at $\\theta = 60°$, what is $(\\Delta S_z)^2$ in units of ħ²?',
          answer: V.q3VarSz,
          tolerance: 0.005,
          unit: 'ħ²',
          hints: [{ text: '$\\langle S_z^2\\rangle = \\hbar^2/4$.' }, { text: '$\\langle S_z\\rangle = 0.25\\hbar$.' }, { text: '$0.25 - 0.0625$.' }],
          walkthrough: [{ text: `${d(V.q3VarSz, 4)}ħ² (D4).` }],
        },
        {
          id: 'q3-e-f',
          kind: 'numeric',
          tier: 'core',
          title: 'A function of S_z',
          prompt: 'With $f(a) = a^2$, what is the top-left entry of $f(S_z)$, in units of ħ²?',
          answer: V.q3F,
          tolerance: 0.005,
          unit: 'ħ²',
          hints: [{ text: '$f$ acts on the eigenvalues.' }, { text: '$(\\pm\\tfrac12)^2 = \\tfrac14$.' }, { text: 'Both entries equal.' }],
          walkthrough: [{ text: `S_z² = (ħ²/4)I, so ${d(V.q3F, 2)}.` }],
        },
        {
          id: 'q3-e-spread-x',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The other spread',
          prompt: 'For $|{+n}\\rangle$ ($\\theta = 60°$, $\\varphi = 45°$), what is $(\\Delta S_x)^2$ in units of ħ²?',
          answer: V.q3VarXY,
          tolerance: 0.005,
          unit: 'ħ²',
          hints: [{ text: '$(\\hbar^2/4)(1 - n_x^2)$.' }, { text: '$n_x = 0.612$.' }, { text: '$n_x^2 = 0.375$.' }],
          walkthrough: [{ text: `$0.25 \\times 0.625 = ${d(V.q3VarXY, 5)}$.` }],
        },
      ],
    },
    {
      id: 'q3-uncertainty',
      story: Q3_STORY['q3-uncertainty'],
      review: Q3_REVIEW['q3-uncertainty'],
      title: 'Commutators and the floor under two spreads',
      question: 'When can two quantities both be sharp, and how small can two spreads be together?',
      lecture: {
        pages: 'notes pp. 18–20, Eqs. 1.9–1.10',
        summary: 'Commuting operators are compatible and share an eigenbasis; the Schwarz inequality, applied to shifted operators, gives a floor under the product of two spreads.',
      },
      books: [
        { source: 'axler', where: '6.14, p. 189; 5.76, p. 176', adds: 'The Cauchy–Schwarz inequality, and simultaneous diagonalization of commuting (here self-adjoint) diagonalizable operators.' },
        { source: 'nc', where: 'Thm 2.2, p. 77; Box 2.4, p. 89; Ex. 2.59, p. 90', adds: 'The simultaneous-diagonalization theorem, the "spread, not disturbance" reading, and a worked example on |+z⟩.' },
      ],
      visual: {
        kind: 'bloch',
        props: { theta: 90, phi: 0, editable: true, landmarks: true },
        tryThis: ['Stay on the x–z circle (φ = 0): is the product on the floor?', 'Move to φ = 45°.'],
      },
      clues: [],
      insight: 'Two observables are compatible when their operators commute. The product of two spreads is bounded below by a quarter of their commutator’s average, a state-dependent floor.',
      insightFormal:
        '$[A,B] = 0$ ⟺ shared eigenbasis (non-degenerate case); $\\langle(\\Delta A)^2\\rangle\\langle(\\Delta B)^2\\rangle \\ge \\tfrac14|\\langle[A,B]\\rangle|^2$, with equality for spin-½ pure states exactly when $n_xn_y = 0$ (e.g. $|{\\pm z}\\rangle$).',
      pitfalls: ['Reading a zero floor as compatibility: [S_x, S_y] is never the zero operator, though the bound vanishes for |+x⟩.'],
      play: [
        {
          id: 'q3-u-comm',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'One commutator average',
          prompt: 'For $|{+z}\\rangle$, what is the imaginary part of $\\langle[S_x, S_y]\\rangle$, in units of ħ²?',
          answer: V.q3UComm,
          tolerance: 0.005,
          unit: 'ħ²',
          hints: [{ text: '$[S_x, S_y] = i\\hbar S_z$.' }, { text: '$\\langle S_z\\rangle = \\hbar/2$.' }, { text: '$i \\times \\tfrac12$.' }],
          walkthrough: [{ text: `${d(V.q3UComm, 1)}iħ².` }],
        },
        {
          id: 'q3-u-floor',
          kind: 'numeric',
          tier: 'core',
          title: 'The floor itself',
          prompt: 'For $|{+n}\\rangle$ ($\\theta = 60°$, $\\varphi = 45°$), what is $\\tfrac14|\\langle[S_x, S_y]\\rangle|^2$, in units of ħ⁴?',
          answer: V.q3RobBoundSq,
          tolerance: 0.00005,
          unit: 'ħ⁴',
          hints: [{ text: '$\\langle[S_x, S_y]\\rangle = i\\hbar\\langle S_z\\rangle$.' }, { text: '$\\langle S_z\\rangle = 0.25\\hbar$.' }, { text: '$\\tfrac14 \\times 0.0625$.' }],
          walkthrough: [{ text: `1/64 = ${d(V.q3RobBoundSq, 6)}.` }],
        },
        {
          id: 'q3-u-which',
          kind: 'choice',
          tier: 'core',
          title: 'On the floor',
          prompt: 'Which states put $\\Delta S_x\\Delta S_y$ exactly on the floor $\\tfrac\\hbar2|\\langle S_z\\rangle|$?',
          options: [
            { text: 'every state with $n_x = 0$ or $n_y = 0$', correct: true, why: 'Right: the gap between the two sides is $n_x^2n_y^2/16$, which vanishes exactly there.' },
            { text: 'only $|\\pm z\\rangle$', correct: false, why: '|+n⟩ at φ = 0 (n_y = 0) or φ = 90° (n_x = 0) also saturate it, for any θ.' },
            { text: 'no state', correct: false, why: '|+z⟩ itself saturates it (this unit’s b5).' },
            { text: 'every state', correct: false, why: 'For |+n⟩ at φ = 45°, the product sits above the floor.' },
          ],
          hints: [{ text: 'Product² = (1 − n_x²)(1 − n_y²)/16.' }, { text: 'Floor² = n_z²/16.' }, { text: 'Expand with n_x² + n_y² + n_z² = 1.' }],
          walkthrough: [{ text: 'The gap is n_x²n_y²/16, zero exactly when n_x = 0 or n_y = 0.' }],
        },
        {
          id: 'q3-u-schwarz',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Schwarz by hand',
          prompt: '$a = (1, i)$, $b = (2, 1)$. What is $|\\langle a|b\\rangle|^2$?',
          answer: V.q3SchwarzLHS,
          tolerance: 0.005,
          hints: [{ text: 'Conjugate a.' }, { text: '$1 \\times 2 + (-i) \\times 1$.' }, { text: '$|2 - i|^2$.' }],
          walkthrough: [{ text: `${d(V.q3SchwarzLHS, 0)} ≤ ${d(V.q3SchwarzRHS, 0)}.` }],
        },
        {
          id: 'q3-u-steps',
          kind: 'order',
          tier: 'stretch',
          title: 'The proof of Eq. 1.10',
          prompt: 'Put the proof of Eq. 1.10 in order.',
          steps: [
            'Set |a⟩ = ΔA|ψ⟩ and |b⟩ = ΔB|ψ⟩.',
            'Schwarz: ⟨a|a⟩⟨b|b⟩ ≥ |⟨a|b⟩|².',
            'Split ΔAΔB into half a commutator and half an anticommutator.',
            'The first part’s average is imaginary, the second’s real.',
            'Drop the real part’s square.',
          ],
          hints: [{ text: 'Name the vectors first.' }, { text: 'The inequality comes before the split.' }, { text: 'Dropping comes last.' }],
          walkthrough: [{ text: 'This is D5, step by step.' }],
        },
      ],
    },
  ],
}
