import type { Lecture } from '../schema'
import { Q4_REVIEW } from './Q4.review'
import { Q4_STORY } from './Q4.story'
import { V, d } from './Q4.values'

// Physics 709, chapter Q4: Bergou §1.1-1.3 (pp. 1-5) with N&C §1.2-1.3.6 (pp. 13-26) filling in where Bergou is
// silent, in both tracks. No 709 lecture notes cover Part II yet (only qc709-n1-n3 are ingested), so every [L] beat
// cites Bergou or N&C directly. Plan: docs/roles/proposals/P-Q4-story.md; rulings docs/roles/decisions/qc709-Q4Q5.md.
// Engine defect E1 (a one-qubit runCircuit corrupting the shared KET constants) was fixed on main before this build
// (ae8ef58): `qc/state.ts` `ket()` returns a fresh array every call.

export const Q4: Lecture = {
  id: 'Q4',
  number: 4,
  title: 'The qubit, gates and circuits',
  outcomes: [
    'Write a qubit as α|0⟩ + β|1⟩, read its chances, and place it on the sphere.',
    'Apply X, Z, H and phase gates as tables and as turns of the sphere.',
    'Build a two-qubit state by multiplying amplitudes, and count the 2ⁿ amplitudes of n qubits.',
    'Use CNOT’s truth table and matrix, and say why every gate is reversible.',
    'Read a circuit left to right, multiply its matrices right to left, and build a Bell pair and a SWAP.',
    'Read all or one of a register’s qubits, and find the state left behind.',
  ],
  prerequisites: ['qc-superposition', 'qc-operator-matrix', 'qc-change-of-basis', 'qc-x-states', 'qc-born-projector', 'qc-bloch-sphere', 'qc-spin-operators', 'qc-euler', 'qc-phase'],
  symbols: {
    '|0\\rangle': 'q4-qubit:b1',
    '|1\\rangle': 'q4-qubit:b1',
    '\\alpha': 'q4-qubit:b1',
    '\\beta': 'q4-qubit:b1',
    '|\\psi\\rangle': 'q4-qubit:b1',
    '|{+z}\\rangle': 'q4-qubit:b1',
    '|{-z}\\rangle': 'q4-qubit:b1',
    '|{+}\\rangle': 'q4-qubit:b4',
    '\\theta': 'q4-qubit:b3',
    '\\varphi': 'q4-qubit:b3',
    X: 'q4-one-qubit-gates:b1',
    'U^\\dagger U = I': 'q4-one-qubit-gates:b2',
    Z: 'q4-one-qubit-gates:b3',
    '\\hat n': 'q4-one-qubit-gates:b3',
    '\\vec\\sigma': 'q4-one-qubit-gates:b3',
    H: 'q4-one-qubit-gates:b4',
    'R_z': 'q4-one-qubit-gates:b6',
    '\\chi': 'q4-one-qubit-gates:b6',
    'P(\\chi)': 'q4-one-qubit-gates:b6',
    S: 'q4-one-qubit-gates:b6',
    T: 'q4-one-qubit-gates:b6',
    '|00\\rangle': 'q4-registers:b1',
    '|01\\rangle': 'q4-registers:b1',
    '|10\\rangle': 'q4-registers:b1',
    '|11\\rangle': 'q4-registers:b1',
    x: 'q4-registers:b1',
    '\\otimes': 'q4-registers:b2',
    n: 'q4-registers:b3',
    '\\oplus': 'q4-cnot:b2',
    '\\Phi^+': 'q4-circuits:b2',
    U: 'q4-circuits:b4',
    '|\\Psi\\rangle': 'q4-registers:b3',
    'c_x': 'q4-measure:b1',
  },
  symbolsFormal: {
    'e^{i\\gamma}': 'q4-qubit:b3',
    'R_n(\\chi)': 'q4-one-qubit-gates:b3',
    'R_y': 'q4-one-qubit-gates:b6',
    '\\gamma': 'q4-one-qubit-gates:b6',
    '\\delta': 'q4-one-qubit-gates:b6',
    'U_{CN}': 'q4-cnot:b3',
    '\\beta_{00}': 'q4-circuits:b2',
    'FANIN': 'q4-circuits:b5',
    'FANOUT': 'q4-circuits:b5',
  },
  units: [
    {
      id: 'q4-qubit',
      story: Q4_STORY['q4-qubit'],
      review: Q4_REVIEW['q4-qubit'],
      title: 'From a bit to a qubit',
      question: 'What can a qubit hold that a bit cannot, and what does reading it give?',
      lecture: {
        pages: 'Bergou §1.1, pp. 1–2, Eqs. 1.1–1.2; N&C §1.2, pp. 13–16, Eqs. 1.1–1.4',
        summary: 'A qubit is a two-level system, α|0⟩ + β|1⟩; reading it gives one bit with the Born-rule chances, and it is a point on the sphere.',
      },
      books: [
        { source: 'bergou', where: '§1.1, pp. 1–2, Eqs. 1.1–1.2', adds: 'The qubit as a unit vector of ℂ², and any two-level system as a candidate.' },
        { source: 'nc', where: '§1.2, pp. 13–16, Eqs. 1.1–1.4, Figs. 1.2–1.3', adds: 'The same definition, plus an atomic two-level system prepared by a light pulse.' },
      ],
      visual: {
        kind: 'amplitude-bars',
        props: { state: [60, 0], basis: 'z', editable: true },
        tryThis: ['Make the chances 0.5 and 0.5.', 'Keep θ, change φ: do the chances move?'],
      },
      clues: [],
      insight: 'A qubit is α|0⟩ + β|1⟩, with |0⟩ = |+z⟩. Reading gives 0 or 1 with chances |α|² and |β|², and one reading gives one bit.',
      insightFormal: 'A unit vector of $\\mathbb{C}^2$ up to global phase; a computational-basis measurement returns $x$ w.p. $|\\alpha_x|^2$ and collapses to $|x\\rangle$, so many identical copies are needed to estimate $\\alpha, \\beta$.',
      pitfalls: ['Thinking a qubit stores its angles for reading: one reading gives one bit, not the angles themselves.'],
      play: [
        {
          id: 'q4-q-p1',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'One chance from the other',
          prompt: 'A qubit is 0.6|0⟩ + 0.8|1⟩. What is the chance of reading 1?',
          answer: V.q4ChP1,
          tolerance: 0.005,
          hints: [{ text: 'A chance is a size squared.' }, { text: 'The |1⟩ amplitude is 0.8.' }, { text: 'Square it.' }],
          walkthrough: [{ text: `${d(V.q4ChP1, 2)}; the chance of 0 is 0.36.` }],
        },
        {
          id: 'q4-q-complex',
          kind: 'numeric',
          tier: 'core',
          title: 'A phase changes no chance',
          prompt: 'A qubit is 0.6|0⟩ + 0.8i|1⟩. What is the chance of reading 1?',
          answer: V.q4ChComplex,
          tolerance: 0.005,
          hints: [{ text: 'Size squared, not square.' }, { text: '|0.8i| = 0.8.' }, { text: '0.8².' }],
          walkthrough: [{ text: `${d(V.q4ChComplex, 2)}: the phase i changes no chance.` }],
        },
        {
          id: 'q4-q-theta',
          kind: 'numeric',
          tier: 'core',
          title: 'Reading θ off a chance',
          prompt: 'A qubit reads 0 with chance 0.25. What is its polar angle θ, in degrees?',
          answer: V.q4ChTheta,
          tolerance: 1,
          unit: '°',
          hints: [{ text: 'P(0) = cos²(θ/2).' }, { text: 'cos(θ/2) = 0.5.' }, { text: 'θ/2 = 60°.' }],
          walkthrough: [{ text: `θ = ${d(V.q4ChTheta, 0)}°: below the equator, 1 is the likelier reading.` }],
        },
        {
          id: 'q4-q-phase',
          kind: 'choice',
          tier: 'stretch',
          title: 'The same state again',
          prompt: 'Which state is the same as ψ = 0.866|0⟩ + 0.5|1⟩?',
          options: [
            { text: '−0.866|0⟩ − 0.5|1⟩', correct: true, why: 'Right: this is −ψ = e^{iπ}ψ, a global phase; every chance and every later interference is unchanged.' },
            { text: '0.866|0⟩ − 0.5|1⟩', correct: false, why: 'This flips only the |1⟩ amplitude’s sign: a relative phase, a different point on the sphere.' },
            { text: '0.5|0⟩ + 0.866|1⟩', correct: false, why: 'This swaps the two chances: a different state entirely.' },
            { text: '0.866|0⟩ + 0.5i|1⟩', correct: false, why: 'This turns only the |1⟩ amplitude: a relative phase, not a global one.' },
          ],
          hints: [{ text: 'Which one is ψ times one number?' }, { text: 'A number of size 1.' }, { text: '−1.' }],
          walkthrough: [{ text: '−ψ is a global phase (Chapter F1); the other options move the point on the sphere.' }],
        },
      ],
    },
    {
      id: 'q4-one-qubit-gates',
      story: Q4_STORY['q4-one-qubit-gates'],
      review: Q4_REVIEW['q4-one-qubit-gates'],
      title: 'One-qubit gates turn the sphere',
      question: 'What does a gate do to one qubit, and why must it be unitary?',
      lecture: {
        pages: 'Bergou §1.2, pp. 3–4, Eqs. 1.5–1.8; N&C §1.3.1, pp. 17–20, Eqs. 1.8–1.17',
        summary: 'A gate is a unitary table. X swaps the amplitudes, Z flips a sign, H makes an even mix, and P(χ)/R_z(χ) turn the sphere about z.',
      },
      books: [
        { source: 'bergou', where: '§1.2, pp. 3–4, Eqs. 1.5–1.8', adds: 'X, the unitarity requirement, Z and H as tables.' },
        { source: 'nc', where: '§1.3.1, pp. 17–20, Eqs. 1.8–1.17, Fig. 1.4, Box 1.1', adds: 'Gates as rotations of the sphere, and the Z–Y decomposition of any one-qubit unitary.' },
      ],
      visual: {
        kind: 'bloch',
        props: { theta: 60, phi: 0, editable: true, rotations: true, rotationAngles: [45, 90, 180, 360], landmarks: true },
        tryThis: ['From |+x⟩, press 90° twice.', 'Press 360°: same point, ket times −1.'],
      },
      clues: [],
      insight: 'A gate is a unitary table; X swaps the amplitudes, Z flips the sign of |1⟩, and H makes |±⟩ with H² = I. Gates turn the sphere.',
      insightFormal: '$X = \\sigma_x$, $Z = \\sigma_z$, $H = (X+Z)/\\sqrt2 = iR_n(\\pi)$; every one-qubit gate is $U = e^{i\\alpha}R_z(\\beta)R_y(\\gamma)R_z(\\delta)$.',
      pitfalls: ['Calling H a “square root of NOT”: H² = I, not X.'],
      play: [
        {
          id: 'q4-g-x',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'X on an unequal mix',
          prompt: 'Apply X to 0.6|0⟩ + 0.8|1⟩. What is the chance of reading 0?',
          answer: V.q4ChX,
          tolerance: 0.005,
          hints: [{ text: 'X swaps the amplitudes.' }, { text: 'The |0⟩ amplitude is now 0.8.' }, { text: 'Square it.' }],
          walkthrough: [{ text: `${d(V.q4ChX, 2)}.` }],
        },
        {
          id: 'q4-g-h',
          kind: 'numeric',
          tier: 'core',
          title: 'H’s second column',
          prompt: 'Apply H to |1⟩. What is the |1⟩ amplitude of the result?',
          answer: V.q4ChH1,
          tolerance: 0.005,
          hints: [{ text: 'H|1⟩ is H’s second column.' }, { text: '(1/√2)(1, −1).' }, { text: 'The bottom entry.' }],
          walkthrough: [{ text: `H|1⟩ = |−⟩ = (0.707, ${d(V.q4ChH1, 3)}).` }],
        },
        {
          id: 'q4-g-z',
          kind: 'choice',
          tier: 'core',
          title: 'The chance-preserving gate',
          prompt: 'Which gate leaves the chances of reading 0 and 1 unchanged for every state?',
          options: [
            { text: 'Z', correct: true, why: 'Right: Z only changes phases (multiplies the |1⟩ amplitude by −1), a number of size 1.' },
            { text: 'X', correct: false, why: 'X swaps the two amplitudes, so it swaps the two chances.' },
            { text: 'H', correct: false, why: 'H mixes the two amplitudes, so the chances generally change.' },
            { text: 'R_x(90°)', correct: false, why: 'This turns the sphere about x, moving most states’ chances.' },
          ],
          hints: [{ text: 'Which gate only changes phases?' }, { text: 'Its table is diagonal.' }, { text: 'A phase has size 1.' }],
          walkthrough: [{ text: 'Z multiplies the |1⟩ amplitude by −1, a size-1 number: the chances are unchanged.' }],
        },
        {
          id: 'q4-g-hpsi',
          kind: 'numeric',
          tier: 'stretch',
          title: 'H on the running state',
          prompt: 'Apply H to ψ = 0.866|0⟩ + 0.5|1⟩. What is the chance of reading 0?',
          answer: V.q4HP0,
          tolerance: 0.005,
          hints: [{ text: 'The |0⟩ amplitude is (α + β)/√2.' }, { text: 'It is 0.966.' }, { text: 'Square it.' }],
          walkthrough: [{ text: `0.966² = ${d(V.q4HP0, 3)}, the same as |⟨{+x}|ψ⟩|².` }],
        },
      ],
    },
    {
      id: 'q4-registers',
      story: Q4_STORY['q4-registers'],
      review: Q4_REVIEW['q4-registers'],
      title: 'Registers: 2ⁿ amplitudes for n qubits',
      question: 'How do several qubits make one state, and how many numbers does it take?',
      lecture: {
        pages: 'Bergou §1.1, p. 2, Eqs. 1.3–1.4; N&C §1.2.1, pp. 16–17, Eq. 1.5',
        summary: 'n qubits have 2ⁿ basis states, each with its own amplitude; side by side, two qubits’ amplitudes multiply.',
      },
      books: [
        { source: 'bergou', where: '§1.1, p. 2, Eqs. 1.3–1.4', adds: 'The N-qubit basis and the general state as a sum over 2^N basis strings.' },
        { source: 'nc', where: '§1.2.1, pp. 16–17, Eq. 1.5', adds: 'The same sum, plus the remark that 2⁵⁰⁰ exceeds the atoms in the Universe.' },
      ],
      visual: {
        kind: 'amplitude-bars',
        props: { state: [60, 0], basis: 'z', editable: true },
        tryThis: ['Multiply ψ’s bars by 0.707.', 'Do the four chances add to 1?'],
      },
      clues: [],
      insight: 'n qubits have 2ⁿ basis strings, and side by side two qubits’ amplitudes multiply. A label is a binary number, and not every state is a product.',
      insightFormal: '$|\\Psi\\rangle = \\sum_{x=0}^{2^n-1}c_x|x\\rangle$; $(|a\\rangle\\otimes|b\\rangle)_{ij} = a_ib_j$; a state is a product iff its coefficient matrix has determinant 0.',
      pitfalls: ['Reading bars as places in space: they are basis strings, not locations.'],
      play: [
        {
          id: 'q4-r-count',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Counting amplitudes',
          prompt: 'How many amplitudes does a 5-qubit register have?',
          answer: V.q4ChCount,
          tolerance: 0.5,
          hints: [{ text: 'Each qubit doubles the count.' }, { text: '2ⁿ.' }, { text: '2⁵.' }],
          walkthrough: [{ text: `${V.q4ChCount}.` }],
        },
        {
          id: 'q4-r-prod',
          kind: 'numeric',
          tier: 'core',
          title: 'One amplitude of a product',
          prompt: 'What is the |01⟩ amplitude of (0.6|0⟩ + 0.8|1⟩) ⊗ (0.6|0⟩ + 0.8|1⟩)?',
          answer: V.q4ChProd,
          tolerance: 0.005,
          hints: [{ text: 'First digit from the first qubit.' }, { text: '0.6 for its 0.' }, { text: '0.8 for the second’s 1.' }],
          walkthrough: [{ text: `0.6 × 0.8 = ${d(V.q4ChProd, 2)}.` }],
        },
        {
          id: 'q4-r-index',
          kind: 'numeric',
          tier: 'core',
          title: 'A label as a number',
          prompt: 'Counting from 0, which bar is |110⟩?',
          answer: V.q4ChIndex,
          tolerance: 0.5,
          hints: [{ text: 'Read 110 in binary.' }, { text: '4 + 2 + 0.' }, { text: 'Qubit 0 is the 4s digit.' }],
          walkthrough: [{ text: `${V.q4ChIndex}.` }],
        },
        {
          id: 'q4-r-product',
          kind: 'choice',
          tier: 'stretch',
          title: 'Spotting a product state',
          prompt: 'Which state is a product of two one-qubit states?',
          options: [
            { text: '½(|00⟩ + |01⟩ + |10⟩ + |11⟩)', correct: true, why: 'Right: this is |+⟩ ⊗ |+⟩; its coefficient determinant is 0.' },
            { text: '(|00⟩ + |11⟩)/√2', correct: false, why: 'The Bell pair Φ⁺: its determinant is 0.5, not a product.' },
            { text: '(|01⟩ − |10⟩)/√2', correct: false, why: 'The singlet: also entangled, determinant 0.5.' },
            { text: '(|00⟩ + |01⟩ + |10⟩)/√3', correct: false, why: 'Missing the |11⟩ term breaks the product pattern; its determinant is nonzero.' },
          ],
          hints: [{ text: 'Test (first × last) − (second × third).' }, { text: 'A product gives 0.' }, { text: 'Only one does.' }],
          walkthrough: [{ text: '½(1, 1, 1, 1) = |+⟩ ⊗ |+⟩, the only one with determinant 0.' }],
        },
      ],
    },
    {
      id: 'q4-cnot',
      story: Q4_STORY['q4-cnot'],
      review: Q4_REVIEW['q4-cnot'],
      title: 'CNOT: flip the target when the control is 1',
      question: 'How does a two-qubit gate act, and why can no gate lose information?',
      lecture: {
        pages: 'Bergou §1.2, pp. 3–4, Eq. 1.9, Fig. 1.4, ⚑ P1.1, P1.4(b); N&C §1.3.2, pp. 20–22, Eq. 1.18; §1.3.5, pp. 24–25',
        summary: 'CNOT flips the target when the control is 1, so B becomes B ⊕ A; every gate, CNOT included, is reversible.',
      },
      books: [
        { source: 'bergou', where: '§1.2, pp. 3–4, Eq. 1.9, Fig. 1.4, ⚑ P1.1, P1.4(b)', adds: 'CNOT’s table, why AND has no direct quantum version, and CZ = (I⊗H)CNOT(I⊗H).' },
        { source: 'nc', where: '§1.3.2, pp. 20–22, Eq. 1.18, Figs. 1.6, 1.8; §1.3.5, pp. 24–25', adds: 'CNOT as XOR, the general controlled-U, and the failed-copy argument.' },
      ],
      visual: {
        kind: 'amplitude-bars',
        props: { state: '+x', basis: 'z', editable: true },
        tryThis: ['Set |0⟩: does the target ever flip?', 'Set |1⟩.'],
      },
      clues: [],
      insight: 'CNOT flips the target when the control is 1, B → B ⊕ A. Its table is I with two columns swapped, CNOT² = I, and it copies bits, not qubits.',
      insightFormal: '$U_{CN} = |0\\rangle\\langle0|\\otimes I + |1\\rangle\\langle1|\\otimes X$; CZ is symmetric in its wires; unitary ⇒ reversible, so classical AND has no direct quantum gate.',
      pitfalls: ['Saying “CNOT copies ψ”: it gives a|00⟩ + b|11⟩, not two copies of a|0⟩ + b|1⟩.'],
      play: [
        {
          id: 'q4-c-table',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Reading the table',
          prompt: 'CNOT, with the top wire as control, acts on |11⟩. What comes out?',
          options: [
            { text: '|10⟩', correct: true, why: 'Right: the control is 1, so the target flips from 1 to 0.' },
            { text: '|11⟩', correct: false, why: 'That would mean the target never flips.' },
            { text: '|01⟩', correct: false, why: 'That flips the control, which CNOT never touches.' },
            { text: '|00⟩', correct: false, why: 'That flips both wires; CNOT flips only the target.' },
          ],
          hints: [{ text: 'The control is 1.' }, { text: 'The target flips.' }, { text: '1 → 0.' }],
          walkthrough: [{ text: '|10⟩.' }],
        },
        {
          id: 'q4-c-entry',
          kind: 'numeric',
          tier: 'core',
          title: 'One entry of the table',
          prompt: 'In CNOT’s table (order |00⟩, |01⟩, |10⟩, |11⟩), what is the entry in row 4, column 3?',
          answer: V.q4ChEntry,
          tolerance: 0.5,
          hints: [{ text: 'Column 3 is CNOT|10⟩.' }, { text: 'That is |11⟩.' }, { text: 'Row 4 is |11⟩’s entry.' }],
          walkthrough: [{ text: `${V.q4ChEntry}.` }],
        },
        {
          id: 'q4-c-cz',
          kind: 'numeric',
          tier: 'core',
          title: 'CZ on an even mix',
          prompt: 'CZ acts on ½(|00⟩ + |01⟩ + |10⟩ + |11⟩). What is the |11⟩ amplitude after?',
          answer: V.q4ChCZ,
          tolerance: 0.005,
          hints: [{ text: 'CZ changes one sign.' }, { text: 'The sign of |11⟩.' }, { text: '½ → −½.' }],
          walkthrough: [{ text: `${d(V.q4ChCZ, 1)}; the other three stay 0.5.` }],
        },
        {
          id: 'q4-c-copy',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The failed copy',
          prompt: 'CNOT acts on (0.6|0⟩ + 0.8|1⟩) ⊗ |0⟩. What is the |11⟩ amplitude?',
          answer: V.q4ChCopy,
          tolerance: 0.005,
          hints: [{ text: 'Expand: 0.6|00⟩ + 0.8|10⟩.' }, { text: 'CNOT maps |10⟩ to |11⟩.' }, { text: 'The amplitude rides along.' }],
          walkthrough: [{ text: `0.6|00⟩ + ${d(V.q4ChCopy, 1)}|11⟩: not two copies.` }],
        },
      ],
    },
    {
      id: 'q4-circuits',
      story: Q4_STORY['q4-circuits'],
      review: Q4_REVIEW['q4-circuits'],
      title: 'Circuits: wires are time, products run backwards',
      question: 'How do you read a circuit, and what can a few gates build?',
      lecture: {
        pages: 'Bergou §1.3, pp. 4–5, ⚑ P1.4(a); N&C §1.3.4, pp. 22–24, Eq. 1.20; §1.3.6, pp. 25–26, Eqs. 1.23–1.27',
        summary: 'A circuit’s wires run left to right in time; the matrix multiplies the other way. H then CNOT builds a Bell pair, and three CNOTs make a SWAP.',
      },
      books: [
        { source: 'bergou', where: '§1.3, pp. 4–5, ⚑ P1.4(a)', adds: 'Reading a circuit, and the three-CNOT SWAP worked in full.' },
        { source: 'nc', where: '§1.3.4, pp. 22–24, Eq. 1.20, Figs. 1.7–1.10; §1.3.6, pp. 25–26, Eqs. 1.23–1.27, Fig. 1.12', adds: 'The Bell-pair circuit, universality, and the rules circuits obey (no loops, no FANIN, no FANOUT).' },
      ],
      visual: {
        kind: 'amplitude-bars',
        props: { state: [60, 0], basis: 'x', editable: true },
        tryThis: ['Switch the basis between z and x.', 'Which state has x bars 1 and 0?'],
      },
      clues: [],
      insight: 'Wires are time, read left to right; matrices multiply right to left. H then CNOT makes Φ⁺, and three CNOTs make a SWAP.',
      insightFormal: '$U_{\\text{circuit}} = U_K\\cdots U_1$; N&C Eq. 1.27 gives every Bell state; circuits are acyclic and forbid FANIN and FANOUT.',
      pitfalls: ['Writing the matrices in the order the boxes are drawn: the first box acts first, so it is the rightmost factor.'],
      play: [
        {
          id: 'q4-k-order',
          kind: 'choice',
          tier: 'warm-up',
          title: 'The matrix of a circuit',
          prompt: 'A circuit applies A, then B, then C. Which product is its matrix?',
          options: [
            { text: 'CBA', correct: true, why: 'Right: the first gate acts first on the ket, so it stands closest to it — read right to left.' },
            { text: 'ABC', correct: false, why: 'That is the order the boxes are drawn, not the order the matrices multiply.' },
            { text: 'BAC', correct: false, why: 'This puts B first, but A acts first.' },
            { text: 'ACB', correct: false, why: 'This has C acting before B, the wrong way round.' },
          ],
          hints: [{ text: 'The first gate acts first on the ket.' }, { text: 'It stands next to the ket.' }, { text: 'Read right to left.' }],
          walkthrough: [{ text: 'CBA|ψ⟩.' }],
        },
        {
          id: 'q4-k-bell',
          kind: 'numeric',
          tier: 'core',
          title: 'One amplitude of the Bell circuit',
          prompt: 'H on the top qubit, then CNOT, act on |10⟩. What is the |11⟩ amplitude?',
          answer: V.q4ChBell11,
          tolerance: 0.005,
          hints: [{ text: 'H|1⟩ = |−⟩.' }, { text: '(|00⟩ − |10⟩)/√2.' }, { text: 'CNOT moves |10⟩ to |11⟩.' }],
          walkthrough: [{ text: `(|00⟩ − |11⟩)/√2, N&C’s β₁₀ (${d(V.q4ChBell11, 3)}).` }],
        },
        {
          id: 'q4-k-swap',
          kind: 'order',
          tier: 'core',
          title: 'The three-CNOT swap',
          prompt: 'Put the states of |a, b⟩ through the three-CNOT swap in order.',
          steps: ['|a, b⟩', '|a, a ⊕ b⟩', '|b, a ⊕ b⟩', '|b, a⟩'],
          hints: [{ text: 'The first CNOT’s control is the top.' }, { text: 'The second’s is the bottom.' }, { text: 'a ⊕ a = 0.' }],
          walkthrough: [{ text: 'Bergou ⚑ P1.4(a): each CNOT XORs one wire into the other, cancelling a in the third step.' }],
        },
        {
          id: 'q4-k-hzh',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Sandwiching X between Hadamards',
          prompt: 'What is the top-right entry of HZH?',
          answer: V.q4ChHZH,
          tolerance: 0.5,
          hints: [{ text: 'H = (X + Z)/√2.' }, { text: 'HZH swaps the roles of X and Z.' }, { text: 'X’s top-right entry.' }],
          walkthrough: [{ text: `HZH = X, whose top-right entry is ${V.q4ChHZH}.` }],
        },
      ],
    },
    {
      id: 'q4-measure',
      story: Q4_STORY['q4-measure'],
      review: Q4_REVIEW['q4-measure'],
      title: 'Reading a register, whole or one qubit',
      question: 'What does reading one qubit of two leave in the other?',
      lecture: {
        pages: 'N&C §1.2.1, pp. 16–17, Eq. 1.6; §1.3.3, p. 22, Eq. 1.19; §1.3.4, p. 24, Fig. 1.10; §1.3.5, p. 25',
        summary: 'Reading a register gives a basis string with the Born-rule chance; reading one qubit adds up the matching chances and rescales what is left.',
      },
      books: [{ source: 'nc', where: '§1.2.1, p. 16, Eq. 1.6; §1.3.3, p. 22, Eq. 1.19; §1.3.4, p. 24, Fig. 1.10', adds: 'The marginal chance and post-state of one qubit, the ± basis, and the meter symbol.' }],
      visual: {
        kind: 'amplitude-bars',
        props: { state: [60, 0], basis: 'x', editable: true },
        tryThis: ['Find a state with P(+) = 1.', 'One with P(+) = P(−).'],
      },
      clues: [],
      insight: 'Reading a register gives x with chance |c_x|²; reading one qubit adds the matching chances and rescales what is left. Φ⁺’s readings always agree.',
      insightFormal: 'N&C Eq. 1.6: $P(q_0{=}0) = |\\alpha_{00}|^2 + |\\alpha_{01}|^2$, post-state rescaled; N&C Eq. 1.19 for the $|{\\pm}\\rangle$ basis; the meter and its double classical wire.',
      pitfalls: ['Forgetting to rescale the state left behind after a partial reading.'],
      play: [
        {
          id: 'q4-m-all',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Reading a whole register',
          prompt: 'A two-qubit state has amplitudes (0.5, 0.5, 0.5, 0.5). What is the chance of reading 10?',
          answer: V.q4ChAll,
          tolerance: 0.005,
          hints: [{ text: 'Bar 2.' }, { text: 'Size squared.' }, { text: '0.5².' }],
          walkthrough: [{ text: `${d(V.q4ChAll, 2)}.` }],
        },
        {
          id: 'q4-m-first',
          kind: 'numeric',
          tier: 'core',
          title: 'Reading one qubit',
          prompt: 'For 0.6|00⟩ + 0.8|11⟩, what is the chance that the first qubit reads 1?',
          answer: V.q4ChFirst,
          tolerance: 0.005,
          hints: [{ text: 'Add the chances with first digit 1.' }, { text: 'Only |11⟩.' }, { text: '0.8².' }],
          walkthrough: [{ text: `${d(V.q4ChFirst, 2)}, and the state becomes |11⟩.` }],
        },
        {
          id: 'q4-m-plus',
          kind: 'numeric',
          tier: 'core',
          title: 'Reading in the ± basis',
          prompt: '|0⟩ is read in the |+⟩, |−⟩ basis. What is the chance of +?',
          answer: V.q4ChPlus0,
          tolerance: 0.005,
          hints: [{ text: '|α + β|²/2.' }, { text: 'α = 1, β = 0.' }, { text: '½.' }],
          walkthrough: [{ text: `${d(V.q4ChPlus0, 1)}.` }],
        },
        {
          id: 'q4-m-post',
          kind: 'numeric',
          tier: 'stretch',
          title: 'What is left after a reading',
          prompt: 'Read the first qubit of ½(|00⟩ + |01⟩ + |10⟩ − |11⟩) and get 1. What is the |11⟩ amplitude afterwards?',
          answer: V.q4ChPost3,
          tolerance: 0.005,
          hints: [{ text: 'Keep |10⟩ and |11⟩.' }, { text: '½(|10⟩ − |11⟩).' }, { text: 'Rescale to length 1.' }],
          walkthrough: [{ text: `(|10⟩ − |11⟩)/√2 = |1⟩|−⟩, so ${d(V.q4ChPost3, 3)}.` }],
        },
      ],
    },
  ],
}
