import type { Lecture } from '../schema'
import { Q5_REVIEW } from './Q5.review'
import { Q5_STORY } from './Q5.story'
import { V, claim, close, d, pct, uf } from './Q5.values'

// Physics 709, chapter Q5: "Deutsch's trick and interference" (Bergou §1.4–1.7, pp. 5–10), in both tracks. Every
// number a learner sees is computed in Q5.values.ts, then asserted in keyed claims (content.test.tsx runs `holds`;
// claims.test.ts compares each key with numpy, pipeline/claims_qc709/q5.py). Plan: docs/roles/proposals/P-Q5-story.md;
// rulings docs/roles/decisions/qc709-Q4Q5.md, qc709-map.md, qc709-nc.md. `q5-one-value` comes before `q5-deutsch`
// (N&C's order, ruling Q1). No sheet assigns any Q5 challenge (homework-status.md); Bergou ⚑ P1.3 is worked in full.

export const Q5: Lecture = {
  id: 'Q5',
  number: 5,
  title: "Deutsch's trick and interference",
  outcomes: [
    "Say what Deutsch's problem asks, and why a classical computer must look at f twice.",
    'Build U_f from a truth table, and show that a |−⟩ target kicks (−1)^{f(x)} back onto x.',
    'Explain why a superposed query still yields only one value of f.',
    "Follow Deutsch's circuit state by state, and read f(0) ⊕ f(1) from the top qubit.",
    "Compute an interferometer's two outputs, and match them to Deutsch's circuit.",
    'Describe adiabatic and measurement-based computing, with a gap and a byproduct.',
  ],
  // Q4's qubit, gates, registers, CNOT, circuits, readout; Q3's spectral gap; Q2's photon frames; F1's phase, Euler.
  prerequisites: ['qc-qubit', 'qc-one-qubit-gates', 'qc-registers', 'qc-cnot', 'qc-circuits', 'qc-readout', 'qc-spectral', 'qc-photon-frames', 'qc-phase', 'qc-euler'],
  symbols: {
    f: 'q5-problem:b1',
    'f(0)': 'q5-problem:b1',
    'f(1)': 'q5-problem:b1',
    x: 'q5-problem:b1',
    'U_f': 'q5-oracle:b1',
    y: 'q5-oracle:b1',
    '|-\\rangle': 'q5-oracle:b3',
    '(-1)^{f(x)}': 'q5-oracle:b3',
    'O_f': 'q5-oracle:b4',
    '|+\\rangle': 'q5-one-value:b1',
    '|\\psi_1\\rangle': 'q5-deutsch:b1',
    '|\\psi_2\\rangle': 'q5-deutsch:b2',
    '|\\psi_3\\rangle': 'q5-deutsch:b3',
    '\\varphi_0': 'q5-interferometer:b2',
    '\\varphi_1': 'q5-interferometer:b2',
    '\\mathcal H_0': 'q5-other-models:b1',
    '\\mathcal H_1': 'q5-other-models:b1',
    '\\mathcal H(s)': 'q5-other-models:b1',
    s: 'q5-other-models:b1',
    '\\Delta': 'q5-other-models:b2',
    'W(\\theta)': 'q5-other-models:b3',
    '\\theta': 'q5-other-models:b3',
    '|{+\\theta}\\rangle': 'q5-other-models:b3',
    '|{-\\theta}\\rangle': 'q5-other-models:b3',
  },
  symbolsFormal: {
    '\\bar x': 'q5-problem:b1',
    '|\\psi_0\\rangle': 'q5-deutsch:b1',
    'a^\\dagger': 'q5-interferometer:b1',
    'b^\\dagger': 'q5-interferometer:b1',
    '|\\mathrm{vac}\\rangle': 'q5-interferometer:b1',
    'U_{BS}': 'q5-interferometer:b2',
    'U_\\varphi': 'q5-interferometer:b2',
    't_f': 'q5-other-models:b1',
    'i\\hbar\\,d/dt': 'q5-other-models:b1',
  },
  corrections: [
    {
      where: 'p. 8, Eq. 1.18',
      says: 'The output state follows from the two splitters of Eq. 1.17 with the phase shifters between.',
      shouldSay:
        "Applying Eq. 1.17 at both splitters with the same a, b labels sends equal phases to b (output 2). Eq. 1.18 holds with Fig. 1.7's geometry: the mirrors bring each arm into BS2 through the other port, and a†, b† then name outputs 1 and 2.",
      check: () => close(V.q5Mz118, 1) && close(V.q5MzNaiveOut2, 1),
      source: 'book',
    },
    {
      where: 'p. 10',
      says: 'W(θ)σ_x = σ_zW(−θ).',
      shouldSay: "W(θ)σ_x = e^{iθ}σ_zW(−θ): equal up to a [[global-phase|global phase]], which changes no reading, so the argument stands.",
      check: () => V.q5WIdentPhase === 1 && V.q5WIdentBare === 0,
      source: 'book',
    },
  ],
  units: [
    {
      id: 'q5-problem',
      story: Q5_STORY['q5-problem'],
      review: Q5_REVIEW['q5-problem'],
      title: "Constant or balanced: Deutsch's question",
      question: 'What does Deutsch\'s problem ask, and why does a classical computer look twice?',
      lecture: { pages: 'Bergou §1.4, p. 5', summary: "Only four one-bit functions exist; Deutsch's problem is to tell a constant one from a balanced one." },
      books: [
        { source: 'bergou', where: '§1.4, p. 5; ⚑ P1.3(a)', adds: "Deutsch's problem stated, with the four functions worked in a table." },
        { source: 'nc', where: '§1.4.3, p. 33', adds: 'The same problem, with f(0) ⊕ f(1) as the one bit sought.' },
      ],
      visual: { kind: 'deposit-stats', props: { state: '+z', axis: 'z', seed: 709 }, tryThis: ['Fire 10 atoms: do any differ?'] },
      clues: [],
      insight: 'Four one-bit functions exist. Deutsch asks whether a hidden one is constant or balanced, and one look never settles it.',
      insightFormal: 'f : \\{0,1\\}\\to\\{0,1\\} is constant or balanced; deciding which, given oracle access alone, needs two classical queries but only one quantum query (Unit 5.4).',
      pitfalls: ['Deciding from one value: always 1 and copy share f(1) = 1, one constant and one balanced.'],
      play: [
        {
          id: 'q5-p-count',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Balanced functions',
          prompt: 'How many functions from one bit to one bit are balanced?',
          answer: V.q5ChCount,
          tolerance: 0.5,
          hints: [{ text: 'There are four functions in all.' }, { text: 'Balanced means one 0 and one 1.' }, { text: 'Copy and flip.' }],
          walkthrough: [{ text: '2: copy and flip.' }],
        },
        {
          id: 'q5-p-which',
          kind: 'choice',
          tier: 'core',
          title: 'Which is balanced?',
          prompt: 'Which truth table is balanced?',
          options: [
            { text: 'f(0) = 1, f(1) = 0', correct: true, why: 'Right: the two values differ (Bergou ⚑ P1.3(a)).' },
            { text: 'f(0) = 1, f(1) = 1', correct: false, why: 'Both values agree: constant.' },
            { text: 'f(0) = 0, f(1) = 0', correct: false, why: 'Both values agree: constant.' },
            { text: 'none of these', correct: false, why: 'The first option is balanced.' },
          ],
          hints: [{ text: 'Compare f(0) and f(1).' }, { text: 'Balanced means they differ.' }, { text: 'Only one pair differs.' }],
          walkthrough: [{ text: 'f(0) = 1, f(1) = 0: flip.' }],
        },
        {
          id: 'q5-p-xor',
          kind: 'numeric',
          tier: 'core',
          title: 'One bit of information',
          prompt: 'f(0) = 1 and f(1) = 1. What is f(0) ⊕ f(1)?',
          answer: V.q5XorOne,
          tolerance: 0.5,
          hints: [{ text: '⊕ adds without carrying.' }, { text: '1 + 1 = 2.' }, { text: 'Drop the carry.' }],
          walkthrough: [{ text: '0: constant.' }],
        },
        {
          id: 'q5-p-queries',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Classical queries',
          prompt: 'In the worst case, how many classical evaluations of f decide whether it is constant?',
          answer: V.q5ChQueries,
          tolerance: 0.5,
          hints: [{ text: 'What does f(0) alone rule out?' }, { text: 'Nothing: a constant and a balanced f both fit.' }, { text: 'Ask f(1) too.' }],
          walkthrough: [{ text: "2; Deutsch's circuit needs only 1 (Unit 5.4)." }],
        },
      ],
    },
    {
      id: 'q5-oracle',
      story: Q5_STORY['q5-oracle'],
      review: Q5_REVIEW['q5-oracle'],
      title: 'The f-CNOT and the phase kickback',
      question: 'How does a quantum computer ask about f, and where does the answer land?',
      lecture: { pages: 'Bergou pp. 5–6', summary: 'f becomes the reversible gate U_f; with the target in |−⟩, its answer comes back as a sign on the control.', equations: ['U_f|x\\rangle|y\\rangle = |x\\rangle|y \\oplus f(x)\\rangle'] },
      books: [
        { source: 'bergou', where: 'pp. 5–6, Eq. 1.13, ⚑ P1.3(b)–(c)', adds: 'U_f built explicitly for each f, and the phase-kickback identity proved.' },
        { source: 'nc', where: '§1.4.1, pp. 29–30, Fig. 1.14; §1.4.2, p. 31', adds: 'The Toffoli construction of a reversible oracle, and the same kickback.' },
      ],
      visual: { kind: 'bloch', props: { theta: 90, phi: 0, editable: false, measure: 'x', rotations: true, rotationAngles: [180] }, tryThis: ['Press 180° once, then twice: when does the x reading flip back?'] },
      clues: [],
      insight: 'U_f adds f(x) to y by XOR and is unitary. With the target in |−⟩, the answer comes back as a sign on x, never touching the target.',
      insightFormal: 'U_f|x\\rangle|y\\rangle = |x\\rangle|y \\oplus f(x)\\rangle is a permutation, hence unitary; on |-\\rangle it acts as O_f = \\mathrm{diag}((-1)^{f(0)}, (-1)^{f(1)}) on x alone.',
      pitfalls: ['Thinking the target changes under the kickback: |−⟩ stays |−⟩ every time.'],
      play: [
        {
          id: 'q5-o-cnot',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which f gives CNOT?',
          prompt: 'For which f is U_f the CNOT?',
          options: [
            { text: 'copy, f(x) = x', correct: true, why: 'Right: CNOT adds x to y, and U_f adds f(x).' },
            { text: 'always 0', correct: false, why: 'This U_f is the identity.' },
            { text: 'always 1', correct: false, why: 'This U_f is X on the target alone.' },
            { text: 'flip', correct: false, why: 'This U_f is CNOT followed by X on the target.' },
          ],
          hints: [{ text: 'CNOT adds x to y.' }, { text: 'U_f adds f(x) to y.' }, { text: 'So f(x) must equal x.' }],
          walkthrough: [{ text: 'copy.' }],
        },
        {
          id: 'q5-o-out',
          kind: 'choice',
          tier: 'core',
          title: 'Always 1 on |0⟩|1⟩',
          prompt: 'U_f for always 1 acts on |0⟩|1⟩. What comes out?',
          options: [
            { text: '|0⟩|0⟩', correct: true, why: 'Right: y ⊕ f(0) = 1 ⊕ 1 = 0, and x is untouched.' },
            { text: '|0⟩|1⟩', correct: false, why: 'f(0) = 1 for always 1, so y must flip.' },
            { text: '|1⟩|1⟩', correct: false, why: 'x is never changed by U_f.' },
            { text: '|1⟩|0⟩', correct: false, why: 'x is never changed by U_f.' },
          ],
          hints: [{ text: 'y ⊕ f(x).' }, { text: 'f(0) = 1 for always 1.' }, { text: 'x is untouched.' }],
          walkthrough: [{ text: '|0⟩|0⟩.' }],
        },
        {
          id: 'q5-o-kick',
          kind: 'numeric',
          tier: 'core',
          title: 'One amplitude of the kickback',
          prompt: 'U_f for flip acts on |0⟩|−⟩. What is the |00⟩ amplitude afterwards?',
          answer: V.q5ChKick0,
          tolerance: 0.005,
          hints: [{ text: 'f(0) = 1 for flip.' }, { text: 'The sign (−1)¹ lands in front of the whole state.' }, { text: '|0⟩|−⟩ has |00⟩ amplitude 1/√2.' }],
          walkthrough: [{ text: `−|0⟩|−⟩: the |00⟩ amplitude is ${d(V.q5ChKick0, 3)}.` }],
        },
        {
          id: 'q5-o-phase',
          kind: 'choice',
          tier: 'stretch',
          title: 'The phase oracle of copy',
          prompt: 'With the target in |−⟩, which one-qubit gate does U_f act as on x, for f(x) = x?',
          options: [
            { text: 'Z', correct: true, why: '|0⟩ keeps its sign and |1⟩ gains (−1)¹: diag(1, −1) = Z.' },
            { text: 'X', correct: false, why: 'X swaps |0⟩ and |1⟩; the kickback only ever changes a sign.' },
            { text: 'H', correct: false, why: 'H mixes the two basis states; the kickback does not.' },
            { text: 'I', correct: false, why: 'That would mean no phase at all, but f(1) = 1 is not 0.' },
          ],
          hints: [{ text: '|0⟩ keeps its sign.' }, { text: '|1⟩ gains (−1)¹.' }, { text: 'diag(1, −1).' }],
          walkthrough: [{ text: 'O_{id} = Z.' }],
        },
      ],
    },
    {
      id: 'q5-one-value',
      story: Q5_STORY['q5-one-value'],
      review: Q5_REVIEW['q5-one-value'],
      title: 'Both values in, only one out',
      question: 'If one query computes f(0) and f(1) together, what can a reading return?',
      lecture: { pages: 'Bergou Eq. 1.16, p. 6', summary: 'One query on a superposed input holds both values of f at once, but a single reading still returns only one.' },
      books: [
        { source: 'bergou', where: 'Eq. 1.16, p. 6', adds: 'The parallel query, following directly from Deutsch\'s own derivation.' },
        { source: 'nc', where: '§1.4.2, pp. 30–32, Eqs. 1.37–1.40, Figs. 1.17–1.18', adds: "Quantum parallelism on n qubits, and the Walsh–Hadamard transform's role." },
      ],
      visual: { kind: 'deposit-stats', props: { state: '+x', axis: 'z', seed: 709 }, tryThis: ['Fire 10, then 100: how close to one half?'] },
      clues: [],
      insight: 'A superposed query holds f(0) and f(1) at once, but one reading still returns only one pair (x, f(x)).',
      insightFormal: 'U_f\\,\\tfrac1{\\sqrt2}(|0\\rangle+|1\\rangle)|0\\rangle = \\tfrac1{\\sqrt2}(|0,f(0)\\rangle+|1,f(1)\\rangle); a computational reading collapses to one term.',
      pitfalls: ['Thinking parallelism reads out every value of f at once: one reading still gives one.'],
      play: [
        {
          id: 'q5-v-prob',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Reading 11',
          prompt: 'After Eq. 1.16 with f(x) = x, what is the chance of reading 11?',
          answer: V.q5ParPHalf,
          tolerance: 0.005,
          unit: 'probability',
          hints: [{ text: 'The state is (|00⟩ + |11⟩)/√2.' }, { text: 'The amplitude is 1/√2.' }, { text: 'Square it.' }],
          walkthrough: [{ text: `${d(V.q5ParPHalf, 1)}.` }],
        },
        {
          id: 'q5-v-wh',
          kind: 'numeric',
          tier: 'core',
          title: 'Three Hadamards',
          prompt: 'H on each of three qubits in |000⟩: what is each amplitude?',
          answer: V.q5ChWh,
          tolerance: 0.005,
          hints: [{ text: '2³ = 8 equal amplitudes.' }, { text: 'Their squares add to 1.' }, { text: '1/√8.' }],
          walkthrough: [{ text: `${d(V.q5ChWh, 3)}.` }],
        },
        {
          id: 'q5-v-values',
          kind: 'numeric',
          tier: 'core',
          title: 'One reading, one value',
          prompt: 'How many values of f does one reading of (|0, f(0)⟩ + |1, f(1)⟩)/√2 reveal?',
          answer: V.q5ChValues,
          tolerance: 0.5,
          hints: [{ text: 'What is left in the state after the reading?' }, { text: 'One term.' }, { text: 'It holds one f(x).' }],
          walkthrough: [{ text: '1 (D5).' }],
        },
        {
          id: 'q5-v-state',
          kind: 'choice',
          tier: 'stretch',
          title: 'Always 1, in superposition',
          prompt: 'For always 1, what does U_f make of (|0⟩ + |1⟩)|0⟩/√2?',
          options: [
            { text: '(|01⟩ + |11⟩)/√2', correct: true, why: 'Right: f(0) = f(1) = 1, so both terms end in 1.' },
            { text: '(|00⟩ + |11⟩)/√2', correct: false, why: 'That is Bell-like entanglement, not what always 1 gives.' },
            { text: '(|01⟩ + |10⟩)/√2', correct: false, why: 'x is never changed by U_f.' },
            { text: '(|00⟩ + |10⟩)/√2', correct: false, why: 'f(0) = f(1) = 1, so y must flip both times.' },
          ],
          hints: [{ text: 'f(0) = f(1) = 1 for always 1.' }, { text: 'Each y becomes 0 ⊕ 1.' }, { text: 'Both terms end in y = 1.' }],
          walkthrough: [{ text: '(|01⟩ + |11⟩)/√2.' }],
        },
      ],
    },
    {
      id: 'q5-deutsch',
      story: Q5_STORY['q5-deutsch'],
      review: Q5_REVIEW['q5-deutsch'],
      title: "Deutsch's circuit: one query, a global answer",
      question: 'How does one use of U_f decide constant or balanced?',
      lecture: { pages: 'Bergou §1.4, pp. 5–6', summary: 'H, U_f, H on the top qubit, then a reading: constant f leaves 0, balanced f leaves 1, from one query.', equations: ['|\\psi_3\\rangle = \\pm|f(0) \\oplus f(1)\\rangle|-\\rangle'] },
      books: [
        { source: 'bergou', where: '§1.4, pp. 5–6, Eqs. 1.10–1.15, Fig. 1.5', adds: "Deutsch's circuit derived state by state." },
        { source: 'nc', where: '§1.4.3, pp. 32–34, Eqs. 1.41–1.45, Fig. 1.19', adds: "The same circuit from |0⟩|1⟩, combining parallelism with interference." },
      ],
      visual: { kind: 'phase-dial', props: { theta: 90, rotations: true }, tryThis: ['Set 0° and 180°: which one is balanced?'] },
      clues: [],
      insight: "Start from |0⟩|−⟩; H, U_f, H on the top qubit. Constant f ends in |0⟩ and balanced f in |1⟩, from one query.",
      insightFormal: '|\\psi_3\\rangle = \\pm|f(0) \\oplus f(1)\\rangle|-\\rangle: one query of U_f, framed by two Hadamards, learns f(0) \\oplus f(1) and nothing more.',
      pitfalls: ['Reading the ± sign as information about f(0): it is an overall factor, invisible to any reading.'],
      play: [
        {
          id: 'q5-d-read',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Flip, read out',
          prompt: 'In Deutsch\'s circuit with flip, what is the chance that the top qubit reads 1?',
          answer: V.q5DTop1Not,
          tolerance: 0.005,
          unit: 'probability',
          hints: [{ text: 'Is flip constant or balanced?' }, { text: 'Balanced f ends in |1⟩.' }, { text: 'Up to an overall sign.' }],
          walkthrough: [{ text: '1.' }],
        },
        {
          id: 'q5-d-psi2',
          kind: 'numeric',
          tier: 'core',
          title: 'One amplitude of ψ₂',
          prompt: 'For always 1, what is the |00⟩ amplitude of |ψ₂⟩ = ½[(−1)^{f(0)}|0⟩ + (−1)^{f(1)}|1⟩](|0⟩ − |1⟩)?',
          answer: V.q5D2OneRe,
          tolerance: 0.005,
          hints: [{ text: 'f(0) = 1 for always 1.' }, { text: '(−1)¹ = −1.' }, { text: 'Times one half.' }],
          walkthrough: [{ text: `${d(V.q5D2OneRe, 1)}.` }],
        },
        {
          id: 'q5-d-steps',
          kind: 'order',
          tier: 'core',
          title: "Deutsch's circuit, in order",
          prompt: "Put Deutsch's circuit in order.",
          steps: ['Prepare |0⟩ on top and |−⟩ below.', 'H on the top qubit.', 'Apply U_f once.', 'H on the top qubit.', 'Read the top qubit.'],
          hints: [{ text: 'Prepare first.' }, { text: 'H surrounds U_f.' }, { text: 'Read last.' }],
          walkthrough: [{ text: 'Fig. 1.5.' }],
        },
        {
          id: 'q5-d-sign',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A final amplitude',
          prompt: 'For always 1, what is the |01⟩ amplitude of the final state?',
          answer: V.q5D3R2,
          tolerance: 0.005,
          hints: [{ text: 'Constant f: the top ends in |0⟩.' }, { text: 'With a sign of −1 in front.' }, { text: '−|0⟩|−⟩.' }],
          walkthrough: [{ text: `−|0⟩|−⟩ = (−${d(V.q5D3R2, 3)}, ${d(V.q5D3R2, 3)}, 0, 0).` }],
        },
      ],
    },
    {
      id: 'q5-interferometer',
      story: Q5_STORY['q5-interferometer'],
      review: Q5_REVIEW['q5-interferometer'],
      title: 'Two paths, one photon: Deutsch in glass',
      question: 'Why does one photon through two splitters tell equal phases from unequal ones?',
      lecture: { pages: 'Bergou §1.5, pp. 7–8', summary: 'A photon split into two arms, recombined after phase shifts, tells constant from balanced exactly as Deutsch\'s circuit does.', equations: ['P(\\text{output 1}) = \\cos^2\\tfrac{\\varphi_1 - \\varphi_0}2'] },
      books: [{ source: 'bergou', where: '§1.5, Eqs. 1.17–1.18, Figs. 1.6–1.7, pp. 7–8', adds: 'The Mach–Zehnder interferometer as an optical Deutsch circuit.' }],
      visual: {
        kind: 'bloch',
        props: { theta: 90, phi: 0, editable: false, measure: 'x', rotations: true, rotationAngles: [45, 90, 135, 180] },
        tryThis: ['Press 45°, 90°, 135°: read 0.854, 0.5, 0.146.', '180°: output 2 every time.'],
      },
      clues: [],
      insight: 'A beam splitter puts one photon in two arms. Phases of 0 or 180° stand for f, and interference sorts constant from balanced.',
      insightFormal: 'P(\\text{output 1}) = \\cos^2\\tfrac{\\varphi_1-\\varphi_0}2; with \\varphi_x = \\pi f(x) this reproduces Deutsch\'s circuit exactly (Bergou p. 8).',
      pitfalls: ["Applying the splitter rule twice with the same arm labels: with Fig. 1.7's mirrors, equal phases go to output 1, not 2."],
      play: [
        {
          id: 'q5-i-bs',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'At the first splitter',
          prompt: 'A photon enters the splitter along arm a. What is its chance of taking arm b?',
          answer: V.q5MzHalfP,
          tolerance: 0.005,
          unit: 'probability',
          hints: [{ text: 'The amplitude is 1/√2.' }, { text: 'Square it.' }, { text: 'One half.' }],
          walkthrough: [{ text: `${d(V.q5MzHalfP, 1)}.` }],
        },
        {
          id: 'q5-i-p90',
          kind: 'numeric',
          tier: 'core',
          title: 'A right-angle phase',
          prompt: 'φ₀ = 0 and φ₁ = 90°. What is the chance of output 1?',
          answer: V.q5MzSweep90,
          tolerance: 0.005,
          unit: 'probability',
          hints: [{ text: '½(1 + e^{iφ₁}).' }, { text: '|1 + i|² = 2.' }, { text: 'Divide by 4.' }],
          walkthrough: [{ text: `${d(V.q5MzSweep90, 1)}.` }],
        },
        {
          id: 'q5-i-p45',
          kind: 'numeric',
          tier: 'core',
          title: 'A 45° phase',
          prompt: 'φ₀ = 0 and φ₁ = 45°. What is the chance of output 1?',
          answer: V.q5MzSweep45,
          tolerance: 0.005,
          unit: 'probability',
          hints: [{ text: 'cos²((φ₁ − φ₀)/2).' }, { text: 'Half of 45° is 22.5°.' }, { text: 'Square its cosine.' }],
          walkthrough: [{ text: `${uf(V.q5MzSweep45)}.` }],
        },
        {
          id: 'q5-i-which',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Reading the arm',
          prompt: 'A detector between the splitters reads the arm, and φ₀ = φ₁. What is the chance of output 2?',
          answer: V.q5WhichPathOut2,
          tolerance: 0.005,
          unit: 'probability',
          hints: [{ text: 'The reading leaves the photon in one arm.' }, { text: 'One arm into a splitter.' }, { text: 'Half and half.' }],
          walkthrough: [{ text: `${d(V.q5WhichPathOut2, 1)}, whatever the phases.` }],
        },
      ],
    },
    {
      id: 'q5-other-models',
      story: Q5_STORY['q5-other-models'],
      review: Q5_REVIEW['q5-other-models'],
      title: 'Two other ways to compute',
      question: 'Can a computation run on slowly changed energies, or on measurements alone?',
      lecture: { pages: 'Bergou §1.6–1.7, pp. 9–10', summary: 'Adiabatic computing changes an energy operator slowly; measurement-based computing applies gates by CZ and readings.', equations: ['\\mathcal H(s) = (1-s)\\mathcal H_0 + s\\mathcal H_1'] },
      books: [{ source: 'bergou', where: '§1.6–1.7, Eqs. 1.19–1.21, pp. 9–10', adds: "Both models sketched, and Chapter 1's three closing lessons." }],
      visual: { kind: 'bloch', props: { theta: 45, phi: 0, editable: true, landmarks: true, measure: 'z' }, tryThis: ['θ = 90°, 45°, 0°: s = 0, one half, 1.'] },
      clues: [],
      insight: 'Adiabatic computing changes an energy operator slowly and stays in its lowest state; measurement-based computing applies gates with CZ and a reading.',
      insightFormal: '\\mathcal H(s) = (1-s)\\mathcal H_0 + s\\mathcal H_1; W(\\theta) = HP(\\theta), applied by \\mathrm{CZ} and a reading in |\\pm\\theta\\rangle, with a known byproduct.',
      pitfalls: ['Thinking a random measurement result spoils the computation: it only leaves a known byproduct gate.'],
      play: [
        {
          id: 'q5-m-gap0',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The gap at the start',
          prompt: 'For ℋ(s) = −(1 − s)X − sZ, what is the gap at s = 0?',
          answer: V.q5Gap0,
          tolerance: 0.005,
          hints: [{ text: 'ℋ(0) = −X.' }, { text: 'Its eigenvalues are ±1.' }, { text: 'Their difference.' }],
          walkthrough: [{ text: `${d(V.q5Gap0, 0)}.` }],
        },
        {
          id: 'q5-m-gapmin',
          kind: 'numeric',
          tier: 'core',
          title: 'The smallest gap',
          prompt: 'What is the smallest gap over all s?',
          answer: V.q5Gap50,
          tolerance: 0.005,
          hints: [{ text: 'Δ(s) = 2√((1 − s)² + s²).' }, { text: 'Smallest at s = ½.' }, { text: '2√(½).' }],
          walkthrough: [{ text: `√2 = ${d(V.q5Gap50, 3)}.` }],
        },
        {
          id: 'q5-m-w',
          kind: 'numeric',
          tier: 'core',
          title: 'Applying W(θ)',
          prompt: 'For ψ = 0.866|0⟩ + 0.5|1⟩ and θ = 45°, what is the chance that W(θ)ψ reads 0?',
          answer: V.q5WPsiPZero,
          tolerance: 0.005,
          unit: 'probability',
          hints: [{ text: 'W(θ) = H·P(θ).' }, { text: "The |0⟩ amplitude is (α + e^{iθ}β)/√2." }, { text: 'Square its size.' }],
          walkthrough: [{ text: `${d(V.q5WPsiPZero, 3)}.` }],
        },
        {
          id: 'q5-m-byproduct',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The other branch',
          prompt: 'Same ψ and θ, but the first reading gave −θ. What is the chance that the second qubit reads 1?',
          answer: V.q5XWPsiPOne,
          tolerance: 0.005,
          unit: 'probability',
          hints: [{ text: 'The second qubit holds XW(θ)ψ.' }, { text: 'X swaps the two chances.' }, { text: 'So read 1 where W(θ)ψ read 0.' }],
          walkthrough: [{ text: `${d(V.q5XWPsiPOne, 3)}.` }],
        },
      ],
    },
  ],
}

export { claim, close, pct }
