import type { Lecture } from '../schema'
import { Q6_REVIEW } from './Q6.review'
import { Q6_STORY } from './Q6.story'
import { V, claim, close, d } from './Q6.values'

// Physics 709, chapter Q6: "Two qubits: products, entanglement and the Bell basis" (notes L5 pp. 21-26, L6 pp.
// 27-29), in both tracks. Every number a learner sees is computed in Q6.values.ts, then asserted in keyed claims
// (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy, pipeline/claims_qc709/q6.py). Plan:
// docs/roles/proposals/P-Q6-story.md; rulings docs/roles/decisions/qc709-remap.md, qc709-Q6Q7.md. Q6 closes Part II
// and owns operator ⊗, the product/entangled split, the Bell basis, the Bell measurement and the two-parity picture
// (Q4 owns ⊗ on kets and `qc-tensor-operator`'s minimal notation beat; Q6 links back). HW2 is submitted
// (homework-status.md), so its P1 and P2(a)-(c) items get full walkthroughs below.

export const Q6: Lecture = {
  id: 'Q6',
  number: 6,
  title: 'Two qubits: products, entanglement and the Bell basis',
  outcomes: [
    'Say why two qubits carry four amplitudes and N qubits carry 2^N, against N bits for N coins.',
    'Build A⊗B as a block matrix, and use A⊗I for an operator that acts on one qubit.',
    "Show that a product state's averages multiply, and read a pair's two arrows and its grid.",
    'Count parameters (6 against 4), and test a two-qubit state for a product with its coefficient grid.',
    'Write the four Bell states, check that they are orthonormal, and name the triplet and the singlet.',
    'Run the Bell-measurement circuit forwards to read a Bell state, and backwards to make one.',
    'Explain why the circuit measures the two commuting parities XX and ZZ, and what a stabilizer is.',
  ],
  prerequisites: [
    'qc-registers',
    'qc-cnot',
    'qc-circuits',
    'qc-readout',
    'qc-one-qubit-gates',
    'qc-born-projector',
    'qc-spin-operators',
    'qc-observables',
    'qc-uncertainty',
    'qc-x-states',
  ],
  symbols: {
    Z: 'q6-tensor:b2',
    "|\\beta_x'y'\\rangle": 'q6-bell-basis:b3',
    "\\delta_xx'": 'q6-bell-basis:b3',
    "\\delta_yy'": 'q6-bell-basis:b3',
    "|u'\\otimesv'\\rangle": 'q6-tensor:b4',
    "|u'\\rangle": 'q6-tensor:b4',
    "|v'\\rangle": 'q6-tensor:b4',
    '|0_x\\rangle': 'q6-bell-basis:b8',
    "\\Pi_x'y'": 'q6-bell-circuit:b4',
    d_1: 'q6-many:b1',
    d_2: 'q6-many:b1',
    '|\\cdot\\rangle': 'q6-many:b1',
    '|0\\rangle': 'q6-many:b1',
    '|1\\rangle': 'q6-many:b1',
    '|00\\rangle': 'q6-many:b1',
    '|01\\rangle': 'q6-many:b1',
    '|10\\rangle': 'q6-many:b1',
    '|11\\rangle': 'q6-many:b1',
    N: 'q6-many:b2',
    '|+\\rangle': 'q6-many:b3',
    A_1: 'q6-tensor:b1',
    '\\sigma_x': 'q6-tensor:b1',
    '\\sigma_z': 'q6-tensor:b2',
    '\\psi_1': 'q6-tensor:b4',
    Z_1: 'q6-tensor:b4',
    X_2: 'q6-tensor:b4',
    r_A: 'q6-tensor:b4',
    r_B: 'q6-tensor:b4',
    a: 'q6-many:b3',
    b: 'q6-many:b3',
    c: 'q6-many:b3',
    d: 'q6-entangled:b3',
    C: 'q6-many:b1',
    x: 'q6-bell-basis:b2',
    y: 'q6-bell-basis:b2',
    '|1,1\\rangle': 'q6-bell-basis:b5',
    '|1,-1\\rangle': 'q6-bell-basis:b5',
    '|1,0\\rangle': 'q6-bell-basis:b5',
    '|0,0\\rangle': 'q6-bell-basis:b5',
    S_x: 'q6-bell-basis:b7',
    m_x: 'q6-bell-basis:b8',
    U: 'q6-bell-circuit:b1',
    '\\Psi_1': 'q6-bell-circuit:b5',
    '\\Psi_2': 'q6-bell-circuit:b6',
    n_i: 'q6-parities:b5',
    P_1: 'q6-tensor:b3',
    I_4: 'q6-bell-circuit:b4',
    '\\hat O': 'q6-parities:b1',
    '\\hat M': 'q6-parities:b5',
    '\\dim': 'q6-many:b1',
    V: 'q6-many:b1',
    '\\otimes': 'q6-many:b1',
    '|\\Psi\\rangle': 'q6-many',
    '|i_1\\rangle': 'q6-many',
    '|i_2\\rangle': 'q6-many',
    c_i_1i_2: 'q6-many',
    A: 'q6-tensor:b1',
    I: 'q6-tensor:b1',
    X: 'q6-tensor:b1',
    B: 'q6-tensor:b2',
    A_11: 'q6-tensor:b2',
    A_12: 'q6-tensor:b2',
    A_21: 'q6-tensor:b2',
    A_22: 'q6-tensor:b2',
    '\\langle\\cdot\\rangle': 'q6-tensor:b4',
    '\\langle\\cdot|': 'q6-tensor:b2',
    '|\\psi_1\\rangle': 'q6-many:b3',
    '|\\psi_2\\rangle': 'q6-many:b3',
    Z_2: 'q6-tensor:b6',
    T_zz: 'q6-tensor:b6',
    '|\\psi_1\\psi_2\\rangle': 'q6-tensor',
    A_ij: 'q6-tensor',
    X_1: 'q6-tensor',
    X_12: 'q6-tensor',
    '\\Phi': 'q6-entangled:b3',
    c_00: 'q6-entangled:b4',
    c_01: 'q6-entangled:b4',
    c_10: 'q6-entangled:b4',
    c_11: 'q6-entangled:b4',
    '|++\\rangle': 'q6-entangled',
    '\\Psi': 'q6-bell-basis:b1',
    '\\beta_00': 'q6-bell-basis:b1',
    '\\Psi_+': 'q6-bell-basis:b1',
    '\\beta_xy': 'q6-bell-basis:b2',
    '\\beta_01': 'q6-bell-basis:b2',
    '\\beta_10': 'q6-bell-basis:b2',
    '\\beta_11': 'q6-bell-basis:b2',
    '\\langle\\cdot|\\cdot\\rangle': 'q6-tensor:b4',
    '|\\beta_xy\\rangle': 'q6-bell-basis:b2',
    '|\\Phi^+\\rangle': 'q6-bell-basis:b3',
    '|\\Psi^+\\rangle': 'q6-bell-basis:b3',
    '|\\Phi^-\\rangle': 'q6-bell-basis:b3',
    '|+x\\rangle': 'q6-bell-basis:b6',
    '|+1_x\\rangle': 'q6-bell-basis:b6',
    '|-x\\rangle': 'q6-bell-basis:b6',
    S: 'q6-entangled:b1',
    '\\hbar': 'q6-bell-basis:b7',
    '\\Psi_\\pm': 'q6-bell-basis',
    '|0,y\\rangle': 'q6-bell-basis',
    '|1,1\\oplusy\\rangle': 'q6-bell-basis',
    '|+x,+x\\rangle': 'q6-bell-basis',
    '|y\\rangle': 'q6-bell-circuit:b2',
    '|-\\rangle': 'q6-bell-circuit:b2',
    '|xy\\rangle': 'q6-bell-circuit:b2',
    H: 'q6-bell-basis:b1',
    '|1,y\\rangle': 'q6-bell-circuit:b2',
    '|x\\rangle': 'q6-bell-circuit:b2',
    '\\dagger': 'q6-bell-basis:b3',
    '\\Pi_xy': 'q6-bell-circuit:b4',
    '\\Pi_10': 'q6-bell-circuit:b4',
    p_00: 'q6-bell-circuit:b6',
    p_10: 'q6-bell-circuit:b6',
    '|\\beta_00\\rangle': 'q6-bell-circuit:b6',
    '|\\Psi_2\\rangle': 'q6-bell-circuit:b6',
    '|\\beta_10\\rangle': 'q6-bell-circuit:b6',
    '|\\beta_11\\rangle': 'q6-bell-circuit',
    n_1: 'q6-parities:b5',
    n_2: 'q6-parities:b5',
    '\\hat n_1': 'q6-parities:b5',
    '\\hat n_2': 'q6-parities:b5',
    '\\hat n_i': 'q6-parities:b5',
    i: 'q6-tensor:b2',
    Z_i: 'q6-parities:b5',
    '\\sigma_x1': 'q6-parities',
    '\\sigma_x2': 'q6-parities',
    '\\mathbb': 'q6-many:b1',
    '|i_1,\\ldots,i_N\\rangle': 'q6-many:b2',
    '|i_N\\rangle': 'q6-many:b2',
    a_i_1: 'q6-many:b3',
    b_i_2: 'q6-many:b3',
    '\\mathsf': 'q6-many:b3',
    T: 'q6-many:b3',
    '|\\psi_1,\\psi_2\\rangle': 'q6-tensor:b1',
    I_2: 'q6-tensor:b1',
    '\\hat\\sigma_1x': 'q6-tensor:b1',
    '\\hat\\sigma_x1': 'q6-tensor:b1',
    X_ij: 'q6-tensor:b1',
    n: 'q6-tensor:b2',
    m: 'q6-tensor:b2',
    k: 'q6-tensor:b2',
    j: 'q6-tensor:b2',
    l: 'q6-tensor:b2',
    B_kl: 'q6-tensor:b2',
    P_2: 'q6-tensor:b3',
    P_n: 'q6-tensor:b3',
    P_k: 'q6-tensor:b3',
    Y: 'q6-tensor:b3',
    '\\hat\\sigma_x2': 'q6-tensor:b3',
    '|ab\\rangle': 'q6-tensor:b3',
    '\\oplus': 'q6-tensor:b3',
    u: 'q6-tensor:b4',
    v: 'q6-tensor:b4',
    '|u\\otimesv\\rangle': 'q6-tensor:b4',
    '|u\\rangle': 'q6-tensor:b4',
    '|v\\rangle': 'q6-tensor:b4',
    '|A\\psi_1\\rangle': 'q6-tensor:b4',
    '|B\\psi_2\\rangle': 'q6-tensor:b4',
    '|\\psi_1\\otimes\\psi_2\\rangle': 'q6-tensor:b4',
    'r_A,i': 'q6-tensor:b5',
    '\\sigma_i': 'q6-tensor:b5',
    'r_B,j': 'q6-tensor:b5',
    '\\sigma_j': 'q6-tensor:b5',
    T_ij: 'q6-tensor:b5',
    T_xx: 'q6-tensor:b5',
    T_zx: 'q6-tensor:b5',
    '\\dim_\\mathbbR': 'q6-entangled:b1',
    'C_\\Phi^+': 'q6-entangled:b3',
    P: 'q6-bell-basis:b4',
    '|+z\\rangle': 'q6-bell-basis:b5',
    '|-x,-x\\rangle': 'q6-bell-basis:b6',
    '|-1_x\\rangle': 'q6-bell-basis:b6',
    p_xy: 'q6-bell-circuit:b4',
    '|\\Psi_1\\rangle': 'q6-bell-circuit:b5',
    p_01: 'q6-bell-circuit:b6',
    p_11: 'q6-bell-circuit:b6',
    '|\\psi\\rangle': 'q6-parities:b4',
    g: 'q6-parities:b4',
    n_general: 'q6-entangled:b1',
    n_product: 'q6-entangled:b1',
  },
  units: [
    {
      id: 'q6-many',
      story: Q6_STORY['q6-many'],
      review: Q6_REVIEW['q6-many'],
      title: 'Composing two at once',
      question: 'Why does joining a second system double the amplitudes instead of adding two?',
      lecture: { pages: 'notes L5 pp. 21–22', summary: 'A pair of qubits has one basis state for every pairing, $d_1d_2$ states in all, not $d_1 + d_2$.' },
      books: [
        { source: 'bergou', where: 'eqs. 1.3–1.4, p. 2', adds: 'the joint space written out for two qubits.' },
        { source: 'nc', where: '§2.1.7, p. 71', adds: 'the tensor product of two [[vector-space|vector spaces]], worked from the definition.' },
      ],
      visual: { kind: 'amplitude-bars', props: { state: '++', basis: 'computational' }, tryThis: ['Add a third qubit and watch the bar count double again.'] },
      clues: [],
      insight: 'Composition multiplies: two qubits carry $2\\times2 = 4$ amplitudes, N qubits carry $2^N$.',
      insightFormal: 'The joint space $V^{(1)}\\otimes V^{(2)}$ has dimension $d_1d_2$; N qubits need $2^N$ complex amplitudes, against N classical bits.',
      pitfalls: ['Adding dimensions ($d_1 + d_2$) instead of multiplying them.'],
      play: [
        {
          id: 'q6-m-count',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Three qubits',
          prompt: 'How many amplitudes does a general state of 3 qubits carry?',
          answer: V.q6AmpN3,
          tolerance: 0.5,
          hints: [{ text: 'Each qubit doubles the count.' }, { text: '2 × 2 × 2.' }, { text: 'One per bit string.' }],
          walkthrough: [{ text: 'The strings 000 … 111, eight of them.' }],
        },
        {
          id: 'q6-m-dim',
          kind: 'numeric',
          tier: 'core',
          title: 'A qubit and a spin-1 particle',
          prompt: 'A qubit and a spin-1 particle (3 basis states) form a pair. What is the dimension of their joint space?',
          answer: V.q6DimSpin1,
          tolerance: 0.5,
          hints: [{ text: 'Dimensions multiply.' }, { text: '2 × 3.' }, { text: 'One basis state per pairing.' }],
          walkthrough: [{ text: '$d_1d_2 = 6$.' }],
        },
        {
          id: 'q6-m-amp',
          kind: 'numeric',
          tier: 'core',
          title: 'A product amplitude',
          prompt: 'Qubit 1 is $|0\\rangle$ and qubit 2 is $|+\\rangle$. What is the $|01\\rangle$ amplitude of the pair?',
          answer: V.q6R2,
          tolerance: 0.005,
          hints: [{ text: 'A product’s amplitude is a product of amplitudes.' }, { text: 'Qubit 1’s $|0\\rangle$ part times qubit 2’s $|1\\rangle$ part.' }, { text: '$1\\times1/\\sqrt2$.' }],
          walkthrough: [{ text: `${d(V.q6R2, 3)}.` }],
        },
        {
          id: 'q6-m-mem',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Thirty qubits',
          prompt: 'At 16 bytes per amplitude, how many GiB ($2^{30}$ bytes) hold the state of 30 qubits?',
          answer: V.q6Gib30,
          tolerance: 0.5,
          hints: [{ text: '$2^{30}$ amplitudes.' }, { text: 'Times 16 bytes.' }, { text: 'Divide by $2^{30}$.' }],
          walkthrough: [{ text: '16 GiB; each extra qubit doubles it.' }],
        },
      ],
    },
    {
      id: 'q6-tensor',
      story: Q6_STORY['q6-tensor'],
      review: Q6_REVIEW['q6-tensor'],
      title: 'Operators on pairs: the tensor product',
      question: "How does an operator on one qubit act on a pair, and what do a product state's averages do?",
      lecture: { pages: 'notes L5 pp. 22–23, eq. 2.1', summary: 'An operator on one qubit becomes $A\\otimes I$ on the pair; $A\\otimes B$ is a block matrix built entry by entry.' },
      books: [
        { source: 'nc', where: '§2.1.7, pp. 72–74', adds: 'the block rule for the tensor product of operators, worked in general.' },
        { source: 'axler', where: '9D, p. 370', adds: 'a Formal aside on bilinear maps and the universal property of the tensor product.' },
      ],
      visual: { kind: 'operator-builder', props: { preset: 'XZ' }, tryThis: ['Build $X\\otimes Z$ block by block.'] },
      clues: [],
      insight: 'An operator on qubit 1 alone is $A\\otimes I$; a product state’s averages multiply.',
      insightFormal: '$A\\otimes B = [A_{ij}B]$ as an $nm\\times nm$ block matrix; for product states $\\langle A\\otimes B\\rangle = \\langle A\\rangle\\langle B\\rangle$ and $T = r_Ar_B^{\\mathsf T}$.',
      pitfalls: ['Reading the Pauli string $XZ$ as the one-qubit product $X\\cdot Z$.'],
      play: [
        {
          id: 'q6-t-xi',
          kind: 'choice',
          tier: 'warm-up',
          title: 'X on qubit 1',
          prompt: 'Which matrix is X acting on qubit 1 of a pair?',
          options: [
            { text: '$X\\otimes I$', correct: true, why: 'Right: qubit 1 carries X, qubit 2 is left alone.' },
            { text: '$I\\otimes X$', correct: false, why: 'That would act on qubit 2.' },
            { text: '$X\\cdot I$', correct: false, why: 'That is one-qubit notation; the pair needs a tensor product.' },
            { text: '$X\\otimes X$', correct: false, why: 'That acts on both qubits.' },
          ],
          hints: [{ text: 'Qubit 1 is the first slot.' }, { text: 'Qubit 2 must be left alone.' }, { text: '“Leave alone” is I.' }],
          walkthrough: [{ text: '$X_1 = X\\otimes I$.' }],
        },
        {
          id: 'q6-t-entry',
          kind: 'numeric',
          tier: 'core',
          title: 'A block entry',
          prompt: 'What is the entry of $\\sigma_x\\otimes\\sigma_z$ in row 2, column 4 (numbering 1–4)?',
          answer: V.q6XZEntry,
          tolerance: 0.5,
          hints: [{ text: 'Row 2, column 4 lies in the top-right block.' }, { text: 'That block is $X_{12}Z = Z$.' }, { text: 'Z’s lower-right entry.' }],
          walkthrough: [{ text: '−1.' }],
        },
        {
          id: 'q6-t-avg',
          kind: 'numeric',
          tier: 'core',
          title: 'An average of a product',
          prompt: 'For $\\psi_1\\otimes|+\\rangle$ with $\\psi_1 = 0.866|0\\rangle + 0.5|1\\rangle$, what is $\\langle X\\otimes X\\rangle$?',
          answer: V.q6Sqrt32,
          tolerance: 0.005,
          hints: [{ text: 'A product’s averages multiply.' }, { text: '$\\langle X\\rangle$ of $\\psi_1$ is $2(0.866)(0.5)$.' }, { text: '$\\langle X\\rangle$ of $|+\\rangle$ is 1.' }],
          walkthrough: [{ text: `0.866 × 1 = ${d(V.q6Sqrt32, 3)}.` }],
        },
        {
          id: 'q6-t-zz',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A zero average',
          prompt: 'Same state: what is $\\langle Z\\otimes Z\\rangle$?',
          answer: 0,
          tolerance: 0.005,
          hints: [{ text: 'Multiply again.' }, { text: '$\\langle Z\\rangle$ of $|+\\rangle$?' }, { text: 'Zero.' }],
          walkthrough: [{ text: '0.5 × 0 = 0.' }],
        },
      ],
    },
    {
      id: 'q6-entangled',
      story: Q6_STORY['q6-entangled'],
      review: Q6_REVIEW['q6-entangled'],
      title: 'States that will not factor',
      question: 'Most two-qubit states are not products: how many are, and how do we test one?',
      lecture: { pages: 'notes L5 p. 22', summary: 'A general pair needs 6 real parameters; a product needs only 4, and the gap widens fast with more qubits.' },
      books: [],
      visual: { kind: 'operator-action', props: { preset: 'cz' }, tryThis: ['Compare $|{+}{+}\\rangle$ before and after CZ.'] },
      clues: [],
      insight: 'A pair’s state needs 6 real numbers; a product needs only 4, and $\\Phi^+$ cannot be one.',
      insightFormal: 'General: $2\\cdot2^N - 2$ parameters; product: $2N$. The fraction collapses exponentially; $\\det C = 0$ tests for a product exactly.',
      pitfalls: ['Thinking every amplitude nonzero means entangled: $|{+}{+}\\rangle$ has four and is a product.'],
      play: [
        {
          id: 'q6-e-params',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Three qubits’ parameters',
          prompt: 'How many real parameters specify a general pure state of 3 qubits?',
          answer: V.q6Param3General,
          tolerance: 0.5,
          hints: [{ text: '8 complex amplitudes.' }, { text: '16 real numbers.' }, { text: 'Remove the norm and the phase.' }],
          walkthrough: [{ text: '$2\\cdot2^3 - 2 = 14$.' }],
        },
        {
          id: 'q6-e-frac',
          kind: 'numeric',
          tier: 'core',
          title: 'A product’s share',
          prompt: 'For N = 3, what fraction of a general state’s parameters does a product state use?',
          answer: V.q6Param3Frac,
          tolerance: 0.001,
          hints: [{ text: 'A product needs 2 per qubit.' }, { text: '6 of 14.' }, { text: 'Divide.' }],
          walkthrough: [{ text: `6/14 = ${d(V.q6Param3Frac, 4)}.` }],
        },
        {
          id: 'q6-e-det',
          kind: 'numeric',
          tier: 'core',
          title: 'A product test',
          prompt: 'Compute $c_{00}c_{11} - c_{01}c_{10}$ for $(|00\\rangle + |01\\rangle + |10\\rangle - |11\\rangle)/2$.',
          answer: V.q6DetCZpp,
          tolerance: 0.005,
          hints: [{ text: 'All four have size ½.' }, { text: '$c_{11} = -\\tfrac12$.' }, { text: '$(\\tfrac12)(-\\tfrac12) - (\\tfrac12)(\\tfrac12)$.' }],
          walkthrough: [{ text: '−0.5: entangled.' }],
        },
        {
          id: 'q6-e-which',
          kind: 'choice',
          tier: 'stretch',
          title: 'Which is a product?',
          prompt: 'Which of these is a product state?',
          options: [
            { text: '$(|00\\rangle + |01\\rangle + |10\\rangle + |11\\rangle)/2$', correct: true, why: 'Right: its test gives $\\tfrac14 - \\tfrac14 = 0$; it is $|{+}{+}\\rangle$.' },
            { text: '$(|00\\rangle + |11\\rangle)/\\sqrt2$', correct: false, why: 'That is $\\Phi^+$: test $\\pm\\tfrac12$.' },
            { text: '$(|01\\rangle - |10\\rangle)/\\sqrt2$', correct: false, why: 'That is the singlet: test $\\pm\\tfrac12$.' },
            { text: '$(|00\\rangle + |01\\rangle + |10\\rangle - |11\\rangle)/2$', correct: false, why: 'Its test gives −0.5: entangled.' },
          ],
          hints: [{ text: 'Use the test.' }, { text: 'Only one gives 0.' }, { text: '$\\tfrac14 - \\tfrac14$.' }],
          walkthrough: [{ text: '$|{+}\\rangle|{+}\\rangle$.' }],
        },
      ],
    },
    {
      id: 'q6-bell-basis',
      story: Q6_STORY['q6-bell-basis'],
      review: Q6_REVIEW['q6-bell-basis'],
      title: 'The Bell basis: four entangled states',
      question: 'Can a whole basis be entangled, and what do its four states share?',
      lecture: { pages: 'notes L5 pp. 25–26, eqs. 2.3–2.4', summary: 'Four entangled states, $\\Phi^\\pm$ and $\\Psi^\\pm$, form an orthonormal basis; each is named by two bits, $\\beta_{xy}$.' },
      books: [
        { source: 'bergou', where: '§3.1, eq. 3.4, pp. 31–32', adds: 'the same four states, with Φ and Ψ swapped against the standard names.' },
        { source: 'nc', where: '§1.3.6, p. 25', adds: 'the $\\beta_{xy}$ table and its two-bit naming rule.' },
      ],
      visual: { kind: 'amplitude-bars', props: { state: 'bell', name: 'Phi+' }, tryThis: ['Switch between the four Bell states and watch the bars move.'] },
      clues: [],
      insight: 'The Bell basis $\\Phi^\\pm, \\Psi^\\pm$ is orthonormal and entangled throughout; $\\beta_{xy}$ names each member by two bits.',
      insightFormal: '$|\\beta_{xy}\\rangle = (|0,y\\rangle + (-1)^x|1,1\\oplus y\\rangle)/\\sqrt2$, orthonormal, each maximally entangled; HW2 P1 ties two of them to the spin-1 triplet and the singlet.',
      pitfalls: ['Mixing name systems: the notes’ $\\beta_{10}$ is $\\Phi^-$, and Bergou’s $\\Psi_\\pm$ are our $\\Phi^\\pm$.'],
      play: [
        {
          id: 'q6-b-name',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which Bell state?',
          prompt: 'Which Bell state is $\\beta_{11}$?',
          options: [
            { text: '$(|01\\rangle - |10\\rangle)/\\sqrt2$', correct: true, why: 'Right: y = 1 (differ), x = 1 (subtract): the singlet.' },
            { text: '$(|00\\rangle + |11\\rangle)/\\sqrt2$', correct: false, why: 'That is $\\beta_{00}$.' },
            { text: '$(|01\\rangle + |10\\rangle)/\\sqrt2$', correct: false, why: 'That is $\\beta_{01}$.' },
            { text: '$(|00\\rangle - |11\\rangle)/\\sqrt2$', correct: false, why: 'That is $\\beta_{10}$.' },
          ],
          hints: [{ text: 'y = 1: the bits differ.' }, { text: 'x = 1: the terms subtract.' }, { text: '$\\Psi^-$.' }],
          walkthrough: [{ text: 'The singlet.' }],
        },
        {
          id: 'q6-b-overlap',
          kind: 'numeric',
          tier: 'core',
          title: 'An overlap',
          prompt: 'What is $\\langle\\Phi^+|\\Phi^-\\rangle$?',
          answer: 0,
          tolerance: 0.005,
          hints: [{ text: 'Same strings.' }, { text: 'Opposite relative signs.' }, { text: '$\\tfrac12 - \\tfrac12$.' }],
          walkthrough: [{ text: '0.' }],
        },
        {
          id: 'q6-b-p1a',
          kind: 'numeric',
          tier: 'core',
          title: 'HW2 P1(a): the triplet component',
          assigned: 'HW2 P1(a)',
          prompt: 'Write $|{+x}\\rangle\\otimes|{+x}\\rangle$ in the triplet basis. What is its $|1, 0\\rangle$ component?',
          answer: V.q6P1aMid,
          tolerance: 0.005,
          hints: [{ text: '$|{+x},{+x}\\rangle = \\tfrac12(|00\\rangle + |01\\rangle + |10\\rangle + |11\\rangle)$.' }, { text: '$|1,0\\rangle = (|01\\rangle + |10\\rangle)/\\sqrt2$.' }, { text: 'Overlap: $\\tfrac1{\\sqrt2}(\\tfrac12 + \\tfrac12)$.' }],
          walkthrough: [],
        },
        {
          id: 'q6-b-p1c',
          kind: 'numeric',
          tier: 'core',
          title: 'HW2 P1(c): the singlet component',
          assigned: 'HW2 P1(c)',
          prompt: 'What is the singlet component of $|{+x}\\rangle\\otimes|{-x}\\rangle$?',
          answer: V.q6P1cS,
          tolerance: 0.005,
          hints: [
            { text: '$|{+x}\\rangle\\otimes|{-x}\\rangle = \\tfrac12(|00\\rangle - |01\\rangle + |10\\rangle - |11\\rangle)$.' },
            { text: '$\\langle0,0| = (\\langle01| - \\langle10|)/\\sqrt2$.' },
            { text: '$\\tfrac1{\\sqrt2}(-\\tfrac12 - \\tfrac12)$.' },
          ],
          walkthrough: [],
        },
        {
          id: 'q6-b-stot',
          kind: 'numeric',
          tier: 'stretch',
          title: 'HW2 P1(e): an $S_x^{\\mathrm{tot}}$ entry',
          assigned: 'HW2 P1(e)',
          prompt: 'In the basis $|1,1\\rangle, |1,0\\rangle, |1,-1\\rangle, |0,0\\rangle$, what is the $(|1,1\\rangle, |1,0\\rangle)$ entry of $S^{\\mathrm{tot}}_x$, in units of ħ?',
          answer: V.q6StotEntry,
          tolerance: 0.005,
          hints: [{ text: '$S^{\\mathrm{tot}}_x = \\tfrac12(X\\otimes I + I\\otimes X)$ in units of ħ.' }, { text: 'Apply it to $|1,0\\rangle$.' }, { text: 'Read the $|00\\rangle$ part.' }],
          walkthrough: [],
        },
      ],
    },
    {
      id: 'q6-bell-circuit',
      story: Q6_STORY['q6-bell-circuit'],
      review: Q6_REVIEW['q6-bell-circuit'],
      title: 'Reading and writing Bell states',
      question: 'How do two ordinary detectors read a Bell state, and how is one made?',
      lecture: { pages: 'notes L5 p. 26, Fig. 7; L6 p. 27, eq. 2.5', summary: 'A CNOT then an H on qubit 1 rotates the Bell basis onto the 0,1 basis; run backwards, the same circuit makes Bell states.' },
      books: [
        { source: 'nc', where: 'Fig. 1.12, p. 25', adds: 'the same circuit drawn, cited for its own Bell-state preparation.' },
        { source: 'bergou', where: '§3.4, p. 37', adds: 'the Bell basis read out for dense coding (Chapter Q11).' },
      ],
      visual: { kind: 'basis-translator', props: { from: 'bell', to: 'computational' }, tryThis: ['Run the circuit on each of the four Bell states.'] },
      clues: [],
      insight: 'CNOT then H on qubit 1 sends $\\beta_{xy}\\to|xy\\rangle$ with certainty; run backwards it makes Bell states.',
      insightFormal: '$U = (H\\otimes I)\\mathrm{CNOT}$, $U|\\beta_{xy}\\rangle = |xy\\rangle$, $U^\\dagger|xy\\rangle = |\\beta_{xy}\\rangle$; outcome chances are $\\langle\\Psi|\\Pi_{xy}|\\Psi\\rangle$.',
      pitfalls: ['Reversing the gate order: the measuring circuit is CNOT first, then H.'],
      play: [
        {
          id: 'q6-c-out',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Reading $\\Phi^-$',
          prompt: 'The measuring circuit receives $\\Phi^-$. What does it record?',
          options: [
            { text: '10', correct: true, why: '$\\Phi^- = \\beta_{10}$, so x = 1, y = 0.' },
            { text: '01', correct: false, why: 'That reads $\\beta_{01} = \\Psi^+$.' },
            { text: '00', correct: false, why: 'That reads $\\beta_{00} = \\Phi^+$.' },
            { text: '11', correct: false, why: 'That reads $\\beta_{11} = \\Psi^-$.' },
          ],
          hints: [{ text: '$\\Phi^- = \\beta_{10}$.' }, { text: 'The circuit sends $\\beta_{xy}$ to $|xy\\rangle$.' }, { text: 'x = 1, y = 0.' }],
          walkthrough: [{ text: '10.' }],
        },
        {
          id: 'q6-c-mid',
          kind: 'numeric',
          tier: 'core',
          title: 'Midway through',
          prompt: 'After the CNOT, $\\beta_{11}$ becomes $(|0\\rangle - |1\\rangle)|1\\rangle/\\sqrt2$. What is its $|11\\rangle$ amplitude?',
          answer: V.q6NegR2,
          tolerance: 0.005,
          hints: [{ text: 'Expand.' }, { text: 'The $|1\\rangle|1\\rangle$ term carries the minus.' }, { text: '$-1/\\sqrt2$.' }],
          walkthrough: [{ text: `${d(V.q6NegR2, 3)}.` }],
        },
        {
          id: 'q6-c-p2a',
          kind: 'numeric',
          tier: 'core',
          title: 'HW2 P2(a): a product input',
          assigned: '709 HW2, Problem 2(a)',
          prompt: 'Expand $|0\\rangle\\otimes|{+x}\\rangle$ in the Bell basis. What is the probability of outcome 11?',
          answer: V.q6Quarter,
          tolerance: 0.005,
          hints: [{ text: '$|0\\rangle|+\\rangle = (|00\\rangle + |01\\rangle)/\\sqrt2$.' }, { text: '$\\langle\\beta_{11}| = (\\langle01| - \\langle10|)/\\sqrt2$.' }, { text: 'Square the overlap.' }],
          walkthrough: [],
        },
        {
          id: 'q6-c-p2c',
          kind: 'numeric',
          tier: 'stretch',
          title: 'HW2 P2(c): an entangled input',
          assigned: '709 HW2, Problem 2(c)',
          prompt: 'For $(\\sqrt3|00\\rangle + |11\\rangle)/2$, what is the probability of outcome 00?',
          answer: V.q6P2c00,
          tolerance: 0.005,
          hints: [{ text: 'Only $\\beta_{00}$ and $\\beta_{10}$ share its strings.' }, { text: '$\\langle\\beta_{00}|\\Psi_2\\rangle = (\\sqrt3 + 1)/(2\\sqrt2)$.' }, { text: 'Square it.' }],
          walkthrough: [],
        },
      ],
    },
    {
      id: 'q6-parities',
      story: Q6_STORY['q6-parities'],
      review: Q6_REVIEW['q6-parities'],
      title: 'Two parities: what the detectors really ask',
      question: 'Which two-qubit quantities does a Bell measurement measure, and why do they fit together?',
      lecture: { pages: 'notes L6 pp. 27–29, eqs. 2.6–2.8', summary: 'The measuring circuit turns the parities $X_1X_2$ and $Z_1Z_2$ into two local readings; the Bell states are their common eigenvectors.' },
      books: [{ source: 'nc', where: '§10.5.1, p. 454', adds: 'XX and ZZ named as the stabilizer generators of the EPR pair.' }],
      visual: { kind: 'operator-action', props: { preset: 'heisenberg' }, tryThis: ['Move a Z observable back through the measuring circuit.'] },
      clues: [],
      insight: 'A Bell measurement reads the commuting parities $X_1X_2$, $Z_1Z_2$; both stabilize $\\Phi^+$.',
      insightFormal: '$U^\\dagger(Z\\otimes I)U = X\\otimes X$, $U^\\dagger(I\\otimes Z)U = Z\\otimes Z$; $U\\hat MU^\\dagger = 2\\hat n_1 + \\hat n_2$ moves the nonlocality into U.',
      pitfalls: ['Conjugating the wrong way: the observable moves as $U\\hat MU^\\dagger$, never $U^\\dagger\\hat MU$.'],
      play: [
        {
          id: 'q6-p-heis',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Moving $Z_2$ back',
          prompt: 'Reading Z on qubit 2 after the measuring circuit’s gates measures which operator on the incoming pair?',
          options: [
            { text: '$Z\\otimes Z$', correct: true, why: 'The H misses qubit 2; the CNOT spreads a target Z to the control.' },
            { text: '$X\\otimes X$', correct: false, why: 'That is what reading $Z_1$ gives.' },
            { text: '$I\\otimes Z$', correct: false, why: 'The CNOT does move this operator.' },
            { text: '$Z\\otimes I$', correct: false, why: 'That acts on the wrong qubit.' },
          ],
          hints: [{ text: 'Move $Z_2$ back through the gates.' }, { text: 'The H misses qubit 2.' }, { text: 'The CNOT spreads a target Z to the control.' }],
          walkthrough: [{ text: '$Z_1Z_2$.' }],
        },
        {
          id: 'q6-p-eig',
          kind: 'numeric',
          tier: 'core',
          title: 'An eigenvalue',
          prompt: 'What is the eigenvalue of $X\\otimes X$ on $\\Psi^-$?',
          answer: V.q6EigXXPsiMinus,
          tolerance: 0.5,
          hints: [{ text: '$\\Psi^- = \\beta_{11}$.' }, { text: '$XX\\beta_{xy} = (-1)^x\\beta_{xy}$.' }, { text: 'x = 1.' }],
          walkthrough: [{ text: '−1.' }],
        },
        {
          id: 'q6-p-p2b',
          kind: 'numeric',
          tier: 'core',
          title: 'HW2 P2(b): a product’s parities',
          assigned: '709 HW2, Problem 2(b)',
          prompt: 'For $|0\\rangle\\otimes|{+x}\\rangle$, what is $\\langle\\sigma_{x1}\\sigma_{x2}\\rangle$?',
          answer: V.q6P2bExpXX,
          tolerance: 0.005,
          hints: [{ text: 'A product’s averages multiply.' }, { text: '$\\langle X\\rangle$ of $|0\\rangle$ is 0.' }, { text: '$0\\times1$.' }],
          walkthrough: [],
        },
        {
          id: 'q6-p-m',
          kind: 'numeric',
          tier: 'stretch',
          title: 'An $\\hat M$ value',
          prompt: '$\\hat M = (I - XX) + \\tfrac12(I - ZZ)$. What is its value on $\\beta_{10}$?',
          answer: V.q6MEigBeta10,
          tolerance: 0.5,
          hints: [{ text: 'On $\\beta_{10}$, XX = −1 and ZZ = +1.' }, { text: '$(1 + 1) + \\tfrac12(1 - 1)$.' }, { text: '$2x + y$.' }],
          walkthrough: [{ text: '2.' }],
        },
      ],
    },
  ],
}

export { claim, close, d }
