import type { Lecture } from '../schema'
import { Q7_REVIEW } from './Q7.review'
import { Q7_STORY } from './Q7.story'
import { V, d } from './Q7.values'

// Physics 709, chapter Q7: "GHZ and Mermin: certainty without instructions" (notes L6 pp. 29–32, L7 pp. 33–34;
// Bergou §3.9, pp. 57–58), in both tracks. Every number a learner sees is computed in Q7.values.ts, then asserted
// in keyed claims (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy,
// pipeline/claims_qc709/q7.py). Plan: docs/roles/proposals/P-Q7-story.md; rulings docs/roles/decisions/
// qc709-remap.md, qc709-Q6Q7.md. Q7 opens Part III ("Correlations and the density matrix"). HW2 is submitted
// (homework-status.md), so P5(b)–(c) and P7(a)–(d) carry full walkthroughs (ruling 12); Bergou ⚑ P10.1(a) is a
// cited aside with no challenge (ruling 13).

export const Q7: Lecture = {
  id: 'Q7',
  number: 7,
  title: 'GHZ and Mermin: certainty without instructions',
  outcomes: [
    'Write the GHZ state and say what its 0/1 readings do; compare its count of zeros with three independent coins.',
    'Compute every single-qubit bracket in the x and y bases with one factor ζ.',
    'Predict the chance of any x/y run of GHZ from s, a power of −i times the product Π of the readings.',
    'Say which bit strings survive XXX, YYX and the odd-y runs, and why the product is a reading.',
    'Show that XXX, YYX, YXY and XYY commute and have GHZ as an eigenstate with zero spread.',
    'State Mermin’s argument: no predetermined answers can match all four results, and quantum operators escape by order.',
  ],
  prerequisites: [
    'qc-bell-basis-station',
    'qc-operator-tensor-station',
    'qc-parities-station',
    'qc-one-qubit-gates',
    'qc-observables',
    'qc-uncertainty',
    'qc-x-states',
    'qc-complex-multiply',
    'qc-euler',
  ],
  // Heuristic symbol lint (content/symbols.test.ts): every TeX "symbol" `requiredSymbols` reads out of a span must
  // be defined at or before its first use, in EITHER track (defs are shared; `defsFor` merges `symbolsFormal` over
  // these only for the Formal track). Kets, averages and subscripted letters each count as their own symbol string.
  symbols: {
    '|\\cdot\\rangle': 'q7-ghz:b1',
    '|000\\rangle': 'q7-ghz:b1',
    '|111\\rangle': 'q7-ghz:b1',
    N: 'q7-ghz:b1',
    '|0\\cdots0\\rangle': 'q7-ghz:b1',
    '|1\\cdots1\\rangle': 'q7-ghz:b1',
    '|_N\\rangle': 'q7-ghz:b1',
    n: 'q7-ghz:b3',
    P: 'q7-ghz:b2',
    '|+x\\rangle': 'q7-ghz:b3',
    '\\otimes': 'q7-ghz:b3',
    '\\langle\\cdot\\rangle': 'q7-ghz:b3',
    'P_': 'q7-ghz:b3',
    p: 'q7-ghz:b3',
    '|-x\\rangle': 'q7-brackets:b1',
    '|+y\\rangle': 'q7-brackets:b1',
    '|-y\\rangle': 'q7-brackets:b1',
    '|0\\rangle': 'q7-brackets:b1',
    '|1\\rangle': 'q7-brackets:b1',
    i: 'q7-brackets:b1',
    k: 'q7-brackets:b2',
    b_k: 'q7-brackets:b2',
    '|\\varepsilon_kb_k\\rangle': 'q7-brackets:b2',
    '|\\varepsilon_2b_2\\rangle': 'q7-brackets:b2',
    b_1: 'q7-brackets:b2',
    b_2: 'q7-brackets:b2',
    b_3: 'q7-brackets:b2',
    '|\\varepsilonx\\rangle': 'q7-brackets:b2',
    '|\\varepsilony\\rangle': 'q7-brackets:b2',
    '\\varepsilon_k': 'q7-brackets:b2',
    '\\langle\\cdot|\\cdot\\rangle': 'q7-brackets:b3',
    '\\zeta_k': 'q7-brackets:b3',
    '\\varepsilon': 'q7-brackets:b3',
    '\\zeta': 'q7-brackets:b4',
    s: 'q7-parity-table:b1',
    '\\zeta_1': 'q7-parity-table:b1',
    '\\zeta_2': 'q7-parity-table:b1',
    '\\zeta_3': 'q7-parity-table:b1',
    '|\\varepsilon_1b_1,\\varepsilon_2b_2,\\varepsilon_3b_3\\rangle': 'q7-parity-table:b1',
    '|\\ldots\\rangle': 'q7-parity-table:b1',
    n_y: 'q7-parity-table:b1',
    '\\Pi': 'q7-parity-table:b1',
    '\\varepsilon_1': 'q7-parity-table:b2',
    '\\varepsilon_2': 'q7-parity-table:b2',
    '\\varepsilon_3': 'q7-parity-table:b2',
    '|+x,+x,+x\\rangle': 'q7-parity-table:b5',
    '|+x,+x,-x\\rangle': 'q7-parity-table:b5',
    P_XXX: 'q7-bit-strings:b1',
    P_YYX: 'q7-bit-strings:b1',
    'P_n_y\\': 'q7-bit-strings:b1',
    '\\iff': 'q7-bit-strings:b1',
    X_1: 'q7-bit-strings:b4',
    X_2: 'q7-bit-strings:b4',
    X_3: 'q7-bit-strings:b4',
    '\\sigma_xk': 'q7-bit-strings:b4',
    '\\sigma_x1': 'q7-bit-strings:b4',
    '\\sigma_x2': 'q7-bit-strings:b4',
    '\\sigma_x3': 'q7-bit-strings:b4',
    Y_1: 'q7-observables:b1',
    Y_2: 'q7-observables:b1',
    Y_3: 'q7-observables:b1',
    '\\hat O': 'q7-observables:b1',
    '\\hat O_XXX': 'q7-observables:b1',
    '\\hat O_YYX': 'q7-observables:b1',
    '\\hat O_YXY': 'q7-observables:b1',
    '\\hat O_XYY': 'q7-observables:b1',
    '\\sigma_y1': 'q7-observables:b1',
    '\\sigma_y2': 'q7-observables:b1',
    I: 'q7-observables:b1',
    '\\sigma_x': 'q7-observables:b2',
    '\\sigma_y': 'q7-observables:b2',
    X: 'q7-observables:b3',
    Y: 'q7-observables:b3',
    '\\Delta': 'q7-observables:b3',
    x_k: 'q7-mermin:b1',
    y_k: 'q7-mermin:b1',
    x_i: 'q7-mermin:b1',
    y_i: 'q7-mermin:b1',
    x_1: 'q7-mermin:b2',
    x_2: 'q7-mermin:b2',
    x_3: 'q7-mermin:b2',
    y_1: 'q7-mermin:b2',
    y_2: 'q7-mermin:b2',
    y_3: 'q7-mermin:b2',
    g: 'q7-mermin:b5',
    '\\Phi': 'q7-mermin:b5',
    Z_1: 'q7-mermin:b5',
    Z_2: 'q7-mermin:b5',
    Z_3: 'q7-mermin:b5',
  },
  units: [
    {
      id: 'q7-ghz',
      story: Q7_STORY['q7-ghz'],
      review: Q7_REVIEW['q7-ghz'],
      title: 'GHZ: all or nothing',
      question: 'What does GHZ look like in the 0/1 basis, and how does it differ from three coins?',
      lecture: { pages: 'notes L6 p. 29', summary: 'Three qubits can share one state, (|000⟩ + |111⟩)/√2: all agree, with no classical analogue for the spread.' },
      books: [{ source: 'bergou', where: '§3.9, pp. 57–58, Eqs. 3.81–3.82', adds: 'Introduces GHZ beside the W state as the two kinds of genuine three-party entanglement.' }],
      visual: { kind: 'deposit-stats', props: { state: '+x', axis: 'z', seed: 709 }, tryThis: ['Fire 20: one qubit of GHZ alone, about half each way.'] },
      clues: [],
      insight: 'GHZ reads 000 or 111, each half the time, and nothing else: one reading fixes the other two.',
      insightFormal: `GHZ’s perfect 0/1 correlation is only part of its story: the zero-count’s variance, ${d(V.q7ZerosVar, 2)}, is three times a product state’s ${d(V.q7ZerosPlusVar, 2)}, with the same mean.`,
      pitfalls: ['Reading "all three agree" as "three copies of one coin": the variance shows the readings move together.'],
      play: [
        {
          id: 'q7-g-p000',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Reading GHZ',
          prompt: 'Read GHZ in the 0/1 basis. What is the chance of 000?',
          answer: V.q7GhzP000,
          tolerance: 0.005,
          unit: 'probability',
          hints: [{ text: 'Two terms.' }, { text: 'Amplitude 1/√2.' }, { text: 'Square it.' }],
          walkthrough: [{ text: '½.' }],
        },
        {
          id: 'q7-g-mean',
          kind: 'numeric',
          tier: 'core',
          title: 'The mean zero-count',
          prompt: 'What is the mean number of qubits that read 0 in GHZ?',
          answer: V.q7ZerosMean,
          tolerance: 0.005,
          hints: [{ text: 'Which counts occur?' }, { text: '0 or 3, each ½.' }, { text: 'Average them.' }],
          walkthrough: [{ text: 'GHZ reads 000 (three zeros) or 111 (none), each with ½, so ⟨n⟩ = ½·3 = 3/2.' }],
        },
        {
          id: 'q7-g-var',
          kind: 'numeric',
          tier: 'core',
          title: 'The variance of the zero-count',
          prompt: 'What is the variance of that number?',
          answer: V.q7ZerosVar,
          tolerance: 0.005,
          hints: [{ text: '⟨n²⟩ − ⟨n⟩².' }, { text: '⟨n²⟩ = ½·9.' }, { text: 'Subtract 9/4.' }],
          walkthrough: [{ text: '9/2 − 9/4 = 9/4.' }],
        },
        {
          id: 'q7-g-var-plus',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Three independent coins',
          prompt: 'For three independent qubits in |+x⟩, what is the variance of the number of zeros?',
          answer: V.q7ZerosPlusVar,
          tolerance: 0.005,
          hints: [{ text: 'Three independent fair coins.' }, { text: 'Each adds ¼.' }, { text: 'Three of them.' }],
          walkthrough: [{ text: 'P(n) = 1/8, 3/8, 3/8, 1/8, mean 3/2 and variance 3·¼ = 3/4. GHZ has the same mean and three times the variance: its zeros come all together.' }],
        },
      ],
    },
    {
      id: 'q7-brackets',
      story: Q7_STORY['q7-brackets'],
      review: Q7_REVIEW['q7-brackets'],
      title: 'Reading GHZ in the x and y bases',
      question: 'What does one qubit’s bracket look like in the x or y basis?',
      lecture: { pages: 'notes L6 pp. 29–30, Eq. 2.9', summary: 'Reading each qubit in x or y gives ±1 with one of eight brackets, each 1/√2 times a factor ζ of size 1.' },
      books: [],
      visual: { kind: 'amplitude-bars', props: { state: [90, 90], basis: 'y', editable: true }, tryThis: ['Measure y: always +. Switch the basis to z: 50/50.'] },
      clues: [],
      insight: 'Every bracket with |0⟩ is 1/√2; a bracket with |1⟩ is that times ζ, a number of size 1.',
      insightFormal: 'ζ_k is real (±1) in the x basis and imaginary (∓i) in the y basis, so a run’s whole bracket pattern is fixed by the chosen bases and readings alone.',
      pitfalls: ['Forgetting that a bra conjugates: ⟨+y|1⟩ = −i/√2, not +i/√2.'],
      play: [
        {
          id: 'q7-b-zero',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A bracket with |0⟩',
          prompt: 'What is ⟨−y|0⟩?',
          answer: V.q7BraMinusYZeroRe,
          tolerance: 0.005,
          hints: [{ text: 'Every basis state has 1/√2 on |0⟩.' }, { text: 'It is real.' }, { text: 'The bra keeps it.' }],
          walkthrough: [{ text: `${d(V.q7BraMinusYZeroRe, 3)}.` }],
        },
        {
          id: 'q7-b-zeta',
          kind: 'choice',
          tier: 'core',
          title: 'A y reading of +1',
          prompt: 'What is ζ for a y-basis reading of +1?',
          options: [
            { text: '−i', correct: true, why: 'ζ = −iε in the y basis, and ε = +1.' },
            { text: 'i', correct: false, why: 'That is ζ for a reading of −1, not +1.' },
            { text: '1', correct: false, why: 'That is the x-basis value, not y.' },
            { text: '−1', correct: false, why: 'ζ in the y basis is imaginary, never −1.' },
          ],
          hints: [{ text: 'ζ = −iε in y.' }, { text: 'ε = +1.' }, { text: '−i.' }],
          walkthrough: [{ text: '−i, from ⟨+y|1⟩ = −i/√2.' }],
        },
        {
          id: 'q7-b-one',
          kind: 'numeric',
          tier: 'core',
          title: 'A bracket with |1⟩',
          prompt: 'What is the imaginary part of ⟨+y|1⟩?',
          answer: V.q7BraPlusYOneIm,
          tolerance: 0.005,
          hints: [{ text: '|+y⟩ has i/√2 on |1⟩.' }, { text: 'A bra conjugates.' }, { text: '−i/√2.' }],
          walkthrough: [{ text: `${d(V.q7BraPlusYOneIm, 3)}.` }],
        },
        {
          id: 'q7-b-real',
          kind: 'choice',
          tier: 'stretch',
          title: 'When is ζ real?',
          prompt: 'For which readings is ζ_k a real number?',
          options: [
            { text: 'x-basis readings', correct: true, why: 'ζ = ε is real in the x basis.' },
            { text: 'y-basis readings', correct: false, why: 'The y case carries −i.' },
            { text: 'readings of +1 only', correct: false, why: 'The basis decides this, not the sign.' },
            { text: 'all readings', correct: false, why: 'The y case carries −i: not real.' },
          ],
          hints: [{ text: 'Look at the two cases of Eq. 2.9.' }, { text: 'The y case carries −i.' }, { text: 'The x case is ±1.' }],
          walkthrough: [{ text: 'x-basis readings.' }],
        },
      ],
    },
    {
      id: 'q7-parity-table',
      story: Q7_STORY['q7-parity-table'],
      review: Q7_REVIEW['q7-parity-table'],
      title: 'One formula for every run',
      question: 'Can one number predict the chance of every outcome of every run?',
      lecture: { pages: 'notes L6 pp. 30–31, Eq. 2.10, the table', summary: 'Every GHZ bracket is (1 + s)/4 with $s = (-i)^{n_y}\\Pi$, so the whole table of chances follows from one formula.' },
      books: [],
      visual: { kind: 'phase-dial', props: { theta: 270, rotations: true }, tryThis: ['Turn once, twice, three times: −i, −1, i.'] },
      clues: [],
      insight: 'A GHZ bracket is (1 + s)/4; squaring its size gives ¼, 0 or ⅛ depending on s.',
      insightFormal: 'Factoring $s = (-i)^{n_y}\\Pi$ separates what the chosen bases fix from what the actual readings decide, collapsing the whole 64-run table into one formula.',
      pitfalls: ['Taking the chance to be |1 + s|/4 instead of |1 + s|²/16.'],
      play: [
        {
          id: 'q7-t-s',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Finding s',
          prompt: 'In a YYX run with Π = −1, what is s?',
          answer: V.q7SYyxPiMinusRe,
          tolerance: 0.5,
          hints: [{ text: 'n_y = 2.' }, { text: '(−i)² = −1.' }, { text: '(−1)(−1).' }],
          walkthrough: [{ text: 's = 1, so that outcome has ¼.' }],
        },
        {
          id: 'q7-t-p',
          kind: 'numeric',
          tier: 'core',
          title: 'A chance from s',
          prompt: 'If s = −i, what is the chance |1 + s|²/16?',
          answer: V.q7P1AtSNegI,
          tolerance: 0.005,
          hints: [{ text: '|1 − i|² = 2.' }, { text: 'Divide by 16.' }, { text: '⅛.' }],
          walkthrough: [{ text: '0.125.' }],
        },
        {
          id: 'q7-t-hw-xxx',
          kind: 'numeric',
          tier: 'core',
          title: 'An XXX bracket by hand',
          prompt: 'Evaluate ⟨+x,+x,+x|GHZ⟩.',
          answer: V.q7BracketXxxAllPlus,
          tolerance: 0.005,
          hints: [{ text: 'Two terms.' }, { text: '⟨+x|0⟩³ = ⟨+x|1⟩³ = 1/(2√2).' }, { text: 'Add and multiply by 1/√2.' }],
          walkthrough: [
            { text: '(1/√2)(1/(2√2) + 1/(2√2)) = ½, chance ¼. With the last reading −1 the second term flips sign and the bracket is 0. Both agree with (1+s)/4, s = Π = ±1: an XXX run gives the four even patterns, ¼ each.' },
          ],
        },
        {
          id: 'q7-t-hw-yyx',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A YYX chance by hand',
          prompt: 'In a YYX run, what is the chance of the readings +1, +1, −1?',
          answer: V.q7PYyxPiMinus,
          tolerance: 0.005,
          hints: [{ text: 'n_y = 2.' }, { text: 'Π = −1.' }, { text: 's = (−i)²Π.' }],
          walkthrough: [{ text: 's = (−1)(−1) = 1, so P = ¼. The surviving YYX patterns are exactly those with Π = −1, as ⟨YYX⟩ = −1 requires.' }],
        },
      ],
    },
    {
      id: 'q7-bit-strings',
      story: Q7_STORY['q7-bit-strings'],
      review: Q7_REVIEW['q7-bit-strings'],
      title: 'Surviving strings carry the parity',
      question: 'Which bit strings survive each run, and what do they share?',
      lecture: { pages: 'notes L6 pp. 31–32', summary: 'A run’s surviving strings all share one parity, even or odd, decided by how many qubits were read in y.' },
      books: [],
      visual: { kind: 'deposit-stats', props: { state: '+z', axis: 'x', seed: 709 }, tryThis: ['Fire 50: one qubit of GHZ alone, close to half each way.'] },
      clues: [],
      insight: 'XXX keeps the even strings; two y’s keep the odd ones; an odd number of y’s keeps all eight.',
      insightFormal: 'Writing down a surviving string already records Π: the single readings are random, yet the product they encode is fixed by the chosen bases alone.',
      pitfalls: ['Thinking random single readings mean a random product.'],
      play: [
        {
          id: 'q7-s-even',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which string survives?',
          prompt: 'Which string can an XXX run produce?',
          options: [
            { text: '011', correct: true, why: 'Two 1s: an even string, so it occurs.' },
            { text: '001', correct: false, why: 'One 1: odd, forbidden in XXX.' },
            { text: '111', correct: false, why: 'Three 1s: odd, forbidden in XXX.' },
            { text: '010', correct: false, why: 'One 1: odd, forbidden in XXX.' },
          ],
          hints: [{ text: 'Count the 1s.' }, { text: 'XXX keeps even strings.' }, { text: 'Two 1s.' }],
          walkthrough: [{ text: '011.' }],
        },
        {
          id: 'q7-s-yxy',
          kind: 'numeric',
          tier: 'core',
          title: 'An even string in YXY',
          prompt: 'In a YXY run, what is the chance of the string 000?',
          answer: V.q7TableYxy000,
          tolerance: 0.005,
          hints: [{ text: 'Two y’s.' }, { text: 'Odd strings survive.' }, { text: '000 is even.' }],
          walkthrough: [{ text: '0.' }],
        },
        {
          id: 'q7-s-xxy',
          kind: 'numeric',
          tier: 'core',
          title: 'An odd-y run',
          prompt: 'In an XXY run, what is the chance of the string 101?',
          answer: V.q7TableXxy101,
          tolerance: 0.005,
          hints: [{ text: 'One y.' }, { text: 's is imaginary.' }, { text: 'All strings equal.' }],
          walkthrough: [{ text: '⅛.' }],
        },
        {
          id: 'q7-s-single',
          kind: 'numeric',
          tier: 'stretch',
          title: 'One qubit alone',
          prompt: 'In an XXX run, what is the chance that qubit 1 alone reads +1?',
          answer: V.q7SingleXProb,
          tolerance: 0.005,
          hints: [{ text: 'Add the even strings that start with 0.' }, { text: '000 and 011.' }, { text: '¼ + ¼.' }],
          walkthrough: [{ text: '½: the single reading is random, the product is not.' }],
        },
      ],
    },
    {
      id: 'q7-observables',
      story: Q7_STORY['q7-observables'],
      review: Q7_REVIEW['q7-observables'],
      title: 'Four products with certain values',
      question: 'Which three-qubit quantities does GHZ fix, and how can all four be certain at once?',
      lecture: { pages: 'notes L7 p. 33, Eqs. 2.11–2.12', summary: 'XXX, YYX, YXY, XYY commute and have GHZ as a common eigenstate with zero spread, though each factor alone is maximally random.' },
      books: [],
      visual: { kind: 'amplitude-bars', props: { state: [90, 0], basis: 'x', editable: true }, tryThis: ['At θ = 90°, φ = 0 the x reading never varies.', 'Set θ = 0: half and half.'] },
      clues: [],
      insight: 'XXX, YYX, YXY, XYY all commute and all have GHZ as an eigenstate: their product values are certain.',
      insightFormal: 'Zero dispersion on a product of three maximally uncertain single-qubit readings is the heart of the Mermin argument Unit 7.6 builds on.',
      pitfalls: ['Reading −GHZ as a new state: the −1 is the eigenvalue.'],
      play: [
        {
          id: 'q7-o-eig',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'An eigenvalue of GHZ',
          prompt: 'What is the eigenvalue of σ_x1σ_x2σ_x3 on GHZ?',
          answer: V.q7EigXxx,
          tolerance: 0.5,
          hints: [{ text: 'X flips a bit.' }, { text: '000 and 111 trade places.' }, { text: 'The sum is unchanged.' }],
          walkthrough: [{ text: '+1.' }],
        },
        {
          id: 'q7-o-yyx',
          kind: 'numeric',
          tier: 'core',
          title: 'An eigenvalue with two Y’s',
          prompt: 'What is the eigenvalue of σ_y1σ_y2σ_x3 on GHZ?',
          answer: V.q7EigYyx,
          tolerance: 0.5,
          hints: [{ text: 'σ_y|0⟩ = i|1⟩, σ_y|1⟩ = −i|0⟩.' }, { text: 'Apply to |000⟩ and |111⟩.' }, { text: 'i² and (−i)².' }],
          walkthrough: [{ text: 'YYX|000⟩ = i·i|111⟩ = −|111⟩ and YYX|111⟩ = (−i)(−i)|000⟩ = −|000⟩, so YYX|GHZ⟩ = −|GHZ⟩.' }],
        },
        {
          id: 'q7-o-sym',
          kind: 'choice',
          tier: 'core',
          title: 'Sharing an eigenvalue',
          prompt: 'Which symmetry of GHZ gives YXY and XYY the eigenvalue of YYX?',
          options: [
            { text: 'GHZ is unchanged by any renumbering of its qubits', correct: true, why: 'Renumbering maps YYX to YXY or XYY and leaves GHZ unchanged.' },
            { text: 'GHZ is unchanged by flipping all three bits', correct: false, why: 'True, but that symmetry gives XXX’s eigenvalue, not YYX’s.' },
            { text: 'GHZ has real amplitudes', correct: false, why: 'Real amplitudes do not explain the shared eigenvalue.' },
            { text: 'XXX commutes with YYX', correct: false, why: 'True but unrelated to why YXY, XYY share YYX’s value.' },
          ],
          hints: [{ text: 'Compare YXY with YYX.' }, { text: 'Swap qubits 2 and 3.' }, { text: 'What does that swap do to GHZ?' }],
          walkthrough: [{ text: 'Renumbering the qubits maps YYX to YXY or XYY and leaves GHZ unchanged, so all three share the eigenvalue −1.' }],
        },
        {
          id: 'q7-o-var',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A single qubit’s spread',
          prompt: 'What is the variance of σ_x1 in GHZ?',
          answer: V.q7VarX1,
          tolerance: 0.005,
          hints: [{ text: '⟨σ_x1⟩ = 0.' }, { text: 'σ_x1² = I.' }, { text: '1 − 0.' }],
          walkthrough: [{ text: '1, the largest a ±1 observable can have.' }],
        },
      ],
    },
    {
      id: 'q7-mermin',
      story: Q7_STORY['q7-mermin'],
      review: Q7_REVIEW['q7-mermin'],
      title: 'No instruction set can do it',
      question: 'Could each qubit carry its answers fixed in advance?',
      lecture: { pages: 'notes L7 pp. 33–34, Eq. 2.13', summary: 'No card of predetermined answers matches all four quantum results; operators escape because order matters, cards cannot.' },
      books: [{ source: 'bergou', where: '⚑ Problem 10.1(a), p. 186', adds: 'GHZ’s stabilizer generators, shown as an aside connecting to Part IX.' }],
      visual: { kind: 'amplitude-bars', props: { state: [90, 45], basis: 'x', editable: true }, tryThis: ['Turn the state and watch the x chance move.', 'No setting keeps the x and y readings both sure.'] },
      clues: [],
      insight: 'The three y-relations force x₁x₂x₃ = −1, but XXX measures +1: no hidden card can match all four.',
      insightFormal: 'Mermin’s argument needs only one run of each of four settings, since every quantum prediction here has zero dispersion: a sharper refutation of local realism than a statistical Bell inequality.',
      pitfalls: ['Treating operators as numbers, which drops the minus sign the anticommutation supplies.'],
      play: [
        {
          id: 'q7-m-cards',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Counting the cards',
          prompt: 'How many instruction cards (x₁, x₂, x₃, y₁, y₂, y₃, each ±1) are there?',
          answer: V.q7MerminTotal,
          tolerance: 0.5,
          hints: [{ text: 'Six answers.' }, { text: 'Two choices each.' }, { text: '2⁶.' }],
          walkthrough: [{ text: '64.' }],
        },
        {
          id: 'q7-m-forced',
          kind: 'numeric',
          tier: 'core',
          title: 'What the y-relations force',
          prompt: 'Multiply the three relations that contain two y’s. What value do they force on x₁x₂x₃?',
          answer: V.q7Forced,
          tolerance: 0.5,
          hints: [{ text: 'Each y appears twice.' }, { text: 'y_i² = 1.' }, { text: '(−1)³.' }],
          walkthrough: [
            { text: '(y₁y₂x₃)(y₁x₂y₃)(x₁y₂y₃) = x₁x₂x₃ = (−1)³ = −1, against +1 for XXX. No hidden values work. It is sharper than a Bell violation because each prediction is certain, so single runs decide, with no averages.' },
          ],
        },
        {
          id: 'q7-m-best',
          kind: 'numeric',
          tier: 'core',
          title: 'The best a card can do',
          prompt: 'At most how many of the four results can one card match?',
          answer: V.q7MerminBest,
          tolerance: 0.5,
          hints: [{ text: 'Not all four.' }, { text: 'A card’s four products multiply to +1.' }, { text: 'The quantum values multiply to −1.' }],
          walkthrough: [{ text: '3; half the cards score 3, half score 1.' }],
        },
        {
          id: 'q7-m-sign',
          kind: 'choice',
          tier: 'stretch',
          title: 'Where the sign comes from',
          prompt: 'In the operator product (YYX)(YXY)(XYY), which qubit supplies the minus sign?',
          options: [
            { text: 'qubit 2', correct: true, why: 'Qubit 2 gets Y·X·Y = −X.' },
            { text: 'qubit 1', correct: false, why: 'Qubit 1 gets Y·Y·X = X, no sign.' },
            { text: 'qubit 3', correct: false, why: 'Qubit 3 gets X·Y·Y = X, no sign.' },
            { text: 'none of them', correct: false, why: 'One qubit does supply a sign: qubit 2.' },
          ],
          hints: [{ text: 'Read each qubit’s three factors in order.' }, { text: 'Qubit 2 gets Y, X, Y.' }, { text: 'Y·X·Y = −X.' }],
          walkthrough: [{ text: 'Qubit 2.' }],
        },
      ],
    },
  ],
}
