import type { Lecture } from '../schema'
import { Q8_REVIEW } from './Q8.review'
import { Q8_STORY } from './Q8.story'
import { BOX, N, RHO_MINUS, RHO_PSI1, V, claim, close, d } from './Q8.values'

// Physics 709, chapter Q8: "Mixtures, the density matrix and the Bloch ball" (notes L7 pp. 34-38; Bergou §2.1-2.4,
// pp. 15-24), in both tracks. Every number a learner sees is computed in Q8.values.ts, then asserted in keyed claims
// (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy, pipeline/claims_qc709/q8.py). Plan:
// docs/roles/proposals/P-Q8-story.md; rulings docs/roles/decisions/qc709-Q8Q9.md. Q8 owns ρ, Tr, coherences,
// mixtures, purity, the Bloch ball, positivity, convexity, the recipes and the von Neumann equation. HW2 is
// submitted (homework-status.md), so its P4 and P6 items get full walkthroughs below.

export const Q8: Lecture = {
  id: 'Q8',
  number: 8,
  title: 'Mixtures, the density matrix and the Bloch ball',
  outcomes: [
    'Explain why a box from which a reading was lost is a coin toss, not a superposition, and name the x test that tells them apart.',
    'Write a pure state as the matrix ρ = |ψ⟩⟨ψ|, read chances off its diagonal and phases off its corners.',
    'Compute an average as Tr(Aρ), and say what a reading without a record does to ρ.',
    'State how ρ moves in time, and why a diagonal ρ stands still under a field along z.',
    'Build ρ for a mixture, and use Tr ρ² to tell mixed from pure.',
    'Place any one-qubit ρ in the Bloch ball, from ρ = ½(I + r·σ) and the three averages rⱼ = Tr(ρσⱼ).',
    'Show that one ρ has many recipes, and that a pure state has exactly one.',
  ],
  prerequisites: [
    'qc-ghz',
    'qc-bell-basis-station',
    'qc-correlation-grid',
    'qc-born-projector',
    'qc-bloch-sphere',
    'qc-spin-operators',
    'qc-observables',
    'qc-uncertainty',
    'qc-operator-matrix',
    'qc-photon-frames',
    'qc-sg-quantization',
  ],
  symbols: {
    // q8-why
    '|000\\rangle': 'q8-why:b1',
    '|111\\rangle': 'q8-why:b1',
    '|00\\rangle': 'q8-why:b1',
    '|11\\rangle': 'q8-why:b1',
    '|\\cdot\\rangle': 'q8-why:b1',
    P: 'q8-why:b1',
    '\\langle\\cdot\\rangle': 'q8-why:b2',
    Z_1: 'q8-why:b2',
    Z_2: 'q8-why:b2',
    '\\Phi': 'q8-why:b3',
    '\\beta_00': 'q8-why:b3',
    '\\Psi_+': 'q8-why:b3',
    X_1: 'q8-why:b3',
    X_2: 'q8-why:b3',
    X: 'q8-why:b3',
    '\\langle\\cdot|\\cdot\\rangle': 'q8-why:b3',
    '\\langle\\cdot|': 'q8-why:b3',
    r_1: 'q8-why:b4',
    r_2: 'q8-why:b4',
    T_zz: 'q8-why:b4',
    Y_1: 'q8-why:b5',
    Y_2: 'q8-why:b5',
    Y: 'q8-why:b5',
    '|0\\rangle': 'q8-why.play.q8-w-xx',

    // q8-pure-rho
    '|\\psi\\rangle': 'q8-pure-rho',
    '|1\\rangle': 'q8-pure-rho:b1',
    '\\rho': 'q8-pure-rho:b1',
    '\\theta': 'q8-pure-rho:b1',
    '\\varphi': 'q8-pure-rho:b1',
    e: 'q8-pure-rho:b1',
    i: 'q8-pure-rho:b1',
    c_0: 'q8-pure-rho:b2',
    c_1: 'q8-pure-rho:b2',
    c_i: 'q8-pure-rho:b2',
    c_j: 'q8-pure-rho:b2',
    '|i\\rangle': 'q8-pure-rho:b2',
    '|j\\rangle': 'q8-pure-rho:b2',
    '|e_i\\rangle': 'q8-pure-rho:b2',
    '|e_j\\rangle': 'q8-pure-rho:b2',
    '\\rho_ij': 'q8-pure-rho:b2',
    '\\rho_ii': 'q8-pure-rho:b2',
    j: 'q8-pure-rho:b2',
    A: 'q8-pure-rho:b3',
    '\\rho_00': 'q8-pure-rho:b3',
    '\\rho_11': 'q8-pure-rho:b3',
    '\\rho_01': 'q8-pure-rho:b4',
    '\\rho_10': 'q8-pure-rho:b4',
    '\\rho_ji': 'q8-pure-rho:b4',
    '\\dagger': 'q8-pure-rho:b4',
    '\\gamma': 'q8-pure-rho:b5',
    '|+\\rangle': 'q8-pure-rho.play.q8-p-minus',
    '|-\\rangle': 'q8-pure-rho.play.q8-p-minus',

    // q8-trace-rule
    '\\sigma_x': 'q8-trace-rule:b1',
    A_ij: 'q8-trace-rule:b1',
    '\\hat H': 'q8-trace-rule:b2',
    '\\dot\\rho': 'q8-trace-rule:b2',
    '|\\dot\\psi\\rangle': 'q8-trace-rule:b2',
    '\\dot A': 'q8-trace-rule:b2',
    '\\hbar': 'q8-trace-rule:b2',
    d: 'q8-trace-rule:b2',
    t: 'q8-trace-rule:b2',
    '\\omega': 'q8-trace-rule:b2',
    Z: 'q8-trace-rule:b2',
    '\\sigma_z': 'q8-trace-rule:b3',
    P_0: 'q8-trace-rule:b4',
    P_j: 'q8-trace-rule:b4',
    p_j: 'q8-trace-rule:b4',
    p_0: 'q8-trace-rule:b4',
    p_1: 'q8-trace-rule:b4',

    // q8-mixed
    p_n: 'q8-mixed:b1',
    '|\\psi_n\\rangle': 'q8-mixed:b1',
    '\\rho_12': 'q8-mixed:b1',
    '\\lambda_j': 'q8-mixed:b2',
    r: 'q8-mixed:b3',
    n_n: 'q8-mixed:b3',
    n: 'q8-mixed:b3',
    S_z: 'q8-mixed:b4',
    S_x: 'q8-mixed:b4',
    S_y: 'q8-mixed:b4',
    S_j: 'q8-mixed:b4',
    '\\sigma_j': 'q8-mixed:b4',
    E_Z: 'q8-mixed:b5',
    k_B: 'q8-mixed:b5',
    T: 'q8-mixed:b5',
    '\\tanh': 'q8-mixed:b5',
    r_z: 'q8-mixed:b5',
    'p_\\uparrow': 'q8-mixed:b5',
    'p_\\downarrow': 'q8-mixed:b5',
    'E_\\uparrow': 'q8-mixed:b5',
    'E_\\downarrow': 'q8-mixed:b5',
    p: 'q8-mixed:b6',
    '\\sigma_y': 'q8-mixed:b6',
    I: 'q8-mixed:b7',

    // q8-ball
    a_0: 'q8-ball:b1',
    a: 'q8-ball:b1',
    '\\boldsymbol': 'q8-ball:b1',
    '\\sigma': 'q8-ball:b1',
    r_x: 'q8-ball:b1',
    r_y: 'q8-ball:b1',
    r_j: 'q8-ball:b1',
    '|\\varphi\\rangle': 'q8-ball:b2',
    '\\mathbb': 'q8-ball:b2',
    R: 'q8-ball:b2',
    '|u\\rangle': 'q8-ball:b3',
    r_k: 'q8-ball:b4',
    k: 'q8-ball:b4',
    '\\sigma_k': 'q8-ball:b4',
    '\\delta_jk': 'q8-ball:b4',
    '\\sigma_\\alpha': 'q8-ball:b5',
    'r_\\alpha': 'q8-ball:b5',
    '|\\mathbfr\\rangle': 'q8-ball.play.q8-b-state',

    // q8-recipes
    '|+x\\rangle': 'q8-recipes:b1',
    '|-x\\rangle': 'q8-recipes:b1',
    '\\lambda_\\pm': 'q8-recipes:b2',
    '|u_\\pm\\rangle': 'q8-recipes:b2',
    '|u_+\\rangle': 'q8-recipes:b2',
    '|u_-\\rangle': 'q8-recipes:b2',
    '|k\\rangle': 'q8-recipes:b2',
    '\\lambda_k': 'q8-recipes:b2',
    '\\rho_1': 'q8-recipes:b3',
    '\\rho_2': 'q8-recipes:b3',
    '\\rho_k': 'q8-recipes:b3',
    '|\\psi^\\perp\\rangle': 'q8-recipes:b3',
    p_i: 'q8-recipes:b4',
    '|\\psi_i\\rangle': 'q8-recipes:b4',
    U_ij: 'q8-recipes:b4',
    U_ik: 'q8-recipes:b4',
    U: 'q8-recipes:b4',
    q_j: 'q8-recipes:b4',
    '|\\varphi_j\\rangle': 'q8-recipes:b4',
    '|\\tilde\\psi_i\\rangle': 'q8-recipes:b4',
    '|\\tilde\\varphi_j\\rangle': 'q8-recipes:b4',
    '|\\tilde\\varphi_1,2\\rangle': 'q8-recipes:b4',
    '|\\tilde\\psi_1\\rangle': 'q8-recipes:b4',
    '|\\tilde\\varphi_1\\rangle': 'q8-recipes:b4',
    '|\\tilde\\varphi_2\\rangle': 'q8-recipes:b4',
    '|\\tilde\\psi_2\\rangle': 'q8-recipes:b4',
    '|\\tilde\\varphi_k\\rangle': 'q8-recipes:b4',
    '|+y\\rangle': 'q8-recipes:b5',
    '|-y\\rangle': 'q8-recipes:b5',
    '\\lambda': 'q8-recipes.play.q8-r-eig',
  },
  units: [
    {
      id: 'q8-why',
      story: Q8_STORY['q8-why'],
      review: Q8_REVIEW['q8-why'],
      title: 'The GHZ box: a coin, not a superposition',
      question: 'A GHZ qubit was read and the record lost: what is left in the box?',
      lecture: { pages: 'notes L7 pp. 34–35; HW2 P7(e) (stated)', summary: "Reading one of three GHZ qubits and losing the record leaves qubits 1 and 2 as a coin's choice of $|00\\rangle$ or $|11\\rangle$." },
      books: [{ source: 'bergou', where: '§2.1 p. 15, Eq. 2.1', adds: 'the ensemble average written as a trace, before ρ itself is introduced.' }],
      visual: { kind: 'sg-lab', props: { source: 'oven', axes: ['x'], editable: true, predict: true, seed: 709 }, tryThis: ['Fire 100 along x: close to 50/50.', 'Turn the analyser to z: still 50/50.'] },
      clues: [],
      insight: "A box from which a reading was lost is a mixture, not a superposition; an x reading on both qubits tells them apart.",
      insightFormal: "No ket reproduces both the z and x statistics of the box: $\\langle X_1X_2\\rangle_{\\mathrm{box}} = 0 \\ne \\langle X_1X_2\\rangle_{\\Phi^+} = 1$.",
      pitfalls: ['Thinking the same z chances mean the same state: a mixture and a superposition can share every z statistic.'],
      play: [
        {
          id: 'q8-w-01',
          kind: 'numeric',
          tier: 'warm-up',
          title: '01 in the box',
          prompt: 'In the box, what is the chance that qubits 1 and 2 read 01?',
          answer: BOX[1][1].re,
          tolerance: 0.005,
          hints: [{ text: 'What can the box hold?' }, { text: '$|00\\rangle$ or $|11\\rangle$.' }, { text: 'Neither has a 01 part.' }],
          walkthrough: [{ text: 'After reading qubit 3 the pair is $|00\\rangle$ or $|11\\rangle$, so 01 never appears.' }],
        },
        {
          id: 'q8-w-xx',
          kind: 'numeric',
          tier: 'core',
          title: 'The box’s x average',
          prompt: 'What is $\\langle X_1X_2\\rangle$ for the box?',
          answer: V.q8BoxXX,
          tolerance: 0.005,
          hints: [{ text: 'Average over the two cases.' }, { text: 'Each case is a product.' }, { text: '$\\langle0|X|0\\rangle = 0$.' }],
          walkthrough: [{ text: '$\\tfrac12\\cdot0 + \\tfrac12\\cdot0 = 0$.' }],
        },
        {
          id: 'q8-w-yy',
          kind: 'numeric',
          tier: 'core',
          title: 'Φ+’s y average',
          prompt: 'What is $\\langle Y_1Y_2\\rangle$ for $\\Phi^+$?',
          answer: V.q8PhiYY,
          tolerance: 0.005,
          hints: [{ text: "Use $\\Phi^+$'s grid from Chapter Q6." }, { text: 'Its diagonal is $(1, -1, 1)$.' }, { text: 'The $yy$ cell.' }],
          walkthrough: [{ text: '$YY\\Phi^+ = -\\Phi^+$, so the average is −1.' }],
        },
        {
          id: 'q8-w-which',
          kind: 'choice',
          tier: 'stretch',
          title: 'Which reading tells them apart?',
          prompt: 'Which reading tells the box from $\\Phi^+$?',
          options: [
            { text: 'X on both qubits, multiplied', correct: true, why: 'Right: the box gives 0, $\\Phi^+$ gives +1.' },
            { text: 'Z on both qubits, multiplied', correct: false, why: 'Both give +1: z statistics agree.' },
            { text: 'Z on qubit 1 alone', correct: false, why: 'Single-qubit z readings look the same in both.' },
            { text: 'X on qubit 1 alone', correct: false, why: 'Single-qubit x readings look the same in both.' },
          ],
          hints: [{ text: 'Single qubits look alike in both.' }, { text: 'z products agree too.' }, { text: 'Try x products.' }],
          walkthrough: [{ text: 'Only the $xx$ (or $yy$) cell differs: 0 against 1.' }],
        },
      ],
    },
    {
      id: 'q8-pure-rho',
      story: Q8_STORY['q8-pure-rho'],
      review: Q8_REVIEW['q8-pure-rho'],
      title: 'One state as a matrix',
      question: 'What do we gain by writing a state as $|\\psi\\rangle\\langle\\psi|$?',
      lecture: { pages: 'notes L7 p. 35; Bergou §2.1 p. 17, Eq. 2.11', summary: 'A pure state written as the projector $\\rho = |\\psi\\rangle\\langle\\psi|$: chances on the diagonal, phase in the corners.' },
      books: [{ source: 'bergou', where: '§2.1 p. 17, Eq. 2.11', adds: 'the projector form of a pure-state density matrix.' }],
      visual: { kind: 'phase-dial', props: { theta: 60, rotations: true }, tryThis: ['Turn the dial a full lap: the chances never change.'] },
      clues: [],
      insight: '$\\rho = |\\psi\\rangle\\langle\\psi|$: chances on the diagonal, the relative phase in the corners.',
      insightFormal: '$\\rho_{ij} = c_ic_j^*$; $\\rho$ is Hermitian with unit trace, and a global phase on $|\\psi\\rangle$ leaves it unchanged.',
      pitfalls: ['Reading a coherence as a chance: the corners can be complex and even negative.'],
      play: [
        {
          id: 'q8-p-diag',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A diagonal entry',
          prompt: 'For $|\\psi\\rangle = (\\sqrt3|0\\rangle + |1\\rangle)/2$, what is $\\rho_{11}$?',
          answer: RHO_PSI1[1][1].re,
          tolerance: 0.005,
          hints: [{ text: 'Diagonal entries are chances.' }, { text: '$|c_1|^2$.' }, { text: '$(1/2)^2$.' }],
          walkthrough: [{ text: '0.25.' }],
        },
        {
          id: 'q8-p-coh',
          kind: 'numeric',
          tier: 'core',
          title: 'A coherence',
          prompt: 'For the same state, what is $\\rho_{01}$?',
          answer: RHO_PSI1[0][1].re,
          tolerance: 0.005,
          hints: [{ text: '$\\rho_{01} = c_0c_1^*$.' }, { text: 'Both amplitudes are real.' }, { text: '$\\tfrac{\\sqrt3}2\\cdot\\tfrac12$.' }],
          walkthrough: [{ text: '$\\sqrt3/4 = 0.433$.' }],
        },
        {
          id: 'q8-p-minus',
          kind: 'numeric',
          tier: 'core',
          title: 'Minus’s coherence',
          prompt: '$|+\\rangle$ has $\\rho_{01} = \\tfrac12$. What is $\\rho_{01}$ for $|-\\rangle$?',
          answer: RHO_MINUS[0][1].re,
          tolerance: 0.005,
          hints: [{ text: 'Same chances.' }, { text: 'The relative sign flips.' }, { text: '$\\tfrac1{\\sqrt2}\\cdot(-\\tfrac1{\\sqrt2})$.' }],
          walkthrough: [{ text: "−0.5: only the coherence tells $|+\\rangle$ from $|-\\rangle$." }],
        },
        {
          id: 'q8-p-phase',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A turned corner',
          prompt: 'Unit 3.2’s state is turned to $\\varphi$ = 135°, $\\theta$ unchanged. What is the phase of $\\rho_{01}$, in degrees?',
          answer: V.q8RhoQuarter01Deg,
          tolerance: 0.5,
          unit: '°',
          hints: [{ text: '$\\rho_{01} = c_0c_1^*$.' }, { text: '$c_1$ carries $e^{i\\varphi}$.' }, { text: 'Its mirror carries $e^{-i\\varphi}$.' }],
          walkthrough: [{ text: '$\\rho_{01} = 0.433e^{-i135^\\circ}$.' }],
        },
      ],
    },
    {
      id: 'q8-trace-rule',
      story: Q8_STORY['q8-trace-rule'],
      review: Q8_REVIEW['q8-trace-rule'],
      title: 'Averages and motion from the density matrix',
      question: 'How do averages, readings and time evolution look in the matrix language?',
      lecture: { pages: 'notes L7 p. 36; Bergou §2.1 p. 15, Eq. 2.1; §5.2 p. 80', summary: 'An average is a trace, $\\langle A\\rangle = \\mathrm{Tr}(A\\rho)$; ρ moves in time by the von Neumann equation.' },
      books: [{ source: 'bergou', where: '§5.2 p. 80', adds: 'postulates 4a–6a: readings and their post-states written with ρ.' }],
      visual: { kind: 'bloch', props: { theta: 60, phi: 45, editable: true, measure: 'x' }, tryThis: ['Read x at θ = 60°, φ = 45°: the average is 0.612.', 'Set φ = 0°: it grows to 0.866.'] },
      clues: [],
      insight: 'An average is a trace, $\\langle A\\rangle = \\mathrm{Tr}(A\\rho)$, and ρ moves by $i\\hbar\\dot\\rho = [\\hat H, \\rho]$.',
      insightFormal: 'Postulates 4a–6a rewrite readings with ρ; the von Neumann sign is opposite to Heisenberg’s.',
      pitfalls: ["Using Heisenberg's sign for ρ: $i\\hbar\\dot\\rho = [\\rho, \\hat H]$ runs time backwards."],
      play: [
        {
          id: 'q8-t-z',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Tr(Zρ)',
          prompt: 'For Unit 3.2’s state, what is $\\mathrm{Tr}(Z\\rho)$?',
          answer: V.q8TrZN,
          tolerance: 0.005,
          hints: [{ text: 'Z keeps the diagonal and flips one sign.' }, { text: '$\\rho_{00} - \\rho_{11}$.' }, { text: '$0.75 - 0.25$.' }],
          walkthrough: [{ text: "0.5, the arrow's z part." }],
        },
        {
          id: 'q8-t-y',
          kind: 'numeric',
          tier: 'core',
          title: 'Tr(Yρ)',
          prompt: 'Same state: what is $\\mathrm{Tr}(Y\\rho)$?',
          answer: V.q8TrYN,
          tolerance: 0.005,
          hints: [{ text: 'Y reads the coherences.' }, { text: '$\\mathrm{Tr}(Y\\rho) = -2\\,\\mathrm{Im}\\,\\rho_{01}$.' }, { text: '$\\rho_{01} = 0.306 - 0.306i$.' }],
          walkthrough: [{ text: "0.612, the arrow's y part, $\\sin60^\\circ\\sin45^\\circ$." }],
        },
        {
          id: 'q8-t-nonsel',
          kind: 'numeric',
          tier: 'core',
          title: 'After an unrecorded reading',
          prompt: 'A z reading is made on this state and the record is lost. What is the new $\\rho_{01}$?',
          answer: V.q8NonSelOffDiag,
          tolerance: 0.005,
          hints: [{ text: '$\\sum_jP_j\\rho P_j$.' }, { text: 'Each $P_j$ keeps one row and one column.' }, { text: 'The corners are dropped.' }],
          walkthrough: [{ text: '$\\mathrm{diag}(0.75, 0.25)$, so 0.' }],
        },
        {
          id: 'q8-t-quarter',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A quarter turn',
          prompt: 'Under $\\hat H = \\tfrac{\\hbar\\omega}2Z$, by how many degrees does the phase of $\\rho_{01}$ turn in a quarter period?',
          answer: V.q8QuarterTurnDeg,
          tolerance: 0.5,
          unit: '°',
          hints: [{ text: '$\\rho_{01}(t) = \\rho_{01}(0)e^{-i\\omega t}$.' }, { text: 'A full period is $\\omega t = 360^\\circ$.' }, { text: 'A quarter of that.' }],
          walkthrough: [{ text: '90°, from −45° to −135°; the arrow turns 90° about z with it.' }],
        },
      ],
    },
    {
      id: 'q8-mixed',
      story: Q8_STORY['q8-mixed'],
      review: Q8_REVIEW['q8-mixed'],
      title: 'Mixtures: chances without phases',
      question: 'How do we write a box whose members are in different states?',
      lecture: { pages: 'notes L7 pp. 36–37; Bergou §2.1 p. 15, Eq. 2.2; p. 18; HW2 P4', summary: 'A mixture weights each member’s ρ by its chance; $\\mathrm{Tr}\\,\\rho^2$, the purity, tells mixed from pure.' },
      books: [{ source: 'bergou', where: 'p. 18', adds: 'the purity-based proof that $\\mathrm{Tr}\\,\\rho^2 = 1$ exactly for pure states.' }],
      visual: { kind: 'sg-lab', props: { source: 'oven', axes: ['z'], editable: true, predict: true, seed: 709 }, tryThis: ['Predict, then fire 100 along z: half and half.'] },
      clues: [],
      insight: 'A mixture weights each member’s ρ by its chance; its purity $\\mathrm{Tr}\\,\\rho^2$ falls below 1.',
      insightFormal: '$\\rho = \\sum_np_n|\\psi_n\\rangle\\langle\\psi_n|$; a qubit mixture’s arrow is the weighted average of its members’ arrows.',
      pitfalls: ['Adding amplitudes instead of matrices: a mixture of $|0\\rangle$ and $|+\\rangle$ is not the ket $(|0\\rangle + |+\\rangle)/\\text{norm}$.'],
      play: [
        {
          id: 'q8-m-box',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The box’s purity',
          prompt: 'What is $\\mathrm{Tr}\\,\\rho^2$ for the GHZ box?',
          answer: V.q8BoxPur,
          tolerance: 0.005,
          hints: [{ text: '$\\rho$ is diagonal.' }, { text: 'Square the two entries of ½.' }, { text: 'Add.' }],
          walkthrough: [{ text: '$\\tfrac14 + \\tfrac14 = 0.5$.' }],
        },
        {
          id: 'q8-m-zx',
          kind: 'numeric',
          tier: 'core',
          title: 'A corner of the ZX mix',
          prompt: 'For $\\tfrac12|0\\rangle\\langle0| + \\tfrac12|+\\rangle\\langle+|$, what is $\\rho_{01}$?',
          answer: V.q8ZX01,
          tolerance: 0.005,
          hints: [{ text: '$|0\\rangle\\langle0|$ has no corner.' }, { text: '$|+\\rangle\\langle+|$ has ½ in each corner.' }, { text: 'Half of ½.' }],
          walkthrough: [{ text: '0.25.' }],
        },
        {
          id: 'q8-m-p4',
          kind: 'numeric',
          tier: 'core',
          title: 'HW2 P4(a)–(b): purity at p = 0.25',
          prompt: '$\\rho = p|1\\rangle\\langle1| + (1 - p)|+\\rangle\\langle+|$ at $p = 0.25$. What is $\\mathrm{Tr}\\,\\rho^2$?',
          answer: V.q8P4Pur,
          tolerance: 0.005,
          hints: [{ text: 'Write the 2 × 2 matrix.' }, { text: '$\\tfrac12\\begin{pmatrix}1 - p & 1 - p\\\\ 1 - p & 1 + p\\end{pmatrix}$.' }, { text: 'Add the squared entries.' }],
          walkthrough: [
            { text: '(a) $|1\\rangle\\langle1| = \\mathrm{diag}(0, 1)$ and $|+\\rangle\\langle+|$ has ½ everywhere, so $\\rho = \\tfrac12\\begin{pmatrix}1 - p & 1 - p\\\\ 1 - p & 1 + p\\end{pmatrix}$.' },
            { text: '(b) $\\mathrm{Tr}\\,\\rho^2 = \\tfrac14\\big(3(1 - p)^2 + (1 + p)^2\\big) = 1 - p + p^2 = 1 - p(1 - p)$, below 1 whenever $0 < p < 1$. At $p = 0.25$ it is 0.8125.' },
          ],
        },
        {
          id: 'q8-m-p4c',
          kind: 'numeric',
          tier: 'core',
          title: 'HW2 P4(c): an average at p = 0.25',
          prompt: 'Same $\\rho$ at $p = 0.25$: what is $\\langle\\sigma_x\\rangle$?',
          answer: V.q8P4SigX,
          tolerance: 0.005,
          hints: [{ text: '$\\langle\\sigma_x\\rangle = \\rho_{01} + \\rho_{10}$.' }, { text: 'Each corner is $(1 - p)/2$.' }, { text: 'Add them.' }],
          walkthrough: [
            { text: '$\\langle\\sigma_x\\rangle = 1 - p = 0.75$; $\\langle\\sigma_y\\rangle = i(\\rho_{01} - \\rho_{10}) = 0$ because the corners are real; $\\langle\\sigma_z\\rangle = \\rho_{00} - \\rho_{11} = -p = -0.25$. The arrow $(1 - p, 0, -p)$ runs along the chord from $|+\\rangle$ to $|1\\rangle$.' },
          ],
        },
        {
          id: 'q8-m-thermal',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A thermal chance',
          prompt: 'Spins in a field with $E_Z = 2k_BT$: what is the chance $p_\\uparrow$?',
          answer: V.q8ThermPUp,
          tolerance: 0.001,
          hints: [{ text: '$p_\\uparrow/p_\\downarrow = e^{E_Z/k_BT}$.' }, { text: '$e^2$ to 1.' }, { text: '$e^2/(e^2 + 1)$.' }],
          walkthrough: [{ text: '0.881; then $\\langle S_z\\rangle = \\tfrac\\hbar2(0.881 - 0.119) = 0.381\\hbar$.' }],
        },
      ],
    },
    {
      id: 'q8-ball',
      story: Q8_STORY['q8-ball'],
      review: Q8_REVIEW['q8-ball'],
      title: 'The Bloch ball: mixed states inside',
      question: 'Where do mixed states sit, if pure states fill the sphere’s surface?',
      lecture: { pages: 'notes L7 p. 37, Eqs. 2.14–2.16; Bergou §2.3 p. 19, Eqs. 2.18–2.20; N&C Ex. 2.72 p. 105; HW2 P6', summary: 'Every one-qubit ρ is $\\tfrac12(I + \\mathbf r\\cdot\\boldsymbol\\sigma)$; positivity gives $|\\mathbf r| \\le 1$, the Bloch ball.' },
      books: [{ source: 'nc', where: 'Exercise 2.72, p. 105', adds: 'the Bloch ball stated as an exercise, with the same $\\rho(\\mathbf r)$ form.' }],
      visual: { kind: 'bloch', props: { theta: 45, phi: 0, editable: true, landmarks: true }, tryThis: ['Drag the point anywhere on the surface: every surface point is pure.'] },
      clues: [],
      insight: '$\\rho = \\tfrac12(I + \\mathbf r\\cdot\\boldsymbol\\sigma)$, $|\\mathbf r| \\le 1$: the Bloch ball, surface pure, inside mixed.',
      insightFormal: '$\\det\\rho = \\tfrac14(1 - |\\mathbf r|^2) \\ge 0$ forces $|\\mathbf r| \\le 1$; $r_j = \\mathrm{Tr}(\\rho\\sigma_j)$.',
      pitfalls: ['Reading a short arrow as "partly up": it is a mixture whose every reading is less certain.'],
      play: [
        {
          id: 'q8-b-det',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A determinant',
          prompt: 'For $\\mathbf r = (0.5, 0, 0.5)$, what is $\\det\\rho$?',
          answer: V.q8ZXDet,
          tolerance: 0.005,
          hints: [{ text: '$\\det\\rho = (1 - |\\mathbf r|^2)/4$.' }, { text: '$|\\mathbf r|^2 = 0.5$.' }, { text: '$0.5/4$.' }],
          walkthrough: [{ text: '0.125.' }],
        },
        {
          id: 'q8-b-pur',
          kind: 'numeric',
          tier: 'core',
          title: 'HW2 P6(a)–(b): purity at |r| = 0.5',
          prompt: '$\\rho = \\tfrac12(I + \\mathbf r\\cdot\\boldsymbol\\sigma)$ with $|\\mathbf r| = 0.5$. What is $\\mathrm{Tr}\\,\\rho^2$?',
          answer: V.q8PurRHalf,
          tolerance: 0.005,
          hints: [{ text: 'Square $\\tfrac12(I + \\mathbf r\\cdot\\boldsymbol\\sigma)$.' }, { text: '$(\\mathbf r\\cdot\\boldsymbol\\sigma)^2 = |\\mathbf r|^2I$.' }, { text: 'Take the trace.' }],
          walkthrough: [
            { text: '(a) Any 2 × 2 matrix is $a_0I + \\mathbf a\\cdot\\boldsymbol\\sigma$; Hermiticity makes the coefficients real and unit trace fixes $a_0 = \\tfrac12$, so $\\rho = \\tfrac12(I + \\mathbf r\\cdot\\boldsymbol\\sigma)$ with $\\mathbf r = 2\\mathbf a$ real; $\\det\\rho = (1 - |\\mathbf r|^2)/4 \\ge 0$ gives $|\\mathbf r| \\le 1$.' },
            { text: '(b) $\\mathrm{Tr}\\,\\rho^2 = \\tfrac12(1 + |\\mathbf r|^2)$ is 1 iff $|\\mathbf r| = 1$: pure on the surface, mixed inside. Here $\\tfrac12(1 + 0.25) = 0.625$.' },
          ],
        },
        {
          id: 'q8-b-avg',
          kind: 'numeric',
          tier: 'core',
          title: 'HW2 P6(c): an average',
          prompt: 'For $\\rho = \\begin{pmatrix}3/4 & 1/4\\\\ 1/4 & 1/4\\end{pmatrix}$, what is $\\langle\\sigma_x\\rangle$?',
          answer: V.q8ZXRx,
          tolerance: 0.005,
          hints: [{ text: '$\\langle\\sigma_\\alpha\\rangle = \\mathrm{Tr}(\\rho\\sigma_\\alpha)$.' }, { text: 'For $\\sigma_x$ this adds the two corners.' }, { text: '$\\tfrac14 + \\tfrac14$.' }],
          walkthrough: [{ text: '$\\mathrm{Tr}(\\rho\\sigma_\\alpha) = \\tfrac12\\sum_kr_k\\mathrm{Tr}(\\sigma_k\\sigma_\\alpha) = r_\\alpha$, since $\\mathrm{Tr}(\\sigma_j\\sigma_k) = 2\\delta_{jk}$. So $\\langle\\sigma_x\\rangle = r_x = 0.5$.' }],
        },
        {
          id: 'q8-b-state',
          kind: 'numeric',
          tier: 'core',
          title: 'HW2 P6(d): a surface state',
          prompt: 'The pure state with $\\mathbf r$ at $\\theta$ = 60°, $\\varphi$ = 45°: what is the size of its $|1\\rangle$ amplitude?',
          answer: Math.hypot(N[1].re, N[1].im),
          tolerance: 0.005,
          hints: [{ text: 'Surface points are pure.' }, { text: '$\\cos\\tfrac\\theta2|0\\rangle + e^{i\\varphi}\\sin\\tfrac\\theta2|1\\rangle$.' }, { text: '$\\sin30^\\circ$.' }],
          walkthrough: [{ text: 'For $|\\mathbf r| = 1$, $\\rho$ has eigenvalues 1 and 0, and $\\rho = |\\mathbf r\\rangle\\langle\\mathbf r|$ with $|\\mathbf r\\rangle = \\cos\\tfrac\\theta2|0\\rangle + e^{i\\varphi}\\sin\\tfrac\\theta2|1\\rangle$ (check: $\\langle\\boldsymbol\\sigma\\rangle = \\mathbf r$, Unit 3.2). Here $\\sin30^\\circ = 0.5$, with phase 45°.' }],
        },
        {
          id: 'q8-b-bad',
          kind: 'choice',
          tier: 'stretch',
          title: 'Which is not a density matrix?',
          prompt: 'Which of these is not a density matrix?',
          options: [
            { text: '$\\tfrac12I + \\tfrac1{\\sqrt2}\\sigma_x$', correct: true, why: '$|\\mathbf r| = \\sqrt2 > 1$, eigenvalues 1.207 and −0.207.' },
            { text: '$\\tfrac12I + \\tfrac12\\sigma_x$', correct: false, why: '$|\\mathbf r| = 1$: a surface point.' },
            { text: '$\\tfrac12I + \\tfrac12\\sigma_z$', correct: false, why: '$|\\mathbf r| = 1$: a surface point.' },
            { text: '$\\tfrac12I$', correct: false, why: '$|\\mathbf r| = 0$: the centre.' },
          ],
          hints: [{ text: 'Read off $\\mathbf r = 2\\mathbf a$.' }, { text: 'Is $|\\mathbf r| \\le 1$?' }, { text: '$2\\cdot\\tfrac1{\\sqrt2} = \\sqrt2$.' }],
          walkthrough: [{ text: '$|\\mathbf r| = \\sqrt2 > 1$, eigenvalues 1.207 and −0.207.' }],
        },
      ],
    },
    {
      id: 'q8-recipes',
      story: Q8_STORY['q8-recipes'],
      review: Q8_REVIEW['q8-recipes'],
      title: 'One matrix, many recipes',
      question: 'If two boxes give the same matrix, can any experiment tell them apart?',
      lecture: { pages: 'notes L7 pp. 37–38, Eqs. 2.17–2.21; Bergou pp. 19–21, Eqs. 2.21–2.28; N&C Thm 2.6 p. 103', summary: 'One $\\rho$ has many ensembles; two recipes are linked by a unitary table, and a pure state has exactly one.' },
      books: [{ source: 'nc', where: 'Theorem 2.6, p. 103', adds: 'the unitary-freedom theorem for ensembles sharing one ρ.' }],
      visual: { kind: 'operator-builder', props: { axis: 'x' }, tryThis: ['Give both eigenstates the value ½: the result is $\\tfrac12I$, the centre.'] },
      clues: [],
      insight: 'One $\\rho$ has many recipes; no experiment can tell them apart, and a pure state has exactly one.',
      insightFormal: 'Two ensembles share one ρ iff their chance-weighted kets are linked by a unitary table (Bergou; N&C Thm 2.6).',
      pitfalls: ['Treating the ensemble as part of the state: the same $\\rho$ hides every recipe equally well.'],
      play: [
        {
          id: 'q8-r-same',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which mixture equals ½I?',
          prompt: 'Which mixture equals $\\tfrac12I$?',
          options: [
            { text: '$\\tfrac12|{+y}\\rangle\\langle{+y}| + \\tfrac12|{-y}\\rangle\\langle{-y}|$', correct: true, why: 'Opposite poles average to the centre, for any axis.' },
            { text: '$\\tfrac12|0\\rangle\\langle0| + \\tfrac12|+\\rangle\\langle+|$', correct: false, why: 'That gives $\\mathbf r = (0.5, 0, 0.5)$, not the centre.' },
            { text: '$|0\\rangle\\langle0|$', correct: false, why: 'That is pure, on the surface.' },
            { text: '$\\tfrac34|0\\rangle\\langle0| + \\tfrac14|1\\rangle\\langle1|$', correct: false, why: 'That gives $r_z = 0.5$, off centre.' },
          ],
          hints: [{ text: 'Where is each recipe’s point?' }, { text: 'Opposite poles average to the centre.' }, { text: 'The y poles.' }],
          walkthrough: [{ text: 'The $|\\pm y\\rangle$ are opposite points, so their even mix is the centre.' }],
        },
        {
          id: 'q8-r-eig',
          kind: 'numeric',
          tier: 'core',
          title: 'An eigenvalue',
          prompt: 'What is the larger eigenvalue of $\\begin{pmatrix}3/4 & 1/4\\\\ 1/4 & 1/4\\end{pmatrix}$?',
          answer: V.q8ZXEigLarge,
          tolerance: 0.001,
          hints: [{ text: 'Trace 1, determinant $\\tfrac18$.' }, { text: '$\\lambda^2 - \\lambda + \\tfrac18 = 0$.' }, { text: '$\\lambda = \\tfrac12 \\pm \\tfrac{\\sqrt2}4$.' }],
          walkthrough: [{ text: '$(2 + \\sqrt2)/4 = 0.854$, the weight of $|u_+\\rangle$.' }],
        },
        {
          id: 'q8-r-conv',
          kind: 'numeric',
          tier: 'core',
          title: 'A point on the chord',
          prompt: 'Mix $\\tfrac14$ of $|0\\rangle\\langle0|$ with $\\tfrac34$ of $|+\\rangle\\langle+|$. What is $r_x$?',
          answer: V.q8ConvRx025,
          tolerance: 0.005,
          hints: [{ text: 'Arrows mix like the matrices.' }, { text: '$|0\\rangle$ has $r_x = 0$, $|+\\rangle$ has $r_x = 1$.' }, { text: '$\\tfrac14\\cdot0 + \\tfrac34\\cdot1$.' }],
          walkthrough: [{ text: '0.75; the point lies on the chord.' }],
        },
        {
          id: 'q8-r-trine',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The trine',
          prompt: 'Three states 120° apart on the x–z circle, each with weight $\\tfrac13$: how long is the mixture’s arrow?',
          answer: V.q8TrineRLen,
          tolerance: 0.005,
          hints: [{ text: 'Add three unit arrows at 120°.' }, { text: 'They close a triangle.' }, { text: 'The average is the centre.' }],
          walkthrough: [{ text: '0, so the trine is a third recipe for $\\tfrac12I$.' }],
        },
      ],
    },
  ],
}

export { claim, close, d }
