import type { Lecture } from '../schema'
import { Q9_REVIEW } from './Q9.review'
import { Q9_STORY, Q9_UNIT_CLAIMS_BY_ID } from './Q9.story'
import { BETA_RA, R12, V, claim, close, d } from './Q9.values'

// Physics 709, chapter Q9: "Parts of a whole: reduced states, entropy, Schmidt" (notes L7 pp. 37-40; Bergou
// §2.1, §2.5-2.7, pp. 16-28), in both tracks. Every number a learner sees is computed in Q9.values.ts, then asserted in
// keyed claims (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy,
// pipeline/claims_qc709/q9.py). Plan: docs/roles/proposals/P-Q9-story.md; rulings docs/roles/decisions/qc709-Q8Q9.md.
// Q9 owns the partial trace, rho_A, S(rho), the Schmidt form and rank, purification, the SVD (Formal), trace
// distance and fidelity. HW2 is submitted (homework-status.md), so its P2(d) and P7(e) items get full walkthroughs
// below. Unit 9.6 is Bergou-only (ruling 8): every beat there is phase 'books', with no [L] beat.

export const Q9: Lecture = {
  id: 'Q9',
  number: 9,
  title: 'Parts of a whole: reduced states, entropy, Schmidt',
  outcomes: [
    'Compute a reduced density matrix by tracing out a partner, block by block.',
    'Show that every Bell state leaves each qubit maximally mixed, and that GHZ with one qubit traced out is the box of Unit 8.1.',
    'Explain why the singlet and a coin-made anti-aligned pair look the same from each side but differ in their grids.',
    'Compute the entropy of a state from its eigenvalues: 0 for pure, 1 bit for a fair coin, log base 2 of the dimension at most.',
    'Write a pure pair in Schmidt form, read off its rank and weights, and see that both halves share their eigenvalues.',
    'Build a purification of a mixture, and relate two purifications by a gate on the partner.',
    'Compute the trace distance and the fidelity of two qubit states, and link them for pure states.',
  ],
  prerequisites: [
    'qc-density-matrix-station',
    'qc-trace-rule',
    'qc-mixed-states',
    'qc-bloch-ball-station',
    'qc-recipes',
    'qc-ghz',
    'qc-bell-basis-station',
    'qc-entanglement',
    'qc-operator-tensor-station',
    'qc-spectral',
    'qc-inner-product',
  ],
  symbols: {
    // q9-partial-trace
    A: 'q9-partial-trace:b1',
    B: 'q9-partial-trace:b1',
    O: 'q9-partial-trace:b1',
    '\\rho_A': 'q9-partial-trace:b1',
    '|0\\rangle': 'q9-partial-trace:b1',
    '|\\cdot\\rangle': 'q9-partial-trace:b1',
    '\\langle\\cdot\\rangle': 'q9-partial-trace:b1',
    Z_A: 'q9-partial-trace:b1',
    X_A: 'q9-partial-trace:b1',
    Z: 'q9-partial-trace:b1',
    '|+\\rangle': 'q9-partial-trace:b1',
    '\\rho': 'q9-partial-trace:b1',
    '\\otimes': 'q9-partial-trace:b1',
    '|a\\rangle': 'q9-partial-trace:b1',
    '|b\\rangle': 'q9-partial-trace:b1',
    '\\langle\\cdot|': 'q9-partial-trace:b1',
    '\\psi_1': 'q9-partial-trace:b1',
    '|\\psi_1\\rangle': 'q9-partial-trace:b1',
    I: 'q9-partial-trace:b1',
    '|00\\rangle': 'q9-partial-trace:b2',
    '|11\\rangle': 'q9-partial-trace:b2',
    a: 'q9-partial-trace:b2',
    "\\rho_ab,a'b": 'q9-partial-trace:b2',
    '\\Psi_2': 'q9-partial-trace:b2',
    '\\rho_00,11': 'q9-partial-trace:b2',
    '|01\\rangle': 'q9-partial-trace:b3',
    '|10\\rangle': 'q9-partial-trace:b3',
    '\\Psi': 'q9-partial-trace:b3',
    '\\beta_11': 'q9-partial-trace:b3',
    '|\\Psi^-\\rangle': 'q9-partial-trace:b3',
    '\\rho_00,00': 'q9-partial-trace:b3',
    '\\rho_01,01': 'q9-partial-trace:b3',
    '\\rho_00,10': 'q9-partial-trace:b3',
    '\\rho_01,11': 'q9-partial-trace:b3',
    '\\rho_10,10': 'q9-partial-trace:b3',
    '\\rho_11,11': 'q9-partial-trace:b3',
    r_A: 'q9-partial-trace:b3',
    T: 'q9-partial-trace:b3',
    I_3: 'q9-partial-trace:b3',
    '\\langle\\cdot|\\cdot\\rangle': 'q9-partial-trace:b4',
    '|1\\rangle': 'q9-partial-trace:b4',
    x: 'q9-partial-trace:b4',
    y: 'q9-partial-trace:b4',
    '\\beta_xy': 'q9-partial-trace:b4',
    '|\\beta_xy\\rangle': 'q9-partial-trace:b4',
    '|0,y\\rangle': 'q9-partial-trace:b4',
    '|1,1\\oplusy\\rangle': 'q9-partial-trace:b4',
    '\\oplus': 'q9-partial-trace:b4',
    'T_\\beta_xy': 'q9-partial-trace:b4',
    '|y\\rangle': 'q9-partial-trace:b4',
    '|1\\oplusy\\rangle': 'q9-partial-trace:b4',
    '|000\\rangle': 'q9-partial-trace:b5',
    '|111\\rangle': 'q9-partial-trace:b5',
    "|x\\,c\\rangle": 'q9-partial-trace:b5',
    '|x\\rangle': 'q9-partial-trace:b5',
    "|x'\\,c'\\rangle": 'q9-partial-trace:b5',
    "|x'\\rangle": 'q9-partial-trace:b5',
    "\\delta_cc'": 'q9-partial-trace:b5',
    T_zz: 'q9-partial-trace:b5',
    T_xx: 'q9-partial-trace:b5',
    T_yy: 'q9-partial-trace:b5',
    '\\rho_12': 'q9-partial-trace:b5',
    '|xc\\rangle': 'q9-partial-trace:b5',
    "|x'c'\\rangle": 'q9-partial-trace:b5',
    X: 'q9-partial-trace:b6',
    '\\beta_10': 'q9-partial-trace',
    '|0y\\rangle': 'q9-partial-trace',
    '|1\\bary\\rangle': 'q9-partial-trace',
    '\\bar y': 'q9-partial-trace',
    '|\\bary\\rangle': 'q9-partial-trace',
    '\\rho_1': 'q9-partial-trace',

    // q9-same-part
    '\\rho_c': 'q9-same-part:b1',
    X_B: 'q9-same-part:b2',
    T_c: 'q9-same-part:b2',
    'T_\\Psi^-': 'q9-same-part:b2',
    b: 'q9-same-part:b3',
    "\\rho_ab,a'b'": 'q9-same-part:b3',
    '|i_1\\rangle': 'q9-same-part:b3',
    '|i_2\\rangle': 'q9-same-part:b3',
    '|j_1\\rangle': 'q9-same-part:b3',
    '|j_2\\rangle': 'q9-same-part:b3',
    '\\delta_i_2j_2': 'q9-same-part:b3',
    'p_i_1i_2,j_1j_2': 'q9-same-part:b3',
    'p_i_1k,j_1k': 'q9-same-part:b3',
    '\\rho_B': 'q9-same-part',
    Z_B: 'q9-same-part',

    // q9-entropy
    S: 'q9-entropy:b1',
    '\\lambda': 'q9-entropy:b1',
    '\\lambda_i': 'q9-entropy:b1',
    d: 'q9-entropy:b2',
    I_4: 'q9-entropy:b2',
    h: 'q9-entropy:b3',
    r: 'q9-entropy:b3',
    '\\boldsymbol': 'q9-entropy:b3',
    '\\sigma': 'q9-entropy:b3',
    '\\lambda_\\pm': 'q9-entropy:b3',
    '\\lambda_+': 'q9-entropy:b3',
    '\\lambda_-': 'q9-entropy:b3',
    p: 'q9-entropy:b3',
    E: 'q9-entropy:b4',
    '|\\psi\\rangle': 'q9-entropy:b4',
    E_Z: 'q9-entropy',
    k_B: 'q9-entropy',
    '\\psi_AB': 'q9-entropy',

    // q9-schmidt
    P: 'q9-schmidt:b1',
    '\\tilde v_0': 'q9-schmidt:b1',
    '\\tilde v_1': 'q9-schmidt:b1',
    C: 'q9-schmidt:b1',
    '|\\tildev_0\\rangle': 'q9-schmidt:b1',
    '|\\tildev_1\\rangle': 'q9-schmidt:b1',
    '|u_i_1\\rangle': 'q9-schmidt:b1',
    '|\\tildev_i_1\\rangle': 'q9-schmidt:b1',
    '|v_i_2\\rangle': 'q9-schmidt:b1',
    c_i_1i_2: 'q9-schmidt:b1',
    '|\\tildev\\rangle': 'q9-schmidt:b1',
    '\\tilde v_i_1': 'q9-schmidt:b1',
    '|u_+\\rangle': 'q9-schmidt:b2',
    '|u_-\\rangle': 'q9-schmidt:b2',
    '|-\\rangle': 'q9-schmidt:b2',
    '|u_\\pm\\rangle': 'q9-schmidt:b2',
    '|w_i_1\\rangle': 'q9-schmidt:b2',
    '\\lambda_i_1': 'q9-schmidt:b2',
    "|\\tildev_i_1'\\rangle": 'q9-schmidt:b2',
    "|u_i_1'\\rangle": 'q9-schmidt:b2',
    "\\delta_i_1i_1'": 'q9-schmidt:b2',
    '|w_\\pm\\rangle': 'q9-schmidt:b2',
    N: 'q9-schmidt:b3',
    '|u\\rangle': 'q9-schmidt:b3',
    '|w\\rangle': 'q9-schmidt:b3',
    '\\Phi': 'q9-schmidt:b3',
    '\\dim': 'q9-schmidt:b3',
    H_A: 'q9-schmidt:b3',
    H_B: 'q9-schmidt:b3',
    r_B: 'q9-schmidt:b4',
    '|u_k\\rangle': 'q9-schmidt:b5',
    '|w_k\\rangle': 'q9-schmidt:b5',
    '\\lambda_k': 'q9-schmidt:b5',
    s_1: 'q9-schmidt:b5',
    s_2: 'q9-schmidt:b5',
    '\\dagger': 'q9-schmidt:b5',
    s: 'q9-schmidt:b5',
    U_B: 'q9-schmidt:b6',
    '\\alpha': 'q9-schmidt:b6',
    U_A: 'q9-schmidt:b6',

    // q9-purification
    '|v_k\\rangle': 'q9-purification',
    p_i: 'q9-purification:b1',
    '|\\Psi\\rangle': 'q9-purification:b1',
    '|\\psi_i\\rangle': 'q9-purification:b1',
    '|i\\rangle': 'q9-purification:b1',
    '|\\psi_j\\rangle': 'q9-purification:b1',
    '|j\\rangle': 'q9-purification:b1',
    '\\delta_ij': 'q9-purification:b1',
    '|P\\rangle': 'q9-purification:b1',
    H: 'q9-purification:b2',
    "|\\Psi'\\rangle": 'q9-purification:b2',
    I_A: 'q9-purification:b2',
    '|\\Psi_\\rmeig\\rangle': 'q9-purification:b2',
    'p_+': 'q9-purification:b3',
    'p_-': 'q9-purification:b3',

    // q9-distance
    D: 'q9-distance:b1',
    '\\Pi': 'q9-distance:b1',
    '\\rho_0': 'q9-distance:b1',
    '\\rho_+': 'q9-distance:b1',
    '\\rho_2': 'q9-distance:b1',
    r_1: 'q9-distance:b2',
    r_2: 'q9-distance:b2',
    F: 'q9-distance:b3',
    '|\\psi_2\\rangle': 'q9-distance:b3',
    '|\\psi_1^\\perp\\rangle': 'q9-distance:b4',
  },
  symbolsFormal: {
    '\\Phi_-': 'q9-partial-trace:b3',
    i_1: 'q9-same-part:b3',
    U: 'q9-schmidt:b5',
    V: 'q9-schmidt:b5',
    's_k': 'q9-schmidt:b5',
  },
  units: [
    {
      id: 'q9-partial-trace',
      story: Q9_STORY['q9-partial-trace'],
      review: Q9_REVIEW['q9-partial-trace'],
      claims: Q9_UNIT_CLAIMS_BY_ID['q9-partial-trace'],
      title: 'Looking at one part: the partial trace',
      question: 'What state does one qubit of a pair have on its own?',
      lecture: { pages: 'notes L7 pp. 38–39; HW2 P2(d), P7(e)', summary: "Adding over one qubit's basis states leaves the other's reduced density matrix, $\\rho_A = \\mathrm{Tr}_B\\,\\rho$." },
      books: [{ source: 'bergou', where: '§2.1 pp. 16–17, Eqs. 2.3–2.5', adds: 'the ensemble-trace derivation of the reduced density matrix, before the worked example of Eqs. 2.8–2.10.' }],
      visual: { kind: 'sg-lab', props: { source: 'oven', axes: ['x'], editable: true, predict: true, seed: 709 }, tryThis: ['Fire 100 along x, then along z: always close to 50/50.'] },
      clues: [],
      insight: "A's own state is $\\rho_A = \\mathrm{Tr}_B\\,\\rho$: every Bell state and GHZ itself leave it $\\tfrac12I$, no matter how entangled the whole pair is.",
      insightFormal: '$\\langle O\\otimes I\\rangle = \\mathrm{Tr}(\\rho_AO)$ for every operator O on A alone; local statistics never see a pair\'s entanglement.',
      pitfalls: ["Reading an off-block coherence as part of $\\rho_A$: only entries whose B labels agree survive the partial trace."],
      play: [
        {
          id: 'q9-p-singlet',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The singlet, traced',
          prompt: 'For the singlet, what is $(\\rho_A)_{00}$?',
          answer: V.q9SingRA00,
          tolerance: 0.005,
          hints: [{ text: 'Trace the top-left block.' }, { text: 'Its diagonal is $\\rho_{00,00}$ and $\\rho_{01,01}$.' }, { text: '0 and ½.' }],
          walkthrough: [{ text: '0.5.' }],
        },
        {
          id: 'q9-p-psi2',
          kind: 'numeric',
          tier: 'core',
          title: 'A coherence that drops out',
          prompt: 'For $(\\sqrt3|00\\rangle + |11\\rangle)/2$, what is $(\\rho_A)_{01}$?',
          answer: V.q9Psi2RA01,
          tolerance: 0.005,
          hints: [{ text: 'Trace the top-right block.' }, { text: 'Its diagonal entries are $\\rho_{00,10}$ and $\\rho_{01,11}$.' }, { text: 'Both are 0; the 0.433 lies off that diagonal.' }],
          walkthrough: [{ text: '0, so A has no coherence.' }],
        },
        {
          id: 'q9-p-p2d',
          kind: 'numeric',
          tier: 'core',
          title: 'HW2 P2(d): a Bell state, traced',
          prompt: 'What is $(\\rho_A)_{00}$ for $\\beta_{10}$?',
          answer: BETA_RA[2][0][0].re,
          tolerance: 0.005,
          hints: [{ text: '$\\beta_{10} = (|00\\rangle - |11\\rangle)/\\sqrt2$.' }, { text: 'Trace out qubit 2.' }, { text: 'Only $|00\\rangle\\langle00|$ feeds $(\\rho_A)_{00}$.' }],
          walkthrough: [
            {
              text:
                "$|\\beta_{xy}\\rangle\\langle\\beta_{xy}| = \\tfrac12\\big(|0y\\rangle\\langle0y| + |1\\bar y\\rangle\\langle1\\bar y| + (-1)^x(|0y\\rangle\\langle1\\bar y| + |1\\bar y\\rangle\\langle0y|)\\big)$ with $\\bar y = 1\\oplus y$. Tracing qubit 2 keeps the first two terms and kills the cross terms, since $\\langle\\bar y|y\\rangle = 0$. So $\\rho_1 = \\tfrac12I$ for all four: no measurement on qubit 1 alone can tell them apart. The Bell measurement can, because it acts on both qubits and reads the parities $XX$ and $ZZ$, which are correlations.",
            },
          ],
        },
        {
          id: 'q9-p-p7e',
          kind: 'numeric',
          tier: 'core',
          title: 'HW2 P7(e): GHZ with one qubit traced out',
          prompt: 'For $\\rho_{12} = \\mathrm{Tr}_3|\\mathrm{GHZ}\\rangle\\langle\\mathrm{GHZ}|$, what is the entry in row 00, column 11?',
          answer: R12[0][3].re,
          tolerance: 0.005,
          hints: [{ text: 'Which terms of $|\\mathrm{GHZ}\\rangle\\langle\\mathrm{GHZ}|$ could feed it?' }, { text: '$|000\\rangle\\langle111|$.' }, { text: 'Its qubit-3 labels differ.' }],
          walkthrough: [
            {
              text:
                "$\\rho_{12} = \\tfrac12(|00\\rangle\\langle00| + |11\\rangle\\langle11|)$: the corner terms die because qubit 3's labels differ. The remaining pair is a mixture of the products $|00\\rangle$ and $|11\\rangle$, so it is not entangled: losing one qubit destroys all of GHZ's entanglement, which makes GHZ fragile.",
            },
          ],
        },
        {
          id: 'q9-p-purity',
          kind: 'numeric',
          tier: 'stretch',
          title: "A's purity",
          prompt: 'What is the purity of $\\rho_A$ for $(\\sqrt3|00\\rangle + |11\\rangle)/2$?',
          answer: V.q9Psi2Pur,
          tolerance: 0.005,
          hints: [{ text: '$\\rho_A = \\mathrm{diag}(0.75, 0.25)$.' }, { text: 'Square the entries.' }, { text: 'Add.' }],
          walkthrough: [{ text: '$0.5625 + 0.0625 = 0.625$.' }],
        },
      ],
    },
    {
      id: 'q9-same-part',
      story: Q9_STORY['q9-same-part'],
      review: Q9_REVIEW['q9-same-part'],
      claims: Q9_UNIT_CLAIMS_BY_ID['q9-same-part'],
      title: 'Same part, different whole',
      question: 'Can two different pairs look identical from either side?',
      lecture: { pages: 'notes L7 p. 39, Eq. 2.22', summary: "Two very different two-qubit states can share the same $\\rho_A$ and $\\rho_B$; the difference hides in the correlations." },
      books: [{ source: 'bergou', where: '§2.1 pp. 16–17, Eqs. 2.8–2.10', adds: 'the general partial-trace formula written index by index, with a worked example (Eq. 2.9\'s Tr read as $\\mathrm{Tr}_B$, erratum B2).' }],
      visual: { kind: 'deposit-stats', props: { state: '+x', axis: 'z', seed: 709 }, tryThis: ['Fire 100: about half each way, whichever pair the qubit came from.'] },
      clues: [],
      insight: "Same $\\rho_A$, same $\\rho_B$, different pair: the singlet and a classical coin toss agree on every one-qubit reading.",
      insightFormal: 'Reduced states underdetermine the whole; the difference lives entirely in the correlations $T$, which only a joint reading sees.',
      pitfalls: ['Assuming matching reduced states force a matching whole: the correlations carry the rest of the information.'],
      play: [
        {
          id: 'q9-s-zz',
          kind: 'numeric',
          tier: 'warm-up',
          title: "The coin pair's zz",
          prompt: 'For the coin pair, what is $\\langle Z_AZ_B\\rangle$?',
          answer: V.q9CoinZZ,
          tolerance: 0.005,
          hints: [{ text: 'The members are $|01\\rangle$ and $|10\\rangle$.' }, { text: 'The bits always differ.' }, { text: 'Parity −1.' }],
          walkthrough: [{ text: '−1 every time.' }],
        },
        {
          id: 'q9-s-xx',
          kind: 'numeric',
          tier: 'core',
          title: "The singlet's xx",
          prompt: 'For the singlet, what is $\\langle X_AX_B\\rangle$?',
          answer: V.q9SingXX,
          tolerance: 0.005,
          hints: [{ text: "The singlet's grid." }, { text: 'All three diagonal cells.' }, { text: '−1.' }],
          walkthrough: [{ text: '−1; the singlet is anti-aligned along every axis.' }],
        },
        {
          id: 'q9-s-which',
          kind: 'choice',
          tier: 'core',
          title: 'Which reading tells them apart?',
          prompt: 'Which reading tells the singlet from the coin pair?',
          options: [
            { text: 'Y on both qubits, multiplied', correct: true, why: 'Right: the coin pair gives 0, the singlet gives −1.' },
            { text: 'Z on both qubits, multiplied', correct: false, why: 'Both give −1: the $zz$ cell agrees.' },
            { text: 'Z on A alone', correct: false, why: 'Single-qubit z readings look the same in both.' },
            { text: 'X on B alone', correct: false, why: 'Single-qubit x readings look the same in both.' },
          ],
          hints: [{ text: 'Single qubits look alike.' }, { text: '$zz$ agrees.' }, { text: 'Try $yy$.' }],
          walkthrough: [{ text: '$yy$ is −1 against 0.' }],
        },
        {
          id: 'q9-s-purity',
          kind: 'numeric',
          tier: 'stretch',
          title: "The coin pair's whole purity",
          prompt: 'What is the purity of the coin pair\'s whole $\\rho$?',
          answer: V.q9CoinPur,
          tolerance: 0.005,
          hints: [{ text: '$\\rho$ is diagonal.' }, { text: 'Two entries of ½.' }, { text: '$\\tfrac14 + \\tfrac14$.' }],
          walkthrough: [{ text: '0.5, while the singlet\'s whole state has purity 1.' }],
        },
      ],
    },
    {
      id: 'q9-entropy',
      story: Q9_STORY['q9-entropy'],
      review: Q9_REVIEW['q9-entropy'],
      claims: Q9_UNIT_CLAIMS_BY_ID['q9-entropy'],
      title: 'Entropy: how mixed is a state?',
      question: 'How many bits are unknown in a mixed state, and in one half of a pure pair?',
      lecture: { pages: 'notes L7 p. 39, Eq. 2.23', summary: "The von Neumann entropy $S(\\rho) = -\\sum\\lambda\\log_2\\lambda$ counts the bits unknown in a state, from 0 (pure) to $\\log_2d$ (maximally mixed)." },
      books: [{ source: 'bergou', where: '§3.7.1 p. 47, Eq. 3.41', adds: 'the entanglement-entropy identity $S(\\rho_A) = S(\\rho_B)$ for a pure pair.' }],
      visual: { kind: 'sg-lab', props: { source: 'oven', axes: ['z'], editable: false, predict: true, seed: 709 }, tryThis: ['Predict, then fire 20: no strategy beats a guess.'] },
      clues: [],
      insight: 'S counts the bits unknown in $\\rho$ from its eigenvalues; for a pure pair, the entropy of one half measures how entangled it is.',
      insightFormal: '$0 \\le S(\\rho) \\le \\log_2d$; for one qubit S depends only on $|\\mathbf r|$, and $E(\\psi_{AB}) = S(\\rho_A) = S(\\rho_B)$.',
      pitfalls: ["Computing S from a recipe's weights instead of $\\rho$'s eigenvalues: they agree only when the recipe's members are orthogonal."],
      play: [
        {
          id: 'q9-e-half',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A fair coin',
          prompt: 'What is $S(\\tfrac12I)$, in bits?',
          answer: V.q9SHalf,
          tolerance: 0.005,
          unit: 'bit',
          hints: [{ text: 'Two eigenvalues of ½.' }, { text: '$-\\tfrac12\\log_2\\tfrac12 = \\tfrac12$.' }, { text: 'Twice.' }],
          walkthrough: [{ text: '1 bit.' }],
        },
        {
          id: 'q9-e-r05',
          kind: 'numeric',
          tier: 'core',
          title: 'Entropy at half length',
          prompt: "A qubit's arrow has length 0.5. What is S?",
          answer: V.q9S05,
          tolerance: 0.005,
          unit: 'bit',
          hints: [{ text: 'Eigenvalues $(1 \\pm |\\mathbf r|)/2$.' }, { text: '0.75 and 0.25.' }, { text: '$-0.75\\log_20.75 - 0.25\\log_20.25$.' }],
          walkthrough: [{ text: '0.811 bit.' }],
        },
        {
          id: 'q9-e-psi2',
          kind: 'numeric',
          tier: 'core',
          title: 'An entanglement entropy',
          prompt: 'What is the entanglement entropy of $(\\sqrt3|00\\rangle + |11\\rangle)/2$?',
          answer: V.q9EPsi2,
          tolerance: 0.005,
          unit: 'bit',
          hints: [{ text: 'Find $\\rho_A$.' }, { text: '$\\mathrm{diag}(0.75, 0.25)$.' }, { text: 'Its entropy.' }],
          walkthrough: [{ text: '0.811, the same number as the previous challenge: A\'s arrow has length 0.5.' }],
        },
        {
          id: 'q9-e-thermal',
          kind: 'numeric',
          tier: 'stretch',
          title: "Unit 8.4's thermal box",
          prompt: 'Unit 8.4\'s thermal box, with $E_Z = 2k_BT$: what is S?',
          answer: V.q9SThermal,
          tolerance: 0.005,
          unit: 'bit',
          hints: [{ text: '$\\rho$ is diagonal.' }, { text: 'The chances are 0.881 and 0.119.' }, { text: 'Use h.' }],
          walkthrough: [{ text: '0.527 bit.' }],
        },
      ],
    },
    {
      id: 'q9-schmidt',
      story: Q9_STORY['q9-schmidt'],
      review: Q9_REVIEW['q9-schmidt'],
      claims: Q9_UNIT_CLAIMS_BY_ID['q9-schmidt'],
      title: 'The Schmidt form of a pair',
      question: 'Is there a best way to write a pure pair, one term per shared chance?',
      lecture: { pages: 'notes L7 p. 40, Eqs. 2.24–2.28', summary: "Grouping a pure pair's terms by $\\rho_A$'s own eigenbasis gives one orthogonal term per shared eigenvalue: the Schmidt form." },
      books: [{ source: 'nc', where: 'Theorem 2.7, p. 109', adds: 'the Schmidt decomposition stated as a theorem, via the singular value decomposition of the coefficient matrix.' }],
      visual: { kind: 'bloch', props: { theta: 45, phi: 0, editable: true, measure: 'x' }, tryThis: ["Read x at θ = 45°: the average is 0.707, A's arrow direction in P; A itself, at length 0.707, gives 0.5."] },
      clues: [],
      insight: 'Grouping by $\\rho_A$\'s own eigenbasis makes the partners orthogonal: the Schmidt form, with weights $\\sqrt\\lambda$ and rank 1 exactly for a product.',
      insightFormal: '$|\\psi\\rangle = \\sum_k\\sqrt{\\lambda_k}|u_k\\rangle|w_k\\rangle$, the SVD of the coefficient matrix C; $\\rho_A$ and $\\rho_B$ share their nonzero eigenvalues.',
      pitfalls: ["Taking the 0/1-basis rows of the amplitude grid as the Schmidt terms: they overlap unless the basis is $\\rho_A$'s own eigenbasis."],
      play: [
        {
          id: 'q9-sc-rank',
          kind: 'numeric',
          tier: 'warm-up',
          title: "A product's rank",
          prompt: 'What is the Schmidt rank of $\\psi_1\\otimes|+\\rangle$?',
          answer: V.q9RankProd,
          tolerance: 0.001,
          hints: [{ text: 'It is a product.' }, { text: 'One term.' }, { text: 'Rank 1.' }],
          walkthrough: [{ text: '1.' }],
        },
        {
          id: 'q9-sc-weight',
          kind: 'numeric',
          tier: 'core',
          title: "P's larger Schmidt weight",
          prompt: "What is P's larger Schmidt weight?",
          answer: V.q9PSchmidtLarge,
          tolerance: 0.005,
          hints: [{ text: '$\\rho_A$ is Unit 8.4\'s mixture.' }, { text: 'Its larger eigenvalue is 0.854.' }, { text: 'Take the square root.' }],
          walkthrough: [{ text: '$\\sqrt{0.854} = 0.924$.' }],
        },
        {
          id: 'q9-sc-overlap',
          kind: 'numeric',
          tier: 'core',
          title: "The 0/1 rows' overlap",
          prompt: "Group P by A's 0/1 basis. What is $\\langle\\tilde v_0|\\tilde v_1\\rangle$?",
          answer: V.q9PVtOverlap,
          tolerance: 0.005,
          hints: [{ text: '$\\tilde v_0 = 0.707|0\\rangle + 0.5|1\\rangle$.' }, { text: '$\\tilde v_1 = 0.5|1\\rangle$.' }, { text: 'Only the $|1\\rangle$ parts meet.' }],
          walkthrough: [{ text: "$0.5\\times0.5 = 0.25$: the 0/1 basis is not A's Schmidt basis." }],
        },
        {
          id: 'q9-sc-rb',
          kind: 'numeric',
          tier: 'stretch',
          title: "B's arrow length",
          prompt: "How long is B's arrow in P?",
          answer: V.q9RBLen,
          tolerance: 0.005,
          hints: [{ text: '$\\rho_B$ has A\'s eigenvalues.' }, { text: '$\\lambda_+ - \\lambda_- = |\\mathbf r|$.' }, { text: '$0.854 - 0.146$.' }],
          walkthrough: [{ text: '0.707, the same as A\'s.' }],
        },
      ],
    },
    {
      id: 'q9-purification',
      story: Q9_STORY['q9-purification'],
      review: Q9_REVIEW['q9-purification'],
      claims: Q9_UNIT_CLAIMS_BY_ID['q9-purification'],
      title: 'Every mixture is part of something pure',
      question: 'Can every mixed state be one half of a pure pair?',
      lecture: { pages: 'notes L7 p. 40', summary: 'Tagging each member of a mixture with an orthogonal partner state always builds a pure pair that reduces back to it: a purification.' },
      books: [{ source: 'bergou', where: '§2.6 pp. 25–26, Eqs. 2.53–2.56', adds: "the purification construction and the unitary-freedom link between two purifications (Eq. 2.56, corrected: $U_B|v_k\\rangle$ for the printed $U_B|u_k\\rangle$, erratum B5)." }],
      visual: { kind: 'bloch', props: { theta: 45, phi: 0, editable: false, measure: 'z' }, tryThis: ['Read z: 0.854 of the readings give 0.'] },
      clues: [],
      insight: 'Always: tag each member of a mixture with its own orthogonal partner state, and the pure pair reduces back to the mixture.',
      insightFormal: '$|\\Psi\\rangle_{AB} = \\sum_i\\sqrt{p_i}|\\psi_i\\rangle_A|i\\rangle_B$ purifies $\\rho_A$; any two purifications with the same partner differ by $I_A\\otimes U_B$.',
      pitfalls: ['Dropping the square root on the weights: $\\sum_ip_i|\\psi_i\\rangle|i\\rangle$ is not [[qc-normalized|normalized]] and traces to the wrong $\\rho$.'],
      play: [
        {
          id: 'q9-pu-which',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which state purifies ½I?',
          prompt: 'Which pure state purifies $\\tfrac12I$?',
          options: [
            { text: '$\\Phi^+$', correct: true, why: 'Right: tracing out B leaves $\\tfrac12I$.' },
            { text: '$|00\\rangle$', correct: false, why: 'A product leaves A pure, not $\\tfrac12I$.' },
            { text: '$|0\\rangle|+\\rangle$', correct: false, why: 'Also a product: A stays pure.' },
            { text: '$(\\sqrt3|00\\rangle + |11\\rangle)/2$', correct: false, why: 'That leaves $\\mathrm{diag}(0.75, 0.25)$, not $\\tfrac12I$.' },
          ],
          hints: [{ text: 'Trace out B for each.' }, { text: 'Products leave A pure.' }, { text: 'A Bell state leaves $\\tfrac12I$.' }],
          walkthrough: [{ text: '$\\Phi^+$.' }],
        },
        {
          id: 'q9-pu-x',
          kind: 'numeric',
          tier: 'core',
          title: 'Reading B along x',
          prompt: 'Read qubit B of P along x. What is the chance of +?',
          answer: V.q9SteerX0,
          tolerance: 0.005,
          hints: [{ text: "P's Schmidt form." }, { text: "B's Schmidt states are $|{\\pm}\\rangle$." }, { text: 'The chance is $\\lambda_+$.' }],
          walkthrough: [{ text: '0.854, and A is left in $|u_+\\rangle$.' }],
        },
        {
          id: 'q9-pu-z',
          kind: 'numeric',
          tier: 'core',
          title: 'Reading B along z',
          prompt: 'Read qubit B of P along z. What is the chance of 0?',
          answer: V.q9SteerZ0,
          tolerance: 0.005,
          hints: [{ text: "Write P with B's 0/1 states." }, { text: '$\\tfrac1{\\sqrt2}(|0\\rangle|0\\rangle + |{+}\\rangle|1\\rangle)$.' }, { text: '$|1/\\sqrt2|^2$.' }],
          walkthrough: [{ text: '0.5, leaving A in $|0\\rangle$.' }],
        },
        {
          id: 'q9-pu-ent',
          kind: 'numeric',
          tier: 'stretch',
          title: "Every purification's entanglement",
          prompt: "Every purification of Unit 8.4's mixture is entangled. What is its entanglement entropy?",
          answer: V.q9EP,
          tolerance: 0.005,
          hints: [{ text: '$E = S(\\rho_A)$.' }, { text: '$\\rho_A$ is the mixture.' }, { text: 'Unit 9.3.' }],
          walkthrough: [{ text: '0.601 bit, for any purification, since all have the same $\\rho_A$.' }],
        },
      ],
    },
    {
      id: 'q9-distance',
      story: Q9_STORY['q9-distance'],
      review: Q9_REVIEW['q9-distance'],
      claims: Q9_UNIT_CLAIMS_BY_ID['q9-distance'],
      title: 'How far apart are two states?',
      question: 'How well can one reading tell two states apart, and how do we measure their overlap?',
      lecture: { pages: 'Bergou §2.7 pp. 26–28, Eqs. 2.57–2.62', summary: 'This unit is Bergou-only (no 709 notes cover it): the trace distance and the fidelity, and how they relate for pure states.' },
      books: [{ source: 'bergou', where: '§2.7 pp. 26–28, Eqs. 2.57–2.62', adds: "the trace-norm definition of trace distance and the Fuchs–van de Graaf bounds linking it to fidelity (p. 26's trace-norm recipe, erratum B4)." }],
      visual: { kind: 'projector', props: { state: 45, basis: 0, editableBasis: true }, tryThis: ['Read the shadow at 45°: 0.707.', 'Turn the basis to 45°: one shadow is 1 (F = 1), the other 0 (F = 0).'] },
      clues: [],
      insight: 'D is half the sum of the eigenvalue sizes of $\\rho_1 - \\rho_2$; F is how much two states overlap; for pure states $D = \\sqrt{1 - F^2}$.',
      insightFormal: '$D(\\rho_1, \\rho_2) = \\tfrac12\\|\\rho_1 - \\rho_2\\|_1 = \\max_\\Pi\\mathrm{Tr}\\,\\Pi(\\rho_1 - \\rho_2)$; for mixed states $1 - F \\le D \\le \\sqrt{1 - F^2}$.',
      pitfalls: ['Mixing the two fidelity conventions: Bergou and N&C use the root; some texts square it.'],
      play: [
        {
          id: 'q9-d-0p',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'D between $|0\\rangle$ and $|+\\rangle$',
          prompt: 'What is D between $|0\\rangle$ and $|+\\rangle$?',
          answer: V.q9D0P,
          tolerance: 0.005,
          hints: [{ text: 'Half the straight distance in the ball.' }, { text: 'The points are $(0, 0, 1)$ and $(1, 0, 0)$.' }, { text: '$\\sqrt2/2$.' }],
          walkthrough: [{ text: '0.707.' }],
        },
        {
          id: 'q9-d-mix',
          kind: 'numeric',
          tier: 'core',
          title: "Unit 8.4's mixture from ½I",
          prompt: "What is D between Unit 8.4's mixture and $\\tfrac12I$?",
          answer: V.q9DZXHalf,
          tolerance: 0.005,
          hints: [{ text: '$\\tfrac12I$ is the centre.' }, { text: "The mixture's arrow has length 0.707." }, { text: 'Halve it.' }],
          walkthrough: [{ text: '0.354.' }],
        },
        {
          id: 'q9-d-fid',
          kind: 'numeric',
          tier: 'core',
          title: 'F between a pure state and ½I',
          prompt: 'What is F between $|0\\rangle$ and $\\tfrac12I$?',
          answer: V.q9F0Half,
          tolerance: 0.005,
          hints: [{ text: 'One state is pure.' }, { text: '$F = \\sqrt{\\langle0|\\rho|0\\rangle}$.' }, { text: '$\\sqrt{1/2}$.' }],
          walkthrough: [{ text: '0.707.' }],
        },
        {
          id: 'q9-d-singcoin',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The singlet from the coin pair',
          prompt: 'What is D between the singlet and the coin pair of Unit 9.2?',
          answer: V.q9DSingCoin,
          tolerance: 0.005,
          hints: [{ text: 'Subtract: only the corners of −½ remain.' }, { text: 'Their eigenvalues are ±½.' }, { text: 'Half the sum of sizes.' }],
          walkthrough: [{ text: `D = 0.5 for the wholes, while their reduced states are ${d(V.q9DSingCoinA, 0)} apart: the difference is all correlation.` }],
        },
      ],
    },
  ],
}

export { claim, close }
