/**
 * Claim ledger (W-L1 §6.1; owner P).
 *  1. Every engine value in L1.values.ts matches its numpy twin in physics/__fixtures__/claims.json
 *     (pipeline/make_claim_fixtures.py: eigh kets, Lüders projectors, bisection, Malus's law).
 *  2. Every claim is keyed (`key · text`) and its key has a numpy value.
 *  3. Every decimal, fraction or percentage a student reads in a story beat (text, caption, reveal) or a
 *     review card equals, to its shown precision, the numpy value of a claim of that beat or its unit.
 *     Angles (45°, 60°) are inputs, not results, and are skipped, as are section/page numbers.
 */
import { describe, expect, it } from 'vitest'
import fixture from '../physics/__fixtures__/claims.json'
import { LECTURES } from './index'
import { claimKey } from './claimKit'
import { COURSES, courseOfId, type Track } from './courses'
import { Q0, V as Q0_VALUES } from './qc709/__fixtures__/demoChapter'
import { QC_CHAPTERS } from './qc709/index'
import { derivationSteps, pickReview, pickTrack } from './track'
import { readingOrder } from './walk'
import { ALL_VALUES as V } from './values'
import type { Claim, Lecture } from './schema'

/** Every chapter with each track of its course (448: Ground-up only; 709: both). */
const TRACKED: [string, Lecture, Track][] = [...LECTURES, ...QC_CHAPTERS].flatMap((l) =>
  COURSES[courseOfId(l.id)].tracks.map((t): [string, Lecture, Track] => [`${l.id} ${t}`, l, t]),
)

/**
 * The DEV demo chapter's two values have closed forms, so their twins are written out here rather than generated by
 * numpy: P(0) on the equator is exactly ½ and each amplitude of |+x⟩ is exactly 1/√2. The fixture is not course
 * content and joins no course's value table (content/values.ts).
 */
const DEMO_TWINS: Readonly<Record<string, number>> = { q0Half: 1 / 2, q0Amp: 1 / Math.sqrt(2), q0SumAbs: 2 * Math.sqrt(5), q0WAbs: Math.sqrt(5) }

/**
 * The numpy twins: 448's one file, plus one file per written 709 chapter (pipeline/claims_qc709/q{n}.py →
 * physics/__fixtures__/claims-qc709/q{n}.json), merged by glob so a new chapter touches no shared file.
 */
const QC_TWINS = import.meta.glob<{ values: Record<string, number> }>('../physics/__fixtures__/claims-qc709/*.json', { eager: true, import: 'default' })
const NUMPY: Readonly<Record<string, number>> = Object.assign({}, fixture.values, ...Object.values(QC_TWINS).map((m) => m.values))

/* ---------------------------------------------------------------------------------------------- */
/* Displayed numbers                                                                               */
/* ---------------------------------------------------------------------------------------------- */

export interface Shown {
  raw: string
  value: number
  /** Half a unit of the last shown digit (exact for fractions). */
  tol: number
}

const GLYPHS: Record<string, number> = { '½': 1 / 2, '¼': 1 / 4, '¾': 3 / 4, '⅛': 1 / 8, '⅜': 3 / 8, '⅓': 1 / 3, '⅔': 2 / 3 }
const EXACT = 1e-9

/** Decimals, fractions and percentages in a rich string (TeX included), in order of the rules below. */
export function shownNumbers(text: string): Shown[] {
  const out: Shown[] = []
  let s = text
  const eat = (re: RegExp, f: (m: RegExpMatchArray) => Shown | null) => {
    s = s.replace(re, (...args: unknown[]) => {
      const m = args.slice(0, -2) as unknown as RegExpMatchArray
      const r = f(m)
      if (r) out.push(r)
      return ' '
    })
  }
  // inputs and references, not results (a bridge `<<id|shown>>` names a place in Spin Lab, never a result)
  eat(/<<[^>|]+\|[^>]+>>/g, () => null)
  eat(/\d+(?:\.\d+)?\s*(?:°|\^\\circ|\^\{\\circ\})/g, () => null)
  eat(/(?:§|\bpp?\.\s?|\bFig\.\s?|\beqs?\.\s?|\bExps?\.\s?|\bProblem\s|\bDefinition\s|\bLecture\s|\bUnits?\s|\bMIT\s|\bL)\d+(?:[.–-]\d+)*/g, () => null)
  // the name of the spin ("spin ½", "spin-½") is not a result
  eat(/\bspin[- ](?:½|\\tfrac\{?1\}?\{?2\}?)/g, () => null)
  // exact forms
  eat(/\\[td]?frac\{?(\d+)\}?\{?(\d+)\}?/g, (m) => ({ raw: m[0], value: Number(m[1]) / Number(m[2]), tol: EXACT }))
  eat(/[½¼¾⅛⅜⅓⅔]/g, (m) => ({ raw: m[0], value: GLYPHS[m[0]], tol: EXACT }))
  eat(/\b50\/50\b/g, (m) => ({ raw: m[0], value: 0.5, tol: EXACT }))
  eat(/(?<![\d.])(\d+)\s*\/\s*(\d+)(?![\d.])/g, (m) => ({ raw: m[0], value: Number(m[1]) / Number(m[2]), tol: EXACT }))
  // rounded forms
  eat(/(?<![\d.])(\d+(?:\.(\d+))?)\s*\\?%/g, (m) => ({ raw: m[0], value: Number(m[1]) / 100, tol: 0.5 * 10 ** -((m[2]?.length ?? 0) + 2) + 1e-12 }))
  eat(/(?<![\d.])(\d+)\.(\d+)(?![\d.])/g, (m) => ({ raw: m[0], value: Number(`${m[1]}.${m[2]}`), tol: 0.5 * 10 ** -m[2].length + 1e-12 }))
  return out
}

/* ---------------------------------------------------------------------------------------------- */
/* Sites and the claims in scope                                                                   */
/* ---------------------------------------------------------------------------------------------- */

interface Scoped {
  where: string
  text: string
  claims: Claim[]
}

/**
 * The sites a track shows, each with the claims in its scope (the beat's, its reveal's and its unit's; a derivation
 * line adds its own). Per track (W-709-platform §B "Lints"): Formal reads the Formal texts and derivation, over the
 * same claims, so a number must be backed in both tracks.
 */
function scopedSites(l: Lecture, track: Track = 'ground'): Scoped[] {
  const out: Scoped[] = []
  for (const u of l.units) {
    const unitClaims = [...(u.claims ?? []), ...(u.review?.claims ?? [])]
    for (const raw of u.story ?? []) {
      const b = pickTrack(raw, track)
      const claims = [...(b.claims ?? []), ...(b.reveal?.claims ?? []), ...unitClaims]
      for (const [field, text] of [
        ['text', b.text],
        ['caption', b.caption],
        ['reveal.text', b.reveal?.text],
        ['reveal.caption', b.reveal?.caption],
      ] as const)
        if (text) out.push({ where: `${b.id} ${field}`, text, claims })
      if (b.derivation) out.push({ where: `${b.id}.derivation result`, text: `$${b.derivation.result}$`, claims })
      derivationSteps(b, track).forEach((s, i) => {
        const stepClaims = [...(s.claims ?? []), ...claims]
        out.push({ where: `${b.id}.derivation.${track}[${i}] why`, text: s.why, claims: stepClaims })
        out.push({ where: `${b.id}.derivation.${track}[${i}] tex`, text: `$${s.tex}$`, claims: stepClaims })
      })
    }
    if (u.review) {
      const card = pickReview(u.review, track)
      for (const [i, p] of card.points.entries()) out.push({ where: `${u.id}.review.points[${i}]`, text: p, claims: unitClaims })
      out.push({ where: `${u.id}.review.equations`, text: card.equations, claims: unitClaims })
      out.push({ where: `${u.id}.review.trap`, text: card.trap, claims: unitClaims })
    }
  }
  return out
}

function allClaims(l: Lecture): { where: string; claim: Claim }[] {
  return l.units.flatMap((u) => [
    ...(u.claims ?? []).map((claim) => ({ where: u.id, claim })),
    ...(u.review?.claims ?? []).map((claim) => ({ where: `${u.id}.review`, claim })),
    ...(u.story ?? []).flatMap((b) => [
      ...[...(b.claims ?? []), ...(b.reveal?.claims ?? [])].map((claim) => ({ where: b.id, claim })),
      ...(['ground', 'formal'] as const).flatMap((t) => derivationSteps(b, t).flatMap((s, i) => (s.claims ?? []).map((claim) => ({ where: `${b.id}.derivation.${t}[${i}]`, claim })))),
    ]),
  ])
}

/** Displayed numbers that no claim in scope backs, as "where: raw". */
function unbacked(l: Lecture, numpy: Readonly<Record<string, number>> = NUMPY, track: Track = 'ground'): string[] {
  const bad: string[] = []
  for (const site of scopedSites(l, track)) {
    const values = site.claims.map((c) => numpy[claimKey(c) ?? ''] ?? Number.NaN)
    for (const n of shownNumbers(site.text)) if (!values.some((v) => Math.abs(v - n.value) <= n.tol)) bad.push(`${site.where}: ${n.raw}`)
  }
  return bad
}

/* ---------------------------------------------------------------------------------------------- */
/* Tests                                                                                           */
/* ---------------------------------------------------------------------------------------------- */

describe('claims.json (numpy) ↔ engine (every lecture\'s values, content/values.ts)', () => {
  it('every engine value has a numpy twin, and no numpy key is stale', () => {
    expect(Object.keys(NUMPY).sort()).toEqual(Object.keys(V).sort())
  })
  it.each(Object.entries(V))('%s agrees with numpy', (key, value) => {
    expect(Math.abs(value - NUMPY[key]), `${key}: engine ${value} vs numpy ${NUMPY[key]}`).toBeLessThan(key === 'theta34' ? 1e-9 : 1e-12)
  })
})

describe('the number reader', () => {
  it('reads fractions, glyphs, 50/50, percentages and decimals; skips angles and references', () => {
    const got = shownNumbers('At 45°, $P(+) = \\tfrac{1}{2}$ or \\tfrac34; ⅛ + 50/50, 3/4, 25 %, ≈ 0.854 (§1.4, pp. 15–16, MIT 8.05, L1 p.4, Unit 2.5) $\\cos^2 22.5^\\circ$')
    expect(got.map((g) => g.raw.replace(/\s/g, ''))).toEqual(['\\tfrac{1}{2}', '\\tfrac34', '⅛', '50/50', '3/4', '25%', '0.854'])
    expect(got.map((g) => g.value)).toEqual([0.5, 0.75, 0.125, 0.5, 0.75, 0.25, 0.854])
  })
  it('ignores symbolic fractions', () => {
    expect(shownNumbers('$\\tfrac{1+\\cos\\theta}{2}$, $1/\\sqrt2$, $\\tfrac{\\hbar}{2}$, $2S_z/\\hbar$, ħ/2')).toEqual([])
  })
  it('the name "spin ½" is not a result, but a ½ beside it still is (L7 review)', () => {
    expect(shownNumbers('For a spin ½, a spin-½ ket and a spin-\\tfrac12 particle')).toEqual([])
    expect(shownNumbers('for a spin ½, $p_+ = \\tfrac12$ and ½').map((g) => g.value)).toEqual([0.5, 0.5])
  })
  it('a wrong number is caught (mutation: 0.854 → 0.845 in a copy of L1)', () => {
    const L = LECTURES.find((l) => l.id === 'L1')!
    const mutated: Lecture = {
      ...L,
      units: L.units.map((u) =>
        u.id !== 'l1-average' ? u : { ...u, story: u.story!.map((b) => (b.id === 'l1-average:b3' ? { ...b, caption: b.caption!.replace('0.854', '0.845') } : b)) },
      ),
    }
    expect(unbacked(mutated)).toEqual(['l1-average:b3 caption: 0.845'])
  })
})

/** The ledger's checks for one chapter in one track, against a table of twins. */
function ledger(lecture: Lecture, track: Track, twins: Readonly<Record<string, number>>) {
  it('every claim is keyed, and its key has a numpy value', () => {
    const bad = allClaims(lecture)
      .map(({ where, claim }) => ({ where, key: claimKey(claim), text: claim.text }))
      .filter((c) => c.key === null || !(c.key in twins))
    expect(bad).toEqual([])
  })
  it('every displayed decimal, fraction and percentage is backed by a claim of its beat or unit', () => {
    expect(unbacked(lecture, twins, track)).toEqual([])
  })
  it('no raw engine float reaches the page: no exponent notation, no number with 7 or more decimals', () => {
    // a template like `${V.x}` prints 1.232595164407831e-32 for a zero that is not exactly 0 (L2 review, 2026-09-27)
    const RAW = /\d(?:\.\d+)?e[-+]?\d|\d\.\d{7,}/
    const bad = readingOrder(lecture, track).filter((site) => RAW.test(site.text)).map((site) => `${site.where} ${site.field}: ${site.text.slice(0, 80)}`)
    expect(bad).toEqual([])
  })
  it('the reader finds numbers in every unit with a story or review (guard against a vacuous pass)', () => {
    for (const u of lecture.units.filter((x) => x.story?.length || x.review)) {
      const found = scopedSites({ ...lecture, units: [u] }, track).flatMap((s) => shownNumbers(s.text))
      expect(found.length, u.id).toBeGreaterThan(0)
    }
  })
}

describe.each(TRACKED)('claim ledger: %s', (_, lecture, track) => ledger(lecture, track, NUMPY))

describe.each(COURSES.qc709.tracks.map((t) => [t] as const))('claim ledger: the DEV demo chapter Q0, %s', (track) => {
  it('the analytic twins agree with the fixture’s engine values', () => {
    for (const [k, v] of Object.entries(Q0_VALUES)) expect(Math.abs(v - DEMO_TWINS[k]), k).toBeLessThan(1e-15)
  })
  ledger(Q0, track, DEMO_TWINS)
})

describe('the ledger reads each track (mutations of Q0)', () => {
  const b3 = Q0.units[0].story![2]
  const patch = (fn: (b: typeof b3) => typeof b3): Lecture => ({
    ...Q0,
    units: Q0.units.map((u, k) => (k ? u : { ...u, story: u.story!.map((b) => (b.id === b3.id ? fn(b) : b)) })),
  })
  it('a wrong number in the Formal text is caught in Formal only', () => {
    const bad = patch((b) => ({ ...b, formal: b.formal!.replace('\\tfrac12', '\\tfrac13') }))
    expect(unbacked(bad, DEMO_TWINS, 'formal')).toEqual(['q0-demo-sphere:b3 text: \\tfrac13'])
    expect(unbacked(bad, DEMO_TWINS, 'ground')).toEqual([])
  })
  it('a wrong number in a derivation line is caught in that line’s track', () => {
    const bad = patch((b) => ({ ...b, derivation: { ...b.derivation!, ground: b.derivation!.ground.map((s, i) => (i === 2 ? { ...s, why: 'So the chance is 0.4 here.' } : s)) } }))
    expect(unbacked(bad, DEMO_TWINS, 'ground')).toEqual(['q0-demo-sphere:b3.derivation.ground[2] why: 0.4'])
    expect(unbacked(bad, DEMO_TWINS, 'formal')).toEqual([])
  })
})
