import type { Lecture } from './schema'
import { V, claim, close, d } from './L11.values'
import { L11_STORY } from './L11.story'
import { L11_REVIEW } from './L11.review'
import './bridges448'

// Every number a learner sees in this lecture is computed in L11.values.ts, then asserted in keyed claims
// (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy). Plan: docs/roles/proposals/P-L11-story.md, with the
// judge's rulings (docs/roles/decisions/448-L8L11.md, L11): built from notes pp. 1-2 and 10-19 (§§11.4-11.10), the second half of Class 11
// (the first half, §§11.1-11.3, is Chapter 10's GHZ argument; one link-back beat recaps it). The `clocks` kind and the `two-clocks`
// widget draw the two energy components of a two-level state as phase clocks (R1); every picture uses E+ = 3 epsilon and E- = epsilon
// (R2); Go deeper 3 supplies P(+x; t) (R3); the notes' "~" is written "≅" (R5). No homework exists for L11. The 448 -> 709 chips live in
// content/bridges448.ts.

export const L11: Lecture = {
  id: 'L11',
  number: 11,
  title: 'Quantum dynamics',
  // the lecture header shows this after "Lecture 11": the chapter is the second half of Class 11 (R4: no class marker inside)
  date: 'Class 11, second half',
  outcomes: [
    'Say why waiting must be a unitary evolution of the state.',
    'Derive that a tiny step is I − iH dt/ħ with H Hermitian, and name H as the generator of time translations.',
    'Build the time-evolution operator U(t) for a finite wait and derive the Schrödinger equation from the tiny step.',
    'Explain why an energy eigenstate is stationary and why motion needs a relative phase.',
    'Evolve |+x⟩ under H = ĒI + (ħω/2)Z and read the Bloch arrow turning at ω = (E₊ − E₋)/ħ.',
  ],
  prerequisites: ['rz', 'full-turn', 'phase-longitude', 'eigen-problem', 'basis-change'],
  // Symbols defined in the text itself (symbol → the unit, beat or site whose sentence defines it). Kets, bras, the average and the
  // letters of earlier lectures are mapped to the first unit that uses them: a recap.
  symbols: {
    '|\\cdot\\rangle': 'l11-wait:b2',
    '|\\psi\\rangle': 'l11-wait:b2',
    t: 'l11-wait:b2',
    '|+x\\rangle': 'l11-wait:b2',
    '|+y\\rangle': 'l11-wait:b3',
    '|+z\\rangle': 'l11-wait:b5',
    '|-z\\rangle': 'l11-wait:b5',
    '|-x\\rangle': 'l11-wait:b5',
    '|-y\\rangle': 'l11-wait:b5',
    '\\langle\\cdot|\\cdot\\rangle': 'l11-unitary:b2',
    '\\langle\\cdot|': 'l11-unitary:b2',
    '\\langle\\cdot\\rangle': 'l11-stationary:b4',
    R_z: 'l11-wait:b3',
    S_z: 'l11-wait:b3',
    '\\varphi': 'l11-wait:b3',
    '\\hbar': 'l11-wait:b3',
    I: 'l11-wait:b3',
    i: 'l11-wait:b3',
    e: 'l11-wait:b3',
    d: 'l11-wait:b3',
    U: 'l11-unitary:b1',
    '\\dagger': 'l11-unitary:b2',
    '\\sigma_z': 'l11-unitary:b5',
    '\\sigma_x': 'l11-generator:b1',
    '\\sigma_y': 'l11-two-level:b7',
    A: 'l11-unitary:b6',
    '\\pi': 'l11-unitary:b1',
    '\\varepsilon': 'l11-generator:b2',
    N: 'l11-generator:b3',
    E: 'l11-stationary:b1',
    P: 'l11-wait:b5',
    '\\bar E': 'l11-two-level:b1',
    '\\omega': 'l11-two-level:b1',
    Z: 'l11-two-level:b2',
    '\\cong': 'l11-two-level:b2',
    T: 'l11-two-level:b8',
    '\\theta': 'l11-two-level:b4',
    '|E\\rangle': 'l11-stationary:b1',
    '|E_j\\rangle': 'l11-schrodinger:b5',
    E_j: 'l11-schrodinger:b5',
    'E_\\pm': 'l11-two-level:b1',
    'E_+': 'l11-two-level:b1',
    'E_-': 'l11-two-level:b1',
    '|\\psi(t)\\rangle': 'l11-unitary:b1',
    '|\\psi(0)\\rangle': 'l11-unitary:b1',
    '|\\psi(t+dt)\\rangle': 'l11-schrodinger:b1',
    c: 'l11-schrodinger:b6',
    n: 'l11-stationary:b1',
    '|E(t)\\rangle': 'l11-stationary:b1',
    S_x: 'l11-two-level:b10',
    'U_1': 'l11-unitary:b5',
    'U_2': 'l11-unitary:b6',
    M: 'l11-unitary:b6',
    '\\psi': 'l11-wait:b2',
  },
  units: [
    {
      id: 'l11-wait',
      story: L11_STORY['l11-wait'],
      review: L11_REVIEW['l11-wait'],
      title: 'What happens if we wait?',
      question: 'We can prepare, measure and turn states; how does a state change by itself?',
      lecture: {
        pages: 'L11 pp. 1–2, 10, 19 (§11.4)',
        summary:
          'So far quantum mechanics has been static. The new question is how a state $|\\psi\\rangle$ prepared at $t = 0$ looks at a later time $t$. A tiny turn is $R_z(d\\varphi) \\approx I - \\tfrac{i}{\\hbar}S_z\\,d\\varphi$, and waiting will have the same structure.',
        equations: ['R_z(d\\varphi) \\approx I - \\tfrac{i}{\\hbar}S_z\\,d\\varphi'],
      },
      books: [{ source: 'susskind', where: 'Lecture 4, §4.1–4.3', adds: 'The state vector follows an exact law, yet measurement outcomes stay probabilistic, unlike classical determinism.' }],
      visual: {
        kind: 'bloch',
        props: { theta: 90, phi: 0, rotations: true, rotationAngles: [30, 90], landmarks: true },
        caption: 'Turn |+x⟩ about z in small steps and in one big step.',
        tryThis: [
          'Start at |+x⟩ (θ = 90°, φ = 0°). Press $R_z(30^\\circ)$, wait for the point to stop, and press it twice more. The note under the sphere reads φ = 90°.',
          'Set φ back to 0° with its slider and press $R_z(90^\\circ)$ once. The point lands in the same place, on the |+y⟩ landmark: three small turns are one big turn.',
        ],
      },
      clues: [],
      insight: 'Waiting will turn out to be a rotation-like change of the state, exact and deterministic, while each reading stays random.',
      pitfalls: [
        'Expecting a deterministic ket to give predictable readings. The ket changes by an exact law; its chances stay chances.',
        'Treating time as something new. A tiny wait will look just like a tiny turn, with a different generator.',
      ],
      play: [
        {
          id: 'l11-wa-turn',
          kind: 'choice',
          tier: 'warm-up',
          title: 'A quarter turn about z',
          prompt: 'Into which state does $R_z(90^\\circ)$ turn $|{+x}\\rangle$?',
          options: [
            { text: '$|{+y}\\rangle$', correct: true, why: 'Right: a quarter turn about $z$ carries the point from $+x$ to $+y$.' },
            { text: '$|{-x}\\rangle$', correct: false, why: 'That needs a half turn, $R_z(180^\\circ)$.' },
            { text: '$|{+z}\\rangle$', correct: false, why: 'A turn about $z$ never moves the point off the equator or toward $+z$.' },
            { text: '$|{-y}\\rangle$', correct: false, why: 'That is the other way round, $R_z(-90^\\circ)$.' },
          ],
          hints: [
            { text: 'A turn about $z$ moves the point along the equator.' },
            { text: 'Positive angles carry $+x$ toward $+y$.' },
            { text: 'A quarter turn is $90^\\circ$ round.' },
          ],
          walkthrough: [
            { text: 'The equator state at azimuth $\\varphi$ is $(|{+z}\\rangle + e^{i\\varphi}|{-z}\\rangle)/\\sqrt2$. A turn by $90^\\circ$ adds $90^\\circ$ to the azimuth.' },
            { text: 'Azimuth $0^\\circ$ is $|{+x}\\rangle$ and azimuth $90^\\circ$ is $|{+y}\\rangle$.' },
          ],
        },
        {
          id: 'l11-wa-steps',
          kind: 'numeric',
          tier: 'core',
          title: 'Three small turns',
          prompt: 'Three turns $R_z(30^\\circ)$ in a row equal one turn of how many degrees?',
          answer: V.l11Steps3,
          tolerance: 0.5,
          unit: '°',
          hints: [
            { text: 'Turns about the same axis add their angles.' },
            { text: 'Each step adds $30^\\circ$ to the azimuth.' },
            { text: 'Add three of them.' },
          ],
          walkthrough: [
            { text: `The three turns add: $30^\\circ + 30^\\circ + 30^\\circ = ${d(V.l11Steps3, 0)}^\\circ$.` },
            { text: 'Many small steps make one big step: the idea behind the next units.' },
          ],
        },
      ],
    },
    {
      id: 'l11-unitary',
      story: L11_STORY['l11-unitary'],
      review: L11_REVIEW['l11-unitary'],
      title: 'Waiting keeps every length',
      question: 'What must time evolution do to the length of every state?',
      lecture: {
        pages: 'L11 p. 11 (§11.5)',
        summary:
          'Write $|\\psi(t)\\rangle = U(t)|\\psi(0)\\rangle$. A closed system keeps its total probability for every starting state, so $\\langle\\psi(0)|U^\\dagger U|\\psi(0)\\rangle = \\langle\\psi(0)|\\psi(0)\\rangle$ and $U^\\dagger U = I$: time evolution is unitary, for the same reason rotations are.',
        equations: ['|\\psi(t)\\rangle = U(t)|\\psi(0)\\rangle', 'U^\\dagger(t)\\,U(t) = I'],
      },
      books: [{ source: 'susskind', where: 'Lecture 4, §4.2–4.4', adds: 'Distinct states must stay distinct, so orthogonal states stay orthogonal and the evolution operator is unitary.' }],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'multiply', z: [0.6, 0.8], w: [0.8, 0.6] },
        caption: 'Multiplying by a number of size 1 only turns.',
        tryThis: [
          'The readout shows r = 1 for z, for w and for the product zw. Multiplying by a number of size 1 only turns z.',
          'Choose “drag w” and pull w outward, off the unit circle. The r of zw grows by the same factor as the r of w. A wait must never change a length like that.',
        ],
      },
      clues: [],
      insight: 'A closed system keeps its total probability for every state, so time evolution is unitary.',
      pitfalls: [
        'Checking only a basis. A matrix can keep $|{\\pm z}\\rangle$ at length 1 and still stretch other states.',
        'Thinking the length condition is a special property of rotations. Every closed-system evolution has it.',
      ],
      claims: [
        claim('l11UnWhich', 'only R_z(60°) among the four candidates is unitary', () => V.l11UnWhich === 1),
        claim('l11BadX', 'U₁ takes |+x⟩ to squared length 1.707', () => close(V.l11BadX, 1 + Math.SQRT1_2, 1e-9)),
        claim('l11U2Y', 'U₂ takes |+y⟩ to squared length 0.293', () => close(V.l11U2Y, 1 - Math.SQRT1_2)),
      ],
      play: [
        {
          id: 'l11-un-which',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which matrix can be a wait?',
          prompt: 'Which of these matrices can describe waiting for a closed system?',
          options: [
            { text: '$R_z(60^\\circ) = \\mathrm{diag}(e^{-i\\pi/6}, e^{i\\pi/6})$', correct: true, why: 'It is unitary: its columns have length 1 and are orthogonal.' },
            { text: '$\\mathrm{diag}(1, 2)$', correct: false, why: 'It stretches $|{-z}\\rangle$ to length 2.' },
            { text: '$\\begin{pmatrix}1 & 1\\\\ 0 & 1\\end{pmatrix}$', correct: false, why: 'It takes $|{-z}\\rangle$ to a state of squared length 2.' },
            { text: '$\\tfrac12 I$', correct: false, why: 'It halves every length, so the total probability drops to $\\tfrac14$.' },
          ],
          hints: [
            { text: 'Waiting must keep the length of every state.' },
            { text: 'Test each matrix on $|{-z}\\rangle$ first.' },
            { text: 'A unitary matrix has $U^\\dagger U = I$.' },
          ],
          walkthrough: [
            { text: 'Waiting needs $U^\\dagger U = I$, so each candidate must keep lengths.' },
            { text: 'Only the rotation does. The other three change the length of $|{-z}\\rangle$ or of $|{+z}\\rangle$.' },
          ],
        },
        {
          id: 'l11-un-bad',
          kind: 'numeric',
          tier: 'core',
          title: 'A matrix that fails on one state',
          prompt: 'Let $U_1 = \\begin{pmatrix}1 & 1/\\sqrt2\\\\ 0 & 1/\\sqrt2\\end{pmatrix}$. What is the squared length of $U_1|{+x}\\rangle$?',
          answer: V.l11BadX,
          tolerance: 0.001,
          hints: [
            { text: 'Write $|{+x}\\rangle$ as the column $(1, 1)/\\sqrt2$.' },
            { text: 'Multiply: the top entry is $(1 + 1/\\sqrt2)/\\sqrt2$ and the bottom one is $1/2$.' },
            { text: 'Add the squared sizes of the two entries.' },
          ],
          walkthrough: [
            { text: 'The product is $((1 + 1/\\sqrt2)/\\sqrt2,\\ 1/2) = (0.707 + 0.5,\\ 0.5)$.' },
            { text: `Its squared length is $1.207^2 + 0.5^2 = ${d(V.l11BadX, 3)}$, more than 1. So $U_1$ cannot describe waiting.` },
          ],
        },
        {
          id: 'l11-un-four',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A matrix that fails on |+y⟩ (beyond the notes)',
          prompt: 'Let $U_2 = \\begin{pmatrix}1 & i/\\sqrt2\\\\ 0 & 1/\\sqrt2\\end{pmatrix}$. What is the squared length of $U_2|{+y}\\rangle$?',
          answer: V.l11U2Y,
          tolerance: 0.001,
          hints: [
            { text: 'Write $|{+y}\\rangle$ as the column $(1, i)/\\sqrt2$.' },
            { text: 'The top entry is $(1 + i\\cdot i/\\sqrt2)/\\sqrt2 = (1 - 1/\\sqrt2)/\\sqrt2$.' },
            { text: 'The bottom entry is $i/2$. Add the squared sizes.' },
          ],
          walkthrough: [
            { text: 'The top entry is $(1 - 1/\\sqrt2)/\\sqrt2 = 0.207$ and the bottom entry is $i/2$.' },
            { text: `The squared length is $0.207^2 + 0.5^2 = ${d(V.l11U2Y, 3)}$, less than 1. This $U_2$ keeps $|{+x}\\rangle$ but not $|{+y}\\rangle$.` },
          ],
        },
      ],
    },
    {
      id: 'l11-generator',
      story: L11_STORY['l11-generator'],
      review: L11_REVIEW['l11-generator'],
      title: 'The Hamiltonian generates each tiny step',
      question: 'Which operator moves a state forward by a tiny time?',
      lecture: {
        pages: 'L11 pp. 12–13 (§11.6)',
        summary:
          'A tiny wait is $U(dt) = I + A\\,dt$. Unitarity to first order gives $A^\\dagger = -A$, so $A = -\\tfrac{i}{\\hbar}H$ with $H^\\dagger = H$. Physics names $H$, the energy observable, the generator of time translations. Chaining many tiny waits gives $U(t) = e^{-iHt/\\hbar}$, the counterpart of $R_z(\\varphi) = e^{-i\\varphi S_z/\\hbar}$.',
        equations: ['U(dt) = I - \\tfrac{i}{\\hbar}H\\,dt', 'U(t) = e^{-iHt/\\hbar}'],
      },
      books: [
        { source: 'susskind', where: 'Lecture 4, §4.5–4.6', adds: 'The same step from unitarity and continuity; the −i is a convention and ħ fixes the units.' },
        { source: 'townsend', where: '§2.2, pp. 36–37', adds: 'Finite rotations built from tiny ones: the analogy this lecture draws for time.' },
      ],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'euler', phi: -90, n: 1 },
        caption: 'N tiny turns chained: the end point against the unit circle.',
        tryThis: [
          'With n = 1 the single step ends well outside the circle, far from the point −i.',
          'Drag n up to 64. The corners of the polygon crowd onto the unit circle and the end point settles on −i.',
        ],
      },
      clues: [],
      insight: 'A tiny wait is I − iH dt/ħ with H Hermitian, the energy observable. Chaining many of them gives $U(t) = e^{-iHt/\\hbar}$.',
      pitfalls: [
        'Forgetting the $i$ in $-\\tfrac{i}{\\hbar}H$. Without it the step would stretch states.',
        'Treating a finite product of tiny steps as exactly unitary. Only its limit is.',
      ],
      claims: [
        claim('l11AntiWhich', 'among −iσ_z, σ_z, σ_x and I + σ_z only −iσ_z is anti-Hermitian', () => V.l11AntiWhich === 1),
        claim('l11DtLen2', 'a step of dt = 0.01 stretches |+x⟩ to squared length 1.0005', () => close(V.l11DtLen2, 1.0005, 1e-9)),
        claim('l11Over1', 'one big step stretches |+x⟩ to squared length 1 + π²/4 = 3.467', () => close(V.l11Over1, 1 + (Math.PI / 2) ** 2, 1e-9)),
      ],
      play: [
        {
          id: 'l11-ge-anti',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which operator is anti-Hermitian?',
          prompt: 'Which of these satisfies $A^\\dagger = -A$?',
          options: [
            { text: '$-i\\sigma_z$', correct: true, why: 'Its conjugate transpose is $+i\\sigma_z$, which is minus the operator itself.' },
            { text: '$\\sigma_z$', correct: false, why: 'It is Hermitian: $\\sigma_z^\\dagger = \\sigma_z$.' },
            { text: '$\\sigma_x$', correct: false, why: 'It is Hermitian too.' },
            { text: '$I + \\sigma_z$', correct: false, why: 'A sum of Hermitian operators with real coefficients is Hermitian.' },
          ],
          hints: [
            { text: 'Take the conjugate transpose of each option.' },
            { text: 'A Hermitian matrix equals its own conjugate transpose.' },
            { text: 'Look for the one that picks up a minus sign instead.' },
          ],
          walkthrough: [
            { text: 'The three Hermitian options are unchanged by the conjugate transpose.' },
            { text: 'For $-i\\sigma_z$ the conjugate of $-i$ is $+i$, and $\\sigma_z$ is unchanged, so the result is $-A$.' },
          ],
        },
        {
          id: 'l11-ge-dt',
          kind: 'numeric',
          tier: 'core',
          title: 'One tiny step is almost unitary',
          prompt: 'For $H = \\mathrm{diag}(3\\varepsilon, \\varepsilon)$ and $dt = 0.01\\,\\hbar/\\varepsilon$, what is the squared length of $(I - \\tfrac{i}{\\hbar}H\\,dt)|{+x}\\rangle$?',
          answer: V.l11DtLen2,
          tolerance: 0.0001,
          hints: [
            { text: 'The step multiplies the $|{+z}\\rangle$ part by $1 - 0.03i$ and the $|{-z}\\rangle$ part by $1 - 0.01i$.' },
            { text: 'A factor $1 - 0.03i$ has the squared size $1 + 0.03^2$; do the same for the other factor.' },
            { text: 'Average the two squared sizes, since $|{+x}\\rangle$ has weight $\\tfrac12$ on each part.' },
          ],
          walkthrough: [
            { text: 'The squared sizes of the two factors are $1 + 0.03^2 = 1.0009$ and $1 + 0.01^2 = 1.0001$.' },
            { text: `Each part carries weight $\\tfrac12$, so the squared length is ${d(V.l11DtLen2, 4)}: off from 1 only at second order in $dt$.` },
          ],
        },
        {
          id: 'l11-ge-n1',
          kind: 'numeric',
          tier: 'stretch',
          title: 'One big step (beyond the notes)',
          prompt: 'Take $H = \\mathrm{diag}(\\varepsilon, -\\varepsilon)$, whose mean energy is zero, and wait $t = \\tfrac{\\pi}{2}\\hbar/\\varepsilon$, a total turn of $180^\\circ$. One single step ($N = 1$) of $I - \\tfrac{i}{\\hbar}Ht$ acts on $|{+x}\\rangle$. What is the squared length of the result?',
          answer: V.l11Over1,
          tolerance: 0.001,
          hints: [
            { text: 'The step multiplies the two parts by $1 - i\\pi/2$ and $1 + i\\pi/2$.' },
            { text: 'Both factors have the squared size $1 + (\\pi/2)^2$.' },
            { text: 'Both parts carry weight $\\tfrac12$, so the squared length is that same number.' },
          ],
          walkthrough: [
            { text: 'Each factor has squared size $1 + (\\pi/2)^2$, and the two parts share the weight equally.' },
            { text: `So the squared length is $1 + \\pi^2/4 = ${d(V.l11Over1, 3)}$: one big step is far from unitary.` },
          ],
        },
      ],
    },
    {
      id: 'l11-schrodinger',
      story: L11_STORY['l11-schrodinger'],
      review: L11_REVIEW['l11-schrodinger'],
      title: 'The Schrödinger equation',
      question: 'How fast is a state changing at each instant?',
      lecture: {
        pages: 'L11 pp. 14–15 (§11.7)',
        summary:
          'Apply the tiny wait to $|\\psi(t)\\rangle$, subtract, divide by $dt$ and let $dt \\to 0$: $i\\hbar\\,\\tfrac{d}{dt}|\\psi\\rangle = H|\\psi\\rangle$. For a time-independent $H$ this says the same as $U(t) = e^{-iHt/\\hbar}$. The structure matches rotations, with $S_z$ and the angle replaced by $H$ and the time.',
        equations: ['i\\hbar\\,\\frac{d}{dt}|\\psi(t)\\rangle = H|\\psi(t)\\rangle'],
      },
      books: [{ source: 'susskind', where: 'Lecture 4, §4.12–4.13', adds: 'The wavefunction equation as a special case, the time-independent partner, and the recipe of attaching $e^{-iE_jt/\\hbar}$ to each energy eigenstate.' }],
      visual: {
        kind: 'bloch',
        props: { theta: 90, phi: 0, rotations: true, rotationAngles: [10], landmarks: true },
        caption: 'Many tiny turns add up to a quarter turn.',
        tryThis: ['Press $R_z(10^\\circ)$, wait for the point to stop, and press it again, nine times in all. Many small steps make one quarter turn: the note under the sphere reads φ = 90°.'],
      },
      clues: [],
      insight: 'The Schrödinger equation is the differential form of $U(t) = e^{-iHt/\\hbar}$: the Hamiltonian sets how fast, and which way, the state moves.',
      pitfalls: [
        'Thinking the equation is a new law. For a time-independent $H$ it says the same thing as $U(t) = e^{-iHt/\\hbar}$.',
        'Expecting a second starting condition. The state at one instant is enough.',
      ],
      claims: [
        claim('l11FD', 'a finite difference of U(t)|+x⟩ equals −iH U(t)|+x⟩', () => V.l11FD === 1),
        claim('l11DerivZ', 'the |+z⟩ amplitude changes at −3i at t = 0', () => close(V.l11DerivZ, -3)),
      ],
      play: [
        {
          id: 'l11-sc-order',
          kind: 'order',
          tier: 'core',
          title: 'From the tiny step to the equation',
          prompt: 'Put the steps from the tiny wait to the Schrödinger equation in order.',
          steps: [
            'Write one tiny wait: $|\\psi(t+dt)\\rangle = (I - \\tfrac{i}{\\hbar}H\\,dt)|\\psi(t)\\rangle$.',
            'Multiply out the bracket.',
            'Subtract $|\\psi(t)\\rangle$ from both sides.',
            'Divide by $dt$.',
            'Let $dt$ shrink to zero, so the left side is $\\tfrac{d}{dt}|\\psi\\rangle$.',
            'Multiply by $i\\hbar$.',
          ],
          hints: [
            { text: 'Start from the tiny wait and end at the equation with $i\\hbar$ in front.' },
            { text: 'The change in the state is formed before it is divided by $dt$.' },
            { text: 'The limit comes after the division, and the factor $i\\hbar$ comes last.' },
          ],
          walkthrough: [
            { text: 'First the tiny wait, then multiply out and subtract the starting state to isolate the change.' },
            { text: 'Divide by $dt$, let it shrink to get a derivative, and multiply by $i\\hbar$.' },
          ],
        },
        {
          id: 'l11-sc-rate',
          kind: 'numeric',
          tier: 'core',
          title: 'How fast an amplitude changes',
          prompt: 'A spin starts in $|{+z}\\rangle$ and waits under $H = \\mathrm{diag}(3\\varepsilon, \\varepsilon)$. At $t = 0$ its $|{+z}\\rangle$ amplitude changes at the rate $c\\,i\\,\\varepsilon/\\hbar$. What is $c$?',
          answer: V.l11DerivZ,
          tolerance: 0.01,
          hints: [
            { text: 'The equation says $d|\\psi\\rangle/dt = -\\tfrac{i}{\\hbar}H|\\psi\\rangle$.' },
            { text: '$H$ acting on $|{+z}\\rangle$ gives $3\\varepsilon\\,|{+z}\\rangle$.' },
            { text: 'Multiply by $-i/\\hbar$.' },
          ],
          walkthrough: [
            { text: 'Since $H|{+z}\\rangle = 3\\varepsilon|{+z}\\rangle$, the rate is $-\\tfrac{i}{\\hbar}\\cdot 3\\varepsilon$ times the amplitude, which is 1 at $t = 0$.' },
            { text: `So the rate is $-3i\\,\\varepsilon/\\hbar$, that is $c = ${d(V.l11DerivZ, 0)}$.` },
          ],
        },
      ],
    },
    {
      id: 'l11-stationary',
      story: L11_STORY['l11-stationary'],
      review: L11_REVIEW['l11-stationary'],
      title: 'Energy eigenstates stand still',
      question: 'Which states never change at all, and why?',
      lecture: {
        pages: 'L11 p. 16 (§11.8)',
        summary:
          'If $H|E\\rangle = E|E\\rangle$ then $e^{-iHt/\\hbar}|E\\rangle = e^{-iEt/\\hbar}|E\\rangle$: only an overall phase, which changes no probability. Energy eigenstates are stationary. Observable motion needs a relative phase between components of different energy.',
        equations: ['|E(t)\\rangle = e^{-iEt/\\hbar}|E\\rangle'],
      },
      books: [{ source: 'susskind', where: 'Lecture 4, §4.8, §4.10', adds: 'Energy is conserved because H commutes with itself; the average energy stays constant even for states that move.' }],
      visual: {
        kind: 'phase-dial',
        props: { theta: 0, rotations: false },
        caption: 'Two amplitudes turned together: the phasors spin, the point stays.',
        tryThis: [
          'Press “multiply both by $e^{i\\pi/2}$”. The two phasors turn together, the point on the equator stays and the relative phase stays at 0°. An energy eigenstate’s ket changes in just this way as time passes.',
          'Now drag the φ slider away from 0°. The phasors turn apart and the point moves. That needs two different energies, which the next unit supplies.',
        ],
      },
      clues: [],
      insight: 'An energy eigenstate only gains an overall phase, so nothing observable changes. Motion comes from a relative phase.',
      pitfalls: [
        'Reading “stationary” as “the ket is constant”. The ket’s phase turns; only the predictions stand still.',
        'Expecting every state to be stationary. Only the states with one definite energy are.',
      ],
      claims: [
        claim('l11StatZ', '|+z⟩ only gains a phase at every sampled time', () => V.l11StatZ === 1),
        claim('l11EnergyConst', '⟨H⟩ for |+x⟩ stays 2', () => close(V.l11EnergyConst, 2, 1e-9)),
      ],
      play: [
        {
          id: 'l11-st-which',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which states are stationary?',
          prompt: 'For $H = \\mathrm{diag}(3\\varepsilon, \\varepsilon)$, which states are stationary?',
          options: [
            { text: '$|{+z}\\rangle$ and $|{-z}\\rangle$ only', correct: true, why: 'They are the energy eigenstates: waiting multiplies each by a phase.' },
            { text: 'Every state', correct: false, why: 'A superposition of the two energies gains a changing relative phase.' },
            { text: '$|{+x}\\rangle$ and $|{-x}\\rangle$', correct: false, why: 'These are equal mixes of the two energies, so they move.' },
            { text: 'None of them', correct: false, why: 'The two energy eigenstates stand still.' },
          ],
          hints: [
            { text: 'A stationary state is an energy eigenstate.' },
            { text: 'The Hamiltonian is diagonal in the $z$ basis.' },
            { text: 'Which kets does a diagonal $H$ only rescale?' },
          ],
          walkthrough: [
            { text: 'In the $z$ basis $H$ is diagonal, so $|{+z}\\rangle$ and $|{-z}\\rangle$ are its eigenvectors.' },
            { text: 'Every other state mixes the two energies and gains a relative phase.' },
          ],
        },
        {
          id: 'l11-st-prob',
          kind: 'numeric',
          tier: 'core',
          title: 'Nothing observable changes',
          prompt: 'A spin is prepared in $|{+z}\\rangle$ and waits. What is the chance of reading $+z$ afterwards, at any time?',
          answer: V.l11StatProb,
          tolerance: 0.001,
          hints: [
            { text: '$|{+z}\\rangle$ is an energy eigenstate.' },
            { text: 'Waiting multiplies it by the phase $e^{-iEt/\\hbar}$.' },
            { text: 'A phase of size 1 does not change a chance.' },
          ],
          walkthrough: [
            { text: 'After a wait the ket is $e^{-iEt/\\hbar}|{+z}\\rangle$, an overall phase times the same state.' },
            { text: `The chance of $+z$ is the squared size of the amplitude, ${d(V.l11StatProb, 0)}, at every time.` },
          ],
        },
        {
          id: 'l11-st-energy',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The energy of a moving state',
          prompt: 'For $H = \\mathrm{diag}(3\\varepsilon, \\varepsilon)$, what is $\\langle H\\rangle$ for the state that started in $|{+x}\\rangle$, at $\\varepsilon t/\\hbar = 90^\\circ$? Answer in units of $\\varepsilon$.',
          answer: V.l11EnergyAt90,
          tolerance: 0.001,
          unit: 'ε',
          hints: [
            { text: 'Energy is conserved when $H$ does not depend on time.' },
            { text: 'At $t = 0$, $|{+x}\\rangle$ has weight $\\tfrac12$ on each energy.' },
            { text: 'Average the two energies.' },
          ],
          walkthrough: [
            { text: 'The weights of the two energies never change, only the phases do.' },
            { text: `So $\\langle H\\rangle = \\tfrac12(3\\varepsilon) + \\tfrac12(\\varepsilon) = ${d(V.l11EnergyAt90, 0)}\\varepsilon$ at every time, including $90^\\circ$.` },
          ],
        },
      ],
    },
    {
      id: 'l11-two-level',
      story: L11_STORY['l11-two-level'],
      review: L11_REVIEW['l11-two-level'],
      title: 'Two energies make the arrow turn',
      question: 'What does a spin with two energy levels do as time passes?',
      lecture: {
        pages: 'L11 pp. 17–19 (§11.9–11.10)',
        summary:
          'For $H = \\mathrm{diag}(E_+, E_-) = \\bar E I + \\tfrac{\\hbar\\omega}{2}Z$ the evolution splits: $U(t) \\cong R_z(\\omega t)$. Starting in $|{+x}\\rangle$, the state becomes $(|{+z}\\rangle + e^{i\\omega t}|{-z}\\rangle)/\\sqrt2$ up to an overall phase: the Bloch arrow turns about $z$ at $\\omega = (E_+ - E_-)/\\hbar$. Energy eigenstates gain only overall phases; a superposition of different energies gains a changing relative phase.',
        equations: ['U(t) \\cong R_z(\\omega t)', '|\\psi(t)\\rangle \\cong \\tfrac{1}{\\sqrt2}\\left(|{+z}\\rangle + e^{i\\omega t}|{-z}\\rangle\\right)'],
      },
      books: [{ source: 'susskind', where: 'Lecture 4, §4.11', adds: 'A spin in a field along z: the averages of $\\sigma_x$ and $\\sigma_y$ precess while $\\sigma_z$ is constant, and each single reading is still ±1.' }],
      visual: {
        kind: 'two-clocks',
        props: { upper: 3, lower: 1, start: '+x' },
        caption: 'One clock for each energy: the gap between the hands is the azimuth of the arrow.',
        tryThis: [
          'Drag the time slider to 45°. The readout line says gap = 90° and the arrow on the equator points along +y.',
          'Raise the mean energy Ē from 2ε to 4ε. Both hands run faster, but the gap, P(+x) and the arrow do not change.',
          'Choose the start |+z⟩. Only one clock has a hand, and nothing moves however far you drag the time.',
        ],
      },
      clues: [],
      insight: 'A superposition of two energies turns at the difference of the energies; the mean energy is only an overall phase.',
      pitfalls: [
        'Saying the arrow turns at $E_+/\\hbar$. Only the difference of the energies is seen; the mean is an overall phase.',
        'Calling the superposition a [[mixture|mixture]]. A mixture is a different object: a set of states weighted by probabilities, not a sum of amplitudes.',
      ],
      claims: [
        claim('l11UisRz', 'U(t) = e^{−iĒt/ħ} R_z(ωt)', () => V.l11UisRz === 1),
        claim('l11UT', 'U(T) = −I for 3ε and ε', () => V.l11UT === 1),
      ],
      play: [
        {
          id: 'l11-tl-omega',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The splitting',
          prompt: 'For $E_+ = 3\\varepsilon$ and $E_- = \\varepsilon$, what is $\\hbar\\omega$ in units of $\\varepsilon$?',
          answer: V.l11HbarOmega,
          tolerance: 0.001,
          unit: 'ε',
          hints: [
            { text: 'The splitting is the gap between the two levels.' },
            { text: '$\\hbar\\omega = E_+ - E_-$.' },
            { text: 'Subtract.' },
          ],
          walkthrough: [{ text: `$\\hbar\\omega = 3\\varepsilon - \\varepsilon = ${d(V.l11HbarOmega, 0)}\\varepsilon$, twice the unit. The mean energy is $\\bar E = ${d(V.l11Mean, 0)}\\varepsilon$.` }],
        },
        {
          id: 'l11-tl-azimuth',
          kind: 'numeric',
          tier: 'core',
          title: 'The azimuth after a wait',
          prompt: 'The spin starts in $|{+x}\\rangle$. What is the azimuth $\\varphi$ of its Bloch arrow at $\\varepsilon t/\\hbar = 30^\\circ$, in degrees?',
          answer: V.l11Gap30,
          tolerance: 0.5,
          unit: '°',
          hints: [
            { text: 'The azimuth grows as $\\varphi(t) = \\omega t$.' },
            { text: 'Here $\\omega = 2\\varepsilon/\\hbar$.' },
            { text: '$\\omega t = 2\\times\\varepsilon t/\\hbar$.' },
          ],
          walkthrough: [
            { text: 'With $\\hbar\\omega = 2\\varepsilon$ the angle grows twice as fast as $\\varepsilon t/\\hbar$.' },
            { text: `At $\\varepsilon t/\\hbar = 30^\\circ$ the azimuth is $2\\times 30^\\circ = ${d(V.l11Gap30, 0)}^\\circ$.` },
          ],
        },
        {
          id: 'l11-tl-gap',
          kind: 'numeric',
          tier: 'core',
          title: 'The gap between the hands',
          prompt: 'How large is the angle between the two clock hands at $\\varepsilon t/\\hbar = 45^\\circ$, in degrees?',
          answer: V.l11Gap45,
          tolerance: 0.5,
          unit: '°',
          hints: [
            { text: 'The upper hand turns at $E_+/\\hbar$ and the lower hand at $E_-/\\hbar$.' },
            { text: 'Their difference is $\\omega = 2\\varepsilon/\\hbar$.' },
            { text: 'The gap is $\\omega t$.' },
          ],
          walkthrough: [
            { text: 'The upper hand has turned $3\\times 45^\\circ = 135^\\circ$ and the lower hand $45^\\circ$, both clockwise.' },
            { text: `The gap is $135^\\circ - 45^\\circ = ${d(V.l11Gap45, 0)}^\\circ$, a quarter turn of the arrow.` },
          ],
        },
        {
          id: 'l11-tl-period',
          kind: 'numeric',
          tier: 'stretch',
          title: 'After one period',
          prompt: 'After one period $T$, with $E_+ = 3\\varepsilon$ and $E_- = \\varepsilon$, what is $\\langle{+x}|U(T)|{+x}\\rangle$?',
          answer: V.l11UTx,
          tolerance: 0.001,
          hints: [
            { text: 'The arrow is back at $+x$ after $T$, but the ket may carry a sign.' },
            { text: 'Here $U(T) = -I$.' },
            { text: 'Sandwich $-I$ between $\\langle{+x}|$ and $|{+x}\\rangle$.' },
          ],
          walkthrough: [
            { text: 'The upper phase is $e^{-i3\\pi} = -1$ and the lower one $e^{-i\\pi} = -1$, so $U(T) = -I$.' },
            { text: `So $\\langle{+x}|U(T)|{+x}\\rangle = ${d(V.l11UTx, 0)}$: the same state with the opposite sign, the full-turn sign of Unit 7.2.` },
          ],
        },
        {
          id: 'l11-tl-px',
          kind: 'numeric',
          tier: 'stretch',
          title: 'What an x magnet sees (beyond the notes)',
          prompt: 'For $E_+ = 3\\varepsilon$, $E_- = \\varepsilon$ and a start in $|{+x}\\rangle$, what is the chance of $+x$ at $\\omega t = 60^\\circ$?',
          answer: V.l11Px60,
          tolerance: 0.001,
          hints: [
            { text: 'The state is the equator state at azimuth $\\omega t$.' },
            { text: 'Its chance for $+x$ is $\\cos^2$ of half the angle between it and $+x$.' },
            { text: 'The angle is $60^\\circ$, so use $\\cos^2 30^\\circ$.' },
          ],
          walkthrough: [
            { text: 'The arrow sits $60^\\circ$ round the equator from $+x$, so the chance of $+x$ is $\\cos^2(60^\\circ/2)$.' },
            { text: `That is $\\cos^2 30^\\circ = ${d(V.l11Px60, 2)}$.` },
          ],
        },
      ],
    },
  ],
}
