import type { Lecture } from './schema'
import { URL } from './refs'
import { V, claim, close, d } from './L2.values'
import { L2_STORY } from './L2.story'
import { L2_REVIEW } from './L2.review'

// Every number a learner sees in this lecture is computed in L2.values.ts, then asserted in keyed claims
// (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy). Plan: docs/roles/proposals/P-L2-story.md.

export const L2: Lecture = {
  id: 'L2',
  number: 2,
  title: 'States as vectors in a complex space',
  date: 'Sep 7, 2026',
  outcomes: [
    'List the rules a set must obey to be a vector space, and say why kets need complex numbers.',
    'Compute an inner product from columns, conjugating the bra, and use it for lengths, right angles and coordinates.',
    'Move between the Cartesian and polar forms of a complex number, and multiply by turning and stretching.',
    'Derive the spin state along +y, and explain why no real coefficient can produce it.',
    'Say what mutually unbiased bases are, and check that the z, x and y bases are.',
  ],
  prerequisites: ['vectors', 'probability'],
  // Symbols defined in the text itself (symbol → the unit, beat or site whose sentence defines it). Kets and
  // amplitudes from Lecture 1 (the prerequisite) are mapped to the first unit's title: a recap, not a new definition.
  symbols: {
    '|\\cdot\\rangle': 'l2-vector-space',
    '|+z\\rangle': 'l2-vector-space',
    '|-z\\rangle': 'l2-vector-space',
    '|+x\\rangle': 'l2-vector-space',
    '|-x\\rangle': 'l2-vector-space',
    '|\\psi\\rangle': 'l2-vector-space',
    '|A\\rangle': 'l2-vector-space:b2',
    '|B\\rangle': 'l2-vector-space:b2',
    '|C\\rangle': 'l2-vector-space.lecture',
    '|\\chi\\rangle': 'l2-inner-product:b2',
    a_1: 'l2-inner-product:b3',
    a_2: 'l2-inner-product:b3',
    b_1: 'l2-inner-product:b3',
    b_2: 'l2-inner-product:b3',
    '\\delta': 'l2-inner-product:b6',
    '\\varepsilon': 'l2-inner-product:b6',
    a: 'l2-complex:b4',
    b: 'l2-complex:b4',
    r: 'l2-complex:b4',
    e: 'l2-complex:b5',
    '\\pi': 'l2-complex:b5',
    c: 'l2-plus-y:b2',
    '|+y\\rangle': 'l2-plus-y:b2',
    '|-y\\rangle': 'l2-plus-y:b6',
    '\\hat m': 'l2-three-bases:b7',
    w: 'l2-complex.visual',
    u: 'l2-complex.play.l2-c-euler.hints[0]',
    '|a\\rangle': 'l2-three-bases.lecture',
    '|b\\rangle': 'l2-three-bases.lecture',
  },
  watch: [
    { source: '3b1b', where: 'Dot products and duality', adds: 'Why a dot product is secretly a row acting on a column: the same picture as a bra acting on a ket.', url: URL.b3('dot-products') },
    { source: '3b1b', where: 'Change of basis', adds: 'One vector, two sets of coordinates. This is the δ, ε calculation of Unit 2.2 with real numbers.', url: URL.b3('change-of-basis') },
    { source: 'mit805', where: 'Lecture 5', adds: 'Zwiebach sets out vector spaces over the complex numbers, with the same rules as the notes.', url: URL.mit805(5) },
  ],
  corrections: [
    {
      where: 'L2 p.5',
      says: 'Once a quarter turn is allowed, the real numbers are found off the number line.',
      shouldSay: 'It is the imaginary numbers that lie off the line, in the complex plane. Every real number sits on the line, at angle 0 or 180°; the [[imaginary-unit|imaginary unit]] $i$ sits at 90°.',
      check: () => close(V.l2TimesITurn, 90) && close(V.l2ISquared, -1),
    },
  ],
  units: [
    {
      id: 'l2-vector-space',
      story: L2_STORY['l2-vector-space'],
      review: L2_REVIEW['l2-vector-space'],
      title: 'Kets add and scale like vectors',
      question: 'Which rules let spin states add and scale like arrows, and what changes when the numbers may be complex?',
      lecture: {
        pages: 'L2 p. 1 – top of p. 2',
        summary:
          'A Hilbert space generalizes the flat geometry of 2D and 3D arrows to any number of dimensions. It is a vector space over the complex numbers with an inner product added; [[completeness]] comes free in finite dimensions. Seven [[axiom|axioms]] say that kets such as $|A\\rangle$, $|B\\rangle$ and $|C\\rangle$ add and scale, and that the space is [[closed]] under both. A zero ket and opposites exist. Every ket has a [[dual]] bra that obeys the same rules.',
        equations: ['|A\\rangle + |B\\rangle = |B\\rangle + |A\\rangle,\\qquad (|A\\rangle + |B\\rangle) + |C\\rangle = |A\\rangle + (|B\\rangle + |C\\rangle),\\qquad \\lambda(|A\\rangle + |B\\rangle) = \\lambda|A\\rangle + \\lambda|B\\rangle'],
      },
      books: [
        { source: 'susskind', where: '§1.9.1–1.9.3', adds: 'The axioms, columns of complex numbers as vectors, and bras and kets with the conjugation rule for a scaled ket.' },
        { source: 'townsend', where: '§1.3, pp. 10–12', adds: 'Kets as abstract vectors, written through components like an electric field; bras and the dual space appear in footnote 7 (p. 12).' },
        { source: 'axler', where: '§1B Def. 1.20', adds: 'The mathematician’s definition of a vector space, with the scalars allowed to be complex.' },
      ],
      visual: {
        kind: 'phase-dial',
        props: { theta: 0 },
        tryThis: [
          'Press the “multiply both” button, which multiplies both amplitudes by $i$. Both arrows turn together, but the dot stays put: a whole ket times a number of size 1 is the same state.',
          'Now drag the slider. The dot moves, because changing one amplitude **relative** to the other makes a new state.',
          'Stop the slider at 90°. Which named state is this? Unit 2.4 answers.',
        ],
      },
      clues: [],
      insight: 'Kets obey the rules of arrows, with one change: the numbers that scale them may be complex. Many vectors describe one physical state.',
      pitfalls: [
        'Thinking two kets can be multiplied into a ket. The rules only add kets and scale them by numbers.',
        'Writing the bra of $\\lambda|A\\rangle$ as $\\lambda\\langle A|$ instead of $\\lambda^*\\langle A|$.',
      ],
      play: [
        {
          id: 'l2-vs-rules',
          kind: 'choice',
          tier: 'warm-up',
          title: 'What the rules do not give',
          prompt: 'Which of these do the vector-space rules **not** give you?',
          options: [
            { text: '$|{+z}\\rangle + |{+x}\\rangle$ is a ket', correct: false, why: 'Rule 1: the sum of two kets is a ket.' },
            { text: '$i|{+x}\\rangle$ is a ket', correct: false, why: 'Rule 6: any ket times any number is a ket.' },
            { text: 'Two kets multiply to give a ket', correct: true, why: 'Right. No rule multiplies two kets. The inner product multiplies a **bra** by a ket, and it gives a number.' },
            { text: '$|A\\rangle + (-|A\\rangle)$ is the zero ket', correct: false, why: 'Rule 5: every ket has an opposite.' },
          ],
          hints: [
            { text: 'The seven rules talk about only two operations.' },
            { text: 'They are adding kets and scaling a ket by a number.' },
            { text: 'Check which option uses neither operation.' },
          ],
          walkthrough: [
            { text: 'Map each true option to its rule: a sum is rule 1, scaling is rule 6, and the opposite is rule 5.' },
            { text: 'No rule multiplies two kets. The inner product multiplies a bra by a ket, and the result is a number, not a ket.' },
          ],
        },
        {
          id: 'l2-vs-sum-prob',
          kind: 'numeric',
          tier: 'core',
          title: 'Add, rescale, measure',
          prompt: 'Add $|{+z}\\rangle$ and $|{+x}\\rangle$, then rescale to length 1. What is the probability that this state reads + along $z$?',
          answer: V.l2VsSumProb,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Write both as columns and add them.' },
            { text: 'The probability is the squared first entry after rescaling.' },
            { text: 'The sum is $(1 + \\tfrac{1}{\\sqrt2}, \\tfrac{1}{\\sqrt2})$, with squared length $2 + \\sqrt2$.' },
          ],
          walkthrough: [
            { text: 'The sum is the column $(1.707, 0.707)$.' },
            { text: 'Its squared length is $2.914 + 0.5 = 3.414$.' },
            { text: `So the [[probability]] is $P(+z) = 2.914/3.414 = ${d(V.l2VsSumProb)}$.` },
            { text: 'Callback: this is $\\cos^2 22.5^\\circ$, the Lecture 1 value for a 45° magnet. The rescaled sum sits halfway between $z$ and $x$.' },
          ],
        },
        {
          id: 'l2-vs-bra-scale',
          kind: 'choice',
          tier: 'core',
          title: 'The bra of a scaled ket',
          prompt: 'What is the bra of $(2 + i)|{+z}\\rangle$?',
          options: [
            { text: '$(2+i)\\langle{+z}|$', correct: false, why: 'The number does not cross over unchanged: it is conjugated.' },
            { text: '$(2-i)\\langle{+z}|$', correct: true, why: 'Right. The bra of $\\lambda|A\\rangle$ is $\\lambda^*\\langle A|$, and $(2+i)^* = 2 - i$.' },
            { text: '$\\langle{+z}|$', correct: false, why: 'The factor does not disappear; only its imaginary part changes sign.' },
            { text: '$(-2+i)\\langle{+z}|$', correct: false, why: 'Conjugation flips the sign of the imaginary part only, not the real part.' },
          ],
          hints: [
            { text: 'Kets and bras are partners, but numbers do not cross over unchanged.' },
            { text: 'The bra of $\\lambda|A\\rangle$ is $\\lambda^*\\langle A|$.' },
            { text: 'Flip the sign of the imaginary part of $2 + i$.' },
          ],
          walkthrough: [
            { text: 'Apply Susskind’s rule: conjugating $2 + i$ gives $2 - i$.' },
            { text: 'Check: applying that bra to $|{+z}\\rangle$ gives $2 - i$, and the engine agrees.' },
          ],
        },
        {
          id: 'l2-vs-real-closed',
          kind: 'choice',
          tier: 'stretch',
          title: 'Real columns only?',
          prompt: 'Keep only kets whose two components are real. Is that set a vector space when the scaling numbers may be complex?',
          options: [
            { text: 'Yes, sums of real columns are real', correct: false, why: 'Sums are fine, but scaling must also stay inside the set.' },
            { text: 'No: $i|{+z}\\rangle = (i, 0)$ is not in the set', correct: true, why: 'Right. One complex scaling already leaves the set, so it is not closed.' },
            { text: 'No, because sums can be complex', correct: false, why: 'A sum of real columns is real.' },
            { text: 'Yes, because the length stays 1', correct: false, why: 'Length is not one of the rules; closure under scaling is.' },
          ],
          hints: [
            { text: 'A vector space must be closed under every allowed operation.' },
            { text: 'Scaling must work for every allowed number $\\lambda$.' },
            { text: 'Try $\\lambda = i$ on $|{+z}\\rangle$.' },
          ],
          walkthrough: [
            { text: '$(i, 0)$ has a non-real entry, so the set is not closed under complex scaling.' },
            { text: 'It **is** a vector space over the real numbers. That is exactly the real Hilbert space that Unit 2.4 shows is too small for spin.' },
          ],
        },
      ],
    },
    {
      id: 'l2-inner-product',
      story: L2_STORY['l2-inner-product'],
      review: L2_REVIEW['l2-inner-product'],
      title: 'Overlap: the inner product gives coordinates',
      question: 'How does a bra times a ket measure overlap, and give a state’s coordinates in any basis?',
      lecture: {
        pages: 'L2 pp. 1–2, 7–8',
        summary:
          'The inner product turns a bra and a ket into one number. It is linear in the ket, conjugates when the two sides swap, and is never negative for a ket with itself. In columns, the bra is the conjugated row. States have length 1, and orthogonal states have overlap 0. Taking overlaps with the $x$ basis turns the $z$ coordinates α and β into new coordinates δ and ε.',
        equations: ['\\langle B|A\\rangle = b_1^*a_1 + b_2^*a_2,\\qquad \\delta = \\langle{+x}|\\psi\\rangle = \\tfrac{\\alpha+\\beta}{\\sqrt2},\\qquad \\varepsilon = \\langle{-x}|\\psi\\rangle = \\tfrac{\\alpha-\\beta}{\\sqrt2}'],
      },
      books: [
        { source: 'susskind', where: '§1.9.4–1.9.5, §2.2', adds: 'Inner products as a bra times a ket, [[orthonormal-basis|orthonormal bases]], and coordinates as overlaps.' },
        { source: 'townsend', where: '§1.3, pp. 12–13 (eqs. 1.6–1.15); Ex. 1.1, p. 14; §2.1, pp. 29–31', adds: 'The bra-ket as a number, with a worked complex example; later, the same thing as a row times a column.' },
        { source: 'axler', where: '§6A Def. 6.2, p. 183', adds: 'The mathematician’s inner product, linear in the first slot rather than the second. Same sizes, conjugate phases.' },
      ],
      visual: {
        kind: 'basis-translator',
        props: { target: 'x', mode: 'state', theta: 60, phi: 0 },
        tryThis: [
          'Set θ = 60°, φ = 0: this is the story’s ψ at 30°, because the widget doubles the angle. Read the $x$ column: about (0.966, 0.259). Square both entries and add.',
          'Set θ = 90° (the state $|{+x}\\rangle$). The $x$ column becomes (1, 0). What does a magnet along $x$ do to it?',
          'Set φ = 90°. The $x$ entries turn complex, but their squared sizes stay ½ and ½.',
        ],
      },
      clues: [],
      insight: 'Coordinates are overlaps: the inner product with each basis state reads off that coordinate. The length stays 1 in every basis.',
      pitfalls: [
        'Forgetting to conjugate the bra’s entries. For real columns it makes no difference, which is why the mistake hides until complex numbers appear.',
        'Adding the coordinates δ and ε instead of their squared sizes when asked for probabilities.',
      ],
      claims: [
        claim('l2Delta30', 'δ = 0.966 for ψ at 30° (Try it)', () => close(V.l2Delta30, 0.9659258262890683)),
        claim('l2Eps30', 'ε = 0.259 for ψ at 30° (Try it)', () => close(V.l2Eps30, 0.25881904510252074)),
      ],
      play: [
        {
          id: 'l2-ip-overlap',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Row times column',
          prompt: 'Compute $\\langle{+x}|{+z}\\rangle$.',
          answer: V.l2IpOverlap,
          tolerance: 0.005,
          hints: [
            { text: 'Turn the bra into a row.' },
            { text: 'Conjugating real entries changes nothing, so the row is $(\\tfrac{1}{\\sqrt2}, \\tfrac{1}{\\sqrt2})$.' },
            { text: 'Multiply it with the column $(1, 0)$.' },
          ],
          walkthrough: [{ text: `$\\tfrac{1}{\\sqrt2}\\cdot 1 + \\tfrac{1}{\\sqrt2}\\cdot 0 = ${d(V.l2IpOverlap)}$.` }],
        },
        {
          id: 'l2-ip-right-left',
          kind: 'numeric',
          tier: 'core',
          title: 'Left from up and down',
          prompt: 'Start from $|{\\pm z}\\rangle = (|{+x}\\rangle \\pm |{-x}\\rangle)/\\sqrt2$ and solve for $|{-x}\\rangle$ in terms of $|{\\pm z}\\rangle$. What is the coefficient of $|{-z}\\rangle$?',
          answer: V.l2IpRightLeft,
          tolerance: 0.005,
          hints: [
            { text: 'You have two equations and two unknowns.' },
            { text: 'Subtract the second equation from the first.' },
            { text: '$|{+z}\\rangle - |{-z}\\rangle = \\tfrac{2}{\\sqrt2}|{-x}\\rangle$.' },
          ],
          walkthrough: [
            { text: 'Subtracting gives $|{+z}\\rangle - |{-z}\\rangle = \\sqrt2\\,|{-x}\\rangle$.' },
            { text: `Dividing by $\\sqrt2$: $|{-x}\\rangle = (|{+z}\\rangle - |{-z}\\rangle)/\\sqrt2$, so the coefficient is $-1/\\sqrt2 = -${d(-V.l2IpRightLeft)}$. This is Lecture 1’s formula again.` },
            { text: 'Adding the equations instead gives $|{+x}\\rangle$.' },
          ],
        },
        {
          id: 'l2-ip-townsend',
          kind: 'numeric',
          tier: 'core',
          title: 'Townsend’s first example',
          prompt: '$|\\psi\\rangle = \\tfrac12|{+z}\\rangle + \\tfrac{\\sqrt3}{2}i|{-z}\\rangle$. What is the probability that a measurement along $z$ gives the − outcome?',
          answer: V.l2IpTownsend,
          tolerance: 0.005,
          unit: 'probability',
          refs: [{ source: 'townsend', where: '§1.3, Ex. 1.1, p. 14', adds: 'The same state and both probabilities.' }],
          hints: [
            { text: 'The amplitude you need is $\\beta = \\langle{-z}|\\psi\\rangle$.' },
            { text: 'The probability is $|\\beta|^2 = \\beta^*\\beta$.' },
            { text: '$(-\\tfrac{\\sqrt3}{2}i)(\\tfrac{\\sqrt3}{2}i) = \\tfrac34$.' },
          ],
          walkthrough: [
            { text: `$\\beta = \\tfrac{\\sqrt3}{2}i$, so $|\\beta|^2 = \\beta^*\\beta = ${d(V.l2IpTownsend, 2)}$.` },
            { text: `Check: $${d(V.l2IpTownsendPlus, 2)} + ${d(V.l2IpTownsend, 2)} = 1$.` },
            { text: 'Trap: squaring $\\beta$ without the conjugate gives $-\\tfrac34$, which is not a probability.' },
          ],
        },
        {
          id: 'l2-ip-delta',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The x probability of a tilted state',
          prompt: '$|\\psi\\rangle = \\cos 30^\\circ|{+z}\\rangle + \\sin 30^\\circ|{-z}\\rangle$. What is the probability that it reads + along $x$, that is, $|\\delta|^2$?',
          answer: V.l2DeltaSq,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'δ is the $|{+x}\\rangle$ coordinate.' },
            { text: '$\\delta = \\langle{+x}|\\psi\\rangle = (\\alpha + \\beta)/\\sqrt2$.' },
            { text: 'Use $\\alpha = 0.866$ and $\\beta = 0.5$.' },
          ],
          walkthrough: [
            { text: `$\\delta = 1.366/1.414 = ${d(V.l2Delta30)}$, so $|\\delta|^2 = ${d(V.l2DeltaSq)}$.` },
            { text: `Cross-check with Lecture 1: this is the + state of a magnet 60° from $z$, which is 30° from $x$. That gives $\\cos^2 15^\\circ = ${d(V.l2IpDeltaL1)}$.` },
          ],
        },
      ],
    },
    {
      id: 'l2-complex',
      story: L2_STORY['l2-complex'],
      review: L2_REVIEW['l2-complex'],
      title: 'Numbers that turn',
      question: 'Why do the real numbers run out, and what does multiplying by $i$ do?',
      lecture: {
        pages: 'L2 pp. 2–7',
        summary:
          'Each new operation forced new numbers: [[integer|integers]] for subtraction, [[rational-number|fractions]] for division, and [[irrational-number|irrational numbers]] such as $\\sqrt2$ for lengths. Square roots of negatives need a new direction. Multiplying by $-1$ is a half turn, so $i$ is a quarter turn off the line. A complex number has a real and an imaginary part, or a size and a phase. Euler’s formula links the two forms, and the conjugate mirrors a number in the real axis.',
        equations: ['z = a + ib = r(\\cos\\varphi + i\\sin\\varphi) = re^{i\\varphi},\\qquad z^* = a - ib,\\qquad z^*z = r^2'],
      },
      books: [
        { source: 'susskind', where: '§1.8', adds: 'Complex numbers in components and in polar form; multiply by multiplying sizes and adding phases.' },
        { source: 'townsend', where: '§1.4, footnote 8, p. 15', adds: 'The polar form and $z^*z = r^2$, in two lines.' },
      ],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'multiply', z: [1, 1], w: [0, 1] },
        tryThis: [
          'Keep the multiplier $w$ at $i$ and watch $z = 1 + i$ turn 90° to $-1 + i$. Its size stays $\\sqrt2$.',
          'Switch to “powers of i” and press “Multiply by i” four times. Where do you end up?',
          'Switch to “conjugate” and drag $z$. Watch $z^*$ mirror it in the real axis, and read $z^*z$.',
        ],
      },
      clues: [],
      insight: 'A complex number is a turn and a stretch. Multiplying by $i$ turns a quarter, and numbers of size 1 only turn.',
      pitfalls: ['Computing $|z|^2$ as $z^2$. The size squared is $z^*z$, which is always real and never negative.'],
      play: [
        {
          id: 'l2-c-modulus',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Size of a complex number',
          prompt: 'What is $|3 - 4i|$?',
          answer: V.l2CModulus,
          tolerance: 0.001,
          hints: [
            { text: 'Size means distance from 0.' },
            { text: 'Use $\\sqrt{a^2 + b^2}$.' },
            { text: '$9 + 16 = 25$.' },
          ],
          walkthrough: [{ text: `$\\sqrt{25} = ${d(V.l2CModulus, 0)}$. The sign of $b$ does not matter.` }],
        },
        {
          id: 'l2-c-turn',
          kind: 'numeric',
          tier: 'core',
          title: 'Turn by i',
          prompt: 'Multiply $1 + i$ by $i$. What is the phase of the result, in degrees between 0 and 360?',
          answer: V.l2CTurn,
          tolerance: 0.5,
          unit: 'degrees',
          hints: [
            { text: 'Multiplying adds phases.' },
            { text: '$1 + i$ has phase 45°, and $i$ has phase 90°.' },
            { text: 'Or expand $i(1+i)$ using $i^2 = -1$.' },
          ],
          walkthrough: [
            { text: `$45^\\circ + 90^\\circ = ${d(V.l2CTurn, 0)}^\\circ$.` },
            { text: 'Check: $i + i^2 = -1 + i$, which lies in the upper-left quadrant.' },
          ],
        },
        {
          id: 'l2-c-sqrt',
          kind: 'choice',
          tier: 'core',
          title: 'Square root of −2',
          prompt: '$\\sqrt{-2}$ = ?',
          options: [
            { text: '$-\\sqrt2$', correct: false, why: '$(-\\sqrt2)^2 = +2$, not $-2$.' },
            { text: '$\\sqrt2\\,i$', correct: true, why: `Right: $(\\sqrt2\\,i)^2 = 2i^2 = -2$, and $\\sqrt2 = ${d(V.l2CSqrt)}$.` },
            { text: '$2i$', correct: false, why: '$(2i)^2 = -4$.' },
            { text: 'Not a number at all', correct: false, why: 'It is not a **real** number, but it is a complex one.' },
          ],
          hints: [
            { text: 'Split off $\\sqrt{-1}$.' },
            { text: '$\\sqrt{-2} = \\sqrt2\\cdot\\sqrt{-1}$.' },
            { text: '$\\sqrt{-1} = i$.' },
          ],
          walkthrough: [
            { text: '$(\\sqrt2\\,i)^2 = 2i^2 = -2$.' },
            { text: 'Note that $-\\sqrt2$ squares to $+2$.' },
          ],
        },
        {
          id: 'l2-c-euler',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Euler’s formula (homework)',
          assigned: 'L2 p.7',
          prompt: 'Homework: show that $\\cos\\varphi + i\\sin\\varphi = e^{i\\varphi}$, treating $i$ as an unknown with $i^2 = -1$. Then check your result: what real number is $e^{i\\pi}$?',
          answer: V.l2EulerPi,
          tolerance: 0.001,
          hints: [
            { text: 'For a number $u$, what infinite sum defines $e^{u}$?' },
            { text: 'Put $u = i\\varphi$ and simplify each power of $i$ using $i^2 = -1$.' },
            { text: 'Collect the terms with no $i$ and the terms with one $i$, and compare each group with a series you know.' },
          ],
          // assigned: hints only, and no walkthrough ships in the bundle (content test)
          walkthrough: [],
        },
      ],
    },
    {
      id: 'l2-plus-y',
      story: L2_STORY['l2-plus-y'],
      review: L2_REVIEW['l2-plus-y'],
      title: 'Real numbers cannot make +y',
      question: 'Which state reads + along $y$, and why must its amplitudes be complex?',
      lecture: {
        pages: 'L2 pp. 8–9',
        summary:
          'A spin prepared along $+y$ splits 50/50 along $z$ and along $x$. Trying $(|{+z}\\rangle + c|{-z}\\rangle)/\\sqrt2$, the $z$ test forces $|c| = 1$. The $x$ test then forces $c + c^* = 0$, so $c^2 = -1$. No real number works; $c = \\pm i$ gives the pair $|{\\pm y}\\rangle$.',
        equations: ['|{\\pm y}\\rangle = \\tfrac{1}{\\sqrt2}\\big(|{+z}\\rangle \\pm i|{-z}\\rangle\\big)'],
      },
      books: [
        { source: 'townsend', where: '§1.5, pp. 18–20 (Experiment 5, eqs. 1.23–1.31, Fig. 1.10); Ex. 1.3, pp. 20–21; §2.1, pp. 31–32', adds: 'The same derivation from an SG$_y$ experiment, why right-handed axes pick $+i$, and a worked example along $y$.' },
        { source: 'susskind', where: '§2.3–2.4 (Ex. 2.2, 2.3)', adds: 'His in and out states are our $|{\\pm y}\\rangle$, found by the same two 50/50 conditions.' },
      ],
      visual: {
        kind: 'real-vs-complex',
        props: { realOnly: true, angle: 0 },
        tryThis: [
          'With “only real numbers allowed” ticked, flip $c$ between +1 and −1. The $z$ split stays 50/50, but the $x$ split is 100/0 or 0/100.',
          'Untick it and drag $c$ round the circle. Where exactly is the $x$ split 50/50?',
          'Watch the top view on the right. Where does the state sit at $c = i$, and where at $c = -i$?',
        ],
      },
      clues: [],
      insight: 'Two fair coin tosses, along $z$ and along $x$, leave no room for a real coefficient. The third direction in space needs the number $i$.',
      pitfalls: ['Believing the $z$ test alone fixes $|{+y}\\rangle$. It only fixes the size of $c$; the $x$ test fixes its phase.'],
      claims: [
        claim('l2YOnZ', '+y splits 50/50 along z (Try it)', () => close(V.l2YOnZ, 0.5)),
        claim('l2RealFailPlus', 'c = 1 gives 100/0 along x (Try it)', () => close(V.l2RealFailPlus, 1)),
      ],
      play: [
        {
          id: 'l2-y-zsplit',
          kind: 'numeric',
          tier: 'warm-up',
          title: '+y meets a z magnet',
          prompt: 'A spin in $|{+y}\\rangle$ meets a magnet along $z$. What is the probability of +?',
          answer: V.l2YZsplit,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Read off α.' },
            { text: '$\\alpha = 1/\\sqrt2$.' },
            { text: 'Square its size.' },
          ],
          walkthrough: [{ text: `$|1/\\sqrt2|^2 = ${d(V.l2YZsplit, 1)}$. The $i$ sits on the other amplitude and changes only its phase.` }],
        },
        {
          id: 'l2-y-why-complex',
          kind: 'choice',
          tier: 'core',
          title: 'Why not a real c?',
          prompt: 'Why can’t $c$ in $(|{+z}\\rangle + c|{-z}\\rangle)/\\sqrt2$ be real for $|{+y}\\rangle$?',
          options: [
            { text: 'A real $c$ cannot be [[normalized]]', correct: false, why: 'Any $c$ can be normalized; $|c| = 1$ already gives length 1.' },
            { text: 'A real $c = \\pm1$ gives $|{\\pm x}\\rangle$, which reads 100 % or 0 % along $x$, not 50/50', correct: true, why: 'Right. The $z$ test passes for any $|c| = 1$; only the $x$ test fails.' },
            { text: 'A real $c$ makes the $z$ split unequal', correct: false, why: 'With $|c| = 1$ the $z$ split is 50/50 whether $c$ is real or not.' },
            { text: 'The axioms forbid real coefficients', correct: false, why: 'Real numbers are allowed; they are just not enough.' },
          ],
          hints: [
            { text: 'Which real values does $|c| = 1$ allow?' },
            { text: 'Name the states they make.' },
            { text: 'Measure those states along $x$.' },
          ],
          walkthrough: [
            { text: 'A real $c$ with $|c| = 1$ is $+1$ or $-1$, giving $|{+x}\\rangle$ or $|{-x}\\rangle$.' },
            { text: `Along $x$ those read + with probability ${d(V.l2RealFailPlus, 0)} or ${d(V.l2RealFailMinus, 0)}, never one half.` },
          ],
        },
        {
          id: 'l2-y-townsend',
          kind: 'numeric',
          tier: 'core',
          title: 'Townsend’s y-spin example',
          prompt: '$|\\psi\\rangle = \\tfrac12|{+z}\\rangle + \\tfrac{\\sqrt3}{2}i|{-z}\\rangle$. What is the probability that a measurement along $y$ gives +?',
          answer: V.l2YTownsend,
          tolerance: 0.005,
          unit: 'probability',
          refs: [{ source: 'townsend', where: '§1.5, Ex. 1.3, pp. 20–21', adds: 'The same state, with the $y$ probabilities and the average.' }],
          hints: [
            { text: 'Write the bra $\\langle{+y}|$, conjugating.' },
            { text: '$\\langle{+y}| = (1, -i)/\\sqrt2$.' },
            { text: '$\\langle{+y}|\\psi\\rangle = \\tfrac{1}{\\sqrt2}\\cdot\\tfrac12 + \\tfrac{-i}{\\sqrt2}\\cdot\\tfrac{\\sqrt3}{2}i$.' },
          ],
          walkthrough: [
            { text: '$-i\\cdot i = +1$, so the amplitude is $\\tfrac{1}{\\sqrt2}\\big(\\tfrac12 + \\tfrac{\\sqrt3}{2}\\big)$.' },
            { text: `Squared: $\\tfrac12 + \\tfrac{\\sqrt3}{4} = ${d(V.l2YTownsend)}$.` },
            { text: `Townsend also gives the average $y$ reading, $\\tfrac{\\sqrt3}{4}$ in units of ħ, which is ${d(V.l2SyTownsend)}.` },
          ],
        },
        {
          id: 'l2-y-35',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A 3–4–5 state along y',
          prompt: '$|\\psi\\rangle = \\tfrac35|{+z}\\rangle + \\tfrac45 i|{-z}\\rangle$. What is the probability that a measurement along $y$ gives +?',
          answer: V.l2Y35,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Conjugate the bra.' },
            { text: 'Both terms of the amplitude come out real and positive.' },
            { text: 'The amplitude is $\\tfrac{1}{\\sqrt2}\\big(\\tfrac35 + \\tfrac45\\big)$.' },
          ],
          walkthrough: [
            { text: `The amplitude is $\\tfrac{7}{5\\sqrt2}$; squared, $\\tfrac{49}{50} = ${d(V.l2Y35, 2)}$.` },
            { text: `Bonus: along $x$ the probability of + is ${d(V.l2X35, 1)}. The state lies in the $y$–$z$ plane, at right angles to $x$.` },
          ],
        },
      ],
    },
    {
      id: 'l2-three-bases',
      story: L2_STORY['l2-three-bases'],
      review: L2_REVIEW['l2-three-bases'],
      title: 'Three bases, each blind to the others',
      question: 'How are the $z$, $x$ and $y$ bases related, and what kind of object is a spin state?',
      lecture: {
        pages: 'L2 pp. 10–11',
        summary:
          'As $c$ steps through $1, i, -1, -i$, the state steps through $+x, +y, -x, -y$. The three pairs are orthogonal bases, and any two of them are mutually unbiased: every cross measurement is 50/50. So a spin state is a unit vector in a complex space of [[dimension]] two. Overlaps between states $|a\\rangle$ and $|b\\rangle$ of different bases all have squared size ½. The notes preview a sphere with the six states at the ends of its three axes.',
        equations: ['|\\langle a|b\\rangle|^2 = \\tfrac12\\ \\ (a, b \\text{ from different bases}),\\qquad |\\psi\\rangle = \\alpha|{+z}\\rangle + \\beta|{-z}\\rangle,\\ \\ \\langle\\psi|\\psi\\rangle = 1'],
      },
      books: [
        { source: 'susskind', where: '§2.5, §2.7', adds: 'Counting parameters: two complex numbers, minus normalization and the overall phase, leave two real ones.' },
        { source: 'townsend', where: '§1.3, p. 11', adds: 'Two basis kets span the whole space of spin states.' },
      ],
      visual: {
        kind: 'bloch',
        props: { theta: 90, phi: 0, editable: true, landmarks: true, measure: 'y' },
        tryThis: [
          'Start at $|{+x}\\rangle$ with the magnet along $y$: 50/50. Press the $|{+y}\\rangle$ button: 100/0.',
          'Press $|{+z}\\rangle$, then $|{-z}\\rangle$: along $y$ both give 50/50 too.',
          'Look for a point that is 50/50 along $x$, $y$ and $z$ at once. Why is there none?',
        ],
      },
      clues: [],
      insight: 'Three directions in the lab give three bases that know nothing about each other. That is the most a spin ½ can hold.',
      pitfalls: ['Expecting a 45° tilted basis to be unbiased with $z$. Unbiased needs axes at right angles in the lab.'],
      claims: [
        claim('l2XOnY', '+x measured along y is 50/50 (Try it)', () => close(V.l2XOnY, 0.5)),
        claim('l2Perp5050', 'every equator state is 50/50 along z (Try it)', () => close(V.l2Perp5050, 0.5)),
      ],
      play: [
        {
          id: 'l2-mub-xy',
          kind: 'numeric',
          tier: 'warm-up',
          title: '+x measured along y',
          prompt: 'A spin in $|{+x}\\rangle$ is measured along $y$. What is the probability of +?',
          answer: V.l2XOnY,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Use the bra of $|{+y}\\rangle$.' },
            { text: 'The amplitude is $(1 - i)/2$.' },
            { text: 'Its squared size is $(1 + 1)/4$.' },
          ],
          walkthrough: [{ text: `$|1 - i|^2/4 = 2/4 = ${d(V.l2XOnY, 1)}$.` }],
        },
        {
          id: 'l2-mub-which',
          kind: 'choice',
          tier: 'core',
          title: 'Which pair is biased?',
          prompt: 'Which pair of bases is **not** mutually unbiased?',
          options: [
            { text: '$z$ and $x$', correct: false, why: 'The axes are at right angles: every cross probability is ½.' },
            { text: '$x$ and $y$', correct: false, why: 'The axes are at right angles: every cross probability is ½.' },
            { text: '$z$ and $y$', correct: false, why: 'The axes are at right angles: every cross probability is ½.' },
            { text: '$z$ and the basis of a magnet tilted 45° from $z$ toward $x$', correct: true, why: `Right. The cross probability is $\\cos^2 22.5^\\circ = ${d(V.l2MubWhich45)}$, not ½.` },
          ],
          hints: [
            { text: 'Unbiased means every cross probability is ½.' },
            { text: 'Use Lecture 1’s rule $P(+) = (1 + \\hat n\\cdot\\hat m)/2$.' },
            { text: 'Which pair of axes is not at 90°?' },
          ],
          walkthrough: [
            { text: 'The three coordinate pairs are at 90° in the lab, so each gives ½.' },
            { text: `The 45° pair gives $\\cos^2 22.5^\\circ = ${d(V.l2MubWhich45)}$.` },
          ],
        },
        {
          id: 'l2-mub-phase',
          kind: 'numeric',
          tier: 'core',
          title: 'Where −y sits',
          prompt: 'Write $|{-y}\\rangle = (|{+z}\\rangle + c|{-z}\\rangle)/\\sqrt2$ with $c = e^{i\\varphi}$. What is φ, in degrees between 0 and 360?',
          answer: V.l2MubPhase,
          tolerance: 0.5,
          unit: 'degrees',
          hints: [
            { text: 'Here $c = -i$.' },
            { text: 'Where does $-i$ sit on the unit circle?' },
            { text: 'Three quarter turns from 1.' },
          ],
          walkthrough: [
            { text: `$-i = e^{i\\,${d(V.l2MubPhase, 0)}^\\circ}$, and $-90^\\circ$ names the same point.` },
            { text: 'On the cycle $1 \\to i \\to -1 \\to -i$ it is the fourth stop.' },
          ],
        },
        {
          id: 'l2-mub-count',
          kind: 'numeric',
          tier: 'stretch',
          title: 'How many numbers make a state?',
          prompt: 'How many real numbers pin down a spin state, once normalization and the overall phase are used up?',
          answer: V.l2MubCount,
          tolerance: 0.001,
          refs: [{ source: 'susskind', where: '§2.5', adds: 'The same count.' }],
          hints: [
            { text: 'Count the real numbers in two complex amplitudes.' },
            { text: 'Normalization is one real equation.' },
            { text: 'An overall phase can be removed.' },
          ],
          walkthrough: [
            { text: `$4 - 1 - 1 = ${d(V.l2MubCount, 0)}$, the same as the number of angles that fix a direction in 3D.` },
            { text: 'This is why a sphere can hold every state: θ from $+z$, φ from $+x$ toward $+y$.' },
          ],
        },
      ],
    },
  ],
}
