import type { Lecture } from './schema'
import { URL } from './refs'
import { V, close, d } from './L3.values'
import { L3_STORY } from './L3.story'
import { L3_REVIEW } from './L3.review'

// Every number a learner sees in this lecture is computed in L3.values.ts, then asserted in keyed claims
// (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy). Plan: docs/roles/proposals/P-L3-story.md.
// Units 3.5 and 3.6 (notes pp. 14–17) belong to L3 by the ownership rule but were taught at the start of Lecture 4.

const L4_SLOT = 'taught at the start of Lecture 4'

export const L3: Lecture = {
  id: 'L3',
  number: 3,
  title: 'Quantum measurement',
  outcomes: [
    'Say what a linear operator does, and write its matrix in a basis, entry by entry.',
    'Check whether a vector is an eigenvector, read off its eigenvalue, and test whether a matrix is Hermitian.',
    'Build a projector, check that the projectors of a basis add up to the identity, and build an observable from its outcomes and their states.',
    'Given a state and an observable, list the possible results, their probabilities, and the state left after each.',
    'Explain why measuring a quantity is not the same as applying its operator.',
    'Compute an average and a spread, and say why an eigenstate has zero spread.',
  ],
  prerequisites: ['vectors', 'inner-product', 'complex-amplitudes'],
  // Symbols defined in the text itself (symbol → the unit, beat or site whose sentence defines it). Kets, bras, ħ and
  // i from Lectures 1–2 (the prerequisites) are mapped to the first unit's title: a recap, not a new definition.
  symbols: {
    '|\\cdot\\rangle': 'l3-operators',
    '\\langle\\cdot|': 'l3-operators',
    '\\langle\\cdot|\\cdot\\rangle': 'l3-operators',
    '|+z\\rangle': 'l3-operators',
    '|-z\\rangle': 'l3-operators',
    '|+x\\rangle': 'l3-operators',
    '|-x\\rangle': 'l3-operators',
    '|+y\\rangle': 'l3-operators',
    '|-y\\rangle': 'l3-operators',
    '|\\psi\\rangle': 'l3-operators',
    '\\hbar': 'l3-operators',
    i: 'l3-operators',
    'c_+': 'l3-operators:b2',
    'c_-': 'l3-operators:b2',
    'c_\\pm': 'l3-operators:b2',
    '|\\uparrow\\rangle': 'l3-operators:b2',
    '|\\downarrow\\rangle': 'l3-operators:b2',
    'c_\\uparrow': 'l3-operators:b2',
    'c_\\downarrow': 'l3-operators:b2',
    '\\hat A': 'l3-operators:b2',
    '|\\phi\\rangle': 'l3-operators:b2',
    c_1: 'l3-operators:b2',
    c_2: 'l3-operators:b2',
    '|\\psi_1\\rangle': 'l3-operators:b2',
    '|\\psi_2\\rangle': 'l3-operators:b2',
    '|\\phi_+\\rangle': 'l3-operators:b3',
    '|\\phi_-\\rangle': 'l3-operators:b3',
    A: 'l3-operators:b4',
    A_ij: 'l3-operators:b4',
    '|i\\rangle': 'l3-operators:b4',
    '|j\\rangle': 'l3-operators:b4',
    j: 'l3-operators:b4',
    '\\hat B': 'l3-operators.play.l3-op-columns',
    B: 'l3-operators.play.l3-op-columns',
    B_ij: 'l3-operators.play.l3-op-columns',
    B_21: 'l3-operators.play.l3-op-columns',
    M: 'l3-eigen:b1',
    '|a\\rangle': 'l3-eigen:b1',
    a: 'l3-eigen:b1',
    S_z: 'l3-eigen:b2',
    '\\hat S_z': 'l3-eigen:b2',
    H: 'l3-eigen:b3',
    A_ji: 'l3-eigen:b6',
    H_12: 'l3-eigen:b6',
    H_21: 'l3-eigen:b6',
    '\\hat R': 'l3-eigen:b7',
    R: 'l3-eigen:b7',
    '\\lambda': 'l3-eigen.play.l3-eig-sz',
    A_21: 'l3-eigen.play.l3-eig-hermitian',
    A_12: 'l3-eigen.play.l3-eig-hermitian',
    '\\hat H': 'l3-eigen.play.l3-eig-real',
    '\\hat P_+z': 'l3-projectors:b1',
    'P_\\uparrow': 'l3-projectors:b1',
    '|\\psi_60\\rangle': 'l3-projectors:b1',
    '\\hat P_-z': 'l3-projectors:b3',
    '|a_i\\rangle': 'l3-projectors:b3',
    c_i: 'l3-projectors:b3',
    'c_+x': 'l3-projectors:b3',
    'c_-x': 'l3-projectors:b3',
    a_i: 'l3-projectors:b4',
    a_j: 'l3-projectors:b4',
    '|a_j\\rangle': 'l3-projectors:b4',
    '\\hat P_+x': 'l3-projectors.pitfalls[1]',
    '\\hat P_\\psi': 'l3-projectors.play.l3-proj-matrix',
    P: 'l3-postulates:b2',
    '\\hat P_i': 'l3-postulates:b2',
    '|a_1\\rangle': 'l3-postulates:b5',
    '|a_2\\rangle': 'l3-postulates:b5',
    a_1: 'l3-postulates:b5',
    a_2: 'l3-postulates:b5',
    '\\hat\\sigma_z': 'l3-postulates:b6',
    '\\sigma_z': 'l3-postulates:b6',
    '|r\\rangle': 'l3-postulates:b6',
    '|l\\rangle': 'l3-postulates:b6',
    S_x: 'l3-spin-example:b3',
    '\\hat S_x': 'l3-spin-example:b6',
    '\\theta': 'l3-spin-example.play.l3-ex-tilt',
  },
  watch: [
    { source: '3b1b', where: 'Linear transformations and matrices', adds: 'A matrix as a record of where the basis vectors land: the columns rule of Unit 3.1, with real pictures.', url: URL.b3('linear-transformations') },
    { source: '3b1b', where: 'Eigenvectors and eigenvalues', adds: 'Vectors that stay on their own line while everything else turns: the picture behind Unit 3.2.', url: URL.b3('eigenvalues') },
    { source: 'mit805', where: 'Lecture 4', adds: 'Zwiebach on spin one-half, bras, kets and operators: the same objects, told from a different angle.', url: URL.mit805(4) },
  ],
  corrections: [
    {
      source: 'book',
      where: 'Townsend §1.4, Example 1.2, p. 17',
      says: 'For the state ½|+z⟩ + (i√3/2)|−z⟩, the worked example ends by giving a spin-up result, +ħ/2, a 75 % chance.',
      shouldSay:
        'The chance of +ħ/2 is |½|² = 25 %; the 75 % belongs to −ħ/2. The example’s own average, −ħ/4, already weights −ħ/2 by ¾, and its spread of about 0.43ħ is right (Unit 3.6).',
      check: () => close(V.l3TownsendUp, 0.25) && close(V.l3TownsendDown, 0.75) && close(V.l3TownsendMean, -0.25) && close(V.l3TownsendSpread, Math.sqrt(3) / 4),
    },
  ],
  units: [
    {
      id: 'l3-operators',
      story: L3_STORY['l3-operators'],
      review: L3_REVIEW['l3-operators'],
      title: 'Operators: machines that turn states into states',
      question: 'What is a linear operator, and how does a basis turn it into a matrix?',
      lecture: {
        pages: 'L3 pp. 1–4',
        summary:
          'A measurement gives one definite reading even when the state is a superposition, so the theory needs new tools. A linear operator $\\hat A$ turns each state vector into another, $\\hat A|\\psi\\rangle = |\\phi\\rangle$, and passes through sums and multiples. Its action on the two basis states fixes it everywhere. In a chosen basis a state is a column and the operator is a matrix $A$, written without the hat, with entries $A_{ij} = \\langle i|\\hat A|j\\rangle$.',
        equations: ['\\hat A|\\psi\\rangle = |\\phi\\rangle,\\qquad A_{ij} = \\langle i|\\hat A|j\\rangle'],
      },
      books: [
        { source: 'susskind', where: '§3.1.1', adds: 'Operators as machines, the three rules that make them linear, and their matrices in a basis.' },
        { source: 'townsend', where: '§2.2, pp. 34–35; §2.1, pp. 29–30; §2.4, pp. 46–47', adds: 'A rotation as an operator that changes the physical state, kets written as columns, and an operator acting on a ket as a matrix times a column.' },
      ],
      visual: {
        kind: 'operator-action',
        props: { preset: 'σx' },
        caption: 'The swap is the preset σx here; Lecture 4 gives it that name.',
        tryThis: [
          'Drag the arrow slowly. Its image is always its mirror across the 45° line.',
          'Put the arrow on $|{+z}\\rangle$, pointing right. Compare its image with the first column of the matrix.',
          'Set the three sliders to 1, 0 and −1, which makes the diagonal matrix with entries 1 and −1. Which arrows flip, and which stay put?',
        ],
      },
      clues: [],
      insight: 'An operator is a rule that turns states into states. Once a basis is chosen, it becomes a matrix whose columns are the images of the basis states.',
      pitfalls: [
        'Writing the images of the basis states as rows. Column $j$ holds $\\hat A|j\\rangle$; the rows give the transpose.',
        'Calling $\\hat A$ a measurement device. It is a rule acting on states; what a measurement does comes in Unit 3.4.',
      ],
      play: [
        {
          id: 'l3-op-swap',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Swap the parts',
          prompt: 'The swap operator $A = \\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$ acts on $|\\psi\\rangle = 0.6|{+z}\\rangle + 0.8|{-z}\\rangle$. What is the $|{+z}\\rangle$ amplitude of $\\hat A|\\psi\\rangle$?',
          answer: V.l3ChSwap,
          tolerance: 0.005,
          hints: [
            { text: 'Where does the swap send each basis state?' },
            { text: 'By linearity, $\\hat A|\\psi\\rangle = 0.6\\,\\hat A|{+z}\\rangle + 0.8\\,\\hat A|{-z}\\rangle$.' },
            { text: 'Substitute $\\hat A|{+z}\\rangle = |{-z}\\rangle$ and $\\hat A|{-z}\\rangle = |{+z}\\rangle$, then read the $|{+z}\\rangle$ coefficient.' },
          ],
          walkthrough: [
            { text: `$\\hat A|\\psi\\rangle = 0.6|{-z}\\rangle + 0.8|{+z}\\rangle$, so the $|{+z}\\rangle$ amplitude is ${d(V.l3ChSwap, 1)}.` },
            { text: 'As columns: $\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}\\begin{pmatrix}0.6\\\\0.8\\end{pmatrix} = \\begin{pmatrix}0.8\\\\0.6\\end{pmatrix}$, the same answer.' },
          ],
        },
        {
          id: 'l3-op-columns',
          kind: 'choice',
          tier: 'core',
          title: 'Images are columns',
          prompt: 'An operator $\\hat B$ does $\\hat B|{+z}\\rangle = |{+z}\\rangle + 2|{-z}\\rangle$ and $\\hat B|{-z}\\rangle = 3|{-z}\\rangle$. Which matrix $B$ represents it in the $z$ basis?',
          options: [
            { text: '$\\begin{pmatrix}1&0\\\\2&3\\end{pmatrix}$', correct: true, why: 'Right. Column $j$ is the image of basis state $j$: column 1 is $(1, 2)$ and column 2 is $(0, 3)$.' },
            { text: '$\\begin{pmatrix}1&2\\\\0&3\\end{pmatrix}$', correct: false, why: 'These are the images written as rows: the transpose.' },
            { text: '$\\begin{pmatrix}1&0\\\\0&3\\end{pmatrix}$', correct: false, why: 'This drops the $2|{-z}\\rangle$ part of the first image.' },
            { text: '$\\begin{pmatrix}3&0\\\\2&1\\end{pmatrix}$', correct: false, why: 'The basis order is swapped: row 1 and column 1 belong to $|{+z}\\rangle$.' },
          ],
          hints: [
            { text: '$B_{ij} = \\langle i|\\hat B|j\\rangle$. Which index says which basis state went in?' },
            { text: 'Column $j$ holds the components of $\\hat B|j\\rangle$.' },
            { text: 'Write $\\hat B|{+z}\\rangle$ as a column and put it first.' },
          ],
          walkthrough: [
            { text: '$\\hat B|{+z}\\rangle$ is the column $(1, 2)$: that is column 1.' },
            { text: '$\\hat B|{-z}\\rangle$ is the column $(0, 3)$: that is column 2.' },
            { text: `So $B = \\begin{pmatrix}1&0\\\\2&3\\end{pmatrix}$. Check: $B_{21} = \\langle{-z}|\\hat B|{+z}\\rangle = ${d(V.l3ChB21, 0)}$.` },
          ],
        },
        {
          id: 'l3-op-linear',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Linearity does the work',
          prompt: 'Use the same $\\hat B$. What is the $|{-z}\\rangle$ component of $\\hat B|{+x}\\rangle$?',
          answer: V.l3ChBx,
          tolerance: 0.005,
          hints: [
            { text: 'You need no new rule for $|{+x}\\rangle$.' },
            { text: 'Write $|{+x}\\rangle = \\tfrac{1}{\\sqrt2}(|{+z}\\rangle + |{-z}\\rangle)$ and use linearity.' },
            { text: 'The answer is $\\tfrac{1}{\\sqrt2}(2 + 3)$.' },
          ],
          walkthrough: [
            { text: 'By linearity, $\\hat B|{+x}\\rangle = \\tfrac{1}{\\sqrt2}(\\hat B|{+z}\\rangle + \\hat B|{-z}\\rangle) = \\tfrac{1}{\\sqrt2}(|{+z}\\rangle + 5|{-z}\\rangle)$.' },
            { text: `So the component is $5/\\sqrt2 \\approx ${d(V.l3ChBx)}$.` },
            { text: 'This is not a probability. $\\hat B$ is not a measurement, and its output need not have length 1.' },
          ],
        },
      ],
    },
    {
      id: 'l3-eigen',
      story: L3_STORY['l3-eigen'],
      review: L3_REVIEW['l3-eigen'],
      title: 'Directions an operator only stretches',
      question: 'Which states does an operator leave on their own line, and why must an observable be Hermitian?',
      lecture: {
        pages: 'L3 pp. 4–8',
        summary:
          'Most vectors come out of an operator pointing somewhere new; an eigenvector $|a\\rangle$ is only rescaled, by its eigenvalue $a$. The spin matrix $S_z$ has eigenvectors $|{\\pm z}\\rangle$ with eigenvalues $\\pm\\tfrac{\\hbar}{2}$, exactly the beams and readings of an SG$_z$ magnet. An operator equal to its Hermitian conjugate is Hermitian. Its eigenvalues are real, a fact the notes leave as homework, and its eigenvectors can form an orthonormal basis. A theory of measurement must then say which results occur, with what odds, and what state is left.',
        equations: ['\\hat A|a\\rangle = a|a\\rangle,\\qquad \\hat A^\\dagger = \\hat A,\\qquad (A^\\dagger)_{ij} = A_{ji}^*'],
      },
      books: [
        { source: 'susskind', where: '§3.1.2–3.1.5', adds: 'Eigenvectors and eigenvalues, the Hermitian conjugate, a short proof that Hermitian eigenvalues are real, and the orthonormal eigenbasis.' },
        { source: 'townsend', where: '§2.2, pp. 36–37; §2.4, p. 50', adds: 'Hermitian operators and the eigenstates of rotations; the adjoint of a matrix as its transpose conjugate.' },
      ],
      visual: {
        kind: 'operator-action',
        props: { preset: '[[2,1],[1,2]]' },
        tryThis: [
          'Drag until the readout says the arrow is an eigenvector. There are exactly two such directions, at right angles.',
          'Read the two stretch factors, 3 and 1, then tick “show eigen-directions” to check.',
          'Move the third slider, the bottom-right entry, from 2 to 1. The eigen-directions move. Are they still at right angles? (Yes: the matrix is still symmetric, so still Hermitian.)',
        ],
      },
      clues: [],
      insight: 'Eigenvectors are the directions an operator leaves on their own line. For a Hermitian operator their eigenvalues are real, the possible readings, and the eigenvectors form an orthonormal basis.',
      pitfalls: [
        'Thinking every operator could be an observable. A quarter turn has eigenvalues $\\pm i$, which no meter can show.',
        'Conjugating without transposing, or transposing without conjugating. The Hermitian conjugate needs both.',
      ],
      play: [
        {
          id: 'l3-eig-sz',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The down eigenvalue',
          prompt: '$\\hat S_z|{-z}\\rangle = \\lambda|{-z}\\rangle$. What is $\\lambda$?',
          answer: V.l3ChSzDown,
          tolerance: 0.005,
          unit: 'ħ',
          hints: [
            { text: 'Multiply the matrix by the column $\\begin{pmatrix}0\\\\1\\end{pmatrix}$.' },
            { text: '$S_z = \\tfrac{\\hbar}{2}\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}$.' },
            { text: 'The result is a multiple of $\\begin{pmatrix}0\\\\1\\end{pmatrix}$. Which multiple?' },
          ],
          walkthrough: [
            { text: '$S_z\\begin{pmatrix}0\\\\1\\end{pmatrix} = \\tfrac{\\hbar}{2}\\begin{pmatrix}0\\\\-1\\end{pmatrix} = -\\tfrac{\\hbar}{2}\\begin{pmatrix}0\\\\1\\end{pmatrix}$.' },
            { text: `So $\\lambda = -\\tfrac{\\hbar}{2}$, or −${d(-V.l3ChSzDown, 1)} in units of ħ: the down reading of an SG$_z$ magnet.` },
          ],
        },
        {
          id: 'l3-eig-which',
          kind: 'choice',
          tier: 'core',
          title: 'Which one stays put?',
          prompt: 'Which state is an eigenvector of $M = \\begin{pmatrix}2&1\\\\1&2\\end{pmatrix}$?',
          options: [
            { text: '$|{-x}\\rangle$', correct: true, why: 'Right. $M|{-x}\\rangle = |{-x}\\rangle$: eigenvalue 1.' },
            { text: '$|{+z}\\rangle$', correct: false, why: '$M|{+z}\\rangle = (2, 1)$, which is not on the line of $(1, 0)$.' },
            { text: '$|{+y}\\rangle$', correct: false, why: '$M$ turns $(1, i)$ into $(2+i,\\ 1+2i)$, which is not a multiple of $(1, i)$.' },
            { text: '$\\tfrac{1}{\\sqrt5}(1, 2)$', correct: false, why: '$M$ sends $(1, 2)$ to $(4, 5)$: a new direction.' },
          ],
          hints: [
            { text: 'Apply $M$ and ask: is the output on the same line as the input?' },
            { text: 'A symmetric real matrix with equal diagonal entries treats $|{\\pm x}\\rangle$ specially.' },
            { text: 'Compute $M\\begin{pmatrix}1\\\\-1\\end{pmatrix}$.' },
          ],
          walkthrough: [
            { text: '$M\\begin{pmatrix}1\\\\-1\\end{pmatrix} = \\begin{pmatrix}1\\\\-1\\end{pmatrix}$, so $|{-x}\\rangle$ is an eigenvector with eigenvalue 1.' },
            { text: 'The other eigenvector is $|{+x}\\rangle$, with eigenvalue 3.' },
            { text: `They are orthogonal, as the Hermitian facts promise. Of the six named states, exactly ${d(V.l3ChMEigenCount, 0)} are eigenvectors of $M$.` },
          ],
        },
        {
          id: 'l3-eig-hermitian',
          kind: 'choice',
          tier: 'core',
          title: 'Spot the Hermitian matrix',
          prompt: 'Which matrix is Hermitian?',
          options: [
            { text: '$\\begin{pmatrix}1&2i\\\\-2i&1\\end{pmatrix}$', correct: true, why: 'Right. The diagonal is real, and the two corner entries are conjugates.' },
            { text: '$\\begin{pmatrix}1&2i\\\\2i&1\\end{pmatrix}$', correct: false, why: 'The lower entry must be the conjugate of the upper one, $-2i$.' },
            { text: '$\\begin{pmatrix}i&0\\\\0&1\\end{pmatrix}$', correct: false, why: 'A diagonal entry must be real.' },
            { text: '$\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$', correct: false, why: 'Real but antisymmetric: it is the quarter turn $R$ of the clue.' },
          ],
          hints: [
            { text: 'Conjugate every entry, then swap rows and columns. Is the result the same matrix?' },
            { text: 'Diagonal entries must equal their own conjugates.' },
            { text: 'Each corner pair must be conjugates: $A_{21} = A_{12}^*$.' },
          ],
          walkthrough: [
            { text: 'Apply the test to each option: only the first comes back unchanged.' },
            { text: 'The last option is the quarter turn $R$ of the clue, whose eigenvalues are $\\pm i$.' },
          ],
        },
        {
          id: 'l3-eig-real',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Real eigenvalues (homework)',
          assigned: 'L3 p.5',
          prompt: 'Homework (notes p. 5): show that a Hermitian operator has real eigenvalues. First, a numerical check. For $H = \\begin{pmatrix}1&-2i\\\\2i&-1\\end{pmatrix}$, what is the imaginary part of $\\langle{+y}|\\hat H|{+y}\\rangle$?',
          answer: V.l3ChHYIm,
          tolerance: 0.001,
          hints: [
            { text: 'Start from $\\hat A|a\\rangle = a|a\\rangle$ and take the [[inner-product|inner product]] with $\\langle a|$.' },
            { text: 'Compare the number $\\langle a|\\hat A|a\\rangle$ with its complex conjugate, using $\\hat A^\\dagger = \\hat A$.' },
            { text: 'Write $\\langle a|\\hat A|a\\rangle$ twice, once letting $\\hat A$ act to the right and once to the left, then compare the two.' },
          ],
          // assigned: hints only, and no walkthrough ships in the bundle (content test)
          walkthrough: [],
        },
      ],
    },
    {
      id: 'l3-projectors',
      story: L3_STORY['l3-projectors'],
      review: L3_REVIEW['l3-projectors'],
      title: 'Projectors keep one part of a state',
      question: 'How do we pull one outcome’s piece out of a state, and how do the outcomes build an observable?',
      lecture: {
        pages: 'L3 pp. 8–10',
        summary:
          'The projector $\\hat P_{+z} = |{+z}\\rangle\\langle{+z}|$ keeps the $|{+z}\\rangle$ part of a state and drops the rest, and projecting twice changes nothing. The projectors of a complete orthonormal basis add up to the identity, which rebuilds any state from its pieces. Weighting each projector by its outcome builds the observable itself, $\\hat A = \\sum_i a_i|a_i\\rangle\\langle a_i|$.',
        equations: ['\\hat P_{+z}^2 = \\hat P_{+z},\\qquad \\sum_i |a_i\\rangle\\langle a_i| = \\hat 1,\\qquad \\hat A = \\sum_i a_i|a_i\\rangle\\langle a_i|'],
      },
      books: [
        { source: 'townsend', where: '§2.3, pp. 41–45; §2.4, p. 48', adds: 'Identity and projection operators, built as Stern–Gerlach devices with merged or blocked beams; the matrix of a projector.' },
        { source: 'susskind', where: '§3.2', adds: 'An observable packages the states a device can tell apart together with the number it reports for each.' },
      ],
      visual: {
        kind: 'operator-builder',
        props: { axis: 'z' },
        tryThis: [
          'Step through the $z$ build. The readout checks that the two projectors add up to the identity.',
          'Switch the axis to “tilt” (it starts at 60°). The projectors are no longer diagonal, yet all three checks stay ✓.',
          'At any tilt, read the diagonal entries of the two projectors. They are the $z$ probabilities of the two outcome states. (Lecture 4 does the $x$ and $y$ builds by hand.)',
        ],
      },
      clues: [],
      insight: 'A projector is a filter that keeps one part of a state. The projectors of a basis add up to the identity, and weighting them by the outcomes builds the observable.',
      pitfalls: [
        'Treating a projected vector as a state. $\\hat P_{+z}|\\psi_{60}\\rangle$ has length ½ and must be rescaled.',
        'Adding projectors onto states that are not orthogonal. $\\hat P_{+z} + \\hat P_{+x}$ is not a projector, and it is not $\\hat 1$.',
      ],
      play: [
        {
          id: 'l3-proj-length',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Length of a projection',
          prompt: 'How long is $\\hat P_{-z}|\\psi_{60}\\rangle$, for $|\\psi_{60}\\rangle = \\tfrac12|{+z}\\rangle + \\tfrac{\\sqrt3}{2}|{-z}\\rangle$?',
          answer: V.l3ChPdLen,
          tolerance: 0.005,
          hints: [
            { text: 'A projector keeps one component.' },
            { text: '$\\hat P_{-z}|\\psi\\rangle = \\langle{-z}|\\psi\\rangle\\,|{-z}\\rangle$.' },
            { text: 'The length is $|\\langle{-z}|\\psi_{60}\\rangle|$.' },
          ],
          walkthrough: [
            { text: `$\\hat P_{-z}|\\psi_{60}\\rangle = \\tfrac{\\sqrt3}{2}|{-z}\\rangle$, so its length is $\\tfrac{\\sqrt3}{2} \\approx ${d(V.l3ChPdLen)}$.` },
            { text: 'Its square, $\\tfrac34$, will be the probability of the − result (Unit 3.4).' },
          ],
        },
        {
          id: 'l3-proj-matrix',
          kind: 'choice',
          tier: 'core',
          title: 'The matrix of a projector',
          prompt: 'Which matrix is $\\hat P_\\psi = |\\psi_{60}\\rangle\\langle\\psi_{60}|$ in the $z$ basis?',
          options: [
            { text: '$\\begin{pmatrix}\\tfrac14&\\tfrac{\\sqrt3}{4}\\\\\\tfrac{\\sqrt3}{4}&\\tfrac34\\end{pmatrix}$', correct: true, why: 'Right: each entry is one component times the conjugate of another.' },
            { text: '$\\begin{pmatrix}\\tfrac14&0\\\\0&\\tfrac34\\end{pmatrix}$', correct: false, why: 'Dropping the corner entries keeps the odds but loses the state.' },
            { text: '$\\begin{pmatrix}\\tfrac12&0\\\\0&\\tfrac{\\sqrt3}{2}\\end{pmatrix}$', correct: false, why: 'Those are the amplitudes, not products of amplitudes.' },
            { text: '$\\begin{pmatrix}\\tfrac34&\\tfrac{\\sqrt3}{4}\\\\\\tfrac{\\sqrt3}{4}&\\tfrac14\\end{pmatrix}$', correct: false, why: 'The two components are swapped.' },
          ],
          hints: [
            { text: '$|\\psi\\rangle\\langle\\psi|$ is a column times a row.' },
            { text: 'Each entry is one component times the conjugate of another.' },
            { text: 'The column is $(\\tfrac12, \\tfrac{\\sqrt3}{2})$; multiply it by the same row.' },
          ],
          walkthrough: [
            { text: 'Column times row: $\\tfrac12\\cdot\\tfrac12 = \\tfrac14$, $\\tfrac12\\cdot\\tfrac{\\sqrt3}{2} = \\tfrac{\\sqrt3}{4}$, and $\\tfrac{\\sqrt3}{2}\\cdot\\tfrac{\\sqrt3}{2} = \\tfrac34$.' },
            { text: `Numerically the corner entry is ${d(V.l3ChPpsi01)}.` },
            { text: 'Check that it is a projector: its trace is 1 and its determinant 0, so its eigenvalues are 1 and 0.' },
          ],
        },
        {
          id: 'l3-proj-build',
          kind: 'numeric',
          tier: 'core',
          title: 'Build an operator from its outcomes',
          prompt: 'Build $\\hat A = 3|{+x}\\rangle\\langle{+x}| + 1\\,|{-x}\\rangle\\langle{-x}|$. What is $A_{12} = \\langle{+z}|\\hat A|{-z}\\rangle$?',
          answer: V.l3ChBuild12,
          tolerance: 0.005,
          hints: [
            { text: 'Write each projector as a 2×2 matrix first.' },
            { text: '$|{\\pm x}\\rangle\\langle{\\pm x}| = \\tfrac12\\begin{pmatrix}1&\\pm1\\\\\\pm1&1\\end{pmatrix}$.' },
            { text: 'Add 3 times the first and 1 times the second.' },
          ],
          walkthrough: [
            { text: `$\\tfrac32\\begin{pmatrix}1&1\\\\1&1\\end{pmatrix} + \\tfrac12\\begin{pmatrix}1&-1\\\\-1&1\\end{pmatrix} = \\begin{pmatrix}2&1\\\\1&2\\end{pmatrix}$, so $A_{12} = ${d(V.l3ChBuild12, 0)}$.` },
            { text: 'This is the $M$ of Unit 3.2. Its eigen-data were built in, so $|{\\pm x}\\rangle$ are its eigenvectors, with eigenvalues 3 and 1.' },
          ],
        },
        {
          id: 'l3-proj-notcomplete',
          kind: 'choice',
          tier: 'stretch',
          title: 'Any two projectors?',
          prompt: 'Is $\\hat P_{+z} + \\hat P_{+x}$ a projector?',
          options: [
            { text: 'No: its square is not itself, because $|{+z}\\rangle$ and $|{+x}\\rangle$ are not orthogonal', correct: true, why: `Right. Its top-left entry is ${d(V.l3ChSum00, 1)}, so it is not $\\hat 1$ either.` },
            { text: 'Yes: a sum of projectors is always a projector', correct: false, why: 'Only when the states are orthogonal do the cross terms vanish.' },
            { text: 'Yes: it equals $\\hat 1$ by completeness', correct: false, why: 'Completeness needs an orthonormal basis; these two states overlap.' },
            { text: 'No, because the matrix has a zero entry', correct: false, why: 'Zero entries are allowed; $\\hat P_{+z}$ itself has three.' },
          ],
          hints: [
            { text: 'Square the sum and compare the result with the sum itself.' },
            { text: 'The cross terms $\\hat P_{+z}\\hat P_{+x} + \\hat P_{+x}\\hat P_{+z}$ must vanish for the sum to be a projector.' },
            { text: 'Those cross terms contain $\\langle{+z}|{+x}\\rangle = \\tfrac{1}{\\sqrt2}$, which is not zero.' },
          ],
          walkthrough: [
            { text: 'Squaring gives $\\hat P_{+z} + \\hat P_{+x}$ plus the cross terms.' },
            { text: 'The cross terms do not vanish, because the two states overlap. So the sum is not a projector, and not $\\hat 1$ either.' },
            { text: `The diagonal already shows it: its top-left entry is ${d(V.l3ChSum00, 1)}, not 1.` },
          ],
        },
      ],
    },
    {
      id: 'l3-postulates',
      story: L3_STORY['l3-postulates'],
      review: L3_REVIEW['l3-postulates'],
      title: 'Three rules for every measurement',
      question: 'Given $|\\psi\\rangle$ and $\\hat A$, which results can appear, how likely is each, and what state is left?',
      lecture: {
        pages: 'L3 pp. 11–13',
        summary:
          'Expand the state in the eigenbasis of the observable. Rule 1: a measurement returns one eigenvalue. Rule 2, the Born rule: the probability of $a_i$ is $|\\langle a_i|\\psi\\rangle|^2$, a projector sandwich, and completeness makes the odds add to one. Rule 3: after the result $a_i$ the state is the rescaled projection, which is $|a_i\\rangle$ up to an overall phase. Measuring $A$ is not the same as applying $\\hat A$.',
        equations: ['P(a_i) = |\\langle a_i|\\psi\\rangle|^2 = \\langle\\psi|\\hat P_i|\\psi\\rangle,\\qquad |\\psi\\rangle \\to \\frac{\\hat P_i|\\psi\\rangle}{\\sqrt{\\langle\\psi|\\hat P_i|\\psi\\rangle}}'],
      },
      books: [
        { source: 'susskind', where: '§3.5; §4.7; §3.2', adds: 'The common misconception that measuring is applying the operator; the average as a sandwich; the rules as four principles, the frame of Lecture 4.' },
        { source: 'townsend', where: '§1.6, pp. 22–24', adds: 'Orthonormal, complete bases, and why the probabilities of all outcomes add to one.' },
      ],
      visual: {
        kind: 'projector',
        props: { state: 60, basis: 0, editableBasis: true },
        tryThis: [
          'With the state at 60°, read ¼ and ¾: the Born rule for $|\\psi_{60}\\rangle$.',
          'Turn the measurement basis to 45°, the $x$ basis: 93.3 % and 6.7 %. They still add to 100 %.',
          'Find the one state that gives 100 % in the $x$ basis. It is an eigenvector of that measurement, so the measurement would leave it unchanged.',
        ],
      },
      clues: [],
      insight: 'A measurement returns an eigenvalue, with the Born-rule odds, and leaves the matching eigenvector behind. It is not the operator acting on the state.',
      pitfalls: [
        'Treating $\\hat A|\\psi\\rangle$ as the state after a measurement. It is generally not an eigenvector, and it need not have length 1.',
        'Forgetting to rescale the projection in Rule 3.',
      ],
      play: [
        {
          id: 'l3-post-born',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The Born rule on the running state',
          prompt: 'Measure $S_z$ on $|\\psi_{60}\\rangle$. What is the probability of $-\\tfrac{\\hbar}{2}$?',
          answer: V.l3P60Down,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Which eigenvector goes with $-\\tfrac{\\hbar}{2}$?' },
            { text: '$P = |\\langle{-z}|\\psi_{60}\\rangle|^2$.' },
            { text: '$\\langle{-z}|\\psi_{60}\\rangle = \\tfrac{\\sqrt3}{2}$.' },
          ],
          walkthrough: [
            { text: 'The outcome state is $|{-z}\\rangle$, with amplitude $\\tfrac{\\sqrt3}{2}$.' },
            { text: `The probability is $\\tfrac34 = ${d(V.l3P60Down, 2)}$. Check: $\\tfrac14 + \\tfrac34 = 1$.` },
          ],
        },
        {
          id: 'l3-post-x',
          kind: 'numeric',
          tier: 'core',
          title: 'The same state along x',
          prompt: 'Now send $|\\psi_{60}\\rangle$ into an SG$_x$ magnet. What is the probability of $+\\tfrac{\\hbar}{2}$?',
          answer: V.l3P60PlusX,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'The states an SG$_x$ magnet leaves are $|{\\pm x}\\rangle$.' },
            { text: '$\\langle{+x}|\\psi_{60}\\rangle = \\tfrac{1}{\\sqrt2}(\\tfrac12 + \\tfrac{\\sqrt3}{2})$.' },
            { text: 'Square it.' },
          ],
          walkthrough: [
            { text: `The amplitude is about ${d(V.l3CxPlus)}, so the probability is ${d(V.l3P60PlusX)}.` },
            { text: `If the result is +, the state becomes $|{+x}\\rangle$ (Rule 3). The − result has ${d(V.l3P60MinusX)}, and the two add to 1.` },
          ],
        },
        {
          id: 'l3-post-after',
          kind: 'choice',
          tier: 'core',
          title: 'The state after the reading',
          prompt: 'An atom in $|{+y}\\rangle$ is measured along $z$ and gives $-\\tfrac{\\hbar}{2}$. Which state describes it afterward?',
          options: [
            { text: '$|{-z}\\rangle$', correct: true, why: 'Right. The rescaled projection is $i|{-z}\\rangle$, the same state.' },
            { text: '$\\hat S_z|{+y}\\rangle$', correct: false, why: 'That points along $|{-y}\\rangle$: applying $\\hat S_z$ is not measuring.' },
            { text: '$\\tfrac{1}{\\sqrt2}|{-z}\\rangle$', correct: false, why: 'Projected but not rescaled: its length is only $\\tfrac{1}{\\sqrt2}$.' },
            { text: '$|{+y}\\rangle$, unchanged', correct: false, why: 'A $z$ measurement changes any state that is not a $z$ eigenvector.' },
          ],
          hints: [
            { text: 'Rule 3: project, then rescale.' },
            { text: '$\\hat P_{-z}|{+y}\\rangle = \\tfrac{i}{\\sqrt2}|{-z}\\rangle$.' },
            { text: 'An overall factor of $i$ changes no prediction.' },
          ],
          walkthrough: [
            { text: `Project: $\\hat P_{-z}|{+y}\\rangle = \\tfrac{i}{\\sqrt2}|{-z}\\rangle$, of length ${d(V.l3ChPdYLen)}.` },
            { text: 'Rescale to length 1: $i|{-z}\\rangle$, the same physical state as $|{-z}\\rangle$.' },
            { text: 'The tempting $\\hat S_z|{+y}\\rangle$ points along $|{-y}\\rangle$, a state this magnet never leaves.' },
          ],
        },
        {
          id: 'l3-post-steps',
          kind: 'order',
          tier: 'stretch',
          title: 'A prediction, step by step',
          prompt: 'Put the steps of a measurement prediction in order.',
          steps: [
            'Find the eigenvalues $a_i$ and eigenvectors $|a_i\\rangle$ of $\\hat A$',
            'Compute the amplitudes $c_i = \\langle a_i|\\psi\\rangle$',
            'Square their sizes: $P(a_i) = |c_i|^2$',
            'Check that the probabilities add to 1',
            'For the result actually seen, replace the state by $|a_i\\rangle$',
          ],
          hints: [
            { text: 'You cannot square an amplitude you have not computed.' },
            { text: 'The eigenvectors decide which amplitudes to compute.' },
            { text: 'The update comes last, because it depends on which result actually occurred.' },
          ],
          walkthrough: [
            { text: 'Run the steps on $|\\psi_{60}\\rangle$ and $S_z$: the eigenvalues are $\\pm\\tfrac{\\hbar}{2}$, with eigenvectors $|{\\pm z}\\rangle$.' },
            { text: `The amplitudes are $\\tfrac12$ and $\\tfrac{\\sqrt3}{2}$, so the probabilities are ${d(V.l3ChStepsProbUp, 2)} and ${d(V.l3P60Down, 2)}, which add to 1.` },
            { text: 'The state becomes $|{+z}\\rangle$ or $|{-z}\\rangle$, whichever result occurred.' },
          ],
        },
      ],
    },
    {
      id: 'l3-spin-example',
      story: L3_STORY['l3-spin-example'],
      review: L3_REVIEW['l3-spin-example'],
      title: 'One spin, measured from start to finish',
      question: 'What do the three rules predict for $|{+x}\\rangle$ sent through $z$, through $z$ again, or through $x$ and then $z$?',
      lecture: {
        pages: `L3 pp. 14–15 · ${L4_SLOT}`,
        summary:
          'The notes run the rules on $|{+x}\\rangle$ measured along $z$: each result has probability one half. After a + result the state is $|{+z}\\rangle$, so an immediate repeat gives + with certainty. An $S_x$ measurement in between splits the beam again, and a final $S_z$ is once more 50/50. This part was taught at the start of Lecture 4.',
        equations: ['P(\\pm\\tfrac{\\hbar}{2}) = |\\langle{\\pm z}|{+x}\\rangle|^2 = \\tfrac12,\\qquad |{+z}\\rangle = \\tfrac{1}{\\sqrt2}\\big(|{+x}\\rangle + |{-x}\\rangle\\big)'],
      },
      books: [
        { source: 'townsend', where: '§1.2, pp. 7–9; §1.4, pp. 14–15', adds: 'Experiments 3 and 4: magnets in sequence, and a modified device that recombines its beams without recording the path.' },
      ],
      visual: {
        kind: 'sg-lab',
        props: { source: '+x', axes: ['z', 'z'], keep: ['+'], editable: true, maxDevices: 3, predict: true },
        tryThis: [
          'Predict, then fire. After a kept $+z$, a second $z$ magnet gives + every time.',
          'Insert an $x$ magnet in the middle and keep +. Predict the final split: ½ of the atoms that reach the last magnet, ⅛ of the source.',
          'Turn the middle magnet back to $z$. Does the final result become certain again?',
        ],
      },
      clues: [],
      insight: 'Each measurement leaves the atom in one of its own eigenstates. A repeat along the same axis confirms it; a measurement along another axis starts the odds afresh.',
      pitfalls: ['Dividing by the wrong total: ⅛ is the share of the source, ½ the share of the atoms that reach the last magnet.'],
      play: [
        {
          id: 'l3-ex-repeat',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Measure it again',
          prompt: '$|{+x}\\rangle$ atoms pass SG$_z$ (keep +), then a second SG$_z$. What fraction of the source atoms lands in the final − spot?',
          answer: V.l3BlockMinus,
          tolerance: 0.005,
          unit: 'fraction of the source',
          hints: [
            { text: 'What state leaves the first magnet’s + beam?' },
            { text: 'Is that state an eigenvector of the second magnet’s $\\hat S_z$?' },
            { text: '$P(-\\tfrac{\\hbar}{2}) = |\\langle{-z}|{+z}\\rangle|^2$.' },
          ],
          walkthrough: [
            { text: 'The kept atoms are in $|{+z}\\rangle$, and $\\langle{-z}|{+z}\\rangle = 0$.' },
            { text: `So ${d(V.l3BlockMinus, 0)} of the source lands −. Half of the source was stopped at the block.` },
          ],
        },
        {
          id: 'l3-ex-insert',
          kind: 'numeric',
          tier: 'core',
          title: 'An x magnet in between',
          prompt: 'Same source, bench $z$ (keep +), then $x$ (keep +), then $z$. What fraction of the **source** atoms lands in the final + spot?',
          answer: V.l3ZxzPlus,
          tolerance: 0.005,
          unit: 'fraction of the source',
          hints: [
            { text: 'Follow one atom’s chances magnet by magnet.' },
            { text: 'Each magnet whose axis is at 90° to the previous state’s axis splits 50/50.' },
            { text: 'Multiply the three halves.' },
          ],
          walkthrough: [
            { text: `½ pass $z$, ½ of those pass $x$, and ½ of those land +: ${d(V.l3ZxzPlus)} of the source.` },
            { text: 'That is ½ of the atoms that reach the last magnet: the trap answer divides by the wrong total.' },
          ],
        },
        {
          id: 'l3-ex-tilt',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A gentler magnet in between',
          prompt: 'Same source, bench $z$ (keep +), then a magnet tilted 60° from $z$ toward $x$ (keep +), then $z$. What fraction of the source lands in the final + spot?',
          answer: V.l3ChTilt,
          tolerance: 0.005,
          unit: 'fraction of the source',
          hints: [
            { text: 'Lecture 1: $P(+) = \\cos^2\\tfrac{\\theta}{2}$ for two axes at angle $\\theta$.' },
            { text: 'The kept states are $|{+z}\\rangle$, then the + state of the tilted magnet.' },
            { text: '$\\tfrac12\\times\\cos^2 30^\\circ\\times\\cos^2 30^\\circ$.' },
          ],
          walkthrough: [
            { text: `$\\tfrac12 \\times \\tfrac34 \\times \\tfrac34 = \\tfrac{9}{32} = ${d(V.l3ChTilt, 5)}$.` },
            { text: 'The tilted magnet disturbs less than a 90° one, so more atoms come back +.' },
          ],
        },
      ],
    },
    {
      id: 'l3-spread',
      story: L3_STORY['l3-spread'],
      review: L3_REVIEW['l3-spread'],
      title: 'Averages and spreads of many readings',
      question: 'What is the average reading, and how widely do single readings scatter around it?',
      lecture: {
        pages: `L3 pp. 15–17, board plan pp. 18–19 · ${L4_SLOT}`,
        summary:
          'The expectation value is the probability-weighted sum of the outcomes, $\\langle A\\rangle = \\sum_i a_i P(a_i)$, and the Born rule turns it into $\\langle\\psi|\\hat A|\\psi\\rangle$. For $|{+x}\\rangle$ along $z$ it is 0, although no atom reads 0. The spread $\\Delta A$, the square root of $\\langle A^2\\rangle - \\langle A\\rangle^2$, measures how far single readings land from the average. It is $\\tfrac{\\hbar}{2}$ for $|{+x}\\rangle$ along $z$ and zero in an eigenstate. This part was taught at the start of Lecture 4.',
        equations: ['\\langle A\\rangle = \\sum_i a_i P(a_i) = \\langle\\psi|\\hat A|\\psi\\rangle,\\qquad (\\Delta A)^2 = \\langle A^2\\rangle - \\langle A\\rangle^2'],
      },
      books: [
        { source: 'townsend', where: '§1.4, pp. 15–17; §1.6, p. 24; §2.6, p. 58', adds: 'The average and the spread of $S_z$, why the spread is called an uncertainty, a worked example with odds ¼ and ¾, and the average as a row times a matrix times a column.' },
        { source: 'susskind', where: '§4.7', adds: 'Two definitions of the average, as a weighted sum and as the mean of many trials, and why they agree.' },
      ],
      visual: {
        kind: 'deposit-stats',
        props: { state: '+x', axis: 'z', seed: 448 },
        caption: 'The widget’s ± figure is the scatter of the up count in one batch, not $\\Delta S_z$. The scatter of an average reading shrinks as more atoms are counted.',
        tryThis: [
          'Fire 10 atoms a few times. The up count wanders around half, and so does the average reading around 0; yet every atom reads $\\pm\\tfrac{\\hbar}{2}$.',
          'Fire 10 000: the up fraction settles close to one half. The average settles; single readings do not.',
          'Every reading is exactly $\\tfrac{\\hbar}{2}$ away from the average 0. Explain from that why $\\Delta S_z = \\tfrac{\\hbar}{2}$ here.',
        ],
      },
      clues: [],
      insight: 'An average describes many identical runs, not one atom. The spread says how far single readings land from that average, and it vanishes only in an eigenstate.',
      pitfalls: [
        'Reading $\\langle S_z\\rangle = 0$ as “no $z$ spin”. Each atom reads $\\pm\\tfrac{\\hbar}{2}$, and the spread is as large as it gets.',
        'Confusing the spread of single readings, $\\Delta S_z$, with the scatter of an average over many atoms, which shrinks as more atoms are counted.',
      ],
      play: [
        {
          id: 'l3-sp-mean',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The average of the running state',
          prompt: 'What is $\\langle S_z\\rangle$ for $|\\psi_{60}\\rangle$?',
          answer: V.l3MeanSzP60,
          tolerance: 0.005,
          unit: 'ħ',
          hints: [
            { text: '$\\langle A\\rangle = \\sum_i a_i P(a_i)$.' },
            { text: 'The odds are ¼ for $+\\tfrac{\\hbar}{2}$ and ¾ for $-\\tfrac{\\hbar}{2}$.' },
            { text: '$\\tfrac{\\hbar}{2}\\cdot\\tfrac14 - \\tfrac{\\hbar}{2}\\cdot\\tfrac34$.' },
          ],
          walkthrough: [
            { text: `$\\tfrac{\\hbar}{8} - \\tfrac{3\\hbar}{8} = -\\tfrac{\\hbar}{4}$, that is −${d(-V.l3MeanSzP60, 2)} in units of ħ.` },
            { text: 'As a sandwich, $\\langle\\psi_{60}|\\hat S_z|\\psi_{60}\\rangle$ gives the same.' },
          ],
        },
        {
          id: 'l3-sp-spread',
          kind: 'numeric',
          tier: 'core',
          title: 'The spread of the running state',
          prompt: 'What is $\\Delta S_z$ for $|\\psi_{60}\\rangle$?',
          answer: V.l3SpreadP60,
          tolerance: 0.005,
          unit: 'ħ',
          hints: [
            { text: '$(\\Delta S_z)^2 = \\langle S_z^2\\rangle - \\langle S_z\\rangle^2$.' },
            { text: 'For a spin ½, $\\langle S_z^2\\rangle = \\tfrac{\\hbar^2}{4}$ in every state.' },
            { text: '$\\tfrac{\\hbar^2}{4} - \\tfrac{\\hbar^2}{16}$.' },
          ],
          walkthrough: [
            { text: '$(\\Delta S_z)^2 = \\tfrac{\\hbar^2}{4} - \\tfrac{\\hbar^2}{16} = \\tfrac{3\\hbar^2}{16}$.' },
            { text: `So $\\Delta S_z = \\tfrac{\\sqrt3}{4}\\hbar \\approx ${d(V.l3SpreadP60)}\\hbar$, the same as Townsend’s worked example, which has the same odds.` },
          ],
        },
        {
          id: 'l3-sp-zero',
          kind: 'choice',
          tier: 'core',
          title: 'An average of zero',
          prompt: 'For $|{+x}\\rangle$, $\\langle S_z\\rangle = 0$. Which statement is right?',
          options: [
            { text: 'Every atom reads $\\pm\\tfrac{\\hbar}{2}$, and the mean of many readings is 0', correct: true, why: 'Right. Rule 1 allows only the eigenvalues; the zero is a statement about many runs.' },
            { text: 'Some atoms read $S_z = 0$', correct: false, why: '0 is not an eigenvalue of $\\hat S_z$, so no single reading is 0.' },
            { text: 'Each atom’s spin points along $x$, so its $S_z$ is exactly 0', correct: false, why: 'No atom ever reads 0; each $z$ reading is $\\pm\\tfrac{\\hbar}{2}$.' },
            { text: '$\\Delta S_z = 0$, because the average is zero', correct: false, why: '$\\Delta S_z = \\tfrac{\\hbar}{2}$, the largest spread possible.' },
          ],
          hints: [
            { text: 'Rule 1: which values can one reading take?' },
            { text: 'An average is a statement about many runs.' },
            { text: 'Compute $\\Delta S_z$ before you pick.' },
          ],
          walkthrough: [
            { text: 'The readings are only $\\pm\\tfrac{\\hbar}{2}$, half and half, so the mean is 0.' },
            { text: `The spread is ${d(V.l3SpreadX, 1)} in units of ħ, as large as it can be.` },
          ],
        },
        {
          id: 'l3-sp-complex',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A complex amplitude',
          prompt: '$|\\psi\\rangle = \\tfrac{1}{\\sqrt3}|{+z}\\rangle + i\\sqrt{\\tfrac23}\\,|{-z}\\rangle$. What is $\\Delta S_z$?',
          answer: V.l3ChSpreadComplex,
          tolerance: 0.005,
          unit: 'ħ',
          hints: [
            { text: 'The $i$ does not change the $z$ odds.' },
            { text: '$P(+) = \\tfrac13$ and $P(-) = \\tfrac23$, so $\\langle S_z\\rangle = -\\tfrac{\\hbar}{6}$.' },
            { text: '$(\\Delta S_z)^2 = \\tfrac{\\hbar^2}{4} - \\tfrac{\\hbar^2}{36}$.' },
          ],
          walkthrough: [
            { text: '$(\\Delta S_z)^2 = \\tfrac{\\hbar^2}{4} - \\tfrac{\\hbar^2}{36} = \\tfrac{2\\hbar^2}{9}$.' },
            { text: `So $\\Delta S_z = \\tfrac{\\sqrt2}{3}\\hbar \\approx ${d(V.l3ChSpreadComplex)}\\hbar$.` },
            { text: 'Phases never enter $z$ statistics; they do matter for $x$ and $y$ (Lectures 5–6).' },
          ],
        },
      ],
    },
  ],
}
