import type { Lecture } from './schema'
import { URL } from './refs'
import { V, close, d, tf } from './L4.values'
import { L4_STORY } from './L4.story'
import { L4_REVIEW } from './L4.review'

// Every number a learner sees in this lecture is computed in L4.values.ts, then asserted in keyed claims
// (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy). Plan: docs/roles/proposals/P-L4-story.md,
// with the judge's rulings (second passes of Units 3.3 and 3.6, σ passport from l4-matrices:b5, the 60° preparation
// magnet, the S_y eigenproblem as L5 homework, no Gram–Schmidt challenge while the homework sheet is missing).

export const L4: Lecture = {
  id: 'L4',
  number: 4,
  title: 'Measurement principles and spin operators',
  outcomes: [
    'State the four principles of measurement, and say what orthonormal and complete each mean.',
    'Treat a projector as a yes/no measurement: its results, its states, and what filters in a row do.',
    'For a given state, list every result, its probability and the state left behind.',
    'Compute an average over many preparations, as a weighted sum and as a sandwich in ket or matrix form.',
    'Build the three spin matrices from their definite states and values, and check that they are Hermitian.',
    'Solve a 2×2 eigenvalue problem: determinant, back-substitution, normalization and phase.',
  ],
  prerequisites: ['projectors', 'expectation', 'observables', 'complex-amplitudes'],
  // Symbols defined in the text itself (symbol → the unit, beat or site whose sentence defines it). Kets, bras, ħ, i
  // and Lecture 3's operators, projectors and eigen-notation are mapped to the first unit's title: a recap.
  symbols: {
    A: 'l4-basis',
    '\\hat A': 'l4-basis',
    a_i: 'l4-basis',
    '\\langle\\cdot|\\cdot\\rangle': 'l4-basis',
    '|a_i\\rangle': 'l4-basis',
    '|\\psi\\rangle': 'l4-basis',
    '|\\cdot\\rangle': 'l4-basis',
    '\\langle\\cdot|': 'l4-basis',
    '|+z\\rangle': 'l4-basis',
    '|-z\\rangle': 'l4-basis',
    '|+x\\rangle': 'l4-basis',
    '|-x\\rangle': 'l4-basis',
    '|+y\\rangle': 'l4-basis',
    '|-y\\rangle': 'l4-basis',
    '\\hbar': 'l4-basis',
    i: 'l4-basis',
    P: 'l4-basis',
    S_z: 'l4-basis',
    '\\hat S_z': 'l4-basis',
    S_x: 'l4-basis',
    '\\hat S_x': 'l4-basis',
    '\\hat P_i': 'l4-basis',
    '\\hat P_+z': 'l4-basis',
    '\\hat P_-z': 'l4-basis',
    '\\hat P_+x': 'l4-basis',
    '\\hat P_-x': 'l4-basis',
    '\\dagger': 'l4-basis',
    '\\alpha': 'l4-basis',
    '\\beta': 'l4-basis',
    '|a_j\\rangle': 'l4-basis:b4',
    j: 'l4-basis:b4',
    c_i: 'l4-basis:b4',
    '|v_1\\rangle': 'l4-basis:b8',
    '|v_2\\rangle': 'l4-basis:b8',
    '|v\\rangle': 'l4-basis:b8',
    '|e_1\\rangle': 'l4-basis:b8',
    '|w_2\\rangle': 'l4-basis:b8',
    '|e_2\\rangle': 'l4-basis:b8',
    'c_+': 'l4-basis.play.l4-b-expand',
    'c_-': 'l4-basis.play.l4-b-expand',
    '\\hat P_\\pm': 'l4-projectors:b5',
    '\\hat P_\\pmz': 'l4-projectors:b5',
    '\\hat P_+': 'l4-projectors:b5',
    '\\hat P_-': 'l4-projectors:b5',
    Q: 'l4-projectors:b6',
    '\\hat P': 'l4-projectors:b6',
    p: 'l4-projectors:b7',
    m_ij: 'l4-matrices:b1',
    m_11: 'l4-matrices:b1',
    m_21: 'l4-matrices:b1',
    m_12: 'l4-matrices:b1',
    m_22: 'l4-matrices:b1',
    'P_\\pmx': 'l4-matrices:b3',
    '\\hat P_\\pmx': 'l4-matrices:b3',
    'P_+x': 'l4-matrices:b3',
    'P_+y': 'l4-matrices:b4',
    'P_-y': 'l4-matrices:b4',
    S_y: 'l4-matrices:b4',
    S_i: 'l4-matrices:b5',
    a_0: 'l4-matrices:b5',
    a_x: 'l4-matrices:b5',
    a_y: 'l4-matrices:b5',
    a_z: 'l4-matrices:b5',
    A_ij: 'l4-matrices:b6',
    A_ji: 'l4-matrices:b6',
    '\\lambda': 'l4-eigen:b1',
    c_1: 'l4-eigen:b1',
    c_2: 'l4-eigen:b1',
    '\\lambda_\\pm': 'l4-eigen:b2',
    '\\theta': 'l4-eigen:b7',
    v: 'l4-eigen.play.l4-g-order.steps[0]',
    M: 'l4-eigen.play.l4-g-shift',
  },
  watch: [
    { source: '3b1b', where: 'The determinant', adds: 'The determinant as the factor by which a matrix scales areas. Zero means the plane is squashed flat, which is why a zero determinant finds eigenvalues.', url: URL.b3('determinant') },
    { source: '3b1b', where: 'Inverse matrices, column space and null space', adds: 'Why a matrix with zero determinant has no inverse, and so can send a nonzero vector to zero.', url: URL.b3('inverse-matrices') },
    { source: 'mit805', where: 'Lecture 4', adds: 'Zwiebach on spin one-half: the spin operators as 2×2 matrices and their eigenstates, told from a different angle.', url: URL.mit805(4) },
  ],
  corrections: [
    {
      where: 'L4 p.10',
      says: 'For many fresh preparations of the example state, the notes put the average z-spin reading at zero, and add that a finite run need not show exactly equal counts.',
      shouldSay:
        'The average is ħ/4, since + comes up three times as often as −. A finite run scatters around 3 : 1, not around equal counts. Zero is the average for |+x⟩, Lecture 3’s example, from which the sentence was carried over (Unit 4.4).',
      check: () => close(V.l4MeanSz, 0.25) && close(V.l4MeanSzX, 0) && close(V.l4PsiUp, 3 * V.l4PsiDown),
      source: 'notes',
    },
    {
      where: 'L4 p.2',
      says: 'The four principles are credited to Chapter 4 of Susskind and Friedman.',
      shouldSay:
        'They are in Susskind’s Lecture 3, §3.2, the printed pages 69–74 that the notes themselves cite on p. 21. His Lecture 4 adds a fifth principle, about how states change in time.',
      // a citation, not a number: nothing for the engine to check
      check: () => true,
      source: 'notes',
    },
    {
      where: 'L4 p.2 (wording)',
      says: 'Orthonormal is explained as: every input state can be expanded in the measurement’s states.',
      shouldSay:
        'That sentence describes complete, not orthonormal. Orthonormal means unit length and no overlap; complete means every state is a sum of the basis states. The set holding only |+z⟩ is orthonormal but builds no part of |−z⟩ (Unit 4.1).',
      check: () => close(V.l4ZMinusZ, 0) && close(V.l4PuKillsDown, 0) && V.l4ComplZ === 1,
      source: 'notes',
    },
    {
      where: 'L3 p.17 (margin, Principle 4)',
      says: 'The margin writes the Born-rule probability with a lower-case a, as ⟨a|l₁⟩⟨l₁|a⟩, although it names the state |A⟩.',
      shouldSay:
        'It should read ⟨A|l₁⟩⟨l₁|A⟩ = |⟨l₁|A⟩|². The capital |A⟩ is the state; lower-case |aᵢ⟩ are an observable’s eigenvectors (Unit 4.1).',
      // notation, not a number: nothing for the engine to check
      check: () => true,
      source: 'notes',
    },
  ],
  units: [
    {
      id: 'l4-basis',
      story: L4_STORY['l4-basis'],
      review: L4_REVIEW['l4-basis'],
      title: 'Four principles and a complete basis',
      question: 'What must an observable’s eigenstates do so that every state can be measured?',
      lecture: {
        pages: 'L4 pp. 1–5',
        summary:
          'Four principles organize measurement: observables are operators, results are eigenvalues, perfectly distinguishable states are orthogonal, and the Born rule gives the odds. A Hermitian operator’s eigenvectors can be chosen orthonormal, and they are complete. So every state is a sum of them, and their projectors add up to the identity. When an eigenvalue repeats, the [[gram-schmidt|Gram–Schmidt procedure]] turns [[linearly-independent|linearly independent]] eigenvectors into orthonormal ones with the same [[span]].',
        equations: ['\\langle a_i|a_j\\rangle = \\delta_{ij},\\qquad |\\psi\\rangle = \\sum_i c_i|a_i\\rangle,\\qquad \\sum_i \\hat P_i = I'],
      },
      books: [
        { source: 'susskind', where: '§3.1.5–3.1.6; §3.2', adds: 'The fundamental theorem, Gram–Schmidt for repeated eigenvalues, and the four principles of measurement.' },
        { source: 'townsend', where: '§2.3, pp. 41–43; §2.8, pp. 67–68', adds: 'The completeness relation as a sum of projectors, and why Hermitian operators have orthogonal eigenstates.' },
      ],
      visual: {
        kind: 'projector',
        props: { state: 30, basis: 0, editableBasis: true },
        tryThis: [
          'Drag the state anywhere. Do the two squares ever add to more, or less, than 1?',
          'Turn the basis to 45°, the $x$ basis. The shares change, but they still add to 1: the $x$ basis is complete too.',
          'Put the state at 45° with the $z$ basis. Which state is it, and why is it not left out of the $z$ measurement?',
        ],
      },
      clues: [],
      insight: 'A Hermitian operator’s eigenvectors can be chosen orthonormal, and they are complete. So every state is a sum over the outcomes of a measurement, and the odds add to one.',
      pitfalls: [
        'Mixing up orthonormal and complete. Orthonormal is about lengths and overlaps; complete is about which states the basis can build.',
        'Assuming eigenvectors overlap nowhere when an eigenvalue repeats. Only eigenvectors with different eigenvalues must be orthogonal; otherwise Gram–Schmidt makes them so.',
      ],
      play: [
        {
          id: 'l4-b-distinct',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Told apart for sure',
          prompt: 'Which pair of states can one measurement always tell apart?',
          options: [
            { text: '$|{+z}\\rangle$ and $|{-z}\\rangle$', correct: true, why: `Right. Their [[inner-product|inner product]] is ${d(V.l4ZMinusZ, 0)}: they are orthogonal.` },
            { text: '$|{+z}\\rangle$ and $|{+x}\\rangle$', correct: false, why: `They overlap: $\\langle{+z}|{+x}\\rangle \\approx ${d(V.l4ZXOverlap)}$.` },
            { text: '$|{+x}\\rangle$ and $|{+y}\\rangle$', correct: false, why: `Conjugating the bra, their overlap has size ${d(V.l4ChXYOverlap)}.` },
            { text: '$|{+y}\\rangle$ and $-|{+y}\\rangle$', correct: false, why: `These are one state: their overlap has size ${d(V.l4ChYMinusY, 0)}.` },
          ],
          hints: [
            { text: 'Principle 3 turns “always tell apart” into a statement about overlaps.' },
            { text: 'Perfectly distinguishable means orthogonal: the inner product is 0.' },
            { text: 'Compute the inner product for each pair, conjugating the bra when it contains $i$.' },
          ],
          walkthrough: [
            { text: 'Write each pair as columns and take the inner products, conjugating the first.' },
            { text: `Only $|{\\pm z}\\rangle$ gives 0. The pair $|{+x}\\rangle$, $|{+y}\\rangle$ overlaps with size ${d(V.l4ChXYOverlap)}.` },
            { text: 'And $-|{+y}\\rangle$ is not even a different state: an [[global-phase|overall sign]] changes nothing.' },
          ],
        },
        {
          id: 'l4-b-complete',
          kind: 'choice',
          tier: 'core',
          title: 'Complete is not orthonormal',
          prompt: 'Which statement says that $|{+z}\\rangle$ and $|{-z}\\rangle$ form a **complete** set?',
          options: [
            { text: 'Every state can be written as $\\alpha|{+z}\\rangle + \\beta|{-z}\\rangle$', correct: true, why: 'Right: no state is left out. That is completeness.' },
            { text: '$\\langle{+z}|{-z}\\rangle = 0$', correct: false, why: 'That is orthogonality: the two do not overlap.' },
            { text: 'Each has length 1', correct: false, why: 'That is normalization. Orthonormal means this plus orthogonality.' },
            { text: 'Each is an eigenvector of $\\hat S_z$', correct: false, why: 'True, but it says nothing about which states can be built from them.' },
          ],
          hints: [
            { text: 'Orthonormal and complete are two different facts about a basis.' },
            { text: 'One is about overlaps and lengths; the other is about which states the basis can build.' },
            { text: 'Ask which statement would fail for the single state $|{+z}\\rangle$ on its own.' },
          ],
          walkthrough: [
            { text: 'Orthonormal means unit length and no overlap. The single vector $|{+z}\\rangle$ already has both.' },
            { text: `Complete means every state is a sum of basis states. $|{+z}\\rangle$ alone fails: $\\hat P_{+z}|{-z}\\rangle = ${d(V.l4PuKillsDown, 0)}$, so nothing of $|{-z}\\rangle$ is built.` },
            { text: 'The notes’ p. 2 describes completeness under the name “orthonormal”; see the errata.' },
          ],
        },
        {
          id: 'l4-b-expand',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Up, in the x basis',
          prompt: 'Write $|{+z}\\rangle = c_+|{+x}\\rangle + c_-|{-x}\\rangle$ in the $x$ basis. What is $c_-$?',
          answer: V.l4ChMinusXofZ,
          tolerance: 0.005,
          hints: [
            { text: 'Completeness in the $x$ basis: each coefficient is an inner product with $|{+z}\\rangle$.' },
            { text: 'The coefficient of $|{-x}\\rangle$ is $\\langle{-x}|{+z}\\rangle$.' },
            { text: 'The bra $\\langle{-x}|$ is the row $\\tfrac{1}{\\sqrt2}(1\\;\\;-1)$; multiply it by the column $\\binom10$.' },
          ],
          walkthrough: [
            { text: `$c_- = \\tfrac{1}{\\sqrt2}(1\\cdot 1 - 1\\cdot 0) = 1/\\sqrt2 \\approx ${d(V.l4ChMinusXofZ)}$.` },
            { text: 'Likewise $c_+ = 1/\\sqrt2$: even $|{+z}\\rangle$ splits evenly between $|{+x}\\rangle$ and $|{-x}\\rangle$.' },
          ],
        },
      ],
    },
    {
      id: 'l4-projectors',
      story: L4_STORY['l4-projectors'],
      review: L4_REVIEW['l4-projectors'],
      title: 'A projector asks a yes/no question',
      question: 'What does one projector measure, and how does it fit into a full measurement?',
      lecture: {
        pages: 'L4 pp. 6–7, 21',
        summary:
          'A projector is itself an observable with two results: 1 for “yes” and 0 for “no”. A “no” leaves the other basis state, never the zero vector. One projector gives one outcome’s share of the probability, and the complete family adds up to the identity. Applied twice, a projector changes nothing, and two opposite projectors multiply to zero.',
        equations: ['\\hat P_{+z}^2 = \\hat P_{+z},\\qquad \\hat P_{+z}\\hat P_{-z} = 0,\\qquad \\hat P_{+z} + \\hat P_{-z} = I'],
      },
      books: [
        { source: 'townsend', where: '§2.3, pp. 42–44; §2.4, p. 48', adds: 'Projectors as magnets with one path blocked, their eigenvalues 1 and 0, filters in a row, and the matrix of a projector.' },
        { source: 'susskind', where: '§3.2 (Principle 4)', adds: 'The probability of an outcome as the squared overlap with its state.' },
      ],
      visual: {
        kind: 'sg-lab',
        props: { source: '+x', axes: ['z', 'z', 'z'], keep: ['+', '+'], editable: true, predict: true, maxDevices: 4 },
        tryThis: [
          'Predict the + fraction, then check: the second $z$ filter stops no atoms, because a projector applied twice is the same projector.',
          'Keep − at the second filter: nothing reaches the plate, because opposite projectors multiply to zero.',
          'Turn the middle filter to $x$: now atoms are lost at every filter. What changed?',
        ],
      },
      clues: [],
      insight: 'A projector asks one yes/no question. Its answers are 1 and 0, and the atom always ends in a real state, never in the zero vector.',
      pitfalls: [
        'Treating $\\hat P_{+z}|\\psi\\rangle$ as the state after a “no”. The “no” state is $|{-z}\\rangle$.',
        'Calling any matrix with $\\hat P^2 = \\hat P$ a measurement. It must also be Hermitian, so that its outcomes are orthogonal.',
      ],
      play: [
        {
          id: 'l4-p-results',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Yes or no',
          prompt: 'Which results can a measurement of $\\hat P_{+z}$ give?',
          options: [
            { text: '1 and 0', correct: true, why: `Right: $\\hat P_{+z}$ has eigenvalues ${d(V.l4PuEigTop, 0)} and ${d(V.l4PuEigLow, 0)}, “yes” and “no”.` },
            { text: '$+\\tfrac{\\hbar}{2}$ and $-\\tfrac{\\hbar}{2}$', correct: false, why: 'Those are the results of $\\hat S_z$, a different observable.' },
            { text: 'Only 1', correct: false, why: 'This forgets the state it sends to zero: $\\hat P_{+z}|{-z}\\rangle = 0\\,|{-z}\\rangle$.' },
            { text: '1 and −1', correct: false, why: 'Those are the [[sigma-reading|±1 readings]] of $\\sigma_z$.' },
          ],
          hints: [
            { text: 'The results of a measurement are the eigenvalues.' },
            { text: 'Find what $\\hat P_{+z}$ does to $|{+z}\\rangle$ and to $|{-z}\\rangle$.' },
            { text: '$\\hat P_{+z}|{+z}\\rangle = 1\\,|{+z}\\rangle$ and $\\hat P_{+z}|{-z}\\rangle = 0\\,|{-z}\\rangle$.' },
          ],
          walkthrough: [
            { text: 'Apply $\\hat P_{+z}$ to both basis states and read off the factors 1 and 0.' },
            { text: 'A result 0 means “no”, and the atom is left in $|{-z}\\rangle$.' },
          ],
        },
        {
          id: 'l4-p-yes',
          kind: 'numeric',
          tier: 'core',
          title: 'The chance of yes',
          prompt: 'For $|\\psi\\rangle = 0.6|{+z}\\rangle + 0.8|{-z}\\rangle$, what is the probability that “up along $z$?” is answered “yes”?',
          answer: V.l4ChYes68,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'The probability of an outcome is $\\langle\\psi|\\hat P|\\psi\\rangle$ for its projector.' },
            { text: '$\\hat P_{+z}|\\psi\\rangle = 0.6|{+z}\\rangle$.' },
            { text: 'Take the inner product of that with $|\\psi\\rangle$.' },
          ],
          walkthrough: [
            { text: `$\\langle\\psi|\\hat P_{+z}|\\psi\\rangle = 0.6 \\times 0.6 = ${d(V.l4ChYes68, 2)}$.` },
            { text: `Check: “no” gets ${d(V.l4ChNo68, 2)}, and the two add to 1.` },
          ],
        },
        {
          id: 'l4-p-idempotent',
          kind: 'choice',
          tier: 'core',
          title: 'Squares to itself, but…',
          prompt: '$Q = \\begin{pmatrix}1&1\\\\0&0\\end{pmatrix}$ satisfies $Q^2 = Q$. Can it represent a yes/no measurement?',
          options: [
            { text: 'Yes: $Q^2 = Q$ is all a projector needs', correct: false, why: 'A measurement projector must also be Hermitian.' },
            { text: 'No: it is not Hermitian, and its “yes” and “no” states overlap', correct: true, why: `Right. The overlap is $1/\\sqrt2 \\approx ${d(V.l4ZMinusXOverlap)}$, so the two outcomes cannot be told apart for sure.` },
            { text: 'No, because $Q^2 \\neq Q$', correct: false, why: 'Multiply it out: $Q^2 = Q$ does hold.' },
            { text: 'No, because its eigenvalues are not 1 and 0', correct: false, why: `They are ${d(V.l4QEigTop, 0)} and ${d(V.l4QEigLow, 0)}.` },
          ],
          hints: [
            { text: 'Principle 3 says a measurement’s outcomes must be told apart for sure.' },
            { text: 'Find the eigenvectors of $Q$ for 1 and for 0.' },
            { text: 'They are $\\binom10$ and $\\tfrac{1}{\\sqrt2}\\binom{1}{-1}$; compute their overlap.' },
          ],
          walkthrough: [
            { text: '$Q^2 = Q$ holds, so $Q$ looks like a projector.' },
            { text: `Its eigenvectors $\\binom10$ and $\\tfrac{1}{\\sqrt2}\\binom{1}{-1}$ overlap by ${d(V.l4ZMinusXOverlap)}, not 0.` },
            { text: 'So its outcomes are not distinguishable: a measurement projector also needs $\\hat P^\\dagger = \\hat P$.' },
          ],
        },
        {
          id: 'l4-p-two-filters',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Two questions in a row',
          prompt: 'Atoms in $|{+z}\\rangle$ pass an “up along $x$?” filter and then an “up along $z$?” filter. What fraction survives both?',
          answer: V.l4ChTwoFilters,
          tolerance: 0.005,
          unit: 'fraction of the source',
          hints: [
            { text: 'Filters in a row are projectors applied in turn.' },
            { text: 'The surviving fraction is the squared length of what is left.' },
            { text: '$\\hat P_{+x}|{+z}\\rangle = \\tfrac12\\binom11$.' },
          ],
          walkthrough: [
            { text: '$\\hat P_{+x}|{+z}\\rangle = \\tfrac12\\binom11$, and then $\\hat P_{+z}$ keeps $\\tfrac12\\binom10$.' },
            { text: `Its squared length is ${d(V.l4ChTwoFiltersNorm, 2)}, the same as ½ × ½ from the lab rule.` },
          ],
        },
      ],
    },
    {
      id: 'l4-example',
      story: L4_STORY['l4-example'],
      review: L4_REVIEW['l4-example'],
      title: 'One state, the whole prediction',
      question: 'For a state with unequal amplitudes, which results occur, how often, and what is left?',
      lecture: {
        pages: 'L4 pp. 8–9',
        summary:
          'The example state $\\tfrac{\\sqrt3}{2}|{+z}\\rangle + \\tfrac12|{-z}\\rangle$ is normalized. Measuring $S_z$ gives $+\\tfrac{\\hbar}{2}$ with probability $\\tfrac34$ and $-\\tfrac{\\hbar}{2}$ with probability $\\tfrac14$. After $+\\tfrac{\\hbar}{2}$ the state is $|{+z}\\rangle$, so an immediate repeat gives $+\\tfrac{\\hbar}{2}$ for certain. As matrices, the update is a projector matrix times a column, then a rescaling.',
        equations: ['P(+\\tfrac{\\hbar}{2}) = |\\langle{+z}|\\psi\\rangle|^2 = \\tfrac34,\\qquad \\frac{\\hat P_{+z}|\\psi\\rangle}{\\sqrt{3/4}} = |{+z}\\rangle'],
      },
      books: [
        { source: 'townsend', where: '§2.4, p. 48', adds: 'The matrix of a projector acting on a column: the update rule as one matrix product.' },
        { source: 'susskind', where: '§3.2 (Principle 4)', adds: 'The Born rule, stated for any observable and any state.' },
      ],
      visual: {
        kind: 'amplitude-bars',
        props: { state: [60, 0], basis: 'z', editable: true },
        tryThis: [
          `Read the two amplitudes and square them: ${d(V.l4PsiUp, 2)} and ${d(V.l4PsiDown, 2)}.`,
          'Set φ to 90°, a complex [[relative-phase|relative phase]]: the $z$ bars do not move. Which basis notices the change?',
          `Back at φ = 0°, switch the basis to $x$: ${d(V.l4PsiXPlus)} and ${d(V.l4PsiXMinus)}, the numbers Unit 4.6 derives.`,
        ],
      },
      clues: [],
      insight: 'One state gives the whole prediction: the possible results, their probabilities, and the state after each. Amplitude, probability, result and state are four different things.',
      pitfalls: [
        'Reporting the amplitude as the probability. The probability is the amplitude’s squared size.',
        'Forgetting the update. A second magnet sees the state after the first result, not the original state.',
      ],
      play: [
        {
          id: 'l4-e-minus',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The down odds',
          prompt: '$|\\psi\\rangle = 0.6|{+z}\\rangle + 0.8|{-z}\\rangle$. What is $P(-\\tfrac{\\hbar}{2})$ for $S_z$?',
          answer: V.l4ChNo68,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'First check that the state is normalized.' },
            { text: 'The amplitude for $-\\tfrac{\\hbar}{2}$ is $\\langle{-z}|\\psi\\rangle$.' },
            { text: 'Square its size.' },
          ],
          walkthrough: [
            { text: `$${d(V.l4ChYes68, 2)} + ${d(V.l4ChNo68, 2)} = 1$, so the state is normalized.` },
            { text: `$\\langle{-z}|\\psi\\rangle = 0.8$, and $0.8^2 = ${d(V.l4ChNo68, 2)}$.` },
          ],
        },
        {
          id: 'l4-e-four',
          kind: 'choice',
          tier: 'core',
          title: 'Four numbers, four meanings',
          prompt: 'In the lecture’s example, what is the number $\\tfrac{\\sqrt3}{2}$?',
          options: [
            { text: 'The amplitude $\\langle{+z}|\\psi\\rangle$', correct: true, why: 'Right. It is the shadow of $|\\psi\\rangle$ on $|{+z}\\rangle$.' },
            { text: 'The probability of $+\\tfrac{\\hbar}{2}$', correct: false, why: `That is its square, $${tf(V.l4PsiUp)}$.` },
            { text: 'The measured value', correct: false, why: 'That is $+\\tfrac{\\hbar}{2}$.' },
            { text: 'The state after the measurement', correct: false, why: 'That is $|{+z}\\rangle$.' },
          ],
          hints: [
            { text: 'Four different things appear in one prediction.' },
            { text: 'Probabilities are squares of amplitudes.' },
            { text: '$(\\tfrac{\\sqrt3}{2})^2 = \\tfrac34$.' },
          ],
          walkthrough: [
            { text: 'List the amplitude, the probability, the result and the state after.' },
            { text: `$\\tfrac{\\sqrt3}{2} \\approx ${d(V.l4PsiAmpUp)}$ is the amplitude; its square, ${d(V.l4PsiUp, 2)}, is the probability.` },
          ],
        },
        {
          id: 'l4-e-normalize',
          kind: 'numeric',
          tier: 'core',
          title: 'Normalize first',
          prompt: 'A state is given as the column $\\binom21$, not yet normalized. What is $P(+\\tfrac{\\hbar}{2})$ for $S_z$?',
          answer: V.l4ChNormalize,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Probabilities need a state of length 1.' },
            { text: 'Divide by the length $\\sqrt{2^2 + 1^2} = \\sqrt5$.' },
            { text: 'Then square the first component.' },
          ],
          walkthrough: [
            { text: 'The length is $\\sqrt5$, so the state is $\\tfrac{1}{\\sqrt5}\\binom21$.' },
            { text: `$P = 4/5 = ${d(V.l4ChNormalize, 1)}$. Skipping the normalization gives 4, which is no probability at all.` },
          ],
        },
        {
          id: 'l4-e-then-x',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Then along x',
          prompt: 'An atom in $|\\psi\\rangle = \\tfrac{\\sqrt3}{2}|{+z}\\rangle + \\tfrac12|{-z}\\rangle$ gives $+\\tfrac{\\hbar}{2}$ for $S_z$. Right after, $S_x$ is measured. What is the probability of $+\\tfrac{\\hbar}{2}$?',
          answer: V.l4ChThenX,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Which state goes into the second magnet?' },
            { text: 'After $+\\tfrac{\\hbar}{2}$ the state is $|{+z}\\rangle$, not $|\\psi\\rangle$.' },
            { text: 'Find $|\\langle{+x}|{+z}\\rangle|^2$.' },
          ],
          walkthrough: [
            { text: `The update sends $|\\psi\\rangle$ to $|{+z}\\rangle$, and $|\\langle{+x}|{+z}\\rangle|^2 = ${d(V.l4ChThenX, 1)}$.` },
            { text: `The trap is ${d(V.l4PsiXPlus)}, what $|\\psi\\rangle$ itself would give; the first measurement erased that.` },
          ],
        },
      ],
    },
    {
      id: 'l4-average',
      story: L4_STORY['l4-average'],
      review: L4_REVIEW['l4-average'],
      title: 'The average that no atom reads',
      question: 'What is the mean $S_z$ reading for this lecture’s state, and how does the sandwich give it in matrix form?',
      lecture: {
        pages: 'L4 pp. 10–12',
        summary:
          'For the example state, $\\langle S_z\\rangle = \\tfrac{\\hbar}{4}$ over many fresh preparations, although every single reading is $\\pm\\tfrac{\\hbar}{2}$. Measuring one atom again repeats its first answer instead. Lecture 3’s sandwich gives the same $\\tfrac{\\hbar}{4}$, and in matrix form it is a row times a matrix times a column. Applying $\\hat S_z$ is a step in that product, not a measurement.',
        equations: ['\\langle S_z\\rangle = \\langle\\psi|\\hat S_z|\\psi\\rangle = \\tfrac{\\hbar}{2}\\cdot\\tfrac34 - \\tfrac{\\hbar}{2}\\cdot\\tfrac14 = \\tfrac{\\hbar}{4}'],
      },
      books: [
        { source: 'townsend', where: '§2.6, p. 58', adds: 'The expectation value as a row times a matrix times a column, in any basis.' },
        { source: 'susskind', where: '§3.5; §4.7', adds: 'Measuring is not applying the operator; the operator acting on the state is one half of the average.' },
      ],
      visual: {
        kind: 'deposit-stats',
        props: { state: [60, 0], axis: 'z', seed: 448 },
        caption: 'The widget’s ± figure is the scatter of the up count in one batch, not Lecture 3’s spread of single readings.',
        tryThis: [
          `Fire 10 atoms, then 1000. Compare the + count with ¾ of the atoms each time; at 1000 the ± figure is about ${d(V.l4Count1000Std, 1)} atoms.`,
          `Fire until the fraction settles near ${d(V.l4PsiUp, 2)}. The mean reading is then near $\\tfrac{\\hbar}{4}$, and still no atom reads it.`,
          'Clear and fire 10 atoms a few times. How often is the count exactly 3 : 1?',
        ],
      },
      clues: [],
      insight: 'An average belongs to many fresh preparations, not to one atom. The sandwich computes it in one step, in any basis.',
      pitfalls: [
        'Reading the mean $\\tfrac{\\hbar}{4}$ as a possible reading. Every atom reads $\\pm\\tfrac{\\hbar}{2}$.',
        'Confusing fresh preparations with re-measuring one atom. Only fresh preparations give the 3 : 1 mix.',
      ],
      play: [
        {
          id: 'l4-a-mean',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A negative mean',
          prompt: 'What is $\\langle S_z\\rangle$ for $0.6|{+z}\\rangle + 0.8|{-z}\\rangle$?',
          answer: V.l4ChMean68,
          tolerance: 0.005,
          unit: 'ħ',
          hints: [
            { text: 'Weight each result by its probability.' },
            { text: `$P(+) = ${d(V.l4ChYes68, 2)}$ and $P(-) = ${d(V.l4ChNo68, 2)}$.` },
            { text: `$\\tfrac12(${d(V.l4ChYes68, 2)}) - \\tfrac12(${d(V.l4ChNo68, 2)})$.` },
          ],
          walkthrough: [
            { text: `The weighted sum is $-${d(V.l4ChMean68Size, 2)}$ in units of ħ: negative, because − is more likely.` },
            { text: 'No atom reads that value; each reads $\\pm\\tfrac{\\hbar}{2}$.' },
          ],
        },
        {
          id: 'l4-a-erratum',
          kind: 'choice',
          tier: 'core',
          title: 'The mean of the example',
          prompt: 'Over many fresh preparations of $|\\psi\\rangle = \\tfrac{\\sqrt3}{2}|{+z}\\rangle + \\tfrac12|{-z}\\rangle$, what is the mean $S_z$ reading?',
          options: [
            { text: '0', correct: false, why: 'That is the mean for $|{+x}\\rangle$, carried over by mistake in the notes (p. 10).' },
            { text: '$\\tfrac{\\hbar}{4}$', correct: true, why: 'Right: $\\tfrac{\\hbar}{2}\\cdot\\tfrac34 - \\tfrac{\\hbar}{2}\\cdot\\tfrac14$.' },
            { text: '$\\tfrac{\\hbar}{2}$', correct: false, why: 'That is the most likely single reading, not the mean.' },
            { text: '$\\tfrac{\\sqrt3}{4}\\hbar$', correct: false, why: 'That is $\\langle S_x\\rangle$ for this state (Unit 4.6).' },
          ],
          hints: [
            { text: 'The mean depends on the probabilities, ¾ and ¼.' },
            { text: 'Use $\\langle A\\rangle = \\sum_i a_i P(a_i)$.' },
            { text: '$\\tfrac{\\hbar}{2}\\cdot\\tfrac34 - \\tfrac{\\hbar}{2}\\cdot\\tfrac14$.' },
          ],
          walkthrough: [
            { text: 'The weighted sum is $\\tfrac{\\hbar}{4}$.' },
            { text: 'The sandwich $\\langle\\psi|\\hat S_z|\\psi\\rangle$ gives the same.' },
            { text: 'A mean of zero would need equal probabilities.' },
          ],
        },
        {
          id: 'l4-a-yesno-mean',
          kind: 'numeric',
          tier: 'core',
          title: 'The mean of a yes/no question',
          prompt: 'What is the mean of the yes/no observable $\\hat P_{+z}$ in $|\\psi\\rangle = \\tfrac{\\sqrt3}{2}|{+z}\\rangle + \\tfrac12|{-z}\\rangle$?',
          answer: V.l4ChYesNoMean,
          tolerance: 0.005,
          hints: [
            { text: 'Its results are 1 and 0.' },
            { text: 'The mean is $1\\cdot P(\\text{yes}) + 0\\cdot P(\\text{no})$.' },
            { text: 'So the mean of a projector is a probability.' },
          ],
          walkthrough: [
            { text: `$P(\\text{yes}) = ${d(V.l4PsiUp, 2)}$, so the mean is ${d(V.l4ChYesNoMean, 2)}.` },
            { text: 'This is $\\langle\\psi|\\hat P_{+z}|\\psi\\rangle$: the Born rule is a special case of the mean.' },
          ],
        },
      ],
    },
    {
      id: 'l4-matrices',
      story: L4_STORY['l4-matrices'],
      review: L4_REVIEW['l4-matrices'],
      title: 'Spin matrices built from their outcomes',
      question: 'Given the definite states and their values, which matrix must each spin component be?',
      lecture: {
        pages: 'L4 pp. 13–16',
        summary:
          'In the $z$ basis each spin component becomes a 2×2 matrix. The eigen-conditions fix $S_z$ column by column. $S_x$ and $S_y$ follow from weighting their outcome projectors by $\\pm\\tfrac{\\hbar}{2}$; for $y$ the bra must be conjugated. Without the factor $\\tfrac{\\hbar}{2}$ they are the Pauli matrices, and all three are Hermitian.',
        equations: ['S_x = \\tfrac{\\hbar}{2}\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix},\\quad S_y = \\tfrac{\\hbar}{2}\\begin{pmatrix}0&-i\\\\i&0\\end{pmatrix},\\quad S_z = \\tfrac{\\hbar}{2}\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}'],
      },
      books: [
        { source: 'susskind', where: '§3.4', adds: 'The three spin matrices from their eigenvectors and eigenvalues, and the Pauli matrices.' },
        { source: 'townsend', where: '§2.4, pp. 46–50; §2.5–2.6, pp. 57–59; §3.6, pp. 94–96', adds: 'Matrix elements, the adjoint as the transpose conjugate, $S_z$ written in the $x$ basis, and the Pauli matrices by another route.' },
      ],
      visual: {
        kind: 'operator-builder',
        props: { axis: 'y' },
        tryThis: [
          'Step through $y$. At the projector step, check that $P_{+y}$ has +½ in its lower-right corner, not −½.',
          'Switch to $x$ and to $z$. Which step makes the diagonal of $S_x$ vanish?',
          'Choose “tilt”: at 60° the builder makes the tilted spin matrix whose + state is the $|\\psi\\rangle$ of Unit 4.3.',
        ],
      },
      clues: [],
      insight: 'A spin matrix is fixed by its definite states and their values. The same operator has different entries in different bases.',
      pitfalls: [
        'Forgetting to conjugate the bra of $|{+y}\\rangle$. The result is not Hermitian and squares to zero.',
        'Reading a matrix’s subscript as its basis. The subscript names the quantity measured; the basis only names the coordinates.',
      ],
      play: [
        {
          id: 'l4-m-m22',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The bottom-right entry',
          prompt: 'What is the entry $m_{22}$ of $S_z$?',
          answer: V.l4ChM22,
          tolerance: 0.005,
          unit: 'ħ',
          hints: [
            { text: 'Column 2 is where $\\hat S_z$ sends $\\binom01$.' },
            { text: '$\\hat S_z|{-z}\\rangle = -\\tfrac{\\hbar}{2}|{-z}\\rangle$.' },
            { text: 'Read the second component of that column.' },
          ],
          walkthrough: [
            { text: 'Column 2 is $-\\tfrac{\\hbar}{2}\\binom01$.' },
            { text: `So $m_{12} = 0$ and $m_{22} = -\\tfrac{\\hbar}{2}$, or −${d(-V.l4ChM22, 1)} in units of ħ.` },
          ],
        },
        {
          id: 'l4-m-py',
          kind: 'numeric',
          tier: 'core',
          title: 'Conjugate the bra',
          prompt: 'Build $P_{+y} = |{+y}\\rangle\\langle{+y}|$. What number sits in its lower-right corner?',
          answer: V.l4PyEntry11,
          tolerance: 0.005,
          hints: [
            { text: 'The bra is the conjugated row.' },
            { text: 'The bra of $|{+y}\\rangle$ is $\\tfrac{1}{\\sqrt2}(1\\;\\;-i)$.' },
            { text: 'The entry is $\\tfrac{i}{\\sqrt2}\\cdot\\tfrac{-i}{\\sqrt2}$.' },
          ],
          walkthrough: [
            { text: 'Row 2 of the ket is $i/\\sqrt2$, and column 2 of the bra is $-i/\\sqrt2$.' },
            { text: `Their product is $-i^2/2 = ${tf(V.l4PyEntry11)}$.` },
            { text: `The trap: forgetting to conjugate gives $-${tf(-V.l4ChNoConj11)}$.` },
          ],
        },
        {
          id: 'l4-m-noconj',
          kind: 'choice',
          tier: 'core',
          title: 'Spot the slip',
          prompt: 'A student writes $P_{+y} = \\tfrac12\\binom1i(1\\;\\;i) = \\tfrac12\\begin{pmatrix}1&i\\\\i&-1\\end{pmatrix}$. What went wrong, and how can you tell?',
          options: [
            { text: 'The bra was not conjugated: the result is not Hermitian, and it squares to zero instead of to itself', correct: true, why: 'Right. A projector must equal its own square and be Hermitian.' },
            { text: 'Nothing: it is correct', correct: false, why: 'Check the corner entries: $i$ and $i$ are not conjugates.' },
            { text: 'The $\\tfrac12$ should be $\\tfrac{1}{\\sqrt2}$', correct: false, why: 'The ket and the bra each carry $\\tfrac{1}{\\sqrt2}$, so their product carries $\\tfrac12$.' },
            { text: 'The ket should be $\\binom{i}{1}$', correct: false, why: 'That column is a multiple of $|{-y}\\rangle$, the other state.' },
          ],
          hints: [
            { text: 'A projector must equal its own square and be Hermitian.' },
            { text: 'Check the lower-right entry, then square the matrix.' },
            { text: 'Redo it with the bra $\\tfrac{1}{\\sqrt2}(1\\;\\;-i)$.' },
          ],
          walkthrough: [
            { text: `The student’s matrix squares to the zero matrix (largest entry ${d(V.l4ChNoConjSquare, 0)}), not to itself.` },
            { text: 'Its corner entries $i$ and $i$ are not conjugates, so it is not Hermitian.' },
            { text: 'Conjugating the bra gives $\\tfrac12\\begin{pmatrix}1&-i\\\\i&1\\end{pmatrix}$.' },
          ],
        },
        {
          id: 'l4-m-basis',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The same operator, new coordinates',
          prompt: 'Preview of Lecture 5: write $\\hat S_z$ in the $x$ basis $\\{|{+x}\\rangle, |{-x}\\rangle\\}$. What is its top-right entry $\\langle{+x}|\\hat S_z|{-x}\\rangle$?',
          answer: V.l4ChSzInX01,
          tolerance: 0.005,
          unit: 'ħ',
          hints: [
            { text: 'Each entry is a sandwich of $\\hat S_z$ between two states of the new basis.' },
            { text: '$\\hat S_z$ flips the sign of the $|{-z}\\rangle$ part, so $\\hat S_z|{-x}\\rangle = \\tfrac{\\hbar}{2}|{+x}\\rangle$.' },
            { text: 'Take the inner product with $|{+x}\\rangle$.' },
          ],
          walkthrough: [
            { text: `$\\langle{+x}|\\hat S_z|{-x}\\rangle = \\tfrac{\\hbar}{2}\\langle{+x}|{+x}\\rangle$, or ${d(V.l4ChSzInX01, 1)} in units of ħ.` },
            { text: 'The whole matrix is $\\tfrac{\\hbar}{2}\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$, the entries of our $S_x$ (Townsend p. 59).' },
          ],
        },
      ],
    },
    {
      id: 'l4-eigen',
      story: L4_STORY['l4-eigen'],
      review: L4_REVIEW['l4-eigen'],
      title: 'From a matrix back to outcomes',
      question: 'Given only the matrix, how do we recover the possible results and the definite states?',
      lecture: {
        pages: 'L4 pp. 16–20',
        summary:
          'Given only the matrix of an observable, the eigenvalue problem recovers everything. A nonzero solution of $(S_x - \\lambda I)\\binom{c_1}{c_2} = 0$ needs $\\det(S_x - \\lambda I) = 0$, which gives $\\pm\\tfrac{\\hbar}{2}$. Back-substitution, normalization and the phase convention then give $|{\\pm x}\\rangle$. With them, any state’s probabilities, update and mean follow.',
        equations: ['\\det(S_x - \\lambda I) = \\lambda^2 - \\tfrac{\\hbar^2}{4},\\qquad P(\\pm\\tfrac{\\hbar}{2}) = \\tfrac12|\\alpha \\pm \\beta|^2'],
      },
      books: [
        { source: 'susskind', where: '§3.7', adds: 'The same eigenvalue problem for a spin component along a tilted direction.' },
        { source: 'townsend', where: '§2.8, p. 67; §3.6, p. 94', adds: 'Why Hermitian eigenvalues are real, and the spin-½ eigenvalue problem.' },
      ],
      visual: {
        kind: 'operator-action',
        props: { preset: 'σx' },
        tryThis: [
          'Turn the test vector until the matrix only stretches or flips it. Those are the eigen-directions; what factors do you find?',
          'Press the preset I: every direction works. This is the repeated eigenvalue of Unit 4.1.',
          'Press the preset P+z: the factors are 1 and 0, the yes/no question of Unit 4.2.',
        ],
      },
      clues: [],
      insight: 'The determinant finds the possible results; back-substitution finds the definite states. Together they turn a matrix into a full measurement prediction.',
      pitfalls: [
        'Normalizing $\\binom11$ to $\\tfrac12\\binom11$. The squared components must add to 1.',
        'Thinking the phase convention changes the physics. It only picks one of many equal vectors.',
      ],
      play: [
        {
          id: 'l4-g-zero',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Can an atom read zero?',
          prompt: 'Evaluate $\\det(S_x - \\lambda I)$ at $\\lambda = 0$. Can 0 be a result of measuring $S_x$?',
          answer: V.l4DetAtZero,
          tolerance: 0.005,
          unit: 'ħ²',
          hints: [
            { text: 'At $\\lambda = 0$ the matrix is just $S_x$.' },
            { text: 'Multiply the diagonal pair, then subtract the product of the off-diagonal pair.' },
            { text: '$0\\cdot 0 - \\tfrac{\\hbar}{2}\\cdot\\tfrac{\\hbar}{2}$.' },
          ],
          walkthrough: [
            { text: `$\\det S_x = -\\tfrac{\\hbar^2}{4}$, or −${d(-V.l4DetAtZero, 2)} in units of ħ², which is not 0.` },
            { text: 'So $S_x$ has an inverse, and the only column it sends to zero is the zero column.' },
            { text: 'So 0 is not an eigenvalue, and no atom reads 0.' },
          ],
        },
        {
          id: 'l4-g-order',
          kind: 'order',
          tier: 'core',
          title: 'The recipe, in order',
          prompt: 'Put the steps for finding an observable’s results and definite states in order.',
          steps: [
            'Write $(A - \\lambda I)v = 0$ for an unknown nonzero column $v$',
            'Require $\\det(A - \\lambda I) = 0$',
            'Solve for the eigenvalues $\\lambda$',
            'Put each $\\lambda$ back to get the ratio of the components',
            'Normalize so that $v^\\dagger v = 1$ and fix the phase: first nonzero component real and positive',
          ],
          hints: [
            { text: 'You cannot find $v$ before you know $\\lambda$.' },
            { text: 'The determinant condition gives $\\lambda$ alone.' },
            { text: 'Normalizing and fixing the phase can be done in either order: a phase does not change length.' },
          ],
          walkthrough: [
            { text: 'The story of this unit runs these steps on $S_x$: the determinant gives $\\pm\\tfrac{\\hbar}{2}$, and back-substitution gives $c_2 = \\pm c_1$.' },
            { text: 'Normalizing and fixing the phase then gives $|{\\pm x}\\rangle$.' },
          ],
        },
        {
          id: 'l4-g-sx-prob',
          kind: 'numeric',
          tier: 'core',
          title: 'Practice: an x measurement',
          prompt: '$|\\psi\\rangle = 0.6|{+z}\\rangle + 0.8|{-z}\\rangle$ goes into an $S_x$ magnet. What is $P(+\\tfrac{\\hbar}{2})$?',
          answer: V.l4ChSx68Plus,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Use the eigenvector $|{+x}\\rangle$.' },
            { text: '$\\langle{+x}|\\psi\\rangle = (\\alpha + \\beta)/\\sqrt2$.' },
            { text: 'Square $1.4/\\sqrt2$.' },
          ],
          walkthrough: [
            { text: `The amplitude is $1.4/\\sqrt2$, so the probability is $1.96/2 = ${d(V.l4ChSx68Plus, 2)}$.` },
            { text: `$P(-) = 0.2^2/2 = ${d(V.l4ChSx68Minus, 2)}$, and the two add to 1.` },
          ],
        },
        {
          id: 'l4-g-shift',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A shifted problem',
          prompt: 'Solve the eigenvalue problem for $M = \\begin{pmatrix}2&1\\\\1&2\\end{pmatrix}$. What is its smaller eigenvalue?',
          answer: V.l4ChShiftLow,
          tolerance: 0.005,
          hints: [
            { text: 'Follow the same steps as for $S_x$.' },
            { text: '$\\det(M - \\lambda I) = (2 - \\lambda)^2 - 1$.' },
            { text: 'Notice that $M = 2I + \\sigma_x$.' },
          ],
          walkthrough: [
            { text: `$(2 - \\lambda)^2 = 1$ gives $\\lambda = ${d(V.l4ChShiftTop, 0)}$ or $\\lambda = ${d(V.l4ChShiftLow, 0)}$.` },
            { text: 'The rows give $c_2 = \\pm c_1$: the columns of $|{\\pm x}\\rangle$, the eigenvectors of $S_x$.' },
            { text: `Adding $2I$ shifts both eigenvalues by 2 and moves no eigenvector. In operator space the gauge reads $a_0 = ${d(V.l4ChShiftA0, 0)}$ and the arrow stays that of $\\sigma_x$, length 1 along $x$.` },
          ],
        },
        {
          id: 'l4-g-sy',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The y eigenproblem (homework)',
          assigned: 'L5 p.1',
          prompt: 'Homework (Lecture 5 notes, p. 1): find the eigenvalues and normalized eigenvectors of $S_y$, with the phase convention. Enter the imaginary part of the second component of the $+\\tfrac{\\hbar}{2}$ eigenvector.',
          answer: V.l4ChSyIm,
          tolerance: 0.005,
          hints: [
            { text: 'Follow the same steps as for $S_x$.' },
            { text: 'The determinant has the same shape; the off-diagonal product now involves $i$ and $-i$.' },
            { text: 'When you put $\\lambda$ back, keep the $i$: the ratio $c_2/c_1$ is not a real number.' },
          ],
          // assigned: hints only, and no walkthrough ships in the bundle (content test)
          walkthrough: [],
        },
      ],
    },
  ],
}
