import type { Lecture } from './schema'
import { URL } from './refs'
import { V, d } from './L5.values'
import { L5_STORY } from './L5.story'
import { L5_REVIEW } from './L5.review'

// Every number a learner sees in this lecture is computed in L5.values.ts, then asserted in keyed claims
// (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy). Plan: docs/roles/proposals/P-L5-story.md,
// with the judge's rulings: link-backs to Units 4.5 and 4.6 for the spin matrices and the S_x eigenproblem; the
// assigned S_y eigenproblem stays a hints-only challenge of Unit 4.6 (no L5 item works it); no ΔS_z in the core text;
// the Bloch stage as a plot of the three averages; B_{z←x} (output ← input) stated once; Townsend's phase for |−x⟩ is a
// books beat, not an erratum (the notes have no physics error; their scope and timing slips are instructor-facing).

export const L5: Lecture = {
  id: 'L5',
  number: 5,
  title: 'Spin matrices, expectation values and basis changes',
  outcomes: [
    'Compute the three spin averages of any state from its two $z$ amplitudes, and say which part of the column each one reads.',
    'Turn a matrix into its possible readings and definite states, and use those states as new coordinates.',
    'Rewrite a state’s column in another basis with the basis-change matrix, keeping the direction of the arrow straight.',
    'Rewrite an operator’s matrix in another basis, and explain why it is diagonal in its own eigenbasis.',
    'Show that averages and probabilities come out the same in every basis, and tell a relabelling from a rotation.',
  ],
  prerequisites: ['spin-matrices', 'expectation', 'projectors', 'inner-product', 'complex-amplitudes'],
  // Symbols defined in the text itself (symbol → the unit, beat or site whose sentence defines it). Kets, bras, ħ, i
  // and Lecture 4's spin matrices, projectors, eigen-notation and operator-space labels are mapped to the first unit's
  // title: a recap.
  symbols: {
    '|\\cdot\\rangle': 'l5-averages',
    '\\langle\\cdot|': 'l5-averages',
    '\\langle\\cdot|\\cdot\\rangle': 'l5-averages',
    '\\langle\\cdot\\rangle': 'l5-averages',
    '|\\psi\\rangle': 'l5-averages',
    '|+z\\rangle': 'l5-averages',
    '|-z\\rangle': 'l5-averages',
    '|+x\\rangle': 'l5-averages',
    '|-x\\rangle': 'l5-averages',
    '|+y\\rangle': 'l5-averages',
    '|-y\\rangle': 'l5-averages',
    '\\hbar': 'l5-averages',
    i: 'l5-averages',
    S_x: 'l5-averages',
    S_y: 'l5-averages',
    S_z: 'l5-averages',
    'P_+y': 'l5-averages',
    'P_-y': 'l5-averages',
    'P_+z': 'l5-averages',
    'P_+x': 'l5-averages',
    a_x: 'l5-averages',
    a_y: 'l5-averages',
    a_z: 'l5-averages',
    a_0: 'l5-averages',
    '\\alpha': 'l5-averages',
    '\\beta': 'l5-averages',
    I: 'l5-averages',
    P: 'l5-averages',
    '\\lambda': 'l5-averages',
    S_k: 'l5-averages:b1',
    '\\sigma_k': 'l5-averages:b1',
    k: 'l5-averages:b1',
    c_z: 'l5-averages:b2',
    c_1: 'l5-inverse:b1',
    c_2: 'l5-inverse:b1',
    '\\vec\\sigma': 'l5-inverse:b4',
    '\\sigma_n': 'l5-inverse:b4',
    n_x: 'l5-inverse:b4',
    n_y: 'l5-inverse:b4',
    n_z: 'l5-inverse:b4',
    A_jk: 'l5-inverse:b5',
    A_kj: 'l5-inverse:b5',
    '\\vec a': 'l5-inverse:b5',
    H: 'l5-inverse:b5',
    M: 'l5-inverse.play.l5-inv-values',
    u: 'l5-coordinates:b1',
    v: 'l5-coordinates:b1',
    c_x: 'l5-coordinates:b3',
    B: 'l5-coordinates:b4',
    '\\theta': 'l5-coordinates.visual.tryThis[1]',
    '\\phi': 'l5-coordinates.visual.tryThis[1]',
    p: 'l5-coordinates.play.l5-co-skew',
    q: 'l5-coordinates.play.l5-co-skew',
    A: 'l5-inverse.lecture',
    '|\\chi\\rangle': 'l5-operators:b1',
    '\\psi_z': 'l5-operators:b1',
    '\\chi_z': 'l5-operators:b1',
    '\\psi_x': 'l5-operators:b2',
    '\\chi_x': 'l5-operators:b2',
    A_new: 'l5-operators:b2',
    A_old: 'l5-operators:b2',
    v_1: 'l5-operators:b5',
    v_2: 'l5-operators:b5',
    '\\lambda_1': 'l5-operators:b5',
    '\\lambda_2': 'l5-operators:b5',
    D: 'l5-operators:b5',
    c_new: 'l5-invariance:b3',
    c_old: 'l5-invariance:b3',
    R_z: 'l5-invariance:b6',
    c: 'l5-invariance.play.l5-in-proof',
    c_y: 'l5-invariance.play.l5-in-ybasis.hints[0]',
    e: 'l5-invariance:b6',
  },
  watch: [
    { source: '3b1b', where: 'Change of basis', adds: 'The same vector described in two coordinate systems, and the matrix that translates between them, drawn with real arrows: the picture behind Unit 5.3.', url: URL.b3('change-of-basis') },
    { source: '3b1b', where: 'Eigenvectors and eigenvalues (the eigenbasis part)', adds: 'Why a matrix written in a basis of its own eigenvectors becomes diagonal: the picture behind Unit 5.4.', url: URL.b3('eigenvalues') },
  ],
  units: [
    {
      id: 'l5-averages',
      story: L5_STORY['l5-averages'],
      review: L5_REVIEW['l5-averages'],
      title: 'Three averages from one column',
      question: 'Given a state’s two $z$ amplitudes, what are the average spin readings along $x$, $y$ and $z$?',
      lecture: {
        pages: 'L5 pp. 2–5',
        summary:
          'With the spin matrices of Lecture 4, every average is one sandwich $\\langle\\psi|S_k|\\psi\\rangle$. The $z$ average reads the populations $|\\alpha|^2$ and $|\\beta|^2$. The $x$ and $y$ averages read the real and imaginary parts of the coherence $\\alpha^*\\beta$. For the notes’ complex state, $\\langle S_z\\rangle = \\tfrac{\\hbar}{4}$, $\\langle S_x\\rangle = 0$ and $\\langle S_y\\rangle = \\tfrac{\\sqrt3}{4}\\hbar$.',
        equations: ['\\langle S_z\\rangle = \\tfrac{\\hbar}{2}(\\lvert\\alpha\\rvert^2 - \\lvert\\beta\\rvert^2),\\qquad \\langle S_x\\rangle = \\hbar\\,\\mathrm{Re}(\\alpha^*\\beta),\\qquad \\langle S_y\\rangle = \\hbar\\,\\mathrm{Im}(\\alpha^*\\beta)'],
      },
      books: [
        { source: 'townsend', where: '§2.6, pp. 58–59; §3.6, pp. 94–96', adds: 'The average as a row times a matrix times a column, a complex worked example, and the Pauli matrices by another route.' },
        { source: 'susskind', where: '§3.4; §3.8', adds: 'The spin matrices from their eigenvectors, and the spin-polarization principle: the squared averages of the three σ’s add to 1.' },
      ],
      // Not the lazy Bloch widget of the plan: in a unit that is not the lecture's last, its late mount moves the later
      // units and their story triggers go stale (platform issue, reported). These bars read the same three averages.
      visual: {
        kind: 'amplitude-bars',
        props: { state: [60, 90], basis: 'z', editable: true },
        caption: 'Each basis is one measurement: half the difference of its two bars is that average, in units of ħ.',
        tryThis: [
          `Start at the notes’ state in the $z$ basis. The bars are the populations, ${d(V.l5PopUp, 2)} and ${d(V.l5PopDown, 2)}; half their difference is $\\langle S_z\\rangle = \\tfrac{\\hbar}{4}$.`,
          `Switch to the $x$ basis: both bars read ${d(V.l5ChYBasisProbZ, 2)}, so $\\langle S_x\\rangle = 0$, although the coherence is not zero. Now try $y$: about ${d(V.l5MeanSy)}ħ.`,
          'Move only the phase slider. The $z$ bars never move, while the $x$ and $y$ bars trade weight: the populations stay put and the coherence turns.',
        ],
      },
      clues: [],
      insight: 'One column gives all three averages. The populations fix the $z$ average; the coherence, a single complex number, fixes the other two.',
      pitfalls: [
        'Leaving out the conjugate in the bra. $\\langle S_y\\rangle$ then comes out 0 for every state, and $\\langle S_x\\rangle$ can even come out complex.',
        'Reading one point as one atom’s three values. Each average is measured on its own batch of freshly prepared atoms.',
      ],
      play: [
        {
          id: 'l5-av-pop',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Only the populations',
          prompt: 'A state has $c_z = (0.6,\\ 0.8i)$. Find $\\langle S_z\\rangle$.',
          answer: V.l5ChSz,
          tolerance: 0.002,
          unit: 'ħ',
          hints: [
            { text: 'Which parts of the column does the $z$ average depend on?' },
            { text: 'Only the populations: $\\langle S_z\\rangle = \\tfrac{\\hbar}{2}(|\\alpha|^2 - |\\beta|^2)$.' },
            { text: `$|\\alpha|^2 = ${d(V.l5ChPopUp, 2)}$, and $|0.8i|^2 = ${d(V.l5ChPopDown, 2)}$.` },
          ],
          walkthrough: [
            { text: `The populations are ${d(V.l5ChPopUp, 2)} and ${d(V.l5ChPopDown, 2)}; their difference is $-${d(V.l5ChPopDiffSize, 2)}$.` },
            { text: `Times $\\tfrac{\\hbar}{2}$: $\\langle S_z\\rangle = -${d(V.l5ChSzSize, 2)}\\,\\hbar$. It is negative because − is the likelier outcome.` },
            { text: 'The $i$ in $\\beta$ changed nothing here: it only turns the coherence.' },
          ],
        },
        {
          id: 'l5-av-coh',
          kind: 'numeric',
          tier: 'core',
          title: 'The coherence speaks',
          prompt: 'The same state, $c_z = (0.6,\\ 0.8i)$. Find $\\langle S_y\\rangle$.',
          answer: V.l5ChSy,
          tolerance: 0.002,
          unit: 'ħ',
          hints: [
            { text: 'The $y$ average is set by the coherence, not by the populations.' },
            { text: '$\\langle S_y\\rangle = \\hbar\\,\\mathrm{Im}(\\alpha^*\\beta)$.' },
            { text: '$\\alpha^* = 0.6$ and $\\beta = 0.8i$.' },
          ],
          walkthrough: [
            { text: `The coherence is $\\alpha^*\\beta = ${d(V.l5ChSy, 2)}i$; its imaginary part gives $\\langle S_y\\rangle = ${d(V.l5ChSy, 2)}\\,\\hbar$.` },
            { text: `Its real part is 0, so $\\langle S_x\\rangle = ${d(V.l5ChSxI, 0)}$. And $\\langle S_z\\rangle = -${d(V.l5ChSzSize, 2)}\\,\\hbar$, as in the warm-up.` },
          ],
        },
        {
          id: 'l5-av-phase',
          kind: 'choice',
          tier: 'core',
          title: 'Move one average, keep another',
          prompt: 'Which change can alter $\\langle S_x\\rangle$ without altering $\\langle S_z\\rangle$?',
          options: [
            {
              text: 'Multiply only $\\beta$ by a [[phase-factor|phase factor]]',
              correct: true,
              why: `Right: the populations keep their sizes while the coherence turns. For $(0.6, 0.8)$, $\\langle S_x\\rangle = ${d(V.l5ChSxReal, 2)}\\,\\hbar$; for $(0.6, 0.8i)$ it is ${d(V.l5ChSxI, 0)}.`,
            },
            { text: 'Multiply the whole column by a phase factor', correct: false, why: `A [[global-phase|global phase]] leaves $\\alpha^*\\beta$ alone: for $(0.6, 0.8)$, $\\langle S_x\\rangle$ stays ${d(V.l5ChSxGlobal, 2)}ħ.` },
            { text: 'Swap $\\alpha$ and $\\beta$', correct: false, why: `That flips the sign of $\\langle S_z\\rangle$, from $-${d(V.l5ChSzSize, 2)}\\,\\hbar$ to $+${d(V.l5ChSzSwap, 2)}\\,\\hbar$ for $(0.6, 0.8)$.` },
            { text: 'Nothing: the two averages are locked together', correct: false, why: 'They read different parts of the column; see the first option.' },
          ],
          hints: [
            { text: 'Which part of the column does each average read?' },
            { text: '$\\langle S_z\\rangle$ reads the populations; $\\langle S_x\\rangle$ reads $\\mathrm{Re}(\\alpha^*\\beta)$.' },
            { text: 'Try each change on $|\\alpha|^2$ and on $\\alpha^*\\beta$.' },
          ],
          walkthrough: [
            { text: 'Sort each change by what it does to the populations and to the coherence.' },
            { text: 'Only a phase on one entry, a [[relative-phase|relative phase]], keeps the populations and turns the coherence.' },
          ],
        },
        {
          id: 'l5-av-missing',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The missing average',
          prompt: 'A state has $\\langle S_z\\rangle = 0$, $\\langle S_x\\rangle = \\tfrac{\\hbar}{4}$ and $\\langle S_y\\rangle > 0$. Find $\\langle S_y\\rangle$.',
          answer: V.l5ChMissingSy,
          tolerance: 0.002,
          unit: 'ħ',
          hints: [
            { text: '$\\langle S_z\\rangle = 0$ fixes the populations.' },
            { text: 'Then $|\\alpha| = |\\beta| = 1/\\sqrt2$, so the coherence has size $\\tfrac12$.' },
            { text: 'Its real part is $\\tfrac14$; find the imaginary part from the size.' },
          ],
          walkthrough: [
            { text: 'The size squared is the real part squared plus the imaginary part squared: $\\tfrac14 = \\tfrac{1}{16} + \\mathrm{Im}^2$.' },
            { text: `So $\\mathrm{Im}(\\alpha^*\\beta) = \\tfrac{\\sqrt3}{4}$ and $\\langle S_y\\rangle \\approx ${d(V.l5ChMissingSy)}\\,\\hbar$.` },
            { text: 'Check with Susskind’s rule: the squares of $\\langle\\sigma_x\\rangle$, $\\langle\\sigma_y\\rangle$ and $\\langle\\sigma_z\\rangle$ add to 1.' },
          ],
        },
      ],
    },
    {
      id: 'l5-inverse',
      story: L5_STORY['l5-inverse'],
      review: L5_REVIEW['l5-inverse'],
      title: 'Matrix in, outcomes and states out',
      question: 'Handed only a matrix, how do we find its possible readings, and the states that give them for sure?',
      lecture: {
        pages: 'L5 pp. 1, 6–7',
        summary:
          'The eigenvalue problem of Lecture 4 turns a matrix $A$ into a measurement: its eigenvalues are the readings, and its unit eigenvectors the definite states. Those eigenvectors are orthonormal, so they can serve as new coordinate axes. The same recipe for $S_y$ is assigned homework.',
        equations: ['\\det(A - \\lambda I) = 0,\\qquad (A - \\lambda I)\\binom{c_1}{c_2} = 0'],
      },
      books: [
        { source: 'susskind', where: '§3.7', adds: 'The eigenvalue problem for a spin component along any direction: always ±1, with orthogonal eigenvectors.' },
        { source: 'townsend', where: '§2.4, p. 50; §3.6, p. 96', adds: 'Why a Hermitian matrix may have complex entries, and the spin-½ eigenvalue problem.' },
      ],
      visual: {
        kind: 'operator-action',
        props: { preset: 'σx' },
        tryThis: [
          'With $\\sigma_x$, find the two directions that only stretch or flip. Compare them with $\\tfrac{1}{\\sqrt2}(1, 1)$ and $\\tfrac{1}{\\sqrt2}(1, -1)$.',
          `Press the preset $\\begin{pmatrix}2&1\\\\1&2\\end{pmatrix}$. The special directions are those of $\\sigma_x$, but the stretch factors are now ${d(V.l5MEigHi, 0)} and ${d(V.l5MEigLo, 0)}. What changed, and what did not?`,
          'Press the $\\sigma_z$ preset, whose off-diagonal entry is 0. Why are the special directions now the axes themselves?',
        ],
      },
      clues: [],
      insight: 'A matrix carries its whole measurement inside it. The determinant gives the readings, back-substitution the definite states, and those states are ready-made coordinates.',
      pitfalls: [
        'Treating $-\\tfrac{1}{\\sqrt2}\\binom11$ as a new answer. A common factor of size 1 is the same state.',
        'Believing complex entries make readings complex. A Hermitian matrix always has real eigenvalues.',
      ],
      play: [
        {
          id: 'l5-inv-values',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The largest reading',
          prompt: '$M = \\begin{pmatrix}1&2\\\\2&1\\end{pmatrix}$, in units of ħ. What is its largest possible reading?',
          answer: V.l5ChInvTop,
          tolerance: 0.002,
          unit: 'ħ',
          hints: [
            { text: 'Readings are eigenvalues.' },
            { text: 'Set $\\det(M - \\lambda I) = 0$.' },
            { text: '$(1-\\lambda)^2 - 4 = 0$.' },
          ],
          walkthrough: [
            { text: `Multiplied out: $\\lambda^2 - ${d(-V.l5ChInvCharLin, 0)}\\lambda - ${d(-V.l5ChInvCharDet, 0)} = 0$, so $1 - \\lambda = \\pm2$.` },
            { text: `So $\\lambda = ${d(V.l5ChInvTop, 0)}$ or $\\lambda = -${d(V.l5ChInvLowSize, 0)}$, and the largest is ${d(V.l5ChInvTop, 0)} (ħ).` },
            { text: 'Aside: $M = I + 2\\sigma_x$, so it shares the eigenvectors of $\\sigma_x$.' },
          ],
        },
        {
          id: 'l5-inv-vector',
          kind: 'choice',
          tier: 'core',
          title: 'The second eigenvector',
          prompt: 'Which unit column is the eigenvector of $M = \\begin{pmatrix}1&2\\\\2&1\\end{pmatrix}$ for $\\lambda = -1$?',
          options: [
            { text: '$\\tfrac{1}{\\sqrt2}(1, 1)$', correct: false, why: 'That one belongs to $\\lambda = 3$.' },
            { text: '$\\tfrac{1}{\\sqrt2}(1, -1)$', correct: true, why: `Right: $M + I$ has both rows equal to $(2, 2)$, so the entries are opposite: $(${d(V.l5ChInvVec0)}, -${d(-V.l5ChInvVec1)})$.` },
            { text: '$(1, 0)$', correct: false, why: '$M$ sends it to $(1, 2)$, which is not a multiple of $(1, 0)$.' },
            { text: '$\\tfrac{1}{\\sqrt2}(1, i)$', correct: false, why: '$M$ sends it to $\\tfrac{1}{\\sqrt2}(1 + 2i,\\ 2 + i)$, which is not a multiple of it.' },
          ],
          hints: [
            { text: 'Put $\\lambda = -1$ back into $(M - \\lambda I)\\binom{c_1}{c_2} = 0$.' },
            { text: 'The top row reads $2c_1 + 2c_2 = 0$.' },
            { text: 'So $c_2 = -c_1$; then normalize.' },
          ],
          walkthrough: [
            { text: '$M + I = \\begin{pmatrix}2&2\\\\2&2\\end{pmatrix}$, so $c_2 = -c_1$.' },
            { text: `With $c_1$ real and positive and length 1: $(${d(V.l5ChInvVec0)}, -${d(-V.l5ChInvVec1)})$, that is $\\tfrac{1}{\\sqrt2}(1, -1)$.` },
            { text: 'It is orthogonal to the eigenvector for 3, as a Hermitian matrix requires.' },
          ],
        },
        {
          id: 'l5-inv-complex',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Complex entries, real readings',
          prompt: '$H = \\begin{pmatrix}2&1-i\\\\1+i&0\\end{pmatrix}$, in units of ħ, has complex entries. What is its largest reading?',
          answer: V.l5AEigUp,
          tolerance: 0.002,
          unit: 'ħ',
          hints: [
            { text: 'Check first that $H$ is Hermitian.' },
            { text: '$\\det(H - \\lambda I) = (2-\\lambda)(-\\lambda) - (1-i)(1+i)$.' },
            { text: `$(1-i)(1+i) = 2$, so $\\lambda^2 - ${d(-V.l5ChACharLin, 0)}\\lambda - ${d(-V.l5ChACharDet, 0)} = 0$.` },
          ],
          walkthrough: [
            { text: `$\\lambda = 1 \\pm \\sqrt3$, so the largest reading is $1 + \\sqrt3 \\approx ${d(V.l5AEigUp)}$ (ħ).` },
            { text: 'It equals $a_0 + |\\vec a|$ with $a_0 = 1$ and $\\vec a = (1, 1, 1)$: the operator-space reading of the story.' },
          ],
        },
      ],
    },
    {
      id: 'l5-coordinates',
      story: L5_STORY['l5-coordinates'],
      review: L5_REVIEW['l5-coordinates'],
      title: 'Same state, new coordinates',
      question: 'How do we rewrite a state’s column so that its entries are the amplitudes for an $x$ measurement?',
      lecture: {
        pages: 'L5 pp. 8–10',
        summary:
          'The same ket can be written in the $z$ basis or the $x$ basis. The basis-change matrix $B_{z\\leftarrow x}$ has the $x$ kets as columns and turns $x$ coordinates into $z$ coordinates. Its columns are orthonormal, so the way back is its conjugate transpose, whose rows are the bras $\\langle{\\pm x}|$.',
        equations: ['c_z = B_{z\\leftarrow x}\\,c_x,\\qquad c_x = B_{x\\leftarrow z}\\,c_z = B_{z\\leftarrow x}^\\dagger\\,c_z'],
      },
      books: [
        { source: 'townsend', where: '§2.5, pp. 54–55', adds: 'The change-of-basis matrix from overlaps, by inserting the identity between a bra and a ket.' },
      ],
      visual: {
        kind: 'basis-translator',
        props: { target: 'x', mode: 'state', theta: 60, phi: 0 },
        tryThis: [
          `Read the $x$ column and square its entries. Do you get ${d(V.l5Psi30XUp)} and ${d(V.l5Psi30XDown)}, the $x$ bars of the story?`,
          'The slider $\\theta$ sets the populations, $|\\alpha|^2 = \\cos^2\\tfrac{\\theta}{2}$, and $\\phi$ is the phase of $\\beta$. Set $\\theta = 90^\\circ$ with $\\phi = 0$: this is $|{+x}\\rangle$. Which column does it get in $x$ coordinates?',
          'Switch the new basis to $y$. The note saying the two matrices look alike disappears. Compare $B_{z\\leftarrow y}$ with $B_{y\\leftarrow z}$ entry by entry.',
        ],
      },
      clues: [],
      insight: 'A column is a list of amplitudes for one named basis. Changing the basis changes the list, never the state.',
      pitfalls: [
        'Using $B_{z\\leftarrow x}$ where $B_{x\\leftarrow z}$ is needed. For the $x$ basis the two agree by luck; for $y$ they do not.',
        'Taking the dagger as the inverse for any pair of basis arrows. It works only when the arrows are orthonormal.',
      ],
      play: [
        {
          id: 'l5-co-u',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The first x amplitude',
          prompt: '$c_z = (0.6,\\ 0.8)$. Find the $x$ amplitude $u = \\langle{+x}|\\psi\\rangle$.',
          answer: V.l5ChCoU,
          tolerance: 0.002,
          hints: [
            { text: 'Use the top row of $B_{x\\leftarrow z}$.' },
            { text: 'That row is the bra $\\langle{+x}| = \\tfrac{1}{\\sqrt2}(1, 1)$.' },
            { text: '$u = (\\alpha + \\beta)/\\sqrt2$.' },
          ],
          walkthrough: [{ text: `$(0.6 + 0.8)/\\sqrt2 = 1.4/\\sqrt2 \\approx ${d(V.l5ChCoU, 4)}$.` }],
        },
        {
          id: 'l5-co-prob',
          kind: 'numeric',
          tier: 'core',
          title: 'Down along x',
          prompt: 'The same state. What is the probability of reading $-\\tfrac{\\hbar}{2}$ along $x$?',
          answer: V.l5ChCoProbMinus,
          tolerance: 0.001,
          unit: 'probability',
          hints: [
            { text: 'It is the squared size of an $x$ amplitude.' },
            { text: 'Which row of $B_{x\\leftarrow z}$ gives $v$?' },
            { text: '$v = (\\alpha - \\beta)/\\sqrt2$.' },
          ],
          walkthrough: [
            { text: `$v = (0.6 - 0.8)/\\sqrt2 \\approx -${d(V.l5ChCoVSize, 4)}$, and $v^2 = ${d(V.l5ChCoProbMinus, 2)}$.` },
            { text: `Check: $u^2 + v^2 = ${d(V.l5ChCoProbPlus, 2)} + ${d(V.l5ChCoProbMinus, 2)} = 1$.` },
          ],
        },
        {
          id: 'l5-co-arrow',
          kind: 'choice',
          tier: 'core',
          title: 'Which way does it go?',
          prompt: 'Which matrix turns $z$ coordinates into $y$ coordinates?',
          options: [
            { text: '$\\tfrac{1}{\\sqrt2}\\begin{pmatrix}1&1\\\\ i&-i\\end{pmatrix}$', correct: false, why: 'That is $B_{z\\leftarrow y}$: it goes the other way.' },
            { text: '$\\tfrac{1}{\\sqrt2}\\begin{pmatrix}1&-i\\\\1&i\\end{pmatrix}$', correct: true, why: 'Right: $B_{y\\leftarrow z} = B_{z\\leftarrow y}^\\dagger$, whose rows are the bras $\\langle{\\pm y}|$.' },
            { text: '$\\tfrac{1}{\\sqrt2}\\begin{pmatrix}1&i\\\\1&-i\\end{pmatrix}$', correct: false, why: 'Transposed but not conjugated.' },
            { text: '$\\tfrac{1}{\\sqrt2}\\begin{pmatrix}1&1\\\\1&-1\\end{pmatrix}$', correct: false, why: 'That belongs to the $x$ basis.' },
          ],
          hints: [
            { text: 'Start from the matrix whose columns are $|{\\pm y}\\rangle$ in $z$ coordinates.' },
            { text: 'Which way does that one go?' },
            { text: 'Undo it with the conjugate transpose.' },
          ],
          walkthrough: [
            { text: 'The columns $\\tfrac{1}{\\sqrt2}(1, \\pm i)$ make $B_{z\\leftarrow y}$.' },
            { text: 'Transpose and conjugate it: the rows become the bras $\\langle{\\pm y}| = \\tfrac{1}{\\sqrt2}(1, \\mp i)$.' },
          ],
        },
        {
          id: 'l5-co-skew',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A skewed basis',
          prompt: 'Use the pair $|{+z}\\rangle$, $|{+x}\\rangle$, which is not orthogonal, as a basis. Write $|{-z}\\rangle = p\\,|{+z}\\rangle + q\\,|{+x}\\rangle$. Find $q$.',
          answer: V.l5ChSkewQ,
          tolerance: 0.002,
          hints: [
            { text: 'The dagger shortcut fails here. Why?' },
            { text: 'Match entries: $(0, 1) = p\\,(1, 0) + q\\,\\tfrac{1}{\\sqrt2}(1, 1)$.' },
            { text: 'The bottom entry gives $q$ at once.' },
          ],
          walkthrough: [
            { text: `Bottom entry: $1 = q/\\sqrt2$, so $q = \\sqrt2 \\approx ${d(V.l5ChSkewQ)}$. Top entry: $0 = p + q/\\sqrt2$, so $p = -${d(-V.l5ChSkewP, 0)}$.` },
            { text: `The dagger would give $(0,\\ ${d(V.l5ChSkewDagger)})$ instead, which is wrong: for this pair $B^\\dagger B \\ne I$.` },
          ],
        },
      ],
    },
    {
      id: 'l5-operators',
      story: L5_STORY['l5-operators'],
      review: L5_REVIEW['l5-operators'],
      title: 'Operators change coordinates too',
      question: 'How must an operator’s matrix change with the basis, and why is it diagonal in its own eigenbasis?',
      lecture: {
        pages: 'L5 pp. 11–13',
        summary:
          'An operator acting on a state is one fact, written in any basis. Its matrix in $x$ coordinates is $B_{x\\leftarrow z}A^{(z)}B_{z\\leftarrow x}$. In a basis of its own eigenvectors the matrix is diagonal, with the eigenvalues on the diagonal. The same numbers can describe different components in different bases.',
        equations: ['A^{(x)} = B_{x\\leftarrow z}\\,A^{(z)}\\,B_{z\\leftarrow x},\\qquad AB = BD,\\ B^\\dagger B = I \\;\\Rightarrow\\; B^\\dagger AB = D'],
      },
      books: [
        { source: 'townsend', where: '§2.4, pp. 48–49; §2.5, pp. 55–57', adds: 'An operator is diagonal in its eigenbasis, and $S_z$ written in the $x$ basis with two phase choices.' },
      ],
      visual: {
        kind: 'basis-translator',
        props: { target: 'x', mode: 'operator', operator: 'Sx' },
        tryThis: [
          'With $S_x$ in the $x$ basis the widget says diagonal. Switch the operator to $S_z$: which numbers appear, and which spin component is it still?',
          'Switch to the $y$ basis. Which of the three operators is diagonal there, and what sits on its diagonal?',
          'Still in the $y$ basis, look at $S_x^{(y)}$. Whose $z$-basis numbers does it copy?',
        ],
      },
      clues: [],
      insight: 'The operator is fixed; only its table of numbers depends on the basis. In its own eigenbasis the table is as simple as it gets: the readings, down the diagonal.',
      pitfalls: [
        'Reading $S_z^{(x)}$ as the $x$ spin because its entries match $S_x^{(z)}$. For an operator the subscript names what is measured and the superscript names the basis.',
        'Reading $B_{x\\leftarrow z}A^{(z)}B_{z\\leftarrow x}$ from left to right. The matrix next to the column acts first.',
      ],
      play: [
        {
          id: 'l5-op-label',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Same numbers, which spin?',
          prompt: '$S_z^{(x)}$ has the same numbers as $S_x^{(z)}$. Which observable does $S_z^{(x)}$ describe?',
          options: [
            { text: 'The $z$ component of spin', correct: true, why: 'Right: the subscript names the component, the superscript the coordinates.' },
            { text: 'The $x$ component of spin', correct: false, why: 'That mixes up the two labels.' },
            { text: 'Both at once', correct: false, why: 'One matrix in one stated basis is one operator.' },
            { text: 'Neither', correct: false, why: 'See the first option.' },
          ],
          hints: [
            { text: 'What does the subscript name?' },
            { text: 'What does the superscript name?' },
            { text: 'Changing coordinates cannot change which magnet you use.' },
          ],
          walkthrough: [
            { text: 'Subscript $z$: the $z$ magnet. Superscript $(x)$: the numbers are written in $x$ coordinates.' },
            { text: 'Matching the numbers of $S_x^{(z)}$ is a coincidence of this pair of bases.' },
          ],
        },
        {
          id: 'l5-op-order',
          kind: 'order',
          tier: 'core',
          title: 'Right to left',
          prompt: 'Order the steps of computing $\\chi_x = B_{x\\leftarrow z}A^{(z)}B_{z\\leftarrow x}\\,\\psi_x$.',
          steps: [
            'Start from the $x$ column $\\psi_x$',
            '$B_{z\\leftarrow x}$ turns it into the $z$ column $\\psi_z$',
            '$A^{(z)}$ acts on the $z$ column, giving $\\chi_z$',
            '$B_{x\\leftarrow z}$ turns $\\chi_z$ back into the $x$ column $\\chi_x$',
          ],
          hints: [
            { text: 'Matrices act on the column to their right.' },
            { text: 'Read the product from right to left.' },
            { text: 'The matrix next to $\\psi_x$ must accept $x$ coordinates.' },
          ],
          walkthrough: [
            { text: 'The rightmost matrix, $B_{z\\leftarrow x}$, meets $\\psi_x$ first and hands a $z$ column to $A^{(z)}$.' },
            { text: '$B_{x\\leftarrow z}$ is last: it hands the result back in $x$ coordinates.' },
          ],
        },
        {
          id: 'l5-op-eigenbasis',
          kind: 'numeric',
          tier: 'core',
          title: 'Diagonal for free',
          prompt: '$M = \\begin{pmatrix}1&2\\\\2&1\\end{pmatrix}$, in units of ħ. Find the top-left entry of $M^{(x)}$.',
          answer: V.l5ChOpTop,
          tolerance: 0.002,
          unit: 'ħ',
          hints: [
            { text: 'Are $|{\\pm x}\\rangle$ eigenvectors of $M$?' },
            { text: 'If so, $M^{(x)}$ is diagonal.' },
            { text: 'The top-left entry is the eigenvalue of the first column, $|{+x}\\rangle$.' },
          ],
          walkthrough: [
            { text: `$M|{+x}\\rangle = ${d(V.l5ChInvTop, 0)}|{+x}\\rangle$ and $M|{-x}\\rangle = -|{-x}\\rangle$.` },
            { text: `So $M^{(x)} = \\mathrm{diag}(${d(V.l5ChInvTop, 0)}, -${d(V.l5ChInvLowSize, 0)})$, and its top-left entry is ${d(V.l5ChOpTop, 0)}.` },
          ],
        },
        {
          id: 'l5-op-sy-in-x',
          kind: 'choice',
          tier: 'stretch',
          title: 'S_y in the x basis',
          prompt: 'What is $S_y$ in the $x$ basis?',
          options: [
            { text: '$\\tfrac{\\hbar}{2}\\begin{pmatrix}0&-i\\\\ i&0\\end{pmatrix}$', correct: false, why: 'That is $S_y^{(z)}$; the matrix must change.' },
            { text: '$\\tfrac{\\hbar}{2}\\begin{pmatrix}0&i\\\\ -i&0\\end{pmatrix}$', correct: true, why: 'Right: the minus signs trade places, so $S_y^{(x)}$ is minus the numbers of $S_y^{(z)}$.' },
            { text: '$\\tfrac{\\hbar}{2}\\,\\mathrm{diag}(1, -1)$', correct: false, why: 'The $x$ basis is not the eigenbasis of $S_y$.' },
            { text: '$\\tfrac{\\hbar}{2}\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$', correct: false, why: 'That is $S_z^{(x)}$.' },
          ],
          hints: [
            { text: 'Use $B_{x\\leftarrow z}S_yB_{z\\leftarrow x}$; here the two arrows have the same entries.' },
            { text: 'Compute $S_yB_{z\\leftarrow x}$ first: $\\tfrac{\\hbar}{2\\sqrt2}\\begin{pmatrix}-i&i\\\\ i&i\\end{pmatrix}$.' },
            { text: 'Then multiply by $B_{x\\leftarrow z}$ on the left.' },
          ],
          walkthrough: [
            { text: `The product has top-right entry $+${d(V.l5ChSyInX01Im, 1)}i$ and bottom-left entry $-${d(V.l5ChSyInX01Im, 1)}i$ (ħ = 1), and zeros on the diagonal.` },
            { text: 'That is minus the numbers of $S_y^{(z)}$: same operator, new table.' },
          ],
        },
      ],
    },
    {
      id: 'l5-invariance',
      story: L5_STORY['l5-invariance'],
      review: L5_REVIEW['l5-invariance'],
      title: 'Predictions ignore the coordinates',
      question: 'Why does every average and every probability come out the same in any basis?',
      lecture: {
        pages: 'L5 pp. 14–15',
        summary:
          'Convert the column and the matrix together and every average survives, because the inner $BB^\\dagger$ pairs collapse to $I$. The state $|{+z}\\rangle$ still gives $\\langle S_z\\rangle = \\tfrac{\\hbar}{2}$ in $x$ coordinates, although both $x$ entries are nonzero. A basis change only relabels; a rotation, next lecture, changes the state.',
        equations: ['c_{\\text{new}}^\\dagger A^{(\\text{new})}c_{\\text{new}} = c_{\\text{old}}^\\dagger A^{(\\text{old})}c_{\\text{old}}'],
      },
      books: [
        { source: 'townsend', where: '§2.5, p. 56; §2.6, pp. 58–59', adds: 'Eigenvalue equations and expectation values hold in every representation; one basis makes the operator simple, another the state.' },
      ],
      visual: {
        kind: 'amplitude-bars',
        props: { state: '+z', basis: 'x', editable: true },
        tryThis: [
          `The $x$ amplitudes of $|{+z}\\rangle$ are both ${d(V.l5ZcxU)}. Switch the basis to $z$. Is the $z$ reading uncertain?`,
          `Set $\\theta = 60^\\circ$ and $\\phi = 90^\\circ$, the state of Unit 5.1. The $y$ bars read ${d(V.l5ChPsiExY)} and ${d(V.l5ChPsiExMinusY)}; half their difference, in units of ħ, is $\\langle S_y\\rangle$. Does it match?`,
          'Pick any state and read its $x$ bars. Switch to $z$ and back: the bars change with the basis, but the state, set by the sliders, never did.',
        ],
      },
      clues: [],
      insight: 'Physics lives in the state and the operator, not in their tables of numbers. Change both tables together and no prediction can tell.',
      pitfalls: [
        'Pairing a column from one basis with a matrix from another. The result describes nothing.',
        'Calling a change of basis a rotation of the atoms. It relabels the same state; a rotation makes a new one.',
      ],
      play: [
        {
          id: 'l5-in-plusx',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The z average of |+x⟩',
          prompt: '$|{+x}\\rangle$ in $x$ coordinates is $(1, 0)$, and $S_z^{(x)} = \\tfrac{\\hbar}{2}\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$. Find $\\langle S_z\\rangle$.',
          answer: V.l5XMeanZInX,
          tolerance: 0.001,
          unit: 'ħ',
          hints: [
            { text: 'In any one basis, $\\langle S_z\\rangle$ is the column’s conjugate row, times the matrix, times the column.' },
            { text: '$S_z^{(x)}$ sends $(1, 0)$ to $\\tfrac{\\hbar}{2}(0, 1)$.' },
            { text: 'Take the inner product with $(1, 0)$.' },
          ],
          walkthrough: [
            { text: `$(1, 0)$ against $\\tfrac{\\hbar}{2}(0, 1)$ gives ${d(V.l5XMeanZInX, 0)}.` },
            { text: `In $z$ coordinates the same state gives $\\langle S_z\\rangle = ${d(V.l5XMeanZ, 0)}$ too.` },
          ],
        },
        {
          id: 'l5-in-sx',
          kind: 'numeric',
          tier: 'core',
          title: 'Where S_x is simple',
          prompt: 'For $c_z = (\\tfrac{\\sqrt3}{2},\\ \\tfrac12)$, compute $\\langle S_x\\rangle$ in $x$ coordinates, where $S_x$ is diagonal.',
          answer: V.l5ChSxInXMean,
          tolerance: 0.002,
          unit: 'ħ',
          hints: [
            { text: 'Convert the column first.' },
            { text: `$c_x = (${d(V.l5Psi30U)},\\ ${d(V.l5Psi30V)})$ and $S_x^{(x)} = \\tfrac{\\hbar}{2}\\,\\mathrm{diag}(1, -1)$.` },
            { text: '$\\langle S_x\\rangle = \\tfrac{\\hbar}{2}(|u|^2 - |v|^2)$.' },
          ],
          walkthrough: [
            { text: `$\\tfrac12(${d(V.l5Psi30XUp)} - ${d(V.l5Psi30XDown)}) \\approx ${d(V.l5ChSxInXMean)}$ (ħ).` },
            { text: `Check in $z$ coordinates: $\\hbar\\,\\mathrm{Re}(\\alpha^*\\beta) = \\tfrac{\\sqrt3}{4}\\hbar \\approx ${d(V.l5ChSxInZMean)}\\,\\hbar$.` },
          ],
        },
        {
          id: 'l5-in-proof',
          kind: 'choice',
          tier: 'core',
          title: 'What makes it collapse',
          prompt: 'For a column $c$, the invariance proof collapses $(c^\\dagger B)(B^\\dagger AB)(B^\\dagger c)$ to $c^\\dagger Ac$. Which fact does it use?',
          options: [
            { text: '$BB^\\dagger = I$', correct: true, why: 'Right. For a square $B$ it follows from $B^\\dagger B = I$.' },
            { text: '$B = B^\\dagger$', correct: false, why: 'True for the $x$ basis only; false for $y$.' },
            { text: '$B^2 = I$', correct: false, why: 'For the $y$ basis $B^2 \\ne I$.' },
            { text: '$AB = BA$', correct: false, why: 'The proof never swaps $A$ and $B$.' },
          ],
          hints: [
            { text: 'Look at the two places where $B$ meets $B^\\dagger$.' },
            { text: 'In which order do they meet?' },
            { text: 'Which identity turns that order into $I$?' },
          ],
          walkthrough: [
            { text: 'Regroup: $c^\\dagger(BB^\\dagger)A(BB^\\dagger)c$.' },
            { text: 'With $BB^\\dagger = I$ both brackets vanish, leaving $c^\\dagger Ac$.' },
          ],
        },
        {
          id: 'l5-in-ybasis',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A probability in y coordinates',
          prompt: 'For the notes’ state $c_z = (\\tfrac{\\sqrt3}{2},\\ \\tfrac{i}{2})$, find the probability of $+\\tfrac{\\hbar}{2}$ along $x$ entirely in $y$ coordinates: transform both the state and the projector $P_{+x}$.',
          answer: V.l5ChYBasisProb,
          tolerance: 0.002,
          unit: 'probability',
          hints: [
            { text: '$P_{+x}^{(y)} = B_{y\\leftarrow z}P_{+x}B_{z\\leftarrow y}$, and $c_y = B_{y\\leftarrow z}c_z$.' },
            { text: 'The answer must equal the one in $z$ coordinates.' },
            { text: 'In $z$ coordinates, $P(+x) = \\tfrac12|\\alpha + \\beta|^2$.' },
          ],
          walkthrough: [
            { text: `Build $c_y$ and $P_{+x}^{(y)}$, then take $c_y^\\dagger P_{+x}^{(y)}c_y = ${d(V.l5ChYBasisProb, 1)}$.` },
            { text: `Check: $\\tfrac12|\\tfrac{\\sqrt3}{2} + \\tfrac{i}{2}|^2 = ${d(V.l5ChYBasisProbZ, 1)}$.` },
          ],
        },
      ],
    },
  ],
}
