import type { Lecture } from './schema'
import { V, claim, d, pct } from './L6.values'
import { L6_STORY } from './L6.story'
import { L6_REVIEW } from './L6.review'

// Every number a learner sees in this lecture is computed in L6.values.ts, then asserted in keyed claims
// (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy). Plan: docs/roles/proposals/P-L6-story.md,
// with the judge's rulings: Lecture 5 owns the basis-change machinery (one link-back beat, `l6-active:b1`); the notes'
// equatorial θ is written φ (one Rosetta line, `l6-equator:b4`); no rotation past 180° (the 360° sign is Lecture 7 §7.2);
// the time-evolution beat and the mixtures unit are beyond the lecture. The notes contain no physics error, so there is
// no errata box: the plan's E2 is the Rosetta line, E3–E6 are cosmetic, E9 cites the printed page only.

export const L6: Lecture = {
  id: 'L6',
  number: 6,
  title: 'Basis changes, the Bloch sphere and rotations',
  outcomes: [
    'Turn any spin state into its point on the Bloch sphere, and read the three averages and the odds along any axis off that point.',
    'Explain why the relative phase of the two z amplitudes is the longitude, and why an overall phase moves nothing.',
    'Tell a passive change of basis from an active rotation, and turn a state about the z axis with the rotation operator.',
    'Build the rotation operator as the exponential of the z spin matrix, and use its small-angle form to say how a state starts to turn.',
    'Place a mixture inside the Bloch ball and tell it apart from a superposition (beyond the lecture).',
  ],
  prerequisites: ['basis-change', 'expectation', 'complex-amplitudes', 'eigen-problem', 'spin-averages'],
  // Symbols defined in the text itself (symbol → the unit, beat or site whose sentence defines it). Kets, bras, ħ, i, e,
  // the spin matrices, the amplitudes α, β and Lecture 5's basis-change names are mapped to the first unit: a recap.
  symbols: {
    '|\\cdot\\rangle': 'l6-bloch',
    '\\langle\\cdot|': 'l6-bloch',
    '\\langle\\cdot|\\cdot\\rangle': 'l6-bloch',
    '\\langle\\cdot\\rangle': 'l6-bloch',
    '|\\psi\\rangle': 'l6-bloch',
    '|+z\\rangle': 'l6-bloch',
    '|-z\\rangle': 'l6-bloch',
    '|+x\\rangle': 'l6-bloch',
    '|-x\\rangle': 'l6-bloch',
    '|+y\\rangle': 'l6-bloch',
    '|-y\\rangle': 'l6-bloch',
    '\\hbar': 'l6-bloch',
    i: 'l6-bloch',
    e: 'l6-bloch',
    S_x: 'l6-bloch',
    S_y: 'l6-bloch',
    S_z: 'l6-bloch',
    '\\alpha': 'l6-bloch',
    '\\beta': 'l6-bloch',
    P: 'l6-bloch',
    I: 'l6-bloch',
    '\\hat n': 'l6-bloch',
    '\\psi_z': 'l6-bloch',
    '\\psi_x': 'l6-bloch',
    A: 'l6-bloch',
    a_x: 'l6-bloch',
    a_z: 'l6-bloch',
    '\\dagger': 'l6-bloch',
    '\\pi': 'l6-bloch',
    '\\arccos': 'l6-bloch.play.l6-b-theta',
    '|\\xi\\rangle': 'l6-bloch.play.l6-b-opposite',
    '|\\psi_\\star\\rangle': 'l6-bloch.play.l6-b-opposite',
    '\\vec r_\\xi': 'l6-bloch.play.l6-b-opposite',
    '\\vec r_\\star': 'l6-bloch.play.l6-b-opposite',
    '|\\psi(\\varphi)\\rangle': 'l6-equator:b4',
    '|i\\rangle': 'l6-equator:b6.refs[0]',
    '\\chi': 'l6-equator:b7',
    '\\varphi_0': 'l6-active:b2',
    '\\varphi_1': 'l6-active:b4',
    '\\varphi_2': 'l6-active:b4',
    'p_\\pm': 'l6-active:b5',
    S_n: 'l6-active:b5',
    '\\hat m': 'l6-active:b8',
    '\\hat x': 'l6-active:b8',
    '\\hat z': 'l6-active:b8',
    M: 'l6-generator:b1',
    w: 'l6-generator.visual',
    '\\hat y': 'l6-generator.play.l6-g-velocity',
    '\\vec r_mix': 'l6-mixture.lecture',
    w_k: 'l6-mixture.lecture',
    '\\vec r_k': 'l6-mixture.lecture',
    a: 'l6-generator:b2',
    b: 'l6-generator:b2',
    '\\hat J_z': 'l6-generator:b6',
    N: 'l6-generator:b6',
    '\\varepsilon': 'l6-generator:b7',
    t: 'l6-generator:b7',
    S: 'l6-generator:b8',
  },
  units: [
    {
      id: 'l6-bloch',
      story: L6_STORY['l6-bloch'],
      review: L6_REVIEW['l6-bloch'],
      title: 'Three averages make a point',
      question: 'How can one picture hold every pure spin state?',
      lecture: {
        pages: 'L6 pp. 1, 7',
        summary:
          'Scale the three spin averages by $2/\\hbar$ and use them as coordinates: the Bloch vector $\\vec r$. For every pure state its length is 1, so the states fill the surface of a unit sphere. The poles are $|{\\pm z}\\rangle$ and the equator holds $|{\\pm x}\\rangle$ and $|{\\pm y}\\rangle$. The coordinates are averages over many atoms, never three readings of one.',
        equations: ['\\vec r = \\tfrac{2}{\\hbar}\\big(\\langle S_x\\rangle, \\langle S_y\\rangle, \\langle S_z\\rangle\\big) = \\big(2\\,\\mathrm{Re}\\,\\alpha^*\\beta,\\ 2\\,\\mathrm{Im}\\,\\alpha^*\\beta,\\ |\\alpha|^2 - |\\beta|^2\\big),\\qquad |\\vec r| = 1'],
      },
      books: [
        { source: 'susskind', where: '§2.5; §3.8', adds: 'Counting parameters: two angles are all a spin state has. The spin-polarization principle: the point itself is the axis along which the state reads + for certain.' },
        { source: 'townsend', where: 'Problem 1.3, p. 26', adds: 'The + state along any direction, written with the two Bloch angles.' },
      ],
      visual: {
        kind: 'bloch',
        props: { theta: 60, phi: 45, editable: true, landmarks: true, measure: 'z' },
        caption: 'The sliders set the polar angle $\\theta$ and the azimuth $\\varphi$; the table reads the three averages, and the bars the odds along $z$.',
        tryThis: [
          'Press each landmark button in turn. For which states is the amplitude $\\beta$ of $|{-z}\\rangle$ zero, and for which is it as large as $\\alpha$?',
          `Find a state that a $z$ magnet sends up ${pct(V.l6Theta90P)} of the time. Which $\\theta$ does it need, and does $\\varphi$ matter? (Check: about $${d(V.l6Theta90, 1)}^\\circ$, whatever $\\varphi$ is.)`,
          `Hold $\\theta$ at $60^\\circ$ and move $\\varphi$. Which of the three averages change? $\\langle S_z\\rangle$ should stay at ${d(V.l6AvgStarZ, 2)}ħ.`,
        ],
      },
      clues: [],
      insight: 'A spin state is a direction. Its three averages are the coordinates of one point on a unit sphere, and every atom still reads only $\\pm\\tfrac{\\hbar}{2}$.',
      pitfalls: [
        'Reading the point as three values carried by one atom. Each coordinate is an average over its own batch of atoms.',
        'Taking opposite points for opposite vectors. Opposite points are orthogonal states; $-|\\psi\\rangle$ is the same point as $|\\psi\\rangle$.',
      ],
      play: [
        {
          id: 'l6-b-theta',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'How far down?',
          prompt: 'A state has $\\psi_z = (0.6,\\ 0.8)$. What is the polar angle $\\theta$ of its Bloch point, in degrees?',
          answer: V.l6ChTheta,
          tolerance: 0.1,
          unit: '°',
          hints: [
            { text: 'Unit 5.1 gave the $z$ average of a column like this one. Turn it into a height.' },
            { text: 'The height is $r_z = \\cos\\theta$.' },
            { text: `$r_z = |\\alpha|^2 - |\\beta|^2 = ${d(V.l6ChPopUp, 2)} - ${d(V.l6ChPopDown, 2)}$.` },
          ],
          walkthrough: [
            { text: `$r_z = -${d(V.l6ChRzSize, 2)}$.` },
            { text: `$\\theta = \\arccos(-${d(V.l6ChRzSize, 2)}) \\approx ${d(V.l6ChTheta, 2)}^\\circ$, a little below the equator.` },
            { text: `Check with Townsend’s form: $|\\alpha| = \\cos\\tfrac{\\theta}{2} = \\cos ${d(V.l6ChHalfTheta, 2)}^\\circ = ${d(V.l6ChAlphaBack, 1)}$.` },
          ],
        },
        {
          id: 'l6-b-phi',
          kind: 'numeric',
          tier: 'core',
          title: 'Which longitude?',
          prompt: 'Now $\\psi_z = (0.6,\\ 0.8i)$. What is the azimuth $\\varphi$ of its point, in degrees?',
          answer: V.l6ChPhi,
          tolerance: 0.5,
          unit: '°',
          hints: [
            { text: 'Compared with the warm-up, only the [[relative-phase|relative phase]] changed.' },
            { text: '$\\varphi$ is the phase of $\\alpha^*\\beta$.' },
            { text: `$\\alpha^*\\beta = ${d(V.l6ChCohIm, 2)}i$.` },
          ],
          walkthrough: [
            { text: `$\\alpha^*\\beta = ${d(V.l6ChCohIm, 2)}i$ has phase ${d(V.l6ChPhi, 0)}°.` },
            { text: `The point sits over the $+y$ side, at the same height as before: $\\theta \\approx ${d(V.l6ChThetaI, 2)}^\\circ$.` },
            { text: `Unit 5.1 found $\\langle S_y\\rangle = ${d(V.l6ChCohIm, 2)}\\,\\hbar$ for this state; on the sphere that is $r_y = ${d(V.l6ChRy, 2)}$.` },
          ],
        },
        {
          id: 'l6-b-average',
          kind: 'choice',
          tier: 'core',
          title: 'What does a coordinate of 0.96 mean?',
          prompt: `For $\\vec r = (0,\\ ${d(V.l6ChRy, 2)},\\ -${d(V.l6ChRzSize, 2)})$, which statement is true?`,
          options: [
            { text: `Along $y$, ${pct(V.l6ChPy)} of the atoms read +`, correct: true, why: `Right: $P(+) = \\tfrac{1 + r_y}{2} = ${d(V.l6ChPy, 2)}$.` },
            { text: `Each atom reads $S_y = ${d(V.l6ChRy, 2)}\\cdot\\tfrac{\\hbar}{2}$`, correct: false, why: 'A single reading is only ever $\\pm\\tfrac{\\hbar}{2}$; the coordinate is an average.' },
            { text: 'Each atom has an $S_y$ value and an $S_z$ value at the same time', correct: false, why: 'The coordinates come from separate batches of atoms, each measured along one axis.' },
            { text: `The state is mixed because $r_y < 1$`, correct: false, why: 'Its length is $|\\vec r| = 1$, so it is pure; it simply does not point along $y$.' },
          ],
          hints: [
            { text: 'What can one atom ever read?' },
            { text: 'The coordinates are averages.' },
            { text: 'Use $P(+) = \\tfrac{1 + \\hat n\\cdot\\vec r}{2}$ with $\\hat n$ along $y$.' },
          ],
          walkthrough: [
            { text: 'A single reading is $\\pm\\tfrac{\\hbar}{2}$.' },
            { text: `The average along $y$ is $${d(V.l6ChRy, 2)}\\cdot\\tfrac{\\hbar}{2}$, so $P(+y) = \\tfrac{1 + ${d(V.l6ChRy, 2)}}{2} = ${d(V.l6ChPy, 2)}$.` },
          ],
        },
        {
          id: 'l6-b-opposite',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The antipode',
          prompt: 'The pure state $|\\xi\\rangle$ has its Bloch point diametrically opposite that of $|\\psi_\\star\\rangle = \\cos 30^\\circ|{+z}\\rangle + e^{i\\pi/4}\\sin 30^\\circ|{-z}\\rangle$. What is $|\\langle\\xi|\\psi_\\star\\rangle|^2$?',
          answer: V.l6ChOpp,
          tolerance: 0.001,
          unit: 'probability',
          hints: [
            { text: 'What do opposite points on the sphere mean for the states?' },
            { text: 'Call the two Bloch vectors $\\vec r_\\xi$ and $\\vec r_\\star$. Use $P = \\tfrac{1 + \\vec r_\\xi\\cdot\\vec r_\\star}{2}$ with $\\vec r_\\xi = -\\vec r_\\star$.' },
            { text: '$\\vec r_\\star\\cdot\\vec r_\\star = 1$.' },
          ],
          walkthrough: [
            { text: `Opposite points are orthogonal states: $P = \\tfrac{1 - 1}{2} = ${d(V.l6ChOpp, 0)}$.` },
            { text: `The trap is ${d(V.l6ChOppTrap, 0)}: that belongs to $-|\\psi_\\star\\rangle$, which sits on the same point as $|\\psi_\\star\\rangle$.` },
            { text: `For $|\\xi\\rangle$ itself the height flips sign, so $P(+z) = \\tfrac{1 - ${d(V.l6RStarZ, 1)}}{2} = ${d(V.l6ChOppPz, 2)}$.` },
          ],
        },
      ],
    },
    {
      id: 'l6-equator',
      story: L6_STORY['l6-equator'],
      review: L6_REVIEW['l6-equator'],
      title: 'Relative phase sets the longitude',
      question: 'If $|{\\pm x}\\rangle$ and $|{\\pm y}\\rangle$ all give 50/50 along $z$, what tells them apart?',
      lecture: {
        pages: 'L6 pp. 7–8',
        summary:
          'The four equatorial states split 50/50 along $z$ and differ only in the relative phase of $|{-z}\\rangle$. Putting $\\alpha = \\tfrac{1}{\\sqrt2}$ and asking for the point $(\\cos\\varphi, \\sin\\varphi, 0)$ forces $\\beta = \\tfrac{1}{\\sqrt2}e^{i\\varphi}$: the relative phase is the longitude. The notes call this angle θ; here it is $\\varphi$, because θ is the polar angle.',
        equations: ['|\\psi(\\varphi)\\rangle = \\tfrac{1}{\\sqrt2}\\big(|{+z}\\rangle + e^{i\\varphi}|{-z}\\rangle\\big),\\qquad \\vec r = (\\cos\\varphi, \\sin\\varphi, 0)'],
      },
      books: [
        { source: 'townsend', where: '§1.5, pp. 18–20; §1.6, p. 25', adds: 'Derives $|{+y}\\rangle$ from 50/50 data; the sign of its phase is a choice of right-handed axes, and relative phases matter.' },
        { source: 'susskind', where: '§2.4 (Exercise 2.3)', adds: 'For $|{+y}\\rangle$ the product $\\alpha^*\\beta$ must be purely imaginary, so real coefficients cannot describe it.' },
      ],
      visual: {
        kind: 'phase-dial',
        props: { theta: 0, rotations: false },
        caption: 'The slider is the relative phase $\\varphi$ of $|{-z}\\rangle$ against $|{+z}\\rangle$ (the notes’ θ); the dot is the point seen from above.',
        tryThis: [
          `Drag the relative phase to $90^\\circ$. Where is the point, and what is $\\beta$? (It should be $i/\\sqrt2 \\approx ${d(V.l6BetaY)}\\,i$.)`,
          'Press “multiply both by $e^{i\\pi/2}$”. What happens to the two phasors, and what happens to the point?',
          'Set the relative phase to $180^\\circ$. Which named state is this, and what does a $z$ magnet do with it?',
        ],
      },
      clues: [],
      claims: [
        claim('l6ChDisguise', '(i|+z⟩ + |−z⟩)/√2 is |−y⟩ up to phase', () => V.l6ChDisguise === 1),
        claim('l6ChDisguiseWrong', '(−i|+z⟩ + |−z⟩)/√2 is |+y⟩ up to phase', () => V.l6ChDisguiseWrong === 1),
      ],
      insight: 'On the equator the $z$ odds are always even. The only thing left to set is the relative phase, and it is exactly the angle around the sphere.',
      pitfalls: [
        'Reading the phase of $\\beta$ alone as the longitude. It is the phase of $\\beta$ relative to $\\alpha$, the phase of $\\alpha^*\\beta$.',
        'Mixing the notes’ θ (longitude) with the app’s θ (polar angle).',
      ],
      play: [
        {
          id: 'l6-e-rx',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Read the longitude',
          prompt: '$|\\psi\\rangle = \\tfrac{1}{\\sqrt2}(|{+z}\\rangle + e^{2\\pi i/3}|{-z}\\rangle)$. What is $r_x$?',
          answer: V.l6EqAnyX,
          tolerance: 0.005,
          hints: [
            { text: 'The relative phase is the longitude.' },
            { text: '$2\\pi/3$ is $120^\\circ$.' },
            { text: 'On the equator, $r_x = \\cos\\varphi$.' },
          ],
          walkthrough: [
            { text: '$\\varphi = 120^\\circ$.' },
            { text: `$r_x = \\cos 120^\\circ = -${d(V.l6EqAnyXSize, 1)}$, and $r_y = ${d(V.l6EqAnyY)}$.` },
          ],
        },
        {
          id: 'l6-e-disguise',
          kind: 'choice',
          tier: 'core',
          title: 'Which one is |−y⟩ in disguise?',
          prompt: 'Which state is physically the same as $|{-y}\\rangle$?',
          options: [
            { text: '$\\tfrac{1}{\\sqrt2}(i|{+z}\\rangle + |{-z}\\rangle)$', correct: true, why: 'Right: it equals $i\\,|{-y}\\rangle$, and $\\beta/\\alpha = 1/i = -i$.' },
            { text: '$\\tfrac{1}{\\sqrt2}(-i|{+z}\\rangle + |{-z}\\rangle)$', correct: false, why: 'Here $\\beta/\\alpha = 1/(-i) = i$: it is $-i\\,|{+y}\\rangle$.' },
            { text: '$\\tfrac{1}{\\sqrt2}(|{+z}\\rangle + i|{-z}\\rangle)$', correct: false, why: 'That is $|{+y}\\rangle$ itself.' },
            { text: '$\\tfrac{1}{\\sqrt2}(|{+z}\\rangle - |{-z}\\rangle)$', correct: false, why: 'That is $|{-x}\\rangle$.' },
          ],
          hints: [
            { text: 'Only the relative phase $\\beta/\\alpha$ matters.' },
            { text: 'Divide $\\beta$ by $\\alpha$ for each option.' },
            { text: '$|{-y}\\rangle$ has $\\beta/\\alpha = -i$.' },
          ],
          walkthrough: [
            { text: 'Option 1: $1/i = -i$, the relative phase of $|{-y}\\rangle$.' },
            { text: 'Option 2: $1/(-i) = i$, which is $|{+y}\\rangle$.' },
            { text: 'The common factor $i$ in front of option 1 changes nothing physical.' },
          ],
        },
        {
          id: 'l6-e-px',
          kind: 'numeric',
          tier: 'core',
          title: 'Equator odds',
          prompt: 'For $\\tfrac{1}{\\sqrt2}(|{+z}\\rangle + e^{i\\pi/3}|{-z}\\rangle)$, what is $P(+x)$?',
          answer: V.l6ChPx,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Use the Bloch vector.' },
            { text: '$\\vec r = (\\cos 60^\\circ, \\sin 60^\\circ, 0)$.' },
            { text: '$P(+x) = \\tfrac{1 + r_x}{2}$.' },
          ],
          walkthrough: [
            { text: `$r_x = ${d(V.l6ChPxRx, 1)}$, so $P(+x) = ${d(V.l6ChPx, 2)}$.` },
            { text: 'The same number comes from $|\\langle{+x}|\\psi\\rangle|^2$.' },
          ],
        },
        {
          id: 'l6-e-phase',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Not on the equator',
          prompt: '$\\psi_z \\propto (1 + i,\\ 2)$. What is its azimuth $\\varphi$ in degrees, between −180 and 180?',
          answer: V.l6ChPhase,
          tolerance: 0.5,
          unit: '°',
          hints: [
            { text: 'The azimuth is the phase of $\\alpha^*\\beta$, not of $\\alpha$ or $\\beta$ alone.' },
            { text: '$\\alpha^* = 1 - i$.' },
            { text: '$\\alpha^*\\beta = 2 - 2i$ (before normalizing, which does not change the phase).' },
          ],
          walkthrough: [
            { text: `$\\alpha^*\\beta = 2 - 2i$, whose phase is $${d(V.l6ChPhase, 0)}^\\circ$.` },
            { text: `The point is off the equator, $\\vec r = (${d(V.l6ChPhaseRx)}, ${d(V.l6ChPhaseRy)}, -${d(V.l6ChPhaseRzSize)})$, but the longitude rule still holds.` },
            { text: 'The trap is $+45^\\circ$, the phase of $\\alpha$ alone.' },
          ],
        },
      ],
    },
    {
      id: 'l6-active',
      story: L6_STORY['l6-active'],
      review: L6_REVIEW['l6-active'],
      title: 'Turn the state, keep the axes',
      question: 'What matrix turns a spin state about $z$, and how is that different from changing basis?',
      lecture: {
        pages: 'L6 pp. 2–6 (Lecture 5 material), 9–10, 12–13',
        summary:
          'A change of basis is passive: the state stays and only its coordinates change (Units 5.3 to 5.5). An active rotation keeps the basis and moves the state. $R_z(\\varphi) = \\mathrm{diag}(e^{-i\\varphi/2}, e^{i\\varphi/2})$ raises the relative phase by $\\varphi$, so the point turns counterclockwise about $z$. It is unitary, undone by its dagger, and turns about one axis add.',
        equations: ['R_z(\\varphi) = \\begin{pmatrix}e^{-i\\varphi/2}&0\\\\0&e^{i\\varphi/2}\\end{pmatrix},\\qquad R_z(\\varphi)\\,\\psi_z(\\varphi_0) = e^{-i\\varphi/2}\\,\\psi_z(\\varphi_0 + \\varphi)'],
      },
      books: [
        { source: 'townsend', where: '§2.2, pp. 33–41', adds: 'The rotation operator about $z$, its unitarity, and worked turns of $|{+x}\\rangle$ by 90° and 180°.' },
        { source: 'townsend', where: '§2.5, pp. 52–57', adds: 'Active versus passive transformations, and why his basis-change matrix is not a pure rotation with the standard phases.' },
      ],
      visual: {
        kind: 'bloch',
        props: { theta: 60, phi: 0, editable: true, rotations: true, rotationAngles: [45, 90, -90, 180], measure: 'y' },
        caption: 'The $R_z$ buttons turn the state itself; the $y$ magnet and the axes stay where they are.',
        tryThis: [
          `Press $R_z(90^\\circ)$ once and watch the $y$-magnet bars. $P(+)$ along $y$ should go from ${pct(V.l6PyBefore)} to about ${pct(V.l6PyAfter)}.`,
          'Press $R_z(90^\\circ)$ and then $R_z(-90^\\circ)$. Where are you, and why?',
          'Set $\\theta = 0$, the state $|{+z}\\rangle$, and press $R_z(45^\\circ)$ a few times. Why does the point stay while the phasors turn?',
        ],
      },
      clues: [],
      claims: [claim('l6ChMinusYOk', 'Rz(270°)|+x⟩ is |−y⟩, and Rz(90°)|+x⟩ is |+y⟩', () => V.l6ChMinusYOk === 1)],
      insight: 'A basis change renames; a rotation moves. $R_z(\\varphi)$ moves the point by $\\varphi$ about $z$ by adding $\\varphi$ to the relative phase, and it carries every prediction along.',
      pitfalls: [
        'Calling a change of basis a rotation of the atom. The matrix may look like a turn, but we use it passively.',
        'Expecting $|{\\pm z}\\rangle$ to move under $R_z$. They lie on the axis and only pick up a phase.',
      ],
      play: [
        {
          id: 'l6-ac-which',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which one changes the state?',
          prompt: 'Start from $|{+x}\\rangle$, written as the column $\\psi_z$. Which operation changes the physical state?',
          options: [
            { text: '$R_z(90^\\circ)\\,\\psi_z$, with the $z$ basis kept', correct: true, why: 'Right: it moves $|{+x}\\rangle$ to $|{+y}\\rangle$, a different point on the sphere.' },
            { text: '$\\psi_x = B_{x\\leftarrow z}\\,\\psi_z$', correct: false, why: 'New coordinates, same state (Unit 5.3).' },
            { text: '$S_z^{(x)} = B_{x\\leftarrow z}S_zB_{z\\leftarrow x}$', correct: false, why: 'A new table of numbers for the same observable (Unit 5.4).' },
            { text: 'Multiplying the whole column $\\psi_z$ by $e^{i\\pi/3}$', correct: false, why: 'An overall phase: the point does not move.' },
          ],
          hints: [
            { text: 'Ask whether the point on the sphere moves.' },
            { text: 'A basis change only relabels.' },
            { text: 'Only one option keeps the basis and changes the relative phase.' },
          ],
          walkthrough: [
            { text: 'The two basis changes move no point, and neither does an overall phase.' },
            { text: '$R_z(90^\\circ)$ turns the point by $90^\\circ$ about $z$.' },
          ],
        },
        {
          id: 'l6-ac-px',
          kind: 'numeric',
          tier: 'core',
          title: 'Turn, then measure',
          prompt: 'Apply $R_z(60^\\circ)$ to $\\psi_z = (\\cos 30^\\circ,\\ \\sin 30^\\circ)$. What is $P(+x)$ afterwards?',
          answer: V.l6ChActPx,
          tolerance: 0.002,
          unit: 'probability',
          hints: [
            { text: 'Turn the Bloch vector instead of the amplitudes one by one.' },
            { text: `$\\vec r = (${d(V.l6Psi60Rx)}, 0, ${d(V.l6Psi60Rz, 1)})$ turns by $60^\\circ$ about $z$.` },
            { text: '$P(+x) = \\tfrac{1 + r_x}{2}$.' },
          ],
          walkthrough: [
            { text: `$\\vec r\\,' = (${d(V.l6Psi60Rx)}\\cos 60^\\circ,\\ ${d(V.l6Psi60Rx)}\\sin 60^\\circ,\\ ${d(V.l6Psi60Rz, 1)}) = (${d(V.l6ChActRx)}, ${d(V.l6ChActRy, 3)}, ${d(V.l6Psi60Rz, 1)})$.` },
            { text: `$P(+x) = \\tfrac{1 + ${d(V.l6ChActRx)}}{2} \\approx ${d(V.l6ChActPx, 4)}$.` },
            { text: `Before the turn it was ${d(V.l6ChActBefore)}.` },
          ],
        },
        {
          id: 'l6-ac-to-minus-y',
          kind: 'numeric',
          tier: 'core',
          title: 'The long way round',
          prompt: 'What is the smallest positive angle $\\varphi$, in degrees, for which $R_z(\\varphi)|{+x}\\rangle$ is physically $|{-y}\\rangle$?',
          answer: V.l6ChMinusY,
          tolerance: 0.5,
          unit: '°',
          hints: [
            { text: '$R_z$ turns counterclockwise, seen from $+z$.' },
            { text: 'Going from $+x$ to $+y$ is $+90^\\circ$.' },
            { text: '$-y$ lies three quarter turns counterclockwise from $+x$.' },
          ],
          walkthrough: [
            { text: '$+x \\to +y \\to -x \\to -y$.' },
            { text: `That is ${d(V.l6ChMinusY, 0)}°. $R_z(-90^\\circ)$ reaches the same state, but its angle is not positive; the trap is 90°, which gives $|{+y}\\rangle$.` },
          ],
        },
        {
          id: 'l6-ac-rotate-avg',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Rotate the averages',
          prompt: `Before a turn $R_z(90^\\circ)$, $\\langle S_x\\rangle = ${d(V.l6ChRotBeforeX, 1)}\\,\\hbar$ and $\\langle S_y\\rangle = ${d(V.l6ChRotBeforeY, 1)}\\,\\hbar$. What is $\\langle S_x\\rangle$ afterwards?`,
          answer: V.l6ChRotAvgX,
          tolerance: 0.005,
          unit: 'ħ',
          hints: [
            { text: 'The notes’ reference page: the averages turn like an ordinary arrow.' },
            { text: '$\\langle S_x\\rangle\' = \\cos\\varphi\\,\\langle S_x\\rangle - \\sin\\varphi\\,\\langle S_y\\rangle$.' },
            { text: 'Here $\\varphi = 90^\\circ$.' },
          ],
          walkthrough: [
            { text: `$\\cos 90^\\circ = 0$ and $\\sin 90^\\circ = 1$, so $\\langle S_x\\rangle' = -${d(V.l6ChRotAvgXSize, 1)}\\,\\hbar$.` },
            { text: `And $\\langle S_y\\rangle' = +${d(V.l6ChRotAvgY, 1)}\\,\\hbar$: the arrow turned a quarter turn counterclockwise.` },
          ],
        },
      ],
    },
    {
      id: 'l6-generator',
      story: L6_STORY['l6-generator'],
      review: L6_REVIEW['l6-generator'],
      title: 'Sz generates the turn',
      question: 'Why is $R_z(\\varphi) = e^{-i\\varphi S_z/\\hbar}$, and what job does $S_z$ do in it?',
      lecture: {
        pages: 'L6 pp. 11–12',
        summary:
          'The exponential of a matrix is defined by its power series; for a diagonal matrix it exponentiates each entry. So $e^{-i\\varphi S_z/\\hbar}$ is exactly $R_z(\\varphi)$. For a small angle only the first two terms matter: $S_z$, the generator, says which way and how fast the state starts to turn.',
        equations: ['R_z(\\varphi) = e^{-i\\varphi S_z/\\hbar},\\qquad R_z(d\\varphi) = I - \\tfrac{i}{\\hbar}S_z\\,d\\varphi + O(d\\varphi^2)'],
      },
      books: [
        { source: 'townsend', where: '§2.2, pp. 36–39', adds: 'Builds a finite turn from many small ones, and explains why the $i$ lets the generator be Hermitian.' },
        { source: 'susskind', where: '§4.5, §4.11', adds: 'Beyond the lecture: time evolution by small steps whose generator is the Hamiltonian; in a field along $z$ it is again a turn about $z$.' },
      ],
      visual: {
        kind: 'complex-plane',
        props: { mode: 'multiply', z: [0.7, 0], w: [1, -0.05] },
        caption: `The number $w = 1 - ${d(V.l6WImSize, 2)}i$ is the factor that the two-term small turn puts on $\\alpha$ at a tenth of a radian.`,
        tryThis: [
          'Read the size of $w$. Is it exactly 1? (It is just above 1: the two-term formula stretches a little, at second order.)',
          `What angle does $w$ turn $z$ by? The widget rounds it to −${d(-V.l6WAngle, 0)}°; exactly it is −${d(-V.l6WAngle, 3)}°, against $-\\tfrac{d\\varphi}{2} = -${d(-V.l6WHalfStep, 3)}^\\circ$ for a tenth of a radian. The two-term factor turns almost exactly like the true one.`,
          'Switch to “powers of $i$”. Multiplying by $i = e^{i\\pi/2}$ is a quarter turn. Which $R_z$ angle multiplies $\\beta$ by exactly $i$? ($R_z(\\varphi)$ multiplies $\\beta$ by $e^{i\\varphi/2}$.)',
        ],
      },
      clues: [],
      claims: [claim('l6ChVelFd', 'the finite-difference velocity of |+y⟩ under Rz is (−1, 0, 0)', () => V.l6ChVelFd === 1)],
      insight: 'The whole turn is packed into one Hermitian matrix: $S_z$ fixes the axis and the direction, and the exponential adds up infinitely many small steps.',
      pitfalls: [
        'Dropping the $-i$. With a Hermitian $S_z$ the step then stretches lengths at first order; a step that keeps lengths would need a non-Hermitian generator.',
        'Exponentiating a matrix entry by entry when it is not diagonal. That shortcut works only for diagonal matrices.',
      ],
      play: [
        {
          id: 'l6-g-exp-diag',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Exponential of a diagonal',
          prompt: 'Let $M = \\mathrm{diag}(0, i\\pi)$. What is the bottom-right entry of $e^M$ (a real number)?',
          answer: V.l6ChExpDiag,
          tolerance: 0.001,
          hints: [
            { text: 'Diagonal in, diagonal out.' },
            { text: 'Exponentiate each diagonal entry.' },
            { text: 'Euler: $e^{i\\pi}$.' },
          ],
          walkthrough: [
            { text: '$e^M = \\mathrm{diag}(e^0, e^{i\\pi})$.' },
            { text: `$e^{i\\pi} = -${d(-V.l6ChExpDiag, 0)}$.` },
          ],
        },
        {
          id: 'l6-g-small-form',
          kind: 'choice',
          tier: 'core',
          title: 'The small turn',
          prompt: 'Which is the first-order form of $R_z(d\\varphi)$?',
          options: [
            { text: '$I - \\tfrac{i}{\\hbar}S_z\\,d\\varphi$', correct: true, why: 'Right: the first two terms of $e^{-i\\,d\\varphi\\,S_z/\\hbar}$.' },
            { text: '$I + \\tfrac{i}{\\hbar}S_z\\,d\\varphi$', correct: false, why: 'That is $R_z(-d\\varphi)$, the turn the other way.' },
            { text: '$I - \\tfrac{1}{\\hbar}S_z\\,d\\varphi$', correct: false, why: `It changes lengths at first order: at a tenth of a radian it stretches $|{-z}\\rangle$ to length ${d(V.l6NoI, 2)}.` },
            { text: '$I - \\tfrac{i}{\\hbar}S_x\\,d\\varphi$', correct: false, why: 'That is a small turn about $x$.' },
          ],
          hints: [
            { text: 'Expand $e^{-i\\varphi S_z/\\hbar}$.' },
            { text: 'Keep the terms up to the first power of $d\\varphi$.' },
            { text: 'Watch the sign in front of the $i$.' },
          ],
          walkthrough: [
            { text: '$e^M \\approx I + M$ with $M = -\\tfrac{i}{\\hbar}S_z\\,d\\varphi$.' },
            { text: `With the $i$, the length is off only at second order: ${d(V.l6WithI, 5)} at a tenth of a radian.` },
          ],
        },
        {
          id: 'l6-g-leftover',
          kind: 'numeric',
          tier: 'stretch',
          title: 'How good is two terms?',
          prompt: 'At $d\\varphi = 0.2$ rad, what is the largest entry of $|R_z(d\\varphi) - (I - \\tfrac{i}{\\hbar}S_z\\,d\\varphi)|$? Give three significant figures.',
          answer: V.l6ChLeftover,
          tolerance: 5e-5,
          hints: [
            { text: 'Compare the top-left entries.' },
            { text: '$e^{-i\\,0.1}$ against $1 - 0.1i$.' },
            { text: 'The difference is about $\\tfrac12(0.1)^2$.' },
          ],
          walkthrough: [
            { text: `Exact: $${d(V.l6ChLeftExactRe, 5)} - ${d(V.l6ChLeftExactImSize, 5)}i$. Two terms: $1 - 0.1i$.` },
            { text: `The gap is about ${d(V.l6ChLeftover, 5)}, that is $d\\varphi^2/8$.` },
          ],
        },
        {
          id: 'l6-g-velocity',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Which way does |+y⟩ start to move?',
          prompt: 'Under $R_z(\\varphi)$, the Bloch point of $|{+y}\\rangle$ starts to move with velocity $\\tfrac{d\\vec r}{d\\varphi}$. What is its $x$ component?',
          answer: V.l6ChVelX,
          tolerance: 0.01,
          hints: [
            { text: 'It is a counterclockwise turn about $z$.' },
            { text: 'The velocity is $\\hat z\\times\\vec r$.' },
            { text: 'Work out $\\hat z\\times\\hat y$.' },
          ],
          walkthrough: [
            { text: `$\\hat z\\times\\hat y = -\\hat x$, so the $x$ component is $-${d(-V.l6ChVelX, 0)}$.` },
            { text: 'So $+y$ heads toward $-x$, as it should: $+x \\to +y \\to -x$.' },
          ],
        },
      ],
    },
    {
      id: 'l6-mixture',
      story: L6_STORY['l6-mixture'],
      review: L6_REVIEW['l6-mixture'],
      title: 'Superposition or mixture?',
      question: 'Can a beam of mixed atoms ever act like one pure state?',
      beyondLecture: {
        why: 'The notes treat pure states only (L6 p. 7). Decision L1 #6 places the full superposition-or-mixture story here, after the teaser in Lecture 1.',
        source: { source: 'townsend', where: '§5.7, pp. 171–178', adds: 'The density operator for pure and mixed beams, worked examples of mixtures, and the caution that different recipes can give the same beam.' },
      },
      lecture: {
        pages: 'none (beyond the lecture; the notes say “pure states here”, p. 7)',
        summary:
          'A beam whose atoms were prepared in different states is a mixture, a point inside the Bloch ball. It sits at $\\vec r_{\\text{mix}} = \\sum_k w_k\\vec r_k$, where $w_k$ is the fraction of atoms with Bloch vector $\\vec r_k$. The same rule gives the odds inside the ball. Different recipes can give the same point, and a rotation turns the whole ball rigidly.',
        equations: ['\\vec r_{\\text{mix}} = \\sum_k w_k\\,\\vec r_k,\\qquad P(+\\hat n) = \\tfrac{1 + \\hat n\\cdot\\vec r}{2}'],
      },
      books: [
        { source: 'townsend', where: '§5.7, pp. 171–178', adds: 'The density operator, Example 5.5 with two mixtures, and the purity $\\mathrm{tr}\\,\\rho^2$.' },
        { source: 'susskind', where: '§7.3', adds: 'Density matrices, reached from entanglement: another road to the same mixtures.' },
      ],
      visual: {
        kind: 'sg-lab',
        props: { source: 'oven', axes: ['x'], editable: true, predict: true, showTheory: true },
        caption: 'The oven beam is a mixture: whatever axis you pick, it splits evenly until a filter makes it pure.',
        tryThis: [
          'Point the magnet along any axis you like. Can the oven ever give anything but 50/50?',
          `Add a first magnet along $x$ that keeps +, then point the second along $x$ too. Of the oven’s atoms, ${pct(V.l6FilterX)} now land on + and ${pct(V.l6FilterXMinus)} on −: the filter made a pure beam.`,
          `Keep the $x$ filter and tilt the last magnet to $60^\\circ$. Compare with the ball rule: ${d(V.l6BallP60Pure)} of the atoms that pass, so ${d(V.l6FilterTilt, 4)} of the oven’s.`,
        ],
      },
      clues: [],
      insight: 'Adding amplitudes makes a new pure state on the surface; mixing beams only averages, and lands inside the ball, where no axis gives certainty.',
      pitfalls: [
        'Calling $|{+x}\\rangle$ “half up, half down”. Along $x$ it is certain; only a beam at the centre of the ball, like the oven’s, gives 50/50 along every axis.',
        'Thinking a mixture’s recipe can be read back from measurements. Only its point in the ball is physical.',
      ],
      play: [
        {
          id: 'l6-m-one-magnet',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'One magnet, two beams',
          prompt: 'Along $x$, how much larger is $P(+)$ for a pure $|{+x}\\rangle$ beam than for the oven beam?',
          answer: V.l6ChOneMagnet,
          tolerance: 0.001,
          unit: 'probability',
          hints: [
            { text: 'The pure beam points along $x$.' },
            { text: 'The oven sits at the centre of the ball.' },
            { text: 'Subtract the two chances.' },
          ],
          walkthrough: [
            { text: `$|{+x}\\rangle$ gives ${d(V.l6PlusXAlongX, 0)}; the oven gives ${d(V.l6OvenAlongX, 1)}.` },
            { text: `The difference is ${d(V.l6ChOneMagnet, 1)}.` },
          ],
        },
        {
          id: 'l6-m-certain',
          kind: 'numeric',
          tier: 'core',
          title: 'Can a mixture ever be certain?',
          prompt: 'A beam is half $|{+z}\\rangle$ atoms and half $|{+x}\\rangle$ atoms. What is the largest $P(+)$ that any magnet can give?',
          answer: V.l6ChCertain,
          tolerance: 0.002,
          unit: 'probability',
          hints: [
            { text: 'Place the beam in the Bloch ball.' },
            { text: `$\\vec r = (${d(V.l6MixZXx, 1)}, 0, ${d(V.l6MixZXz, 1)})$.` },
            { text: 'The best axis points along $\\vec r$, giving $P = \\tfrac{1 + |\\vec r|}{2}$.' },
          ],
          walkthrough: [
            { text: `$|\\vec r| = ${d(V.l6MixZXLen)}$, and the best magnet is tilted $45^\\circ$ from $z$ toward $x$.` },
            { text: `$P = \\tfrac{1 + ${d(V.l6MixZXLen)}}{2} \\approx ${d(V.l6ChCertain, 4)}$. The trap is 1, which belongs to the superposition.` },
          ],
        },
        {
          id: 'l6-m-lookalike',
          kind: 'choice',
          tier: 'core',
          title: 'A perfect lookalike',
          prompt: 'A beam is half $|{+x}\\rangle$ and half $|{-x}\\rangle$. Which experiment can tell it apart from the oven beam?',
          options: [
            { text: 'None', correct: true, why: 'Right: both sit at $\\vec r = 0$, so every axis gives ½.' },
            { text: 'A $z$ magnet', correct: false, why: 'Both give 50/50.' },
            { text: 'An $x$ magnet', correct: false, why: 'Both give 50/50: the half $|{+x}\\rangle$ reads + and the half $|{-x}\\rangle$ reads −.' },
            { text: 'A magnet at $45^\\circ$', correct: false, why: 'Both give 50/50.' },
          ],
          hints: [
            { text: 'Place both beams in the ball.' },
            { text: 'What does $P(+)$ depend on?' },
            { text: 'Only on $\\vec r$.' },
          ],
          walkthrough: [
            { text: 'Both have $\\vec r = 0$.' },
            { text: 'So $P(+) = \\tfrac12$ along every axis: different recipes, the same physics.' },
          ],
        },
        {
          id: 'l6-m-best-tilt',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Townsend’s chamber',
          prompt: 'Townsend’s beam is half $|{+z}\\rangle$ and half $|{-x}\\rangle$. At what tilt, in degrees from $+z$ toward $+x$ (negative means toward $-x$), is $P(+)$ largest?',
          answer: V.l6ChBestTilt,
          tolerance: 1,
          unit: '°',
          hints: [
            { text: 'Find $\\vec r$.' },
            { text: 'Point the magnet along $\\vec r$.' },
            { text: '$\\vec r$ lies halfway between $+z$ and $-x$.' },
          ],
          walkthrough: [
            { text: `$\\vec r = (-${d(V.l6T55XSize, 1)}, 0, ${d(V.l6T55Z, 1)})$.` },
            { text: `Its direction is $45^\\circ$ from $+z$ toward $-x$, so the tilt is ${d(V.l6ChBestTilt, 0)}°, where $P = ${d(V.l6ChBestTiltP, 4)}$.` },
          ],
        },
      ],
    },
  ],
}

