import type { Lecture } from './schema'
import { V, claim, close, d, tf } from './L7.values'
import { L7_STORY } from './L7.story'
import { L7_REVIEW } from './L7.review'

// Every number a learner sees in this lecture is computed in L7.values.ts, then asserted in keyed claims
// (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy). Plan: docs/roles/proposals/P-L7-story.md,
// with the judge's rulings: built from notes pp. 1–13 (page 14 is missing); References A and B stay in the story and the
// text says they are outside the class plan; Lecture 6 owns the Bloch sphere, R_z and its generator, and Lecture 3 the
// update rule and the spread, so their beats here are link-backs that define nothing. Townsend's Example 1.2 slip is in
// Lecture 3's errata; L7 mentions it once (`l7-spreads:b6`) and has no errata box. The course's last lecture.

export const L7: Lecture = {
  id: 'L7',
  number: 7,
  title: 'Rotations, compatible measurements and uncertainty',
  outcomes: [
    'Explain why opposite points on the Bloch sphere are orthogonal states, and compute the angle between two state rays.',
    'Say why a full turn returns minus the state, and why only two full turns return the state itself.',
    'Predict how swapping two measurements changes the results, and say when it cannot.',
    'Test two observables for compatibility with a commutator, and compute the commutator of the x and y spin matrices.',
    'Read all three spin spreads off the Bloch vector.',
    'Derive and check the spin uncertainty relation, and say what it does not mean.',
  ],
  prerequisites: ['bloch-sphere', 'rz', 'born-rule', 'projectors', 'expectation', 'spin-matrices', 'order'],
  // Symbols defined in the text itself (symbol → the unit, beat or site whose sentence defines it). Kets, bras, ħ, i, e,
  // the spin matrices, the amplitudes α, β, the identity I and Lecture 6's Bloch notation are mapped to the first unit: a
  // recap of earlier lectures.
  symbols: {
    '|\\cdot\\rangle': 'l7-two-angles',
    '\\langle\\cdot|': 'l7-two-angles',
    '\\langle\\cdot|\\cdot\\rangle': 'l7-two-angles',
    '\\langle\\cdot\\rangle': 'l7-two-angles',
    '|\\psi\\rangle': 'l7-two-angles',
    '|+z\\rangle': 'l7-two-angles',
    '|-z\\rangle': 'l7-two-angles',
    '|+x\\rangle': 'l7-two-angles',
    '|-x\\rangle': 'l7-two-angles',
    '|+y\\rangle': 'l7-two-angles',
    '\\hbar': 'l7-two-angles',
    i: 'l7-two-angles',
    e: 'l7-two-angles',
    S_x: 'l7-two-angles',
    S_y: 'l7-two-angles',
    S_z: 'l7-two-angles',
    '\\alpha': 'l7-two-angles',
    '\\beta': 'l7-two-angles',
    I: 'l7-two-angles',
    '\\pi': 'l7-two-angles',
    '\\varphi': 'l7-two-angles',
    p: 'l7-two-angles',
    '\\hat n': 'l7-two-angles',
    '|\\psi(\\varphi)\\rangle': 'l7-two-angles:b1',
    '|\\psi_1\\rangle': 'l7-two-angles:b2',
    '|\\psi(\\varphi_1)\\rangle': 'l7-two-angles:b2',
    '|\\psi(\\varphi_2)\\rangle': 'l7-two-angles:b2',
    '|\\psi(0)\\rangle': 'l7-two-angles:b2',
    '|\\psi(120^\\circ)\\rangle': 'l7-two-angles:b2',
    '|\\psi(30^\\circ)\\rangle': 'l7-two-angles.play.l7-ta-orthogonal.options[1]',
    '|\\psi(210^\\circ)\\rangle': 'l7-two-angles.play.l7-ta-orthogonal.options[1]',
    '|\\psi_2\\rangle': 'l7-two-angles:b2',
    '\\varphi_1': 'l7-two-angles:b2',
    '\\varphi_2': 'l7-two-angles:b2',
    '\\arccos': 'l7-two-angles:b3',
    '|+\\hatn\\rangle': 'l7-two-angles:b4',
    '\\varphi_0': 'l7-full-turn:b1',
    '|\\psi(\\varphi_0)\\rangle': 'l7-full-turn:b1',
    '|\\psi(\\varphi_0+\\varphi)\\rangle': 'l7-full-turn:b1',
    '|\\psi(\\varphi_0+360^\\circ)\\rangle': 'l7-full-turn:b7',
    '|\\psi(360^\\circ)\\rangle': 'l7-full-turn:b7',
    A: 'l7-order:b1',
    a: 'l7-order:b1',
    P_a: 'l7-order:b1',
    'P_+x': 'l7-order:b1',
    'P_+z': 'l7-compatible:b3',
    '|k\\rangle': 'l7-compatible:b1',
    a_k: 'l7-compatible:b1',
    b_k: 'l7-compatible:b1',
    B: 'l7-compatible:b1',
    a_0: 'l7-compatible:b2',
    Q_b: 'l7-compatible:b3',
    b: 'l7-compatible:b3',
    '\\vec a': 'l7-compatible:b4',
    '\\vec b': 'l7-compatible:b4',
    '\\hat m': 'l7-compatible:b8',
    'S_\\hatn': 'l7-compatible:b8',
    'S_\\hatm': 'l7-compatible:b8',
    '\\vec S': 'l7-compatible:b8',
    c: 'l7-compatible.play.l7-co-tilt',
    '\\hat a': 'l7-compatible.play.l7-co-tilt.hints[0]',
    '\\hat b': 'l7-compatible.play.l7-co-tilt.hints[0]',
    'S_\\hata': 'l7-compatible.play.l7-co-tilt.hints[0]',
    'S_\\hatb': 'l7-compatible.play.l7-co-tilt.hints[0]',
    '\\hat z': 'l7-compatible.play.l7-co-tilt.hints[2]',
    S_j: 'l7-spreads:b2',
    j: 'l7-spreads:b2',
    r_j: 'l7-spreads:b2',
    N: 'l7-spreads:b4',
    'p_\\pm': 'l7-spreads:b5',
    'p_+': 'l7-spreads:b5',
    'p_-': 'l7-spreads:b5',
    '\\hat r': 'l7-spreads:b7',
    'S_\\hatr': 'l7-spreads:b7',
  },
  units: [
    {
      id: 'l7-two-angles',
      story: L7_STORY['l7-two-angles'],
      review: L7_REVIEW['l7-two-angles'],
      title: 'Sphere angles are twice state angles',
      question: 'How does the angle between two Bloch arrows relate to the angle between the two states?',
      lecture: {
        pages: 'L7 pp. 1–2',
        summary:
          'On the [[bloch-sphere|Bloch sphere]] the relative phase of an equatorial state is its azimuth $\\varphi$. Two states whose arrows are $\\Delta\\varphi$ apart overlap with probability $\\cos^2\\tfrac{\\Delta\\varphi}{2}$. The ray angle $\\eta = \\arccos|\\langle\\psi_1|\\psi_2\\rangle|$ is half the Bloch angle, so opposite arrows are orthogonal states. The notes call the azimuth θ; here θ is the polar angle.',
        equations: ['\\eta = \\arccos|\\langle\\psi_1|\\psi_2\\rangle| = \\tfrac{\\Delta\\varphi}{2},\\qquad |\\langle\\psi_1|\\psi_2\\rangle|^2 = \\cos^2\\tfrac{\\Delta\\varphi}{2}'],
      },
      books: [
        { source: 'townsend', where: 'Problem 1.3, p. 26', adds: 'The state along any direction in the polar and azimuthal angles, the same letters as our sphere.' },
        { source: 'townsend', where: '§2.2, p. 40, eq. (2.42)', adds: 'A quarter turn about $z$ takes $|{+x}\\rangle$ to $|{+y}\\rangle$: arrows 90° apart, overlap one half.' },
      ],
      visual: {
        kind: 'bloch',
        props: { theta: 90, phi: 120, measure: 'x', landmarks: true, editable: true },
        caption: 'The magnet along $x$ asks “is it $|\\psi(0)\\rangle = |{+x}\\rangle$?”, so its bar is the overlap probability with that state.',
        tryThis: [
          'Keep $\\theta$ at $90^\\circ$ and drag $\\varphi$. The bar is $\\cos^2(\\varphi/2)$. Where does it reach one half, and where zero? (At $90^\\circ$ and at $180^\\circ$.)',
          `Set $\\varphi = -10^\\circ$. The bar reads ${d(V.l7TryP10)}, which is $\\cos^2 5^\\circ$: always go the short way round.`,
          `Leave the equator: $\\theta = 60^\\circ$, $\\varphi = 0$. The arrows are now $30^\\circ$ apart, so $\\eta = 15^\\circ$ and the bar reads about ${d(V.l7TryPx60)}.`,
        ],
      },
      clues: [],
      insight: 'A state vector sees half the angle the sphere shows. That is why opposite points, 180° apart, are orthogonal states, only 90° apart as vectors.',
      pitfalls: [
        'Taking the difference of two azimuths without folding it into 0° to 180°. The separation of 10° and 350° is 20°, not 340°.',
        'Reading the notes’ θ as the polar angle. On the equator the notes’ θ is our azimuth $\\varphi$.',
      ],
      play: [
        {
          id: 'l7-ta-overlap',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Arrows 120° apart',
          prompt: 'Two equatorial states have Bloch arrows 120° apart. What is the probability of finding one of them in the other?',
          answer: V.l7Ov120P,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Angles between state vectors are half of sphere angles.' },
            { text: 'The probability is $\\cos^2\\tfrac{\\Delta\\varphi}{2}$.' },
            { text: 'Here $\\Delta\\varphi/2 = 60^\\circ$, and $\\cos 60^\\circ$ is one half.' },
          ],
          walkthrough: [
            { text: 'The separation is $\\Delta\\varphi = 120^\\circ$, so $\\eta = 60^\\circ$.' },
            { text: `$|\\langle\\psi_1|\\psi_2\\rangle| = \\cos 60^\\circ = ${d(V.l7Ov120Abs, 1)}$.` },
            { text: `Square it: ${d(V.l7Ov120P, 2)}.` },
          ],
        },
        {
          id: 'l7-ta-short-way',
          kind: 'numeric',
          tier: 'core',
          title: 'The short way round',
          prompt: 'Equatorial states sit at $\\varphi_1 = 10^\\circ$ and $\\varphi_2 = 350^\\circ$. What is the ray angle $\\eta$, in degrees?',
          answer: V.l7EtaShort,
          tolerance: 0.1,
          unit: '°',
          hints: [
            { text: 'The Bloch separation always lies between 0° and 180°.' },
            { text: '350° is the same direction as −10°.' },
            { text: 'The separation is 20°; halve it.' },
          ],
          walkthrough: [
            { text: `The short way round is ${d(V.l7SepShort, 0)}°, so $\\eta = ${d(V.l7EtaShort, 0)}^\\circ$.` },
            { text: `Check: $|\\langle\\psi_1|\\psi_2\\rangle| = \\cos 10^\\circ \\approx ${d(V.l7OvShort)}$.` },
            { text: 'The trap, 170°, would need $\\cos 170^\\circ < 0$, impossible for a size.' },
          ],
        },
        {
          id: 'l7-ta-orthogonal',
          kind: 'choice',
          tier: 'core',
          title: 'Which pair is orthogonal?',
          prompt: 'Which pair of states is orthogonal?',
          options: [
            { text: '$|{+x}\\rangle$ and $|{+y}\\rangle$', correct: false, why: `Their arrows are 90° apart, so they overlap with probability ${d(V.l7PXY, 1)}.` },
            { text: '$|\\psi(30^\\circ)\\rangle$ and $|\\psi(210^\\circ)\\rangle$', correct: true, why: `Right: the arrows are opposite, so $\\eta = 90^\\circ$ and the overlap probability is ${d(V.l7Orth30, 0)}.` },
            { text: '$|{+z}\\rangle$ and $|{+x}\\rangle$', correct: false, why: `Their arrows are 90° apart: overlap probability ${d(V.l7PZX, 1)}.` },
            { text: '$|{+x}\\rangle$ and $-|{+x}\\rangle$', correct: false, why: 'They are the same state: an [[global-phase|overall sign]] changes nothing.' },
          ],
          hints: [
            { text: 'Orthogonal means probability zero.' },
            { text: 'That needs $\\eta = 90^\\circ$.' },
            { text: 'So the Bloch arrows must be 180° apart.' },
          ],
          walkthrough: [
            { text: 'Look for the pair whose arrows are opposite.' },
            { text: '30° and 210° differ by 180°, so $\\eta = 90^\\circ$ and the overlap is zero.' },
          ],
        },
        {
          id: 'l7-ta-offaxis',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Off the equator',
          prompt: 'A state has $\\theta = 60^\\circ$, $\\varphi = 90^\\circ$. What is its ray angle $\\eta$ to $|{+y}\\rangle$, in degrees?',
          answer: V.l7EtaOff,
          tolerance: 0.1,
          unit: '°',
          hints: [
            { text: 'The half-angle rule works off the equator too.' },
            { text: 'Both arrows lie in the $y$–$z$ plane.' },
            { text: '$|{+y}\\rangle$ sits at $\\theta = 90^\\circ$, so the arrows are 30° apart.' },
          ],
          walkthrough: [
            { text: `The arrows are $90^\\circ - 60^\\circ = 30^\\circ$ apart, so $\\eta = ${d(V.l7EtaOff, 0)}^\\circ$.` },
            { text: `Check: the overlap probability is $\\cos^2 15^\\circ \\approx ${d(V.l7POff)}$.` },
          ],
        },
      ],
    },
    {
      id: 'l7-full-turn',
      opener: {
        film: 'belt',
        lede: 'A film of the [[belt-trick|belt trick]]: a block hanging from a belt turns once, then once more, and the belt twists. Then the belt loops around the block and hangs flat again. The words beside it say what each turn means for a spin state.',
      },
      story: L7_STORY['l7-full-turn'],
      review: L7_REVIEW['l7-full-turn'],
      title: 'A full turn flips the sign',
      question: 'If a rotation brings the Bloch arrow all the way round, is the state vector back where it started?',
      lecture: {
        pages: 'L7 pp. 3–4; p. 13 (Reference B, outside the class plan)',
        summary:
          'On an equatorial state, $R_z(\\varphi)$ moves the arrow by $\\varphi$ and adds the overall phase $e^{-i\\varphi/2}$. At 360° the arrow is home but $R_z(2\\pi) = -I$, so the ket is $-|\\psi\\rangle$, the same ray. Only at 720° is $R_z(4\\pi) = I$. Pages 4 and 13 repeat Lecture 6: the generator, and the averages turning like an arrow.',
        equations: ['R_z(\\varphi)|\\psi(\\varphi_0)\\rangle = e^{-i\\varphi/2}|\\psi(\\varphi_0 + \\varphi)\\rangle,\\qquad R_z(2\\pi) = -I,\\qquad R_z(4\\pi) = I'],
      },
      books: [{ source: 'townsend', where: '§2.2, pp. 36–40', adds: 'The rotation operator built from tiny turns, worked turns of $|{+x}\\rangle$, and a first mention of the sign after a full turn.' }],
      visual: {
        kind: 'bloch',
        props: { theta: 90, phi: 0, rotations: true, rotationAngles: [90, 180, 360], landmarks: true, editable: true },
        caption: 'The phasors $\\alpha$ and $\\beta$ show the ket; the point shows only the ray.',
        tryThis: [
          'Press $R_z(360^\\circ)$ once. The point comes back, but both phasors now point the other way: the ket is $-|{+x}\\rangle$.',
          'Press it again. Which total angle brought the phasors home? (720°.)',
          'Drag $\\theta$ to 0, the state $|{+z}\\rangle$, and press $R_z(360^\\circ)$. The point never moves, yet $\\alpha$ still flips.',
        ],
      },
      clues: [],
      insight: 'A full turn brings back the point and every probability, but not the ket: spin ½ needs two full turns to return exactly.',
      pitfalls: [
        'Reading the −1 after 360° as a different state. It is an overall sign, so the ray and every prediction are unchanged.',
        'Thinking the sign needs the point to move. $|{+z}\\rangle$ sits on the axis and still flips sign after 360°.',
      ],
      claims: [claim('l7SpinHalf', 'a spin ½ reads ±ħ/2', () => close(V.l7SpinHalf, 0.5))],
      play: [
        {
          id: 'l7-ft-what-changes',
          kind: 'choice',
          tier: 'warm-up',
          title: 'What did a full turn change?',
          prompt: '$R_z(360^\\circ)$ acts on $|{+x}\\rangle$. What has changed?',
          options: [
            { text: 'The Bloch point', correct: false, why: `No: the point is $(${d(V.l7Rz2piRx, 0)}, 0, 0)$ again.` },
            { text: 'The probability of $+x$', correct: false, why: `No: it is still ${d(V.l7Rz2piP, 0)}.` },
            { text: 'The sign of the ket', correct: true, why: `Right: $\\langle{+x}|R_z(2\\pi)|{+x}\\rangle = -${d(-V.l7Rz2piX, 0)}$.` },
            { text: 'Nothing at all', correct: false, why: 'The column vector is negated, even though nothing measurable changed.' },
          ],
          hints: [
            { text: 'Look at the diagonal of $R_z(2\\pi)$.' },
            { text: '$e^{\\mp i\\pi} = -1$.' },
            { text: 'An overall −1 is a global phase.' },
          ],
          walkthrough: [
            { text: '$R_z(2\\pi) = -I$, so $R_z(2\\pi)|{+x}\\rangle = -|{+x}\\rangle$.' },
            { text: 'A global phase changes no probability and no Bloch point: only the sign changed.' },
          ],
        },
        {
          id: 'l7-ft-sandwich',
          kind: 'numeric',
          tier: 'core',
          title: 'The full-turn sandwich',
          prompt: 'Compute $\\langle{+x}|R_z(2\\pi)|{+x}\\rangle$.',
          answer: V.l7Rz2piX,
          tolerance: 0.001,
          hints: [
            { text: 'Write $R_z(2\\pi)$ as a matrix.' },
            { text: 'It is $-I$.' },
            { text: '$\\langle{+x}|{+x}\\rangle = 1$.' },
          ],
          walkthrough: [
            { text: '$R_z(2\\pi) = \\mathrm{diag}(e^{-i\\pi}, e^{i\\pi}) = -I$.' },
            { text: `So $\\langle{+x}|(-I)|{+x}\\rangle = -${d(-V.l7Rz2piX, 0)}$.` },
            { text: 'The trap is to read the −1 as a different state.' },
          ],
        },
        {
          id: 'l7-ft-still',
          kind: 'numeric',
          tier: 'core',
          title: 'A point that never moves',
          prompt: '$|{+z}\\rangle$ sits on the turning axis, so $R_z(360^\\circ)$ never moves its Bloch point. What is $\\langle{+z}|R_z(2\\pi)|{+z}\\rangle$?',
          answer: V.l7Rz2piZ,
          tolerance: 0.001,
          hints: [
            { text: 'Did the point have to move for the sign to appear?' },
            { text: '$R_z(2\\pi)$ is the same matrix for every state.' },
            { text: 'It is $-I$.' },
          ],
          walkthrough: [
            { text: '$R_z(\\varphi)|{+z}\\rangle = e^{-i\\varphi/2}|{+z}\\rangle$ (Unit 6.3).' },
            { text: `At $\\varphi = 2\\pi$ the factor is $-${d(-V.l7Rz2piZ, 0)}$: the sign belongs to the turn, not to a loop drawn by the point.` },
          ],
        },
        {
          id: 'l7-ft-720',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Truly home',
          prompt: 'What is the smallest positive turn angle $\\varphi$, in degrees, with $R_z(\\varphi)|{+x}\\rangle = |{+x}\\rangle$ exactly, sign included?',
          answer: V.l7FirstHome,
          tolerance: 0.5,
          unit: '°',
          hints: [
            { text: 'Compute $\\langle{+x}|R_z(\\varphi)|{+x}\\rangle$ as a function of $\\varphi$.' },
            { text: 'It is $\\cos(\\varphi/2)$.' },
            { text: 'When is $\\cos(\\varphi/2) = 1$ again?' },
          ],
          walkthrough: [
            { text: '$\\langle{+x}|R_z(\\varphi)|{+x}\\rangle = \\tfrac12(e^{-i\\varphi/2} + e^{i\\varphi/2}) = \\cos\\tfrac{\\varphi}{2}$.' },
            { text: `It is ${d(V.l7Cos90)} at 90°, ${d(V.l7Cos180, 0)} at 180°, −${d(-V.l7Rz2piX, 0)} at 360° and ${d(V.l7Rz4piX, 0)} again only at ${d(V.l7FirstHome, 0)}°.` },
          ],
        },
      ],
    },
    {
      id: 'l7-order',
      story: L7_STORY['l7-order'],
      review: L7_REVIEW['l7-order'],
      title: 'Swapping the order of two measurements',
      question: 'When does measuring z then x predict something different from x then z?',
      lecture: {
        pages: 'L7 p. 5',
        summary:
          'A measurement of $A$ gives outcome $a$ with probability $p(a) = \\langle\\psi|P_a|\\psi\\rangle$ and leaves $P_a|\\psi\\rangle/\\sqrt{p(a)}$ (Unit 3.4 and Unit 4.2). From $|{+z}\\rangle$, $z$ first gives + for certain, while $x$ first makes the $z$ result a coin toss. A repeated $z$ measurement repeats its result.',
        equations: ['p(a) = \\langle\\psi|P_a|\\psi\\rangle,\\qquad |\\psi\\rangle \\to \\frac{P_a|\\psi\\rangle}{\\sqrt{p(a)}}'],
      },
      books: [{ source: 'susskind', where: 'Lecture 5, §5.1.1–5.2', adds: 'A state that is an eigenvector of both observables makes their order irrelevant; for spin components along different axes none exists.' }],
      visual: {
        kind: 'sg-lab',
        props: { source: '+z', axes: ['x', 'z'], keep: ['+'], editable: true, maxDevices: 3, predict: true },
        caption: 'The same two magnets in either order: the plate shows which order keeps the $z$ answer.',
        tryThis: [
          'Predict the − share at the last magnet, then fire. Now swap the magnets to $z$ then $x$: which order keeps the $z$ answer certain?',
          'With $x$ then $z$, add a third magnet along $z$. Of the atoms that reach it, what fraction lands +? (All of them.)',
          `Make the first magnet a 60° tilt, keep −, and end with $z$. Predict the − spot’s share of the source, ${d(V.l7TiltKeepMinus, 4)}, then fire 1000 atoms.`,
        ],
      },
      clues: [],
      insight: 'Order matters when the first measurement leaves states that are not states of the second observable. Randomness alone never does it.',
      pitfalls: [
        'Blaming randomness. Two $z$ magnets give random first readings, yet their order cannot matter.',
        'Forgetting the update. After an $x$ magnet the atom is in $|{\\pm x}\\rangle$ and remembers nothing of $z$.',
      ],
      play: [
        {
          id: 'l7-or-swap',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'x first, then z',
          prompt: 'Prepare $|{+z}\\rangle$. Measure $S_x$, then $S_z$, keeping every atom. What is the probability that $S_z$ reads $-\\hbar/2$?',
          answer: V.l7XzPMinusZ,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Split into the two $x$ results.' },
            { text: 'Each happens half the time.' },
            { text: 'From $|{\\pm x}\\rangle$, the chance of $-z$ is one half.' },
          ],
          walkthrough: [
            { text: '$p(-z) = p(+x)\\,p(-z\\,|\\,{+x}) + p(-x)\\,p(-z\\,|\\,{-x})$.' },
            { text: `$= ${tf(V.l7XzPlusMinus)} + ${tf(V.l7XzMinusMinus)} = ${tf(V.l7XzPMinusZ)}$. With $z$ first it would be ${d(V.l7ZzFirstMinus, 0)}.` },
          ],
        },
        {
          id: 'l7-or-steps',
          kind: 'order',
          tier: 'core',
          title: 'One ideal measurement, step by step',
          prompt: 'Put the steps of an ideal measurement of $A$ on $|\\psi\\rangle$ in order.',
          steps: [
            'Find the projector $P_a$ for each outcome $a$',
            'Compute $p(a) = \\langle\\psi|P_a|\\psi\\rangle$',
            'One outcome $a$ occurs, with probability $p(a)$',
            'Apply $P_a$ to $|\\psi\\rangle$',
            'Divide by $\\sqrt{p(a)}$ to get the state after the measurement',
          ],
          hints: [
            { text: 'Probabilities come before the outcome.' },
            { text: 'The update uses the outcome that happened.' },
            { text: 'The last step restores length 1.' },
          ],
          walkthrough: [
            { text: 'Projectors, then probabilities, then the outcome, then the projection, then the rescaling.' },
            { text: `For $|{+z}\\rangle$ and $S_x$: $p(+x) = ${tf(V.l7PxFromZ)}$, the projected part has length ${d(V.l7BranchLen)}, and rescaling gives $|{+x}\\rangle$.` },
          ],
        },
        {
          id: 'l7-or-repeat',
          kind: 'choice',
          tier: 'core',
          title: 'Measure z again',
          prompt: 'After the $x$ step and a first $z$ reading, you measure $S_z$ again straight away. What happens?',
          options: [
            { text: 'It repeats the first $z$ reading', correct: true, why: `Right: the first $z$ reading prepared a $z$ eigenstate, so the other result has probability ${d(V.l7XzzMinus, 0)}.` },
            { text: 'It splits 50/50 again', correct: false, why: 'Only a different axis would split it; the atom is already in a $z$ eigenstate.' },
            { text: 'It always reads +', correct: false, why: 'It repeats whichever result the first $z$ magnet gave, + or −.' },
            { text: 'It depends on the $x$ result', correct: false, why: 'The $x$ result was erased by the first $z$ reading.' },
          ],
          hints: [
            { text: 'What state does a $z$ reading leave?' },
            { text: 'A $z$ eigenstate.' },
            { text: 'A $z$ eigenstate gives its own value with certainty.' },
          ],
          walkthrough: [
            { text: 'The first $z$ reading prepared $|{+z}\\rangle$ or $|{-z}\\rangle$.' },
            { text: 'A second $z$ reading finds the same value; the randomness came from the $x$ step.' },
          ],
        },
        {
          id: 'l7-or-tilt',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A tilted first magnet',
          prompt: 'Prepare $|{+z}\\rangle$. First measure with a magnet tilted 60° from $z$ toward $x$, keeping every atom, then measure $S_z$. What is $p(-z)$?',
          answer: V.l7TiltMinusZ,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'There are two branches, the + and − states of the tilted magnet.' },
            { text: `The + branch happens with probability $\\cos^2 30^\\circ = ${tf(V.l7TiltPass)}$.` },
            { text: 'From either branch, the chance of $-z$ is $\\sin^2 30^\\circ$ or $\\cos^2 30^\\circ$.' },
          ],
          walkthrough: [
            { text: `$\\tfrac34\\cdot\\tfrac14 + \\tfrac14\\cdot\\tfrac34 = ${d(V.l7TiltKeepPlus, 4)} + ${d(V.l7TiltKeepMinus, 4)} = ${d(V.l7TiltMinusZ, 3)}$.` },
            { text: `With $z$ first, $p(-z) = ${d(V.l7ZzFirstMinus, 0)}$: the tilted step made the $z$ answer uncertain.` },
          ],
        },
      ],
    },
    {
      id: 'l7-compatible',
      story: L7_STORY['l7-compatible'],
      review: L7_REVIEW['l7-compatible'],
      title: 'Compatible measurements share a basis and commute',
      question: 'What property of two observables guarantees that their order never matters?',
      lecture: {
        pages: 'L7 pp. 6–7',
        summary:
          'Two observables with a complete common eigenbasis commute, $[A, B] = 0$, and for Hermitian matrices the converse holds. Measuring them in either order gives the same joint probabilities, because their projectors commute. For spin, $[S_x, S_y] = i\\hbar S_z$ and its cyclic partners, so components along different axes are not compatible.',
        equations: ['[A, B] = AB - BA,\\qquad [S_x, S_y] = i\\hbar S_z,\\quad [S_y, S_z] = i\\hbar S_x,\\quad [S_z, S_x] = i\\hbar S_y'],
      },
      books: [
        { source: 'townsend', where: '§3.1, pp. 75–79; §3.2, pp. 80–81', adds: 'Rotations that do not commute give the commutators of the generators; commuting operators share nondegenerate eigenstates.' },
        { source: 'susskind', where: 'Lecture 5, §5.1.1–5.2', adds: 'Simultaneous eigenvectors, and which spin components can be measured together.' },
      ],
      visual: {
        kind: 'basis-translator',
        props: { mode: 'operator', target: 'x', operator: 'Sz' },
        caption: 'Commuting observables are the ones that some basis makes diagonal together.',
        tryThis: [
          '$S_z$ written in the $x$ basis: is it diagonal? Switch the operator to $S_x$: now?',
          'Try the $y$ basis with $S_z$ and with $S_x$. Is there any basis here in which $S_x$ and $S_z$ are both diagonal? (No: they do not commute.)',
          'Two diagonal matrices always commute. Explain in one sentence why “diagonal in the same basis” forces $[A, B] = 0$.',
        ],
      },
      clues: [],
      claims: [claim('l7SpinHalf', 'a spin ½ reads ±ħ/2', () => close(V.l7SpinHalf, 0.5))],
      insight: 'Commuting is the algebra of compatibility: a shared eigenbasis, commuting projectors, and a measuring order that never matters.',
      pitfalls: [
        'Treating $AB$ as “measure $B$, then $A$”. Measurements act through projectors and the update rule, not by multiplying.',
        'Thinking $[A, B] \\ne 0$ changes every number. From $|{+y}\\rangle$ both orders give the same joint probability, yet different final states.',
      ],
      play: [
        {
          id: 'l7-co-which',
          kind: 'choice',
          tier: 'warm-up',
          title: 'Which pair shares a basis?',
          prompt: 'Which pair of observables can share a complete eigenbasis?',
          options: [
            { text: '$S_x$ and $S_y$', correct: false, why: '$[S_x, S_y] = i\\hbar S_z \\ne 0$.' },
            { text: '$S_z$ and $I + 4S_z$', correct: true, why: `Right: both are diagonal in the $z$ basis, and $[S_z, I + 4S_z] = ${d(V.l7CommSzB, 0)}$.` },
            { text: '$S_x$ and $S_z$', correct: false, why: `$[S_z, S_x] = i\\hbar S_y$; its entries have size ${d(V.l7CommXZNonzero, 1)}ħ².` },
            { text: '$S_z$ and the spin along an axis 60° from $z$', correct: false, why: `Their commutator is $i\\hbar\\,${d(V.l7CoTilt)}\\,S_y$, not zero.` },
          ],
          hints: [
            { text: 'A shared basis means a zero commutator.' },
            { text: 'Functions of $S_z$ commute with $S_z$.' },
            { text: 'Spin components along different axes never commute.' },
          ],
          walkthrough: [
            { text: '$I + 4S_z$ has the eigenstates $|{\\pm z}\\rangle$, so it shares the $z$ basis with $S_z$.' },
            { text: 'Each other pair has $[A, B] \\ne 0$.' },
          ],
        },
        {
          id: 'l7-co-joint',
          kind: 'numeric',
          tier: 'core',
          title: 'How much does the order change?',
          prompt: 'Start in $|{+z}\\rangle$. Take the probability of + then + for “$z$ then $x$”, and subtract the probability of + then + for “$x$ then $z$”.',
          answer: V.l7JointDiff,
          tolerance: 0.005,
          unit: 'probability',
          hints: [
            { text: 'Use the squared length of the part that survives both projectors.' },
            { text: '$z$ first: $1\\cdot\\tfrac12$.' },
            { text: '$x$ first: $\\tfrac12\\cdot\\tfrac12$.' },
          ],
          walkthrough: [
            { text: `$z$ then $x$: $1\\cdot\\tfrac12 = ${tf(V.l7JointZX)}$; $x$ then $z$: $\\tfrac12\\cdot\\tfrac12 = ${tf(V.l7JointXZ)}$.` },
            { text: `The difference is $${tf(V.l7JointDiff)}$, because $P_{+x}P_{+z} \\ne P_{+z}P_{+x}$.` },
          ],
        },
        {
          id: 'l7-co-yplus',
          kind: 'choice',
          tier: 'core',
          title: 'Same number, different story',
          prompt: 'From $|{+y}\\rangle$, both orders of $S_z$ and $S_x$ give probability one quarter for + then +. What does this show?',
          options: [
            { text: '$S_z$ and $S_x$ commute', correct: false, why: '$[S_z, S_x] = i\\hbar S_y \\ne 0$.' },
            { text: 'Order never matters for $|{+y}\\rangle$', correct: false, why: 'The final states differ: $|{+x}\\rangle$ after $z$ then $x$, $|{+z}\\rangle$ after $x$ then $z$.' },
            { text: 'One statistic can hide an order effect', correct: true, why: 'Right: a nonzero commutator says order can matter, not that every number shows it.' },
            { text: 'The two projectors commute', correct: false, why: '$P_{+x}P_{+z} \\ne P_{+z}P_{+x}$.' },
          ],
          hints: [
            { text: 'Compare the final states, not only the numbers.' },
            { text: 'After $z$ then $x$, the state is $|{+x}\\rangle$.' },
            { text: 'After $x$ then $z$, it is $|{+z}\\rangle$.' },
          ],
          walkthrough: [
            { text: `Both joint probabilities are $${tf(V.l7JointYZX)}$ (the story, Unit 7.4).` },
            { text: 'But the states left behind differ, so the order still matters for what comes next.' },
          ],
        },
        {
          id: 'l7-co-tilt',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A tilted commutator',
          prompt: 'Let $S_{\\hat n}$ be the spin along an axis tilted 60° from $z$ toward $x$. Then $[S_z, S_{\\hat n}] = i\\hbar\\,c\\,S_y$. Find $c$.',
          answer: V.l7CoTilt,
          tolerance: 0.002,
          hints: [
            { text: 'Use $[S_{\\hat a}, S_{\\hat b}] = i\\hbar(\\hat a\\times\\hat b)\\cdot\\vec S$.' },
            { text: '$\\hat n = (\\sin 60^\\circ, 0, \\cos 60^\\circ)$.' },
            { text: '$\\hat z\\times\\hat n = (0, \\sin 60^\\circ, 0)$.' },
          ],
          walkthrough: [
            { text: 'The cross product points along $y$ with length $\\sin 60^\\circ$.' },
            { text: `So $c = \\sin 60^\\circ \\approx ${d(V.l7CoTilt)}$. It is zero only for a tilt of 0° or 180°.` },
          ],
        },
      ],
    },
    {
      id: 'l7-spreads',
      story: L7_STORY['l7-spreads'],
      review: L7_REVIEW['l7-spreads'],
      title: 'Spreads you can read off the sphere',
      question: 'How uncertain is each spin component in one prepared state?',
      lecture: {
        pages: 'L7 p. 8; p. 13 (Reference B, last line)',
        summary:
          'The spread $\\Delta A$ of Unit 3.6 belongs to one prepared state measured on fresh copies. For spin every reading is $\\pm\\hbar/2$, so $(\\Delta S_j)^2 = \\tfrac{\\hbar^2}{4}(1 - r_j^2)$: the Bloch arrow fixes all three spreads. The error of an average shrinks with more trials; the spread does not.',
        equations: ['(\\Delta S_j)^2 = \\langle S_j^2\\rangle - \\langle S_j\\rangle^2 = \\tfrac{\\hbar^2}{4}\\,(1 - r_j^2)'],
      },
      books: [
        { source: 'townsend', where: '§1.4, pp. 15–17', adds: 'The spread of $S_z$ for a state with complex amplitudes (Example 1.2).' },
        { source: 'susskind', where: 'Lecture 3, §3.8; Lecture 5, §5.4', adds: 'Every spin state reads + for certain along its own direction; the spread through the shifted operator.' },
      ],
      visual: {
        kind: 'deposit-stats',
        props: { state: [60, 0], axis: 'z', seed: 7 },
        caption: 'The band is the error of the average; each atom still reads $\\pm\\hbar/2$.',
        tryThis: [
          `Predict first: $p(+z) = ${tf(V.l7PplusRule)}$, so $\\langle S_z\\rangle = \\hbar/4$ and $\\Delta S_z \\approx ${d(V.l7Sd60z)}\\,\\hbar$.`,
          'Fire 10, then 100, then 1000 atoms. The band around the count narrows, but no atom ever lands between the spots.',
          `From the final counts, estimate $\\Delta S_z = \\hbar\\sqrt{p_+p_-}$ and compare it with ${d(V.l7Sd60z)}ħ.`,
        ],
      },
      clues: [],
      claims: [claim('l7SpinHalf', 'a spin ½ reads ±ħ/2', () => close(V.l7SpinHalf, 0.5))],
      insight: 'For a spin ½ the spreads are geometry: each is ħ/2 times the distance from the Bloch point to that axis.',
      pitfalls: [
        'Confusing the spread with the error of an average. More atoms shrink the error, never the spread.',
        'Calling a state fuzzy because some spread is nonzero. Along its own Bloch arrow every pure state has zero spread.',
      ],
      play: [
        {
          id: 'l7-sp-plusz',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Sideways spread of up',
          prompt: 'What is $\\Delta S_x$ in the state $|{+z}\\rangle$?',
          answer: V.l7SdZx,
          tolerance: 0.005,
          unit: 'ħ',
          hints: [
            { text: 'Use $(\\Delta S_j)^2 = \\tfrac{\\hbar^2}{4}(1 - r_j^2)$.' },
            { text: '$r_x = 0$ for $|{+z}\\rangle$.' },
            { text: 'Take the square root.' },
          ],
          walkthrough: [
            { text: '$(\\Delta S_x)^2 = \\tfrac{\\hbar^2}{4}$, so $\\Delta S_x = \\hbar/2$.' },
            { text: 'A fair coin between $\\pm\\hbar/2$.' },
          ],
        },
        {
          id: 'l7-sp-sixty',
          kind: 'numeric',
          tier: 'core',
          title: 'Spread at 60°',
          prompt: 'A state has $\\theta = 60^\\circ$, $\\varphi = 0$. What is $\\Delta S_z$?',
          answer: V.l7Sd60z,
          tolerance: 0.002,
          unit: 'ħ',
          hints: [
            { text: '$r_z = \\cos\\theta$.' },
            { text: `So $r_z = ${d(V.l7R60z, 1)}$.` },
            { text: '$\\Delta S_z = \\tfrac{\\hbar}{2}\\sqrt{1 - r_z^2}$.' },
          ],
          walkthrough: [
            { text: `$\\sqrt{1 - ${d(V.l7R60z, 2)}^2} = ${d(V.l7R60x)}$.` },
            { text: `Half of it: $\\Delta S_z \\approx ${d(V.l7Sd60z)}\\,\\hbar$, the same as in Townsend’s Example 1.2.` },
          ],
        },
        {
          id: 'l7-sp-sum',
          kind: 'numeric',
          tier: 'core',
          title: 'The sum of the squares',
          prompt: 'For any pure state, what is $(\\Delta S_x)^2 + (\\Delta S_y)^2 + (\\Delta S_z)^2$?',
          answer: V.l7SumSq,
          tolerance: 0.005,
          unit: 'ħ²',
          hints: [
            { text: 'Add the three formulas.' },
            { text: '$r_x^2 + r_y^2 + r_z^2 = 1$.' },
            { text: '$\\tfrac{\\hbar^2}{4}(3 - 1)$.' },
          ],
          walkthrough: [
            { text: `$\\tfrac{\\hbar^2}{4}(3 - |\\vec r|^2) = ${d(V.l7SumSq, 1)}\\,\\hbar^2$.` },
            { text: 'The same for every pure state.' },
          ],
        },
        {
          id: 'l7-sp-ninety',
          kind: 'numeric',
          tier: 'stretch',
          title: 'From odds to spread',
          prompt: `A magnet along $\\hat n$ gives + with probability ${d(V.l7P90, 1)}. What is $\\Delta S_{\\hat n}$?`,
          answer: V.l7Sd90,
          tolerance: 0.002,
          unit: 'ħ',
          hints: [
            { text: '$p_+ = \\tfrac12 + \\langle S_{\\hat n}\\rangle/\\hbar$.' },
            { text: `So $\\langle S_{\\hat n}\\rangle = ${d(V.l7Avg90, 1)}\\,\\hbar$.` },
            { text: '$(\\Delta S_{\\hat n})^2 = \\tfrac{\\hbar^2}{4} - \\langle S_{\\hat n}\\rangle^2$.' },
          ],
          walkthrough: [
            { text: `$0.25 - ${d(V.l7Avg90 ** 2, 2)} = ${d(V.l7Var90, 2)}$, so $\\Delta S_{\\hat n} = ${d(V.l7Sd90, 1)}\\,\\hbar$.` },
            { text: `Equivalently $\\hbar\\sqrt{p_+p_-} = \\hbar\\sqrt{${d(V.l7Var90, 2)}}$.` },
          ],
        },
      ],
    },
    {
      id: 'l7-uncertainty',
      story: L7_STORY['l7-uncertainty'],
      review: L7_REVIEW['l7-uncertainty'],
      title: 'A floor under the product of spreads',
      question: 'How small can the spreads of Sx and Sy be at the same time?',
      lecture: {
        pages: 'L7 pp. 9–11; p. 12 (Reference A, outside the class plan)',
        summary:
          'From $|\\vec r| = 1$ alone, $(\\Delta S_x\\Delta S_y)^2 = \\tfrac{\\hbar^4}{16}(r_z^2 + r_x^2r_y^2)$, so $\\Delta S_x\\Delta S_y \\ge \\tfrac{\\hbar}{2}\\lvert\\langle S_z\\rangle\\rvert = \\tfrac12\\lvert\\langle[S_x, S_y]\\rangle\\rvert$. The general Robertson relation has the same form for any two observables. The spreads belong to one preparation; the bound says nothing about one measurement disturbing another.',
        equations: ['\\Delta S_x\\,\\Delta S_y \\ge \\tfrac{\\hbar}{2}\\lvert\\langle S_z\\rangle\\rvert,\\qquad \\Delta A\\,\\Delta B \\ge \\tfrac12\\lvert\\langle[A, B]\\rangle\\rvert'],
      },
      books: [
        { source: 'townsend', where: '§3.5, pp. 91–93', adds: 'The general uncertainty relation through the Schwarz inequality, applied to angular momentum.' },
        { source: 'susskind', where: 'Lecture 5, §5.5–5.7', adds: 'The same relation, with the shifted operators of the notes.' },
      ],
      visual: {
        kind: 'bloch',
        props: { theta: 60, phi: 45, measure: 'z', landmarks: true, editable: true },
        caption: 'The table gives $\\langle S_x\\rangle$, $\\langle S_y\\rangle$ and $\\langle S_z\\rangle$; each spread is $\\sqrt{\\hbar^2/4 - \\langle S_j\\rangle^2}$.',
        tryThis: [
          `Use the table to get $\\Delta S_x$ and $\\Delta S_y$, then compare their product, ${d(V.l7Prod6045)}ħ², with $\\tfrac{\\hbar}{2}\\lvert\\langle S_z\\rangle\\rvert$, ${d(V.l7Bound6045)}ħ².`,
          'Set $\\varphi = 0$, so $\\langle S_y\\rangle = 0$. Is the bound now met exactly?',
          `Find the state with the largest product (${d(V.l7MaxProd, 2)}ħ², at a pole) and the one with the largest gap (${d(V.l7MaxGap)}ħ², on the equator at $\\varphi = 45^\\circ$).`,
        ],
      },
      clues: [],
      claims: [claim('l7SpinHalf', 'the ½ in the bound', () => close(V.l7SpinHalf, 0.5))],
      insight: 'The floor comes from the length of the Bloch arrow: two sideways spreads cannot both be small unless the arrow points along the third axis.',
      pitfalls: [
        'Reading a zero floor as “they commute”. At $|{+x}\\rangle$ the average of $[S_x, S_y]$ is zero, but the commutator is not.',
        'Reading the bound as measurement disturbance. Both spreads are measured on fresh copies of one prepared state.',
      ],
      play: [
        {
          id: 'l7-un-zero',
          kind: 'choice',
          tier: 'warm-up',
          title: 'A zero product',
          prompt: 'In $|{+x}\\rangle$, $\\Delta S_x\\Delta S_y = 0$. Which statement is true?',
          options: [
            { text: '$S_x$ and $S_y$ commute', correct: false, why: '$[S_x, S_y] = i\\hbar S_z$, which is not zero.' },
            { text: '$S_x$ is definite and $S_y$ is a fair coin', correct: true, why: `Right: $\\Delta S_x = ${d(V.l7VarXx, 0)}$ and $\\Delta S_y = ${d(V.l7SdXy, 1)}\\,\\hbar$.` },
            { text: 'Both values are definite', correct: false, why: `$\\Delta S_y = ${d(V.l7SdXy, 1)}\\,\\hbar$: a fair coin.` },
            { text: 'The bound is broken', correct: false, why: 'The bound is $\\tfrac{\\hbar}{2}\\lvert\\langle S_z\\rangle\\rvert = 0$, and $0 \\ge 0$.' },
          ],
          hints: [
            { text: 'Which factor is zero?' },
            { text: '$\\Delta S_x = 0$ because $r_x = 1$.' },
            { text: '$r_y = 0$, so $\\Delta S_y = \\hbar/2$.' },
          ],
          walkthrough: [
            { text: 'The product is zero because one factor is zero.' },
            { text: 'The bound is $\\tfrac{\\hbar}{2}\\lvert\\langle S_z\\rangle\\rvert = 0$, while the commutator is still $i\\hbar S_z \\ne 0$.' },
          ],
        },
        {
          id: 'l7-un-product',
          kind: 'numeric',
          tier: 'core',
          title: 'Product at (60°, 45°)',
          prompt: 'A state has $\\theta = 60^\\circ$, $\\varphi = 45^\\circ$. Find $\\Delta S_x\\Delta S_y$.',
          answer: V.l7Prod6045,
          tolerance: 0.002,
          unit: 'ħ²',
          hints: [
            { text: '$r_x = r_y = \\sin 60^\\circ\\cos 45^\\circ$.' },
            { text: `So $r_x^2 = r_y^2 = ${d(V.l7Rx2)}$.` },
            { text: `Each spread is $\\tfrac{\\hbar}{2}\\sqrt{${d(V.l7OneMinusRx2)}}$.` },
          ],
          walkthrough: [
            { text: `$\\tfrac{\\hbar^2}{4}\\times ${d(V.l7OneMinusRx2)} \\approx ${d(V.l7Prod6045)}\\,\\hbar^2$.` },
            { text: `The bound is $\\tfrac{\\hbar}{2}\\cdot\\tfrac{\\hbar}{4} = ${d(V.l7Bound6045)}\\,\\hbar^2$: it holds with room to spare.` },
          ],
        },
        {
          id: 'l7-un-max',
          kind: 'numeric',
          tier: 'core',
          title: 'The largest product',
          prompt: 'What is the largest value $\\Delta S_x\\Delta S_y$ can take in any pure state?',
          answer: V.l7MaxProd,
          tolerance: 0.002,
          unit: 'ħ²',
          hints: [
            { text: 'The product is $\\tfrac{\\hbar^2}{4}\\sqrt{(1 - r_x^2)(1 - r_y^2)}$.' },
            { text: 'Make $r_x$ and $r_y$ both zero.' },
            { text: 'That is a pole.' },
          ],
          walkthrough: [
            { text: `At $|{\\pm z}\\rangle$ both factors are 1, so the product is ${d(V.l7MaxProd, 2)}ħ².` },
            { text: 'There the bound is met exactly too.' },
          ],
        },
        {
          id: 'l7-un-gap',
          kind: 'numeric',
          tier: 'stretch',
          title: 'The largest gap',
          prompt: 'Over all pure states, what is the largest gap $\\Delta S_x\\Delta S_y - \\tfrac{\\hbar}{2}\\lvert\\langle S_z\\rangle\\rvert$?',
          answer: V.l7MaxGap,
          tolerance: 0.002,
          unit: 'ħ²',
          hints: [
            { text: 'The gap comes from the dropped term $r_x^2r_y^2$.' },
            { text: 'Put the state on the equator, where $r_z = 0$.' },
            { text: 'Then maximize $\\sqrt{(1 - r_x^2)(1 - r_y^2)}$ with $r_x^2 + r_y^2 = 1$.' },
          ],
          walkthrough: [
            { text: 'On the equator the bound is 0 and the product is $\\tfrac{\\hbar^2}{4}|r_xr_y|$.' },
            { text: `It is largest at $r_x = r_y = 1/\\sqrt2$ ($\\varphi = 45^\\circ$): the gap is $\\tfrac{\\hbar^2}{8} = ${d(V.l7MaxGap)}\\,\\hbar^2$.` },
          ],
        },
      ],
    },
  ],
}
