import type { Lecture } from './schema'
import { V, d } from './L8.values'
import { L8_STORY } from './L8.story'
import { L8_REVIEW } from './L8.review'
import './bridges448'

// Every number a learner sees in this lecture is computed in L8.values.ts, then asserted in keyed claims
// (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy). Plan: docs/roles/proposals/P-L8-story.md, with the
// judge's rulings (docs/roles/decisions/448-L8L11.md, L8): built from notes pp. 1-11 (§§8.1-8.9) and the Lecture 9 notes pp. 1-6 (§§9.1-9.3),
// which import the attack and the test from Lecture 8 (class 8 stopped before the attack, so `l8-attack:b1` carries the class marker
// "Class 9 starts here"). Rosetta (R3): the notes' ϑ is χ, the message bit m is x, the bases are H/V and D/A (the notes' Z and X). The
// polarization sphere names its poles H/V, D/A, C± (R4). The `bb84` ledger kind, the `bb84-bench` widget and the `catch-eve` Arcade game
// share one seeded engine (R7). No homework exists for L8. The 448 -> 709 chips live in content/bridges448.ts.

export const L8: Lecture = {
  id: 'L8',
  number: 8,
  title: 'Polarization and BB84',
  outcomes: [
    'Show that the three Pauli variances of a pure state always sum to 2.',
    'Predict what an H/V analyzer and a D/A analyzer report for a photon, including the cos² of the angle between them.',
    'Derive the rotation matrix of light, its generator σ_y, the circular states, and why a photon’s Bloch point turns twice as far.',
    'Run and sift a BB84 exchange.',
    'Derive the error rate Q = ¼ of a full intercept–resend attack, say what Eve learns, and size a test sample.',
  ],
  prerequisites: ['bloch-spreads', 'mutually-unbiased', 'born-rule', 'rz', 'full-turn', 'ray-angle'],
  // Symbols defined in the text itself (symbol → the unit, beat or site whose sentence defines it). Kets, bras, the average and the
  // letters of earlier lectures are mapped to the first unit that uses them: a recap.
  symbols: {
    '\\sigma_x': 'l8-variance-sum:b1',
    '\\sigma_y': 'l8-variance-sum:b1',
    '\\sigma_z': 'l8-variance-sum:b1',
    '\\langle\\cdot\\rangle': 'l8-variance-sum:b1',
    'r_i': 'l8-variance-sum:b1',
    '\\sigma_i': 'l8-variance-sum:b1',
    r: 'l8-variance-sum:b1',
    'r_x': 'l8-variance-sum:b1',
    'r_y': 'l8-variance-sum:b1',
    'r_z': 'l8-variance-sum:b1',
    I: 'l8-variance-sum:b2',
    '|\\cdot\\rangle': 'l8-variance-sum:b4',
    '|+z\\rangle': 'l8-variance-sum:b4',
    '\\vec r': 'l8-variance-sum:b6',
    '|H\\rangle': 'l8-polarization:b1',
    '|V\\rangle': 'l8-polarization:b1',
    '|\\psi\\rangle': 'l8-polarization:b2',
    '\\alpha': 'l8-polarization:b2',
    '\\beta': 'l8-polarization:b2',
    H: 'l8-polarization:b2',
    V: 'l8-polarization:b2',
    '|D\\rangle': 'l8-polarization:b3',
    '|A\\rangle': 'l8-polarization:b3',
    '|-z\\rangle': 'l8-polarization:b4',
    '|+x\\rangle': 'l8-polarization:b4',
    '|-x\\rangle': 'l8-polarization:b4',
    P: 'l8-polarization:b2',
    '\\langle\\cdot|\\cdot\\rangle': 'l8-polarization',
    '\\chi': 'l8-polarization:b2',
    D: 'l8-polarization:b3',
    A: 'l8-polarization:b3',
    'R_': 'l8-turning:b1',
    '\\varphi': 'l8-turning:b1',
    '|p(\\chi)\\rangle': 'l8-turning:b3',
    '\\chi_a': 'l8-turning:b3',
    '|p(\\chi_a)\\rangle': 'l8-turning:b3',
    i: 'l8-photon-spin:b1',
    G: 'l8-photon-spin:b1',
    'J_z': 'l8-photon-spin:b2',
    '\\hbar': 'l8-photon-spin:b2',
    '|C_\\pm\\rangle': 'l8-photon-spin:b2',
    e: 'l8-photon-spin:b3',
    'C_\\pm': 'l8-photon-spin:b6',
    '|C_+\\rangle': 'l8-photon-spin:b2',
    '|C_-\\rangle': 'l8-photon-spin:b2',
    c: 'l8-key:b2',
    '\\oplus': 'l8-key:b2',
    k: 'l8-key:b2',
    a: 'l8-bb84:b2',
    'B_A': 'l8-bb84:b2',
    'B_B': 'l8-bb84:b2',
    b: 'l8-bb84:b2',
    'B_E': 'l8-attack:b1',
    Q: 'l8-attack:b3',
    f: 'l8-attack:b7',
    m: 'l8-test:b1',
    'n_': 'l8-test:b1',
    '\\hat Q': 'l8-test:b1',
  },
  units: [
    {
      id: 'l8-variance-sum',
      story: L8_STORY['l8-variance-sum'],
      review: L8_REVIEW['l8-variance-sum'],
      title: 'Three variances that always add to two',
      question: 'If one spin component is certain, how random are the other two?',
      lecture: {
        pages: 'L8 p. 2 (§8.1)',
        summary:
          'Every Pauli reading is $+1$ or $-1$, so $\\sigma_i^2 = I$ and $(\\Delta\\sigma_i)^2 = 1 - r_i^2$. A pure state has $r^2 = 1$, so the three variances always total 2: a state can only move that total from one component to another.',
        equations: ['(\\Delta\\sigma_i)^2 = 1 - r_i^2', '\\sum_i(\\Delta\\sigma_i)^2 = 3 - r^2 = 2'],
      },
      books: [],
      visual: {
        kind: 'bloch',
        props: { theta: 60, phi: 45, landmarks: true, editable: true },
        caption: 'A pure state on the sphere: read the three averages, then add the three variances.',
        tryThis: [
          `Read the three averages ⟨S⟩ and double each to get r = (${d(V.l8rStarX, 3)}, ${d(V.l8rStarY, 3)}, ${d(V.l8rStarZ, 3)}). Work out 1 − r² for each component and add them: the total is 2.`,
          'Press the |+z⟩ button. Now r = (0, 0, 1), so the variances are 1, 1 and 0, and the total is still 2.',
          `Set θ to 55° and φ to 45° (the sliders move in whole degrees). All three variances come out near ${d(V.l8VarsEqual, 2)}, and they still add to 2.`,
        ],
      },
      clues: [],
      insight: 'A pure state fixes the total uncertainty of the three Pauli measurements at 2. A state can only move that total from one component to another.',
      pitfalls: [
        'Hoping to make all three variances small at once. The total is fixed at 2, whatever the pure state.',
        'Reading “$z$ is certain” as “$x$ and $y$ are small”. Certainty in one component makes the other two as random as they can be.',
      ],
      play: [
        {
          id: 'l8-vs-sum',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The total of the three',
          prompt: 'What do the three Pauli variances $(\\Delta\\sigma_x)^2$, $(\\Delta\\sigma_y)^2$ and $(\\Delta\\sigma_z)^2$ add up to for any pure state?',
          answer: V.l8VarSumWorst,
          tolerance: 0.001,
          hints: [
            { text: 'Each variance is $1 - r_i^2$.' },
            { text: 'Add the three: three ones, minus $r_x^2 + r_y^2 + r_z^2$.' },
            { text: 'A pure state has $r^2 = 1$.' },
          ],
          walkthrough: [
            { text: 'The sum is $(1 - r_x^2) + (1 - r_y^2) + (1 - r_z^2) = 3 - r^2$.' },
            { text: `For a pure state $r^2 = 1$, so the total is $3 - 1 = ${d(V.l8VarSumWorst, 0)}$.` },
          ],
        },
        {
          id: 'l8-vs-pole',
          kind: 'numeric',
          tier: 'core',
          title: 'At the north pole',
          prompt: 'In the state $|{+z}\\rangle$, what is $(\\Delta\\sigma_x)^2$?',
          answer: V.l8VarXPlusZ,
          tolerance: 0.001,
          hints: [
            { text: 'Find the average $r_x$ first.' },
            { text: 'For $|{+z}\\rangle$ the vector is $r = (0, 0, 1)$, so $r_x = 0$.' },
            { text: 'Then $(\\Delta\\sigma_x)^2 = 1 - r_x^2$.' },
          ],
          walkthrough: [
            { text: 'The state $|{+z}\\rangle$ has $r_x = 0$: an $x$ magnet gives a fair coin.' },
            { text: `So $(\\Delta\\sigma_x)^2 = 1 - 0 = ${d(V.l8VarXPlusZ, 0)}$, the largest a variance can be.` },
          ],
        },
        {
          id: 'l8-vs-mixed',
          kind: 'numeric',
          tier: 'stretch',
          title: 'A mixture (beyond the notes)',
          prompt: 'A [[mixture]] sits inside the ball at $\\vec r = (0, 0, 0.6)$. Its Pauli averages still square to 1. What do the three variances add up to?',
          answer: V.l8MixSum06,
          tolerance: 0.001,
          hints: [
            { text: 'Each variance is still $1 - r_i^2$, because every reading squares to 1.' },
            { text: 'The sum is $3 - r^2$ with $r$ the length of the vector.' },
            { text: 'Here $r^2 = 0.6^2 = 0.36$.' },
          ],
          walkthrough: [
            { text: 'Inside the ball $\\langle\\sigma_i^2\\rangle = 1$ still holds, so the variances are $1 - r_i^2$.' },
            { text: `They add to $3 - 0.36 = ${d(V.l8MixSum06, 2)}$: more than 2, because a mixture is less certain than a pure state.` },
          ],
        },
      ],
    },
    {
      id: 'l8-polarization',
      story: L8_STORY['l8-polarization'],
      review: L8_REVIEW['l8-polarization'],
      title: 'A second qubit: the polarization of light',
      question: 'How does one photon’s polarization behave like a spin state?',
      lecture: {
        pages: 'L8 p. 3 (§8.2)',
        summary:
          'Light along a fixed line has two perpendicular polarizations, $|H\\rangle$ and $|V\\rangle$, and every polarization is $\\alpha|H\\rangle + \\beta|V\\rangle$. A beam splitter makes one click per photon. The diagonal pair $|D\\rangle$, $|A\\rangle$ is mutually unbiased with H/V.',
        equations: ['|\\psi\\rangle = \\alpha|H\\rangle + \\beta|V\\rangle', '|D\\rangle, |A\\rangle = \\tfrac{1}{\\sqrt2}\\left(|H\\rangle \\pm |V\\rangle\\right)'],
      },
      books: [townsendRef('§2.7, pp. 59–62', 'Photon polarization as a two-state system, with its amplitudes taken from classical optics.')],
      visual: {
        kind: 'projector',
        props: { state: 30, basis: 0, editableBasis: true, labels: 'polarization' },
        caption: 'The plane of linear polarizations: the arrow’s angle is the polarizer’s angle.',
        tryThis: [
          `With χ = 30° and the analyzer at 0°, the readout gives P(H) = ${d(V.l8PH30 * 100, 0)}% and P(V) = ${d(V.l8PV30 * 100, 0)}%.`,
          'Set χ to 0° and move the analyzer angle to 45° (the D/A pair). A horizontal photon now gives 50% for D and 50% for A.',
          'Set χ to 45°. With the analyzer at 45° the D port is certain (100%); with the analyzer back at 0°, H and V are a coin (50% each).',
        ],
      },
      clues: [],
      insight: 'A photon’s polarization behaves like a spin: H/V and D/A are two mutually unbiased bases, and every photon makes exactly one click.',
      pitfalls: [
        'Picturing half a photon at each detector. A photon makes one click; the chances appear over many photons.',
        'Thinking the photon changed between an H/V and a D/A analyzer. The state is the same; the question the apparatus asks is different.',
      ],
      play: [
        {
          id: 'l8-po-d-in-hv',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'A diagonal photon in an H/V analyzer',
          prompt: 'A photon prepared in $|D\\rangle$ meets an H/V analyzer. What is the chance of the $H$ port?',
          answer: V.l8PHD,
          tolerance: 0.001,
          hints: [
            { text: 'The chance is the squared overlap of the analyzer’s state with the photon’s.' },
            { text: '$|D\\rangle = (|H\\rangle + |V\\rangle)/\\sqrt2$, so $\\langle H|D\\rangle = 1/\\sqrt2$.' },
            { text: 'Square it.' },
          ],
          walkthrough: [
            { text: 'The overlap is $\\langle H|D\\rangle = 1/\\sqrt2$.' },
            { text: `Its square is $\\tfrac12$, that is ${d(V.l8PHD, 1)}. The two bases are mutually unbiased.` },
          ],
        },
        {
          id: 'l8-po-30',
          kind: 'numeric',
          tier: 'core',
          title: 'Thirty degrees from horizontal',
          prompt: 'A photon is polarized at χ = 30° from horizontal. What is the chance that an H/V analyzer sends it to the $V$ port?',
          answer: V.l8PV30,
          tolerance: 0.001,
          hints: [
            { text: 'Write the state as $\\cos\\chi\\,|H\\rangle + \\sin\\chi\\,|V\\rangle$.' },
            { text: 'The $V$ port has amplitude $\\sin\\chi$.' },
            { text: 'Square $\\sin 30^\\circ$.' },
          ],
          walkthrough: [
            { text: 'The amplitude of $V$ is $\\sin 30^\\circ = 0.5$.' },
            { text: `The chance is its square, ${d(V.l8PV30, 2)}.` },
          ],
        },
        {
          id: 'l8-po-mub',
          kind: 'choice',
          tier: 'core',
          title: 'Which bases are unbiased?',
          prompt: 'Which pair of bases is mutually unbiased?',
          options: [
            { text: 'H/V and D/A', correct: true, why: 'Right: every state of one pair gives 50/50 in the other.' },
            { text: 'H/V and V/H (the same basis in the other order)', correct: false, why: 'The same two states give certainty, not 50/50.' },
            { text: 'D/A and A/D', correct: false, why: 'Again the same basis: an A photon in it is certain.' },
            { text: 'H and D only', correct: false, why: 'A basis needs two orthogonal states, and these two are not.' },
          ],
          hints: [
            { text: 'Mutually unbiased means a state of one basis is a fair coin in the other.' },
            { text: 'Check what an $H$ photon does in a D/A analyzer.' },
            { text: 'It gives ½ and ½.' },
          ],
          walkthrough: [
            { text: 'Test a state of one basis in the other: $H$ in D/A gives D or A with chance ½ each.' },
            { text: 'The same holds for $V$, $D$ and $A$, so H/V and D/A are unbiased.' },
          ],
        },
      ],
    },
    {
      id: 'l8-turning',
      story: L8_STORY['l8-turning'],
      review: L8_REVIEW['l8-turning'],
      title: 'Turning a polarization: the rotation matrix',
      question: 'What matrix turns a polarization, and what does an analyzer pass?',
      lecture: {
        pages: 'L8 p. 4 (§8.3)',
        summary:
          'Polarization amplitudes turn like the transverse electric field, so $R_{\\mathrm{pol}}(\\varphi)$ has the columns $(\\cos\\varphi, \\sin\\varphi)$ and $(-\\sin\\varphi, \\cos\\varphi)$. An analyzer at $\\chi_a$ passes a photon at $\\chi$ with chance $\\cos^2\\Delta\\chi$.',
        equations: ['R_{\\mathrm{pol}}(\\varphi) = \\begin{pmatrix}\\cos\\varphi & -\\sin\\varphi\\\\ \\sin\\varphi & \\cos\\varphi\\end{pmatrix}', 'P(\\text{aligned}) = \\cos^2\\Delta\\chi'],
      },
      books: [townsendRef('p. 62, eqs. (2.111)–(2.113)', 'The rotation of a polarization state about the beam and the chance an analyzer passes it.')],
      visual: {
        kind: 'projector',
        props: { state: 60, basis: 45, editableBasis: true, labels: 'polarization' },
        caption: 'The angle between the arrow and the analyzer sets the chances.',
        tryThis: [
          `With χ = 60° and the analyzer at 45° (Δχ = 15°), the aligned port passes ${d(V.l8Pal15 * 100, 1)}% and the other port ${d(V.l8PalOther15 * 100, 1)}%.`,
          'Set the analyzer to 60°. The aligned port now passes 100%, and the second port, at 150°, never fires.',
          'With the analyzer at 60°, set χ to 240°, which is 60° turned by 180°. Every chance is the same: an arrow and its opposite are one polarization.',
        ],
      },
      clues: [],
      insight: 'The turn of light comes from geometry, and its chances use the whole angle: the aligned port passes $\\cos^2\\Delta\\chi$.',
      pitfalls: [
        'Using the half angle of spin for light. A photon needs a 90° analyzer turn to be blocked, a spin needs 180°.',
        'Reading the notes’ ϑ as a Bloch angle. It is χ, an angle in the lab.',
      ],
      play: [
        {
          id: 'l8-tu-15',
          kind: 'numeric',
          tier: 'core',
          title: 'Fifteen degrees off',
          prompt: 'A photon is polarized at $\\chi = 60^\\circ$ and the analyzer is set to $\\chi_a = 45^\\circ$. What is the chance of the aligned port?',
          answer: V.l8Pal15,
          tolerance: 0.001,
          hints: [
            { text: 'The chance depends on the angle between the photon and the analyzer.' },
            { text: '$P(\\text{aligned}) = \\cos^2\\Delta\\chi$ with $\\Delta\\chi = \\chi - \\chi_a$.' },
            { text: 'Here $\\Delta\\chi = 15^\\circ$.' },
          ],
          walkthrough: [
            { text: 'The angle between photon and analyzer is $\\Delta\\chi = 60^\\circ - 45^\\circ = 15^\\circ$.' },
            { text: `The aligned port passes $\\cos^2 15^\\circ = ${d(V.l8Pal15, 3)}$.` },
          ],
        },
        {
          id: 'l8-tu-matrix',
          kind: 'order',
          tier: 'core',
          title: 'Building the rotation matrix',
          prompt: 'Put the steps that build $R_{\\mathrm{pol}}(\\varphi)$ in order.',
          steps: [
            'Turn $|H\\rangle$ to angle $\\varphi$: it becomes $\\cos\\varphi\\,|H\\rangle + \\sin\\varphi\\,|V\\rangle$.',
            'Turn $|V\\rangle$, which starts at $90^\\circ$, to $90^\\circ + \\varphi$.',
            'Use $\\cos(90^\\circ + \\varphi) = -\\sin\\varphi$ and $\\sin(90^\\circ + \\varphi) = \\cos\\varphi$.',
            'Place the two images as the columns of the matrix.',
          ],
          hints: [
            { text: 'A matrix is built from what it does to the basis states.' },
            { text: 'Do $H$ first, then $V$, then read off the coordinates.' },
            { text: 'The identities for $90^\\circ + \\varphi$ come right after the turn of $V$.' },
          ],
          walkthrough: [
            { text: 'Each basis state is turned by the same angle $\\varphi$, from its own starting angle.' },
            { text: 'The columns of the matrix are the coordinates of the two turned states.' },
          ],
        },
        {
          id: 'l8-tu-block',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Blocking a beam',
          prompt: 'A beam is polarized at $\\chi = 60^\\circ$. An analyzer set between $90^\\circ$ and $180^\\circ$ passes none of it through its aligned port. What is its angle, in degrees?',
          answer: V.l8BlockAngle,
          tolerance: 0.5,
          unit: 'degrees',
          hints: [
            { text: 'Nothing passes when the aligned chance is zero.' },
            { text: '$\\cos^2\\Delta\\chi = 0$ when $\\Delta\\chi = 90^\\circ$.' },
            { text: 'Add 90° to the beam’s angle.' },
          ],
          walkthrough: [
            { text: 'The aligned port is empty when $\\cos\\Delta\\chi = 0$, that is when the analyzer is 90° from the beam.' },
            { text: `So $\\chi_a = 60^\\circ + 90^\\circ = ${d(V.l8BlockAngle, 0)}^\\circ$.` },
          ],
        },
      ],
    },
    {
      id: 'l8-photon-spin',
      story: L8_STORY['l8-photon-spin'],
      review: L8_REVIEW['l8-photon-spin'],
      title: 'A photon turns the sphere twice as fast',
      question: 'Why does a 90° turn of light cross the whole Bloch sphere?',
      lecture: {
        pages: 'L8 p. 5 (§8.3, continued)',
        summary:
          'The generator of the turn is $\\sigma_y$, the matrix of $J_z/\\hbar$ in the H/V basis. Its eigenstates are the circular states, with helicity $\\pm 1$, so the photon has spin 1. With H and V at the poles, a lab turn $\\varphi$ moves the Bloch point by $2\\varphi$.',
        equations: ['G = \\sigma_y', 'R_{\\mathrm{pol}}(\\varphi) = e^{-i\\varphi\\sigma_y}', 'R_{\\mathrm{pol}}(\\varphi)|C_\\pm\\rangle = e^{\\mp i\\varphi}|C_\\pm\\rangle'],
      },
      books: [townsendRef('pp. 62–65, eqs. (2.116)–(2.120) and Example 2.8', 'Circular states gain the phases e^{∓iφ}, the photon has J_z = ±ħ, and a massless particle has no zero value. Optics books disagree on which circular state is right-handed; helicity ±1 is unambiguous.')],
      visual: {
        kind: 'polarization-dial',
        props: { chi: 0, analyzer: 0, carrier: 'photon' },
        caption: 'The lab on the left, the Bloch sphere’s x–z circle on the right.',
        tryThis: [
          'Press Turn 45°. The lab turn is 45° and the readout says the sphere turn is 90°.',
          'Switch to electron and press Turn 45°. The sphere turn is only 45°.',
          'Switch back to photon and press Turn 180°. The arrow head flips and the sphere turn reads 360°, yet with the analyzer at 0° the aligned port is 100% again.',
        ],
      },
      clues: [],
      insight: 'The turn of light is generated by $\\sigma_y = J_z/\\hbar$ in the H/V basis. Its eigenstates are the circular states, and the photon’s point turns twice as far as the light.',
      pitfalls: [
        'Reading the sphere’s $y$ axis as the lab’s $y$ axis. The sphere’s axes are averages in a chosen basis, not directions in the lab.',
        'Looking for a helicity-0 polarization. A free photon has none, so two dimensions are enough.',
      ],
      play: [
        {
          id: 'l8-ps-sphere',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Light turns the sphere twice as far',
          prompt: 'A polarization of light is turned by 45° in the lab. How far, in degrees, does its Bloch point move?',
          answer: V.l8Turn45,
          tolerance: 0.5,
          unit: 'degrees',
          hints: [
            { text: 'Compare the lab turn with the sphere turn.' },
            { text: 'For light, the sphere turn is twice the lab turn.' },
            { text: 'Double 45°.' },
          ],
          walkthrough: [
            { text: '$R_{\\mathrm{pol}}(\\varphi)$ turns the Bloch point by $2\\varphi$.' },
            { text: `So 45° in the lab is ${d(V.l8Turn45, 0)}° on the sphere: from $H$ to $D$.` },
          ],
        },
        {
          id: 'l8-ps-phase',
          kind: 'numeric',
          tier: 'core',
          title: 'The phase of a circular state',
          prompt: 'Light in the circular state $|C_+\\rangle$ is turned by $\\varphi = 40^\\circ$. By how many degrees does its phase change (the sign matters)?',
          answer: V.l8PhaseCp40,
          tolerance: 0.5,
          unit: 'degrees',
          hints: [
            { text: '$|C_+\\rangle$ is an eigenstate of the turn, so it only gets a phase.' },
            { text: 'The phase is $e^{-i\\varphi}$ for $|C_+\\rangle$ and $e^{+i\\varphi}$ for $|C_-\\rangle$.' },
            { text: 'The phase angle is minus the turn.' },
          ],
          walkthrough: [
            { text: 'The generator has eigenvalue $+1$ on $|C_+\\rangle$, so $R_{\\mathrm{pol}}(\\varphi)|C_+\\rangle = e^{-i\\varphi}|C_+\\rangle$.' },
            { text: `The phase is $-\\varphi = ${d(V.l8PhaseCp40, 0)}^\\circ$.` },
          ],
        },
        {
          id: 'l8-ps-electron',
          kind: 'choice',
          tier: 'stretch',
          title: 'Orthogonal in the lab',
          prompt: 'Which pair of physical turns takes each state to an orthogonal state?',
          options: [
            { text: 'A photon by 90°, an electron by 180°', correct: true, why: 'Right: both end 180° apart on the sphere.' },
            { text: 'A photon by 180°, an electron by 90°', correct: false, why: 'A 180° turn of light brings the same polarization back.' },
            { text: 'Both by 90°', correct: false, why: 'An electron turned 90° is only halfway across the sphere.' },
            { text: 'Both by 180°', correct: false, why: 'A photon turned 180° returns to itself.' },
          ],
          hints: [
            { text: 'Orthogonal states are 180° apart on the sphere.' },
            { text: 'Light turns the sphere twice as far as the lab; an electron once.' },
            { text: 'Halve 180° for light.' },
          ],
          walkthrough: [
            { text: 'Orthogonal states sit at opposite points, 180° apart on the sphere.' },
            { text: 'For light that takes a 90° turn ($H$ to $V$); for an electron it takes 180° ($|{+z}\\rangle$ to $|{-z}\\rangle$).' },
          ],
        },
      ],
    },
    {
      id: 'l8-key',
      story: L8_STORY['l8-key'],
      review: L8_REVIEW['l8-key'],
      title: 'Why share a secret key',
      question: 'What problem does a quantum key solve?',
      lecture: {
        pages: 'L8 p. 6 (§8.4)',
        summary:
          'A one-time pad hides each message bit $x$ as $c = x \\oplus k$ with a random key bit $k$. The problem is delivering the key unseen. BB84 uses polarized photons in two bases, so that Eve cannot read every state perfectly.',
        equations: ['c = x \\oplus k', 'x = c \\oplus k'],
      },
      books: [],
      visual: {
        kind: 'bb84-bench',
        props: { eve: 'off', seed: 84 },
        caption: 'Photons sent from Alice to Bob, one row each. No Eve yet.',
        tryThis: [
          'Press Send 10. In every row where Alice’s and Bob’s basis chips match, the two bits are equal.',
          'Look at a row where the chips differ: the bit Bob read has no link to Alice’s bit. Press Send 100 to see more of them.',
          'Switch Eve on, tick “compare bases” and press Send 100 again. The readout Q̂ is no longer 0.',
        ],
      },
      clues: [],
      insight: 'BB84 does not carry the message. It creates a shared random key, and two unbiased bases are what stop Eve from reading every photon perfectly.',
      pitfalls: [
        'Thinking the photons carry the message. They carry key material only.',
        'Forgetting that the public channel must be authenticated, or Eve could pose as Alice to Bob.',
      ],
      play: [
        {
          id: 'l8-ke-otp',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'One bit of a one-time pad',
          prompt: 'Alice’s message bit is $x = 0$ and the key bit is $k = 1$. What ciphertext bit $c = x \\oplus k$ does she send?',
          answer: V.l8OtpOne,
          tolerance: 0.001,
          hints: [
            { text: '$\\oplus$ adds bits and drops the carry.' },
            { text: 'Zero plus one is one.' },
            { text: 'Only $1 \\oplus 1$ gives 0.' },
          ],
          walkthrough: [
            { text: 'Add the bits: $0 + 1 = 1$, and there is no carry to drop.' },
            { text: `So $c = ${d(V.l8OtpOne, 0)}$. Bob adds $k$ again and gets $x = 0$ back.` },
          ],
        },
        {
          id: 'l8-ke-why',
          kind: 'choice',
          tier: 'core',
          title: 'Why two bases?',
          prompt: 'Why does BB84 use two bases instead of one?',
          options: [
            { text: 'So Eve cannot read all four states perfectly with one measurement', correct: true, why: 'Right: a measurement in either basis gives a coin toss for the other basis’ states.' },
            { text: 'To send bits faster', correct: false, why: 'A second basis does not send more bits per photon.' },
            { text: 'To use fewer photons', correct: false, why: 'It costs rounds, because half are discarded.' },
            { text: 'To hide the bases from Eve', correct: false, why: 'The bases are announced publicly after the transmission.' },
          ],
          hints: [
            { text: 'What would Eve do if only H and V were ever sent?' },
            { text: 'She could read every photon perfectly in H/V.' },
            { text: 'With two bases, one of her choices is always wrong half the time.' },
          ],
          walkthrough: [
            { text: 'With a single basis Eve would read every photon and resend an exact copy.' },
            { text: 'With two unbiased bases, no single measurement identifies all four states, so she must guess.' },
          ],
        },
      ],
    },
    {
      id: 'l8-bb84',
      story: L8_STORY['l8-bb84'],
      review: L8_REVIEW['l8-bb84'],
      title: 'BB84: prepare, measure, then compare bases',
      question: 'How do Alice and Bob end up with the same bits?',
      lecture: {
        pages: 'L8 pp. 7–8 (§§8.5–8.6) and L9 p. 3 (§9.1)',
        summary:
          'Alice prepares a random bit in a random basis; Bob measures in a random basis. They announce bases, not bits, keep the matching rounds, and test a sample. With no Eve, matched rounds always agree.',
        equations: ['P(B_A = B_B) = \\tfrac12', 'P(b \\ne a \\mid B_A = B_B) = 0'],
      },
      books: [],
      visual: {
        kind: 'bb84-bench',
        props: { eve: 'off', seed: 84 },
        caption: 'Send photons, compare bases, and test a sample of the kept bits.',
        tryThis: [
          'Press Send 100 and tick “compare bases”. About half of the rounds are kept (checked).',
          'Set the test sample m to 20. The readout reports 0 errors in the test, since there is no Eve; the remaining kept bits stay secret.',
          'Press New run and send 100 again. The kept count moves a little, but Alice and Bob still never disagree.',
        ],
      },
      clues: [],
      insight: 'Prepare, measure, announce bases, sift, test. Matched bases give matching bits in the ideal channel, so a disagreement is the only trace Eve can leave.',
      pitfalls: [
        'Keeping rounds whose bits happen to agree. Sift by the bases, never by the bits.',
        'Announcing the basis before Bob has measured. Eve would then measure in it and leave no trace.',
      ],
      play: [
        {
          id: 'l8-bb-sift',
          kind: 'choice',
          tier: 'core',
          title: 'Sift the notes’ board',
          prompt: 'On the notes’ board Alice’s bases are H/V, D/A, H/V, D/A, D/A, H/V, D/A, H/V and Bob’s are H/V, H/V, D/A, D/A, D/A, H/V, H/V, D/A. Which rounds survive sifting?',
          options: [
            { text: 'Rounds 1, 4, 5 and 6', correct: true, why: 'These are the rounds where Alice and Bob used the same basis.' },
            { text: 'Rounds 1, 2, 4, 5, 6 and 8', correct: false, why: 'These are the rounds where the bits agree, not the bases.' },
            { text: 'Rounds 2, 3, 7 and 8', correct: false, why: 'These are the rounds where the bases differ: the discarded ones.' },
            { text: 'Rounds 1 and 5 only', correct: false, why: 'Those are the public test sample, which leaves the key after sifting.' },
          ],
          hints: [
            { text: 'Sifting uses only the bases.' },
            { text: 'Keep a round when Alice’s and Bob’s bases are equal.' },
            { text: 'Compare the two lists round by round.' },
          ],
          walkthrough: [
            { text: 'Compare the bases round by round: they match in rounds 1, 4, 5 and 6.' },
            { text: 'Rounds 2 and 8 agree in their bits by luck. They are dropped too.' },
          ],
        },
        {
          id: 'l8-bb-kept',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'How many rounds survive',
          prompt: 'Alice and Bob choose their bases independently and equally likely. What fraction of the rounds survive sifting?',
          answer: V.l8PMatch,
          tolerance: 0.001,
          hints: [
            { text: 'A round survives when the two bases are equal.' },
            { text: 'Fix Alice’s basis. Bob matches it with one of his two choices.' },
            { text: 'That is one chance in two.' },
          ],
          walkthrough: [
            { text: 'Whatever Alice chose, Bob chooses the same basis half of the time.' },
            { text: `So ${d(V.l8PMatch, 1)} of the rounds survive.` },
          ],
        },
        {
          id: 'l8-bb-luck',
          kind: 'choice',
          tier: 'stretch',
          title: 'Rounds that agree by luck',
          prompt: 'Rounds 2 and 8 of the board have different bases but equal bits. Should Alice and Bob keep them?',
          options: [
            { text: 'No: their agreement is luck, and searching for such rounds would reveal bits', correct: true, why: 'Right: they would have to announce bits to find them, which Eve hears.' },
            { text: 'Yes: equal bits are safe to keep', correct: false, why: 'Bob’s result in a mismatched basis is a random outcome.' },
            { text: 'Yes, but only round 2', correct: false, why: 'Both are the same kind of coincidence.' },
            { text: 'No: bits that agree in a mismatched round are always errors', correct: false, why: 'Agreement there happens half of the time, with no error.' },
          ],
          hints: [
            { text: 'How would they find such rounds?' },
            { text: 'They would have to compare bits publicly.' },
            { text: 'Eve hears everything on the public channel.' },
          ],
          walkthrough: [
            { text: 'With mismatched bases Bob’s bit is a coin toss, so equal bits are coincidences.' },
            { text: 'Looking for them means announcing bits, and the key must not be announced.' },
          ],
        },
      ],
    },
    {
      id: 'l8-attack',
      story: L8_STORY['l8-attack'],
      review: L8_REVIEW['l8-attack'],
      title: 'An eavesdropper who measures and resends',
      question: 'What does a measuring eavesdropper leave behind?',
      lecture: {
        pages: 'L8 p. 9 (§8.7) = L9 pp. 3–5 (§9.2)',
        summary:
          'Eve measures every photon in a random basis and resends what she finds. In the wrong basis Bob errs half the time; in the right basis never. Averaged over her choice, the sifted key has error rate $Q = \\tfrac14$, and she knows half of the sifted bits.',
        equations: ['Q = \\tfrac12\\cdot 0 + \\tfrac12\\cdot\\tfrac12 = \\tfrac14'],
      },
      books: [],
      visual: {
        kind: 'bb84-bench',
        props: { eve: 'all', seed: 84 },
        caption: 'Eve intercepts and resends every photon.',
        tryThis: [
          `Press Send 1000 and tick “compare bases”. The readout shows Q̂ with its band next to the exact Q = ${d(V.l8Q, 2)}, and Q̂ lands close to ¼.`,
          'Read the line “Eve knows … of …”, which counts kept bits: about half of them.',
          'Press New run and send 1000 again. Q̂ changes a little each run and always stays near ¼.',
        ],
      },
      clues: [],
      insight: 'Eve guesses the basis right half the time. The other half she scrambles the photon, so a quarter of the sifted bits disagree, and she learns half of them.',
      pitfalls: [
        'Writing $Q = \\tfrac18$ because half of the rounds are dropped. Q already counts only kept rounds; the ⅛ is per photon sent.',
        'Taking ¼ as the error rate of every attack. It belongs to this one.',
      ],
      play: [
        {
          id: 'l8-at-exit',
          kind: 'numeric',
          tier: 'core',
          title: 'The notes’ exit check',
          prompt: 'Alice sends $|D\\rangle$, Bob measures in D/A, and Eve intercepts in H/V. The round is kept. What is the chance that Bob’s bit is wrong?',
          answer: V.l8Exit,
          tolerance: 0.001,
          hints: [
            { text: 'Eve resends $H$ or $V$, whichever she finds.' },
            { text: 'Each of those gives $D$ or $A$ with equal chance in Bob’s analyzer.' },
            { text: 'Bob is wrong when he reads $A$.' },
          ],
          walkthrough: [
            { text: 'Eve finds $H$ or $V$ at random and resends it.' },
            { text: `Either way Bob’s D/A analyzer gives $D$ or $A$ half and half, so he errs with chance ${d(V.l8Exit, 1)}. Averaged over her basis choice it would be ¼.` },
          ],
        },
        {
          id: 'l8-at-q',
          kind: 'numeric',
          tier: 'core',
          title: 'The error rate of the sifted key',
          prompt: 'Eve intercepts every photon in a random basis and resends it. What fraction of the sifted bits disagree?',
          answer: V.l8Q,
          tolerance: 0.001,
          hints: [
            { text: 'Split into Eve choosing the right basis and the wrong one.' },
            { text: 'Right basis: no error. Wrong basis: Bob errs half of the time.' },
            { text: 'Each case has chance ½.' },
          ],
          walkthrough: [
            { text: '$Q = \\tfrac12\\cdot 0 + \\tfrac12\\cdot\\tfrac12$.' },
            { text: `That is ${d(V.l8Q, 2)}.` },
          ],
        },
        {
          id: 'l8-at-photon',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Wrong bits per photon sent',
          prompt: 'Under the full attack, what fraction of all photons sent end up kept and wrong?',
          answer: V.l8PerPhoton,
          tolerance: 0.001,
          hints: [
            { text: 'First the fraction kept, then the fraction of those that are wrong.' },
            { text: 'Half are kept, and a quarter of the kept ones are wrong.' },
            { text: 'Multiply the two.' },
          ],
          walkthrough: [
            { text: 'A photon is kept with chance ½, and a kept bit is wrong with chance ¼.' },
            { text: `Multiply: ${d(V.l8PerPhoton, 3)}. Putting the ½ into Q itself is the trap.` },
          ],
        },
      ],
    },
    {
      id: 'l8-test',
      story: L8_STORY['l8-test'],
      review: L8_REVIEW['l8-test'],
      title: 'Catching the eavesdropper with a test sample',
      question: 'How many tested bits make the attack visible?',
      lecture: {
        pages: 'L8 pp. 10–11 (§§8.8–8.9) = L9 p. 6 (§9.3)',
        summary:
          'Reveal $m$ sifted bits and count the disagreements. Under the full attack all $m$ agree with chance $(\\tfrac34)^m$: 0.32% for $m = 20$. Three classical steps remain: estimate the error rate, reconcile the strings, and hash them into a shorter key.',
        equations: ['P(\\text{no error in } m) = \\left(\\tfrac34\\right)^m'],
      },
      books: [],
      visual: {
        kind: 'bb84-bench',
        props: { eve: 'all', seed: 84, testSize: 17 },
        caption: 'The test sample is already 17 sifted bits. Send photons to fill it.',
        tryThis: [
          'Press Send 100. The line “no-error chance” reads 0.0075 for the 17 tested bits.',
          'Set the test sample m to 16: the chance is 0.0100, just above 1%. Set it back to 17: 0.0075, just below.',
          'Set m to 20: the chance is 0.0032. Each extra tested bit multiplies the chance by ¾.',
        ],
      },
      clues: [],
      insight: 'A test of $m$ bits misses this attack with chance $(\\tfrac34)^m$: 17 bits catch it with 99% certainty. After the test come estimation, reconciliation and privacy amplification.',
      pitfalls: [
        'Treating ¼ as an abort threshold. It is the error rate of this one attack, not a level of acceptable error.',
        'Reading “no errors” as proof of no Eve. A short test can miss her, and noise can fake her.',
      ],
      play: [
        {
          id: 'l8-te-20',
          kind: 'numeric',
          tier: 'core',
          title: 'Twenty tested bits',
          prompt: 'Under the full attack, what is the chance that a test of $m = 20$ sifted bits shows no error?',
          answer: V.l8Miss20,
          tolerance: 0.0001,
          hints: [
            { text: 'Each tested bit agrees with chance ¾.' },
            { text: 'The bits are independent, so the chances multiply.' },
            { text: 'Raise ¾ to the 20th power.' },
          ],
          walkthrough: [
            { text: 'All 20 bits must agree, and each does with chance $\\tfrac34$.' },
            { text: `$(\\tfrac34)^{20} = ${d(V.l8Miss20, 4)}$.` },
          ],
        },
        {
          id: 'l8-te-99',
          kind: 'numeric',
          tier: 'stretch',
          title: 'How many tested bits catch her',
          prompt: 'What is the smallest test size $m$ for which the full attack shows at least one error with at least 99% certainty?',
          answer: V.l8M99,
          tolerance: 0.001,
          hints: [
            { text: 'You need $(\\tfrac34)^m \\le 0.01$.' },
            { text: 'Try $m = 16$: the chance is still just above 1%.' },
            { text: 'Try the next whole number.' },
          ],
          walkthrough: [
            { text: `For $m = 16$ the chance is ${d(V.l8Miss16, 4)}, just above $0.01$.` },
            { text: `For $m = ${d(V.l8M99, 0)}$ it is ${d(V.l8Miss17, 4)}, below $0.01$. So ${d(V.l8M99, 0)} bits are the fewest.` },
          ],
        },
        {
          id: 'l8-te-not-threshold',
          kind: 'choice',
          tier: 'core',
          title: 'What does ¼ mean?',
          prompt: 'What does the error rate $Q = \\tfrac14$ tell us?',
          options: [
            { text: 'The average error rate of this one attack: full intercept–resend in random bases', correct: true, why: 'Right: it is a result of one calculation.' },
            { text: 'The error level at which Alice and Bob must abort', correct: false, why: 'An abort rule needs a security analysis of real devices.' },
            { text: 'The error rate of every eavesdropping attack', correct: false, why: 'Other attacks disturb the photons differently.' },
            { text: 'The noise level of the detectors', correct: false, why: 'The model has no noise: all errors here come from Eve.' },
          ],
          hints: [
            { text: 'Where did the ¼ come from?' },
            { text: 'From averaging over Eve’s random basis choices in one specific attack.' },
            { text: 'It describes that attack and nothing else.' },
          ],
          walkthrough: [
            { text: 'We computed $Q$ for an ideal channel and one attack: measure every photon in a random basis and resend.' },
            { text: 'The result is not a universal threshold.' },
          ],
        },
      ],
    },
  ],
}

function townsendRef(where: string, adds: string) {
  return { source: 'townsend' as const, where, adds }
}
