import type { Lecture } from './schema'
import { V, d, tf } from './L9.values'
import { L9_STORY } from './L9.story'
import { L9_REVIEW } from './L9.review'
import './bridges448'

// Every number a learner sees in this lecture is computed in L9.values.ts, then asserted in keyed claims
// (content.test.tsx runs `holds`; claims.test.ts compares each key with numpy). Plan: docs/roles/proposals/P-L9-story.md, with the
// judge's rulings (docs/roles/decisions/448-L8L11.md, L9): built from notes pp. 7-14 (§§9.4-9.9); the first 23 minutes of Class 9
// (BB84, pp. 3-6) are Lecture 8's, so this chapter opens with the class marker "Class 9 · from minute 23" (R2). No pair-grid stage
// kind (R1): every picture is the `matrix` kind's pair view and the Try-it widget W4 `pair-grid` draws the same scene. The
// determinant test is Go-deeper only (R4). The chapter stops at "the pair has a state, the spins do not" (R6). No homework exists
// for L9. The dealer of the notes' penny and dime is "the dealer" (R8). The 448 -> 709 chips live in content/bridges448.ts.

export const L9: Lecture = {
  id: 'L9',
  number: 9,
  title: 'Composite quantum systems',
  outcomes: [
    'Build the composite space for two systems and count its dimension.',
    'Tell a classical correlation from independence, and say what independence does to an average.',
    'Write and use the four-state basis of two spins, with Alice’s letter first.',
    'Expand a product state, and say why its normalization is automatic.',
    'Count the real parameters of two separate spins and of a general pair, and say what six against four means.',
    'Show that the singlet does not factor, and factor a state that does.',
  ],
  prerequisites: ['vector-space', 'inner-product', 'probability', 'expectation', 'bloch-sphere', 'born-rule'],
  // Symbols defined in the text itself (symbol → the unit, beat or site whose sentence defines it). Kets, bras, the average and the
  // axis kets of earlier lectures are mapped to the first unit: a recap.
  symbols: {
    '|\\cdot\\rangle': 'l9-tensor',
    '\\langle\\cdot\\rangle': 'l9-classical',
    '|H\\rangle': 'l9-tensor:b3',
    '|V\\rangle': 'l9-tensor:b3',
    '|1\\rangle': 'l9-tensor:b3',
    '|6\\rangle': 'l9-tensor:b3',
    '|4\\rangle': 'l9-tensor:b3',
    '|H4\\rangle': 'l9-tensor:b3',
    A: 'l9-tensor:b3',
    B: 'l9-tensor:b3',
    H: 'l9-tensor:b3',
    '\\dim': 'l9-tensor:b4',
    N_A: 'l9-tensor:b4',
    N_B: 'l9-tensor:b4',
    '|V3\\rangle': 'l9-tensor.visual.tryThis[1]',
    V: 'l9-tensor.visual.tryThis[1]',
    '\\sigma_A': 'l9-classical:b1',
    '\\sigma_B': 'l9-classical:b1',
    P: 'l9-classical:b1',
    a: 'l9-classical:b3',
    b: 'l9-classical:b3',
    '|u\\rangle': 'l9-two-spins:b1',
    '|d\\rangle': 'l9-two-spins:b1',
    '|+z\\rangle': 'l9-two-spins:b1',
    '|-z\\rangle': 'l9-two-spins:b1',
    '|uu\\rangle': 'l9-two-spins:b2',
    '|ud\\rangle': 'l9-two-spins:b2',
    '|du\\rangle': 'l9-two-spins:b2',
    '|dd\\rangle': 'l9-two-spins:b2',
    u: 'l9-two-spins:b2',
    d: 'l9-two-spins:b2',
    '\\langle\\cdot|\\cdot\\rangle': 'l9-two-spins:b3',
    '|ab\\rangle': 'l9-two-spins:b3',
    "|a'b'\\rangle": 'l9-two-spins:b3',
    "\\delta_aa'": 'l9-two-spins:b3',
    "\\delta_bb'": 'l9-two-spins:b3',
    '|\\Psi\\rangle': 'l9-two-spins:b4',
    '\\psi_uu': 'l9-two-spins:b4',
    '\\psi_ud': 'l9-two-spins:b4',
    '\\psi_du': 'l9-two-spins:b4',
    '\\psi_dd': 'l9-two-spins:b4',
    '\\psi_ab': 'l9-two-spins:b4',
    '\\theta': 'l9-product:b1',
    '|\\psi_A\\rangle': 'l9-product:b1',
    '|\\psi_B\\rangle': 'l9-product:b1',
    '\\alpha_u': 'l9-product:b1',
    '\\alpha_d': 'l9-product:b1',
    '\\beta_u': 'l9-product:b1',
    '\\beta_d': 'l9-product:b1',
    '|\\phi\\rangle': 'l9-product:b1',
    '\\alpha_a': 'l9-product:b2.derivation',
    '\\beta_b': 'l9-product:b2.derivation',
    t: 'l9-counting:b5',
    '|+x\\rangle': 'l9-singlet:b6',
  },
  units: [
    {
      id: 'l9-tensor',
      story: L9_STORY['l9-tensor'],
      review: L9_REVIEW['l9-tensor'],
      title: 'Two systems need one new space',
      question: 'What state space describes two systems at once?',
      lecture: {
        pages: 'L9 p. 7 (§9.4)',
        summary:
          'Two systems with state spaces $\\mathcal H_A$ and $\\mathcal H_B$ live in a new space, $\\mathcal H_{AB} = \\mathcal H_A \\otimes \\mathcal H_B$, whose basis has a state for each pair of labels. So dimensions multiply. The class starts here at minute 23: its first 23 minutes finished the key-distribution protocol of Lecture 8.',
        equations: ['\\dim(\\mathcal H_A \\otimes \\mathcal H_B) = N_A N_B'],
      },
      books: [{ source: 'susskind', where: '§6.1, Fig. 6.1', adds: 'The same table with a coin for Alice and a die for Bob: twelve basis vectors, one per box.' }],
      visual: {
        kind: 'pair-grid',
        props: { frame: 'coin-die' },
        caption: 'Alice’s photon labels run down the side and Bob’s die labels across the top; each box is one basis state of the pair.',
        tryThis: [
          'Count the boxes. The readout says $2 \\times 6 = 12$ basis states.',
          'Find $|V3\\rangle$: it sits in row $V$, column 3.',
          'Switch the table to two spins. The pair now has 4 boxes, because $2 \\times 2 = 4$.',
        ],
      },
      clues: [],
      insight: 'The pair needs a new space, not two spaces side by side: one basis state for every pair of labels, so the dimensions multiply.',
      pitfalls: [
        'Adding the dimensions. A two-state system with a six-state one has 12 basis states, not 8.',
        'Reading $|H4\\rangle$ as two states. It is one state of the pair; its label records what each part shows.',
      ],
      play: [
        {
          id: 'l9-te-dim',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Photon and die',
          prompt: 'Alice holds a photon polarization with basis kets $|H\\rangle$ and $|V\\rangle$, and Bob a quantum die with six faces. How many basis states does the pair have?',
          answer: V.l9DimCoinDie,
          tolerance: 0.001,
          unit: 'basis states',
          hints: [
            { text: 'The pair has one basis state for each pair of labels.' },
            { text: 'Think of a table: the photon gives the rows and the die gives the columns.' },
            { text: 'Count rows times columns: 2 times 6.' },
          ],
          walkthrough: [
            { text: 'One basis state per pair of labels fills a table with two rows ($H$, $V$) and six columns (1 to 6).' },
            { text: `Rows times columns: $2 \\times 6 = ${d(V.l9DimCoinDie, 0)}$ basis states.` },
          ],
        },
        {
          id: 'l9-te-dim3',
          kind: 'numeric',
          tier: 'core',
          title: 'A three-state system with the die',
          prompt: 'Alice’s system has three basis states and Bob’s is the six-faced die. What is the dimension of the pair’s space?',
          answer: V.l9DimThreeDie,
          tolerance: 0.001,
          unit: 'dimensions',
          hints: [
            { text: 'Dimensions multiply, they do not add.' },
            { text: 'The table has 3 rows and 6 columns.' },
            { text: 'Multiply: 3 times 6.' },
          ],
          walkthrough: [
            { text: '$\\dim(\\mathcal H_A \\otimes \\mathcal H_B) = N_A N_B$.' },
            { text: `Here $3 \\times 6 = ${d(V.l9DimThreeDie, 0)}$. Adding would give 9, which is the trap.` },
          ],
        },
        {
          id: 'l9-te-one',
          kind: 'choice',
          tier: 'core',
          title: 'What is $|H4\\rangle$?',
          prompt: 'The label $|H4\\rangle$ has two parts, $H$ and 4. What is it?',
          options: [
            { text: 'One basis state of the pair, whose label records what each system shows', correct: true, why: 'Right: it is the box in row $H$, column 4, one vector of the pair’s space.' },
            { text: 'Two states side by side, one of Alice and one of Bob', correct: false, why: 'The label has two parts, but the state is a single vector of the composite space.' },
            { text: 'A product of two numbers', correct: false, why: 'Nothing is multiplied into a number. The tensor product builds a new space.' },
            { text: 'A [[superposition]] of $|H\\rangle$ and $|4\\rangle$', correct: false, why: 'Those two kets live in different spaces and cannot be added.' },
          ],
          hints: [
            { text: 'Look at which space the label belongs to.' },
            { text: 'It is a basis state of $\\mathcal H_A \\otimes \\mathcal H_B$.' },
            { text: 'A basis state is one box of the table.' },
          ],
          walkthrough: [
            { text: 'The pair has one basis state for each pair of labels, drawn as one box.' },
            { text: '$|H4\\rangle = |H\\rangle_A \\otimes |4\\rangle_B$ is the box in row $H$ and column 4: a single state of the pair.' },
          ],
        },
      ],
    },
    {
      id: 'l9-classical',
      story: L9_STORY['l9-classical'],
      review: L9_REVIEW['l9-classical'],
      title: 'Correlation without anything quantum',
      question: 'Can two coins be correlated with nothing quantum going on?',
      lecture: {
        pages: 'L9 p. 8 (§9.5)',
        summary:
          'A dealer hands a penny ($+1$) and a dime ($-1$) to two people at random. Each average is $0$, but the coins always differ, so $\\langle\\sigma_A\\sigma_B\\rangle = -1$ and the correlation $\\langle\\sigma_A\\sigma_B\\rangle - \\langle\\sigma_A\\rangle\\langle\\sigma_B\\rangle$ is not zero. Independence means $P(a,b) = P_A(a)P_B(b)$, which makes $\\langle ab\\rangle = \\langle a\\rangle\\langle b\\rangle$.',
        equations: ['P(a,b) = P_A(a)P_B(b) \\;\\Rightarrow\\; \\langle ab\\rangle = \\langle a\\rangle\\langle b\\rangle'],
      },
      books: [{ source: 'susskind', where: '§6.2', adds: 'The penny and the dime sent to two distant people: perfect correlation, and why it is not mysterious.' }],
      visual: {
        kind: 'pair-grid',
        props: { mode: 'classical', coins: 'dealer' },
        caption: 'A table of chances for two coins scored $\\pm 1$: row $a$, column $b$.',
        tryThis: [
          'Read the three averages: $\\langle a\\rangle = 0$, $\\langle b\\rangle = 0$ and $\\langle ab\\rangle = -1$.',
          `Choose two separate dealers and set $P(+1)$ to ${d(V.l9BiasedPA, 1)} for coin A and ${d(V.l9BiasedPB, 1)} for coin B. Then $\\langle ab\\rangle = -${d(V.l9BiasedABSize, 2)}$, which equals $\\langle a\\rangle\\langle b\\rangle$.`,
          'Try to make two separate dealers correlated. No setting does it: the correlation stays 0.',
        ],
      },
      clues: [],
      insight: 'Correlation needs no quantum mechanics: a dealer can make it. What independence guarantees is that the joint chances factor, and then the correlation is zero.',
      pitfalls: [
        'Concluding “correlated, so quantum”. The dealer’s coins are perfectly anticorrelated and fully classical.',
        'Forgetting that independence is a statement about the whole table of chances, not about the averages alone.',
      ],
      play: [
        {
          id: 'l9-cl-ab',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'The dealer’s coins',
          prompt: 'A dealer gives a penny ($+1$) and a dime ($-1$) to Alice and Bob at random. What is $\\langle\\sigma_A\\sigma_B\\rangle$?',
          answer: V.l9CoinAB,
          tolerance: 0.001,
          hints: [
            { text: 'Look at what the two scores are on any single deal.' },
            { text: 'They always differ: one is $+1$ and the other $-1$.' },
            { text: 'So the product $\\sigma_A\\sigma_B$ is the same on every deal.' },
          ],
          walkthrough: [
            { text: 'On every deal one person has $+1$ and the other $-1$.' },
            { text: `So $\\sigma_A\\sigma_B = -1$ every time, and its average is ${d(V.l9CoinAB, 0)}.` },
          ],
        },
        {
          id: 'l9-cl-indep',
          kind: 'numeric',
          tier: 'core',
          title: 'Two separate dealers',
          prompt: 'Two dealers who never meet each give a fair coin to Alice and to Bob. What is the correlation $\\langle ab\\rangle - \\langle a\\rangle\\langle b\\rangle$?',
          answer: V.l9IndepAB,
          tolerance: 0.001,
          hints: [
            { text: 'Are the two coins independent?' },
            { text: 'Independent coins have a table that factors, $P(a,b) = P_A(a)P_B(b)$.' },
            { text: 'Then $\\langle ab\\rangle = \\langle a\\rangle\\langle b\\rangle$.' },
          ],
          walkthrough: [
            { text: 'Nothing links the two coins, so every pair of values has chance $\\tfrac14$ and the table factors.' },
            { text: `Then $\\langle ab\\rangle = \\langle a\\rangle\\langle b\\rangle$, and the correlation is ${d(V.l9IndepAB, 0)}.` },
          ],
        },
        {
          id: 'l9-cl-biased',
          kind: 'numeric',
          tier: 'stretch',
          title: 'Biased independent coins',
          prompt: 'Independent coins with $P_A(+1) = 0.7$ and $P_B(+1) = 0.4$. Find $\\langle ab\\rangle$.',
          answer: V.l9BiasedAB,
          tolerance: 0.001,
          hints: [
            { text: 'Independence gives $\\langle ab\\rangle = \\langle a\\rangle\\langle b\\rangle$.' },
            { text: 'Each average is $P(+1) - P(-1) = 2P(+1) - 1$.' },
            { text: `So $\\langle a\\rangle = ${d(V.l9BiasedA, 1)}$ and $\\langle b\\rangle = -${d(V.l9BiasedBSize, 1)}$.` },
          ],
          walkthrough: [
            { text: `$\\langle a\\rangle = 2(${d(V.l9BiasedPA, 1)}) - 1 = ${d(V.l9BiasedA, 1)}$ and $\\langle b\\rangle = 2(${d(V.l9BiasedPB, 1)}) - 1 = -${d(V.l9BiasedBSize, 1)}$.` },
            { text: `Multiply: $\\langle ab\\rangle = ${d(V.l9BiasedA, 1)} \\cdot (-${d(V.l9BiasedBSize, 1)}) = -${d(V.l9BiasedABSize, 2)}$.` },
          ],
        },
      ],
    },
    {
      id: 'l9-two-spins',
      story: L9_STORY['l9-two-spins'],
      review: L9_REVIEW['l9-two-spins'],
      title: 'Two spins: four basis states',
      question: 'What basis describes two spin-½ particles together?',
      lecture: {
        pages: 'L9 p. 9 (§9.6)',
        summary:
          'With $|u\\rangle = |{+z}\\rangle$ and $|d\\rangle = |{-z}\\rangle$, two spins have the four-state basis $|uu\\rangle, |ud\\rangle, |du\\rangle, |dd\\rangle$, the first letter Alice’s. The four are orthonormal, $\\langle ab|a\'b\'\\rangle = \\delta_{aa\'}\\delta_{bb\'}$, so any combination is a state of the pair.',
        equations: ['|\\Psi\\rangle = \\psi_{uu}|uu\\rangle + \\psi_{ud}|ud\\rangle + \\psi_{du}|du\\rangle + \\psi_{dd}|dd\\rangle'],
      },
      books: [{ source: 'susskind', where: '§§6.3–6.4', adds: 'The same four product kets for two spins, with Bob’s spin given its own letter.' }],
      visual: {
        kind: 'pair-grid',
        props: { frame: 'spin', alice: [0, 0], bob: [180, 0] },
        caption: 'Alice’s spin sets the row and Bob’s sets the column; the lit box is the pair’s state.',
        tryThis: [
          'One box lights: $|ud\\rangle$, because Alice points up and Bob down.',
          'Flip both spins (Alice θ = 180°, Bob θ = 0°). The light moves to $|du\\rangle$.',
          'Which box is “Alice down, Bob up”? Row $d$, column $u$.',
        ],
      },
      clues: [],
      insight: 'Two spins are not two kets side by side: they are one four-dimensional state, with the first letter always Alice’s and the second Bob’s.',
      pitfalls: [
        'Treating $|ud\\rangle$ and $|du\\rangle$ as the same state because they hold the same letters. The order tells who points where.',
        'Writing a pair as two separate kets. A general pair state mixes all four basis states.',
      ],
      play: [
        {
          id: 'l9-ts-overlap',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'Two different boxes',
          prompt: 'What is $\\langle ud|du\\rangle$?',
          answer: V.l9UdDu,
          tolerance: 0.001,
          hints: [
            { text: 'The four basis states are orthonormal.' },
            { text: 'The rule is $\\langle ab|a\'b\'\\rangle = \\delta_{aa\'}\\delta_{bb\'}$: both letters must match.' },
            { text: 'Compare the first letters, then the second.' },
          ],
          walkthrough: [
            { text: 'The first letters are $u$ and $d$. They differ, so the first factor of the overlap is 0.' },
            { text: `The whole overlap is ${d(V.l9UdDu, 0)}. The two states are different basis states.` },
          ],
        },
        {
          id: 'l9-ts-count',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'How many basis states?',
          prompt: 'How many basis states do two spin-½ particles have together?',
          answer: V.l9DimSpins,
          tolerance: 0.001,
          unit: 'basis states',
          hints: [
            { text: 'Each spin has two basis states.' },
            { text: 'Dimensions multiply.' },
            { text: 'Count the four boxes of the table.' },
          ],
          walkthrough: [
            { text: 'Each spin has the basis $u$, $d$.' },
            { text: `The pair has one basis state per pair of letters: $2 \\times 2 = ${d(V.l9DimSpins, 0)}$.` },
          ],
        },
        {
          id: 'l9-ts-label',
          kind: 'choice',
          tier: 'core',
          title: 'Alice down, Bob up',
          prompt: 'Alice’s spin points down and Bob’s points up. Which basis state is that?',
          options: [
            { text: '$|du\\rangle$', correct: true, why: 'Right: Alice’s letter comes first, so down for Alice and up for Bob is $|du\\rangle$.' },
            { text: '$|ud\\rangle$', correct: false, why: 'That is Alice up and Bob down, the other way round.' },
            { text: '$|dd\\rangle$', correct: false, why: 'Both would be down.' },
            { text: '$|uu\\rangle$', correct: false, why: 'Both would be up.' },
          ],
          hints: [
            { text: 'The first letter always belongs to Alice.' },
            { text: 'Write Alice’s letter, then Bob’s.' },
            { text: 'Alice: $d$. Bob: $u$.' },
          ],
          walkthrough: [
            { text: 'First letter for Alice ($d$), second for Bob ($u$).' },
            { text: 'So the state is $|du\\rangle = |d\\rangle_A \\otimes |u\\rangle_B$.' },
          ],
        },
      ],
    },
    {
      id: 'l9-product',
      story: L9_STORY['l9-product'],
      review: L9_REVIEW['l9-product'],
      title: 'Independent preparations give product states',
      question: 'What state does a pair have when each part is prepared alone?',
      lecture: {
        pages: 'L9 p. 10 (§9.7)',
        summary:
          'If Alice prepares $|\\psi_A\\rangle = \\alpha_u|u\\rangle + \\alpha_d|d\\rangle$ and Bob separately $|\\psi_B\\rangle = \\beta_u|u\\rangle + \\beta_d|d\\rangle$, the pair is in the product state with amplitudes $\\psi_{ab} = \\alpha_a\\beta_b$. Its normalization is automatic, and Bob’s predictions are those of $|\\psi_B\\rangle$. The notes write $|\\phi\\rangle_B$ for Bob’s state; here it is $|\\psi_B\\rangle$.',
        equations: ['\\psi_{ab} = \\alpha_a\\beta_b,\\qquad \\langle\\Psi|\\Psi\\rangle = (|\\alpha_u|^2 + |\\alpha_d|^2)(|\\beta_u|^2 + |\\beta_d|^2) = 1'],
      },
      books: [{ source: 'susskind', where: '§6.5', adds: 'The product state expanded term by term, and why a product state describes independent preparations.' }],
      visual: {
        kind: 'pair-grid',
        props: { frame: 'spin', alice: [60, 0], bob: [90, 0] },
        caption: 'Two separate preparations: Alice’s column of amplitudes times Bob’s row fills the four boxes.',
        tryThis: [
          `Read the four boxes: ${d(V.l9ProdUU)}, ${d(V.l9ProdUD)}, ${d(V.l9ProdDU)}, ${d(V.l9ProdDD)}.`,
          `Drag Alice’s θ. Every box changes, but Bob’s readout stays at u ${d(V.l9BobPu, 1)}, d ${d(1 - V.l9BobPu, 1)}. Set “Boxes show” to chances to see it as column totals.`,
          'The chances always add to 1, with no extra condition.',
        ],
      },
      clues: [],
      insight: 'A product state’s four amplitudes come from only two small states, so its normalization is automatic and Bob’s predictions ignore what Alice did.',
      pitfalls: [
        'Mixing up two meanings of “product”. The tensor-product space holds every pair state; a product state is one special vector in it.',
        'Expecting Alice’s preparation to change Bob’s predictions. In a product state it does not.',
      ],
      play: [
        {
          id: 'l9-pr-amp',
          kind: 'numeric',
          tier: 'core',
          title: 'One box of a product',
          prompt: 'Alice’s spin is tilted $60^\\circ$ from $+z$ toward $+x$, and Bob’s points along $+x$. What is the amplitude $\\psi_{du}$?',
          answer: V.l9ProdDU,
          tolerance: 0.001,
          hints: [
            { text: 'For a product state each box is Alice’s amplitude times Bob’s.' },
            { text: 'The box $du$ uses $\\alpha_d$ and $\\beta_u$.' },
            { text: `Alice gives $\\alpha_d = ${d(V.l9AlphaD, 1)}$ and Bob gives $\\beta_u = ${d(V.l9BetaU)}$.` },
          ],
          walkthrough: [
            { text: `$\\psi_{du} = \\alpha_d\\beta_u = ${d(V.l9AlphaD, 1)} \\times ${d(V.l9BetaU)}$.` },
            { text: `That is about ${d(V.l9ProdDU)}.` },
          ],
        },
        {
          id: 'l9-pr-norm',
          kind: 'numeric',
          tier: 'core',
          title: 'The chances of a product',
          prompt: 'Two normalized spins are prepared separately. What do the four chances of the pair add up to?',
          answer: V.l9ProdNorm,
          tolerance: 0.001,
          hints: [
            { text: 'The four chances are $|\\alpha_a\\beta_b|^2$.' },
            { text: 'They add to a product of two brackets, one for each spin.' },
            { text: 'Each bracket is the normalization of one spin.' },
          ],
          walkthrough: [
            { text: 'The sum is $(|\\alpha_u|^2 + |\\alpha_d|^2)(|\\beta_u|^2 + |\\beta_d|^2)$.' },
            { text: `Each bracket is 1, so the total is ${d(V.l9ProdNorm, 0)}: no new normalization is needed.` },
          ],
        },
        {
          id: 'l9-pr-words',
          kind: 'choice',
          tier: 'core',
          title: 'Two uses of “product”',
          prompt: 'How do the tensor-product space $\\mathcal H_A \\otimes \\mathcal H_B$ and a product state differ?',
          options: [
            { text: 'The space contains all pair states; a product state is a single, special vector inside it', correct: true, why: 'Right: most vectors of the tensor-product space are not product states.' },
            { text: 'They are the same thing', correct: false, why: 'The space has many vectors that are not products of an Alice state and a Bob state.' },
            { text: 'The space is a number and a product state is a vector', correct: false, why: 'The space is a collection of vectors; neither one is a number.' },
            { text: 'A product state is the space and the space is one vector', correct: false, why: 'This reverses the roles.' },
          ],
          hints: [
            { text: 'One is a place where vectors live; the other is a vector.' },
            { text: 'Ask whether every vector of the space can be written as Alice’s state times Bob’s.' },
            { text: 'Not every one can: that is the next unit.' },
          ],
          walkthrough: [
            { text: '$\\mathcal H_A \\otimes \\mathcal H_B$ is the state space of the pair.' },
            { text: 'A product state $|\\psi_A\\rangle \\otimes |\\psi_B\\rangle$ is one special vector inside it, made by independent preparations.' },
          ],
        },
      ],
    },
    {
      id: 'l9-counting',
      story: L9_STORY['l9-counting'],
      review: L9_REVIEW['l9-counting'],
      title: 'Counting parameters: six is more than four',
      question: 'Does every pair state come from two separate preparations?',
      lecture: {
        pages: 'L9 p. 11 (§9.8)',
        summary:
          'The rules allow every normalized vector of the four-dimensional space. One spin has $4 - 1 - 1 = 2$ real parameters, so two separate spins have $2 + 2 = 4$. A general pair has four complex amplitudes, eight reals, minus normalization and the overall phase: $8 - 1 - 1 = 6$. Six is more than four, so some pair states are not products. They are entangled.',
        equations: ['8 - 1 - 1 = 6 > 2 + 2'],
      },
      books: [{ source: 'susskind', where: '§§6.6–6.7', adds: 'The same count for the product state and the general state, and the remark that entanglement comes in degrees.' }],
      visual: {
        kind: 'pair-grid',
        props: { frame: 'spin', preset: 'family', t: 0 },
        caption: 'The path $\\cos t\\,|ud\\rangle - \\sin t\\,|du\\rangle$ starts at a product and opens into a state that no two separate spins can make.',
        tryThis: [
          'At $t = 0$ one box is lit: $|ud\\rangle$, a product.',
          `Slide to $t = 45^\\circ$: the singlet, with two boxes of size ${d(V.l9SingUd)}.`,
          'Switch to “two separate spins” and try to match the singlet with the sliders. No setting does it.',
        ],
      },
      clues: [],
      insight: 'Two separate spins can reach only 4 of the 6 parameters a pair has, so most pair states are not products.',
      pitfalls: [
        'Reading “four amplitudes either way” as “the same states”. A product’s four are tied together; the general four are free.',
        'Forgetting the overall phase when counting. Without it a pair would seem to have 7 parameters, not 6.',
      ],
      play: [
        {
          id: 'l9-co-one',
          kind: 'numeric',
          tier: 'warm-up',
          title: 'One spin',
          prompt: 'How many real parameters does the state of one spin have?',
          answer: V.l9ParamsOne,
          tolerance: 0.001,
          unit: 'real numbers',
          hints: [
            { text: 'Start from two complex amplitudes.' },
            { text: 'Two complex numbers are four real numbers.' },
            { text: 'Normalization removes one and the overall phase removes another.' },
          ],
          walkthrough: [
            { text: 'Two complex amplitudes: 4 real numbers.' },
            { text: `Minus normalization and the overall phase: $4 - 1 - 1 = ${d(V.l9ParamsOne, 0)}$, the two Bloch angles.` },
          ],
        },
        {
          id: 'l9-co-gen',
          kind: 'numeric',
          tier: 'core',
          title: 'A general pair',
          prompt: 'How many real parameters does a general state of two spins have?',
          answer: V.l9ParamsGeneral,
          tolerance: 0.001,
          unit: 'real numbers',
          hints: [
            { text: 'A pair state has four complex amplitudes.' },
            { text: 'That is 8 real numbers.' },
            { text: 'Remove one for normalization and one for the overall phase.' },
          ],
          walkthrough: [
            { text: 'Four complex amplitudes: 8 reals.' },
            { text: `Minus one normalization and one phase: $8 - 1 - 1 = ${d(V.l9ParamsGeneral, 0)}$. Two separate spins reach only ${d(V.l9ParamsProduct, 0)}.` },
          ],
        },
        {
          id: 'l9-co-why',
          kind: 'order',
          tier: 'stretch',
          title: 'Why some pairs are entangled',
          prompt: 'Put the counting argument in order.',
          steps: [
            'Four complex amplitudes are eight real numbers',
            'Normalization removes one',
            'The overall phase removes one',
            'Six remain, more than the four of two separate spins',
          ],
          hints: [
            { text: 'Start from the raw count of numbers.' },
            { text: 'Then take away what has no physical effect.' },
            { text: 'End with the comparison.' },
          ],
          walkthrough: [
            { text: 'A pair has four complex amplitudes: eight reals. Normalization and the overall phase remove two.' },
            { text: 'Six remain, but two separate spins reach only four, so some pair states are not products.' },
          ],
        },
      ],
    },
    {
      id: 'l9-singlet',
      story: L9_STORY['l9-singlet'],
      review: L9_REVIEW['l9-singlet'],
      title: 'The singlet: a pair with no separate states',
      question: 'Which state of two spins cannot be split into two?',
      lecture: {
        pages: 'L9 pp. 11–13 (§§9.8–9.9)',
        summary:
          'The singlet $(|ud\\rangle - |du\\rangle)/\\sqrt2$ is a normalized pair state that is not a product. Assume it factors: then $\\alpha_u\\beta_d \\ne 0$, so $\\alpha_u \\ne 0$, and $\\beta_u = 0$ follows from $\\alpha_u\\beta_u = 0$. But then $\\alpha_d\\beta_u$ would be 0, not $-1/\\sqrt2$. The pair has a state while neither spin has a state vector of its own. The notes’ proof calls the four numbers a, b, c, d; here they are $\\alpha_u, \\alpha_d, \\beta_u, \\beta_d$.',
        equations: ['|\\mathrm{sing}\\rangle = \\tfrac{1}{\\sqrt2}(|ud\\rangle - |du\\rangle)'],
      },
      books: [{ source: 'susskind', where: '§6.7, Exercise 6.3', adds: 'The singlet named as maximally entangled, and the no-factor proof set as an exercise.' }],
      visual: {
        kind: 'pair-grid',
        props: { frame: 'spin', preset: 'family', t: 45 },
        caption: 'The singlet is the path’s 45° point: two boxes, no column times row.',
        tryThis: [
          'Read the boxes: $\\psi_{ud} = 1/\\sqrt2$ and $\\psi_{du} = -1/\\sqrt2$, about $\\pm 0.707$.',
          'Build the exit-check state: switch to “two separate spins” and set Alice θ = 90° and φ = 0°, and Bob’s the same. Every box reads 1/2.',
          `Go deeper (beyond the notes): switch on “show the factoring test”. The singlet reads ${d(V.l9SingDet, 1)}; two separate spins always read 0.`,
        ],
      },
      clues: [],
      insight: 'The singlet is a good state of the pair, but no Alice state times a Bob state equals it. The pair has a state; the spins do not.',
      pitfalls: [
        'Counting terms. Four terms can still be a product; one flipped sign can make four terms entangled.',
        'Saying each spin is “in the singlet”. The singlet belongs to the pair; asking what each spin alone shows is Lecture 10’s question.',
      ],
      play: [
        {
          id: 'l9-si-exit',
          kind: 'choice',
          tier: 'core',
          title: 'The exit check',
          prompt: 'Is $\\tfrac12(|uu\\rangle + |ud\\rangle + |du\\rangle + |dd\\rangle)$ entangled? Try to factor it instead of counting terms.',
          options: [
            { text: 'No: it is a product, $|{+x}\\rangle \\otimes |{+x}\\rangle$', correct: true, why: 'Right: $\\tfrac{|u\\rangle + |d\\rangle}{\\sqrt2}$ for Alice times the same for Bob gives all four terms.' },
            { text: 'Yes: four terms means entangled', correct: false, why: 'The number of terms does not decide it. This state factors.' },
            { text: 'It is the singlet', correct: false, why: 'The singlet has only the terms $ud$ and $du$, with opposite signs.' },
            { text: 'It is not normalized', correct: false, why: `Each box is ½ in size, so the four chances add to ${d(V.l9UniNorm, 0)}.` },
          ],
          hints: [
            { text: 'Try to write it as (Alice’s state) times (Bob’s state).' },
            { text: 'Look for equal coefficients.' },
            { text: 'What state has equal amplitudes on $u$ and $d$?' },
          ],
          walkthrough: [
            { text: 'The state $\\tfrac{|u\\rangle + |d\\rangle}{\\sqrt2}$ is $|{+x}\\rangle$.' },
            { text: 'Multiplying out $|{+x}\\rangle \\otimes |{+x}\\rangle$ gives $\\tfrac12$ on each of the four basis states. It is a product.' },
          ],
        },
        {
          id: 'l9-si-proof',
          kind: 'order',
          tier: 'core',
          title: 'The no-factor proof',
          prompt: 'Put the proof that the singlet is not a product in order.',
          steps: [
            'Assume a product and match the four amplitudes',
            'The $ud$ amplitude is not zero, so $\\alpha_u$ is not zero',
            'The $uu$ amplitude is zero, so $\\beta_u = 0$',
            'Then the $du$ amplitude $\\alpha_d\\beta_u$ would be 0, but it must be $-1/\\sqrt2$',
            'The contradiction shows that no product equals the singlet',
          ],
          hints: [
            { text: 'A proof by contradiction begins with an assumption.' },
            { text: 'Follow the boxes: $ud$, then $uu$, then $du$.' },
            { text: 'The last line is the conclusion.' },
          ],
          walkthrough: [
            { text: 'Assume the factorization and match the four amplitudes.' },
            { text: '$\\alpha_u \\ne 0$ forces $\\beta_u = 0$, which empties the box $du$; the singlet does not. Contradiction.' },
          ],
        },
        {
          id: 'l9-si-flip',
          kind: 'choice',
          tier: 'stretch',
          title: 'One sign flipped',
          prompt: 'Is $\\tfrac12(|uu\\rangle + |ud\\rangle + |du\\rangle - |dd\\rangle)$ a product state?',
          options: [
            { text: 'No: it is entangled', correct: true, why: 'Right: equal $\\alpha_u\\beta_u$ and $\\alpha_u\\beta_d$ force $\\beta_u = \\beta_d$, equal $\\alpha_u\\beta_u$ and $\\alpha_d\\beta_u$ force $\\alpha_u = \\alpha_d$, and then $\\alpha_d\\beta_d$ would be $+\\tfrac12$.' },
            { text: 'Yes: it is $|{+x}\\rangle \\otimes |{+x}\\rangle$', correct: false, why: 'That product has $+\\tfrac12$ on all four boxes; this state has $-\\tfrac12$ on the last.' },
            { text: 'Yes: any four-term state is a product', correct: false, why: 'The number of terms decides nothing.' },
            { text: 'It is not a state', correct: false, why: `It is normalized: the chances add to ${d(V.l9UniNorm, 0)}.` },
          ],
          hints: [
            { text: 'Try to factor it, as in the exit check.' },
            { text: 'Compare the boxes $uu$, $ud$ and $du$: they have the same size and sign.' },
            { text: 'What does that force for $\\alpha_d\\beta_d$?' },
          ],
          walkthrough: [
            { text: 'Equal boxes $uu = ud$ force $\\beta_u = \\beta_d$; equal boxes $uu = du$ force $\\alpha_u = \\alpha_d$.' },
            { text: `Then $\\alpha_d\\beta_d = \\alpha_u\\beta_u = ${tf(V.l9UniAmp)}$, but the state needs $-${tf(V.l9UniAmp)}$. No product exists.` },
          ],
        },
      ],
    },
  ],
}
