/**
 * The light registry (content/meta.generated.ts) must say exactly what the lectures say. Regenerate it after any
 * change to lecture ids, titles, unit titles or questions, challenge ids or board equations:
 *
 *   UPDATE_META=1 npx vitest run src/content/meta.test.ts
 */
import { describe, expect, it } from 'vitest'
import { APP_DIR, env, fs, path } from '../security/node'
import { LECTURES } from './index'
import { LOADABLE, cachedLecture, loadLecture } from './load'
import { LECTURE_META, type LectureMeta, metaById } from './meta'

const derived: LectureMeta[] = LECTURES.map((l) => ({
  id: l.id,
  number: l.number,
  title: l.title,
  units: l.units.map((u) => ({
    id: u.id,
    title: u.title,
    question: u.question,
    challenges: u.play.map((c) => c.id),
    equations: u.lecture.equations ?? [],
  })),
}))

if (env.UPDATE_META) {
  fs.writeFileSync(
    path.join(APP_DIR, 'src/content/meta.generated.ts'),
    `/** GENERATED by content/meta.test.ts (UPDATE_META=1): do not edit by hand. */\nimport type { LectureMeta } from './meta'\n\nexport const LECTURE_META: LectureMeta[] = ${JSON.stringify(derived, null, 2)}\n`,
  )
}

describe('lecture registry', () => {
  it('matches the lectures (else regenerate with UPDATE_META=1)', () => {
    expect(LECTURE_META).toEqual(derived)
  })
  it('every registered lecture has a loader, and only those', () => {
    expect([...LOADABLE].sort()).toEqual(LECTURE_META.map((l) => l.id).sort())
  })
  it('loads each lecture as the same object the eager registry holds, then serves it from the cache', async () => {
    for (const l of LECTURES) {
      expect(await loadLecture(l.id)).toBe(l)
      expect(cachedLecture(l.id.toLowerCase())).toBe(l)
    }
    expect(await loadLecture('L99')).toBeUndefined()
    expect(metaById('l3')?.id).toBe('L3')
  })
})
