/**
 * The light registries must say exactly what the chapters say, per course:
 *   448  content/meta.generated.ts        (LECTURE_META, from content/index.ts)
 *   709  content/qc709/meta.generated.ts  (QC_META, from the chapter files qc709/Q{n}.ts / F{n}.ts)
 * Regenerate both after any change to chapter ids, titles, unit titles or questions, challenge ids or board equations:
 *
 *   UPDATE_META=1 npx vitest run src/content/meta.test.ts
 */
import { describe, expect, it } from 'vitest'
import { APP_DIR, env, fs, path } from '../security/node'
import { metaFor, registerCourseMeta, type CourseId } from './courses'
import { LECTURES } from './index'
import { LOADABLE, LOADABLE_709, cachedLecture, loadLecture } from './load'
import { LECTURE_META, type LectureMeta, metaById } from './meta'
import { Q0 } from './qc709/__fixtures__/demoChapter'
import { QC_CHAPTERS, QC_FILES } from './qc709/index'
import { QC_META } from './qc709/meta.generated'
import { OUTLINE_CHAPTERS } from './qc709/outline'
import type { Lecture } from './schema'

/** What the registry lists for a chapter (the pages that LIST chapters need no more). */
export const deriveMeta = (lectures: Lecture[]): LectureMeta[] =>
  lectures.map((l) => ({
    id: l.id,
    number: l.number,
    title: l.title,
    units: l.units.map((u) => ({
      id: u.id,
      title: u.title,
      question: u.question,
      challenges: u.play.map((c) => c.id),
      equations: u.lecture.equations ?? [],
    })),
  }))

const REGISTRIES: { course: CourseId; file: string; name: string; typeFrom: string; lectures: Lecture[]; current: LectureMeta[]; loadable: string[] }[] = [
  { course: 'sl448', file: 'src/content/meta.generated.ts', name: 'LECTURE_META', typeFrom: './meta', lectures: LECTURES, current: LECTURE_META, loadable: LOADABLE },
  { course: 'qc709', file: 'src/content/qc709/meta.generated.ts', name: 'QC_META', typeFrom: '../meta', lectures: QC_CHAPTERS, current: QC_META, loadable: LOADABLE_709 },
]

const generated = (r: (typeof REGISTRIES)[number]) =>
  `/** GENERATED by content/meta.test.ts (UPDATE_META=1): do not edit by hand. */\nimport type { LectureMeta } from '${r.typeFrom}'\n\nexport const ${r.name}: LectureMeta[] = ${JSON.stringify(deriveMeta(r.lectures), null, 2)}\n`

if (env.UPDATE_META) for (const r of REGISTRIES) fs.writeFileSync(path.join(APP_DIR, r.file), generated(r))

describe.each(REGISTRIES)('chapter registry of $course', (r) => {
  it('matches the chapters (else regenerate with UPDATE_META=1)', () => {
    expect(r.current).toEqual(deriveMeta(r.lectures))
    // byte-identical, so a regeneration never churns the file
    expect(fs.readFileSync(path.join(APP_DIR, r.file), 'utf8')).toBe(generated(r))
  })
  it('every registered chapter has a loader, and only those', () => {
    expect([...r.loadable].sort()).toEqual(r.current.map((l) => l.id).sort())
  })
  it('loads each chapter as the same object the eager registry holds, then serves it from the cache', async () => {
    registerCourseMeta('qc709', QC_META) // what the 709 pages' registry chunk does on load
    for (const l of r.lectures) {
      expect(await loadLecture(l.id)).toBe(l)
      expect(cachedLecture(l.id.toLowerCase())).toBe(l)
    }
    expect(metaFor(r.course)).toBe(r.current)
  })
})

describe('lecture registry (448)', () => {
  it('unknown ids load nothing; lookups are case-insensitive', async () => {
    expect(await loadLecture('L99')).toBeUndefined()
    expect(await loadLecture('Q99')).toBeUndefined()
    expect(metaById('l3')?.id).toBe('L3')
  })
})

describe('chapter registry (709)', () => {
  it('every chapter file exports the chapter it is named after, with that id', () => {
    for (const f of QC_FILES) expect(f.exported, `${f.file} must export ${f.id}`).toBe(true)
    for (const l of QC_CHAPTERS) expect(QC_FILES.some((f) => f.id === l.id), l.id).toBe(true)
  })
  it('only chapters of the semester outline can be registered, and the outline knows which are built', () => {
    const outline = new Set(OUTLINE_CHAPTERS.map((c) => c.id))
    for (const m of QC_META) expect(outline.has(m.id), m.id).toBe(true)
    for (const c of OUTLINE_CHAPTERS) expect(c.status === 'built', c.id).toBe(QC_META.some((m) => m.id === c.id))
  })
  it('generation works for 709 ids (the DEV demo chapter Q0): units, challenges and boards carry through', () => {
    const [m] = deriveMeta([Q0])
    expect(m.id).toBe('Q0')
    expect(m.units.map((u) => u.id)).toEqual(['q0-demo-sphere', 'q0-demo-plain', 'q0-demo-kinds', 'q0-demo-fields'])
    expect(m.units[1].challenges).toEqual(['q0-demo-plain-c1'])
    expect(QC_META.some((x) => x.id === 'Q0')).toBe(false) // the fixture is never registered
  })
})
