/** GENERATED by content/meta.test.ts (UPDATE_META=1): do not edit by hand. */
import type { LectureMeta } from './meta'

export const LECTURE_META: LectureMeta[] = [
  {
    "id": "L1",
    "number": 1,
    "title": "Stern–Gerlach and the birth of the quantum state",
    "units": [
      {
        "id": "l1-quantized",
        "title": "Two spots, not a smear",
        "question": "If spin is a tiny magnet, why does the beam split into exactly two spots?",
        "challenges": [
          "l1-q-classical",
          "l1-q-repeat"
        ],
        "equations": [
          "S_z \\in \\{+\\tfrac{\\hbar}{2},\\; -\\tfrac{\\hbar}{2}\\}"
        ]
      },
      {
        "id": "l1-sequential",
        "title": "A new axis erases the old answer",
        "question": "What happens when you measure along x an atom you already know is \"up\" along z?",
        "challenges": [
          "l1-s-zxz",
          "l1-s-blocked",
          "l1-s-memory"
        ],
        "equations": [
          "P(\\pm x \\mid {+z}) = \\tfrac{1}{2}",
          "P(\\pm z \\mid {+x}) = \\tfrac{1}{2}"
        ]
      },
      {
        "id": "l1-average",
        "title": "Single atoms are random, averages are classical",
        "question": "If each atom is random, what does the tilt of the magnet actually control?",
        "challenges": [
          "l1-a-45",
          "l1-a-34",
          "l1-a-errata",
          "l1-a-avg"
        ],
        "equations": [
          "\\langle \\sigma_n \\rangle = \\hat n\\cdot\\hat m = \\cos\\theta",
          "P(+) = \\tfrac{1+\\cos\\theta}{2} = \\cos^2\\tfrac{\\theta}{2}"
        ]
      },
      {
        "id": "l1-logic",
        "title": "When \"or\" depends on the order",
        "question": "Why can't quantum propositions be checked like facts about a set?",
        "challenges": [
          "l1-l-false",
          "l1-l-assumption"
        ],
        "equations": []
      },
      {
        "id": "l1-vectors",
        "title": "States are vectors",
        "question": "What mathematical object can hold \"up\", \"right\", and the 50/50 relation between them?",
        "challenges": [
          "l1-v-right",
          "l1-v-left",
          "l1-v-norm"
        ],
        "equations": [
          "|\\psi\\rangle = \\alpha\\,|{+z}\\rangle + \\beta\\,|{-z}\\rangle,\\quad |\\alpha|^2 + |\\beta|^2 = 1",
          "|{+x}\\rangle = \\tfrac{1}{\\sqrt2}(|{+z}\\rangle + |{-z}\\rangle),\\quad |{-x}\\rangle = \\tfrac{1}{\\sqrt2}(|{+z}\\rangle - |{-z}\\rangle)",
          "P(\\text{outcome}) = |\\langle \\text{outcome}|\\psi\\rangle|^2"
        ]
      }
    ]
  },
  {
    "id": "L2",
    "number": 2,
    "title": "States as vectors in a complex space",
    "units": [
      {
        "id": "l2-vector-space",
        "title": "Kets add and scale like vectors",
        "question": "Which rules let spin states add and scale like arrows, and what changes when the numbers may be complex?",
        "challenges": [
          "l2-vs-rules",
          "l2-vs-sum-prob",
          "l2-vs-bra-scale",
          "l2-vs-real-closed"
        ],
        "equations": [
          "|A\\rangle + |B\\rangle = |B\\rangle + |A\\rangle,\\qquad (|A\\rangle + |B\\rangle) + |C\\rangle = |A\\rangle + (|B\\rangle + |C\\rangle),\\qquad \\lambda(|A\\rangle + |B\\rangle) = \\lambda|A\\rangle + \\lambda|B\\rangle"
        ]
      },
      {
        "id": "l2-inner-product",
        "title": "Overlap: the inner product gives coordinates",
        "question": "How does a bra times a ket measure overlap, and give a state’s coordinates in any basis?",
        "challenges": [
          "l2-ip-overlap",
          "l2-ip-right-left",
          "l2-ip-townsend",
          "l2-ip-delta"
        ],
        "equations": [
          "\\langle B|A\\rangle = b_1^*a_1 + b_2^*a_2,\\qquad \\delta = \\langle{+x}|\\psi\\rangle = \\tfrac{\\alpha+\\beta}{\\sqrt2},\\qquad \\varepsilon = \\langle{-x}|\\psi\\rangle = \\tfrac{\\alpha-\\beta}{\\sqrt2}"
        ]
      },
      {
        "id": "l2-complex",
        "title": "Numbers that turn",
        "question": "Why do the real numbers run out, and what does multiplying by $i$ do?",
        "challenges": [
          "l2-c-modulus",
          "l2-c-turn",
          "l2-c-sqrt",
          "l2-c-euler"
        ],
        "equations": [
          "z = a + ib = r(\\cos\\varphi + i\\sin\\varphi) = re^{i\\varphi},\\qquad z^* = a - ib,\\qquad z^*z = r^2"
        ]
      },
      {
        "id": "l2-plus-y",
        "title": "Real numbers cannot make +y",
        "question": "Which state reads + along $y$, and why must its amplitudes be complex?",
        "challenges": [
          "l2-y-zsplit",
          "l2-y-why-complex",
          "l2-y-townsend",
          "l2-y-35"
        ],
        "equations": [
          "|{\\pm y}\\rangle = \\tfrac{1}{\\sqrt2}\\big(|{+z}\\rangle \\pm i|{-z}\\rangle\\big)"
        ]
      },
      {
        "id": "l2-three-bases",
        "title": "Three bases, each blind to the others",
        "question": "How are the $z$, $x$ and $y$ bases related, and what kind of object is a spin state?",
        "challenges": [
          "l2-mub-xy",
          "l2-mub-which",
          "l2-mub-phase",
          "l2-mub-count"
        ],
        "equations": [
          "|\\langle a|b\\rangle|^2 = \\tfrac12\\ \\ (a, b \\text{ from different bases}),\\qquad |\\psi\\rangle = \\alpha|{+z}\\rangle + \\beta|{-z}\\rangle,\\ \\ \\langle\\psi|\\psi\\rangle = 1"
        ]
      }
    ]
  },
  {
    "id": "L3",
    "number": 3,
    "title": "Quantum measurement",
    "units": [
      {
        "id": "l3-operators",
        "title": "Operators: machines that turn states into states",
        "question": "What is a linear operator, and how does a basis turn it into a matrix?",
        "challenges": [
          "l3-op-swap",
          "l3-op-columns",
          "l3-op-linear"
        ],
        "equations": [
          "\\hat A|\\psi\\rangle = |\\phi\\rangle,\\qquad A_{ij} = \\langle i|\\hat A|j\\rangle"
        ]
      },
      {
        "id": "l3-eigen",
        "title": "Directions an operator only stretches",
        "question": "Which states does an operator leave on their own line, and why must an observable be Hermitian?",
        "challenges": [
          "l3-eig-sz",
          "l3-eig-which",
          "l3-eig-hermitian",
          "l3-eig-real"
        ],
        "equations": [
          "\\hat A|a\\rangle = a|a\\rangle,\\qquad \\hat A^\\dagger = \\hat A,\\qquad (A^\\dagger)_{ij} = A_{ji}^*"
        ]
      },
      {
        "id": "l3-projectors",
        "title": "Projectors keep one part of a state",
        "question": "How do we pull one outcome’s piece out of a state, and how do the outcomes build an observable?",
        "challenges": [
          "l3-proj-length",
          "l3-proj-matrix",
          "l3-proj-build",
          "l3-proj-notcomplete"
        ],
        "equations": [
          "\\hat P_{+z}^2 = \\hat P_{+z},\\qquad \\sum_i |a_i\\rangle\\langle a_i| = \\hat 1,\\qquad \\hat A = \\sum_i a_i|a_i\\rangle\\langle a_i|"
        ]
      },
      {
        "id": "l3-postulates",
        "title": "Three rules for every measurement",
        "question": "Given $|\\psi\\rangle$ and $\\hat A$, which results can appear, how likely is each, and what state is left?",
        "challenges": [
          "l3-post-born",
          "l3-post-x",
          "l3-post-after",
          "l3-post-steps"
        ],
        "equations": [
          "P(a_i) = |\\langle a_i|\\psi\\rangle|^2 = \\langle\\psi|\\hat P_i|\\psi\\rangle,\\qquad |\\psi\\rangle \\to \\frac{\\hat P_i|\\psi\\rangle}{\\sqrt{\\langle\\psi|\\hat P_i|\\psi\\rangle}}"
        ]
      },
      {
        "id": "l3-spin-example",
        "title": "One spin, measured from start to finish",
        "question": "What do the three rules predict for $|{+x}\\rangle$ sent through $z$, through $z$ again, or through $x$ and then $z$?",
        "challenges": [
          "l3-ex-repeat",
          "l3-ex-insert",
          "l3-ex-tilt"
        ],
        "equations": [
          "P(\\pm\\tfrac{\\hbar}{2}) = |\\langle{\\pm z}|{+x}\\rangle|^2 = \\tfrac12,\\qquad |{+z}\\rangle = \\tfrac{1}{\\sqrt2}\\big(|{+x}\\rangle + |{-x}\\rangle\\big)"
        ]
      },
      {
        "id": "l3-spread",
        "title": "Averages and spreads of many readings",
        "question": "What is the average reading, and how widely do single readings scatter around it?",
        "challenges": [
          "l3-sp-mean",
          "l3-sp-spread",
          "l3-sp-zero",
          "l3-sp-complex"
        ],
        "equations": [
          "\\langle A\\rangle = \\sum_i a_i P(a_i) = \\langle\\psi|\\hat A|\\psi\\rangle,\\qquad (\\Delta A)^2 = \\langle A^2\\rangle - \\langle A\\rangle^2"
        ]
      }
    ]
  },
  {
    "id": "L4",
    "number": 4,
    "title": "Measurement principles and spin operators",
    "units": [
      {
        "id": "l4-basis",
        "title": "Four principles and a complete basis",
        "question": "What must an observable’s eigenstates do so that every state can be measured?",
        "challenges": [
          "l4-b-distinct",
          "l4-b-complete",
          "l4-b-expand"
        ],
        "equations": [
          "\\langle a_i|a_j\\rangle = \\delta_{ij},\\qquad |\\psi\\rangle = \\sum_i c_i|a_i\\rangle,\\qquad \\sum_i \\hat P_i = I"
        ]
      },
      {
        "id": "l4-projectors",
        "title": "A projector asks a yes/no question",
        "question": "What does one projector measure, and how does it fit into a full measurement?",
        "challenges": [
          "l4-p-results",
          "l4-p-yes",
          "l4-p-idempotent",
          "l4-p-two-filters"
        ],
        "equations": [
          "\\hat P_{+z}^2 = \\hat P_{+z},\\qquad \\hat P_{+z}\\hat P_{-z} = 0,\\qquad \\hat P_{+z} + \\hat P_{-z} = I"
        ]
      },
      {
        "id": "l4-example",
        "title": "One state, the whole prediction",
        "question": "For a state with unequal amplitudes, which results occur, how often, and what is left?",
        "challenges": [
          "l4-e-minus",
          "l4-e-four",
          "l4-e-normalize",
          "l4-e-then-x"
        ],
        "equations": [
          "P(+\\tfrac{\\hbar}{2}) = |\\langle{+z}|\\psi\\rangle|^2 = \\tfrac34,\\qquad \\frac{\\hat P_{+z}|\\psi\\rangle}{\\sqrt{3/4}} = |{+z}\\rangle"
        ]
      },
      {
        "id": "l4-average",
        "title": "The average that no atom reads",
        "question": "What is the mean $S_z$ reading for this lecture’s state, and how does the sandwich give it in matrix form?",
        "challenges": [
          "l4-a-mean",
          "l4-a-erratum",
          "l4-a-yesno-mean"
        ],
        "equations": [
          "\\langle S_z\\rangle = \\langle\\psi|\\hat S_z|\\psi\\rangle = \\tfrac{\\hbar}{2}\\cdot\\tfrac34 - \\tfrac{\\hbar}{2}\\cdot\\tfrac14 = \\tfrac{\\hbar}{4}"
        ]
      },
      {
        "id": "l4-matrices",
        "title": "Spin matrices built from their outcomes",
        "question": "Given the definite states and their values, which matrix must each spin component be?",
        "challenges": [
          "l4-m-m22",
          "l4-m-py",
          "l4-m-noconj",
          "l4-m-basis"
        ],
        "equations": [
          "S_x = \\tfrac{\\hbar}{2}\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix},\\quad S_y = \\tfrac{\\hbar}{2}\\begin{pmatrix}0&-i\\\\i&0\\end{pmatrix},\\quad S_z = \\tfrac{\\hbar}{2}\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}"
        ]
      },
      {
        "id": "l4-eigen",
        "title": "From a matrix back to outcomes",
        "question": "Given only the matrix, how do we recover the possible results and the definite states?",
        "challenges": [
          "l4-g-zero",
          "l4-g-order",
          "l4-g-sx-prob",
          "l4-g-shift",
          "l4-g-sy"
        ],
        "equations": [
          "\\det(S_x - \\lambda I) = \\lambda^2 - \\tfrac{\\hbar^2}{4},\\qquad P(\\pm\\tfrac{\\hbar}{2}) = \\tfrac12|\\alpha \\pm \\beta|^2"
        ]
      }
    ]
  },
  {
    "id": "L5",
    "number": 5,
    "title": "Spin matrices, expectation values and basis changes",
    "units": [
      {
        "id": "l5-averages",
        "title": "Three averages from one column",
        "question": "Given a state’s two $z$ amplitudes, what are the average spin readings along $x$, $y$ and $z$?",
        "challenges": [
          "l5-av-pop",
          "l5-av-coh",
          "l5-av-phase",
          "l5-av-missing"
        ],
        "equations": [
          "\\langle S_z\\rangle = \\tfrac{\\hbar}{2}(\\lvert\\alpha\\rvert^2 - \\lvert\\beta\\rvert^2),\\qquad \\langle S_x\\rangle = \\hbar\\,\\mathrm{Re}(\\alpha^*\\beta),\\qquad \\langle S_y\\rangle = \\hbar\\,\\mathrm{Im}(\\alpha^*\\beta)"
        ]
      },
      {
        "id": "l5-inverse",
        "title": "Matrix in, outcomes and states out",
        "question": "Handed only a matrix, how do we find its possible readings, and the states that give them for sure?",
        "challenges": [
          "l5-inv-values",
          "l5-inv-vector",
          "l5-inv-complex"
        ],
        "equations": [
          "\\det(A - \\lambda I) = 0,\\qquad (A - \\lambda I)\\binom{c_1}{c_2} = 0"
        ]
      },
      {
        "id": "l5-coordinates",
        "title": "Same state, new coordinates",
        "question": "How do we rewrite a state’s column so that its entries are the amplitudes for an $x$ measurement?",
        "challenges": [
          "l5-co-u",
          "l5-co-prob",
          "l5-co-arrow",
          "l5-co-skew"
        ],
        "equations": [
          "c_z = B_{z\\leftarrow x}\\,c_x,\\qquad c_x = B_{x\\leftarrow z}\\,c_z = B_{z\\leftarrow x}^\\dagger\\,c_z"
        ]
      },
      {
        "id": "l5-operators",
        "title": "Operators change coordinates too",
        "question": "How must an operator’s matrix change with the basis, and why is it diagonal in its own eigenbasis?",
        "challenges": [
          "l5-op-label",
          "l5-op-order",
          "l5-op-eigenbasis",
          "l5-op-sy-in-x"
        ],
        "equations": [
          "A^{(x)} = B_{x\\leftarrow z}\\,A^{(z)}\\,B_{z\\leftarrow x},\\qquad AB = BD,\\ B^\\dagger B = I \\;\\Rightarrow\\; B^\\dagger AB = D"
        ]
      },
      {
        "id": "l5-invariance",
        "title": "Predictions ignore the coordinates",
        "question": "Why does every average and every probability come out the same in any basis?",
        "challenges": [
          "l5-in-plusx",
          "l5-in-sx",
          "l5-in-proof",
          "l5-in-ybasis"
        ],
        "equations": [
          "c_{\\text{new}}^\\dagger A^{(\\text{new})}c_{\\text{new}} = c_{\\text{old}}^\\dagger A^{(\\text{old})}c_{\\text{old}}"
        ]
      }
    ]
  },
  {
    "id": "L6",
    "number": 6,
    "title": "Basis changes, the Bloch sphere and rotations",
    "units": [
      {
        "id": "l6-bloch",
        "title": "Three averages make a point",
        "question": "How can one picture hold every pure spin state?",
        "challenges": [
          "l6-b-theta",
          "l6-b-phi",
          "l6-b-average",
          "l6-b-opposite"
        ],
        "equations": [
          "\\vec r = \\tfrac{2}{\\hbar}\\big(\\langle S_x\\rangle, \\langle S_y\\rangle, \\langle S_z\\rangle\\big) = \\big(2\\,\\mathrm{Re}\\,\\alpha^*\\beta,\\ 2\\,\\mathrm{Im}\\,\\alpha^*\\beta,\\ |\\alpha|^2 - |\\beta|^2\\big),\\qquad |\\vec r| = 1"
        ]
      },
      {
        "id": "l6-equator",
        "title": "Relative phase sets the longitude",
        "question": "If $|{\\pm x}\\rangle$ and $|{\\pm y}\\rangle$ all give 50/50 along $z$, what tells them apart?",
        "challenges": [
          "l6-e-rx",
          "l6-e-disguise",
          "l6-e-px",
          "l6-e-phase"
        ],
        "equations": [
          "|\\psi(\\varphi)\\rangle = \\tfrac{1}{\\sqrt2}\\big(|{+z}\\rangle + e^{i\\varphi}|{-z}\\rangle\\big),\\qquad \\vec r = (\\cos\\varphi, \\sin\\varphi, 0)"
        ]
      },
      {
        "id": "l6-active",
        "title": "Turn the state, keep the axes",
        "question": "What matrix turns a spin state about $z$, and how is that different from changing basis?",
        "challenges": [
          "l6-ac-which",
          "l6-ac-px",
          "l6-ac-to-minus-y",
          "l6-ac-rotate-avg"
        ],
        "equations": [
          "R_z(\\varphi) = \\begin{pmatrix}e^{-i\\varphi/2}&0\\\\0&e^{i\\varphi/2}\\end{pmatrix},\\qquad R_z(\\varphi)\\,\\psi_z(\\varphi_0) = e^{-i\\varphi/2}\\,\\psi_z(\\varphi_0 + \\varphi)"
        ]
      },
      {
        "id": "l6-generator",
        "title": "Sz generates the turn",
        "question": "Why is $R_z(\\varphi) = e^{-i\\varphi S_z/\\hbar}$, and what job does $S_z$ do in it?",
        "challenges": [
          "l6-g-exp-diag",
          "l6-g-small-form",
          "l6-g-leftover",
          "l6-g-velocity"
        ],
        "equations": [
          "R_z(\\varphi) = e^{-i\\varphi S_z/\\hbar},\\qquad R_z(d\\varphi) = I - \\tfrac{i}{\\hbar}S_z\\,d\\varphi + O(d\\varphi^2)"
        ]
      },
      {
        "id": "l6-mixture",
        "title": "Superposition or mixture?",
        "question": "Can a beam of mixed atoms ever act like one pure state?",
        "challenges": [
          "l6-m-one-magnet",
          "l6-m-certain",
          "l6-m-lookalike",
          "l6-m-best-tilt"
        ],
        "equations": [
          "\\vec r_{\\text{mix}} = \\sum_k w_k\\,\\vec r_k,\\qquad P(+\\hat n) = \\tfrac{1 + \\hat n\\cdot\\vec r}{2}"
        ]
      }
    ]
  },
  {
    "id": "L7",
    "number": 7,
    "title": "Rotations, compatible measurements and uncertainty",
    "units": [
      {
        "id": "l7-two-angles",
        "title": "Sphere angles are twice state angles",
        "question": "How does the angle between two Bloch arrows relate to the angle between the two states?",
        "challenges": [
          "l7-ta-overlap",
          "l7-ta-short-way",
          "l7-ta-orthogonal",
          "l7-ta-offaxis"
        ],
        "equations": [
          "\\eta = \\arccos|\\langle\\psi_1|\\psi_2\\rangle| = \\tfrac{\\Delta\\varphi}{2},\\qquad |\\langle\\psi_1|\\psi_2\\rangle|^2 = \\cos^2\\tfrac{\\Delta\\varphi}{2}"
        ]
      },
      {
        "id": "l7-full-turn",
        "title": "A full turn flips the sign",
        "question": "If a rotation brings the Bloch arrow all the way round, is the state vector back where it started?",
        "challenges": [
          "l7-ft-what-changes",
          "l7-ft-sandwich",
          "l7-ft-still",
          "l7-ft-720"
        ],
        "equations": [
          "R_z(\\varphi)|\\psi(\\varphi_0)\\rangle = e^{-i\\varphi/2}|\\psi(\\varphi_0 + \\varphi)\\rangle,\\qquad R_z(2\\pi) = -I,\\qquad R_z(4\\pi) = I"
        ]
      },
      {
        "id": "l7-order",
        "title": "Swapping the order of two measurements",
        "question": "When does measuring z then x predict something different from x then z?",
        "challenges": [
          "l7-or-swap",
          "l7-or-steps",
          "l7-or-repeat",
          "l7-or-tilt"
        ],
        "equations": [
          "p(a) = \\langle\\psi|P_a|\\psi\\rangle,\\qquad |\\psi\\rangle \\to \\frac{P_a|\\psi\\rangle}{\\sqrt{p(a)}}"
        ]
      },
      {
        "id": "l7-compatible",
        "title": "Compatible measurements share a basis and commute",
        "question": "What property of two observables guarantees that their order never matters?",
        "challenges": [
          "l7-co-which",
          "l7-co-joint",
          "l7-co-yplus",
          "l7-co-tilt"
        ],
        "equations": [
          "[A, B] = AB - BA,\\qquad [S_x, S_y] = i\\hbar S_z,\\quad [S_y, S_z] = i\\hbar S_x,\\quad [S_z, S_x] = i\\hbar S_y"
        ]
      },
      {
        "id": "l7-spreads",
        "title": "Spreads you can read off the sphere",
        "question": "How uncertain is each spin component in one prepared state?",
        "challenges": [
          "l7-sp-plusz",
          "l7-sp-sixty",
          "l7-sp-sum",
          "l7-sp-ninety"
        ],
        "equations": [
          "(\\Delta S_j)^2 = \\langle S_j^2\\rangle - \\langle S_j\\rangle^2 = \\tfrac{\\hbar^2}{4}\\,(1 - r_j^2)"
        ]
      },
      {
        "id": "l7-uncertainty",
        "title": "A floor under the product of spreads",
        "question": "How small can the spreads of Sx and Sy be at the same time?",
        "challenges": [
          "l7-un-zero",
          "l7-un-product",
          "l7-un-max",
          "l7-un-gap"
        ],
        "equations": [
          "\\Delta S_x\\,\\Delta S_y \\ge \\tfrac{\\hbar}{2}\\lvert\\langle S_z\\rangle\\rvert,\\qquad \\Delta A\\,\\Delta B \\ge \\tfrac12\\lvert\\langle[A, B]\\rangle\\rvert"
        ]
      }
    ]
  },
  {
    "id": "L8",
    "number": 8,
    "title": "Polarization and BB84",
    "units": [
      {
        "id": "l8-variance-sum",
        "title": "Three variances that always add to two",
        "question": "If one spin component is certain, how random are the other two?",
        "challenges": [
          "l8-vs-sum",
          "l8-vs-pole",
          "l8-vs-mixed"
        ],
        "equations": [
          "(\\Delta\\sigma_i)^2 = 1 - r_i^2",
          "\\sum_i(\\Delta\\sigma_i)^2 = 3 - r^2 = 2"
        ]
      },
      {
        "id": "l8-polarization",
        "title": "A second qubit: the polarization of light",
        "question": "How does one photon’s polarization behave like a spin state?",
        "challenges": [
          "l8-po-d-in-hv",
          "l8-po-30",
          "l8-po-mub"
        ],
        "equations": [
          "|\\psi\\rangle = \\alpha|H\\rangle + \\beta|V\\rangle",
          "|D\\rangle, |A\\rangle = \\tfrac{1}{\\sqrt2}\\left(|H\\rangle \\pm |V\\rangle\\right)"
        ]
      },
      {
        "id": "l8-turning",
        "title": "Turning a polarization: the rotation matrix",
        "question": "What matrix turns a polarization, and what does an analyzer pass?",
        "challenges": [
          "l8-tu-15",
          "l8-tu-matrix",
          "l8-tu-block"
        ],
        "equations": [
          "R_{\\mathrm{pol}}(\\varphi) = \\begin{pmatrix}\\cos\\varphi & -\\sin\\varphi\\\\ \\sin\\varphi & \\cos\\varphi\\end{pmatrix}",
          "P(\\text{aligned}) = \\cos^2\\Delta\\chi"
        ]
      },
      {
        "id": "l8-photon-spin",
        "title": "A photon turns the sphere twice as fast",
        "question": "Why does a 90° turn of light cross the whole Bloch sphere?",
        "challenges": [
          "l8-ps-sphere",
          "l8-ps-phase",
          "l8-ps-electron"
        ],
        "equations": [
          "G = \\sigma_y",
          "R_{\\mathrm{pol}}(\\varphi) = e^{-i\\varphi\\sigma_y}",
          "R_{\\mathrm{pol}}(\\varphi)|C_\\pm\\rangle = e^{\\mp i\\varphi}|C_\\pm\\rangle"
        ]
      },
      {
        "id": "l8-key",
        "title": "Why share a secret key",
        "question": "What problem does a quantum key solve?",
        "challenges": [
          "l8-ke-otp",
          "l8-ke-why"
        ],
        "equations": [
          "c = x \\oplus k",
          "x = c \\oplus k"
        ]
      },
      {
        "id": "l8-bb84",
        "title": "BB84: prepare, measure, then compare bases",
        "question": "How do Alice and Bob end up with the same bits?",
        "challenges": [
          "l8-bb-sift",
          "l8-bb-kept",
          "l8-bb-luck"
        ],
        "equations": [
          "P(B_A = B_B) = \\tfrac12",
          "P(b \\ne a \\mid B_A = B_B) = 0"
        ]
      },
      {
        "id": "l8-attack",
        "title": "An eavesdropper who measures and resends",
        "question": "What does a measuring eavesdropper leave behind?",
        "challenges": [
          "l8-at-exit",
          "l8-at-q",
          "l8-at-photon"
        ],
        "equations": [
          "Q = \\tfrac12\\cdot 0 + \\tfrac12\\cdot\\tfrac12 = \\tfrac14"
        ]
      },
      {
        "id": "l8-test",
        "title": "Catching the eavesdropper with a test sample",
        "question": "How many tested bits make the attack visible?",
        "challenges": [
          "l8-te-20",
          "l8-te-99",
          "l8-te-not-threshold"
        ],
        "equations": [
          "P(\\text{no error in } m) = \\left(\\tfrac34\\right)^m"
        ]
      }
    ]
  },
  {
    "id": "L9",
    "number": 9,
    "title": "Composite quantum systems",
    "units": [
      {
        "id": "l9-tensor",
        "title": "Two systems need one new space",
        "question": "What state space describes two systems at once?",
        "challenges": [
          "l9-te-dim",
          "l9-te-dim3",
          "l9-te-one"
        ],
        "equations": [
          "\\dim(\\mathcal H_A \\otimes \\mathcal H_B) = N_A N_B"
        ]
      },
      {
        "id": "l9-classical",
        "title": "Correlation without anything quantum",
        "question": "Can two coins be correlated with nothing quantum going on?",
        "challenges": [
          "l9-cl-ab",
          "l9-cl-indep",
          "l9-cl-biased"
        ],
        "equations": [
          "P(a,b) = P_A(a)P_B(b) \\;\\Rightarrow\\; \\langle ab\\rangle = \\langle a\\rangle\\langle b\\rangle"
        ]
      },
      {
        "id": "l9-two-spins",
        "title": "Two spins: four basis states",
        "question": "What basis describes two spin-½ particles together?",
        "challenges": [
          "l9-ts-overlap",
          "l9-ts-count",
          "l9-ts-label"
        ],
        "equations": [
          "|\\Psi\\rangle = \\psi_{uu}|uu\\rangle + \\psi_{ud}|ud\\rangle + \\psi_{du}|du\\rangle + \\psi_{dd}|dd\\rangle"
        ]
      },
      {
        "id": "l9-product",
        "title": "Independent preparations give product states",
        "question": "What state does a pair have when each part is prepared alone?",
        "challenges": [
          "l9-pr-amp",
          "l9-pr-norm",
          "l9-pr-words"
        ],
        "equations": [
          "\\psi_{ab} = \\alpha_a\\beta_b,\\qquad \\langle\\Psi|\\Psi\\rangle = (|\\alpha_u|^2 + |\\alpha_d|^2)(|\\beta_u|^2 + |\\beta_d|^2) = 1"
        ]
      },
      {
        "id": "l9-counting",
        "title": "Counting parameters: six is more than four",
        "question": "Does every pair state come from two separate preparations?",
        "challenges": [
          "l9-co-one",
          "l9-co-gen",
          "l9-co-why"
        ],
        "equations": [
          "8 - 1 - 1 = 6 > 2 + 2"
        ]
      },
      {
        "id": "l9-singlet",
        "title": "The singlet: a pair with no separate states",
        "question": "Which state of two spins cannot be split into two?",
        "challenges": [
          "l9-si-exit",
          "l9-si-proof",
          "l9-si-flip"
        ],
        "equations": [
          "|\\mathrm{sing}\\rangle = \\tfrac{1}{\\sqrt2}(|ud\\rangle - |du\\rangle)"
        ]
      }
    ]
  }
]
