/**
 * Answer mode is FROZEN (P review of the Grapher, docs/roles/audits/P-grapher-review.md item 1).
 *
 * The Grapher's grammar (`grammar: 'grapher'` in physics/expr.ts: "2 3" and "sin 2x" become errors) must not reach
 * any other caller. This table was generated from the parser BEFORE that grammar landed and committed first; every
 * row is asserted IDENTICAL after it. A row records, for one input, every answer-mode caller whole:
 *   - ui/parseNumber (every learner answer and challenge; whitespace deleted, the pre-W1 rule);
 *   - `parse` in real mode with the answer limits (the Operator Lab's τ field), with its value;
 *   - complex mode with the answer limits (the Operator Lab's generator) and the cell limits (typed matrix cells), and
 *     parseMatrix2 itself;
 *   - the grapher's function set WITHOUT the grapher grammar (`fns: 'grapher'` alone reads exactly as before).
 * The parse results are kept whole (the AST, or the caret and the reason), so a changed tree fails too, not only a
 * changed value. Inputs: spaces between numbers, functions with bare arguments, units, the Unicode operators.
 */
import { describe, expect, it } from 'vitest'
import { parseNumber } from '../ui/parseNumber'
import { LIMITS, evalComplex, evalReal, parse, parseMatrix2, type Parsed } from './expr'

const enc = (v: unknown): string => JSON.stringify(v, (_k, x: unknown) => (typeof x === 'number' && !Number.isFinite(x) ? `#${String(x)}` : x))
const ENV = new Map([['x', 0.7], ['t', 1.3]])
const realValue = (r: Parsed) => (r.ok ? evalReal(r.ast, ENV) : null)
const complexValue = (r: Parsed) => (r.ok ? evalComplex(r.ast) : null)

function row(src: string): string {
  const real = parse(src, { mode: 'real', limits: LIMITS.answer })
  const complex = parse(src, { mode: 'complex', limits: LIMITS.answer })
  const cell = parse(src, { mode: 'complex', limits: LIMITS.cell })
  const fns = parse(src, { mode: 'real', limits: LIMITS.grapher, fns: 'grapher', vars: ['x', 't'] })
  const m = parseMatrix2([[src, '0'], ['0', '0']])
  return enc({
    parseNumber: parseNumber(src),
    real,
    realValue: realValue(real),
    complex,
    complexValue: complexValue(complex),
    cell: enc(cell) === enc(complex) ? '=complex' : cell,
    matrix: m.ok ? m.M[0][0] : m,
    grapherFnsOnly: fns,
    grapherFnsOnlyValue: realValue(fns),
  })
}

const INPUTS: readonly string[] = [
  '2 3', '1 / 2', 'sin 2x', 'sin 2', 'sin 2 3', 'sin 2 pi', 'cos pi t', 'cos pi', '2 pi', '2pi', '1 2', '1 2 3', '1 . 5',
  '1e 3', '1e3', '2E3', '2 e 3', '2e', '2 e', '1e-3 2', '1 e-3', 'x^2 3', 'x 2', '2^3 4', '2^ 3', '(2) 3', '2 (3)', '2(3)',
  '1/2 3', 'sin(2) 3', 'sin(2)·3', 'sin 2·3', 'sin 2 * 3', '3 sin 2', '2 sin x', 'sin x cos t', 'sin x', 'sin(2x)',
  'sin pi/2', 'sqrt 2', 'sqrt 2 3', '√2', '√2 3', '√2x', '√2/2', '3√2', 'sqrt pi', 'sin pi', 'ln 2 3', 'e^2 3',
  'e^(i pi)', 'i pi', '2 i', '1 2i', '1+2i', 'sin 2i', 'exp i pi', 'pi 2', 'ħ 2', 'hbar/2', '0.5 0.5', '.5 .5', '1.5 2',
  '−1 2', '3 ÷ 4 × 2', ' 12 ', '-2^2', '2^-1', 'abs -2', 'abs(-2) 3', 'cos(0)^2', '√4^3', 'PI', 'SIN 2', '1/(1/0)',
  '(1+2', '', '  ', '2 $', 'asin 1', 'tanh 1', 'e', 'cos(pi/8)^2', '1/sqrt2', 'ħ/4', '3/4', '0.75',
]

/** Generated from the parser before the grapher grammar (grapherfix, 2026-09-28). Do not edit by hand. */
const TABLE: [string, string][] = [
  ["2 3", "{\"parseNumber\":23,\"real\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":23},\"vars\":[]},\"realValue\":23,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":6,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":6,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":23},\"vars\":[]},\"grapherFnsOnlyValue\":23}"],
  ["1 / 2", "{\"parseNumber\":0.5,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":0.5,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":0.5,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.5,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":0.5}"],
  ["sin 2x", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":5,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":5,\"reason\":\"unknown-identifier\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":5,\"reason\":\"unknown-identifier\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"var\",\"name\":\"x\"}},\"vars\":[\"x\"]},\"grapherFnsOnlyValue\":0.6365081987779772}"],
  ["sin 2", "{\"parseNumber\":0.9092974268256817,\"real\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":0.9092974268256817,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":0.9092974268256817,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.9092974268256817,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":0.9092974268256817}"],
  ["sin 2 3", "{\"parseNumber\":-0.8462204041751706,\"real\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":23}},\"vars\":[]},\"realValue\":-0.8462204041751706,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":2.727892280477045,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":2.727892280477045,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":23}},\"vars\":[]},\"grapherFnsOnlyValue\":-0.8462204041751706}"],
  ["sin 2 pi", "{\"parseNumber\":2.856642116043664,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"realValue\":2.856642116043664,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"complexValue\":{\"re\":2.856642116043664,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":2.856642116043664,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"grapherFnsOnlyValue\":2.856642116043664}"],
  ["cos pi t", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":7,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":7,\"reason\":\"unknown-identifier\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":7,\"reason\":\"unknown-identifier\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"cos\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"b\":{\"t\":\"var\",\"name\":\"t\"}},\"vars\":[\"t\"]},\"grapherFnsOnlyValue\":-1.3}"],
  ["cos pi", "{\"parseNumber\":null,\"real\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"cos\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"realValue\":-1,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"cos\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"complexValue\":{\"re\":-1,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":-1,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"cos\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"grapherFnsOnlyValue\":-1}"],
  ["2 pi", "{\"parseNumber\":6.283185307179586,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"realValue\":6.283185307179586,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"complexValue\":{\"re\":6.283185307179586,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":6.283185307179586,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"grapherFnsOnlyValue\":6.283185307179586}"],
  ["2pi", "{\"parseNumber\":6.283185307179586,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"realValue\":6.283185307179586,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"complexValue\":{\"re\":6.283185307179586,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":6.283185307179586,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"grapherFnsOnlyValue\":6.283185307179586}"],
  ["1 2", "{\"parseNumber\":12,\"real\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":12},\"vars\":[]},\"realValue\":12,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":2,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":2,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":12},\"vars\":[]},\"grapherFnsOnlyValue\":12}"],
  ["1 2 3", "{\"parseNumber\":123,\"real\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":123},\"vars\":[]},\"realValue\":123,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":6,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":6,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":123},\"vars\":[]},\"grapherFnsOnlyValue\":123}"],
  ["1 . 5", "{\"parseNumber\":1.5,\"real\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":1.5},\"vars\":[]},\"realValue\":1.5,\"complex\":{\"ok\":false,\"pos\":2,\"reason\":\"syntax\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":2,\"reason\":\"syntax\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":1.5},\"vars\":[]},\"grapherFnsOnlyValue\":1.5}"],
  ["1e 3", "{\"parseNumber\":1000,\"real\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":1000},\"vars\":[]},\"realValue\":1000,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"const\",\"name\":\"e\"}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":8.154845485377136,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":8.154845485377136,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":1000},\"vars\":[]},\"grapherFnsOnlyValue\":1000}"],
  ["1e3", "{\"parseNumber\":1000,\"real\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":1000},\"vars\":[]},\"realValue\":1000,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":1000},\"vars\":[]},\"complexValue\":{\"re\":1000,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":1000,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":1000},\"vars\":[]},\"grapherFnsOnlyValue\":1000}"],
  ["2E3", "{\"parseNumber\":16.30969097075427,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"e\"}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"realValue\":16.30969097075427,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"e\"}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":16.30969097075427,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":16.30969097075427,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"e\"}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"grapherFnsOnlyValue\":16.30969097075427}"],
  ["2 e 3", "{\"parseNumber\":2000,\"real\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":2000},\"vars\":[]},\"realValue\":2000,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"e\"}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":16.30969097075427,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":16.30969097075427,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":2000},\"vars\":[]},\"grapherFnsOnlyValue\":2000}"],
  ["2e", "{\"parseNumber\":5.43656365691809,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"e\"}},\"vars\":[]},\"realValue\":5.43656365691809,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"e\"}},\"vars\":[]},\"complexValue\":{\"re\":5.43656365691809,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":5.43656365691809,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"e\"}},\"vars\":[]},\"grapherFnsOnlyValue\":5.43656365691809}"],
  ["2 e", "{\"parseNumber\":5.43656365691809,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"e\"}},\"vars\":[]},\"realValue\":5.43656365691809,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"e\"}},\"vars\":[]},\"complexValue\":{\"re\":5.43656365691809,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":5.43656365691809,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"const\",\"name\":\"e\"}},\"vars\":[]},\"grapherFnsOnlyValue\":5.43656365691809}"],
  ["1e-3 2", "{\"parseNumber\":1e-32,\"real\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":1e-32},\"vars\":[]},\"realValue\":1e-32,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":0.001},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":0.002,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.002,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":1e-32},\"vars\":[]},\"grapherFnsOnlyValue\":1e-32}"],
  ["1 e-3", "{\"parseNumber\":0.001,\"real\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":0.001},\"vars\":[]},\"realValue\":0.001,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"-\",\"a\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"const\",\"name\":\"e\"}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":-0.2817181715409549,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":-0.2817181715409549,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":0.001},\"vars\":[]},\"grapherFnsOnlyValue\":0.001}"],
  ["x^2 3", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":0,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":0,\"reason\":\"unknown-identifier\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":0,\"reason\":\"unknown-identifier\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"var\",\"name\":\"x\"},\"b\":{\"t\":\"num\",\"v\":23}},\"vars\":[\"x\"]},\"grapherFnsOnlyValue\":0.0002736874734008088}"],
  ["x 2", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":0,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":0,\"reason\":\"unknown-identifier\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":0,\"reason\":\"unknown-identifier\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"var\",\"name\":\"x\"},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[\"x\"]},\"grapherFnsOnlyValue\":1.4}"],
  ["2^3 4", "{\"parseNumber\":17179869184,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":34}},\"vars\":[]},\"realValue\":17179869184,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"b\":{\"t\":\"num\",\"v\":4}},\"vars\":[]},\"complexValue\":{\"re\":32,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":32,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":34}},\"vars\":[]},\"grapherFnsOnlyValue\":17179869184}"],
  ["2^ 3", "{\"parseNumber\":8,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"realValue\":8,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":8,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":8,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"grapherFnsOnlyValue\":8}"],
  ["(2) 3", "{\"parseNumber\":6,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"realValue\":6,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":6,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":6,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"grapherFnsOnlyValue\":6}"],
  ["2 (3)", "{\"parseNumber\":6,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"realValue\":6,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":6,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":6,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"grapherFnsOnlyValue\":6}"],
  ["2(3)", "{\"parseNumber\":6,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"realValue\":6,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":6,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":6,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"grapherFnsOnlyValue\":6}"],
  ["1/2 3", "{\"parseNumber\":0.043478260869565216,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"num\",\"v\":23}},\"vars\":[]},\"realValue\":0.043478260869565216,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":1.5,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":1.5,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"num\",\"v\":23}},\"vars\":[]},\"grapherFnsOnlyValue\":0.043478260869565216}"],
  ["sin(2) 3", "{\"parseNumber\":2.727892280477045,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"realValue\":2.727892280477045,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":2.727892280477045,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":2.727892280477045,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"grapherFnsOnlyValue\":2.727892280477045}"],
  ["sin(2)·3", "{\"parseNumber\":2.727892280477045,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"realValue\":2.727892280477045,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":2.727892280477045,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":2.727892280477045,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"grapherFnsOnlyValue\":2.727892280477045}"],
  ["sin 2·3", "{\"parseNumber\":2.727892280477045,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"realValue\":2.727892280477045,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":2.727892280477045,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":2.727892280477045,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"grapherFnsOnlyValue\":2.727892280477045}"],
  ["sin 2 * 3", "{\"parseNumber\":2.727892280477045,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"realValue\":2.727892280477045,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":2.727892280477045,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":2.727892280477045,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"grapherFnsOnlyValue\":2.727892280477045}"],
  ["3 sin 2", "{\"parseNumber\":2.727892280477045,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":3},\"b\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}}},\"vars\":[]},\"realValue\":2.727892280477045,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":3},\"b\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}}},\"vars\":[]},\"complexValue\":{\"re\":2.727892280477045,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":2.727892280477045,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":3},\"b\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}}},\"vars\":[]},\"grapherFnsOnlyValue\":2.727892280477045}"],
  ["2 sin x", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":6,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":6,\"reason\":\"unknown-identifier\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":6,\"reason\":\"unknown-identifier\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"var\",\"name\":\"x\"}}},\"vars\":[\"x\"]},\"grapherFnsOnlyValue\":1.288435374475382}"],
  ["sin x cos t", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":4,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":4,\"reason\":\"unknown-identifier\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":4,\"reason\":\"unknown-identifier\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"var\",\"name\":\"x\"}},\"b\":{\"t\":\"call\",\"fn\":\"cos\",\"a\":{\"t\":\"var\",\"name\":\"t\"}}},\"vars\":[\"x\",\"t\"]},\"grapherFnsOnlyValue\":0.1723274767153231}"],
  ["sin x", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":4,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":4,\"reason\":\"unknown-identifier\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":4,\"reason\":\"unknown-identifier\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"var\",\"name\":\"x\"}},\"vars\":[\"x\"]},\"grapherFnsOnlyValue\":0.644217687237691}"],
  ["sin(2x)", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":5,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":5,\"reason\":\"unknown-identifier\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":5,\"reason\":\"unknown-identifier\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"var\",\"name\":\"x\"}}},\"vars\":[\"x\"]},\"grapherFnsOnlyValue\":0.9854497299884601}"],
  ["sin pi/2", "{\"parseNumber\":null,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":6.123233995736766e-17,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":6.123233995736766e-17,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":6.123233995736766e-17,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":6.123233995736766e-17}"],
  ["sqrt 2", "{\"parseNumber\":1.4142135623730951,\"real\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":1.4142135623730951,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":1.4142135623730951,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":1.4142135623730951,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":1.4142135623730951}"],
  ["sqrt 2 3", "{\"parseNumber\":4.795831523312719,\"real\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":23}},\"vars\":[]},\"realValue\":4.795831523312719,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":4.242640687119286,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":4.242640687119286,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":23}},\"vars\":[]},\"grapherFnsOnlyValue\":4.795831523312719}"],
  ["√2", "{\"parseNumber\":1.4142135623730951,\"real\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":1.4142135623730951,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":1.4142135623730951,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":1.4142135623730951,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":1.4142135623730951}"],
  ["√2 3", "{\"parseNumber\":4.795831523312719,\"real\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":23}},\"vars\":[]},\"realValue\":4.795831523312719,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":4.242640687119286,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":4.242640687119286,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":23}},\"vars\":[]},\"grapherFnsOnlyValue\":4.795831523312719}"],
  ["√2x", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":2,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":2,\"reason\":\"unknown-identifier\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":2,\"reason\":\"unknown-identifier\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"var\",\"name\":\"x\"}},\"vars\":[\"x\"]},\"grapherFnsOnlyValue\":0.9899494936611666}"],
  ["√2/2", "{\"parseNumber\":0.7071067811865476,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":0.7071067811865476,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":0.7071067811865476,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.7071067811865476,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":0.7071067811865476}"],
  ["3√2", "{\"parseNumber\":4.242640687119286,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":3},\"b\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}}},\"vars\":[]},\"realValue\":4.242640687119286,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":3},\"b\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}}},\"vars\":[]},\"complexValue\":{\"re\":4.242640687119286,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":4.242640687119286,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":3},\"b\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}}},\"vars\":[]},\"grapherFnsOnlyValue\":4.242640687119286}"],
  ["sqrt pi", "{\"parseNumber\":null,\"real\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"realValue\":1.7724538509055159,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"complexValue\":{\"re\":1.7724538509055159,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":1.7724538509055159,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"grapherFnsOnlyValue\":1.7724538509055159}"],
  ["sin pi", "{\"parseNumber\":null,\"real\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"realValue\":1.2246467991473532e-16,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"complexValue\":{\"re\":1.2246467991473532e-16,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":1.2246467991473532e-16,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"grapherFnsOnlyValue\":1.2246467991473532e-16}"],
  ["ln 2 3", "{\"parseNumber\":3.1354942159291497,\"real\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"ln\",\"a\":{\"t\":\"num\",\"v\":23}},\"vars\":[]},\"realValue\":3.1354942159291497,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"ln\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":2.0794415416798357,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":2.0794415416798357,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"ln\",\"a\":{\"t\":\"num\",\"v\":23}},\"vars\":[]},\"grapherFnsOnlyValue\":3.1354942159291497}"],
  ["e^2 3", "{\"parseNumber\":9744803446.24889,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"const\",\"name\":\"e\"},\"b\":{\"t\":\"num\",\"v\":23}},\"vars\":[]},\"realValue\":9744803446.24889,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"const\",\"name\":\"e\"},\"b\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":22.16716829679195,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":22.16716829679195,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"const\",\"name\":\"e\"},\"b\":{\"t\":\"num\",\"v\":23}},\"vars\":[]},\"grapherFnsOnlyValue\":9744803446.24889}"],
  ["e^(i pi)", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":3,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"const\",\"name\":\"e\"},\"b\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"i\"},\"b\":{\"t\":\"const\",\"name\":\"pi\"}}},\"vars\":[]},\"complexValue\":{\"re\":-1,\"im\":1.2246467991473532e-16},\"cell\":\"=complex\",\"matrix\":{\"re\":-1,\"im\":1.2246467991473532e-16},\"grapherFnsOnly\":{\"ok\":false,\"pos\":3,\"reason\":\"unknown-identifier\"},\"grapherFnsOnlyValue\":null}"],
  ["i pi", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":0,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"i\"},\"b\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"complexValue\":{\"re\":0,\"im\":3.141592653589793},\"cell\":\"=complex\",\"matrix\":{\"re\":0,\"im\":3.141592653589793},\"grapherFnsOnly\":{\"ok\":false,\"pos\":0,\"reason\":\"unknown-identifier\"},\"grapherFnsOnlyValue\":null}"],
  ["2 i", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":2,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"i\"}},\"vars\":[]},\"complexValue\":{\"re\":0,\"im\":2},\"cell\":\"=complex\",\"matrix\":{\"re\":0,\"im\":2},\"grapherFnsOnly\":{\"ok\":false,\"pos\":2,\"reason\":\"unknown-identifier\"},\"grapherFnsOnlyValue\":null}"],
  ["1 2i", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":3,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"i\"}},\"vars\":[]},\"complexValue\":{\"re\":0,\"im\":2},\"cell\":\"=complex\",\"matrix\":{\"re\":0,\"im\":2},\"grapherFnsOnly\":{\"ok\":false,\"pos\":3,\"reason\":\"unknown-identifier\"},\"grapherFnsOnlyValue\":null}"],
  ["1+2i", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":3,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"+\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"i\"}}},\"vars\":[]},\"complexValue\":{\"re\":1,\"im\":2},\"cell\":\"=complex\",\"matrix\":{\"re\":1,\"im\":2},\"grapherFnsOnly\":{\"ok\":false,\"pos\":3,\"reason\":\"unknown-identifier\"},\"grapherFnsOnlyValue\":null}"],
  ["sin 2i", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":5,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"b\":{\"t\":\"i\"}},\"vars\":[]},\"complexValue\":{\"re\":0,\"im\":0.9092974268256817},\"cell\":\"=complex\",\"matrix\":{\"re\":0,\"im\":0.9092974268256817},\"grapherFnsOnly\":{\"ok\":false,\"pos\":5,\"reason\":\"unknown-identifier\"},\"grapherFnsOnlyValue\":null}"],
  ["exp i pi", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":4,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"exp\",\"a\":{\"t\":\"i\"}},\"b\":{\"t\":\"const\",\"name\":\"pi\"}},\"vars\":[]},\"complexValue\":{\"re\":1.6974097548329732,\"im\":2.643559064081456},\"cell\":\"=complex\",\"matrix\":{\"re\":1.6974097548329732,\"im\":2.643559064081456},\"grapherFnsOnly\":{\"ok\":false,\"pos\":4,\"reason\":\"unknown-identifier\"},\"grapherFnsOnlyValue\":null}"],
  ["pi 2", "{\"parseNumber\":6.283185307179586,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"const\",\"name\":\"pi\"},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":6.283185307179586,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"const\",\"name\":\"pi\"},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":6.283185307179586,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":6.283185307179586,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"const\",\"name\":\"pi\"},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":6.283185307179586}"],
  ["ħ 2", "{\"parseNumber\":2,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"const\",\"name\":\"hbar\"},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":2,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"const\",\"name\":\"hbar\"},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":2,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":2,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"const\",\"name\":\"hbar\"},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":2}"],
  ["hbar/2", "{\"parseNumber\":0.5,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"const\",\"name\":\"hbar\"},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":0.5,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"const\",\"name\":\"hbar\"},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":0.5,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.5,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"const\",\"name\":\"hbar\"},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":0.5}"],
  ["0.5 0.5", "{\"parseNumber\":0.25,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":0.5},\"b\":{\"t\":\"num\",\"v\":0.5}},\"vars\":[]},\"realValue\":0.25,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":0.5},\"b\":{\"t\":\"num\",\"v\":0.5}},\"vars\":[]},\"complexValue\":{\"re\":0.25,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.25,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":0.5},\"b\":{\"t\":\"num\",\"v\":0.5}},\"vars\":[]},\"grapherFnsOnlyValue\":0.25}"],
  [".5 .5", "{\"parseNumber\":0.25,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":0.5},\"b\":{\"t\":\"num\",\"v\":0.5}},\"vars\":[]},\"realValue\":0.25,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":0.5},\"b\":{\"t\":\"num\",\"v\":0.5}},\"vars\":[]},\"complexValue\":{\"re\":0.25,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.25,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":0.5},\"b\":{\"t\":\"num\",\"v\":0.5}},\"vars\":[]},\"grapherFnsOnlyValue\":0.25}"],
  ["1.5 2", "{\"parseNumber\":1.52,\"real\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":1.52},\"vars\":[]},\"realValue\":1.52,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"num\",\"v\":1.5},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":3,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":3,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":1.52},\"vars\":[]},\"grapherFnsOnlyValue\":1.52}"],
  ["−1 2", "{\"parseNumber\":-12,\"real\":{\"ok\":true,\"ast\":{\"t\":\"neg\",\"a\":{\"t\":\"num\",\"v\":12}},\"vars\":[]},\"realValue\":-12,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"neg\",\"a\":{\"t\":\"num\",\"v\":1}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":-2,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":-2,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"neg\",\"a\":{\"t\":\"num\",\"v\":12}},\"vars\":[]},\"grapherFnsOnlyValue\":-12}"],
  ["3 ÷ 4 × 2", "{\"parseNumber\":1.5,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":3},\"b\":{\"t\":\"num\",\"v\":4}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":1.5,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":3},\"b\":{\"t\":\"num\",\"v\":4}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":1.5,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":1.5,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":3},\"b\":{\"t\":\"num\",\"v\":4}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":1.5}"],
  [" 12 ", "{\"parseNumber\":12,\"real\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":12},\"vars\":[]},\"realValue\":12,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":12},\"vars\":[]},\"complexValue\":{\"re\":12,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":12,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":12},\"vars\":[]},\"grapherFnsOnlyValue\":12}"],
  ["-2^2", "{\"parseNumber\":-4,\"real\":{\"ok\":true,\"ast\":{\"t\":\"neg\",\"a\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":2}}},\"vars\":[]},\"realValue\":-4,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"neg\",\"a\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":2}}},\"vars\":[]},\"complexValue\":{\"re\":-4,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":-4,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"neg\",\"a\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"num\",\"v\":2}}},\"vars\":[]},\"grapherFnsOnlyValue\":-4}"],
  ["2^-1", "{\"parseNumber\":0.5,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"neg\",\"a\":{\"t\":\"num\",\"v\":1}}},\"vars\":[]},\"realValue\":0.5,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"neg\",\"a\":{\"t\":\"num\",\"v\":1}}},\"vars\":[]},\"complexValue\":{\"re\":0.5,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.5,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"num\",\"v\":2},\"b\":{\"t\":\"neg\",\"a\":{\"t\":\"num\",\"v\":1}}},\"vars\":[]},\"grapherFnsOnlyValue\":0.5}"],
  ["abs -2", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":4,\"reason\":\"syntax\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":4,\"reason\":\"syntax\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":4,\"reason\":\"syntax\"},\"grapherFnsOnly\":{\"ok\":false,\"pos\":4,\"reason\":\"syntax\"},\"grapherFnsOnlyValue\":null}"],
  ["abs(-2) 3", "{\"parseNumber\":6,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"abs\",\"a\":{\"t\":\"neg\",\"a\":{\"t\":\"num\",\"v\":2}}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"realValue\":6,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"abs\",\"a\":{\"t\":\"neg\",\"a\":{\"t\":\"num\",\"v\":2}}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":6,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":6,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"*\",\"a\":{\"t\":\"call\",\"fn\":\"abs\",\"a\":{\"t\":\"neg\",\"a\":{\"t\":\"num\",\"v\":2}}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"grapherFnsOnlyValue\":6}"],
  ["cos(0)^2", "{\"parseNumber\":1,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"call\",\"fn\":\"cos\",\"a\":{\"t\":\"num\",\"v\":0}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":1,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"call\",\"fn\":\"cos\",\"a\":{\"t\":\"num\",\"v\":0}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":1,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":1,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"call\",\"fn\":\"cos\",\"a\":{\"t\":\"num\",\"v\":0}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":1}"],
  ["√4^3", "{\"parseNumber\":8,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":4}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"realValue\":8,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":4}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"complexValue\":{\"re\":8,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":8,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":4}},\"b\":{\"t\":\"num\",\"v\":3}},\"vars\":[]},\"grapherFnsOnlyValue\":8}"],
  ["PI", "{\"parseNumber\":3.141592653589793,\"real\":{\"ok\":true,\"ast\":{\"t\":\"const\",\"name\":\"pi\"},\"vars\":[]},\"realValue\":3.141592653589793,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"const\",\"name\":\"pi\"},\"vars\":[]},\"complexValue\":{\"re\":3.141592653589793,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":3.141592653589793,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"const\",\"name\":\"pi\"},\"vars\":[]},\"grapherFnsOnlyValue\":3.141592653589793}"],
  ["SIN 2", "{\"parseNumber\":0.9092974268256817,\"real\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":0.9092974268256817,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":0.9092974268256817,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.9092974268256817,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"sin\",\"a\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":0.9092974268256817}"],
  ["1/(1/0)", "{\"parseNumber\":0,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"num\",\"v\":0}}},\"vars\":[]},\"realValue\":\"#NaN\",\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"num\",\"v\":0}}},\"vars\":[]},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":0,\"reason\":\"non-finite\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"num\",\"v\":0}}},\"vars\":[]},\"grapherFnsOnlyValue\":\"#NaN\"}"],
  ["(1+2", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":4,\"reason\":\"unexpected-end\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":4,\"reason\":\"unexpected-end\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":4,\"reason\":\"unexpected-end\"},\"grapherFnsOnly\":{\"ok\":false,\"pos\":4,\"reason\":\"unexpected-end\"},\"grapherFnsOnlyValue\":null}"],
  ["", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":0,\"reason\":\"empty\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":0,\"reason\":\"empty\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":0,\"reason\":\"empty\"},\"grapherFnsOnly\":{\"ok\":false,\"pos\":0,\"reason\":\"empty\"},\"grapherFnsOnlyValue\":null}"],
  ["  ", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":0,\"reason\":\"empty\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":0,\"reason\":\"empty\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":0,\"reason\":\"empty\"},\"grapherFnsOnly\":{\"ok\":false,\"pos\":0,\"reason\":\"empty\"},\"grapherFnsOnlyValue\":null}"],
  ["2 $", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":2,\"reason\":\"bad-char\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":2,\"reason\":\"bad-char\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":2,\"reason\":\"bad-char\"},\"grapherFnsOnly\":{\"ok\":false,\"pos\":2,\"reason\":\"bad-char\"},\"grapherFnsOnlyValue\":null}"],
  ["asin 1", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":0,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":0,\"reason\":\"unknown-identifier\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":0,\"reason\":\"unknown-identifier\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"asin\",\"a\":{\"t\":\"num\",\"v\":1}},\"vars\":[]},\"grapherFnsOnlyValue\":1.5707963267948966}"],
  ["tanh 1", "{\"parseNumber\":null,\"real\":{\"ok\":false,\"pos\":0,\"reason\":\"unknown-identifier\"},\"realValue\":null,\"complex\":{\"ok\":false,\"pos\":0,\"reason\":\"unknown-identifier\"},\"complexValue\":null,\"cell\":\"=complex\",\"matrix\":{\"ok\":false,\"cell\":[0,0],\"pos\":0,\"reason\":\"unknown-identifier\"},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"call\",\"fn\":\"tanh\",\"a\":{\"t\":\"num\",\"v\":1}},\"vars\":[]},\"grapherFnsOnlyValue\":0.7615941559557649}"],
  ["e", "{\"parseNumber\":2.718281828459045,\"real\":{\"ok\":true,\"ast\":{\"t\":\"const\",\"name\":\"e\"},\"vars\":[]},\"realValue\":2.718281828459045,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"const\",\"name\":\"e\"},\"vars\":[]},\"complexValue\":{\"re\":2.718281828459045,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":2.718281828459045,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"const\",\"name\":\"e\"},\"vars\":[]},\"grapherFnsOnlyValue\":2.718281828459045}"],
  ["cos(pi/8)^2", "{\"parseNumber\":0.8535533905932737,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"call\",\"fn\":\"cos\",\"a\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"const\",\"name\":\"pi\"},\"b\":{\"t\":\"num\",\"v\":8}}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"realValue\":0.8535533905932737,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"call\",\"fn\":\"cos\",\"a\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"const\",\"name\":\"pi\"},\"b\":{\"t\":\"num\",\"v\":8}}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"complexValue\":{\"re\":0.8535533905932737,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.8535533905932737,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"^\",\"a\":{\"t\":\"call\",\"fn\":\"cos\",\"a\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"const\",\"name\":\"pi\"},\"b\":{\"t\":\"num\",\"v\":8}}},\"b\":{\"t\":\"num\",\"v\":2}},\"vars\":[]},\"grapherFnsOnlyValue\":0.8535533905932737}"],
  ["1/sqrt2", "{\"parseNumber\":0.7071067811865475,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}}},\"vars\":[]},\"realValue\":0.7071067811865475,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}}},\"vars\":[]},\"complexValue\":{\"re\":0.7071067811865475,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.7071067811865475,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":1},\"b\":{\"t\":\"call\",\"fn\":\"sqrt\",\"a\":{\"t\":\"num\",\"v\":2}}},\"vars\":[]},\"grapherFnsOnlyValue\":0.7071067811865475}"],
  ["ħ/4", "{\"parseNumber\":0.25,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"const\",\"name\":\"hbar\"},\"b\":{\"t\":\"num\",\"v\":4}},\"vars\":[]},\"realValue\":0.25,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"const\",\"name\":\"hbar\"},\"b\":{\"t\":\"num\",\"v\":4}},\"vars\":[]},\"complexValue\":{\"re\":0.25,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.25,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"const\",\"name\":\"hbar\"},\"b\":{\"t\":\"num\",\"v\":4}},\"vars\":[]},\"grapherFnsOnlyValue\":0.25}"],
  ["3/4", "{\"parseNumber\":0.75,\"real\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":3},\"b\":{\"t\":\"num\",\"v\":4}},\"vars\":[]},\"realValue\":0.75,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":3},\"b\":{\"t\":\"num\",\"v\":4}},\"vars\":[]},\"complexValue\":{\"re\":0.75,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.75,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"bin\",\"op\":\"/\",\"a\":{\"t\":\"num\",\"v\":3},\"b\":{\"t\":\"num\",\"v\":4}},\"vars\":[]},\"grapherFnsOnlyValue\":0.75}"],
  ["0.75", "{\"parseNumber\":0.75,\"real\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":0.75},\"vars\":[]},\"realValue\":0.75,\"complex\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":0.75},\"vars\":[]},\"complexValue\":{\"re\":0.75,\"im\":0},\"cell\":\"=complex\",\"matrix\":{\"re\":0.75,\"im\":0},\"grapherFnsOnly\":{\"ok\":true,\"ast\":{\"t\":\"num\",\"v\":0.75},\"vars\":[]},\"grapherFnsOnlyValue\":0.75}"],
]

describe('answer mode is unchanged by the grapher grammar (review #1)', () => {
  it('the table covers the inputs the review names ("2 3", "1 / 2", "sin 2x", "cos pi t", "x^2 3")', () => {
    const inputs = TABLE.map(([s]) => s)
    for (const s of ['2 3', '1 / 2', 'sin 2x', 'cos pi t', 'x^2 3']) expect(inputs).toContain(s)
    expect(new Set(inputs).size).toBe(inputs.length)
    expect(inputs).toEqual([...INPUTS])
  })
  it.each(TABLE)('%j reads exactly as before', (src, want) => {
    expect(row(src)).toBe(want)
  })
})
